---
# ANE
ansible_nas_app_name: "magnetico"
magnetico_enabled: false
magnetico_traefik_enabled: false
magnetico_traefik_whitelist: "{{ lan }}"

magnetico_data_directory: "{{ docker_home }}/magnetico"

# network
magnetico_hostname: "magnetico"
magnetico_port_http: "9017"

# docker
# This repository was archived by the owner on Jan 20, 2022. It is now read-only.
magnetico_container_name: "magnetico"
magnetico_image_name: "boramalper/magneticow"
magnetico_image_tag: "latest"
magneticod_container_name: "magnetico-crawler"
magneticod_image_name: "boramalper/magneticod"
magneticod_image_tag: "latest"

# specs
magneticod_cpu_shares: 1024
magneticod_memory: "1G"
magneticod_memory_swap: -1
magnetico_cpu_shares: 1024
magnetico_memory: "1G"
magnetico_memory_swap: -1

# app
magnetico_username: "{{ ansible_nas_user }}"
magnetico_password: "{{ ansible_nas_app_admin_password }}"

# autoheal
magneticod_autoheal_enabled: false
magnetico_autoheal_enabled: false

# dockflare
magnetico_dockflare_enabled: false
magnetico_dockflare_access_group: ""

# homepage
magnetico_homepage_group: "Apps"
magnetico_homepage_icon: "mdi-magnet-on"
magnetico_homepage_href: "http://{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}:{{ magnetico_port_http }}"
magnetico_homepage_showstats: false
magneticod_homepage_group: "Misc"
magneticod_homepage_showstats: false

# repliqate
magnetico_repliqate_enabled: false
magnetico_repliqate_engine: "restic"
magnetico_repliqate_schedule: "@daily 3am"
magnetico_repliqate_backup_id: "{{ magnetico_container_name }}"
magnetico_repliqate_retention: "30d"
magneticod_repliqate_enabled: false
magneticod_repliqate_engine: "restic"
magneticod_repliqate_schedule: "@daily 3am"
magneticod_repliqate_backup_id: "{{ magneticod_container_name }}"
magneticod_repliqate_retention: "30d"

# tinyauth
magnetico_tinyauth_enabled: false

# watchtower
magnetico_watchtower_enabled: false