---
ansible_nas_app_name: "magnetico"

#
magnetico_enabled: false
magnetico_available_externally: false
magnetico_traefik_whitelist: "{{ lan }}"

magnetico_data_directory: "{{ docker_home }}/magnetico"

# network
magnetico_hostname: "magnetico"
magnetico_port_http: "8092"

# docker
magneticod_container_name: "magneticod"
magneticod_image_name: "boramalper/magneticod"
magneticod_image_tag: "latest"
magneticod_cpu_shares: "1024"
magneticod_memory: "1g"
magneticow_container_name: "magneticow"
magneticow_image_name: "boramalper/magneticow"
magneticow_image_tag: "latest"
magneticow_cpu_shares: "1024"
magneticow_memory: "1g"

# autoheal
magneticod_autoheal: "false"
magneticow_autoheal: "false"

# homepage
magnetico_homepage_group: "Apps"
magnetico_homepage_icon: "magnetico.png"
magnetico_homepage_href: "http://{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}:{{ magnetico_port_http }}"
magnetico_homepage_showStats: "false"
magneticod_homepage_group: "Apps"
magneticod_homepage_icon: "magnetico.png"
magneticod_homepage_showStats: "false"

# watchtower
magnetico_watchtower_monitor_only: "true"