---
# ANE
ansible_nas_app_name: "Stash"
stash_enabled: false
stash_available_externally: false
stash_traefik_whitelist: "{{ lan }}"
stash_data_directory: "{{ docker_home }}/stash"

# network
stash_hostname: "stash"
stash_port_http: "9998"

stash_user_id: "0"
stash_group_id: "0"

# docker
stash_container_name: "stash"
stash_image_name: "stashapp/stash"
stash_image_tag: "latest"
stash_cpu_shares: "1024"
stash_memory: "1g"

# autoheal
stash_autoheal: "false"

# dockflare
stash_dockflare_tunnel: "false"
stash_dockflare_access_group: ""

# homepage
stash_homepage_group: "Apps"
stash_homepage_icon: "stash.png"
stash_homepage_href: "http://{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}:{{ stash_port_http }}"
stash_homepage_showStats: "false"
stash_homepage_widget_key: "your api key"
stash_homepage_widget_fields: '["scenes", "images"]' # optional - default fields shown

# watchtower
stash_watchtower_monitor_only: "true"