---
# ANE
webmin_usermin_proper_name: "Webmin/Usermin"
usermin_enabled: false
webmin_enabled: false

###
### BELOW for info and possible homepage future integration
###

# network
usermin_port_http: "20000"
webmin_port_http: "10000"

# dockflare
usermin_dockflare_enabled: false
usermin_dockflare_access_group: ""
webmin_dockflare_enabled: false
webmin_dockflare_access_group: ""

# homepage
usermin_homepage_group: "Apps"
usermin_homepage_icon: "usermin.png"
usermin_homepage_href: "http://{{ hostvars[inventory_hostname]['ansible_facts']['default_ipv4']['address'] }}:{{ usermin_port_http }}"
webmin_homepage_group: "Apps"
webmin_homepage_icon: "webmin.png"
webmin_homepage_href: "http://{{ hostvars[inventory_hostname]['ansible_facts']['default_ipv4']['address'] }}:{{ webmin_port_http }}"
