---
# ANE
ansible_nas_app_name: "Readarr"
readarr_enabled: false
readarr_available_externally: false
readarr_traefik_whitelist: "{{ lan }}"

# directories
readarr_data_directory: "{{ docker_home }}/readarr"
readarr_download_directory: "{{ downloads_root }}"
readarr_books_directory: "{{ books_root }}"

# docker
readarr_container_name: "readarr"
readarr_image_name: "lscr.io/linuxserver/readarr"
readarr_image_version: "nightly"
readarr_env_docker_mods: ""

# uid / gid
readarr_user_id: "0"
readarr_group_id: "0"

# network
readarr_hostname: "readarr"
readarr_port: "8787"

# specs
readarr_cpu_shares: 1024
readarr_memory: "1g"

# autoheal
readarr_autoheal: "false"

# dockflare
readarr_dockflare_tunnel: "false"
readarr_dockflare_access_group: ""

# homepage
readarr_homepage_group: "Media Management"
readarr_homepage_icon: "readarr.png"
readarr_homepage_href: "http://{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}:{{ readarr_port }}"
readarr_homepage_showStats: "false"
readarr_homepage_widget_key: "123456789"

# watchtower
readarr_watchtower_monitor_only: "true"