---
- name: Start {{ ansible_nas_app_name }}
  block:
    - name: Create {{ ansible_nas_app_name }} Container
      community.docker.docker_container:
        container_default_behavior: "compatibility"
        name: "{{ dozzle_container_name }}"
        hostname: "{{ dozzle_container_name }}"
        image: "{{ dozzle_image_name }}:{{ dozzle_image_tag }}"
        pull: true
        ports:
          - "{{ dozzle_port_http }}:8080"
        volumes:
          - "/var/run/docker.sock:/var/run/docker.sock"
          - "/etc/timezone:/etc/timezone:ro"
        env:
          TZ: "{{ ansible_nas_timezone }}"
        labels:
          autoheal: "{{ dozzle_autoheal }}"
          com.centurylinklabs.watchtower.monitor-only: "{{ dozzle_watchtower_monitor_only }}"
          dockflare.enable: "{{ dozzle_dockflare_tunnel }}"
          dockflare.access.group: "{{ dozzle_dockflare_access_group }}"
          dockflare.hostname: "{{ dozzle_hostname }}.{{ ansible_nas_domain }}"
          dockflare.service: "http://{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}:{{ dozzle_port_http }}"
          homepage.name: "{{ ansible_nas_app_name }}"
          homepage.group: "{{ dozzle_homepage_group }}"
          homepage.icon: "{{ dozzle_homepage_icon }}"
          homepage.href: "{{ dozzle_homepage_href }}"
          homepage.siteMonitor: "http://{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}:{{ dozzle_port_http }}"
          homepage.description: "{{ 'Realtime log viewer for docker containers.' if homepage_show_description else omit }}"
          homepage.server: "my-docker"
          homepage.container: "{{ dozzle_container_name }}"
          homepage.showStats: "{{ dozzle_homepage_showStats }}"
          traefik.enable: "{{ dozzle_available_externally | string }}"
          traefik.http.routers.dozzle.rule: "Host(`{{ dozzle_hostname }}.{{ ansible_nas_domain }}`)"
          traefik.http.routers.dozzle.tls.certresolver: "letsencrypt"
          traefik.http.routers.dozzle.tls.domains[0].main: "{{ ansible_nas_domain }}"
          traefik.http.routers.dozzle.tls.domains[0].sans: "*.{{ ansible_nas_domain }}"
          traefik.http.routers.frontend.middlewares: "{{ dozzle_hostname }}"
          traefik.http.routers.dozzle.middlewares: "{{ dozzle_hostname }}@docker"
          traefik.http.middlewares.dozzle.IPAllowList.sourcerange: "{{ dozzle_traefik_whitelist }}"
          traefik.http.services.dozzle.loadbalancer.server.port: "8080"
          wud.tag.include: '^\d+\.\d+\.\d+.*$'
          wud.tag.transform.type: "semver"
          wud.link.template: "https://hub.docker.com/r/amir20/dozzle"
        cpu_shares: "{{ dozzle_cpu_shares }}"
        memory: "{{ dozzle_memory }}"
        restart_policy: unless-stopped
  when: dozzle_enabled is true

- name: Stop {{ ansible_nas_app_name }}
  block:
    - name: Stop {{ ansible_nas_app_name }} Container
      community.docker.docker_container:
        name: "{{ dozzle_container_name }}"
        state: absent
  when: dozzle_enabled is false