---
# ANE
ansible_nas_app_name: "Minecraft Bedrock Server"
minecraft_bedrock_server_enabled: false
minecraft_bedrock_server_data_directory: "{{ docker_home }}/minecraft-bedrock-server"

# network
minecraft_bedrock_server_port: "19132"

# docker
minecraft_bedrock_server_container_name: "minecraft-bedrock-server"
minecraft_bedrock_server_image: "ghcr.io/itzg/minecraft-bedrock-server"
minecraft_bedrock_server_image_tag: "latest"

# specs
minecraft_bedrock_server_cpu_shares: 1024
minecraft_bedrock_server_memory: "1024M"

# minecraft settings
minecraft_bedrock_server_name: "ANE Minecraft Server"
minecraft_bedrock_server_game_mode: "creative"
minecraft_bedrock_server_difficulty: "normal"
minecraft_bedrock_server_online_mode: "false"
minecraft_bedrock_server_ops: "" # csv list of server ops xuids
minecraft_bedrock_server_members: "" # csv list of server members
minecraft_bedrock_server_visitors: "" # csv list of server visitors

# autoheal
minecraft_bedrock_server_autoheal: "false"

# homepage
minecraft_bedrock_server_homepage_group: "Misc"
minecraft_bedrock_server_homepage_icon: "minecraft.png"
minecraft_bedrock_server_homepage_showstats: "false"

# repliqate
minecraft_bedrock_server_repliqate_enabled: "false"
minecraft_bedrock_server_repliqate_engine: "restic"
minecraft_bedrock_server_repliqate_schedule: "@daily 3am"
minecraft_bedrock_server_repliqate_backup_id: "{{ minecraft_bedrock_container_name }}"
minecraft_bedrock_server_repliqate_retention: "30d"

# watchtower
minecraft_bedrock_server_watchtower_enable: "false"