---
- name: Start {{ ansible_nas_app_name }}
  block:
    - name: Create {{ ansible_nas_app_name }} Directories
      file:
        path: "{{ item }}"
        state: directory
        owner: "1001"
      with_items:
        - "{{ osclass_data_directory }}"
        - "{{ osclass_data_directory }}/data"
        - "{{ osclass_data_directory }}/db"

    - name: Create {{ ansible_nas_app_name }} DB Container
      community.docker.docker_container:
        container_default_behavior: "compatibility"
        name: "{{ osclass_db_container_name }}"
        hostname: "{{ osclass_db_container_name }}"
        image: "{{ osclass_db_image_name }}:{{ osclass_db_image_tag }}"
        pull: true
        network_mode: "bridge"
        networks_cli_compatible: "yes"
        volumes:
          - "{{ osclass_data_directory }}/db:/bitnami/mariadb"
#         - "{{ osclass_data_directory }}/db:/var/lib/mysql"
        env:
          ALLOW_EMPTY_PASSWORD: "no"
          MARIADB_ROOT_PASSWORD: "Ansible-NAS"
          MARIADB_USER: "osclass"
          MARIADB_PASSWORD: "bitnami"
          MARIADB_DATABASE: "osclass_db"
          TZ: "{{ ansible_nas_timezone }}"
        labels:
          autoheal: "{{ osclass_db_autoheal }}"
          com.centurylinklabs.watchtower.monitor-only: "{{ osclass_db_watchtower_monitor_only }}"
          dockflare.enable: "false"
          homepage.name: "{{ ansible_nas_app_name }} MariaDB"
          homepage.group: "{{ osclass_db_homepage_group }}"
          homepage.icon: "{{ osclass_db_homepage_icon }}"
          homepage.href: "{{ osclass_homepage_href }}"
          homepage.description: "{{ 'MariaDB Server is a high performing open source relational database, forked from MySQL.' if homepage_show_description else omit }}"
          homepage.server: "my-docker"
          homepage.container: "{{ osclass_db_container_name }}"
          homepage.showStats: "{{ osclass_db_homepage_showStats }}"
          traefik.enable: "false"
          wud.tag.include: '^\d+\.\d+\.\d+$'
          wud.link.template: "https://mariadb.com/kb/en/mariadb-$${major}$${minor}$${patch}-changelog"
        cpu_shares: "{{ osclass_db_cpu_shares }}"
        memory: "{{ osclass_db_memory }}"
        restart_policy: unless-stopped

    - name: Create {{ ansible_nas_app_name }} Container
      community.docker.docker_container:
        container_default_behavior: "compatibility"
        name: "{{ osclass_container_name }}"
        hostname: "{{ osclass_container_name }}"
        image: "{{ osclass_image_name }}:{{ osclass_image_tag }}"
        pull: true
        network_mode: "bridge"
        networks_cli_compatible: "yes"
        volumes:
          - "{{ osclass_data_directory }}/data:/bitnami/osclass"
        ports:
          - "{{ osclass_port_http }}:8080"
        env:
          ALLOW_EMPTY_PASSWORD: "no"
          OSCLASS_DATABASE_USER: "{{ osclass_database_user }}"
          OSCLASS_DATABASE_PASSWORD: "{{ osclass_database_password }}"
          OSCLASS_DATABASE_NAME: "osclass_db"
          OSCLASS_DATABASE_HOST: "{{ osclass_db_container_name }}"
          OSCLASS_DATABASE_PORT_NUMBER: "3306"
          OSCLASS_EMAIL: "{{ osclass_email }}"
          OSCLASS_SMTP_HOST: "{{ osclass_smtp_host }}"
          OSCLASS_SMTP_PORT: "{{ osclass_smtp_port }}"
          OSCLASS_SMTP_USER: "{{ osclass_smtp_user }}"
          OSCLASS_SMTP_PASSWORD: " {{ osclass_smtp_password }}"
          OSCLASS_USERNAME: "{{ osclass_admin_username }}"
          OSCLASS_PASSWORD: "{{ osclass_admin_password }}"
          OSCLASS_WEB_TITLE: "{{ osclass_hostname }}.{{ ansible_nas_domain }}"
          TZ: "{{ ansible_nas_timezone }}"
        links:
          - "{{ osclass_db_container_name }}"
        labels:
          autoheal: "{{ osclass_autoheal }}"
          com.centurylinklabs.watchtower.monitor-only: "{{ osclass_watchtower_monitor_only }}"
          dockflare.enable: "{{ osclass_dockflare_tunnel }}"
          dockflare.access.group: "{{ osclass_dockflare_access_group }}"
          dockflare.hostname: "{{ osclass_hostname }}.{{ ansible_nas_domain }}"
          dockflare.service: "http://{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}:{{ osclass_port_http }}"
          homepage.name: "{{ ansible_nas_app_name }}"
          homepage.group: "{{ osclass_homepage_group }}"
          homepage.icon: "{{ osclass_homepage_icon }}"
          homepage.href: "{{ osclass_homepage_href }}"
          homepage.siteMonitor: "http://{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}:{{ osclass_port_http }}"
          homepage.description: "{{ 'classifieds' if homepage_show_description else omit }}"
          homepage.server: "my-docker"
          homepage.container: "{{ osclass_container_name }}"
          homepage.showStats: "{{ osclass_homepage_showStats }}"
          traefik.enable: "{{ osclass_available_externally | string }}"
#         traefik.http.routers.osclass.rule: "Host(`{{ osclass_hostname }}.{{ ansible_nas_domain }}`)"
          traefik.http.routers.osclass.rule: "Host(`classifieds.{{ ansible_nas_domain }}`)"
          traefik.http.routers.osclass.tls.certresolver: "letsencrypt"
          traefik.http.routers.osclass.tls.domains[0].main: "{{ ansible_nas_domain }}"
          traefik.http.routers.osclass.tls.domains[0].sans: "*.{{ ansible_nas_domain }}"
          traefik.http.routers.frontend.middlewares: "{{ osclass_hostname }}"
          traefik.http.routers.osclass.middlewares: "osclass@docker"
          traefik.http.middlewares.osclass.IPAllowList.sourcerange: "{{ osclass_traefik_whitelist }}"
          traefik.http.services.osclass.loadbalancer.server.port: "8080"
          wud.tag.include: '^\d+\.\d+\.\d+$$'
          wud.link.template: "https://hub.docker.com/r/bitnami/osclass-archived/tags/tag/$${major}.$${minor}.$${patch}"
        cpu_shares: "{{ osclass_cpu_shares }}"
        memory: "{{ osclass_memory }}"
        restart_policy: unless-stopped
  when: osclass_enabled is true

- name: Stop {{ ansible_nas_app_name }}
  block:
    - name: Stop {{ ansible_nas_app_name }} Container
      community.docker.docker_container:
        name: "{{ osclass_container_name }}"
        state: absent

    - name: Stop {{ ansible_nas_app_name }} DB Container
      community.docker.docker_container:
        name: "{{ osclass_db_container_name }}"
        state: absent
  when: osclass_enabled is false

- name: Data Archive {{ ansible_nas_app_name }}
  block:
    - name: Check for {{ ansible_nas_app_name }} Data Directory
      stat:
        path: "{{ osclass_data_directory }}"
      register: dir_stat

    - name: Archive {{ ansible_nas_app_name }} Data Directory
      ansible.builtin.archive:
        path: "{{ osclass_data_directory }}"
        dest: "{{ docker_home }}/{{ ansible_nas_app_name | lower }}.zip"
        force_archive: true
        format: zip
        owner: ansible-nas
        group: ansible-nas
        mode: u=rw,g=rw
        remove: true
      when: dir_stat.stat.exists
  when: osclass_enabled is false and archive_app_data_enabled is true


# NOTE:
# Would like to move this from Bitnami's mariadb to linuxserver's mariadb
