---
- name: Start {{ ansible_nas_app_name }}
  block:
    - name: Create {{ ansible_nas_app_name }} Directories
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        # mode: 0755
      with_items:
        - "{{ ispyagentdvr_data_directory }}"
        - "{{ ispyagentdvr_data_directory }}/config"
        - "{{ ispyagentdvr_data_directory }}/commands"
        - "{{ ispyagentdvr_recordings_directory }}"

    - name: Create {{ ansible_nas_app_name }} Container
      community.docker.docker_container:
        container_default_behavior: "compatibility"
        name: "{{ ispyagentdvr_container_name }}"
        hostname: "{{ ispyagentdvr_container_name }}"
        image: "{{ ispyagentdvr_image_name }}:{{ ispyagentdvr_image_tag }}"
        pull: true
        volumes:
          - "{{ ispyagentdvr_data_directory }}/config:/AgentDVR/Media/XML:rw"
          - "{{ ispyagentdvr_data_directory }}/commands:/AgentDVR/Commands:rw"
          - "{{ ispyagentdvr_recordings_directory }}:/AgentDVR/Media/WebServerRoot/Media:rw"
        ports:
          - "{{ ispyagentdvr_webui_port }}:8090"
          - "{{ ispyagentdvr_turn_port }}:3478/udp"
          - "{{ ispyagentdvr_agentdvr_host_port }}:50000-50010/udp"
        env:
          TZ: "{{ ansible_nas_timezone }}"
          WEBUI_PORT: "{{ ispyagentdvr_webui_port }}"
          PUID: "{{ ispyagentdvr_user_id }}"
          PGID: "{{ ispyagentdvr_group_id }}"
        labels:
          autoheal: "{{ ispyagentdvr_autoheal }}"
          com.centurylinklabs.watchtower.enable: "{{ ispyagentdvr_watchtower_enable }}"
          dockflare.enable: "{{ ispyagentdvr_dockflare_tunnel }}"
          dockflare.access.group: "{{ ispyagentdvr_dockflare_access_group }}"
          dockflare.hostname: "{{ ispyagentdvr_hostname }}.{{ ansible_nas_domain }}"
          dockflare.service: "http://{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}:{{ ispyagentdvr_webui_port }}"
          homepage.name: "{{ ansible_nas_app_name }}"
          homepage.group: "{{ ispyagentdvr_homepage_group }}"
          homepage.icon: "{{ ispyagentdvr_homepage_icon }}"
          homepage.href: "{{ ispyagentdvr_homepage_href }}"
          homepage.description: "{{ 'Camera Monitoring software' if homepage_show_description else omit }}"
          homepage.server: "my-docker"
          homepage.container: "{{ ispyagentdvr_container_name }}"
          homepage.showStats: "{{ ispyagentdvr_homepage_showstats }}"
          homepage.siteMonitor: "http://{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}:{{ ispyagentdvr_port }}"
          traefik.enable: "{{ ispyagentdvr_available_externally | string }}"
          traefik.http.routers.ispyagentdvr.rule: "Host(`ispyagentdvr.{{ ansible_nas_domain }}`)"
          traefik.http.routers.ispyagentdvr.tls.certresolver: "letsencrypt"
          traefik.http.routers.ispyagentdvr.tls.domains[0].main: "{{ ansible_nas_domain }}"
          traefik.http.routers.ispyagentdvr.tls.domains[0].sans: "*.{{ ansible_nas_domain }}"
          traefik.http.routers.frontend.middlewares: "{{ ispyagentdvr_hostname }}"
          traefik.http.routers.ispyagentdvr.middlewares: "{{ ispyagentdvr_hostname }}@docker"
          traefik.http.middlewares.ispyagentdvr.IPAllowList.sourcerange: "{{ ispyagentdvr_traefik_whitelist }}"
          traefik.http.services.ispyagentdvr.loadbalancer.server.port: "8097"
          wud.tag.include: '^\d+\.\d+\.\d+\.\d+.*$'
          wud.tag.transform.type: "semver"
          wud.link.template: "https://hub.docker.com/r/mekayelanik/ispyagentdvr"
        cpu_shares: "{{ ispyagentdvr_cpu_shares }}"
        memory: "{{ ispyagentdvr_memory }}"
        restart_policy: unless-stopped

    - name: Access {{ ansible_nas_app_name }} at
      ansible.builtin.debug:
        msg: >-
              {{
                ['http://' + hostvars[inventory_hostname]['ansible_default_ipv4']['address'] + ':' + (ispyagentdvr_webuit_port | string)] +
                (['https://' + ispyagentdvr_hostname + '.' + ansible_nas_domain] if (ispyagentdvr_available_externally is true or ispyagentdvr_dockflare_tunnel is true) else [])
              }}
  when: ispyagentdvr_enabled is true

- name: Stop {{ ansible_nas_app_name }}
  block:
    - name: Stop {{ ansible_nas_app_name }} Container
      community.docker.docker_container:
        name: "{{ ispyagentdvr_container_name }}"
        state: absent
  when: ispyagentdvr_enabled is false

- name: Data Archive {{ ansible_nas_app_name }}
  block:
    - name: Check for {{ ansible_nas_app_name }} Data Directory
      stat:
        path: "{{ ispyagentdvr_data_directory }}"
      register: dir_stat

    - name: Archive {{ ansible_nas_app_name }} Data Directory
      ansible.builtin.archive:
        path: "{{ ispyagentdvr_data_directory }}"
        dest: "{{ docker_home }}/{{ ansible_nas_app_name | lower }}.zip"
        force_archive: true
        format: zip
        owner: ansible-nas
        group: ansible-nas
        mode: u=rw,g=rw
        remove: true
      when: dir_stat.stat.exists
  when: ispyagentdvr_enabled is false and archive_app_data_enabled is true
