---
- name: Start {{ ansible_nas_app_name }}
  block:
    - name: Create {{ ansible_nas_app_name }} Directories
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
      with_items:
        - "{{ deluge_data_directory }}"
        - "{{ deluge_data_directory }}/config"
        - "{{ deluge_download_directory }}"

    - name: Create {{ ansible_nas_app_name }} Container
      community.docker.docker_container:
        name: deluge
        image: linuxserver/deluge
        pull: true
        cpu_shares: "{{ deluge_cpu_shares }}"
        volumes:
          - "{{ deluge_data_directory }}/config:/config:rw"
          - "{{ deluge_download_directory }}:/downloads:rw"
        ports:
          - "{{ deluge_port }}:8112"
        env:
          TZ: "{{ deluge_timezone }}"
          PUID: "{{ deluge_user_id }}"
          PGID: "{{ deluge_group_id }}"
        restart_policy: unless-stopped
        memory: "{{ deluge_memory }}"
        labels:
          autoheal: "{{ deluge_autoheal }}"
          com.centurylinklabs.watchtower.monitor-only: "{{ deluge_watchtower_monitor_only }}"
          traefik.enable: "{{ deluge_available_externally | string }}"
          traefik.http.routers.deluge.rule: "Host(`{{ deluge_hostname }}.{{ ansible_nas_domain }}`)"
          traefik.http.routers.deluge.tls.certresolver: "letsencrypt"
          traefik.http.routers.deluge.tls.domains[0].main: "{{ ansible_nas_domain }}"
          traefik.http.routers.deluge.tls.domains[0].sans: "*.{{ ansible_nas_domain }}"
          traefik.http.services.deluge.loadbalancer.server.port: "8112"
          homepage.group: Download Tools
          homepage.name: Deluge
          homepage.icon: deluge.png
          homepage.href: "http://{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}:{{ deluge_port }}"
          homepage.description: BitTorrent client
          homepage.widget.type: deluge
          homepage.widget.url: "http://{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}:{{ deluge_port }}"
  when: deluge_enabled is true

- name: Stop {{ ansible_nas_app_name }}
  block:
    - name: Stop {{ ansible_nas_app_name }} Container
      community.docker.docker_container:
        name: "{{ deluge_container_name }}"
        state: absent
  when: deluge_enabled is false

- name: Data Archive {{ ansible_nas_app_name }}
  block:
    - name: Check for {{ ansible_nas_app_name }} Data Directory
      stat:
        path: "{{ deluge_data_directory }}"
      register: dir_stat

    - name: Archive {{ ansible_nas_app_name }} Data Directory
      ansible.builtin.archive:
        path: "{{ deluge_data_directory }}"
        dest: "{{ docker_home }}/{{ ansible_nas_app_name | lower }}.zip"
        force_archive: true
        format: zip
        owner: ansible-nas
        group: ansible-nas
        mode: u=rw,g=rw
        remove: true
      when: dir_stat.stat.exists
  when: deluge_enabled is false and archive_app_data_enabled is true
