---
- name: Start {{ ansible_nas_app_name }}
  block:
    - name: Create {{ ansible_nas_app_name }} Directories
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
      with_items:
        - "{{ deluge_data_directory }}"
        - "{{ deluge_data_directory }}/config"
        - "{{ deluge_download_directory }}"

    - name: Create {{ ansible_nas_app_name }} Container
      community.docker.docker_container:
        container_default_behavior: "compatibility"
        name: "{{ deluge_container_name }}"
        hostname: "{{ deluge_container_name }}"
        image: "{{ deluge_image_name }}:{{ deluge_image_tag }}"
        pull: true
        volumes:
          - "{{ deluge_data_directory }}/config:/config:rw"
          - "{{ deluge_download_directory }}:/downloads:rw"
        ports:
          - "{{ deluge_port_http }}:8112"
        env:
          DOCKER_MODS: "{{ deluge_env_docker_mods }}"
          INSTALL_PACKAGES: "{{ deluge_env_docker_mods_install_packages }}"
          INSTALL_PIP_PACKAGES: "{{ deluge_env_docker_mods_install_pip_packages}}"
          TP_DOMAIN: "{{ deluge_env_docker_mods_tp_domain }}"
          TP_THEME: "{{ deluge_env_docker_mods_tp_theme }}"
          TP_COMMUNITY_THEME: "{{ deluge_env_docker_mods_tp_community_theme }}"
          TP_ADDON: "{{ deluge_env_docker_mods_tp_addon }}"
          PUID: "{{ deluge_user_id }}"
          PGID: "{{ deluge_group_id }}"
          TZ: "{{ ansible_nas_timezone }}"
        labels:
          autoheal: "{{ deluge_autoheal | string }}"
          com.centurylinklabs.watchtower.enable: "{{ deluge_watchtower_enabled | string }}"
          dockflare.enable: "{{ deluge_dockflare_enabled | string }}"
          dockflare.access.group: "{{ deluge_dockflare_access_group }}"
          dockflare.hostname: "{{ deluge_hostname }}.{{ ansible_nas_domain }}"
          dockflare.service: "http://{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}:{{ deluge_port_http }}"
          homepage.name: "{{ ansible_nas_app_name }}"
          homepage.group: "{{ deluge_homepage_group }}"
          homepage.icon: "{{ deluge_homepage_icon }}"
          homepage.href: "{{ deluge_homepage_href }}"
          homepage.description: "{{ 'BitTorrent client' if homepage_show_description else omit }}"
          homepage.server: "my-docker"
          homepage.container: "{{ deluge_container_name }}"
          homepage.showStats: "{{ deluge_homepage_showstats | string }}"
          homepage.siteMonitor: "http://{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}:{{ deluge_port_http }}"
          homepage.widget.type: "deluge"
          homepage.widget.url: "http://{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}:{{ deluge_port_http }}"
          homepage.widget.password: "{{ deluge_homepage_widget_password }}"
          homepage.widget.enableLeechProgress: "{{ deluge_homepage_widget_enableleechprogress }}"
          repliqate.enabled: "{{ deluge_repliqate_enabled | string }}"
          repliqate.engine: "{{ deluge_repliqate_engine }}"
          repliqate.schedule: "{{ deluge_repliqate_schedule }}"
          repliqate.backup_id: "{{ deluge_repliqate_backup_id }}"
          repliqate.retention: "{{ deluge_repliqate_retention }}"
          traefik.enable: "{{ deluge_available_externally | string }}"
          traefik.http.routers.deluge.rule: "Host(`{{ deluge_hostname }}.{{ ansible_nas_domain }}`)"
          traefik.http.routers.deluge.tls.certresolver: "letsencrypt"
          traefik.http.routers.deluge.tls.domains[0].main: "{{ ansible_nas_domain }}"
          traefik.http.routers.deluge.tls.domains[0].sans: "*.{{ ansible_nas_domain }}"
          traefik.http.routers.deluge.middlewares: "deluge@docker{{ ',tinyauth-auth@docker' if deluge_tinyauth_enabled | bool else '' }}"
          traefik.http.middlewares.deluge.IPAllowList.sourcerange: "{{ deluge_traefik_whitelist }}"
          traefik.http.services.deluge.loadbalancer.server.port: "8112"
          wud.tag.include: '^version-\d+\.\d+\.\d+$'
          wud.tag.transform.type: "semver"
          wud.link.template: "lscr.io/linuxserver/deluge"
        cpu_shares: "{{ deluge_cpu_shares }}"
        memory: "{{ deluge_memory }}"
        memory_swap: "{{ deluge_memory_swap }}"
        restart_policy: unless-stopped

    - name: Access {{ ansible_nas_app_name }} at
      ansible.builtin.debug:
        msg: >-
              {{
                ['http://' + hostvars[inventory_hostname]['ansible_default_ipv4']['address'] + ':' + (deluge_port_http | string)] +
                (['https://' + deluge_hostname + '.' + ansible_nas_domain] if (deluge_available_externally is true or deluge_dockflare_enabled is true) else [])
              }}
  when: deluge_enabled is true

- name: Stop {{ ansible_nas_app_name }}
  block:
    - name: Stop {{ ansible_nas_app_name }} Container
      community.docker.docker_container:
        name: "{{ deluge_container_name }}"
        state: absent
  when: deluge_enabled is false

- name: Data Archive {{ ansible_nas_app_name }}
  include_role:
    name: ansible-nas-archive
  vars:
    target_data_dir: "{{ deluge_data_directory }}"
  when:
    - archive_app_data_enabled is true
    - deluge_enabled is false