---
# ANE
ansible_nas_app_name: "Plex Media Server"
plex_enabled: false
plex_traefik_enabled: false
plex_traefik_whitelist: "{{ lan }}"

# directories
plex_data_directory: "{{ docker_home }}/plex"
plex_anime_directory: "{{ anime_root }}"
plex_audiobooks_directory: "{{ audiobooks_root }}"
plex_movies_directory: "{{ movies_root }}"
plex_music_directory: "{{ music_root }}"
plex_photos_directory: "{{ photos_root }}"
plex_podcasts_directory: "{{ podcasts_root }}"
plex_porn_directory: "{{ porn_root }}"
plex_tv_directory: "{{ tv_root }}"

# uid / gid
plex_user_id: "0"
plex_group_id: "0"

# media permissions (change to "ro" for ready only)
plex_anime_permissions: "rw"
plex_audiobooks_permissions: "rw"
plex_movies_permissions: "rw"
plex_music_permissions: "rw"
plex_photos_permissions: "rw"
plex_podcasts_permissions: "rw"
plex_porn_permissions: "rw"
plex_tv_permissions: "rw"

# network
plex_hostname: "plex"
plex_port_http: "32400"

# docker
plex_container_name: "plex"
plex_image_name: "lscr.io/linuxserver/plex"
plex_image_version: "latest"

# specs
plex_cpu_shares: 1024
plex_memory: "2g"
plex_memory_swap: -1

# Device mappings for the docker container. E.g. To enable hardware transcoding:
# plex_devices:
#  - "/dev/dri:/dev/dri"

# see https://hub.docker.com/r/linuxserver/plex for details on this setting
plex_version: "docker"

# autoheal
plex_autoheal_enabled: false

# dockflare
plex_dockflare_enabled: false
plex_dockflare_access_group: ""

# homepage
plex_homepage_group: "Media Servers"
plex_homepage_icon: "plex.png"
plex_homepage_href: "https://{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}:32400/web"
plex_homepage_showstats: false
plex_homepage_widget_key: ""

# linuxserver.io docker mods
# https://mods.linuxserver.io/?mod=plex
plex_env_docker_mods: ""
plex_env_docker_mods_install_packages: ""
plex_env_docker_mods_install_pip_packages: ""

# theme.park themes
# https://docs.theme-park.dev/themes/plex/
plex_env_docker_mods_tp_theme: ""
plex_env_docker_mods_tp_community_theme: ""
plex_env_docker_mods_tp_domain: ""
plex_env_docker_mods_tp_addon: ""

# repliqate
plex_repliqate_enabled: false
plex_repliqate_engine: "restic"
plex_repliqate_schedule: "@daily 3am"
plex_repliqate_backup_id: "{{ plex_container_name }}"
plex_repliqate_retention: "30d"

# tinyauth
plex_tinyauth_enabled: false

# watchtower
plex_watchtower_enabled: false