---
# ANE
ansible_nas_app_name: "Resilio Sync"
resilio_sync_enabled: false
resilio_sync_traefik_enabled: false
resilio_sync_traefik_whitelist: "{{ lan }}"
resilio_sync_data_directory: "{{ docker_home }}/resilio-sync"

# network
resilio_sync_port_http: "3014"
resilio_sync_port_sync: "55555"
resilio_sync_hostname: "resiliosync"

resilio_sync_puid: "1000"
resilio_sync_pgid: "1000"

# docker
resilio_sync_container_name: "resilio-sync"
resilio_sync_image_name: "lscr.io/linuxserver/resilio-sync"
resilio_sync_image_tag: "latest"

# specs
resilio_sync_cpu_shares: 1024
resilio_sync_memory: "512M"
resilio_sync_memory_swap: -1

# autoheal
resilio_sync_autoheal_enabled: false

# dockflare
resilio_sync_dockflare_enabled: false
resilio_sync_dockflare_access_group: ""

# homepage
resilio_sync_homepage_group: "Apps"
resilio_sync_homepage_icon: "resiliosync.png"
resilio_sync_homepage_href: "http://{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}:{{ resilio_sync_port_http }}"
resilio_sync_homepage_showstats: false

# linuxserver.io docker mods
resilio_sync_env_docker_mods: ""
resilio_sync_env_docker_mods_install_packages: ""
resilio_sync_env_docker_mods_install_pip_packages: ""

# theme.park themes
# https://docs.theme-park.dev/themes/resilio-sync/
resilio_sync_env_docker_mods_tp_theme: ""
resilio_sync_env_docker_mods_tp_community_theme: ""
resilio_sync_env_docker_mods_tp_domain: ""
resilio_sync_env_docker_mods_tp_addon: ""

# repliqate
resilio_sync_repliqate_enabled: false
resilio_sync_repliqate_engine: "restic"
resilio_sync_repliqate_schedule: "@daily 3am"
resilio_sync_repliqate_backup_id: "{{ resilio_sync_container_name }}"
resilio_sync_repliqate_retention: "30d"

# tinyauth
resilio_sync_tinyauth_enabled: false

# watchtower
resilio_sync_watchtower_enabled: false
