---
- name: Start Tautulli
  block:
    - name: Create Tdarr Directories
      file:
        path: "{{ item }}"
        state: directory
      with_items:
        - "{{ tdarr1_data_directory }}"
        - "{{ tdarr1_db_directory }}"
        - "{{ tdarr1_cache_directory }}"
        - "{{ tdarr1_media_directory }}"

    - name: Create Tdarr Docker Container
      docker_container:
        name: tdarr_v1
        image: haveagitgat/tdarr_aio
        log_options:
          driver: json-file
          options:
            max-file: 10
            max-size: 200k
        pull: true
        volumes:
          - "/etc/localtime:/etc/localtime:ro"
          - "{{ tdarr1_data_directory }}:/home/Tdarr/Documents/Tdarr"
          - "{{ tdarr1_db_directory }}:/var/lib/mongodb"
          - "{{ tdarr1_cache_directory }}:/home/Tdarr/cache"
          - "{{ tdarr1_media_directory }}:/media"
        ports:
          - "{{ tdarr1_port_http }}:8265"
        cpu_shares: "{{ tdarr1_cpu_shares }}"
        env:
          TZ: "{{ ansible_nas_timezone }}"
          PUID: "{{ tdarr1_user_id }}"
          PGID: "{{ tdarr1_group_id }}"
          NVIDIA_VISIBLE_DEVICES: "all"
          NVIDIA_DRIVER_CAPABILITIES: "compute,video,utility"
          VERSION: "docker"
        restart_policy: unless-stopped
        labels:
          traefik.enable: "{{ tdarr1_available_externally | string }}"
          traefik.http.routers.tdarr.rule: "Host(`tdarr.{{ ansible_nas_domain }}`)"
          traefik.http.routers.tdarr.tls.certresolver: "letsencrypt"
          traefik.http.routers.tdarr.tls.domains[0].main: "{{ ansible_nas_domain }}"
          traefik.http.routers.tdarr.tls.domains[0].sans: "*.{{ ansible_nas_domain }}"
          traefik.http.routers.frontend.middlewares: "{{ tdarr1_hostname }}"
          traefik.http.routers.tdarr.middlewares: "{{ tdarr1_hostname }}@docker"
          traefik.http.middlewares.tdarr.IPAllowList.sourcerange: "{{ tdarr1_traefik_whitelist }}"
          traefik.http.services.tdarr.loadbalancer.server.port: "8265"
        memory: "{{ tdarr1_memory }}"
  when: tdarr1_enabled is true

- name: Stop Tdarr
  block:
    - name: Stop Tdarr
      community.docker.docker_container:
        name: "tdarr_v1"
        state: absent
  when: tdarr1_enabled is false