---
- name: Start {{ ansible_nas_app_name }}
  block:
    - name: Create {{ ansible_nas_app_name }} Directories
      file:
        path: "{{ item }}"
        state: directory
      with_items:
        - "{{ glance_data_directory }}"
        - "{{ glance_data_directory }}/assets"

    - name: Create {{ ansible_nas_app_name }} Container
      community.docker.docker_container:
        container_default_behavior: "compatibility"
        name: "{{ glance_container_name }}"
        hostname: "{{ glance_container_name }}"
        image: "{{ glance_image_name }}:{{ glance_image_tag }}"
        pull: true
        ports:
          - "{{ glance_port_http }}:8080"
        volumes:
          - "{{ glance_data_directory }}/glance.yml:/app/glance.yml"
          - "{{ glance_data_directory }}/assets:/app/assets"
        network_mode: bridge
        env:
          TZ: "{{ ansible_nas_timezone }}"
        labels:
          autoheal: "{{ glance_autoheal }}"
          com.centurylinklabs.watchtower.enable: "{{ glance_watchtower_enable }}"
          dockflare.enable: "{{ glance_dockflare_tunnel }}"
          dockflare.access.group: "{{ glance_dockflare_access_group }}"
          dockflare.hostname: "{{ glance_hostname }}.{{ ansible_nas_domain }}"
          dockflare.service: "http://{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}:{{ glance_port_http }}"
          homepage.name: "{{ ansible_nas_app_name }}"
          homepage.group: "{{ glance_homepage_group }}"
          homepage.icon: "{{ glance_homepage_icon }}"
          homepage.href: "{{ glance_homepage_href }}"
          homepage.siteMonitor: "http://{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}:{{ glance_port_http }}"
          homepage.description: "{{ 'A self-hosted dashboard that puts all your feeds in one place.' if homepage_show_description else omit }}"
          homepage.server: "my-docker"
          homepage.container: "{{ glance_container_name }}"
          homepage.showStats: "{{ glance_homepage_showstats }}"
          traefik.enable: "{{ glance_available_externally | string }}"
          traefik.http.routers.glance.rule: "Host(`{{ glance_hostname }}.{{ ansible_nas_domain }}`)"
          traefik.http.routers.glance.tls.certresolver: "letsencrypt"
          traefik.http.routers.glance.tls.domains[0].main: "{{ ansible_nas_domain }}"
          traefik.http.routers.glance.tls.domains[0].sans: "*.{{ ansible_nas_domain }}"
          traefik.http.routers.frontend.middlewares: "{{ glance_hostname }}"
          traefik.http.routers.glance.middlewares: "{{ glance_hostname }}@docker"
          traefik.http.middlewares.glance.IPAllowList.sourcerange: "{{ glance_traefik_whitelist }}"
          traefik.http.services.glance.loadbalancer.server.port: "8080"
          wud.tag.include: '^\d+\.\d+\.\d+.*$'
          wud.tag.transform.type: "semver"
          wud.link.template: "https://hub.docker.com/r/glanceapp/glance"
        cpu_shares: "{{ glance_cpu_shares }}"
        memory: "{{ glance_memory }}"
        restart_policy: unless-stopped
  when: glance_enabled is true

- name: Stop {{ ansible_nas_app_name }}
  block:
    - name: Stop {{ ansible_nas_app_name }} Container
      community.docker.docker_container:
        name: "{{ glance_container_name }}"
        state: absent
  when: glance_enabled is false

- name: Data Archive {{ ansible_nas_app_name }}
  block:
    - name: Check for {{ ansible_nas_app_name }} Data Directory
      stat:
        path: "{{ glance_data_directory }}"
      register: dir_stat

    - name: Archive {{ ansible_nas_app_name }} Data Directory
      ansible.builtin.archive:
        path: "{{ glance_data_directory }}"
        dest: "{{ docker_home }}/{{ ansible_nas_app_name | lower }}.zip"
        force_archive: true
        format: zip
        owner: ansible-nas
        group: ansible-nas
        mode: u=rw,g=rw
        remove: true
      when: dir_stat.stat.exists
  when: glance_enabled is false and archive_app_data_enabled is true
