---
- name: Start {{ ansible_nas_app_name }}
  block:
    - name: Create {{ ansible_nas_app_name }} Directories
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
      with_items:
        - "{{ glance_data_directory }}"
        - "{{ glance_data_directory }}/assets"
        - "{{ glance_data_directory }}/config"

    - name: Create {{ ansible_nas_app_name }} Template config file
      ansible.builtin.template:
        src: "{{ item }}"
        dest: "{{ glance_data_directory }}/config/{{ item }}"
      with_items:
        - glance.yml
      register: glance_config

    - name: Create {{ ansible_nas_app_name }} Container
      community.docker.docker_container:
        container_default_behavior: "compatibility"
        name: "{{ glance_container_name }}"
        hostname: "{{ glance_container_name }}"
        image: "{{ glance_image_name }}:{{ glance_image_tag }}"
        pull: true
        ports:
          - "{{ glance_port_http }}:8080"
        volumes:
#          - "{{ glance_data_directory }}/config/glance.yml:/app/config/glance.yml"
          - "{{ glance_data_directory }}/assets:/app/assets"
          - "{{ glance_data_directory }}/config:/app/config"
          - "/etc/localtime:/etc/localtime:ro"
          - "/var/run/docker.sock:/var/run/docker.sock:ro"
        network_mode: bridge
        env:
          TZ: "{{ ansible_nas_timezone }}"
        labels:
          autoheal: "{{ glance_autoheal | string }}"
          com.centurylinklabs.watchtower.enable: "{{ glance_watchtower_enabled | string }}"
          dockflare.enable: "{{ glance_dockflare_enabled | string }}"
          dockflare.access.group: "{{ glance_dockflare_access_group }}"
          dockflare.hostname: "{{ glance_hostname }}.{{ ansible_nas_domain }}"
          dockflare.service: "http://{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}:{{ glance_port_http }}"
          homepage.name: "{{ ansible_nas_app_name }}"
          homepage.group: "{{ glance_homepage_group }}"
          homepage.icon: "{{ glance_homepage_icon }}"
          homepage.href: "{{ glance_homepage_href }}"
          homepage.siteMonitor: "http://{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}:{{ glance_port_http }}"
          homepage.description: "{{ 'A self-hosted dashboard that puts all your feeds in one place.' if homepage_show_description else omit }}"
          homepage.server: "my-docker"
          homepage.container: "{{ glance_container_name }}"
          homepage.showStats: "{{ glance_homepage_showstats | string }}"
          repliqate.enabled: "{{ glance_repliqate_enabled | string }}"
          repliqate.engine: "{{ glance_repliqate_engine }}"
          repliqate.schedule: "{{ glance_repliqate_schedule }}"
          repliqate.backup_id: "{{ glance_repliqate_backup_id }}"
          repliqate.retention: "{{ glance_repliqate_retention }}"
          traefik.enable: "{{ glance_available_externally | string }}"
          traefik.http.routers.glance.rule: "Host(`{{ glance_hostname }}.{{ ansible_nas_domain }}`)"
          traefik.http.routers.glance.tls.certresolver: "letsencrypt"
          traefik.http.routers.glance.tls.domains[0].main: "{{ ansible_nas_domain }}"
          traefik.http.routers.glance.tls.domains[0].sans: "*.{{ ansible_nas_domain }}"
          traefik.http.routers.glance.middlewares: "glance@docker{{ ',tinyauth-auth@docker' if glance_tinyauth_enabled | bool else '' }}"
          traefik.http.middlewares.glance.IPAllowList.sourcerange: "{{ glance_traefik_whitelist }}"
          traefik.http.services.glance.loadbalancer.server.port: "8080"
          wud.tag.include: '^\d+\.\d+\.\d+.*$'
          wud.tag.transform.type: "semver"
          wud.link.template: "https://hub.docker.com/r/glanceapp/glance"
        cpu_shares: "{{ glance_cpu_shares }}"
        memory: "{{ glance_memory }}"
        memory_swap: "{{ glance_memory_swap }}"
        restart_policy: unless-stopped

    - name: Access {{ ansible_nas_app_name }} at
      ansible.builtin.debug:
        msg: >-
              {{
                ['http://' + hostvars[inventory_hostname]['ansible_default_ipv4']['address'] + ':' + (glance_port_http | string)] +
                (['https://' + glance_hostname + '.' + ansible_nas_domain] if (glance_available_externally is true or glance_dockflare_enabled is true) else [])
              }}
  when: glance_enabled is true

- name: Stop {{ ansible_nas_app_name }}
  block:
    - name: Stop {{ ansible_nas_app_name }} Container
      community.docker.docker_container:
        name: "{{ glance_container_name }}"
        state: absent
  when: glance_enabled is false

- name: Data Archive {{ ansible_nas_app_name }}
  include_role:
    name: ansible-nas-archive
  vars:
    target_data_dir: "{{ glance_data_directory }}"
  when:
    - archive_app_data_enabled is true
    - glance_enabled is false