---
- name: Start {{ ansible_nas_app_name }}
  block:
    - name: Create {{ ansible_nas_app_name }} Directories
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
      with_items:
        - "{{ proxmox_stack_data_directory }}"
        - "{{ proxmox_stack_data_directory }}/backup"
        - "{{ proxmox_stack_data_directory }}/iso"

    - name: Create {{ ansible_nas_app_name }} Network
      community.docker.docker_network:
        name: "{{ proxmox_stack_network_name }}"
  when:
    - proxmox_stack_enabled is true

- ansible.builtin.import_tasks: pve1.yml
- ansible.builtin.import_tasks: pve2.yml
- ansible.builtin.import_tasks: pve3.yml
- ansible.builtin.import_tasks: pdm.yml

- name: Delete {{ ansible_nas_app_name }} Network
  community.docker.docker_network:
    name: "{{ proxmox_stack_network_name }}"
    state: absent
  when:
    - proxmox_stack_enabled is false

- name: Data Archive Proxmox Stack
  include_role:
    name: ansible-nas-archive
  vars:
    target_data_dir: "{{ docker_home }}/proxmox"
  when:
    - archive_app_data_enabled is true
    - proxmox_stack_enabled is false
