---
- name: Start {{ ansible_nas_app_name }}
  block:
    - name: Create {{ ansible_nas_app_name }} Directories
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
      with_items:
        - "{{ octoprint_data_directory }}"

    - name: Create {{ ansible_nas_app_name }} Container
      community.docker.docker_container:
        container_default_behavior: "compatibility"
        name: "{{ octoprint_container_name }}"
        hostname: "{{ octoprint_container_name }}"
        image: "{{ octoprint_image_name }}:{{ octoprint_image_version }}"
        pull: true
        volumes:
          - "{{ octoprint_data_directory }}:/octoprint:rw"
        ports:
          - "{{ octoprint_port_http }}:80"
        devices:
          - "{{ octoprint_enable_printer | ternary(octoprint_printer_mountpoint, '/dev/null') }}"
          - "{{ octoprint_enable_webcam | ternary(octoprint_webcam_mountpoint, '/dev/null') }}"
        env:
          ENABLE_MJPG_STREAMER: "{{ octoprint_enable_webcam | string }}"
          MJPG_STREAMER_INPUT: "-n -r 1080x1024 -f 30"
          TZ: "{{ ansible_nas_timezone }}"
        labels:
          autoheal: "{{ octoprint_autoheal }}"
          com.centurylinklabs.watchtower.enable: "{{ octoprint_watchtower_enable }}"
          dockflare.enable: "{{ octoprint_dockflare_tunnel }}"
          dockflare.access.group: "{{ octoprint_dockflare_access_group }}"
          dockflare.hostname: "{{ octoprint_hostname }}.{{ ansible_nas_domain }}"
          dockflare.service: "http://{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}:{{ octoprint_port_http }}"
          homepage.name: "{{ ansible_nas_app_name }}"
          homepage.group: "{{ octoprint_homepage_group }}"
          homepage.icon: "{{ octoprint_homepage_icon }}"
          homepage.href: "{{ octoprint_homepage_href }}"
          homepage.description: "{{ 'octoprint description' if homepage_show_description else omit }}"
          homepage.server: "my-docker"
          homepage.container: "{{ octoprint_container_name }}"
          homepage.showStats: "{{ octoprint_homepage_showstats }}"
          homepage.siteMonitor: "http://{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}:{{ octoprint_port_http }}"
          traefik.enable: "{{ octoprint_available_externally | string }}"
          traefik.http.routers.octoprint.rule: "Host(`{{ octoprint_hostname }}.{{ ansible_nas_domain }}`)"
          traefik.http.routers.octoprint.tls.certresolver: "letsencrypt"
          traefik.http.routers.octoprint.tls.domains[0].main: "{{ ansible_nas_domain }}"
          traefik.http.routers.octoprint.tls.domains[0].sans: "*.{{ ansible_nas_domain }}"
          traefik.http.routers.frontend.middlewares: "{{ octoprint_hostname }}"
          traefik.http.routers.octoprint.middlewares: "{{ octoprint_hostname }}@docker"
          traefik.http.middlewares.octoprint.IPAllowList.sourcerange: "{{ octoprint_traefik_whitelist }}"
          traefik.http.services.octoprint.loadbalancer.server.port: "80"
          wud.tag.include: '^\d+\.\d+\.\d+.*$'
          wud.tag.transform.type: "semver"
          wud.link.template: "https://hub.docker.com/r/octoprint/octoprint"
        cpu_shares: "{{ octoprint_cpu_shares }}"
        memory: "{{ octoprint_memory }}"
        restart_policy: unless-stopped

    - name: Access {{ ansible_nas_app_name }} at
      ansible.builtin.debug:
        msg: >-
              {{
                ['http://' + hostvars[inventory_hostname]['ansible_default_ipv4']['address'] + ':' + (octoprint_port_http | string)] +
                (['https://' + octoprint_hostname + '.' + ansible_nas_domain] if (octoprint_available_externally is true or octoprint_dockflare_tunnel is true) else [])
              }}
  when: octoprint_enabled is true

- name: Stop {{ ansible_nas_app_name }}
  block:
    - name: Stop {{ ansible_nas_app_name }} Container
      community.docker.docker_container:
        name: "{{ octoprint_container_name }}"
        state: absent
  when: octoprint_enabled is false

- name: Data Archive {{ ansible_nas_app_name }}
  include_role:
    name: ansible-nas-archive
  vars:
    target_data_dir: "{{ octoprint_data_directory }}"
  when:
    - archive_app_data_enabled is true
    - octoprint_enabled is false