---
- name: Start {{ ansible_nas_app_name }}
  block:
    - name: Create {{ ansible_nas_app_name }} Directories
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
      with_items:
        - "{{ octoprint_data_directory }}"

    - name: Create {{ ansible_nas_app_name }} Container
      community.docker.docker_container:
        container_default_behavior: "compatibility"
        name: "{{ octoprint_container_name }}"
        hostname: "{{ octoprint_container_name }}"
        image: "{{ octoprint_image_name }}:{{ octoprint_image_version }}"
        pull: true
        volumes:
          - "{{ octoprint_data_directory }}:/octoprint:rw"
        ports:
          - "{{ octoprint_port }}:80"
        devices:
          - "{{ octoprint_printer_mountpoint }}"
          - "{{ octoprint_enable_webcam | ternary(octoprint_webcam_mountpoint, '/dev/null') }}"
        env:
          ENABLE_MJPG_STREAMER: "{{ octoprint_enable_webcam | string }}"
          MJPG_STREAMER_INPUT: "-n -r 1080x1024 -f 30"
          TZ: "{{ ansible_nas_timezone }}"
        labels:
          autoheal: "{{ octoprint_autoheal }}"
          com.centurylinklabs.watchtower.monitor-only: "{{ octoprint_watchtower_monitor_only }}"
          homepage.name: "{{ ansible_nas_app_name }}"
          homepage.group: "{{ octoprint_homepage_group }}"
          homepage.icon: "{{ octoprint_homepage_icon }}"
          homepage.href: "{{ octoprint_homepage_href }}"
          homepage.description: "{{ 'octoprint description' if homepage_show_description else omit }}"
          homepage.server: "my-docker"
          homepage.container: "{{ octoprint_container_name }}"
          homepage.showStats: "{{ octoprint_homepage_showStats }}"
          homepage.siteMonitor: "http://{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}:{{ octoprint_port }}"
          traefik.enable: "{{ octoprint_available_externally | string }}"
          traefik.http.routers.octoprint.rule: "Host(`{{ octoprint_hostname }}.{{ ansible_nas_domain }}`)"
          traefik.http.routers.octoprint.tls.certresolver: "letsencrypt"
          traefik.http.routers.octoprint.tls.domains[0].main: "{{ ansible_nas_domain }}"
          traefik.http.routers.octoprint.tls.domains[0].sans: "*.{{ ansible_nas_domain }}"
          traefik.http.routers.frontend.middlewares: "{{ octoprint_hostname }}"
          traefik.http.routers.octoprint.middlewares: "{{ octoprint_hostname }}@docker"
          traefik.http.middlewares.octoprint.IPAllowList.sourcerange: "{{ octoprint_traefik_whitelist }}"
          traefik.http.services.octoprint.loadbalancer.server.port: "80"
          wud.tag.include: '^\d+\.\d+\.\d+$$'
          wud.link.template: "https://github.com/OctoPrint/OctoPrint/releases/tag/$${major}.$${minor}.$${patch}"
        cpu_shares: "{{ octoprint_cpu_shares }}"
        memory: "{{ octoprint_memory }}"
        restart_policy: unless-stopped
  when: octoprint_enabled is true

- name: Stop {{ ansible_nas_app_name }}
  block:
    - name: Stop {{ ansible_nas_app_name }} Container
      community.docker.docker_container:
        name: "{{ octoprint_container_name }}"
        state: absent
  when: octoprint_enabled is false

- name: Data Archive {{ ansible_nas_app_name }}
  block:
    - name: Check for {{ ansible_nas_app_name }} Data Directory
      stat:
        path: "{{ octoprint_data_directory }}"
      register: dir_stat

    - name: Archive {{ ansible_nas_app_name }} Data Directory
      ansible.builtin.archive:
        path: "{{ octoprint_data_directory }}"
        dest: "{{ docker_home }}/{{ ansible_nas_app_name | lower }}.zip"
        force_archive: true
        format: zip
        owner: ansible-nas
        group: ansible-nas
        mode: u=rw,g=rw
        remove: true
      when: dir_stat.stat.exists
  when: octoprint_enabled is false and archive_app_data_enabled is true
