---
- name: Start {{ ansible_nas_app_name }}
  block:
    - name: Create {{ ansible_nas_app_name }} Container
      community.docker.docker_container:
        container_default_behavior: "compatibility"
        name: "{{ whatsrunning_container_name }}"
        hostname: "{{ whatsrunning_container_name }}"
        image: "{{ whatsrunning_image_name }}:{{ whatsrunning_image_tag }}"
        pull: true
        volumes:
          - "/var/run/docker.sock:/var/run/docker.sock:ro"
        env:
          HOST_HOSTNAME: "{{ whatsrunning_env_host_hostname }}"
          VERBOSE: "true"
          TZ: "{{ ansible_nas_timezone }}"
        ports:
          - "{{ whatsrunning_port_http }}:5000"
        labels:
          autoheal: "{{ whatsrunning_autoheal_enabled | ternary('true', 'false') }}"
          com.centurylinklabs.watchtower.enable: "{{ whatsrunning_watchtower_enabled | ternary('true', 'false') }}"
          dockflare.enable: "{{ whatsrunning_dockflare_enabled | ternary('true', 'false') }}"
          dockflare.access.group: "{{ whatsrunning_dockflare_access_group }}"
          dockflare.hostname: "{{ whatsrunning_hostname }}.{{ ansible_nas_domain }}"
          dockflare.service: "http://{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}:{{ whatsrunning_port_http }}"
          homepage.name: "{{ ansible_nas_app_name }}"
          homepage.group: "{{ whatsrunning_homepage_group }}"
          homepage.icon: "{{ whatsrunning_homepage_icon }}"
          homepage.href: "{{ whatsrunning_homepage_href }}"
          homepage.description: "{{ 'a barebones webpage showing all docker containers that expose ports' if homepage_show_description else omit }}"
          homepage.siteMonitor: "http://{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}:{{ whatsrunning_port_http }}"
          homepage.server: "my-docker"
          homepage.container: "{{ whatsrunning_container_name }}"
          homepage.showStats: "{{ whatsrunning_homepage_showstats | ternary('true', 'false') }}"
          repliqate.enabled: "false"
          traefik.enable: "{{ whatsrunning_traefik_enabled | ternary('true', 'false') }}"
          traefik.http.routers.whatsrunning.rule: "Host(`{{ whatsrunning_hostname }}.{{ ansible_nas_domain }}`)"
          traefik.http.routers.whatsrunning.tls.certresolver: "letsencrypt"
          traefik.http.routers.whatsrunning.tls.domains[0].main: "{{ ansible_nas_domain }}"
          traefik.http.routers.whatsrunning.tls.domains[0].sans: "*.{{ ansible_nas_domain }}"
          traefik.http.routers.whatsrunning.middlewares: "whatsrunning@docker{{ ',tinyauth-auth@docker' if whatsrunning_tinyauth_enabled | bool else '' }}"
          traefik.http.middlewares.whatsrunning.IPAllowList.sourcerange: "{{ whatsrunning_traefik_whitelist }}"
          traefik.http.services.whatsrunning.loadbalancer.server.port: "5000"
          wud.tag.include: '^\d{4}\.\d{2}\.\d+$'
          wud.tag.transform.type: "semver"
          wud.link.template: "https://hub.docker.com/r/mikeage/whatsrunning"
        cpu_shares: "{{ whatsrunning_cpu_shares }}"
        memory: "{{ whatsrunning_memory }}"
        memory_swap: "{{ whatsrunning_memory_swap }}"
        restart_policy: unless-stopped

    - name: Access {{ ansible_nas_app_name }} at
      ansible.builtin.debug:
        msg: >-
              {{
                ['http://' + hostvars[inventory_hostname]['ansible_default_ipv4']['address'] + ':' + (whatsrunning_port_http | string)] +
                (['https://' + whatsrunning_hostname + '.' + ansible_nas_domain] if (whatsrunning_traefik_enabled is true or whatsrunning_dockflare_enabled is true) else [])
              }}
  when: whatsrunning_enabled is true

- name: Stop {{ ansible_nas_app_name }}
  block:
    - name: Stop {{ ansible_nas_app_name }} Container
      community.docker.docker_container:
        name: "{{ whatsrunning_container_name }}"
        state: absent
  when: whatsrunning_enabled is false
