---
- name: Start {{ ansible_nas_app_name }}
  block:
    - name: Create {{ ansible_nas_app_name }} Directories
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
      with_items:
        - "{{ mealie_data_directory }}/data"

    - name: Create {{ ansible_nas_app_name }} Container
      community.docker.docker_container:
        container_default_behavior: "compatibility"
        name: "{{ mealie_container_name }}"
        hostname: "{{ mealie_container_name }}"
        image: "{{ mealie_image_name }}:{{ mealie_image_version }}"
        pull: true
        volumes:
          - "{{ mealie_data_directory }}:/app/data:rw"
        ports:
          - "{{ mealie_port_http }}:9000"
        env:
          BASE_URL: "{{ mealie_env_base_url }}"
          PUID: "{{ mealie_user_id }}"
          PGID: "{{ mealie_group_id }}"
          RECIPE_PUBLIC: "{{ mealie_env_recipe_public }}"
          RECIPE_SHOW_NUTRITION: "{{ mealie_env_recipe_show_nutrition }}"
          RECIPE_SHOW_ASSETS: "{{ mealie_env_recipe_show_assets }}"
          RECIPE_LANDSCAPE_VIEW: "{{ mealie_env_receipe_landscape_view }}"
          RECIPE_DISABLE_COMMENTS: "{{ mealie_env_recipe_disable_comments }}"
          RECIPE_DISABLE_AMOUNT: "{{ mealie_env_recipe_disable_amount }}"
          TZ: "{{ ansible_nas_timezone }}"
        labels:
          autoheal: "{{ mealie_autoheal }}"
          com.centurylinklabs.watchtower.enable: "{{ mealie_watchtower_enable }}"
          dockflare.enable: "{{ mealie_dockflare_tunnel }}"
          dockflare.access.group: "{{ mealie_dockflare_access_group }}"
          dockflare.hostname: "{{ mealie_hostname }}.{{ ansible_nas_domain }}"
          dockflare.service: "http://{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}:{{ mealie_port_http }}"
          homepage.name: "{{ ansible_nas_app_name }}"
          homepage.group: "{{ mealie_homepage_group }}"
          homepage.icon: "{{ mealie_homepage_icon }}"
          homepage.href: "{{ mealie_homepage_href }}"
          homepage.description: "{{ 'mealie description' if homepage_show_description else omit }}"
          homepage.server: "my-docker"
          homepage.container: "{{ mealie_container_name }}"
          homepage.showStats: "{{ mealie_homepage_showstats }}"
          homepage.siteMonitor: "http://{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}:{{ mealie_port_http }}"
          homepage.widget.type: "mealie"
          homepage.widget.url: "http://{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}:{{ mealie_port_http }}"
          homepage.widget.key: "{{ mealie_homepage_widget_key }}"
          homepage.widget.version: "{{ mealie_homepage_widget_version }}"
          repliqate.enabled: "{{ mealie_repliqate_enabled }}"
          repliqate.engine: "{{ mealie_repliqate_engine }}"
          repliqate.schedule: "{{ mealie_repliqate_schedule }}"
          repliqate.backup_id: "{{ mealie_repliqate_backup_id }}"
          repliqate.retention: "{{ mealie_repliqate_retention }}"
          traefik.enable: "{{ mealie_available_externally | string }}"
          traefik.http.routers.mealie.rule: "Host(`{{ mealie_hostname }}.{{ ansible_nas_domain }}`)"
          traefik.http.routers.mealie.tls.certresolver: "letsencrypt"
          traefik.http.routers.mealie.tls.domains[0].main: "{{ ansible_nas_domain }}"
          traefik.http.routers.mealie.tls.domains[0].sans: "*.{{ ansible_nas_domain }}"
          traefik.http.routers.mealie.middlewares: "mealie@docker{{ ',tinyauth-auth@docker' if mealie_tinyauth_enabled | bool else '' }}"
          traefik.http.middlewares.mealie.IPAllowList.sourcerange: "{{ mealie_traefik_whitelist }}"
          traefik.http.services.mealie.loadbalancer.server.port: "9000"
          wud.tag.include: '^v\d+\.\d+\.\d+$'
          wud.tag.transform.type: "semver"
          wud.link.template: "https://github.com/mealie-recipes/mealie/pkgs/container/mealie"
        cpu_shares: "{{ mealie_cpu_shares }}"
        memory: "{{ mealie_memory }}"
        memory_swap: "{{ mealie_memory_swap }}"
        restart_policy: unless-stopped

    - name: Access {{ ansible_nas_app_name }} at
      ansible.builtin.debug:
        msg: >-
              {{
                ['http://' + hostvars[inventory_hostname]['ansible_default_ipv4']['address'] + ':' + (mealie_port_http | string)] +
                (['https://' + mealie_hostname + '.' + ansible_nas_domain] if (mealie_available_externally is true or mealie_dockflare_tunnel is true) else [])
              }}
  when: mealie_enabled is true

- name: Stop {{ ansible_nas_app_name }}
  block:
    - name: Stop {{ ansible_nas_app_name }} Container
      community.docker.docker_container:
        name: "{{ mealie_container_name }}"
        state: absent
  when: mealie_enabled is false

- name: Data Archive {{ ansible_nas_app_name }}
  include_role:
    name: ansible-nas-archive
  vars:
    target_data_dir: "{{ mealie_data_directory }}"
  when:
    - archive_app_data_enabled is true
    - mealie_enabled is false