---
- name: Verify
  hosts: all
  gather_facts: false
  tasks:
    - ansible.builtin.include_vars:
        file: ../../defaults/main.yml

    - name: Try and stop and remove {{ vaultwarden_proper_name }}
      community.docker.docker_container:
        name: "{{ vaultwarden_container_name }}"
        state: absent
      register: result

    - name: Try and stop and remove {{ vaultwarden_proper_name }} Backup
      community.docker.docker_container:
        name: "{{ vaultwarden_backup_container_name }}"
        state: absent
      register: result_backup

    - name: Check {{ vaultwarden_proper_name }} is stopped
      ansible.builtin.assert:
        that:
          - not result.changed
          - not result_backup.changed
