---
# ANE
bazarr_proper_name: "Bazarr"
bazarr_enabled: false
bazarr_traefik_enabled: false
bazarr_traefik_whitelist: "{{ lan }}"

# directories
bazarr_data_directory: "{{ docker_home }}/bazarr"
bazarr_tv_directory: "{{ tv_root }}"
bazarr_movies_directory: "{{ movies_root }}"

# uid/gid
bazarr_user_id: "0"
bazarr_group_id: "0"

# network
bazarr_port_http: "6767"
bazarr_hostname: "bazarr"

# specs
bazarr_cpu_shares: 1024
bazarr_memory: "1G"
bazarr_memory_swap: -1

# docker
bazarr_container_name: "bazarr"
bazarr_image_name: "lscr.io/linuxserver/bazarr"
bazarr_image_tag: "latest"

# autoheal
bazarr_autoheal_enabled: false

# dockflare
bazarr_dockflare_enabled: false
bazarr_dockflare_access_group: ""

# homepage
bazarr_homepage_group: "Apps"
bazarr_homepage_icon: "bazarr.png"
bazarr_homepage_href: "http://{{ hostvars[inventory_hostname]['ansible_facts']['default_ipv4']['address'] }}:{{ bazarr_port_http }}"
bazarr_homepage_showstats: false
bazarr_homepage_widget_key: "" # override with your api key

# linuxserver.io docker mods
bazarr_env_docker_mods: ""

# theme.park themes
# https://docs.theme-park.dev/themes/bazarr/
bazarr_env_docker_mods_tp_theme: ""
bazarr_env_docker_mods_tp_community_theme: ""
bazarr_env_docker_mods_tp_domain: ""
bazarr_env_docker_mods_tp_addon: ""
bazarr_env_docker_mods_install_packages: ""
bazarr_env_docker_mods_install_pip_packages: ""

# repliqate
bazarr_repliqate_enabled: false
bazarr_repliqate_engine: "restic"
bazarr_repliqate_schedule: "@daily 3am"
bazarr_repliqate_backup_id: "{{ bazarr_container_name }}"
bazarr_repliqate_retention: "30d"

# tinyauth
bazarr_tinyauth_enabled: false

# watchtower
bazarr_watchtower_enabled: false