---
# ANE
ansible_nas_app_name: "Bazarr"
bazarr_enabled: false
bazarr_available_externally: false
bazarr_traefik_whitelist: "{{ lan }}"

# directories
bazarr_data_directory: "{{ docker_home }}/bazarr"
bazarr_tv_directory: "{{ tv_root }}"
bazarr_movies_directory: "{{ movies_root }}"

# uid/gid
bazarr_user_id: "0"
bazarr_group_id: "0"

# network
bazarr_port: "6767"
bazarr_hostname: "bazarr"

# specs
bazarr_memory: 1g

# docker
bazarr_container_name: bazarr
bazarr_cpu_shares: 1024
bazarr_image_name: "lscr.io/linuxserver/bazarr"
bazarr_image_tag: "latest"

# autoheal
bazarr_autoheal: "false"

# dockflare
bazarr_dockflare_tunnel: "false"
bazarr_dockflare_access_group: ""

# homepage
bazarr_homepage_group: "Apps"
bazarr_homepage_icon: "bazarr.png"
bazarr_homepage_href: "http://{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}:{{ bazarr_port }}"
bazarr_homepage_showstats: "false"

# linuxserver.io docker mods
bazarr_env_docker_mods: ""

# theme.park themes
# https://docs.theme-park.dev/themes/bazarr/
bazarr_env_docker_mods_tp_theme: ""
bazarr_env_docker_mods_tp_community_theme: ""
bazarr_env_docker_mods_tp_domain: ""
bazarr_env_docker_mods_tp_addon: ""

# watchtower
bazarr_watchtower_enable: "false"