---
- name: Start {{ ansible_nas_app_name }}
  block:
    - name: Create Dashy Directory
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
      with_items:
        - "{{ dashy_data_directory }}"

    - name: Copy {{ ansible_nas_app_name }} base config
      ansible.builtin.copy:
        src: conf.yml
        dest: "{{ dashy_data_directory }}/conf.yml"
        force: no

    - name: Create {{ ansible_nas_app_name }} Container
      community.docker.docker_container:
        container_default_behavior: "compatibility"
        name: "{{ dashy_container_name }}"
        hostname: "{{ dashy_container_name }}"
        image: "{{ dashy_image_name }}:{{ dashy_image_tag }}"
        pull: true
        ports:
          - "{{ dashy_port }}:80"
        volumes:
          - "{{ dashy_data_directory }}/conf.yml:/app/public/conf.yml:rw"
        labels:
          autoheal: "{{ dashy_autoheal }}"
          com.centurylinklabs.watchtower.enable: "{{ dashy_watchtower_enable }}"
          dockflare.enable: "{{ dashy_dockflare_tunnel }}"
          dockflare.access.group: "{{ dashy_dockflare_access_group }}"
          dockflare.hostname: "{{ dashy_hostname }}.{{ ansible_nas_domain }}"
          dockflare.service: "http://{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}:{{ dashy_port }}"
          homepage.name: "{{ ansible_nas_app_name }}"
          homepage.group: "{{ dashy_homepage_group }}"
          homepage.icon: "{{ dashy_homepage_icon }}"
          homepage.href: "{{ dashy_homepage_href }}"
          homepage.description: "{{ 'dashy description' if homepage_show_description else omit }}"
          homepage.server: "my-docker"
          homepage.container: "{{ dashy_container_name }}"
          homepage.showStats: "{{ dashy_homepage_showstats }}"
          homepage.siteMonitor: "http://{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}:{{ dashy_port }}"
          repliqate.enabled: "{{ dashy_repliqate_enabled }}"
          repliqate.engine: "{{ dashy_repliqate_engine }}"
          repliqate.schedule: "{{ dashy_repliqate_schedule }}"
          repliqate.backup_id: "{{ dashy_repliqate_backup_id }}"
          repliqate.retention: "{{ dashy_repliqate_retention }}"
          traefik.enable: "{{ dashy_available_externally | string }}"
          traefik.http.routers.dashy.rule: "Host(`{{ dashy_hostname }}.{{ ansible_nas_domain }}`)"
          traefik.http.routers.dashy.tls.certresolver: "letsencrypt"
          traefik.http.routers.dashy.tls.domains[0].main: "{{ ansible_nas_domain }}"
          traefik.http.routers.dashy.tls.domains[0].sans: "*.{{ ansible_nas_domain }}"
          traefik.http.routers.frontend.middlewares: "{{ dashy_hostname }}"
          traefik.http.routers.dashy.middlewares: "{{ dashy_hostname }}@docker"
          traefik.http.middlewares.dashy.IPAllowList.sourcerange: "{{ dashy_traefik_whitelist }}"
          traefik.http.services.dashy.loadbalancer.server.port: "80"
          wud.tag.include: '^\d+\.\d+\.\d+.*$'
          wud.tag.transform.type: "semver"
          wud.link.template: "https://hub.docker.com/r/lissy93/dashy"
        cpu_shares: "{{ dashy_cpu_shares }}"
        memory: "{{ dashy_memory }}"
        restart_policy: unless-stopped

    - name: Access {{ ansible_nas_app_name }} at
      ansible.builtin.debug:
        msg: >-
              {{
                ['http://' + hostvars[inventory_hostname]['ansible_default_ipv4']['address'] + ':' + (dashy_port | string)] +
                (['https://' + dashy_hostname + '.' + ansible_nas_domain] if (dashy_available_externally is true or dashy_dockflare_tunnel is true) else [])
              }}
  when: dashy_enabled is true

- name: Stop {{ ansible_nas_app_name }}
  block:
    - name: Stop {{ ansible_nas_app_name }} Container
      community.docker.docker_container:
        name: "{{ dashy_container_name }}"
        state: absent
  when: dashy_enabled is false

- name: Data Archive {{ ansible_nas_app_name }}
  block:
    - name: Check for {{ ansible_nas_app_name }} Data Directory
      stat:
        path: "{{ dashy_data_directory }}"
      register: dir_stat

    - name: Archive {{ ansible_nas_app_name }} Data Directory
      ansible.builtin.archive:
        path: "{{ dashy_data_directory }}"
        dest: "{{ docker_home }}/{{ ansible_nas_app_name | lower }}.zip"
        force_archive: true
        format: zip
        owner: ansible-nas
        group: ansible-nas
        mode: u=rw,g=rw
        remove: true
      when: dir_stat.stat.exists
  when: dashy_enabled is false and archive_app_data_enabled is true
