---
# ANE
ansible_nas_app_name: "CouchPotato"
couchpotato_enabled: false
couchpotato_available_externally: false
couchpotato_traefik_whitelist: "{{ lan }}"

# directories
couchpotato_data_directory: "{{ docker_home }}/couchpotato"
couchpotato_movies_directory: "{{ movies_root }}"
couchpotato_downloads_directory: "{{ downloads_root }}"
couchpotato_torrents_directory: "{{ torrents_root }}"

# uid / gid
couchpotato_user_id: "0"
couchpotato_group_id: "0"

# network
couchpotato_hostname: "couchpotato"
couchpotato_port_http: "5050"

# specs
couchpotato_memory: "1G"

# docker
couchpotato_container_name: "couchpotato"
couchpotato_cpu_shares: 1024
couchpotato_image_name: "lscr.io/linuxserver/couchpotato"
couchpotato_image_tag: "latest"

# autoheal
couchpotato_autoheal: "false"

# dockflare
couchpotato_dockflare_tunnel: "false"
couchpotato_dockflare_access_group: ""

# homepage
couchpotato_homepage_group: "Apps"
couchpotato_homepage_icon: "couchpotato.png"
couchpotato_homepage_href: "http://{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}:{{ couchpotato_port_http }}"
couchpotato_homepage_showstats: "false"

# linuxserver.io docker mods
couchpotato_env_docker_mods: ""
couchpotato_env_docker_mods_install_packages: ""
couchpotato_env_docker_mods_install_pip_packages: ""

# repliqate
couchpotato_repliqate_enabled: "false"
couchpotato_repliqate_engine: "restic"
couchpotato_repliqate_schedule: "@daily 3am"
couchpotato_repliqate_backup_id: "{{ couchpotato_container_name }}"
couchpotato_repliqate_retention: "30d"

# tinyauth
couchpotato_tinyauth_enabled: false

# watchtower
couchpotato_watchtower_enable: "false"