---
# ANE
ansible_nas_app_name: "Nextcloud"
nextcloud_enabled: false
nextcloud_available_externally: false
nextcloud_traefik_whitelist: "{{ lan }}"
nextcloud_media_enable: "false"

# directories
nextcloud_data_directory: "{{ docker_home }}/nextcloud"

# network
nextcloud_port_http: "8080"
nextcloud_hostname: "nextcloud"
nextcloud_network_name: "nextcloud"

# docker
nextcloud_container_name: "nextcloud"
nextcloud_image_name: "nextcloud"
nextcloud_image_version: "stable"
#nextcloud_image_version: "latest"
nextcloud_db_container_name: "nextcloud-db"
nextcloud_db_image_name: "mysql"
nextcloud_db_image_version: "8.4"
nextcloud_redis_container_name: "nextcloud-redis"
nextcloud_redis_image_name: "redis"
nextcloud_redis_image_version: "latest"
nextcloud_redis_cpu_shares: 1024

# username / passwords
nextcloud_sql_user: "nextcloud-user"
nextcloud_sql_password: "nextcloud-pass"
nextcloud_sql_root_password: "nextcloud-secret"

# specs
nextcloud_cpu_shares: 1024
nextcloud_memory: "1G"
nextcloud_db_cpu_shares: 1024
nextcloud_db_memory: "1G"
nextcloud_redis_memory: "1G"

# app
nextcloud_env_nextcloud_init_htaccess: "false"

# autoheal
nextcloud_autoheal: "false"
nextcloud_db_autoheal: "false"
nextcloud_redis_autoheal: "false"

# dockflare
nextcloud_dockflare_tunnel: "false"
nextcloud_dockflare_access_group: ""

# homepage
nextcloud_homepage_group: "Apps"
nextcloud_homepage_icon: "nextcloud.png"
nextcloud_homepage_href: "http://{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}:{{ nextcloud_port_http }}"
nextcloud_homepage_showstats: "false"
nextcloud_homepage_widget_key: "your_api_key"
nextcloud_db_homepage_group: "DBs"
nextcloud_db_homepage_icon: "mysql.png"
nextcloud_db_homepage_showstats: "false"
nextcloud_redis_homepage_group: "DBs"
nextcloud_redis_homepage_icon: "redis.png"
nextcloud_redis_homepage_showstats: "false"

# repliqate
nextcloud_repliqate_enabled: "false"
nextcloud_repliqate_engine: "restic"
nextcloud_repliqate_schedule: "@daily 3am"
nextcloud_repliqate_backup_id: "{{ nextcloud_container_name }}"
nextcloud_repliqate_retention: "30d"
nextcloud_db_repliqate_enabled: "false"
nextcloud_db_repliqate_engine: "restic"
nextcloud_db_repliqate_schedule: "@daily 3am"
nextcloud_db_repliqate_backup_id: "{{ nextcloud_db_container_name }}"
nextcloud_db_repliqate_retention: "30d"

# watchtower
nextcloud_watchtower_enable: "false"
nextcloud_db_watchtower_enable: "false"
nextcloud_redis_watchtower_enable: "false"