---
# ANE
ansible_nas_app_name: "LocalAI"
localai_enabled: false
localai_traefik_enabled: false
localai_traefik_whitelist: "{{ lan }}"
localai_data_directory: "{{ docker_home }}/localai"

# network
localai_hostname: "localai"
localai_port_http: "3042"

# docker
# check images available for GPU at: 
# https://hub.docker.com/r/localai/localai
localai_container_name: "local-ai"
localai_image_name: "localai/localai" # CPU and GPU combined image
localai_image_tag: "latest-cpu" # CPU only image

# specs
localai_cpu_shares: 1024
# Minimum (Tiny Models/Audio): 4 GB RAM (e.g., for Whisper Base or tiny quantized LLMs).
# Recommended (Standard LLM): 8 GB – 16 GB RAM (Fits 7B to 13B parameter models).
# Performance (Large Models/GPU): 24 GB+ VRAM/RAM (For 30B+ models or high-speed generation).
localai_memory: "4G"
localai_memory_swap: -1

# app
# see the documentation at: https://localai.io/basics/build/index.html
# See also https://github.com/go-skynet/LocalAI/issues/288
localai_env_rebuild: "false"
localai_env_cmake_args: ""
localai_amd_ai_enabled: true

# autoheal
localai_autoheal_enabled: false

# dockflare
localai_dockflare_enabled: false
localai_dockflare_access_group: ""

# healthcheck
localai_healthcheck_test: ["CMD-SHELL", "curl -f http://127.0.0.1:8080/readyz || exit 1"]
localai_healthcheck_interval: 30s
localai_healthcheck_timeout: 10s
localai_healthcheck_retries: 5
localai_healthcheck_start_period: 60s

# homepage
localai_homepage_group: "Apps"
localai_homepage_icon: "sh-localai"
localai_homepage_href: "http://{{ hostvars[inventory_hostname]['ansible_facts']['default_ipv4']['address'] }}:{{ localai_port_http }}"
localai_homepage_showstats: false

# tinyauth
localai_tinyauth_enabled: false

# watchtower
localai_watchtower_enabled: false