---
# ANE
nebula_sync_proper_name: "nebula-sync"
nebula_sync_enabled: false

# docker
nebula_sync_container_name: "nebula-sync"
nebula_sync_image_name: "ghcr.io/lovelaze/nebula-sync"
nebula_sync_image_tag: "latest"

# specs
nebula_sync_cpu_shares: 1024
nebula_sync_memory: "512M"
nebula_sync_memory_swap: -1

# app
# https://github.com/lovelaze/nebula-sync
nebula_sync_env_primary: "" # http://ph1.example.com|password
nebula_sync_env_replicas: "" # http://ph2.example.com|password,http://ph3.example.com|password
nebula_sync_env_full_sync: "true"
nebula_sync_env_run_gravity: "true"
nebula_sync_env_cron: "0 * * * *"

# autoheal
nebula_sync_autoheal_enabled: false

# homepage
nebula_sync_homepage_group: "Misc"
nebula_sync_homepage_icon: "si-nebula"
nebula_sync_homepage_showstats: false

# watchtower
nebula_sync_watchtower_enabled: false
