---
- name: Verify
  hosts: all
  gather_facts: false
  tasks:
    - ansible.builtin.include_vars:
        file: ../../defaults/main.yml

    - name: Get container state {{ openemr_proper_name }}
      community.docker.docker_container_info:
        name: "{{ openemr_container_name }}"
      register: result

    - name: Get container state {{ openemr_proper_name }} DB
      community.docker.docker_container_info:
        name: "{{ openemr_db_container_name }}"
      register: result_db

    - name: Check {{ openemr_proper_name }} is running
      ansible.builtin.assert:
        that:
          - result.container['State']['Status'] == "running"
          - result.container['State']['Restarting'] == false
          - result_db.container['State']['Status'] == "running"
          - result_db.container['State']['Restarting'] == false