---
# ANE
ansible_nas_app_name: "Odoo"
odoo_enabled: false
odoo_available_externally: false
odoo_traefik_whitelist: "{{ lan }}"
odoo_data_directory: "{{ docker_home }}/odoo"

# network
odoo_hostname: "odoo"
odoo_port_http: "8069"
odoo_port_chat: "8072"

# docker
odoo_container_name: "odoo"
odoo_image_name: "odoo"
odoo_image_tag: "17"
odoo_cpu_shares: "1024"
odoo_memory: "1g"
odoo_db_container_name: "odoo-db"
odoo_db_image_name: "docker.io/library/postgres"
odoo_db_image_tag: "15"
odoo_db_cpu_shares: "1024"
odoo_db_memory: "1g"

# autoheal
odoo_autoheal: "false"
odoo_db_autoheal: "false"

# dockflare
odoo_dockflare_tunnel: "false"
odoo_dockflare_access_group: ""

# homepage
odoo_homepage_group: "Apps"
odoo_homepage_icon: "odoo.png"
odoo_homepage_href: "http://{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}:{{ odoo_port_http }}"
odoo_homepage_showStats: "false"
odoo_db_homepage_group: "DBs"
odoo_db_homepage_icon: "postgres.png"
odoo_db_homepage_showStats: "false"

# watchtower
odoo_watchtower_monitor_only: "true"
odoo_db_watchtower_monitor_only: "true"
