---
# ANE
ansible_nas_app_name: "Tautulli"
tautulli_enabled: false
tautulli_traefik_enabled: false
tautulli_traefik_whitelist: "{{ lan }}"

# directories
tautulli_data_directory: "{{ docker_home }}/tautulli"

# uid / gid
tautulli_user_id: "0"
tautulli_group_id: "0"

# network
tautulli_hostname: "tautulli"
tautulli_port_http: "8185"

# docker
tautulli_container_name: "tautulli"
tautulli_image_name: "lscr.io/linuxserver/tautulli"
tautulli_image_version: "latest"

# specs
tautulli_cpu_shares: 1024
tautulli_memory: "512M"
tautulli_memory_swap: -1

# autoheal
tautulli_autoheal_enabled: false

# dockflare
tautulli_dockflare_enabled: false
tautulli_dockflare_access_group: ""

# healthcheck
tautulli_healthcheck_test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://127.0.0.1:8181/ || exit 1"]
tautulli_healthcheck_interval: 30s
tautulli_healthcheck_timeout: 10s
tautulli_healthcheck_retries: 3
tautulli_healthcheck_start_period: 20s

# homepage
tautulli_homepage_group: "Apps"
tautulli_homepage_icon: "tautulli.png"
tautulli_homepage_href: "http://{{ hostvars[inventory_hostname]['ansible_facts']['default_ipv4']['address'] }}:{{ tautulli_port_http }}"
tautulli_homepage_showstats: false

# linuxserver.io docker mods
tautulli_env_docker_mods: ""
tautulli_env_docker_mods_install_packages: ""
tautulli_env_docker_mods_install_pip_packages: ""

# theme.park themes
# https://docs.theme-park.dev/themes/tautulli/
tautulli_env_docker_mods_tp_theme: ""
tautulli_env_docker_mods_tp_community_theme: ""
tautulli_env_docker_mods_tp_domain: ""
tautulli_env_docker_mods_tp_addon: ""

# repliqate
tautulli_repliqate_enabled: false
tautulli_repliqate_engine: "restic"
tautulli_repliqate_schedule: "@daily 3am"
tautulli_repliqate_backup_id: "{{ tautulli_container_name }}"
tautulli_repliqate_retention: "30d"

# tinyauth
tautulli_tinyauth_enabled: false

# watchtower
tautulli_watchtower_enabled: false