---
# ANE
ansible_nas_app_name: "Focalboard"
focalboard_enabled: false
focalboard_traefik_enabled: false
focalboard_traefik_whitelist: "{{ lan }}"
focalboard_data_directory: "{{ docker_home }}/focalboard"

# network
focalboard_hostname: "focalboard"
focalboard_port_http: "3047"

# docker
focalboard_container_name: "focalboard"
focalboard_image_name: "mattermost/focalboard"
focalboard_image_tag: "latest"

# specs
focalboard_cpu_shares: 1024
focalboard_memory: "1G"
focalboard_memory_swap: -1

# autoheal
focalboard_autoheal_enabled: false

# dockflare
focalboard_dockflare_enabled: false
focalboard_dockflare_access_group: ""

# homepage
focalboard_homepage_group: "Apps"
focalboard_homepage_icon: "focalboard.png"
focalboard_homepage_href: "http://{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}:{{ focalboard_port_http }}"
focalboard_homepage_showstats: false

# repliqate
focalboard_repliqate_enabled: false
focalboard_repliqate_engine: "restic"
focalboard_repliqate_schedule: "@daily 3am"
focalboard_repliqate_backup_id: "{{ focalboard_container_name }}"
focalboard_repliqate_retention: "30d"

# tinyauth
focalboard_tinyauth_enabled: false

# watchtower
focalboard_watchtower_enabled: false
