---
# ANE
ansible_nas_app_name: "Semaphore"
semaphore_enabled: false
semaphore_available_externally: false
semaphore_traefik_whitelist: "{{ lan }}"

# directories
semaphore_data_directory: "{{ docker_home }}/semaphore"

# network
semaphore_hostname: "semaphore"
semaphore_port_http: "3001"

# docker
semaphore_container_name: "semaphore"
semaphore_image_name: "semaphoreui/semaphore"
semaphore_image_tag: "latest"
semaphore_cpu_shares: "1024"
semaphore_memory: "1g"

# app
semaphore_env_semaphore_db_dialect: "bolt"
semaphore_env_semaphore_admin_name: "admin"
semaphore_env_semaphore_admin_password: "{{ ansible_nas_app_admin_password }}"
semaphore_env_semaphore_admin_email: "admin@localhost"
semaphore_env_semaphore_admin: "admin"

# autoheal
semaphore_autoheal: "false"

# dockflare
semaphore_dockflare_tunnel: "false"
semaphore_dockflare_access_group: ""

# homepage
semaphore_homepage_group: "Apps"
semaphore_homepage_icon: "semaphore.png"
semaphore_homepage_href: "http://{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}:{{ semaphore_port_http }}"
semaphore_homepage_showstats: "false"

# repliqate
semaphore_repliqate_enabled: "false"
semaphore_repliqate_engine: "restic"
semaphore_repliqate_schedule: "@daily 3am"
semaphore_repliqate_backup_id: "{{ semaphore_container_name }}"
semaphore_repliqate_retention: "30d"

# watchtower
semaphore_watchtower_enable: "false"