---
- name: Start {{ ansible_nas_app_name }}
  block:
    - name: Create {{ ansible_nas_app_name }} Directories
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
      with_items:
        - "{{ threadfin_data_directory }}"

    - name: Create {{ ansible_nas_app_name }} Container
      community.docker.docker_container:
        container_default_behavior: "compatibility"
        name: "{{ threadfin_container_name }}"
        hostname: "{{ threadfin_container_name }}"
        image: "{{ threadfin_image_name }}:{{ threadfin_image_version }}"
        pull: true
        ports:
          - "{{ threadfin_port_http }}:34400"
        env:
          PUID: "{{ threadfin_user_id }}"
          PGID: "{{ threadfin_group_id }}"
          TZ: "{{ ansible_nas_timezone }}"
        volumes:
          - "{{ threadfin_data_directory }}:/home/threadfin/conf"
        labels:
          autoheal: "{{ threadfin_autoheal }}"
          com.centurylinklabs.watchtower.enable: "{{ threadfin_watchtower_enable }}"
          dockflare.enable: "false"
          homepage.name: "{{ ansible_nas_app_name }}"
          homepage.group: "{{ threadfin_homepage_group }}"
          homepage.icon: "{{ threadfin_homepage_icon }}"
          homepage.href: "{{ threadfin_homepage_href }}"
          homepage.description: "{{ 'M3U proxy for media servers' if homepage_show_description else omit }}"
          homepage.server: "my-docker"
          homepage.container: "{{ threadfin_container_name }}"
          homepage.showStats: "{{ threadfin_homepage_showstats }}"
          homepage.siteMonitor: "http://{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}:{{ threadfin_port_http }}"
          homepage.widget.type: "xteve"
          homepage.widget.url: "http://{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}:{{ threadfin_port_http }}"
          repliqate.enabled: "{{ threadfin_repliqate_enabled }}"
          repliqate.engine: "{{ threadfin_repliqate_engine }}"
          repliqate.schedule: "{{ threadfin_repliqate_schedule }}"
          repliqate.backup_id: "{{ threadfin_repliqate_backup_id }}"
          repliqate.retention: "{{ threadfin_repliqate_retention }}"
          traefik.enable: "false"
          wud.tag.include: '^\d+\.\d+\.\d+$'
          wud.tag.transform.type: "semver"
          wud.link.template: "https://hub.docker.com/r/fyb3roptik/threadfin"
        cpu_shares: "{{ threadfin_cpu_shares }}"
        memory: "{{ threadfin_memory }}"
        restart_policy: unless-stopped
  when: threadfin_enabled is true

- name: Stop {{ ansible_nas_app_name }}
  block:
    - name: Stop {{ ansible_nas_app_name }} Container
      community.docker.docker_container:
        name: "{{ threadfin_container_name }}"
        state: absent
  when: threadfin_enabled is false

- name: Data Archive {{ ansible_nas_app_name }}
  include_role:
    name: ansible-nas-archive
  vars:
    target_data_dir: "{{ threadfin_data_directory }}"
  when:
    - archive_app_data_enabled is true
    - threadfin_enabled is false