---
# ANE
ansible_nas_app_name: "OctoPrint"
octoprint_enabled: false
octoprint_traefik_enabled: false
octoprint_traefik_whitelist: "{{ lan }}"

# directories
octoprint_data_directory: "{{ docker_home }}/octoprint"

# network
octoprint_port_http: "3050"
octoprint_hostname: "octoprint"

# docker
octoprint_container_name: "octoprint"
octoprint_image_name: "octoprint/octoprint"
octoprint_image_version: "latest"

# devices
octoprint_enable_printer: false
octoprint_printer_mountpoint: "/dev/ttyUSB0"

octoprint_enable_webcam: false
octoprint_webcam_mountpoint: "/dev/video0"

# specs
octoprint_cpu_shares: 1024
octoprint_memory: "1G"
octoprint_memory_swap: -1

# autoheal
octoprint_autoheal_enabled: false

# dockflare
octoprint_dockflare_enabled: false
octoprint_dockflare_access_group: ""

# homepage
octoprint_homepage_group: "Apps"
octoprint_homepage_icon: "octoprint.png"
octoprint_homepage_href: "http://{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}:{{ octoprint_port_http }}"
octoprint_homepage_showstats: false
octoprint_homepage_widget_key: ""

# tinyauth
octoprint_tinyauth_enabled: false

# watchtower
octoprint_watchtower_enabled: false