---
ansible_nas_app_name: "OctoPrint"

octoprint_enabled: false
octoprint_available_externally: false
octoprint_traefik_whitelist: "{{ lan }}"

# directories
octoprint_data_directory: "{{ docker_home }}/octoprint"

# network
octoprint_port: "8095"
octoprint_hostname: "octoprint"

# docker
octoprint_container_name: "octoprint"
octoprint_image_name: "octoprint/octoprint"
octoprint_image_version: "latest"
octoprint_cpu_shares: 1024

# devices
octoprint_printer_mountpoint: "/dev/ttyUSB0"

octoprint_enable_webcam: false
octoprint_webcam_mountpoint: "/dev/video0"

# specs
octoprint_memory: 1g

# autoheal
octoprint_autoheal: "false"

# watchtower
octoprint_watchtower_monitor_only: "true"