---
# ANE
ansible_nas_app_name: "Glances"
glances_enabled: false
glances_traefik_enabled: false
glances_traefik_whitelist: "{{ lan }}"

# network
glances_hostname: "glances"
glances_port_http: "61208"
glances_port_two: "61209"

# security options
glances_security_options:
  - "apparmor=unconfined"

# docker
glances_container_name: "glances"
glances_image_name: "nicolargo/glances" 
glances_image_version: "latest" # ubuntu-latest-full for NVIDIA GPU support

# specs
glances_cpu_shares: 1024
glances_memory: "512M"
glances_memory_swap: -1

# app
glances_env_opt: "-w"

# autoheal
glances_autoheal_enabled: false

# dockflare
glances_dockflare_enabled: false
glances_dockflare_access_group: ""

# healthcheck
glances_healthcheck_interval: 30s
glances_healthcheck_timeout: 5s
glances_healthcheck_retries: 3
glances_healthcheck_start_period: 15s

# homepage
glances_homepage_group: "Apps"
glances_homepage_icon: "glances.png"
glances_homepage_href: "http://{{ hostvars[inventory_hostname]['ansible_facts']['default_ipv4']['address'] }}:{{ glances_port_http }}"
glances_homepage_showstats: false

# tinyauth
glances_tinyauth_enabled: false

# watchtower
glances_watchtower_enabled: false
