---
# ANE
ansible_nas_app_name: "Mylar"
mylar_enabled: false
mylar_available_externally: false
mylar_traefik_whitelist: "{{ lan }}"

# directories
mylar_data_directory: "{{ docker_home }}/mylar"
mylar_comics_directory: "{{ comics_root }}"
mylar_downloads_directory: "{{ downloads_root }}"

# uid / gid
mylar_user_id: "0"
mylar_group_id: "0"

# network
mylar_hostname: "mylar"
mylar_port_http: "8585"

# docker
mylar_container_name: "mylar"
mylar_image_name: "lscr.io/linuxserver/mylar3"
mylar_image_version: "latest"

# specs
mylar_cpu_shares: 1024
mylar_memory: "1G"

# autoheal
mylar_autoheal: "false"

# dockflare
mylar_dockflare_tunnel: "false"
mylar_dockflare_access_group: ""

# homepage
mylar_homepage_group: "Media Management"
mylar_homepage_icon: "mylar.png"
mylar_homepage_href: "http://{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}:{{ mylar_port_http }}"
mylar_homepage_widget_key: "insert_your_key_here"

# linuxserver.io docker mods
mylar_env_docker_mods: ""
mylar_env_docker_mods_install_packages: ""
mylar_env_docker_mods_install_pip_packages: ""

# theme.park themes
# https://docs.theme-park.dev/themes/mylar3/
mylar_env_docker_mods_tp_theme: ""
mylar_env_docker_mods_tp_community_theme: ""
mylar_env_docker_mods_tp_domain: ""
mylar_env_docker_mods_tp_addon: ""

# repliqate
mylar_repliqate_enabled: "false"
mylar_repliqate_engine: "restic"
mylar_repliqate_schedule: "@daily 3am"
mylar_repliqate_backup_id: "{{ mylar_container_name }}"
mylar_repliqate_retention: "30d"

# tinyauth
mylar_tinyauth_enabled: false

# watchtower
mylar_watchtower_enable: "false"