---
- name: Start {{ ansible_nas_app_name }}
  block:
    - name: Create {{ ansible_nas_app_name }} Directories
      file:
        path: "{{ item }}"
        state: directory
      with_items:
        - "{{ odoo_data_directory }}/data"
        - "{{ odoo_data_directory }}/db"
        - "{{ odoo_data_directory }}/config"
        - "{{ odoo_data_directory }}/addons"

    - name: Create {{ ansible_nas_app_name }} DB Container
      community.docker.docker_container:
        container_default_behavior: "compatibility"
        name: "{{ odoo_db_container_name }}"
        hostname: "{{ odoo_db_container_name }}"
        image: "{{ odoo_db_image_name }}:{{ odoo_db_image_tag }}"
        pull: true
        volumes:
          - "{{ odoo_data_directory }}/db:/var/lib/postgresql/data/pgdata"
        network_mode: bridge
        env:
          POSTGRES_DB: "postgres"
          POSTGRES_USER: "odoo"
          POSTGRES_PASSWORD: "odoo"
          PGDATA: "/var/lib/postgresql/data/pgdata"
        labels:
          autoheal: "{{ odoo_db_autoheal }}"
          com.centurylinklabs.watchtower.enable: "{{ odoo_db_watchtower_enable }}"
          dockflare.enable: "false"
          homepage.name: "{{ ansible_nas_app_name }} PostgreSQL"
          homepage.group: "{{ odoo_db_homepage_group }}"
          homepage.icon: "{{ odoo_db_homepage_icon }}"
          homepage.description: "{{ 'PostgreSQL Database Management System' if homepage_show_description else omit }}"
          homepage.showStats: "{{ odoo_db_homepage_showstats }}"
          traefik.enable: "false"
          wud.tag.include: '^\d+\.\d+.*$'
          wud.tag.transform.type: "semver"
          wud.link.template: "https://hub.docker.com/_/postgres"
        cpu_shares: "{{ odoo_db_cpu_shares }}"
        memory: "{{ odoo_db_memory }}"
        restart_policy: unless-stopped

    - name: Create {{ ansible_nas_app_name }} Container
      community.docker.docker_container:
        container_default_behavior: "compatibility"
        name: "{{ odoo_container_name }}"
        hostname: "{{ odoo_container_name }}"
        image: "{{ odoo_image_name }}:{{ odoo_image_tag }}"
        pull: true
        user: root
        links:
          - "{{ odoo_db_container_name }}"
        ports:
          - "{{ odoo_port_http }}:8069"
          - "{{ odoo_port_chat }}:8072"
        volumes:
          - "{{ odoo_data_directory }}/data:/var/lib/odoo"  # needed?
          - "{{ odoo_data_directory }}/config:/etc/odoo"
          - "{{ odoo_data_directory }}/addons:/mnt/extra-addons"
        network_mode: bridge
        env:
          HOST: "{{ odoo_db_container_name }}"
          USER: "odoo"
          PASSWORD: "odoo"
          TZ: "{{ ansible_nas_timezone }}"
        labels:
          autoheal: "{{ odoo_autoheal }}"
          com.centurylinklabs.watchtower.enable: "{{ odoo_watchtower_enable }}"
          dockflare.enable: "{{ odoo_dockflare_tunnel }}"
          dockflare.access.group: "{{ odoo_dockflare_access_group }}"
          dockflare.hostname: "{{ odoo_hostname }}.{{ ansible_nas_domain }}"
          dockflare.service: "http://{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}:{{ odoo_port_http }}"
          homepage.name: "{{ ansible_nas_app_name }}"
          homepage.group: "{{ odoo_homepage_group }}"
          homepage.icon: "{{ odoo_homepage_icon }}"
          homepage.href: "{{ odoo_homepage_href }}"
          homepage.description: "{{ 'Open Source Apps To Grow Your Business.' if homepage_show_description else omit }}"
          homepage.siteMonitor: "http://{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}:{{ odoo_port_http }}"
          homepage.server: "my-docker"
          homepage.container: "odoo"
          homepage.showStats: "{{ odoo_homepage_showstats }}"
          traefik.enable: "{{ odoo_available_externally | string }}"
          traefik.http.routers.odoo.rule: "Host(`{{ odoo_hostname }}.{{ ansible_nas_domain }}`)"
          traefik.http.routers.odoo.tls.certresolver: "letsencrypt"
          traefik.http.routers.odoo.tls.domains[0].main: "{{ ansible_nas_domain }}"
          traefik.http.routers.odoo.tls.domains[0].sans: "*.{{ ansible_nas_domain }}"
          traefik.http.routers.frontend.middlewares: "{{ odoo_hostname }}"
          traefik.http.routers.odoo.middlewares: "{{ odoo_hostname }}@docker"
          traefik.http.middlewares.odoo.IPAllowList.sourcerange: "{{ odoo_traefik_whitelist }}"
          traefik.http.services.odoo.loadbalancer.server.port: "8069"
          wud.tag.include: '^\d+\.\d+.*$'
          wud.tag.transform.type: "semver"
          wud.link.template: "https://hub.docker.com/_/odoo"
        cpu_shares: "{{ odoo_cpu_shares }}"
        memory: "{{ odoo_memory }}"
        restart_policy: unless-stopped

    - name: Access {{ ansible_nas_app_name }} at
      ansible.builtin.debug:
        msg: >-
              {{
                ['http://' + hostvars[inventory_hostname]['ansible_default_ipv4']['address'] + ':' + (odoo_port_http | string)] +
                (['https://' + odoo_hostname + '.' + ansible_nas_domain] if (odoo_available_externally is true or odoo_dockflare_tunnel is true) else [])
              }}
  when: odoo_enabled is true

- name: Stop {{ ansible_nas_app_name }}
  block:
    - name: Stop {{ ansible_nas_app_name }} Container
      community.docker.docker_container:
        name: "{{ odoo_container_name }}"
        state: absent

    - name: Stop {{ ansible_nas_app_name }} DB Container
      community.docker.docker_container:
        name: "{{ odoo_db_container_name }}"
        state: absent
  when: odoo_enabled is false

- name: Data Archive {{ ansible_nas_app_name }}
  block:
    - name: Check for {{ ansible_nas_app_name }} Data Directory
      stat:
        path: "{{ odoo_data_directory }}"
      register: dir_stat

    - name: Archive {{ ansible_nas_app_name }} Data Directory
      ansible.builtin.archive:
        path: "{{ odoo_data_directory }}"
        dest: "{{ docker_home }}/{{ ansible_nas_app_name | lower }}.zip"
        force_archive: true
        format: zip
        owner: ansible-nas
        group: ansible-nas
        mode: u=rw,g=rw
        remove: true
      when: dir_stat.stat.exists
  when: odoo_enabled is false and archive_app_data_enabled is true
