---
# ANE
ansible_nas_app_name: "Virtual Tabletop"
virtualtabletop_enabled: false
virtualtabletop_available_externally: false
virtualtabletop_traefik_whitelist: "{{ lan }}"

# directories
virtualtabletop_data_directory: "{{ docker_home }}/virtualtabletop"

# docker
virtualtabletop_container_name: "virtual-tabletop"
virtualtabletop_image_name: "arnoldsmith86/virtualtabletop"
virtualtabletop_image_tag: "latest"

# network
virtualtabletop_port_http: "8272"
virtualtabletop_hostname: "virtualtabletop"

# specs
virtualtabletop_cpu_shares: 1024
virtualtabletop_memory: "1G"

# app
virtualtabletop_env_adminurl: "/admin"
virtualtabletop_env_allowpubliclibraryedits: "false"
virtualtabletop_env_customtab: "Virtual Tabletop ({{ ansible_nas_hostname }})"
#virtualtabletop_env_externalurl: "https://{{ virtualtabletop_hostname }}.{{ ansible_nas_domain }}"
virtualtabletop_env_externalurl: "http://{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}:{{ virtualtabletop_port_http }}"
virtualtabletop_env_forcetracing: "false"
virtualtabletop_env_minifyjavascript: "false"
virtualtabletop_env_servername: "{{ ansible_nas_hostname }}"
virtualtabletop_env_simulateserverlag: "0"
virtualtabletop_env_urlprefix: ""

# autoheal
virtualtabletop_autoheal: "false"

# dockflare
virtualtabletop_dockflare_tunnel: "false"
virtualtabletop_dockflare_access_group: ""

# homepage
virtualtabletop_homepage_group: "Apps"
virtualtabletop_homepage_icon: "https://raw.githubusercontent.com/ArnoldSmith86/virtualtabletop/refs/heads/main/assets/branding/android-192.png"
virtualtabletop_homepage_href: "http://{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}:{{ virtualtabletop_port_http }}"
virtualtabletop_homepage_showstats: "false"

# watchtower
virtualtabletop_watchtower_enable: "false"
