---
# ANE
ansible_nas_app_name: "Stalwart Mail"
stalwart_enabled: false
stalwart_available_externally: false
stalwart_traefik_whitelist: "{{ lan }}"
stalwart_data_directory: "{{ docker_home }}/stalwart"

# network
stalwart_hostname: "stalwart"
stalwart_port_http: "3008"

# docker
stalwart_container_name: "stalwart-mail"
stalwart_image_name: "ghcr.io/stalwartlabs/stalwart"
stalwart_image_tag: "latest"
stalwart_cpu_shares: "1024"
stalwart_memory: "1G"

# autoheal
stalwart_autoheal: "false"

# dockflare
stalwart_dockflare_tunnel: "false"
stalwart_dockflare_access_group: ""

# homepage
stalwart_homepage_group: "Apps"
stalwart_homepage_icon: "stalwart.png"
stalwart_homepage_href: "http://{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}:{{ stalwart_port_http }}"
stalwart_homepage_showstats: "false"

# repliqate
stalwart_repliqate_enabled: "false"
stalwart_repliqate_engine: "restic"
stalwart_repliqate_schedule: "@daily 3am"
stalwart_repliqate_backup_id: "{{ stalwart_container_name }}"
stalwart_repliqate_retention: "30d"

# watchtower
stalwart_watchtower_enable: "false"