---
- name: Start {{ mybibliotheca_proper_name }}
  block:
    - name: Create {{ mybibliotheca_proper_name }} Directories
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
      with_items:
        - "{{ mybibliotheca_data_directory }}"
        - "{{ mybibliotheca_data_directory }}/data"

    - name: Set {{ mybibliotheca_proper_name }} FQDN var overrides
      ansible.builtin.set_fact:
        mybibliotheca_homepage_href: "https://{{ mybibliotheca_hostname }}.{{ ansible_nas_domain }}"
      when: mybibliotheca_traefik_enabled | bool or mybibliotheca_dockflare_enabled | bool

    - name: Create {{ mybibliotheca_proper_name }} Container
      community.docker.docker_container:
        container_default_behavior: "compatibility"
        name: "{{ mybibliotheca_container_name }}"
        hostname: "{{ mybibliotheca_container_name }}"
        image: "{{ mybibliotheca_image_name }}:{{ mybibliotheca_image_tag }}"
        pull: true
        volumes:
          - "{{ mybibliotheca_data_directory }}/data:/app/data"
        ports:
          - "{{ mybibliotheca_port_http }}:5054"
        env:
          WORKERS: "6"
          TZ: "{{ ansible_nas_timezone }}"
        labels:
          autoheal: "{{ mybibliotheca_autoheal_enabled | ternary('true', 'false') }}"
          com.centurylinklabs.watchtower.enable: "{{ mybibliotheca_watchtower_enabled | ternary('true', 'false') }}"
          dockflare.enable: "{{ mybibliotheca_dockflare_enabled | ternary('true', 'false') }}"
          dockflare.access.group: "{{ mybibliotheca_dockflare_access_group }}"
          dockflare.hostname: "{{ mybibliotheca_hostname }}.{{ ansible_nas_domain }}"
          dockflare.service: "http://{{ hostvars[inventory_hostname]['ansible_facts']['default_ipv4']['address'] }}:{{ mybibliotheca_port_http }}"
          homepage.name: "{{ mybibliotheca_proper_name }}"
          homepage.group: "{{ mybibliotheca_homepage_group }}"
          homepage.icon: "{{ mybibliotheca_homepage_icon }}"
          homepage.href: "{{ mybibliotheca_homepage_href }}"
          homepage.description: "{{ 'Bibliotheca is a self-hosted personal library and reading tracker web app built with Flask.' if homepage_show_description else omit }}"
          homepage.server: "my-docker"
          homepage.container: "{{ mybibliotheca_container_name }}"
          homepage.showStats: "{{ mybibliotheca_homepage_showstats | ternary('true', 'false') }}"
          homepage.siteMonitor: "http://{{ hostvars[inventory_hostname]['ansible_facts']['default_ipv4']['address'] }}:{{ mybibliotheca_port_http }}"
          repliqate.enabled: "{{ mybibliotheca_repliqate_enabled | ternary('true', 'false') }}"
          repliqate.engine: "{{ mybibliotheca_repliqate_engine }}"
          repliqate.schedule: "{{ mybibliotheca_repliqate_schedule }}"
          repliqate.backup_id: "{{ mybibliotheca_repliqate_backup_id }}"
          repliqate.retention: "{{ mybibliotheca_repliqate_retention }}"
          traefik.enable: "{{ mybibliotheca_traefik_enabled | ternary('true', 'false') }}"
          traefik.http.routers.mybibliotheca.rule: "Host(`{{ mybibliotheca_hostname }}.{{ ansible_nas_domain }}`)"
          traefik.http.routers.mybibliotheca.tls.certresolver: "letsencrypt"
          traefik.http.routers.mybibliotheca.tls.domains[0].main: "{{ ansible_nas_domain }}"
          traefik.http.routers.mybibliotheca.tls.domains[0].sans: "*.{{ ansible_nas_domain }}"
          traefik.http.routers.mybibliotheca.middlewares: "mybibliotheca@docker{{ ',tinyauth-auth@docker' if mybibliotheca_tinyauth_enabled | bool else '' }}"
          traefik.http.middlewares.mybibliotheca.IPAllowList.sourcerange: "{{ mybibliotheca_traefik_whitelist }}"
          traefik.http.services.mybibliotheca.loadbalancer.server.port: "5054"
          wud.tag.include: '^\d+\.\d+\.\d+$'
          wud.tag.transform.type: "semver"
          wud.link.template: "https://hub.docker.com/r/pickles4evaaaa/mybibliotheca"
        cpu_shares: "{{ mybibliotheca_cpu_shares }}"
        memory: "{{ mybibliotheca_memory }}"
        memory_swap: "{{ mybibliotheca_memory_swap }}"
        restart_policy: unless-stopped

    - name: Access {{ mybibliotheca_proper_name }} at
      ansible.builtin.debug:
        msg: >-
              {{
                ['http://' + hostvars[inventory_hostname]['ansible_facts']['default_ipv4']['address'] + ':' + (mybibliotheca_port_http | string)] +
                (['https://' + mybibliotheca_hostname + '.' + ansible_nas_domain] if (mybibliotheca_traefik_enabled is true or mybibliotheca_dockflare_enabled is true) else [])
              }}
  when: mybibliotheca_enabled is true

- name: Stop {{ mybibliotheca_proper_name }}
  block:
    - name: Stop {{ mybibliotheca_proper_name }} Container
      community.docker.docker_container:
        name: "{{ mybibliotheca_container_name }}"
        state: absent
  when: mybibliotheca_enabled is false

- name: Data Archive {{ mybibliotheca_proper_name }}
  include_role:
    name: ansible-nas-archive
  vars:
    target_data_dir: "{{ mybibliotheca_data_directory }}"
  when:
    - archive_app_data_enabled is true
    - mybibliotheca_enabled is false