---
# ANE
ansible_nas_app_name: "Transmission"
transmission_enabled: false
transmission_available_externally: false
transmission_traefik_whitelist: "{{ lan }}"

# directories
transmission_data_directory: "{{ docker_home }}/transmission"
transmission_download_directory: "{{ downloads_root }}"
transmission_watch_directory: "{{ torrents_root }}"

# uid / gid
transmission_user_id: "0"
transmission_group_id: "0"

# network
transmission_port_http: "9092"
transmission_port_bt: "51414"
transmission_hostname: "transmission"

transmission_timezone: "{{ ansible_nas_timezone }}"

transmission_container_name: "transmission"
transmission_image_name: "lscr.io/linuxserver/transmission"
transmission_image_version: "latest"

# specs
transmission_cpu_shares: 1024
transmission_memory: 1g

# autoheal
transmission_autoheal: "false"

# dockflare
transmission_dockflare_tunnel: "false"
transmission_dockflare_access_group: ""

# homepage
transmission_homepage_group: "Download Tools"
transmission_homepage_icon: "transmission.png"
transmission_homepage_href: "http://{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}:{{ transmission_port_http }}"
transmission_homepage_showstats: "false"
transmission_homepage_widget_user: "admin"
transmission_homepage_widget_password: "your password"

# linuxserver.io docker mods
# https://mods.linuxserver.io/?mod=transmission
transmission_env_docker_mods: ""
transmission_env_docker_mods_install_packages: ""
transmission_env_docker_mods_install_pip_packages: ""

# theme.park themes
# https://docs.theme-park.dev/themes/transmission/
transmission_env_docker_mods_tp_theme: ""
transmission_env_docker_mods_tp_community_theme: ""
transmission_env_docker_mods_tp_domain: ""
transmission_env_docker_mods_tp_addon: ""

# repliqate
transmission_repliqate_enabled: "false"
transmission_repliqate_engine: "restic"
transmission_repliqate_schedule: "@daily 3am"
transmission_repliqate_backup_id: "{{ transmission_container_name }}"
transmission_repliqate_retention: "30d"

# watchtower
transmission_watchtower_enable: "false"
