---
ansible_nas_app_name: "Transmission"

transmission_enabled: false
transmission_available_externally: false
transmission_traefik_whitelist: "{{ lan }}"

# directories
transmission_data_directory: "{{ docker_home }}/transmission"
transmission_download_directory: "{{ downloads_root }}"
transmission_watch_directory: "{{ torrents_root }}"

# uid / gid
transmission_user_id: "0"
transmission_group_id: "0"

# network
transmission_webui_port: "9092"
transmission_external_port: "51414"
transmission_hostname: "transmission"

transmission_timezone: "{{ ansible_nas_timezone }}"

transmission_container_name: "transmission"
transmission_image_name: "linuxserver/transmission"
transmission_image_version: "latest"

# specs
transmission_cpu_shares: 1024
transmission_memory: 1g

# autoheal
transmission_autoheal: "false"

# homepage
transmission_homepage_group: "Download Tools"
transmission_homepage_icon: "transmission.png"
transmission_homepage_href: "http://{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}:{{ transmission_webui_port }}"
transmission_homepage_showStats: "false"
transmission_homepage_widget_user: "admin"
transmission_homepage_widget_password: "your password"

# watchtower
transmission_watchtower_monitor_only: "true"
