---
# ANE
ansible_nas_app_name: "Luanti"
luanti_enabled: false
luanti_available_externally: false
luanti_traefik_whitelist: "{{ lan }}"

# directories
luanti_data_directory: "{{ docker_home }}/luanti"

# docker
luanti_container_name: "luanti"
luanti_image_name: "lscr.io/linuxserver/luanti"
luanti_image_tag: "latest"

# uid / gid
luanti_user_id: "1000"
luanti_group_id: "1000"

# network
luanti_port: "30000"
luanti_hostname: "luanti"

# specs
luanti_cpu_shares: 1024
luanti_memory: "1G"
luanti_memory_swap: -1

# autoheal
luanti_autoheal: "false"

# homepage
luanti_homepage_group: "Misc"
luanti_homepage_icon: "si-luanti"
luanti_homepage_showstats: "false"

# linuxserver.io docker mods
luanti_env_docker_mods: ""
luanti_env_docker_mods_install_packages: ""
luanti_env_docker_mods_install_pip_packages: ""

# repliqate
luanti_repliqate_enabled: "false"
luanti_repliqate_engine: "restic"
luanti_repliqate_schedule: "@daily 3am"
luanti_repliqate_backup_id: "{{ luanti_container_name }}"
luanti_repliqate_retention: "30d"

# watchtower
luanti_watchtower_enable: "false"
