---
# ANE
ansible_nas_app_name: "Proxmox Datacenter Manager"
pdm_enabled: false
pdm_available_externally: false
pdm_traefik_whitelist: "{{ lan }}"

# directories
pdm_data_directory: "{{ docker_home }}/pdm"

# docker
pdm_container_name: "pdm"
pdm_image_name: "ghcr.io/longqt-sea/proxmox-datacenter-manager"
pdm_image_tag: "latest"

# network
pdm_hostname: "pdm"
pdm_network_name: "proxmox"
pdm_port_http: "3085"
pdm_port_ssh: "2222"

# specs
pdm_cpu_shares: 1024
pdm_memory: "1G"
pdm_memory_swap: -1

# app
pdm_root_password: "{{ ansible_nas_app_admin_password }}"

# autoheal
pdm_autoheal: "false"

# dockflare
pdm_dockflare_tunnel: false
pdm_dockflare_access_group: ""

# homepage
pdm_homepage_group: "Apps"
pdm_homepage_icon: "proxmox.png"
pdm_homepage_href: "http://{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}:{{ pdm_port_http }}"
pdm_homepage_showstats: "false"

# repliqate
pdm_repliqate_enabled: false
pdm_repliqate_engine: "restic"
pdm_repliqate_schedule: "@daily 3am"
pdm_repliqate_backup_id: "{{ pdm_container_name }}"
pdm_repliqate_retention: "30d"

# tinyauth
pdm_tinyauth_enabled: false

# watchtower
pdm_watchtower_enable: false
