# -------------------------------------------------------------------------
# NOTIFICATIONS
# -------------------------------------------------------------------------
configs:
{% for target in mailrise_targets %}
  {{ target.email }}:
    urls:
    {% for url in target.urls %}
      - {{ url }}
    {% endfor %}
{% endfor %}

# -------------------------------------------------------------------------
# AUTHENTICATION
# -------------------------------------------------------------------------
smtp:
  auth:
    basic:
      {{ mailrise_smtp_username }}:{{ mailrise_smtp_password }}
