---
- name: Start {{ ansible_nas_app_name }}
  block:
    - name: Create {{ ansible_nas_app_name }} Directories
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
      with_items:
        - "{{ christmas_community_data_directory }}"

    - name: Create {{ ansible_nas_app_name }} Container
      community.docker.docker_container:
        container_default_behavior: "compatibility"
        name: "{{ christmas_community_container_name }}"
        hostname: "{{ christmas_community_container_name }}"
        image: "{{ christmas_community_image_name }}:{{ christmas_community_image_tag }}"
        pull: true
        volumes:
          - "{{ christmas_community_data_directory }}:/data"
        ports:
          - "{{ christmas_community_port_http }}:80"
        env:
          SMILE: 'true'
          TABLE: 'true'
          SINGLE_LIST: 'false'
          NODE_OPTIONS: "--max-http-header-size=32768"
          TZ: "{{ ansible_nas_timezone }}"
        labels:
          autoheal: "{{ christmas_community_autoheal | string }}"
          com.centurylinklabs.watchtower.enable: "{{ christmas_community_watchtower_enabled| string }}"
          dockflare.enable: "{{ christmas_community_dockflare_enabled | string }}"
          dockflare.access.group: "{{ christmas_community_dockflare_access_group }}"
          dockflare.hostname: "{{ christmas_community_hostname }}.{{ ansible_nas_domain }}"
          dockflare.service: "http://{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}:{{ christmas_community_port_http }}"
          homepage.name: "{{ ansible_nas_app_name }}"
          homepage.group: "{{ christmas_community_homepage_group }}"
          homepage.href: "{{ christmas_community_homepage_href }}"
          homepage.icon: "{{ christmas_community_homepage_icon }}"
          homepage.siteMonitor: "http://{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}:{{ christmas_community_port_http }}"
          homepage.description: "{{ 'Christmas lists for families' if homepage_show_description else omit }}"
          homepage.server: "my-docker"
          homepage.container: "christmas-community"
          homepage.showStats: "{{ christmas_community_homepage_showstats | string }}"
          repliqate.enabled: "{{ christmas_community_repliqate_enabled | string }}"
          repliqate.engine: "{{ christmas_community_repliqate_engine }}"
          repliqate.schedule: "{{ christmas_community_repliqate_schedule }}"
          repliqate.backup_id: "{{ christmas_community_repliqate_backup_id }}"
          repliqate.retention: "{{ christmas_community_repliqate_retention }}"
          traefik.enable: "{{ christmas_community_available_externally | string }}"
          traefik.http.routers.christmascommunity.rule: "Host(`{{ christmas_community_hostname }}.{{ ansible_nas_domain }}`)"
          traefik.http.routers.christmascommunity.tls.certresolver: "letsencrypt"
          traefik.http.routers.christmascommunity.tls.domains[0].main: "{{ ansible_nas_domain }}"
          traefik.http.routers.christmascommunity.tls.domains[0].sans: "*.{{ ansible_nas_domain }}"
          traefik.http.routers.christmascommunity.middlewares: "christmascommunity@docker{{ ',tinyauth-auth@docker' if christmas_community_tinyauth_enabled | bool else '' }}"
          traefik.http.middlewares.christmascommunity.IPAllowList.sourcerange: "{{ christmas_community_traefik_whitelist }}"
          traefik.http.services.christmas_community.loadbalancer.server.port: "80"
          wud.tag.include: '^\d+\.\d+\.\d+.*$'
          wud.tag.transform.type: "semver"
          wud.link.template: "https://hub.docker.com/r/wingysam/christmas-community"
        cpu_shares: "{{ christmas_community_cpu_shares }}"
        memory: "{{ christmas_community_memory }}"
        memory_swap: "{{ christmas_community_memory_swap }}"
        restart_policy: unless-stopped

    - name: Access {{ ansible_nas_app_name }} at
      ansible.builtin.debug:
        msg: >-
              {{
                ['http://' + hostvars[inventory_hostname]['ansible_default_ipv4']['address'] + ':' + (christmas_community_port_http | string)] +
                (['https://' + christmas_community_hostname + '.' + ansible_nas_domain] if (christmas_community_available_externally is true or christmas_community_dockflare_enabled is true) else [])
              }}
  when: christmas_community_enabled is true

- name: Stop {{ ansible_nas_app_name }}
  block:
    - name: Stop {{ ansible_nas_app_name }} Container
      community.docker.docker_container:
        name: "{{ christmas_community_container_name }}"
        state: absent
  when: christmas_community_enabled is false

- name: Data Archive {{ ansible_nas_app_name }}
  include_role:
    name: ansible-nas-archive
  vars:
    target_data_dir: "{{ christmas_community_data_directory }}"
  when:
    - archive_app_data_enabled is true
    - christmas_community_enabled is false