---
- name: Start {{ ansible_nas_app_name }}
  block:
    - name: Create {{ ansible_nas_app_name }} Directories
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
      with_items:
        - "{{ umami_data_directory }}"
        - "{{ umami_data_directory }}/db"

    - name: Set {{ ansible_nas_app_name }} FQDN var overrides
      ansible.builtin.set_fact:
        umami_homepage_href: "https://{{ umami_hostname }}.{{ ansible_nas_domain }}"
      when: umami_traefik_enabled | bool or umami_dockflare_enabled | bool

    - name: Create {{ ansible_nas_app_name }} DB Container
      community.docker.docker_container:
        container_default_behavior: "compatibility"
        name: "{{ umami_db_container_name }}"
        hostname: "{{ umami_db_container_name }}"
        image: "{{ umami_db_image_name }}:{{ umami_db_image_tag }}"
        pull: true
        volumes:
          - "{{ umami_data_directory }}/db:/var/lib/postgresql/data"
        env:
          POSTGRES_DB: "umami"
          POSTGRES_USER: "umami"
          POSTGRES_PASSWORD: "umami"
        healthcheck:
          test: ["CMD-SHELL", "pg_isready -U umami -d umami"]
          interval: 5s
          timeout: 5s
          retries: "5"
        labels:
          autoheal: "{{ umami_db_autoheal_enabled | ternary('true', 'false') }}"
          com.centurylinklabs.watchtower.enable: "{{ umami_db_watchtower_enabled | ternary('true', 'false') }}"
          dockflare.enable: "false"
          homepage.name: "{{ ansible_nas_app_name }} PostgreSQL"
          homepage.group: "{{ umami_db_homepage_group }}"
          homepage.icon: "{{ umami_db_homepage_icon }}"
          homepage.href: "{{ umami_db_homepage_href }}"
          homepage.description: "{{ 'PostgreSQL Database Management System' if homepage_show_description else omit }}"
          homepage.server: "my-docker"
          homepage.container: "{{ umami_db_container_name }}"
          homepage.showStats: "{{ umami_db_homepage_showstats | ternary('true', 'false') }}"
          repliqate.enabled: "{{ umami_db_repliqate_enabled | ternary('true', 'false') }}"
          repliqate.engine: "{{ umami_db_repliqate_engine }}"
          repliqate.schedule: "{{ umami_db_repliqate_schedule }}"
          repliqate.backup_id: "{{ umami_db_repliqate_backup_id }}"
          repliqate.retention: "{{ umami_db_repliqate_retention }}"
          traefik.enable: "false"
          wud.tag.include: "^\\d+-alpine$"
          wud.tag.transform.type: "semver"
          wud.link.template: "https://www.postgresql.org/docs/release/"
        cpu_shares: "{{ umami_db_cpu_shares }}"
        memory: "{{ umami_db_memory }}"
        memory_swap: "{{ umami_db_memory_swap }}"
        restart_policy: unless-stopped

    - name: Verify {{ ansible_nas_app_name }} DB is healthy
      community.docker.docker_container_info:
        name: "{{ umami_db_container_name }}"
      register: db_info
      until: "db_info.container.State.Health.Status == 'healthy'"
      retries: 30
      delay: 5

    - name: Create {{ ansible_nas_app_name }} Container
      community.docker.docker_container:
        container_default_behavior: "compatibility"
        name: "{{ umami_container_name }}"
        hostname: "{{ umami_container_name }}"
        image: "{{ umami_image_name }}:{{ umami_image_tag }}"
        pull: true
        ports:
          - "{{ umami_port_http }}:3000"
        env:
          DATABASE_TYPE: "postgresql"
          DATABASE_URL: "postgres://umami:umami@{{ umami_db_container_name }}:5432/umami"
          APP_SECRET: "{{ umami_app_secret }}"
          TZ: "{{ ansible_nas_timezone }}"
        healthcheck:
          test: ["CMD-SHELL", "curl http://localhost:3000/api/heartbeat"]
          interval: 5s
          timeout: 5s
          retries: 5
        links:
          - "{{ umami_db_container_name }}"
        labels:
          autoheal: "{{ umami_autoheal_enabled | ternary('true', 'false') }}"
          com.centurylinklabs.watchtower.enable: "{{ umami_watchtower_enabled | ternary('true', 'false') }}"
          dockflare.enable: "{{ umami_dockflare_enabled | ternary('true', 'false') }}"
          dockflare.access.group: "{{ umami_dockflare_access_group }}"
          dockflare.hostname: "{{ umami_hostname }}.{{ ansible_nas_domain }}"
          dockflare.service: "http://{{ hostvars[inventory_hostname]['ansible_facts']['default_ipv4']['address'] }}:{{ umami_port_http }}"
          homepage.name: "{{ ansible_nas_app_name }}"
          homepage.group: "{{ umami_homepage_group }}"
          homepage.icon: "{{ umami_homepage_icon }}"
          homepage.href: "{{ umami_homepage_href }}"
          homepage.description: "{{ 'a simple, fast, privacy-focused alternative to Google Analytics' if homepage_show_description else omit }}"
          homepage.siteMonitor: "http://{{ hostvars[inventory_hostname]['ansible_facts']['default_ipv4']['address'] }}:{{ umami_port_http }}"
          homepage.server: "my-docker"
          homepage.container: "{{ umami_container_name }}"
          homepage.showStats: "{{ umami_homepage_showstats | ternary('true', 'false') }}"
          repliqate.enabled: "{{ umami_repliqate_enabled | ternary('true', 'false') }}"
          repliqate.engine: "{{ umami_repliqate_engine }}"
          repliqate.schedule: "{{ umami_repliqate_schedule }}"
          repliqate.backup_id: "{{ umami_repliqate_backup_id }}"
          repliqate.retention: "{{ umami_repliqate_retention }}"
          traefik.enable: "{{ umami_traefik_enabled | ternary('true', 'false') }}"
          traefik.http.routers.umami.rule: "Host(`{{ umami_hostname }}.{{ ansible_nas_domain }}`)"
          traefik.http.routers.umami.tls.certresolver: "letsencrypt"
          traefik.http.routers.umami.tls.domains[0].main: "{{ ansible_nas_domain }}"
          traefik.http.routers.umami.tls.domains[0].sans: "*.{{ ansible_nas_domain }}"
          traefik.http.routers.umami.middlewares: "umami@docker{{ ',tinyauth-auth@docker' if umami_tinyauth_enabled | bool else '' }}"
          traefik.http.middlewares.umami.IPAllowList.sourcerange: "{{ umami_traefik_whitelist }}"
          traefik.http.services.umami.loadbalancer.server.port: "3000"
          wud.tag.include: '^postgresql-v\d+\.\d+\.\d+$'
          wud.tag.transform.type: "semver"
          wud.link.template: "https://github.com/umami-software/umami/pkgs/container/umami"
        cpu_shares: "{{ umami_cpu_shares }}"
        memory: "{{ umami_memory }}"
        memory_swap: "{{ umami_memory_swap }}"
        restart_policy: unless-stopped

    - name: Access {{ ansible_nas_app_name }} at
      ansible.builtin.debug:
        msg: >-
              {{
                ['http://' + hostvars[inventory_hostname]['ansible_facts']['default_ipv4']['address'] + ':' + (umami_port_http | string)] +
                (['https://' + umami_hostname + '.' + ansible_nas_domain] if (umami_traefik_enabled is true or umami_dockflare_enabled is true) else [])
              }}
  when: umami_enabled is true

- name: Stop {{ ansible_nas_app_name }}
  block:
    - name: Stop {{ ansible_nas_app_name }} Container
      community.docker.docker_container:
        name: "{{ umami_container_name }}"
        state: absent

    - name: Stop {{ ansible_nas_app_name }} DB Container
      community.docker.docker_container:
        name: "{{ umami_db_container_name }}"
        state: absent
  when: umami_enabled is false

- name: Data Archive {{ ansible_nas_app_name }}
  include_role:
    name: ansible-nas-archive
  vars:
    target_data_dir: "{{ umami_data_directory }}"
  when:
    - archive_app_data_enabled is true
    - umami_enabled is false