---
- name: Start {{ ansible_nas_app_name }}
  block:
    - name: Create {{ ansible_nas_app_name }} Directory
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
      with_items:
        - "{{ wud_data_directory }}"

    - name: Install python3-passlib
      apt:
        name: "python3-passlib"
        state: present
      register: result
      until: result is succeeded

    - name: Create {{ ansible_nas_app_name }} Container
      community.docker.docker_container:
        container_default_behavior: "compatibility"
        name: "{{ wud_container_name }}"
        hostname: "{{ wud_container_name }}"
        image: "{{ wud_image_name }}:{{ wud_image_tag }}"
        pull: true
        volumes:
          - "{{ wud_data_directory }}:/store"
          - "/var/run/docker.sock:/var/run/docker.sock"
        ports:
          - "{{ wud_port_http }}:3000"
        env:
# NOTE: Consider moving env vars to a list so that triggers can be added manually
          WUD_AUTH_BASIC_ADMIN_USER: "{{ wud_env_wud_auth_basic_admin_username }}"
          WUD_AUTH_BASIC_ADMIN_HASH: "{{ wud_admin_password | password_hash('md5') }}"
          WUD_REGISTRY_HUB_PUBLIC_LOGIN: "{{ wud_env_wud_registry_hub_public_login }}"
          WUD_REGISTRY_HUB_PUBLIC_PASSWORD: "{{ wud_env_wud_registry_hub_public_password }}"
          WUD_WATCHER_LOCAL_WATCHALL: "{{ wud_env_wud_watcher_local_watchall }}"
          WUD_TRIGGER_WATCHTOWER_HTTP_URL: "http://{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}:{{ watchtower_port_api }}/v1/update"
          WUD_TRIGGER_WATCHTOWER_HTTP_METHOD: "POST"
          WUD_TRIGGER_WATCHTOWER_HTTP_HEADERS: '{"Authorization":"Bearer {{ watchtower_api_token }}"}'
#          WUD_REGISTRY_ACR_{REGISTRY_NAME}_CLIENTID	red_circle	Service Principal Client ID	See Service Principal Auth	
#          WUD_REGISTRY_ACR_{REGISTRY_NAME}_CLIENTSECRET	red_circle	Service Principal Secret	See Service Principal Auth
#          WUD_REGISTRY_CUSTOM_{REGISTRY_NAME}_URL	red_circle	Registry URL (e.g. http://localhost:5000)		
#          WUD_REGISTRY_CUSTOM_{REGISTRY_NAME}_LOGIN	white_circle	Login (when htpasswd auth is enabled on the registry)	WUD_REGISTRY_CUSTOM_{REGISTRY_NAME}_PASSWORD must be defined	
#          WUD_REGISTRY_CUSTOM_{REGISTRY_NAME}_PASSWORD	white_circle	Password (when htpasswd auth is enabled on the registry)	WUD_REGISTRY_CUSTOM_{REGISTRY_NAME}_LOGIN must be defined	
#          WUD_REGISTRY_CUSTOM_{REGISTRY_NAME}_AUTH	white_circle	Htpasswd string (when htpasswd auth is enabled on the registry)
#          WUD_REGISTRY_ECR_{REGISTRY_NAME}_REGION	red_circle	A valid AWS Region Code	AWS Region list	
#          WUD_REGISTRY_ECR_{REGISTRY_NAME}_ACCESSKEYID	red_circle	A valid AWS Access Key Id	Standard AWS Credentials	
#          WUD_REGISTRY_ECR_{REGISTRY_NAME}_SECRETACCESSKEY	red_circle	A valid AWS Secret Access Key	Standard AWS Credentials
#          WUD_REGISTRY_FORGEJO_{REGISTRY_NAME}_URL	red_circle	Registry URL (e.g. https://forgejo.acme.com)		
#          WUD_REGISTRY_FORGEJO_{REGISTRY_NAME}_LOGIN	red_circle	Forgejo username	WUD_REGISTRY_FORGEJO_{REGISTRY_NAME}_PASSWORD must be defined	
#          WUD_REGISTRY_FORGEJO_{REGISTRY_NAME}_PASSWORD	red_circle	Forgejo password or personal access token	WUD_REGISTRY_FORGEJO_{REGISTRY_NAME}_LOGIN must be defined	
#          WUD_REGISTRY_FORGEJO_{REGISTRY_NAME}_AUTH	white_circle	Htpasswd string (when htpasswd auth is enabled on the registry)
#          WUD_REGISTRY_GCR_{REGISTRY_NAME}_CLIENTEMAIL	white_circle	Service Account Client Email (required for private images access)	See Service Account credentials	
#          WUD_REGISTRY_GCR_{REGISTRY_NAME}_PRIVATEKEY	white_circle	Service Account Private Key (required for private images access)	See Service Account credentials
#          WUD_REGISTRY_GHCR_{REGISTRY_NAME}_USERNAME	white_circle	Github username		
#          WUD_REGISTRY_GHCR_{REGISTRY_NAME}_TOKEN	white_circle	Github token	Github password or Github Personal Token	
#          WUD_REGISTRY_GITEA_{REGISTRY_NAME}_URL	red_circle	Registry URL (e.g. https://gitea.acme.com)		
#          WUD_REGISTRY_GITEA_{REGISTRY_NAME}_LOGIN	red_circle	Gitea username	WUD_REGISTRY_GITEA_{REGISTRY_NAME}_PASSWORD must be defined	
#          WUD_REGISTRY_GITEA_{REGISTRY_NAME}_PASSWORD	red_circle	Gitea password	WUD_REGISTRY_GITEA_{REGISTRY_NAME}_LOGIN must be defined	
#          WUD_REGISTRY_GITEA_{REGISTRY_NAME}_AUTH	white_circle	Htpasswd string (when htpasswd auth is enabled on the registry)
#          WUD_REGISTRY_GITLAB_{REGISTRY_NAME}_AUTHURL	red_circle	Gitlab Authentication base url		https://gitlab.com
#          WUD_REGISTRY_GITLAB_{REGISTRY_NAME}_TOKEN	red_circle	Gitlab Personal Access Token		
#          WUD_REGISTRY_GITLAB_{REGISTRY_NAME}_URL	red_circle	Gitlab Registry base url		https://registry.gitlab.com
#          WUD_REGISTRY_LSCR_{REGISTRY_NAME}_USERNAME	red_circle	Github username		
#          WUD_REGISTRY_LSCR_{REGISTRY_NAME}_TOKEN	red_circle	Github token	Github password or Github Personal Token	
#          WUD_REGISTRY_QUAY_{REGISTRY_NAME}_NAMESPACE	white_circle	Quay namespace		
#          WUD_REGISTRY_QUAY_{REGISTRY_NAME}_ACCOUNT	white_circle	Quay account		
#          WUD_REGISTRY_QUAY_{REGISTRY_NAME}_TOKEN	white_circle	Quay token
          TZ: "{{ ansible_nas_timezone }}"
        healthcheck:
          test: 'curl --fail http://localhost:3000/health || exit 1'
          interval: "10s"
          timeout: "10s"
          retries: "3"
          start_period: "10s"
        labels:
          autoheal: "{{ wud_autoheal | string }}"
          com.centurylinklabs.watchtower.enable: "{{ wud_watchtower_enabled | string }}"
          dockflare.enable: "{{ wud_dockflare_enabled | string }}"
          dockflare.access.group: "{{ wud_dockflare_access_group }}"
          dockflare.hostname: "{{ wud_hostname }}.{{ ansible_nas_domain }}"
          dockflare.service: "http://{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}:{{ wud_port_http }}"
          homepage.name: "{{ ansible_nas_app_name }}"
          homepage.group: "{{ wud_homepage_group }}"
          homepage.icon: "{{ wud_homepage_icon }}"
          homepage.href: "{{ wud_homepage_href }}"
          homepage.description: "{{ 'Keep your containers up-to-date!' if homepage_show_description else omit }}"
          homepage.siteMonitor: "http://{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}:{{ wud_port_http }}"
          homepage.server: "my-docker"
          homepage.container: "{{ wud_container_name }}"
          homepage.showStats: "{{ wud_homepage_showstats | string }}"
          homepage.widget.type: "whatsupdocker"
          homepage.widget.url: "http://{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}:{{ wud_port_http }}"
          homepage.widget.username: "{{ wud_homepage_widget_username }}"
          homepage.widget.password: "{{ wud_homepage_widget_password }}"
          repliqate.enabled: "{{ wud_repliqate_enabled | string }}"
          repliqate.engine: "{{ wud_repliqate_engine }}"
          repliqate.schedule: "{{ wud_repliqate_schedule }}"
          repliqate.backup_id: "{{ wud_repliqate_backup_id }}"
          repliqate.retention: "{{ wud_repliqate_retention }}"
          traefik.enable: "{{ wud_available_externally | string }}"
          traefik.http.routers.wud.rule: "Host(`{{ wud_hostname }}.{{ ansible_nas_domain }}`)"
          traefik.http.routers.wud.tls.certresolver: "letsencrypt"
          traefik.http.routers.wud.tls.domains[0].main: "{{ ansible_nas_domain }}"
          traefik.http.routers.wud.tls.domains[0].sans: "*.{{ ansible_nas_domain }}"
          traefik.http.routers.wud.middlewares: "wud@docker{{ ',tinyauth-auth@docker' if wud_tinyauth_enabled | bool else '' }}"
          traefik.http.middlewares.wud.IPAllowList.sourcerange: "{{ wud_traefik_whitelist }}"
          traefik.http.services.wud.loadbalancer.server.port: "3000"
          wud.tag.include: '^\d+\.\d+\.\d+$'
          wud.link.template: "https://github.com/getwud/wud/releases/tag/${major}.${minor}.${patch}"
        cpu_shares: "{{ wud_cpu_shares }}"
        memory: "{{ wud_memory }}"
        memory_swap: "{{ wud_memory_swap }}"
        restart_policy: unless-stopped

    - name: Access {{ ansible_nas_app_name }} at
      ansible.builtin.debug:
        msg: >-
              {{
                ['http://' + hostvars[inventory_hostname]['ansible_default_ipv4']['address'] + ':' + (wud_port_http | string)] +
                (['https://' + wud_hostname + '.' + ansible_nas_domain] if (wud_available_externally is true or wud_dockflare_enabled is true) else [])
              }}
  when: wud_enabled is true

- name: Stop {{ ansible_nas_app_name }}
  block:
    - name: Stop {{ ansible_nas_app_name }} Container
      community.docker.docker_container:
        name: "{{ wud_container_name }}"
        state: absent
  when: wud_enabled is false

- name: Data Archive {{ ansible_nas_app_name }}
  include_role:
    name: ansible-nas-archive
  vars:
    target_data_dir: "{{ wud_data_directory }}"
  when:
    - archive_app_data_enabled is true
    - wud_enabled is false