---
# ANE
ansible_nas_app_name: "apcupsd"
apcupsd_enabled: false

# directories
apcupsd_data_directory: "{{ docker_home }}/apcupsd"

# network
apcupsd_port_http: "3551"

# docker
apcupsd_container_name: "apcupsd"
apcupsd_image_name: "gregewing/apcupsd"
apcupsd_image_tag: "latest"
apcupsd_device: "/dev/usb/hiddev0" # This device needs to match what the APC UPS on your system uses.

# specs
apcupsd_cpu_shares: 1024
apcupsd_memory: "1G"
apcupsd_memory_swap: -1

# ups config
apcupsd_onbatterydelay: 6
apcupsd_batterylevel: 5
apcupsd_minutes: 5
apcupsd_timeout: 0
apcupsd_annoy: 300
apcupsd_annoydelay: 60
apcupsd_nologon: "disable"
apcupsd_killdelay: 0

# autoheal
apcupsd_autoheal_enabled: false

# homepage
apcupsd_homepage_group: "Misc"
apcupsd_homepage_icon: "apc.png"
apcupsd_homepage_showstats: false

# repliqate
apcupsd_repliqate_enabled: false
apcupsd_repliqate_engine: "restic"
apcupsd_repliqate_schedule: "@daily 3am"
apcupsd_repliqate_backup_id: "{{ apcupsd_container_name }}"
apcupsd_repliqate_retention: "30d"

# watchtower
apcupsd_watchtower_enabled: false