---
ansible_nas_app_name: "apcupsd"

apcupsd_enabled: false

# directories
apcupsd_data_directory: "{{ docker_home }}/apcupsd"

# network
apcupsd_port: "3551"

# specs
apcupsd_memory: 1g

# docker
apcupsd_container_name: apcupsd
apcupsd_cpu_shares: 1024
apcupsd_image_name: "gregewing/apcupsd"
apcupsd_image_tag: "latest"

# ups config
apcupsd_onbatterydelay: 6
apcupsd_batterylevel: 5
apcupsd_minutes: 5
apcupsd_timeout: 0
apcupsd_annoy: 300
apcupsd_annoydelay: 60
apcupsd_nologon: "disable"
apcupsd_killdelay: 0

# autoheal
apcupsd_autoheal: "false"

# homepage
apcupsd_homepage_group: "Apps"
apcupsd_homepage_icon: "apcupsd.png"
apcupsd_homepage_showStats: "false"

# watchtower
apcupsd_watchtower_monitor_only: "true"