---
- name: Start {{ paperless_ngx_proper_name }}
  block:
    - name: Create {{ paperless_ngx_proper_name }} Directories
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
      with_items:
        - "{{ paperless_ngx_data_directory }}"
        - "{{ paperless_ngx_data_directory }}/data"
        - "{{ paperless_ngx_files_directory }}"
        - "{{ paperless_ngx_postgres_directory }}"
        - "{{ paperless_ngx_export_directory }}"
        - "{{ paperless_ngx_media_directory }}"
        - "{{ paperless_ngx_consume_directory }}"

    - name: Set {{ paperless_ngx_proper_name }} FQDN var overrides
      ansible.builtin.set_fact:
        paperless_ngx_homepage_href: "https://{{ paperless_ngx_hostname }}.{{ ansible_nas_domain }}"
      when: paperless_ngx_traefik_enabled | bool or paperless_ngx_dockflare_enabled | bool

    - name: Create {{ paperless_ngx_proper_name }} network
      community.docker.docker_network:
        name: "{{ paperless_ngx_network_name }}"

    - name: Create {{ paperless_ngx_proper_name }} Redis Container
      community.docker.docker_container:
        container_default_behavior: "compatibility"
        name: "{{ paperless_ngx_redis_container_name }}"
        hostname: "{{ paperless_ngx_redis_container_name }}"
        image: "{{ paperless_ngx_redis_image_name }}:{{ paperless_ngx_redis_image_version }}"
        pull: true
        env:
          TZ: "{{ ansible_nas_timezone }}"
        networks:
          - name: "{{ paperless_ngx_network_name }}"
        network_mode: "{{ paperless_ngx_network_name }}"
        labels:
          traefik.enable: "false"
          autoheal: "{{ paperless_ngx_redis_autoheal_enabled | ternary('true', 'false') }}"
          com.centurylinklabs.watchtower.enable: "{{ paperless_ngx_redis_watchtower_enabled | ternary('true', 'false') }}"
          dockflare.enable: "false"
          homepage.name: "{{ paperless_ngx_proper_name }} Redis"
          homepage.group: "{{ paperless_ngx_redis_homepage_group }}"
          homepage.icon: "{{ paperless_ngx_redis_homepage_icon }}"
          homepage.href: "{{ paperless_ngx_redis_homepage_href }}"
          homepage.description: "{{ 'The Real-time Data Platform' if homepage_show_description else omit }}"
          homepage.server: "my-docker"
          homepage.container: "{{ paperless_ngx_redis_container_name }}"
          homepage.showStats: "{{ paperless_ngx_redis_homepage_showstats | ternary('true', 'false') }}"
          repliqate.enabled: "{{ paperless_ngx_redis_repliqate_enabled | ternary('true', 'false') }}"
          repliqate.engine: "{{ paperless_ngx_redis_repliqate_engine }}"
          repliqate.schedule: "{{ paperless_ngx_redis_repliqate_schedule }}"
          repliqate.backup_id: "{{ paperless_ngx_redis_repliqate_backup_id }}"
          repliqate.retention: "{{ paperless_ngx_redis_repliqate_retention }}"
          wud.tag.include: '^\d+\.\d+\.\d+.*$'
          wud.tag.transform.type: "semver"
          wud.link.template: "https://hub.docker.com/_/redis"
        cpu_shares: "{{ paperless_ngx_redis_cpu_shares }}"
        restart_policy: unless-stopped
        memory: "{{ paperless_ngx_redis_memory }}"
        memory_swap: "{{ paperless_ngx_redis_memory_swap }}"

    - name: Create {{ paperless_ngx_proper_name }} DB Container
      community.docker.docker_container:
        container_default_behavior: "compatibility"
        name: "{{ paperless_ngx_db_container_name }}"
        hostname: "{{ paperless_ngx_db_container_name }}"
        image: "{{ paperless_ngx_db_image_name }}:{{ paperless_ngx_db_image_version }}"
        pull: true
        volumes:
          - "{{ paperless_ngx_postgres_directory }}:/var/lib/postgresql/data"
        env:
          POSTGRES_DB: "{{ paperless_ngx_postgres_db }}"
          POSTGRES_USER: "{{ paperless_ngx_postgres_user }}"
          POSTGRES_PASSWORD: "{{ paperless_ngx_postgres_password }}"
          TZ: "{{ ansible_nas_timezone }}"
        networks:
          - name: "{{ paperless_ngx_network_name }}"
        network_mode: "{{ paperless_ngx_network_name }}"
        healthcheck:
          test: ["CMD-SHELL", "pg_isready -U {{ paperless_ngx_postgres_user }}"]
          interval: 10s
          timeout: 5s
          retries: 5
          start_period: 30s
        labels:
          traefik.enable: "false"
          autoheal: "{{ paperless_ngx_db_autoheal_enabled | ternary('true', 'false') }}"
          com.centurylinklabs.watchtower.enable: "{{ paperless_ngx_db_watchtower_enabled | ternary('true', 'false') }}"
          dockflare.enable: "false"
          homepage.name: "{{ paperless_ngx_proper_name }} PostgreSQL"
          homepage.group: "{{ paperless_ngx_db_homepage_group }}"
          homepage.icon: "{{ paperless_ngx_db_homepage_icon }}"
          homepage.href: "{{ paperless_ngx_db_homepage_href }}"
          homepage.description: "{{ 'PostgreSQL Database Management System' if homepage_show_description else omit }}"
          homepage.server: "my-docker"
          homepage.container: "{{ paperless_ngx_db_container_name }}"
          homepage.showStats: "{{ paperless_ngx_db_homepage_showstats | ternary('true', 'false') }}"
          repliqate.enabled: "{{ paperless_ngx_db_repliqate_enabled | ternary('true', 'false') }}"
          repliqate.engine: "{{ paperless_ngx_db_repliqate_engine }}"
          repliqate.schedule: "{{ paperless_ngx_db_repliqate_schedule }}"
          repliqate.backup_id: "{{ paperless_ngx_db_repliqate_backup_id }}"
          repliqate.retention: "{{ paperless_ngx_db_repliqate_retention }}"
          wud.tag.include: '^\d+\.\d+.*$'
          wud.tag.transform.type: "semver"
          wud.link.template: "https://hub.docker.com/_/postgres"
        cpu_shares: "{{ paperless_ngx_db_cpu_shares }}"
        restart_policy: unless-stopped
        memory: "{{ paperless_ngx_db_memory }}"
        memory_swap: "{{ paperless_ngx_db_memory_swap }}"

    - name: Wait for {{ paperless_ngx_proper_name }} DB to become healthy
      community.docker.docker_container_info:
        name: "{{ paperless_ngx_db_container_name }}"
      register: db_info
      until: "db_info.container.State.Health.Status == 'healthy'"
      retries: 30
      delay: 5

    - name: Create {{ paperless_ngx_proper_name }} Container
      community.docker.docker_container:
        container_default_behavior: "compatibility"
        name: "{{ paperless_ngx_container_name }}"
        hostname: "{{ paperless_ngx_container_name }}"
        image: "{{ paperless_ngx_image_name }}:{{ paperless_ngx_image_version }}"
        pull: true
        volumes:
          - "{{ paperless_ngx_data_directory }}/data:/usr/src/paperless/data"
          - "{{ paperless_ngx_media_directory }}:/usr/src/paperless/media"
          - "{{ paperless_ngx_export_directory }}:/usr/src/paperless/export"
          - "{{ paperless_ngx_consume_directory }}:/usr/src/paperless/consume"
        ports:
          - "{{ paperless_ngx_port_http }}:8000"
        env:
          PAPERLESS_REDIS: "redis://{{ paperless_ngx_redis_container_name | string }}:6379"
          PAPERLESS_DBHOST: "{{ paperless_ngx_db_container_name | string }}"
          PAPERLESS_OCR_LANGUAGES: "{{ paperless_ngx_languages }}"
#         PAPERLESS_CSRF_TRUSTED_ORIGINS: "{{ paperless_ngx_hostname }}.{{ ansible_nas_domain }}"
          PAPERLESS_URL: "https://{{ paperless_ngx_hostname }}.{{ ansible_nas_domain }}"
          CORS_ALLOWED_ORIGINS: "*"
          USERMAP_UID: "{{ paperless_ngx_user_id }}"
          USERMAP_GID: "{{ paperless_ngx_group_id }}"
          TZ: "{{ ansible_nas_timezone }}"
        networks:
          - name: "{{ paperless_ngx_network_name }}"
        network_mode: "{{ paperless_ngx_network_name }}"
        links:
          - "{{ paperless_ngx_db_container_name }}"
          - "{{ paperless_ngx_redis_container_name }}"
        labels:
          autoheal: "{{ paperless_ngx_autoheal_enabled | ternary('true', 'false') }}"
          com.centurylinklabs.watchtower.enable: "{{ paperless_ngx_watchtower_enabled | ternary('true', 'false') }}"
          dockflare.enable: "{{ paperless_ngx_dockflare_enabled | ternary('true', 'false') }}"
          dockflare.access.group: "{{ paperless_ngx_dockflare_access_group }}"
          dockflare.hostname: "{{ paperless_ngx_hostname }}.{{ ansible_nas_domain }}"
          dockflare.service: "http://{{ hostvars[inventory_hostname]['ansible_facts']['default_ipv4']['address'] }}:{{ paperless_ngx_port_http }}"
          homepage.name: "{{ paperless_ngx_proper_name }}"
          homepage.group: "{{ paperless_ngx_homepage_group }}"
          homepage.icon: "{{ paperless_ngx_homepage_icon }}"
          homepage.href: "{{ paperless_ngx_homepage_href }}"
          homepage.siteMonitor: "http://{{ hostvars[inventory_hostname]['ansible_facts']['default_ipv4']['address'] }}:{{ paperless_ngx_port_http }}"
          homepage.description: "{{ 'Open source dropbox alternative' if homepage_show_description else omit }}"
          homepage.server: "my-docker"
          homepage.container: "{{ paperless_ngx_container_name }}"
          homepage.showStats: "{{ paperless_ngx_homepage_showstats | ternary('true', 'false') }}"
          homepage.widget.type: "paperlessngx"
          homepage.widget.url: "http://{{ hostvars[inventory_hostname]['ansible_facts']['default_ipv4']['address'] }}:{{ paperless_ngx_port_http }}"
          homepage.widget.username: "{{ paperless_ngx_homepage_widget_username }}"
          homepage.widget.password: "{{ paperless_ngx_homepage_widget_password }}"
          homepage.widget.key: "{{ paperless_ngx_homepage_widget_key }}"
          repliqate.enabled: "{{ paperless_ngx_repliqate_enabled | ternary('true', 'false') }}"
          repliqate.engine: "{{ paperless_ngx_repliqate_engine }}"
          repliqate.schedule: "{{ paperless_ngx_repliqate_schedule }}"
          repliqate.backup_id: "{{ paperless_ngx_repliqate_backup_id }}"
          repliqate.retention: "{{ paperless_ngx_repliqate_retention }}"
          traefik.enable: "{{ paperless_ngx_traefik_enabled | ternary('true', 'false') }}"
          traefik.http.routers.paperlessngx.rule: "Host(`{{ paperless_ngx_hostname }}.{{ ansible_nas_domain }}`)"
          traefik.http.routers.paperlessngx.tls.certresolver: "letsencrypt"
          traefik.http.routers.paperlessngx.tls.domains[0].main: "{{ ansible_nas_domain }}"
          traefik.http.routers.paperlessngx.tls.domains[0].sans: "*.{{ ansible_nas_domain }}"
          traefik.http.routers.paperlessngx.middlewares: "paperlessngx@docker{{ ',tinyauth-auth@docker' if paperless_ngx_tinyauth_enabled | bool else '' }}"
          traefik.http.middlewares.paperlessngx.IPAllowList.sourcerange: "{{ paperless+ngx_traefik_whitelist }}"
          traefik.http.services.paperless_ngx.loadbalancer.server.port: "8000"
          wud.tag.include: '^\d+\.\d+\.\d+$'
          wud.tag.transform.type: "semver"
          wud.link.template: "https://github.com/paperless-ngx/paperless-ngx/pkgs/container/paperless-ngx"
        cpu_shares: "{{ paperless_ngx_cpu_shares }}"
        memory: "{{ paperless_ngx_memory }}"
        restart_policy: unless-stopped
        memory_swap: "{{ paperless_ngx_memory_swap }}"

    - name: Access {{ paperless_ngx_proper_name }} at
      ansible.builtin.debug:
        msg: >-
              {{
                ['http://' + hostvars[inventory_hostname]['ansible_facts']['default_ipv4']['address'] + ':' + (paperless_ngx_port_http | string)] +
                (['https://' + paperless_ngx_hostname + '.' + ansible_nas_domain] if (paperless_ngx_traefik_enabled is true or paperless_ngx_dockflare_enabled is true) else [])
              }}
  when: paperless_ngx_enabled is true

- name: Stop {{ paperless_ngx_proper_name }}
  block:
    - name: Stop {{ paperless_ngx_proper_name }} Container
      community.docker.docker_container:
        name: "{{ paperless_ngx_container_name }}"
        state: absent

    - name: Stop {{ paperless_ngx_proper_name }} Redis Container
      community.docker.docker_container:
        name: "{{ paperless_ngx_redis_container_name }}"
        state: absent

    - name: Stop {{ paperless_ngx_proper_name }} DB Container
      community.docker.docker_container:
        name: "{{ paperless_ngx_db_container_name }}"
        state: absent

    - name: Delete {{ paperless_ngx_proper_name }} Network
      community.docker.docker_network:
        name: "{{ paperless_ngx_network_name }}"
        state: absent
  when: paperless_ngx_enabled is false

- name: Data Archive {{ paperless_ngx_proper_name }}
  include_role:
    name: ansible-nas-archive
  vars:
    target_data_dir: "{{ paperless_ngx_data_directory }}"
  when:
    - archive_app_data_enabled is true
    - paperless_ngx_enabled is false