---
- name: Verify
  hosts: all
  gather_facts: false
  tasks:
    - ansible.builtin.include_vars:
        file: ../../defaults/main.yml

    - name: Try and stop and remove RomM
      community.docker.docker_container:
        name: "{{ romm_container_name }}"
        state: absent
      register: result

    - name: Check RomM is stopped
      ansible.builtin.assert:
        that:
          - not result.changed

    - name: Try and stop and remove RomM DB
      community.docker.docker_container:
        name: "{{ romm_db_container_name }}"
        state: absent
      register: result

    - name: Check RomM DB is stopped
      ansible.builtin.assert:
        that:
          - not result.changed
