---
ansible_nas_app_name: "n8n"

n8n_enabled: false

# Networking
n8n_available_externally: false
n8n_traefik_whitelist: "{{ lan }}"
n8n_port: 5678
n8n_hostname: "n8n"

# Directories
n8n_data_directory: "{{ docker_home }}/n8n"

# Security
n8n_basic_auth_user: "n8n_user"
n8n_basic_auth_password: "n8n_change_me"

# docker
n8n_container_name: "n8n"
n8n_image_name: "docker.n8n.io/n8nio/n8n"
n8n_image_version: "latest"
n8n_cpu_shares: 1024

# specs
n8n_memory: 1g

# autoheal
n8n_autoheal: "false"

# dockflare
n8n_dockflare_tunnel: "false"
n8n_dockflare_access_group: ""

# homepage
n8n_homepage_group: "Apps"
n8n_homepage_icon: "n8n.png"
n8n_homepage_href: "http://{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}:{{ n8n_port }}"
n8n_homepage_showStats: "false"

# watchtower
n8n_watchtower_monitor_only: "true"