---
ansible_nas_app_name: "Striparr"

#
striparr_enabled: false
striparr_available_externally: false
striparr_traefik_whitelist: "{{ lan }}"
striparr_data_directory: "{{ docker_home }}/striparr"

# network
striparr_port_http: "40000"

striparr_puid: "500"
striparr_pgid: "0"

# docker
striparr_container_name: "striparr"
striparr_image_name: "mikenye/striparr"
striparr_image_tag: "latest"
striparr_cpu_shares: "1024"
striparr_memory: "512m"

# autoheal
striparr_autoheal: "false"

# homepage
striparr_homepage_group: "Apps"
striparr_homepage_icon: "striparr.png"
striparr_homepage_href: "http://{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}:{{ striparr_port_http }}"
striparr_homepage_showStats: "false"

# watchtower
striparr_watchtower_monitor_only: "true"