---
# ANE
striparr_proper_name: "Striparr"
striparr_enabled: false
striparr_traefik_enabled: false
striparr_traefik_whitelist: "{{ lan }}"

# network
striparr_port_http: "40000" # not exposed, for reference

striparr_puid: "1000"
striparr_pgid: "1000"

# docker
striparr_container_name: "striparr"
striparr_image_name: "ghcr.io/mikenye/docker-striparr"
striparr_image_tag: "latest"

# specs
striparr_cpu_shares: 1024
striparr_memory: "512M"
striparr_memory_swap: -1

# autoheal
striparr_autoheal_enabled: false

# homepage
striparr_homepage_group: "Misc"
striparr_homepage_icon: "radarr.png" # better icon?
striparr_homepage_showstats: false

# watchtower
striparr_watchtower_enabled: false