---
- name: Start {{ ansible_nas_app_name }}
  block:
    - name: Create {{ ansible_nas_app_name }} Directories
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
      with_items:
        - "{{ whisparr_data_directory }}"
        - "{{ whisparr_data_directory }}/config"

    - name: Create {{ ansible_nas_app_name }} Container
      community.docker.docker_container:
        container_default_behavior: "compatibility"
        name: "{{ whisparr_container_name }}"
        hostname: "{{ whisparr_container_name }}"
        image: "{{ whisparr_image_name }}:{{ whisparr_image_tag }}"
        pull: true
        ports:
          - "{{ whisparr_port_http }}:6969"
        volumes:
          - "{{ whisparr_data_directory }}/config:/config"
          - "{{ whisparr_porn_directory }}:/porn"
          - "{{ whisparr_download_directory }}:/downloads"
        network_mode: bridge
        env:
          PUID: "{{ whisparr_puid }}"
          PGID: "{{ whisparr_pgid }}"
          TZ: "{{ ansible_nas_timezone }}"
        labels:
          autoheal: "{{ whisparr_autoheal }}"
          com.centurylinklabs.watchtower.enable: "{{ whisparr_watchtower_enable }}"
          dockflare.enable: "{{ whisparr_dockflare_tunnel }}"
          dockflare.access.group: "{{ whisparr_dockflare_access_group }}"
          dockflare.hostname: "{{ whisparr_hostname }}.{{ ansible_nas_domain }}"
          dockflare.service: "http://{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}:{{ whisparr_port_http }}"
          homepage.name: "{{ ansible_nas_app_name }}"
          homepage.group: "{{ whisparr_homepage_group }}"
          homepage.icon: "{{ whisparr_homepage_icon }}"
          homepage.href: "{{ whisparr_homepage_href }}"
          homepage.siteMonitor: "http://{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}:{{ whisparr_port_http }}"
          homepage.description: "{{ 'Whisparr is an adult movie collection manager for Usenet and BitTorrent users.' if homepage_show_description else omit }}"
          homepage.server: "my-docker"
          homepage.container: "{{ whisparr_container_name }}"
          homepage.showStats: "{{ whisparr_homepage_showstats }}"
          traefik.enable: "{{ whisparr_available_externally | string }}"
          traefik.http.routers.whisparr.rule: "Host(`{{ whisparr_hostname }}.{{ ansible_nas_domain }}`)"
          traefik.http.routers.whisparr.tls.certresolver: "letsencrypt"
          traefik.http.routers.whisparr.tls.domains[0].main: "{{ ansible_nas_domain }}"
          traefik.http.routers.whisparr.tls.domains[0].sans: "*.{{ ansible_nas_domain }}"
          traefik.http.routers.frontend.middlewares: "{{ whisparr_hostname }}"
          traefik.http.routers.whisparr.middlewares: "{{ whisparr_hostname }}@docker"
          traefik.http.middlewares.whisparr.IPAllowList.sourcerange: "{{ whisparr_traefik_whitelist }}"
          traefik.http.services.whisparr.loadbalancer.server.port: "6969"
          wud.tag.include: '^v\d+\.\d+\.\d+\.\d+$'
          wud.tag.transform.type: "semver"
          wud.link.template: "https://github.com/TheSpad/Whisparr/pkgs/container/whisparr"
        cpu_shares: "{{ whisparr_cpu_shares }}"
        memory: "{{ whisparr_memory }}"
        restart_policy: unless-stopped

    - name: Access {{ ansible_nas_app_name }} at
      ansible.builtin.debug:
        msg: >-
              {{
                ['http://' + hostvars[inventory_hostname]['ansible_default_ipv4']['address'] + ':' + (whisparr_port_http | string)] +
                (['https://' + whisparr_hostname + '.' + ansible_nas_domain] if (whisparr_available_externally is true or whisparr_dockflare_tunnel is true) else [])
              }}
  when: whisparr_enabled is true

- name: Stop {{ ansible_nas_app_name }}
  block:
    - name: Stop {{ ansible_nas_app_name }} Container
      community.docker.docker_container:
        name: "{{ whisparr_container_name }}"
        state: absent
  when: whisparr_enabled is false

- name: Data Archive {{ ansible_nas_app_name }}
  block:
    - name: Check for {{ ansible_nas_app_name }} Data Directory
      stat:
        path: "{{ whisparr_data_directory }}"
      register: dir_stat

    - name: Archive {{ ansible_nas_app_name }} Data Directory
      ansible.builtin.archive:
        path: "{{ whisparr_data_directory }}"
        dest: "{{ docker_home }}/{{ ansible_nas_app_name | lower }}.zip"
        force_archive: true
        format: zip
        owner: ansible-nas
        group: ansible-nas
        mode: u=rw,g=rw
        remove: true
      when: dir_stat.stat.exists
  when: whisparr_enabled is false and archive_app_data_enabled is true
