---
- name: Start {{ ansible_nas_app_name }}
  block:
    - name: Create {{ ansible_nas_app_name }} Directories
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
      with_items:
        - "{{ maintainerr_data_directory }}"
        - "{{ maintainerr_data_directory }}/data"

    - name: Set {{ ansible_nas_app_name }} FQDN var overrides
      ansible.builtin.set_fact:
        maintainerr_homepage_href: "https://{{ maintainerr_hostname }}.{{ ansible_nas_domain }}"
      when: maintainerr_traefik_enabled | bool or maintainerr_dockflare_enabled | bool

    - name: Create {{ ansible_nas_app_name }} Container
      community.docker.docker_container:
        container_default_behavior: "compatibility"
        name: "{{ maintainerr_container_name }}"
        hostname: "{{ maintainerr_container_name }}"
        image: "{{ maintainerr_image_name }}:{{ maintainerr_image_tag }}"
        pull: true
        user: 1000:1000
        ports:
          - "{{ maintainerr_port_http }}:6246"
        volumes:
          - "{{ maintainerr_data_directory }}/data:/opt/data"
        env:
          UV_USE_IO_URING: "0"
          TZ: "{{ ansible_nas_timezone }}"
        labels:
          autoheal: "{{ maintainerr_autoheal_enabled | ternary('true', 'false') }}"
          com.centurylinklabs.watchtower.enable: "{{ maintainerr_watchtower_enabled | ternary('true', 'false') }}"
          dockflare.enable: "{{ maintainerr_dockflare_enabled | ternary('true', 'false') }}"
          dockflare.access.group: "{{ maintainerr_dockflare_access_group }}"
          dockflare.hostname: "{{ maintainerr_hostname }}.{{ ansible_nas_domain }}"
          dockflare.service: "http://{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}:{{ maintainerr_port_http }}"
          homepage.name: "{{ ansible_nas_app_name }}"
          homepage.group: "{{ maintainerr_homepage_group }}"
          homepage.icon: "{{ maintainerr_homepage_icon }}"
          homepage.href: "{{ maintainerr_homepage_href }}"
          homepage.siteMonitor: "http://{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}:{{ maintainerr_port_http }}"
          homepage.description: "{{ 'Looks and smells like Overseerr, does the opposite. Maintenance tool for the Plex ecosystem' if homepage_show_description else omit }}"
          homepage.server: "my-docker"
          homepage.container: "{{ maintainerr_container_name }}"
          homepage.showStats: "{{ maintainerr_homepage_showstats | ternary('true', 'false') }}"
          repliqate.enabled: "{{ maintainerr_repliqate_enabled | ternary('true', 'false') }}"
          repliqate.engine: "{{ maintainerr_repliqate_engine }}"
          repliqate.schedule: "{{ maintainerr_repliqate_schedule }}"
          repliqate.backup_id: "{{ maintainerr_repliqate_backup_id }}"
          repliqate.retention: "{{ maintainerr_repliqate_retention }}"
          traefik.enable: "{{ maintainerr_traefik_enabled | ternary('true', 'false') }}"
          traefik.http.routers.maintainerr.rule: "Host(`{{ maintainerr_hostname }}.{{ ansible_nas_domain }}`)"
          traefik.http.routers.maintainerr.tls.certresolver: "letsencrypt"
          traefik.http.routers.maintainerr.tls.domains[0].main: "{{ ansible_nas_domain }}"
          traefik.http.routers.maintainerr.tls.domains[0].sans: "*.{{ ansible_nas_domain }}"
          traefik.http.routers.maintainerr.middlewares: "maintainerr@docker{{ ',tinyauth-auth@docker' if maintainerr_tinyauth_enabled | bool else '' }}"
          traefik.http.middlewares.maintainerr.IPAllowList.sourcerange: "{{ maintainerr_traefik_whitelist }}"
          traefik.http.services.maintainerr.loadbalancer.server.port: "6246"
          wud.tag.include: '^\d+\.\d+\.\d+.*$'
          wud.tag.transform.type: "semver"
          wud.link.template: "https://github.com/jorenn92/Maintainerr/releases"
        cpu_shares: "{{ maintainerr_cpu_shares }}"
        memory: "{{ maintainerr_memory }}"
        memory_swap: "{{ maintainerr_memory_swap }}"
        restart_policy: unless-stopped

    - name: Access {{ ansible_nas_app_name }} at
      ansible.builtin.debug:
        msg: >-
              {{
                ['http://' + hostvars[inventory_hostname]['ansible_default_ipv4']['address'] + ':' + (maintainerr_port_http | string)] +
                (['https://' + maintainerr_hostname + '.' + ansible_nas_domain] if (maintainerr_traefik_enabled is true or maintainerr_dockflare_enabled is true) else [])
              }}
  when: maintainerr_enabled is true

- name: Stop {{ ansible_nas_app_name }}
  block:
    - name: Stop {{ ansible_nas_app_name }} Container
      community.docker.docker_container:
        name: "{{ maintainerr_container_name }}"
        state: absent
  when: maintainerr_enabled is false

- name: Data Archive {{ ansible_nas_app_name }}
  include_role:
    name: ansible-nas-archive
  vars:
    target_data_dir: "{{ maintainerr_data_directory }}"
  when:
    - archive_app_data_enabled is true
    - maintainerr_enabled is false