---
- name: Start {{ ansible_nas_app_name }}
  block:
    - name: Create {{ ansible_nas_app_name }} Directories
      file:
        path: "{{ item }}"
        state: directory
      with_items:
        - "{{ dailytxt_data_directory }}"
        - "{{ dailytxt_data_directory }}/data"

    - name: Create {{ ansible_nas_app_name }} Container
      community.docker.docker_container:
        container_default_behavior: "compatibility"
        name: "{{ dailytxt_container_name }}"
        image: "{{ dailytxt_image_name }}:{{ dailytxt_image_tag }}"
        pull: true
        volumes:
          - "{{ dailytxt_data_directory }}/data:/app/data:rw"
        ports:
          - "{{ dailytxt_port_http }}:{{ dailytxt_port_http }}"
        env:
          ALLOW_REGISTRATION: "{{ dailytxt_allow_registration }}"
          DATA_INDENT: "2"
          JWT_EXP_DAYS: "{{ dailytxt_jwt_exp_days }}"
          PORT: "{{ dailytxt_port_http }}"
          SECRET_KEY: "{{ dailytxt_secret_key }}"
          TZ: "{{ ansible_nas_timezone }}"
        labels:
          autoheal: "{{ dailytxt_autoheal }}"
          com.centurylinklabs.watchtower.enable: "{{ dailytxt_watchtower_enable }}"
          dockflare.enable: "{{ dailytxt_dockflare_tunnel }}"
          dockflare.access.group: "{{ dailytxt_dockflare_access_group }}"
          dockflare.hostname: "{{ dailytxt_hostname }}.{{ ansible_nas_domain }}"
          dockflare.service: "http://{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}:{{ dailytxt_port_http }}"
          homepage.name: "{{ ansible_nas_app_name }}"
          homepage.group: "{{ dailytxt_homepage_group }}"
          homepage.href: "{{ dailytxt_homepage_href }}"
          homepage.icon: "{{ dailytxt_homepage_icon }}"
          homepage.siteMonitor: "http://{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}:{{ dailytxt_port_http }}"
          homepage.description: "{{ 'Encrypted Diary Web-App' if homepage_show_description else omit }}"
          homepage.server: "my-docker"
          homepage.container: "dailytxt"
          homepage.showStats: "{{ dailytxt_homepage_showstats }}"
          traefik.enable: "{{ dailytxt_available_externally | string }}"
          traefik.http.routers.dailytxt.rule: "Host(`{{ dailytxt_hostname }}.{{ ansible_nas_domain }}`)"
          traefik.http.routers.dailytxt.tls.certresolver: "letsencrypt"
          traefik.http.routers.dailytxt.tls.domains[0].main: "{{ ansible_nas_domain }}"
          traefik.http.routers.dailytxt.tls.domains[0].sans: "*.{{ ansible_nas_domain }}"
          traefik.http.routers.frontend.middlewares: "{{ dailytxt_hostname }}"
          traefik.http.routers.dailytxt.middlewares: "{{ dailytxt_hostname }}@docker"
          traefik.http.middlewares.dailytxt.IPAllowList.sourcerange: "{{ dailytxt_traefik_whitelist }}"
          traefik.http.services.dailytxt.loadbalancer.server.port: "8766"
          wud.watch.digest: "true"
          wud.link.template: "https://hub.docker.com/r/phitux/dailytxt"
        cpu_shares: "{{ dailytxt_cpu_shares }}"
        memory: "{{ dailytxt_memory }}"
        restart_policy: unless-stopped
  when: dailytxt_enabled is true

- name: Stop {{ ansible_nas_app_name }}
  block:
    - name: Stop {{ ansible_nas_app_name }} Container
      community.docker.docker_container:
        name: "{{ dailytxt_container_name }}"
        state: absent
  when: dailytxt_enabled is false

- name: Data Archive {{ ansible_nas_app_name }}
  block:
    - name: Check for {{ ansible_nas_app_name }} Data Directory
      stat:
        path: "{{ dailytxt_data_directory }}"
      register: dir_stat

    - name: Archive {{ ansible_nas_app_name }} Data Directory
      ansible.builtin.archive:
        path: "{{ dailytxt_data_directory }}"
        dest: "{{ docker_home }}/{{ ansible_nas_app_name | lower }}.zip"
        force_archive: true
        format: zip
        owner: ansible-nas
        group: ansible-nas
        mode: u=rw,g=rw
        remove: true
      when: dir_stat.stat.exists
  when: dailytxt_enabled is false and archive_app_data_enabled is true
