---
- name: Start {{ ansible_nas_app_name }}
  block:
    - name: Create {{ ansible_nas_app_name }} Directories
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
      with_items:
        - "{{ dailytxt_data_directory }}"
        - "{{ dailytxt_data_directory }}/data"

    - name: Create {{ ansible_nas_app_name }} Container
      community.docker.docker_container:
        container_default_behavior: "compatibility"
        name: "{{ dailytxt_container_name }}"
        hostname: "{{ dailytxt_container_name }}"
        image: "{{ dailytxt_image_name }}:{{ dailytxt_image_tag }}"
        pull: true
        volumes:
          - "{{ dailytxt_data_directory }}/data:/data:rw"
        ports:
          - "{{ dailytxt_port_http }}:80"
        env:
          ADMIN_PASSWORD: "{{ dailytxt_env_admin_password }}"
          ALLOW_REGISTRATION: "{{ dailytxt_env_allow_registration }}"
          DATA_INDENT: "{{ dailytxt_env_data_indent }}"
          JWT_EXP_DAYS: "{{ dailytxt_env_jwt_exp_days }}"
          LOGOUT_AFTER_DAYS: "{{ dailytxt_env_logout_after_days }}"
          SECRET_KEY: "{{ dailytxt_env_secret_key }}"
          TZ: "{{ ansible_nas_timezone }}"
        labels:
          autoheal: "{{ dailytxt_autoheal | string }}"
          com.centurylinklabs.watchtower.enable: "{{ dailytxt_watchtower_enabled| string }}"
          dockflare.enable: "{{ dailytxt_dockflare_enabled | string }}"
          dockflare.access.group: "{{ dailytxt_dockflare_access_group }}"
          dockflare.hostname: "{{ dailytxt_hostname }}.{{ ansible_nas_domain }}"
          dockflare.service: "http://{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}:{{ dailytxt_port_http }}"
          homepage.name: "{{ ansible_nas_app_name }}"
          homepage.group: "{{ dailytxt_homepage_group }}"
          homepage.href: "{{ dailytxt_homepage_href }}"
          homepage.icon: "{{ dailytxt_homepage_icon }}"
          homepage.siteMonitor: "http://{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}:{{ dailytxt_port_http }}"
          homepage.description: "{{ 'Encrypted Diary Web-App' if homepage_show_description else omit }}"
          homepage.server: "my-docker"
          homepage.container: "dailytxt"
          homepage.showStats: "{{ dailytxt_homepage_showstats | string }}"
          repliqate.enabled: "{{ dailytxt_repliqate_enabled | string }}"
          repliqate.engine: "{{ dailytxt_repliqate_engine }}"
          repliqate.schedule: "{{ dailytxt_repliqate_schedule }}"
          repliqate.backup_id: "{{ dailytxt_repliqate_backup_id }}"
          repliqate.retention: "{{ dailytxt_repliqate_retention }}"
          traefik.enable: "{{ dailytxt_available_externally | string }}"
          traefik.http.routers.dailytxt.rule: "Host(`{{ dailytxt_hostname }}.{{ ansible_nas_domain }}`)"
          traefik.http.routers.dailytxt.tls.certresolver: "letsencrypt"
          traefik.http.routers.dailytxt.tls.domains[0].main: "{{ ansible_nas_domain }}"
          traefik.http.routers.dailytxt.tls.domains[0].sans: "*.{{ ansible_nas_domain }}"
          traefik.http.routers.dailytxt.middlewares: "dailytxt@docker{{ ',tinyauth-auth@docker' if dailytxt_tinyauth_enabled | bool else '' }}"
          traefik.http.middlewares.dailytxt.IPAllowList.sourcerange: "{{ dailytxt_traefik_whitelist }}"
          traefik.http.services.dailytxt.loadbalancer.server.port: "80"
          wud.watch.digest: "true"
          wud.link.template: "https://hub.docker.com/r/phitux/dailytxt"
        cpu_shares: "{{ dailytxt_cpu_shares }}"
        memory: "{{ dailytxt_memory }}"
        memory_swap: "{{ dailytxt_memory_swap }}"
        restart_policy: unless-stopped

    - name: Access {{ ansible_nas_app_name }} at
      ansible.builtin.debug:
        msg: >-
              {{
                ['http://' + hostvars[inventory_hostname]['ansible_default_ipv4']['address'] + ':' + (dailytxt_port_http | string)] +
                (['https://' + dailytxt_hostname + '.' + ansible_nas_domain] if (dailytxt_available_externally is true or dailytxt_dockflare_enabled is true) else [])
              }}
  when: dailytxt_enabled is true

- name: Stop {{ ansible_nas_app_name }}
  block:
    - name: Stop {{ ansible_nas_app_name }} Container
      community.docker.docker_container:
        name: "{{ dailytxt_container_name }}"
        state: absent
  when: dailytxt_enabled is false

- name: Data Archive {{ ansible_nas_app_name }}
  include_role:
    name: ansible-nas-archive
  vars:
    target_data_dir: "{{ dailytxt_data_directory }}"
  when:
    - archive_app_data_enabled is true
    - dailytxt_enabled is false