---
# ANE
ansible_nas_app_name: "GitLab"
gitlab_enabled: false
gitlab_available_externally: false
gitlab_traefik_whitelist: "{{ lan }}"

# directories
gitlab_data_directory: "{{ docker_home }}/gitlab"

# network
gitlab_hostname: "gitlab"
gitlab_port_http: "4080"
gitlab_port_https: "4443"
gitlab_port_ssh: "422"

# docker
gitlab_container_name: "gitlab"
gitlab_image_name: "gitlab/gitlab-ce"
gitlab_image_version: "latest"
gitlab_cpu_shares: 1024

# app
gitlab_user_id: "1000"
gitlab_group_id: "1000"

# specs
gitlab_memory: "4g"

# autoheal
gitlab_autoheal: "false"

# dockflare
gitlab_dockflare_tunnel: "false"
gitlab_dockflare_access_group: ""

# homepage
gitlab_homepage_group: "Apps"
gitlab_homepage_icon: "gitlab.png"
gitlab_homepage_href: "http://{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}:{{ gitlab_port }}"
gitlab_homepage_showstats: "false"

# repliqate
gitlab_repliqate_enabled: "false"
gitlab_repliqate_engine: "restic"
gitlab_repliqate_schedule: "@daily 3am"
gitlab_repliqate_backup_id: "{{ gitlab_container_name }}"
gitlab_repliqate_retention: "30d"

# watchtower
gitlab_watchtower_enable: "false"