---
# https://github.com/openemr/openemr/blob/master/docker/production/docker-compose.yml
- name: Start {{ ansible_nas_app_name }}
  block:
    - name: Create {{ ansible_nas_app_name }} Directories
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
      with_items:
        - "{{ openemr_data_directory }}"
        - "{{ openemr_data_directory }}/db"
        - "{{ openemr_data_directory }}/log"
        - "{{ openemr_data_directory }}/sites"
        - "{{ openemr_data_directory }}/sites/default"

    - name: Create {{ ansible_nas_app_name }} network
      community.docker.docker_network:
        name: "{{ openemr_network_name }}"

    - name: Create {{ ansible_nas_app_name }} DB Container
      community.docker.docker_container:
        container_default_behavior: "compatibility"
        name: "{{ openemr_db_container_name }}"
        hostname: "{{ openemr_db_container_name }}"
        image: "{{ openemr_db_image_name }}:{{ openemr_db_image_tag }}"
        pull: true
        command: 'mariadb --character-set-server=utf8mb4'
        network_mode: "bridge"
        networks:
          - name: "{{ openemr_network_name }}"
        networks_cli_compatible: "yes"
        volumes:
          - "{{ openemr_data_directory }}/db:/var/lib/mysql"
        env:
          ALLOW_EMPTY_PASSWORD: "{{ openemr_db_env_allow_empty_password }}"
          DOCKER_MODS: "{{ openemr_db_env_docker_mods }}"
          INSTALL_PACKAGES: "{{ openemr_db_env_docker_mods_install_packages }}"
          INSTALL_PIP_PACKAGES: "{{ openemr_db_env_docker_mods_install_pip_packages}}"
          MYSQL_ROOT_PASSWORD: "{{ openemr_db_env_mysql_root_password }}"
          MYSQL_USER: "{{ openemr_env_mysql_user }}"
          MYSQL_PASSWORD: "{{ openemr_env_mysql_pass }}"
          MYSQL_DATABASE: "{{ openemr_env_mysql_database }}"
          PGID: "{{ openemr_db_group_id }}"
          PUID: "{{ openemr_db_user_id }}"
          TZ: "{{ ansible_nas_timezone }}"
        labels:
          autoheal: "{{ openemr_db_autoheal }}"
          com.centurylinklabs.watchtower.enable: "{{ openemr_db_watchtower_enable }}"
          dockflare.enable: "false"
          homepage.name: "{{ ansible_nas_app_name }} MariaDB"
          homepage.group: "{{ openemr_db_homepage_group }}"
          homepage.icon: "{{ openemr_db_homepage_icon }}"
          homepage.href: "{{ openemr_db_homepage_href }}"
          homepage.description: "{{ 'MariaDB' if homepage_show_description else omit }}"
          homepage.server: "my-docker"
          homepage.container: "{{ openemr_db_container_name }}"
          homepage.showStats: "{{ openemr_db_homepage_showstats }}"
          repliqate_db.enabled: "{{ openemr_repliqate_enabled }}"
          repliqate_db.engine: "{{ openemr_repliqate_engine }}"
          repliqate_db.schedule: "{{ openemr_repliqate_schedule }}"
          repliqate_db.backup_id: "{{ openemr_repliqate_backup_id }}"
          repliqate_db.retention: "{{ openemr_repliqate_retention }}"
          traefik.enable: "false"
          wud.tag.include: '^\d+\.\d+\.\d+.*$'
          wud.tag.transform.type: "semver"
          wud.link.template: "https://lscr.io/linuxserver/mariadb"
        cpu_shares: "{{ openemr_db_cpu_shares }}"
        memory: "{{ openemr_db_memory }}"
        restart_policy: unless-stopped

    - name: Create {{ ansible_nas_app_name }} Container
      community.docker.docker_container:
        container_default_behavior: "compatibility"
        name: "{{ openemr_container_name }}"
        hostname: "{{ openemr_container_name }}"
        image: "{{ openemr_image_name }}:{{ openemr_image_tag }}"
        pull: true
        network_mode: "bridge"
        networks:
          - name: "{{ openemr_network_name }}"
        networks_cli_compatible: "yes"
        ports:
          - "{{ openemr_port_http }}:80"
        volumes:
          - "{{ openemr_data_directory }}/log:/var/log"
          - "{{ openemr_data_directory }}/sites:/var/www/localhost/htdocs/openemr/sites"
        env:
          MYSQL_HOST: "{{ openemr_db_container_name }}"
          MYSQL_ROOT_PASS: "{{ openemr_env_mysql_root_pass }}"
          MYSQL_USER: "{{ openemr_env_mysql_user }}"
          MYSQL_PASS: "{{ openemr_env_mysql_pass }}"
          MYSQL_DATABASE: "{{ openemr_env_mysql_database }}"
          OE_USER: "{{ openemr_env_oe_user }}"
          OE_PASS: "{{ openemr_admin_password }}"
          OPENEMR__ENVIRONMENT: "{{ openemr_env_openemr__environment }}"
          TZ: "{{ ansible_nas_timezone }}"
        healthcheck:
          test:
          - CMD
          - /usr/bin/curl
          - --fail
          - --insecure
          - --location
          - --show-error
          - --silent
          - https://localhost/
          start_period: "3m"
          start_interval: "10s"
          interval: "1m"
          timeout: "5s"
          retries: 3
        links:
          - "{{ openemr_db_container_name }}"
        labels:
          autoheal: "{{ openemr_autoheal }}"
          com.centurylinklabs.watchtower.enable: "{{ openemr_watchtower_enable }}"
          dockflare.enable: "{{ openemr_dockflare_tunnel }}"
          dockflare.access.group: "{{ openemr_dockflare_access_group }}"
          dockflare.hostname: "{{ openemr_hostname }}.{{ ansible_nas_domain }}"
          dockflare.service: "http://{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}:{{ openemr_port_http }}"
          homepage.name: "{{ ansible_nas_app_name }}"
          homepage.group: "{{ openemr_homepage_group }}"
          homepage.icon: "{{ openemr_homepage_icon }}"
          homepage.href: "{{ openemr_homepage_href }}"
          homepage.siteMonitor: "http://{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}:{{ openemr_port_http }}"
          homepage.description: "{{ 'Free and Open Source electronic health records and medical practice management application' if homepage_show_description else omit }}"
          homepage.server: "my-docker"
          homepage.container: "{{ openemr_container_name }}"
          homepage.showStats: "{{ openemr_homepage_showstats }}"
          repliqate.enabled: "{{ openemr_repliqate_enabled }}"
          repliqate.engine: "{{ openemr_repliqate_engine }}"
          repliqate.schedule: "{{ openemr_repliqate_schedule }}"
          repliqate.backup_id: "{{ openemr_repliqate_backup_id }}"
          repliqate.retention: "{{ openemr_repliqate_retention }}"
          traefik.enable: "{{ openemr_available_externally | string }}"
          traefik.http.routers.openemr.rule: "Host(`{{ openemr_hostname }}.{{ ansible_nas_domain }}`)"
          traefik.http.routers.openemr.tls.certresolver: "letsencrypt"
          traefik.http.routers.openemr.tls.domains[0].main: "{{ ansible_nas_domain }}"
          traefik.http.routers.openemr.tls.domains[0].sans: "*.{{ ansible_nas_domain }}"
          traefik.http.routers.frontend.middlewares: "{{ openemr_hostname }}"
          traefik.http.routers.openemr.middlewares: "{{ openemr_hostname }}@docker"
          traefik.http.middlewares.openemr.IPAllowList.sourcerange: "{{ openemr_traefik_whitelist }}"
          traefik.http.services.openemr.loadbalancer.server.port: "80"
          wud.tag.include: '^\d+\.\d+\.\d+.*$'
          wud.tag.transform.type: "semver"
          wud.link.template: "https://hub.docker.com/r/openemr/openemr"
        cpu_shares: "{{ openemr_cpu_shares }}"
        memory: "{{ openemr_memory }}"
        restart_policy: unless-stopped

    - name: Access {{ ansible_nas_app_name }} at
      ansible.builtin.debug:
        msg: >-
              {{
                ['http://' + hostvars[inventory_hostname]['ansible_default_ipv4']['address'] + ':' + (openemr_port_http | string)] +
                (['https://' + openemr_hostname + '.' + ansible_nas_domain] if (openemr_available_externally is true or openemr_dockflare_tunnel is true) else [])
              }}
  when: openemr_enabled is true

- name: Stop {{ ansible_nas_app_name }}
  block:
    - name: Stop {{ ansible_nas_app_name }} Container
      community.docker.docker_container:
        name: "{{ openemr_container_name }}"
        state: absent

    - name: Stop {{ ansible_nas_app_name }} DB Container
      community.docker.docker_container:
        name: "{{ openemr_db_container_name }}"
        state: absent

    - name: Delete {{ ansible_nas_app_name }} Network
      community.docker.docker_network:
        name: "{{ openemr_network_name }}"
        state: absent
  when: openemr_enabled is false

- name: Data Archive {{ ansible_nas_app_name }}
  block:
    - name: Check for {{ ansible_nas_app_name }} Data Directory
      stat:
        path: "{{ openemr_data_directory }}"
      register: dir_stat

    - name: Archive {{ ansible_nas_app_name }} Data Directory
      ansible.builtin.archive:
        path: "{{ openemr_data_directory }}"
        dest: "{{ docker_home }}/{{ ansible_nas_app_name | lower }}.zip"
        force_archive: true
        format: zip
        owner: ansible-nas
        group: ansible-nas
        mode: u=rw,g=rw
        remove: true
      when: dir_stat.stat.exists
  when: openemr_enabled is false and archive_app_data_enabled is true
