---
- name: Start {{ ansible_nas_app_name }}
  block:
    - name: Create {{ ansible_nas_app_name }} Directories
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
      with_items:
        - "{{ openemr_data_directory }}"
        - "{{ openemr_data_directory }}/db"

    - name: Create {{ ansible_nas_app_name }} Docker volumes
      community.docker.docker_volume:
        name: "{{ item }}"
      loop:
        - openemr_logvolume
        - openemr_sitevolume

    - name: Set {{ ansible_nas_app_name }} FQDN var overrides
      ansible.builtin.set_fact:
        openemr_homepage_href: "https://{{ openemr_hostname }}.{{ ansible_nas_domain }}"
      when: openemr_traefik_enabled | bool or openemr_dockflare_enabled | bool

    - name: Create {{ ansible_nas_app_name }} Network
      community.docker.docker_network:
        name: "{{ openemr_network_name }}"

    - name: Create {{ ansible_nas_app_name }} DB Container
      community.docker.docker_container:
        container_default_behavior: "compatibility"
        name: "{{ openemr_db_container_name }}"
        hostname: "{{ openemr_db_container_name }}"
        image: "{{ openemr_db_image_name }}:{{ openemr_db_image_tag }}"
        pull: true
        command: ['mysqld','--character-set-server=utf8mb4','--binlog-expire-logs-seconds=0']
        network_mode: bridge
        networks:
          - name: "{{ openemr_network_name }}"
        networks_cli_compatible: "yes"
        volumes:
          - "{{ openemr_data_directory }}/db:/var/lib/mysql"
        env:
          ALLOW_EMPTY_PASSWORD: "{{ openemr_db_env_allow_empty_password }}"
          MYSQL_DATABASE: "{{ openemr_env_mysql_database }}"
          MYSQL_USER: "{{ openemr_env_mysql_user }}"
          MYSQL_PASSWORD: "{{ openemr_env_mysql_pass }}"
          MYSQL_ROOT_PASSWORD: "{{ openemr_env_mysql_root_pass }}"
          TZ: "{{ ansible_nas_timezone }}"
        healthcheck:
              test:
                - CMD-SHELL
                - 'mariadb-admin ping -h localhost -p{{ openemr_env_mysql_root_pass }} --silent'
              interval: "20s"
              timeout: "10s"
              retries: "5"
        labels:
          autoheal: "{{ openemr_db_autoheal_enabled | ternary('true', 'false') }}"
          com.centurylinklabs.watchtower.enable: "{{ openemr_db_watchtower_enabled | ternary('true', 'false') }}"
          dockflare.enable: "false"
          homepage.name: "{{ ansible_nas_app_name }} MariaDB"
          homepage.group: "{{ openemr_db_homepage_group }}"
          homepage.icon: "{{ openemr_db_homepage_icon }}"
          homepage.href: "{{ openemr_db_homepage_href }}"
          homepage.description: "{{ 'MariaDB' if homepage_show_description else omit }}"
          homepage.server: "my-docker"
          homepage.container: "{{ openemr_db_container_name }}"
          homepage.showStats: "{{ openemr_db_homepage_showstats | ternary('true', 'false') }}"
          repliqate_db.enabled: "{{ openemr_repliqate_enabled | ternary('true', 'false') }}"
          repliqate_db.engine: "{{ openemr_repliqate_engine }}"
          repliqate_db.schedule: "{{ openemr_repliqate_schedule }}"
          repliqate_db.backup_id: "{{ openemr_repliqate_backup_id }}"
          repliqate_db.retention: "{{ openemr_repliqate_retention }}"
          traefik.enable: "false"
          wud.tag.include: '^\d+\.\d+\.\d+.*$'
          wud.tag.transform.type: "semver"
          wud.link.template: "https://lscr.io/linuxserver/mariadb"
        cpu_shares: "{{ openemr_db_cpu_shares }}"
        memory: "{{ openemr_db_memory }}"
        memory_swap: "{{ openemr_db_memory_swap }}"
        restart_policy: unless-stopped

    - name: Verify {{ ansible_nas_app_name }} DB is healthy
      community.docker.docker_container_info:
        name: "{{ openemr_db_container_name }}"
      register: db_info
      until: "db_info.container.State.Health.Status == 'healthy'"
      retries: 30
      delay: 5

    - name: Create {{ ansible_nas_app_name }} Container
      community.docker.docker_container:
        container_default_behavior: "compatibility"
        name: "{{ openemr_container_name }}"
        hostname: "{{ openemr_container_name }}"
        image: "{{ openemr_image_name }}:{{ openemr_image_tag }}"
        pull: true
        network_mode: bridge
        networks:
          - name: "{{ openemr_network_name }}"
        networks_cli_compatible: "yes"
        ports:
          - "{{ openemr_port_http }}:80"
        volumes:
          - logvolume:/var/log
          - sitevolume:/var/www/localhost/htdocs/openemr/sites
        env:
          MYSQL_HOST: "{{ openemr_db_container_name }}"
          MYSQL_DATABASE: "{{ openemr_env_mysql_database }}"
          MYSQL_USER: "{{ openemr_env_mysql_user }}"
          MYSQL_PASS: "{{ openemr_env_mysql_pass }}"
          MYSQL_ROOT_PASS: "{{ openemr_env_mysql_root_pass }}"
          OE_USER: "{{ openemr_env_oe_user }}"
          OE_PASS: "{{ openemr_admin_password }}"
          OPENEMR__ENVIRONMENT: "{{ openemr_env_openemr__environment }}"
          TZ: "{{ ansible_nas_timezone }}"
        healthcheck:
          test:
          - CMD
          - /usr/bin/curl
          - --fail
          - --insecure
          - --location
          - --show-error
          - --silent
          - https://localhost/
          start_period: "3m"
          start_interval: "10s"
          interval: "1m"
          timeout: "5s"
          retries: 3
        links:
          - "{{ openemr_db_container_name }}"
        labels:
          autoheal: "{{ openemr_autoheal_enabled | ternary('true', 'false') }}"
          com.centurylinklabs.watchtower.enable: "{{ openemr_watchtower_enabled | ternary('true', 'false') }}"
          dockflare.enable: "{{ openemr_dockflare_enabled | ternary('true', 'false') }}"
          dockflare.access.group: "{{ openemr_dockflare_access_group }}"
          dockflare.hostname: "{{ openemr_hostname }}.{{ ansible_nas_domain }}"
          dockflare.service: "http://{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}:{{ openemr_port_http }}"
          homepage.name: "{{ ansible_nas_app_name }}"
          homepage.group: "{{ openemr_homepage_group }}"
          homepage.icon: "{{ openemr_homepage_icon }}"
          homepage.href: "{{ openemr_homepage_href }}"
          homepage.siteMonitor: "http://{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}:{{ openemr_port_http }}"
          homepage.description: "{{ 'Free and Open Source electronic health records and medical practice management application' if homepage_show_description else omit }}"
          homepage.server: "my-docker"
          homepage.container: "{{ openemr_container_name }}"
          homepage.showStats: "{{ openemr_homepage_showstats | ternary('true', 'false') }}"
          repliqate.enabled: "{{ openemr_repliqate_enabled | ternary('true', 'false') }}"
          repliqate.engine: "{{ openemr_repliqate_engine }}"
          repliqate.schedule: "{{ openemr_repliqate_schedule }}"
          repliqate.backup_id: "{{ openemr_repliqate_backup_id }}"
          repliqate.retention: "{{ openemr_repliqate_retention }}"
          traefik.enable: "{{ openemr_traefik_enabled | ternary('true', 'false') }}"
          traefik.http.routers.openemr.rule: "Host(`{{ openemr_hostname }}.{{ ansible_nas_domain }}`)"
          traefik.http.routers.openemr.tls.certresolver: "letsencrypt"
          traefik.http.routers.openemr.tls.domains[0].main: "{{ ansible_nas_domain }}"
          traefik.http.routers.openemr.tls.domains[0].sans: "*.{{ ansible_nas_domain }}"
          traefik.http.routers.openemr.middlewares: "openemr@docker{{ ',tinyauth-auth@docker' if openemr_tinyauth_enabled | bool else '' }}"
          traefik.http.middlewares.openemr.IPAllowList.sourcerange: "{{ openemr_traefik_whitelist }}"
          traefik.http.services.openemr.loadbalancer.server.port: "80"
          wud.tag.include: '^\d+\.\d+\.\d+.*$'
          wud.tag.transform.type: "semver"
          wud.link.template: "https://hub.docker.com/r/openemr/openemr"
        cpu_shares: "{{ openemr_cpu_shares }}"
        memory: "{{ openemr_memory }}"
        memory_swap: "{{ openemr_memory_swap }}"
        restart_policy: unless-stopped

    - name: Access {{ ansible_nas_app_name }} at
      ansible.builtin.debug:
        msg: >-
              {{
                ['http://' + hostvars[inventory_hostname]['ansible_default_ipv4']['address'] + ':' + (openemr_port_http | string)] +
                (['https://' + openemr_hostname + '.' + ansible_nas_domain] if (openemr_traefik_enabled is true or openemr_dockflare_enabled is true) else [])
              }}
  when: openemr_enabled is true

- name: Stop {{ ansible_nas_app_name }}
  block:
    - name: Stop {{ ansible_nas_app_name }} Container
      community.docker.docker_container:
        name: "{{ openemr_container_name }}"
        state: absent

    - name: Stop {{ ansible_nas_app_name }} DB Container
      community.docker.docker_container:
        name: "{{ openemr_db_container_name }}"
        state: absent

    - name: Delete {{ ansible_nas_app_name }} Network
      community.docker.docker_network:
        name: "{{ openemr_network_name }}"
        state: absent
  when: openemr_enabled is false

- name: Data Archive {{ ansible_nas_app_name }}
  include_role:
    name: ansible-nas-archive
  vars:
    target_data_dir: "{{ openemr_data_directory }}"
  when:
    - archive_app_data_enabled is true
    - openemr_enabled is false