---
# ANE
fasten_proper_name: "Fasten"
fasten_enabled: false
fasten_traefik_enabled: false
fasten_traefik_whitelist: "{{ lan }}"
fasten_data_directory: "{{ docker_home }}/fasten"

# network 
fasten_hostname: "fasten"
fasten_port_http: "3068"

# docker
fasten_container_name: "fasten"
fasten_image_name: "ghcr.io/fastenhealth/fasten-onprem"
fasten_image_tag: "main"

# specs
fasten_cpu_shares: 1024
fasten_memory: "1G"
fasten_memory_swap: -1

# autoheal
fasten_autoheal_enabled: false

# dockflare
fasten_dockflare_enabled: false
fasten_dockflare_access_group: ""

# homepage
fasten_homepage_group: "Apps"
fasten_homepage_icon: "fasten.png"
fasten_homepage_href: "http://{{ hostvars[inventory_hostname]['ansible_facts']['default_ipv4']['address'] }}:{{ fasten_port_http }}"
fasten_homepage_showstats: false

# repliqate
fasten_repliqate_enabled: false
fasten_repliqate_engine: "restic"
fasten_repliqate_schedule: "@daily 3am"
fasten_repliqate_backup_id: "{{ fasten_container_name }}"
fasten_repliqate_retention: "30d"

# tinyauth
fasten_tinyauth_enabled: false

# watchtower
fasten_watchtower_enabled: false