---
- name: Start {{ ansible_nas_app_name }}
  block:
    - name: Create {{ ansible_nas_app_name }} Network
      community.docker.docker_network:
        name: "{{ pdm_network_name }}"

    - name: Create {{ ansible_nas_app_name }} Container
      community.docker.docker_container:
        container_default_behavior: "compatibility"
        name: "{{ pdm_container_name }}"
        hostname: "{{ pdm_container_name }}"
        image: "{{ pdm_image_name }}:{{ pdm_image_tag }}"
        pull: true
        networks:
          - name: "{{ pdm_network_name }}"
        network_mode: "{{ pdm_network_name }}"
        networks_cli_compatible: "yes"
        capabilities:	['ALL']
        cgroupns_mode: host
        security_opts: 
          - apparmor=unconfined
          - seccomp=unconfined
        volumes:
          - "/sys/fs/cgroup:/sys/fs/cgroup"
        ports:
          - "{{ pdm_port_http }}:8443"
          - "{{ pdm_port_ssh }}:22"
        env:
          TZ: "{{ ansible_nas_timezone }}"
        labels:
          autoheal: "{{ pdm_autoheal | string }}"
          com.centurylinklabs.watchtower.enable: "{{ pdm_watchtower_enable | string }}"
          dockflare.enable: "{{ pdm_dockflare_tunnel | string }}"
          dockflare.access.group: "{{ pdm_dockflare_access_group }}"
          dockflare.hostname: "{{ pdm_hostname }}.{{ ansible_nas_domain }}"
          dockflare.option.no-tls-verify: "true"
          dockflare.service: "https://{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}:{{ pdm_port_http }}"
          homepage.name: "{{ ansible_nas_app_name }}"
          homepage.group: "{{ pdm_homepage_group }}"
          homepage.icon: "{{ pdm_homepage_icon }}"
          homepage.href: "{{ pdm_homepage_href }}"
          homepage.description: "{{ 'pdm description' if homepage_show_description else omit }}"
          homepage.server: "my-docker"
          homepage.container: "{{ pdm_container_name }}"
          homepage.showStats: "{{ pdm_homepage_showstats }}"
          homepage.siteMonitor: "https://{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}:{{ pdm_port_http }}"
          repliqate.enabled: "{{ pdm_repliqate_enabled | string }}"
          repliqate.engine: "{{ pdm_repliqate_engine }}"
          repliqate.schedule: "{{ pdm_repliqate_schedule }}"
          repliqate.backup_id: "{{ pdm_repliqate_backup_id }}"
          repliqate.retention: "{{ pdm_repliqate_retention }}"
          traefik.enable: "{{ pdm_available_externally | string }}"
          traefik.http.routers.pdm.rule: "Host(`{{ pdm_hostname }}.{{ ansible_nas_domain }}`)"
          traefik.http.routers.pdm.tls.certresolver: "letsencrypt"
          traefik.http.routers.pdm.tls.domains[0].main: "{{ ansible_nas_domain }}"
          traefik.http.routers.pdm.tls.domains[0].sans: "*.{{ ansible_nas_domain }}"
          traefik.http.routers.pdm.middlewares: "pdm@docker{{ ',tinyauth-auth@docker' if pdm_tinyauth_enabled | bool else '' }}"
          traefik.http.middlewares.pdm.IPAllowList.sourcerange: "{{ pdm_traefik_whitelist }}"
          traefik.http.services.pdm.loadbalancer.server.scheme: "https"
          traefik.http.services.pdm.loadbalancer.serverstransport: "insecureTransport@file"
          traefik.http.services.pdm.loadbalancer.server.port: "8443"
          wud.tag.include: "^latest$"
          wud.tag.transform.type: "semver"
          wud.link.template: "https://github.com/LongQT-Sea/Proxmox-Datacenter-Manager/releases"
        cpu_shares: "{{ pdm_cpu_shares }}"
        memory: "{{ pdm_memory }}"
        memory_swap: "{{ pdm_memory_swap }}"
        restart_policy: unless-stopped

    - name: Set password for {{ ansible_nas_app_name }} user
      community.docker.docker_container_exec:
        container: "{{ pdm_container_name }}"
        command: /bin/sh -c "printf '{{ pdm_root_password }}\n{{ pdm_root_password }}\n' | passwd"
      no_log: true 

    - name: Access {{ ansible_nas_app_name }} at
      ansible.builtin.debug:
        msg: >-
              {{
                ['https://' + hostvars[inventory_hostname]['ansible_default_ipv4']['address'] + ':' + (pdm_port_http | string)] +
                (['https://' + pdm_hostname + '.' + ansible_nas_domain] if (pdm_available_externally | bool or pdm_dockflare_tunnel | bool) else [])
              }}
  when: pdm_enabled is true

- name: Stop {{ ansible_nas_app_name }}
  block:
    - name: Stop {{ ansible_nas_app_name }} Container
      community.docker.docker_container:
        name: "{{ pdm_container_name }}"
        state: absent
  when: pdm_enabled is false
