---
# ANE
ansible_nas_app_name: "Unpackerr"
unpackerr_enabled: false

# directories
unpackerr_data_directory: "{{ docker_home }}/unpackerr"
unpackerr_downloads_directory: "{{ downloads_root }}"

# docker
unpackerr_container_name: "unpackerr"
unpackerr_image_name: "golift/unpackerr"
unpackerr_image_tag: "latest"

# specs
unpackerr_cpu_shares: 1024
unpackerr_memory: "1G"

# app
unpackerr_env_un_lidarr_0_api_key: ""
unpackerr_env_un_sonarr_0_api_key: ""
unpackerr_env_un_radarr_0_api_key: ""
unpackerr_env_un_readarr_0_api_key: ""
unpackerr_env_un_whisparr_0_api_key: ""

# autoheal
unpackerr_autoheal: false

# homepage
unpackerr_homepage_group: "Misc"
unpackerr_homepage_icon: "sh-unpackerr.png"
unpackerr_homepage_showstats: false

# watchtower
unpackerr_watchtower_enabled: false

# NOTE: There are more env vars that could be implemented
# https://unpackerr.zip/docs/install/configuration
