---
# ANE
ansible_nas_app_name: "Uptime Kuma"
uptimekuma_enabled: false
uptimekuma_available_externally: false
uptimekuma_traefik_whitelist: "{{ lan }}"
uptimekuma_data_directory: "{{ docker_home }}/uptime-kuma"

# network
uptimekuma_hostname: "uptimekuma"
uptimekuma_port_http: "3004"

# docker
uptimekuma_container_name: "uptime-kuma"
uptimekuma_image_name: "louislam/uptime-kuma"
uptimekuma_image_tag: "latest"
uptimekuma_cpu_shares: "1024"
uptimekuma_memory: "512m"

# autoheal
uptimekuma_autoheal: "false"

# dockflare
uptimekuma_dockflare_tunnel: "false"
uptimekuma_dockflare_access_group: ""

# homepage
uptimekuma_homepage_group: "Apps"
uptimekuma_homepage_icon: "uptime-kuma.png"
uptimekuma_homepage_href: "http://{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}:{{ uptimekuma_port_http }}"
uptimekuma_homepage_widget_slug: "{{ ansible_nas_hostname }}"
uptimekuma_homepage_showStats: "false"

# watchtower
uptimekuma_watchtower_monitor_only: "true"