---
# ANE
ansible_nas_app_name: "Uptime Kuma"
uptime_kuma_enabled: false
uptime_kuma_traefik_enabled: false
uptime_kuma_traefik_whitelist: "{{ lan }}"
uptime_kuma_data_directory: "{{ docker_home }}/uptime-kuma"

# network
uptime_kuma_hostname: "uptimekuma"
uptime_kuma_port_http: "3004"

# docker
uptime_kuma_container_name: "uptime-kuma"
uptime_kuma_image_name: "ghcr.io/louislam/uptime-kuma"
uptime_kuma_image_tag: "2"

# specs
uptime_kuma_cpu_shares: 1024
uptime_kuma_memory: "512M"
uptime_kuma_memory_swap: -1

# autoheal
uptime_kuma_autoheal_enabled: false

# dockflare
uptime_kuma_dockflare_enabled: false
uptime_kuma_dockflare_access_group: ""

# homepage
uptime_kuma_homepage_group: "Apps"
uptime_kuma_homepage_icon: "uptime-kuma.png"
uptime_kuma_homepage_href: "http://{{ hostvars[inventory_hostname]['ansible_facts']['default_ipv4']['address'] }}:{{ uptime_kuma_port_http }}"
uptime_kuma_homepage_widget_slug: "{{ ansible_nas_hostname }}"
uptime_kuma_homepage_showstats: false

# repliqate
uptime_kuma_repliqate_enabled: false
uptime_kuma_repliqate_engine: "restic"
uptime_kuma_repliqate_schedule: "@daily 3am"
uptime_kuma_repliqate_backup_id: "{{ uptime_kuma_container_name }}"
uptime_kuma_repliqate_retention: "30d"

# tinyauth
uptime_kuma_tinyauth_enabled: false

# watchtower
uptime_kuma_watchtower_enabled: false