---
- name: Start {{ ansible_nas_app_name }}
  block:
    - name: Create {{ ansible_nas_app_name }} Directory
      ansible.builtin.file:
        path: "{{ tiddlywiki_data_directory }}"
        state: directory

    - name: Create {{ ansible_nas_app_name }} Container
      community.docker.docker_container:
        name: "{{ tiddlywiki_container_name }}"
        hostname: "{{ tiddlywiki_container_name }}"
        image: "{{ tiddlywiki_image_name }}:{{ tiddlywiki_image_version }}"
        ports:
          - "{{ tiddlywiki_port }}:8080"
        volumes:
          - "{{ tiddlywiki_data_directory }}:/var/lib/tiddlywiki"
        env:
          NODE_MEM: "{{ tiddlywiki_node_memory | default(omit) }}"
          USERNAME: "{{ tiddlywiki_username | default(omit) }}"
          PASSWORD: "{{ tiddlywiki_password | default(omit) }}"
          DEBUG: "{{ tiddlywiki_debug_level | default(omit) }}"
        pull: true
        restart_policy: unless-stopped
        cpu_shares: "{{ tiddlywiki_cpu_shares }}"
        memory: "{{ tiddlywiki_memory }}"
        labels:
          autoheal: "{{ tiddlywiki_autoheal }}"
          com.centurylinklabs.watchtower.monitor-only: "{{ tiddlywiki_watchtower_monitor_only }}"
          traefik.enable: "{{ tiddlywiki_available_externally | string }}"
          traefik.http.routers.tiddlywiki.rule: "Host(`{{ tiddlywiki_hostname }}.{{ ansible_nas_domain }}`)"
          traefik.http.routers.tiddlywiki.tls.certresolver: "letsencrypt"
          traefik.http.routers.tiddlywiki.tls.domains[0].main: "{{ ansible_nas_domain }}"
          traefik.http.routers.tiddlywiki.tls.domains[0].sans: "*.{{ ansible_nas_domain }}"
          traefik.http.services.tiddlywiki.loadbalancer.server.port: "8080"
  when: tiddlywiki_enabled is true

- name: Stop {{ ansible_nas_app_name }}
  block:
    - name: Stop {{ ansible_nas_app_name }} Container
      community.docker.docker_container:
        name: "{{ tiddlywiki_container_name }}"
        state: absent
  when: tiddlywiki_enabled is false

- name: Data Archive {{ ansible_nas_app_name }}
  block:
    - name: Check for {{ ansible_nas_app_name }} Data Directory
      stat:
        path: "{{ tiddlywiki_data_directory }}"
      register: dir_stat

    - name: Archive {{ ansible_nas_app_name }} Data Directory
      ansible.builtin.archive:
        path: "{{ tiddlywiki_data_directory }}"
        dest: "{{ docker_home }}/{{ ansible_nas_app_name | lower }}.zip"
        force_archive: true
        format: zip
        owner: ansible-nas
        group: ansible-nas
        mode: u=rw,g=rw
        remove: true
      when: dir_stat.stat.exists
  when: tiddlywiki_enabled is false and archive_app_data_enabled is true
