---
# ANE
ansible_nas_app_name: "Prowlarr"
prowlarr_enabled: false
prowlarr_traefik_enabled: false
prowlarr_traefik_whitelist: "{{ lan }}"

# directories
prowlarr_data_directory: "{{ docker_home }}/prowlarr"

# uid / gid
prowlarr_user_id: "0"
prowlarr_group_id: "0"

# network
prowlarr_port_http: "9696"
prowlarr_hostname: "prowlarr"

# docker
prowlarr_container_name: "prowlarr"
prowlarr_image_name: "lscr.io/linuxserver/prowlarr"
prowlarr_image_version: "develop"

# specs
prowlarr_cpu_shares: 1024
prowlarr_memory: "1G"
prowlarr_memory_swap: -1

# autoheal
prowlarr_autoheal_enabled: false

# dockflare
prowlarr_dockflare_enabled: false
prowlarr_dockflare_access_group: ""

# homepage
prowlarr_homepage_group: "Download Tools"
prowlarr_homepage_icon: "prowlarr.png"
prowlarr_homepage_href: "http://{{ hostvars[inventory_hostname]['ansible_facts']['default_ipv4']['address'] }}:{{ prowlarr_port_http }}"
prowlarr_homepage_showstats: false
prowlarr_homepage_widget_key: ""

# linuxserver.io docker mods
prowlarr_env_docker_mods: ""
prowlarr_env_docker_mods_install_packages: ""
prowlarr_env_docker_mods_install_pip_packages: ""

# theme.park themes
# https://docs.theme-park.dev/themes/prowlarr/
prowlarr_env_docker_mods_tp_theme: ""
prowlarr_env_docker_mods_tp_community_theme: ""
prowlarr_env_docker_mods_tp_domain: ""
prowlarr_env_docker_mods_tp_addon: ""

# repliqate
prowlarr_repliqate_enabled: false
prowlarr_repliqate_engine: "restic"
prowlarr_repliqate_schedule: "@daily 3am"
prowlarr_repliqate_backup_id: "{{ prowlarr_container_name }}"
prowlarr_repliqate_retention: "30d"

# tinyauth
prowlarr_tinyauth_enabled: false

# watchtower
prowlarr_watchtower_enabled: false
