---
# ANE
ansible_nas_app_name: "ControlR"
controlr_enabled: false
controlr_available_externally: false
controlr_traefik_whitelist: "{{ lan }}"
controlr_data_directory: "{{ docker_home }}/controlr"

# network
controlr_hostname: "controlr"
controlr_port_http: "5120"

controlr_network_name: "controlr"
controlr_network_gateway: "172.29.0.1"
controlr_network_subnet: "172.29.0.0/16"

# docker
controlr_container_name: "controlr"
controlr_image_name: "translucency/controlr"
controlr_image_tag: "latest"

# specs
controlr_cpu_shares: 1024
controlr_memory: "1G"

# autoheal
controlr_autoheal: "false"

# dockflare
controlr_dockflare_tunnel: "false"
controlr_dockflare_access_group: ""

# tinyauth
controlr_tinyauth_enabled: false

# watchtower
controlr_watchtower_enable: "false"
