---
- name: Start {{ ansible_nas_app_name }}
  block:
    - name: Create {{ ansible_nas_app_name }} Directories
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
      with_items:
        - "{{ kapowarr_data_directory }}/config"
        - "{{ kapowarr_comics_directory }}"
        - "{{ kapowarr_downloads_directory }}"

    - name: Create {{ ansible_nas_app_name }} Container
      community.docker.docker_container:
        container_default_behavior: "compatibility"
        name: "{{ kapowarr_container_name }}"
        hostname: "{{ kapowarr_container_name }}"
        image: "{{ kapowarr_image_name }}:{{ kapowarr_image_tag }}"
        pull: true
        volumes:
          - "{{ kapowarr_comics_directory }}:/comics:rw"
          - "{{ kapowarr_downloads_directory }}:/downloads:rw"
          - "{{ kapowarr_data_directory }}/config:/app/db:rw"
        network_mode: bridge
        ports:
          - "{{ kapowarr_port_http }}:5656"
        env:
          TZ: "{{ ansible_nas_timezone }}"
        labels:
          autoheal: "{{ kapowarr_autoheal | string }}"
          com.centurylinklabs.watchtower.enable: "{{ kapowarr_watchtower_enabled| string }}"
          dockflare.enable: "{{ kapowarr_dockflare_enabled | string }}"
          dockflare.access.group: "{{ kapowarr_dockflare_access_group }}"
          dockflare.hostname: "{{ kapowarr_hostname }}.{{ ansible_nas_domain }}"
          dockflare.service: "http://{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}:{{ kapowarr_port_http }}"
          homepage.name: "{{ ansible_nas_app_name }}"
          homepage.group: "{{ kapowarr_homepage_group }}"
          homepage.icon: "{{ kapowarr_homepage_icon }}"
          homepage.href: "{{ kapowarr_homepage_href }}"
          homepage.siteMonitor: "http://{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}:{{ kapowarr_port_http }}"
          homepage.description: "{{ 'Kapowarr is a software to build and manage a comic book library, fitting in the *arr suite of software.' if homepage_show_description else omit }}"
          homepage.server: "my-docker"
          homepage.container: "{{ kapowarr_container_name }}"
          homepage.showStats: "{{ kapowarr_homepage_showstats | string }}"
          repliqate.enabled: "{{ kapowarr_repliqate_enabled | string }}"
          repliqate.engine: "{{ kapowarr_repliqate_engine }}"
          repliqate.schedule: "{{ kapowarr_repliqate_schedule }}"
          repliqate.backup_id: "{{ kapowarr_repliqate_backup_id }}"
          repliqate.retention: "{{ kapowarr_repliqate_retention }}"
          traefik.enable: "{{ kapowarr_available_externally | string }}"
          traefik.http.routers.kapowarr.rule: "Host(`{{ kapowarr_hostname }}.{{ ansible_nas_domain }}`)"
          traefik.http.routers.kapowarr.tls.certresolver: "letsencrypt"
          traefik.http.routers.kapowarr.tls.domains[0].main: "{{ ansible_nas_domain }}"
          traefik.http.routers.kapowarr.tls.domains[0].sans: "*.{{ ansible_nas_domain }}"
          traefik.http.routers.kapowarr.middlewares: "kapowarr@docker{{ ',tinyauth-auth@docker' if kapowarr_tinyauth_enabled | bool else '' }}"
          traefik.http.middlewares.kapowarr.IPAllowList.sourcerange: "{{ kapowarr_traefik_whitelist }}"
          traefik.http.services.kapowarr.loadbalancer.server.port: "5656"
          wud.tag.include: '^\d+\.\d+\.\d+.*$'
          wud.tag.transform.type: "semver"
          wud.link.template: "https://hub.docker.com/r/mrcas/kapowarr"
        cpu_shares: "{{ kapowarr_cpu_shares }}"
        memory: "{{ kapowarr_memory }}"
        memory_swap: "{{ kapowarr_memory_swap }}"
        restart_policy: unless-stopped

    - name: Access {{ ansible_nas_app_name }} at
      ansible.builtin.debug:
        msg: >-
              {{
                ['http://' + hostvars[inventory_hostname]['ansible_default_ipv4']['address'] + ':' + (kapowarr_port_http | string)] +
                (['https://' + kapowarr_hostname + '.' + ansible_nas_domain] if (kapowarr_available_externally is true or kapowarr_dockflare_enabled is true) else [])
              }}
  when: kapowarr_enabled is true

- name: Stop {{ ansible_nas_app_name }}
  block:
    - name: Stop {{ ansible_nas_app_name }} Container
      community.docker.docker_container:
        name: "{{ kapowarr_container_name }}"
        state: absent
  when: kapowarr_enabled is false

- name: Data Archive {{ ansible_nas_app_name }}
  include_role:
    name: ansible-nas-archive
  vars:
    target_data_dir: "{{ kapowarr_data_directory }}"
  when:
    - archive_app_data_enabled is true
    - kapowarr_enabled is false