---
# ANE
ansible_nas_app_name: "code-server"
codeserver_enabled: false
codeserver_available_externally: false
codeserver_traefik_whitelist: "{{ lan }}"
codeserver_data_directory: "{{ docker_home }}/code-server"

# network
codeserver_hostname: "codeserver"
codeserver_port_http: "3009"

# config
codeserver_password: "{{ ansible_nas_app_admin_password }}"

# docker
codeserver_container_name: "code-server"
codeserver_image_name: "codercom/code-server"
codeserver_image_tag: "latest"
codeserver_cpu_shares: "1024"
codeserver_memory: "1G"

# autoheal
codeserver_autoheal: "false"

# dockflare
codeserver_dockflare_tunnel: "false"
codeserver_dockflare_access_group: ""

# homepage
codeserver_homepage_group: "Apps"
codeserver_homepgae_icon: "code-server.png"
codeserver_homepage_href: "http://{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}:{{ codeserver_port_http }}"
codeserver_homepage_showstats: "false"

# repliqate
codeserver_repliqate_enabled: "false"
codeserver_repliqate_engine: "restic"
codeserver_repliqate_schedule: "@daily 3am"
codeserver_repliqate_backup_id: "codeserver"
codeserver_repliqate_retention: "30d"

# watchtower
codeserver_watchtower_enable: "false"