---
# ANE
ansible_nas_app_name: "code-server"
code_server_enabled: false
code_server_available_externally: false
code_server_traefik_whitelist: "{{ lan }}"
code_server_data_directory: "{{ docker_home }}/code-server"

# network
code_server_hostname: "codeserver"
code_server_port_http: "3009"

# config
code_server_password: "{{ ansible_nas_app_admin_password }}"

# docker
code_server_container_name: "code-server"
code_server_image_name: "codercom/code-server"
code_server_image_tag: "latest"

# specs
code_server_cpu_shares: 1024
code_server_memory: "1G"
code_server_memory_swap: -1

# autoheal
code_server_autoheal: "false"

# dockflare
code_server_dockflare_tunnel: "false"
code_server_dockflare_access_group: ""

# homepage
code_server_homepage_group: "Apps"
code_server_homepgae_icon: "code-server.png"
code_server_homepage_href: "http://{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}:{{ code_server_port_http }}"
code_server_homepage_showstats: "false"

# repliqate
code_server_repliqate_enabled: "false"
code_server_repliqate_engine: "restic"
code_server_repliqate_schedule: "@daily 3am"
code_server_repliqate_backup_id: "{{ code_server_container_name }}"
code_server_repliqate_retention: "30d"

# tinyauth
code_server_tinyauth_enabled: false

# watchtower
code_server_watchtower_enable: "false"
