---
# ANE
ansible_nas_app_name: "bitmagnet"
bitmagnet_enabled: false
bitmagnet_traefik_enabled: false
bitmagnet_traefik_whitelist: "{{ lan }}"

# directories
bitmagnet_data_directory: "{{ docker_home }}/bitmagnet"

# network
bitmagnet_hostname: "bitmagnet"
bitmagnet_port_http: "3333"
bitmagnet_port_http2: "3334"

# docker
bitmagnet_container_name: "bitmagnet"
bitmagnet_image_name: "ghcr.io/bitmagnet-io/bitmagnet"
bitmagnet_image_tag: "latest"
bitmagnet_db_container_name: "bitmagnet-db"
bitmagnet_db_image_name: "postgres"
bitmagnet_db_image_tag: "16-alpine"

# specs
bitmagnet_cpu_shares: 1024
bitmagnet_memory: "1G"
bitmagnet_memory_swap: -1
bitmagnet_db_cpu_shares: 1024
bitmagnet_db_memory: "1G"
bitmagnet_db_memory_swap: "{{ bitmagnet_db_memory }}"

# app
bitmagnet_tmdb_api_key: ""

# autoheal
bitmagnet_autoheal_enabled: false
bitmagnet_db_autoheal_enabled: false

# dockflare
bitmagnet_dockflare_enabled: false
bitmagnet_dockflare_access_group: ""

# homepage
bitmagnet_homepage_group: "Apps"
bitmagnet_homepage_icon: "https://avatars.githubusercontent.com/u/146768397"
bitmagnet_homepage_href: "http://{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}:{{ bitmagnet_port_http }}"
bitmagnet_homepage_showstats: false
bitmagnet_db_homepage_group: "DBs"
bitmagnet_db_homepage_icon: "postgres.png"
bitmagnet_db_homepage_href: "{{ bitmagnet_homepage_href }}"
bitmagnet_db_homepage_showstats: false

# repliqate
bitmagnet_repliqate_enabled: false
bitmagnet_repliqate_engine: "restic"
bitmagnet_repliqate_schedule: "@daily 3am"
bitmagnet_repliqate_backup_id: "{{ bitmagnet_container_name}}"
bitmagnet_repliqate_retention: "30d"
bitmagnet_db_repliqate_enabled: false
bitmagnet_db_repliqate_engine: "restic"
bitmagnet_db_repliqate_schedule: "@daily 3am"
bitmagnet_db_repliqate_backup_id: "{{ bitmagnet_db_container_name }}"
bitmagnet_db_repliqate_retention: "30d"

# tinyauth
bitmagnet_tinyauth_enabled: false

# watchtower
bitmagnet_watchtower_enabled: false
bitmagnet_db_watchtower_enabled: false
