---
- name: Start {{ ansible_nas_app_name }}
  block:
    - name: Create {{ ansible_nas_app_name }} Directories
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
      with_items:
        - "{{ couchdb_data_directory }}/config"
        - "{{ couchdb_data_directory }}/data"

    - name: Create {{ ansible_nas_app_name }} Container
      community.docker.docker_container:
        container_default_behavior: "compatibility"
        name: "{{ couchdb_container_name }}"
        hostname: "{{ couchdb_container_name }}"
        image: "{{ couchdb_image_name }}:{{ couchdb_image_version }}"
        pull: true
        env:
          COUCHDB_USER: "{{ couchdb_admin_user }}"
          COUCHDB_PASSWORD: "{{ couchdb_admin_password }}"
        ports:
          - "{{ couchdb_port_http }}:5984"
        volumes:
          - "{{ couchdb_data_directory }}/config:/opt/couchdb/etc/local.d"
          - "{{ couchdb_data_directory }}/data:/opt/couchdb/data"
        labels:
          autoheal: "{{ couchdb_autoheal | string }}"
          com.centurylinklabs.watchtower.enable: "{{ couchdb_watchtower_enabled | string }}"
          dockflare.enable: "{{ couchdb_dockflare_enabled | string }}"
          dockflare.access.group: "{{ couchdb_dockflare_access_group }}"
          dockflare.hostname: "{{ couchdb_hostname }}.{{ ansible_nas_domain }}"
          dockflare.service: "http://{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}:{{ couchdb_port_http }}"
          homepage.name: "{{ ansible_nas_app_name }}"
          homepage.group: "{{ couchdb_homepage_group }}"
          homepage.icon: "{{ couchdb_homepage_icon }}"
          homepage.href: "{{ couchdb_homepage_href }}"
          homepage.description: "{{ 'couchdb description' if homepage_show_description else omit }}"
          homepage.server: "my-docker"
          homepage.container: "{{ couchdb_container_name }}"
          homepage.showStats: "{{ couchdb_homepage_showstats | string }}"
          homepage.siteMonitor: "http://{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}:{{ couchdb_port_http }}"
          repliqate.enabled: "{{ couchdb_repliqate_enabled | string }}"
          repliqate.engine: "{{ couchdb_repliqate_engine }}"
          repliqate.schedule: "{{ couchdb_repliqate_schedule }}"
          repliqate.backup_id: "{{ couchdb_repliqate_backup_id }}"
          repliqate.retention: "{{ couchdb_repliqate_retention }}"
          traefik.enable: "{{ couchdb_available_externally | string }}"
          traefik.http.routers.couchdb.rule: "Host(`{{ couchdb_hostname }}.{{ ansible_nas_domain }}`)"
          traefik.http.routers.couchdb.tls.certresolver: "letsencrypt"
          traefik.http.routers.couchdb.tls.domains[0].main: "{{ ansible_nas_domain }}"
          traefik.http.routers.couchdb.tls.domains[0].sans: "*.{{ ansible_nas_domain }}"
          traefik.http.routers.couchdb.middlewares: "couchdb@docker{{ ',tinyauth-auth@docker' if couchdb_tinyauth_enabled | bool else '' }}"
          traefik.http.middlewares.couchdb.IPAllowList.sourcerange: "{{ couchdb_traefik_whitelist }}"
          traefik.http.services.couchdb.loadbalancer.server.port: "5984"
          wud.tag.include: '^\d+\.\d+\.\d+.*$'
          wud.tag.transform.type: "semver"
          wud.link.template: "https://hub.docker.com/_/couchdb"
        cpu_shares: "{{ couchdb_cpu_shares }}"
        memory: "{{ couchdb_memory }}"
        memory_swap: "{{ couchdb_memory_swap }}"
        restart_policy: unless-stopped

    - name: Access {{ ansible_nas_app_name }} at
      ansible.builtin.debug:
        msg: >-
              {{
                ['http://' + hostvars[inventory_hostname]['ansible_default_ipv4']['address'] + ':' + (couchdb_port_http | string)] +
                (['https://' + couchdb_hostname + '.' + ansible_nas_domain] if (couchdb_available_externally is true or couchdb_dockflare_enabled is true) else [])
              }}
  when: couchdb_enabled is true

- name: Stop {{ ansible_nas_app_name }}
  block:
    - name: Stop {{ ansible_nas_app_name }} Container
      community.docker.docker_container:
        name: "{{ couchdb_container_name }}"
        state: absent
  when: couchdb_enabled is false

- name: Data Archive {{ ansible_nas_app_name }}
  include_role:
    name: ansible-nas-archive
  vars:
    target_data_dir: "{{ couchdb_data_directory }}"
  when:
    - archive_app_data_enabled is true
    - couchdb_enabled is false