---
- name: Start {{ ansible_nas_app_name }}
  block:
    - name: Create {{ ansible_nas_app_name }} Directories
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
      with_items:
        - "{{ couchdb_data_directory }}/config"
        - "{{ couchdb_data_directory }}/data"

    - name: Create {{ ansible_nas_app_name }} Container
      community.docker.docker_container:
        container_default_behavior: "compatibility"
        name: "{{ couchdb_container_name }}"
        hostname: "{{ couchdb_container_name }}"
        image: "{{ couchdb_image_name }}:{{ couchdb_image_version }}"
        pull: true
        env:
          COUCHDB_USER: "{{ couchdb_admin_user }}"
          COUCHDB_PASSWORD: "{{ couchdb_admin_password }}"
        ports:
          - "{{ couchdb_port }}:5984"
        volumes:
          - "{{ couchdb_data_directory }}/config:/opt/couchdb/etc/local.d"
          - "{{ couchdb_data_directory }}/data:/opt/couchdb/data"
        labels:
          autoheal: "{{ couchdb_autoheal }}"
          com.centurylinklabs.watchtower.monitor-only: "{{ couchdb_watchtower_monitor_only }}"
          homepage.name: "{{ ansible_nas_app_name }}"
          homepage.group: "{{ couchdb_homepage_group }}"
          homepage.icon: "{{ couchdb_homepage_icon }}"
          homepage.href: "{{ couchdb_homepage_href }}"
          homepage.description: "{{ 'couchdb description' if homepage_show_description else omit }}"
          homepage.server: "my-docker"
          homepage.container: "{{ couchdb_container_name }}"
          homepage.showStats: "{{ couchdb_homepage_showStats }}"
          homepage.siteMonitor: "http://{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}:{{ couchdb_port }}"
          traefik.enable: "{{ couchdb_available_externally | string }}"
          traefik.http.routers.couchdb.rule: "Host(`{{ couchdb_hostname }}.{{ ansible_nas_domain }}`)"
          traefik.http.routers.couchdb.tls.certresolver: "letsencrypt"
          traefik.http.routers.couchdb.tls.domains[0].main: "{{ ansible_nas_domain }}"
          traefik.http.routers.couchdb.tls.domains[0].sans: "*.{{ ansible_nas_domain }}"
          traefik.http.routers.frontend.middlewares: "{{ couchdb_hostname }}"
          traefik.http.routers.couchdb.middlewares: "{{ couchdb_hostname }}@docker"
          traefik.http.middlewares.couchdb.IPAllowList.sourcerange: "{{ couchdb_traefik_whitelist }}"
          traefik.http.services.couchdb.loadbalancer.server.port: "5984"
          wud.tag.include: '^\d+\.\d+\.\d+$$'
          wud.link.template: "https://github.com/apache/couchdb/releases/tag/$${major}.$${minor}.$${patch}"
        cpu_shares: "{{ couchdb_cpu_shares }}"
        restart_policy: unless-stopped
        memory: "{{ couchdb_memory }}"
  when: couchdb_enabled is true

- name: Stop {{ ansible_nas_app_name }}
  block:
    - name: Stop {{ ansible_nas_app_name }} Container
      community.docker.docker_container:
        name: "{{ couchdb_container_name }}"
        state: absent
  when: couchdb_enabled is false

- name: Data Archive {{ ansible_nas_app_name }}
  block:
    - name: Check for {{ ansible_nas_app_name }} Data Directory
      stat:
        path: "{{ couchdb_data_directory }}"
      register: dir_stat

    - name: Archive {{ ansible_nas_app_name }} Data Directory
      ansible.builtin.archive:
        path: "{{ couchdb_data_directory }}"
        dest: "{{ docker_home }}/{{ ansible_nas_app_name | lower }}.zip"
        force_archive: true
        format: zip
        owner: ansible-nas
        group: ansible-nas
        mode: u=rw,g=rw
        remove: true
      when: dir_stat.stat.exists
  when: couchdb_enabled is false and archive_app_data_enabled is true
