---
# ANE
ansible_nas_app_name: "osTicket"
osticket_enabled: false
osticket_available_externally: false
osticket_traefik_whitelist: "{{ lan }}"
osticket_data_directory: "{{ docker_home }}/osticket"

# network
osticket_hostname: "osticket"
osticket_port_http: "9005"

# docker
osticket_container_name: "osticket"
osticket_image_name: "phib256/osticket"
osticket_image_tag: "v1.18.2"
osticket_db_container_name: "osticket-db"
osticket_db_image_name: "lscr.io/linuxserver/mariadb"
osticket_db_image_tag: "latest"

# specs
osticket_cpu_shares: 1024
osticket_memory: "1G"
osticket_db_cpu_shares: 1024
osticket_db_memory: "1G"

# app
osticket_env_admin_username: "admin"
osticket_env_admin_password: "{{ ansible_nas_app_admin_password }}"
osticket_env_mysql_root_password: "topsecret"
osticket_env_mysql_user: "osticket"
osticket_env_mysql_password: "topsecret"
osticket_env_mysql_database: "osticket_db"

# autoheal
osticket_autoheal: "false"
osticket_db_autoheal: "false"

# dockflare
osticket_dockflare_tunnel: "false"
osticket_dockflare_access_group: ""

# homepage
osticket_homepage_group: "Apps"
osticket_homepage_icon: "osticket.png"
osticket_homepage_href: "http://{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}:{{ osticket_port_http }}"
osticket_homepage_showstats: "false"
osticket_db_homepage_group: "DBs"
osticket_db_homepage_icon: "mariadb.png"
osticket_db_homepage_showstats: "false"

# linuxserver.io docker mods
osticket_db_env_docker_mods: ""
osticket_db_env_docker_mods_install_packages: ""
osticket_db_env_docker_mods_install_pip_packages: ""

# repliqate
osticket_repliqate_enabled: "false"
osticket_repliqate_engine: "restic"
osticket_repliqate_schedule: "@daily 3am"
osticket_repliqate_backup_id: "{{ osticket_container_name }}"
osticket_repliqate_retention: "30d"
osticket_db_repliqate_enabled: "false"
osticket_db_repliqate_engine: "restic"
osticket_db_repliqate_schedule: "@daily 3am"
osticket_db_repliqate_backup_id: "{{ osticket_container_name }}"
osticket_db_repliqate_retention: "30d"

# tinyauth
osticket_tinyauth_enabled: false

# watchtower
osticket_watchtower_enable: "false"
osticket_db_watchtower_enable: "false"