---
# ANE
watchstate_proper_name: "WatchState"
watchstate_enabled: false
watchstate_traefik_enabled: false
watchstate_traefik_whitelist: "{{ lan }}"

# directories
watchstate_data_directory: "{{ docker_home }}/watchstate"

# docker
watchstate_container_name: "watchstate"
watchstate_image_name: "ghcr.io/arabcoders/watchstate"
watchstate_image_tag: "latest"

# uid / gid
watchstate_user_id: "1000"
watchstate_group_id: "1000"

# network
watchstate_port_http: "8992"
watchstate_hostname: "watchstate"

# specs
watchstate_cpu_shares: 1024
watchstate_memory: "1G"
watchstate_memory_swap: -1

# autoheal
watchstate_autoheal_enabled: false

# dockflare
watchstate_dockflare_enabled: false
watchstate_dockflare_access_group: ""

# homepage
watchstate_homepage_group: "Apps"
watchstate_homepage_icon: "sh-watchstate.png"
watchstate_homepage_href: "http://{{ hostvars[inventory_hostname]['ansible_facts']['default_ipv4']['address'] }}:{{ watchstate_port_http }}"
watchstate_homepage_showstats: false

# repliqate
watchstate_repliqate_enabled: false
watchstate_repliqate_engine: "restic"
watchstate_repliqate_schedule: "@daily 3am"
watchstate_repliqate_backup_id: "{{ watchstate_container_name }}"
watchstate_repliqate_retention: "30d"

# tinyauth
watchstate_tinyauth_enabled: false

# watchtower
watchstate_watchtower_enabled: false
