---
# ANE
ansible_nas_app_name: "cloudflared"
cloudflared_enabled: false

# docker
cloudflared_container_name: "cloudflared"
cloudflared_image_name: "cloudflare/cloudflared"
cloudflared_image_tag: "latest"

# specs
cloudflared_cpu_shares: 1024
cloudflared_memory: "256M"
cloudflared_memory_swap: -1

# app
cloudflared_token: "put_your_cloudflared_token_here"

# autoheal
cloudflared_autoheal: false

# homepage
cloudflared_homepage_group: "Apps"
cloudflared_homepage_icon: "cloudflare.png"
cloudflared_homepage_showstats: false
cloudflared_homepage_widget_accountid: "" # https://one.dash.cloudflare.com/<accountid>/home/quick-start
cloudflared_homepage_widget_tunnelid: "" # found in tunnels dashboard under the tunnel name
cloudflared_homepage_widget_key: "" # # api token with `Account.Cloudflare Tunnel:Read` https://dash.cloudflare.com/profile/api-tokens

# watchtower
cloudflared_watchtower_enabled: false