---
# ANE
ansible_nas_app_name: "Ombi"
ombi_enabled: false
ombi_available_externally: false
ombi_traefik_whitelist: "{{ lan }}"

# directories
ombi_data_directory: "{{ docker_home }}/ombi"

# network
ombi_port: "3579"
ombi_hostname: "ombi"

# docker
ombi_container_name: "ombi"
ombi_image_name: "lscr.io/linuxserver/ombi"
ombi_image_version: "latest"
ombi_cpu_shares: 1024

ombi_user_id: "0"
ombi_group_id: "0"

# specs
ombi_memory: 1g

# autoheal
ombi_autoheal: "false"

# dockflare
ombi_dockflare_tunnel: "false"
ombi_dockflare_access_group: ""

# homepage
ombi_homepage_group: "Apps"
ombi_homepage_icon: "ombi.png"
ombi_homepage_href: "http://{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}:{{ ombi_port }}"
ombi_homepage_showstats: "false"

# linuxserver.io docker mods
ombi_env_docker_mods: ""

# theme.park themes
# https://docs.theme-park.dev/themes/ombi/
ombi_env_docker_mods_tp_theme: ""
ombi_env_docker_mods_tp_community_theme: ""
ombi_env_docker_mods_tp_domain: ""
ombi_env_docker_mods_tp_addon: ""

# watchtower
ombi_watchtower_enable: "false"