---
# ANE
ansible_nas_app_name: "Ubooquity"
ubooquity_enabled: false
ubooquity_available_externally: false
ubooquity_traefik_whitelist: "{{ lan }}"

# uid / gid
ubooquity_user_id: "0"
ubooquity_group_id: "0"

# Directories
ubooquity_data_directory: "{{ docker_home }}/ubooquity"

# Networking
ubooquity_hostname: "ubooquity"
ubooquity_port_http: "2202"
ubooquity_port_admin: "2203"

# Container
ubooquity_container_name: "ubooquity"
ubooquity_image_name: "lscr.io/linuxserver/ubooquity"
ubooquity_image_version: "latest"

# specs
ubooquity_cpu_shares: 1024
ubooquity_memory: "1G"

# autoheal
ubooquity_autoheal: "false"

# dockflare
ubooquity_dockflare_tunnel: "false"
ubooquity_dockflare_access_group: ""

# homepage
ubooquity_homepage_group: "Media Servers"
ubooquity_homepage_icon: "ubooquity.png"
ubooquity_homepage_href: "http://{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}:{{ ubooquity_port_http }}"
ubooquity_homepage_showstats: "false"

# linuxserver.io docker mods
ubooquity_env_docker_mods: ""
ubooquity_env_docker_mods_install_packages: ""
ubooquity_env_docker_mods_install_pip_packages: ""

# repliqate
ubooquity_repliqate_enabled: "false"
ubooquity_repliqate_engine: "restic"
ubooquity_repliqate_schedule: "@daily 3am"
ubooquity_repliqate_backup_id: "{{ ubooquity_container_name }}"
ubooquity_repliqate_retention: "30d"

# watchtower
ubooquity_watchtower_enable: "false"