---
- name: Start {{ ansible_nas_app_name }}
  block:
    - name: Create {{ ansible_nas_app_name }} Directories
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
      with_items:
        - "{{ docker_android_data_directory }}"
        - "{{ docker_android_data_directory }}/data"

    - name: Set {{ ansible_nas_app_name }} FQDN var overrides
      ansible.builtin.set_fact:
        docker_android_homepage_href: "https://{{ docker_android_hostname }}.{{ ansible_nas_domain }}"
      when: docker_android_traefik_enabled | bool or docker_android_dockflare_enabled | bool

    - name: Create {{ ansible_nas_app_name }} Container
      community.docker.docker_container:
        container_default_behavior: "compatibility"
        name: "{{ docker_android_container_name }}"
        hostname: "{{ docker_android_container_name }}"
        image: "{{ docker_android_image_name }}:{{ docker_android_image_tag }}"
        pull: true
#        volumes:
#          - "{{ docker_android_data_directory }}/data:/home/androidusr"
        ports:
          - "{{ docker_android_port_http }}:6080"
        env:
          EMULATOR_DEVICE: "{{ docker_android_env_emulator_device }}"
          WEB_VNC: "true"
          TZ: "{{ ansible_nas_timezone }}"
        devices:
          - "/dev/kvm"
        labels:
          autoheal: "{{ docker_android_autoheal_enabled | ternary('true', 'false') }}"
          com.centurylinklabs.watchtower.enable: "{{ docker_android_watchtower_enabled | ternary('true', 'false') }}"
          dockflare.enable: "{{ docker_android_dockflare_enabled | ternary('true', 'false') }}"
          dockflare.access.group: "{{ docker_android_dockflare_access_group }}"
          dockflare.hostname: "{{ docker_android_hostname }}.{{ ansible_nas_domain }}"
          dockflare.service: "http://{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}:{{ docker_android_port_http }}"
          homepage.name: "{{ ansible_nas_app_name }}"
          homepage.group: "{{ docker_android_homepage_group }}"
          homepage.icon: "{{ docker_android_homepage_icon }}"
          homepage.href: "{{ docker_android_homepage_href }}"
          homepage.description: "{{ 'Android in docker solution with noVNC supported and video recording' if homepage_show_description else omit }}"
          homepage.server: "my-docker"
          homepage.container: "{{ docker_android_container_name }}"
          homepage.showStats: "{{ docker_android_homepage_showstats | ternary('true', 'false') }}"
          homepage.siteMonitor: "http://{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}:{{ docker_android_port_http }}"
          repliqate.enabled: "{{ docker_android_repliqate_enabled | ternary('true', 'false') }}"
          repliqate.engine: "{{ docker_android_repliqate_engine }}"
          repliqate.schedule: "{{ docker_android_repliqate_schedule }}"
          repliqate.backup_id: "{{ docker_android_repliqate_backup_id }}"
          repliqate.retention: "{{ docker_android_repliqate_retention }}"
          traefik.enable: "{{ docker_android_traefik_enabled | ternary('true', 'false') }}"
          traefik.http.routers.dockerandroid.rule: "Host(`{{ docker_android_hostname }}.{{ ansible_nas_domain }}`)"
          traefik.http.routers.docke_android.tls.certresolver: "letsencrypt"
          traefik.http.routers.dockerandroid.tls.domains[0].main: "{{ ansible_nas_domain }}"
          traefik.http.routers.dockerandroid.tls.domains[0].sans: "*.{{ ansible_nas_domain }}"
          traefik.http.routers.dockerandroid.middlewares: "dockerandroid@docker{{ ',tinyauth-auth@docker' if docker_android_tinyauth_enabled | bool else '' }}"
          traefik.http.middlewares.dockerandroid.IPAllowList.sourcerange: "{{ docker_android_traefik_whitelist }}"
          traefik.http.services.dockerandroid.loadbalancer.server.port: "6080"
          wud.tag.include: '^\d+\.\d+.*$'
          wud.tag.transform.type: "semver"
          wud.link.template: "https://hub.docker.com/r/budtmo/docker-android"
        cpu_shares: "{{ docker_android_cpu_shares }}"
        memory: "{{ docker_android_memory }}"
        memory_swap: "{{ docker_android_memory_swap }}"
        restart_policy: unless-stopped

    - name: Access {{ ansible_nas_app_name }} at
      ansible.builtin.debug:
        msg: >-
              {{
                ['http://' + hostvars[inventory_hostname]['ansible_default_ipv4']['address'] + ':' + (docker_android_port_http | string)] +
                (['https://' + docker_android_hostname + '.' + ansible_nas_domain] if (docker_android_traefik_enabled is true or docker_android_dockflare_enabled is true) else [])
              }}
  when: docker_android_enabled is true

- name: Stop {{ ansible_nas_app_name }}
  block:
    - name: Stop {{ ansible_nas_app_name }} Container
      community.docker.docker_container:
        name: "{{ docker_android_container_name }}"
        state: absent
  when: docker_android_enabled is false

- name: Data Archive {{ ansible_nas_app_name }}
  include_role:
    name: ansible-nas-archive
  vars:
    target_data_dir: "{{ docker_android_data_directory }}"
  when:
    - archive_app_data_enabled is true
    - docker_android_enabled is false