---
# ANE
ansible_nas_app_name: "Portainer Agent"
portainer_agent_enabled: false

# network
portainer_agent_port: "9002"

# docker
portainer_agent_container_name: "portainer-agent"
portainer_agent_image_name: "portainer/agent"
portainer_agent_image_tag: "lts"

# specs
portainer_agent_cpu_shares: 1024
portainer_agent_memory: "256M"
portainer_agent_memory_swap: -1

# autoheal
portainer_agent_autoheal: false

# homepage
portainer_agent_homepage_group: "Misc"
portainer_agent_homepage_icon: "portainer.png"
portainer_agent_homepage_showstats: false

# watchtower
portainer_agent_watchtower_enabled: false