---
ansible_nas_app_name: "Shoutcast Server"

#
shoutcast_enabled: false
shoutcast_available_externally: false
shoutcast_traefik_whitelist: "{{ lan }}"
shoutcast_data_directory: "{{ docker_home }}/shoutcast"

# network
shoutcast_hostname: "shoutcast"
shoutcast_port_http: "8002"

# app
shoutcast_media_directory: "{{ music_root }}"

# docker
shoutcast_container_name: "shoutcast"
shoutcast_image_name: "luzifer/shoutcast"
shoutcast_image_tag: "latest"
shoutcast_cpu_shares: "1024"
shoutcast_memory: "1g"

# autoheal
shoutcast_autoheal: "false"

# homepage
shoutcast_homepage_group: "Apps"
shoutcast_homepage_icon: "shoutcast.png"
shoutcast_homepage_href: "http://{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}:{{ shoutcast_port_http }}"
shoutcast_homepage_showStats: "false"

# watchtower
shoutcast_watchtower_monitor_only: "true"