---
# ANE
ansible_nas_app_name: "LoggiFly"
loggifly_enabled: false
loggifly_available_externally: false
loggifly_traefik_whitelist: "{{ lan }}"

# directories
loggifly_data_directory: "{{ docker_home }}/loggifly"

# docker
loggifly_container_name: "loggifly"
loggifly_image_name: "ghcr.io/clemcer/loggifly"
loggifly_image_tag: "latest"
loggifly_cpu_shares: "1024"

# network
loggifly_hostname: "loggifly"

# specs
loggifly_memory: 1g

# autoheal
loggifly_autoheal: "false"

# homepage
loggifly_homepage_group: "Misc"
loggifly_homepage_icon: "loggifly.png"
loggifly_homepage_showstats: "false"

# repliqate
loggifly_repliqate_enabled: "false"
loggifly_repliqate_engine: "restic"
loggifly_repliqate_schedule: "@daily 3am"
loggifly_repliqate_backup_id: "{{ loggifly_container_name }}"
loggifly_repliqate_retention: "30d"

# watchtower
loggifly_watchtower_enable: "false"
