---
- name: Start {{ ansible_nas_app_name }}
  block:
    - name: Create {{ ansible_nas_app_name }} Directories
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        # mode: 0755
      with_items:
        - "{{ sickchill_data_directory }}"
        - "{{ sickchill_data_directory }}/config"

    - name: Create {{ ansible_nas_app_name }} Container
      community.docker.docker_container:
        container_default_behavior: "compatibility"
        name: "{{ sickchill_container_name }}"
        hostname: "{{ sickchill_container_name }}"
        image: "{{ sickchill_image_name }}:{{ sickchill_image_version }}"
        pull: true
        volumes:
          - "{{ sickchill_data_directory }}/config:/config:rw"
          - "{{ sickchill_downloads_directory }}:/downloads:rw"
          - "{{ sickchill_tv_directory }}:/tv:rw"
        ports:
          - "{{ sickchill_port_http }}:8081"
        env:
          DOCKER_MODS: "{{ sickchill_env_docker_mods }}"
          INSTALL_PACKAGES: "{{ sickchill_env_docker_mods_install_packages }}"
          INSTALL_PIP_PACKAGES: "{{ sickchill_env_docker_mods_install_pip_packages}}"
          PUID: "{{ sickchill_user_id }}"
          PGID: "{{ sickchill_group_id }}"
          TZ: "{{ ansible_nas_timezone }}"
        labels:
          autoheal: "{{ sickchill_autoheal }}"
          com.centurylinklabs.watchtower.enable: "{{ sickchill_watchtower_enable }}"
          dockflare.enable: "{{ sickchill_dockflare_tunnel }}"
          dockflare.access.group: "{{ sickchill_dockflare_access_group }}"
          dockflare.hostname: "{{ sickchill_hostname }}.{{ ansible_nas_domain }}"
          dockflare.service: "http://{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}:{{ sickchill_port_http }}"
          homepage.name: "{{ ansible_nas_app_name }}"
          homepage.group: "{{ sickchill_homepage_group }}"
          homepage.icon: "{{ sickchill_homepage_icon }}"
          homepage.href: "{{ sickchill_homepage_href }}"
          homepage.description: "{{ 'sickchill description' if homepage_show_description else omit }}"
          homepage.server: "my-docker"
          homepage.container: "{{ sickchill_container_name }}"
          homepage.showStats: "{{ sickchill_homepage_showstats }}"
          homepage.siteMonitor: "http://{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}:{{ sickchill_port_http }}"
          traefik.enable: "{{ sickchill_available_externally | string }}"
          traefik.http.routers.sickchill.rule: "Host(`{{ sickchill_hostname }}.{{ ansible_nas_domain }}`)"
          traefik.http.routers.sickchill.tls.certresolver: "letsencrypt"
          traefik.http.routers.sickchill.tls.domains[0].main: "{{ ansible_nas_domain }}"
          traefik.http.routers.sickchill.tls.domains[0].sans: "*.{{ ansible_nas_domain }}"
          traefik.http.routers.frontend.middlewares: "{{ sickchill_hostname }}"
          traefik.http.routers.sickchill.middlewares: "{{ sickchill_hostname }}@docker"
          traefik.http.middlewares.sickchill.IPAllowList.sourcerange: "{{ sickchill_traefik_whitelist }}"
          traefik.http.services.sickchill.loadbalancer.server.port: "8081"
          wud.tag.include: '^\d+\.\d+\.\d+.*$'
          wud.tag.transform.type: "semver"
          wud.link.template: "https://lscr.io/linuxserver/sickchill"
        cpu_shares: "{{ sickchill_cpu_shares }}"
        memory: "{{ sickchill_memory }}"
        restart_policy: unless-stopped

    - name: Access {{ ansible_nas_app_name }} at
      ansible.builtin.debug:
        msg: >-
              {{
                ['http://' + hostvars[inventory_hostname]['ansible_default_ipv4']['address'] + ':' + (sickchill_port_http | string)] +
                (['https://' + sickchill_hostname + '.' + ansible_nas_domain] if (sickchill_available_externally is true or sickchill_dockflare_tunnel is true) else [])
              }}
  when: sickchill_enabled is true

- name: Stop {{ ansible_nas_app_name }}
  block:
    - name: Stop {{ ansible_nas_app_name }} Container
      community.docker.docker_container:
        name: "{{ sickchill_container_name }}"
        state: absent
  when: sickchill_enabled is false

- name: Data Archive {{ ansible_nas_app_name }}
  block:
    - name: Check for {{ ansible_nas_app_name }} Data Directory
      stat:
        path: "{{ sickchill_data_directory }}"
      register: dir_stat

    - name: Archive {{ ansible_nas_app_name }} Data Directory
      ansible.builtin.archive:
        path: "{{ sickchill_data_directory }}"
        dest: "{{ docker_home }}/{{ ansible_nas_app_name | lower }}.zip"
        force_archive: true
        format: zip
        owner: ansible-nas
        group: ansible-nas
        mode: u=rw,g=rw
        remove: true
      when: dir_stat.stat.exists
  when: sickchill_enabled is false and archive_app_data_enabled is true
