---
- name: Start {{ cloudcmd_proper_name }}
  block:
    - name: Create {{ cloudcmd_proper_name }} Directories
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
      with_items:
        - "{{ cloudcmd_data_directory }}"
        - "{{ cloudcmd_data_directory }}/config"

    - name: Set {{ cloudcmd_proper_name }} FQDN var overrides
      ansible.builtin.set_fact:
        cloudcmd_homepage_href: "https://{{ cloudcmd_hostname }}.{{ ansible_nas_domain }}"
      when: cloudcmd_traefik_enabled | bool or cloudcmd_dockflare_enabled | bool

    - name: Create {{ cloudcmd_proper_name }} Container
      community.docker.docker_container:
        container_default_behavior: "compatibility"
        name: "{{ cloudcmd_container_name }}"
        hostname: "{{ cloudcmd_container_name }}"
        image: "{{ cloudcmd_image_name }}:{{ cloudcmd_image_tag }}"
        pull: true
        volumes:
          - "{{ cloudcmd_data_directory }}/config:/config:rw"
          - "{{ cloudcmd_browse_directory }}:/mnt/fs"
        ports:
          - "{{ cloudcmd_port_http }}:8000"
        env:
          TZ: "{{ ansible_nas_timezone }}"
          PUID: "{{ cloudcmd_user_id }}"
          PGID: "{{ cloudcmd_group_id }}"
        labels:
          autoheal: "{{ cloudcmd_autoheal_enabled | ternary('true', 'false') }}"
          com.centurylinklabs.watchtower.enable: "{{ cloudcmd_watchtower_enabled | ternary('true', 'false') }}"
          dockflare.enable: "{{ cloudcmd_dockflare_enabled | ternary('true', 'false') }}"
          dockflare.access.group: "{{ cloudcmd_dockflare_access_group }}"
          dockflare.hostname: "{{ cloudcmd_hostname }}.{{ ansible_nas_domain }}"
          dockflare.service: "http://{{ hostvars[inventory_hostname]['ansible_facts']['default_ipv4']['address'] }}:{{ cloudcmd_port_http }}"
          homepage.name: "{{ cloudcmd_proper_name }}"
          homepage.group: "{{ cloudcmd_homepage_group }}"
          homepage.icon: "{{ cloudcmd_homepage_icon }}"
          homepage.href: "{{ cloudcmd_homepage_href }}"
          homepage.description: "{{ 'cloudcmd description' if homepage_show_description else omit }}"
          homepage.server: "my-docker"
          homepage.container: "{{ cloudcmd_container_name }}"
          homepage.showStats: "{{ cloudcmd_homepage_showstats | ternary('true', 'false') }}"
          homepage.siteMonitor: "http://{{ hostvars[inventory_hostname]['ansible_facts']['default_ipv4']['address'] }}:{{ cloudcmd_port_http }}"
          repliqate.enabled: "{{ cloudcmd_repliqate_enabled | ternary('true', 'false') }}"
          repliqate.engine: "{{ cloudcmd_repliqate_engine }}"
          repliqate.schedule: "{{ cloudcmd_repliqate_schedule }}"
          repliqate.backup_id: "{{ cloudcmd_repliqate_backup_id }}"
          repliqate.retention: "{{ cloudcmd_repliqate_retention }}"
          traefik.enable: "{{ cloudcmd_traefik_enabled | ternary('true', 'false') }}"
          traefik.http.routers.cloudcmd.rule: "Host(`{{ cloudcmd_hostname }}.{{ ansible_nas_domain }}`)"
          traefik.http.routers.cloudcmd.tls.certresolver: "letsencrypt"
          traefik.http.routers.cloudcmd.tls.domains[0].main: "{{ ansible_nas_domain }}"
          traefik.http.routers.cloudcmd.tls.domains[0].sans: "*.{{ ansible_nas_domain }}"
          traefik.http.routers.cloudcmd.middlewares: "cloudcmd@docker{{ ',tinyauth-auth@docker' if cloudcmd_tinyauth_enabled | bool else '' }}"
          traefik.http.middlewares.cloudcmd.IPAllowList.sourcerange: "{{ cloudcmd_traefik_whitelist }}"
          traefik.http.services.cloudcmd.loadbalancer.server.port: "8000"
          wud.tag.include: "^\\d+\\.\\d+\\.\\d+$"
          wud.tag.transform.type: "semver"
          wud.link.template: "https://github.com/coderaiser/cloudcmd/pkgs/container/cloudcmd"
        cpu_shares: "{{ cloudcmd_cpu_shares }}"
        memory: "{{ cloudcmd_memory }}"
        memory_swap: "{{ cloudcmd_memory_swap }}"
        restart_policy: unless-stopped

    - name: Access {{ cloudcmd_proper_name }} at
      ansible.builtin.debug:
        msg: >-
              {{
                ['http://' + hostvars[inventory_hostname]['ansible_facts']['default_ipv4']['address'] + ':' + (cloudcmd_port_http | string)] +
                (['https://' + cloudcmd_hostname + '.' + ansible_nas_domain] if (cloudcmd_traefik_enabled is true or cloudcmd_dockflare_enabled is true) else [])
              }}
  when: cloudcmd_enabled is true

- name: Stop {{ cloudcmd_proper_name }}
  block:
    - name: Stop {{ cloudcmd_proper_name }} Container
      community.docker.docker_container:
        name: "{{ cloudcmd_container_name }}"
        state: absent
  when: cloudcmd_enabled is false

- name: Data Archive {{ cloudcmd_proper_name }}
  include_role:
    name: ansible-nas-archive
  vars:
    target_data_dir: "{{ cloudcmd_data_directory }}"
  when:
    - archive_app_data_enabled is true
    - cloudcmd_enabled is false