---
- name: Start {{ ansible_nas_app_name }}
  block:
    - name: Create {{ ansible_nas_app_name }} Directories
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
      with_items:
        - "{{ cloudcmd_data_directory }}"
        - "{{ cloudcmd_data_directory }}/config"

    - name: Create {{ ansible_nas_app_name }} Container
      community.docker.docker_container:
        container_default_behavior: "compatibility"
        name: "{{ cloudcmd_container_name }}"
        hostname: "{{ cloudcmd_container_name }}"
        image: "{{ cloudcmd_image_name }}:{{ cloudcmd_image_tag }}"
        pull: true
        volumes:
          - "{{ cloudcmd_data_directory }}/config:/config:rw"
          - "{{ cloudcmd_browse_directory }}:/mnt/fs"
        ports:
          - "{{ cloudcmd_port }}:8000"
        env:
          TZ: "{{ ansible_nas_timezone }}"
          PUID: "{{ cloudcmd_user_id }}"
          PGID: "{{ cloudcmd_group_id }}"
        labels:
          autoheal: "{{ cloudcmd_autoheal }}"
          com.centurylinklabs.watchtower.enable: "{{ cloudcmd_watchtower_enable }}"
          dockflare.enable: "{{ cloudcmd_dockflare_tunnel }}"
          dockflare.access.group: "{{ cloudcmd_dockflare_access_group }}"
          dockflare.hostname: "{{ cloudcmd_hostname }}.{{ ansible_nas_domain }}"
          dockflare.service: "http://{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}:{{ cloudcmd_port }}"
          homepage.name: "{{ ansible_nas_app_name }}"
          homepage.group: "{{ cloudcmd_homepage_group }}"
          homepage.icon: "{{ cloudcmd_homepage_icon }}"
          homepage.href: "{{ cloudcmd_homepage_href }}"
          homepage.description: "{{ 'cloudcmd description' if homepage_show_description else omit }}"
          homepage.server: "my-docker"
          homepage.container: "{{ cloudcmd_container_name }}"
          homepage.showStats: "{{ cloudcmd_homepage_showstats }}"
          homepage.siteMonitor: "http://{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}:{{ cloudcmd_port }}"
          traefik.enable: "{{ cloudcmd_available_externally | string }}"
          traefik.http.routers.cloudcmd.rule: "Host(`{{ cloudcmd_hostname }}.{{ ansible_nas_domain }}`)"
          traefik.http.routers.cloudcmd.tls.certresolver: "letsencrypt"
          traefik.http.routers.cloudcmd.tls.domains[0].main: "{{ ansible_nas_domain }}"
          traefik.http.routers.cloudcmd.tls.domains[0].sans: "*.{{ ansible_nas_domain }}"
          traefik.http.routers.frontend.middlewares: "{{ cloudcmd_hostname }}"
          traefik.http.routers.cloudcmd.middlewares: "{{ cloudcmd_hostname }}@docker"
          traefik.http.middlewares.cloudcmd.IPAllowList.sourcerange: "{{ cloudcmd_traefik_whitelist }}"
          traefik.http.services.cloudcmd.loadbalancer.server.port: "8000"
          wud.tag.include: '^\d+\.\d+\.\d+.*$'
          wud.tag.transform.type: "semver"
          wud.link.template: "https://hub.docker.com/r/coderaiser/cloudcmd"
        cpu_shares: "{{ cloudcmd_cpu_shares }}"
        memory: "{{ cloudcmd_memory }}"
        restart_policy: unless-stopped
  when: cloudcmd_enabled is true

- name: Stop {{ ansible_nas_app_name }}
  block:
    - name: Stop {{ ansible_nas_app_name }} Container
      community.docker.docker_container:
        name: "{{ cloudcmd_container_name }}"
        state: absent
  when: cloudcmd_enabled is false

- name: Data Archive {{ ansible_nas_app_name }}
  block:
    - name: Check for {{ ansible_nas_app_name }} Data Directory
      stat:
        path: "{{ cloudcmd_data_directory }}"
      register: dir_stat

    - name: Archive {{ ansible_nas_app_name }} Data Directory
      ansible.builtin.archive:
        path: "{{ cloudcmd_data_directory }}"
        dest: "{{ docker_home }}/{{ ansible_nas_app_name | lower }}.zip"
        force_archive: true
        format: zip
        owner: ansible-nas
        group: ansible-nas
        mode: u=rw,g=rw
        remove: true
      when: dir_stat.stat.exists
  when: cloudcmd_enabled is false and archive_app_data_enabled is true
