---
- name: Start {{ ansible_nas_app_name }}
  block:
    - name: Create {{ ansible_nas_app_name }} Directories
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
      with_items:
        - "{{ netbootxyz_data_directory }}"
        - "{{ netbootxyz_data_directory }}/assets"
        - "{{ netbootxyz_data_directory }}/data"

    - name: Set {{ ansible_nas_app_name }} FQDN var overrides
      ansible.builtin.set_fact:
        netbootxyz_homepage_href: "https://{{ netbootxyz_hostname }}.{{ ansible_nas_domain }}"
      when: netbootxyz_traefik_enabled | bool or netbootxyz_dockflare_enabled | bool

    - name: Create {{ ansible_nas_app_name }} Container
      community.docker.docker_container:
        container_default_behavior: "compatibility"
        name: "{{ netbootxyz_container_name }}"
        hostname: "{{ netbootxyz_container_name }}"
        image: "{{ netbootxyz_image_name }}:{{ netbootxyz_image_version }}"
        pull: true
        volumes:
          - "{{ netbootxyz_data_directory }}/assets:/assets:rw"
          - "{{ netbootxyz_data_directory }}/config:/config:rw"
        ports:
          - "{{ netbootxyz_port_http }}:{{ netbootxyz_port_http }}" # changed
          - "{{ netbootxyz_port_http2 }}:{{ netbootxyz_port_http2 }}"
          - "69/udp:69/udp"
        env:
          NGINX_PORT: "{{ netbootxyz_port_http2 }}"
          PUID: "{{ netbootxyz_user_id }}"
          PGID: "{{ netbootxyz_group_id }}"
          TZ: "{{ ansible_nas_timezone }}"
          WEB_APP_PORT: "{{ netbootxyz_port_http }}"
        labels:
          autoheal: "{{ netbootxyz_autoheal_enabled | ternary('true', 'false') }}"
          com.centurylinklabs.watchtower.enable: "{{ netbootxyz_watchtower_enabled | ternary('true', 'false') }}"
          dockflare.enable: "{{ netbootxyz_dockflare_enabled | ternary('true', 'false') }}"
          dockflare.access.group: "{{ netbootxyz_dockflare_access_group }}"
          dockflare.hostname: "{{ netbootxyz_hostname }}.{{ ansible_nas_domain }}"
          dockflare.service: "http://{{ hostvars[inventory_hostname]['ansible_facts']['default_ipv4']['address'] }}:{{ netbootxyz_port_http }}"
          homepage.name: "{{ ansible_nas_app_name }}"
          homepage.group: "{{ netbootxyz_homepage_group }}"
          homepage.icon: "{{ netbootxyz_homepage_icon }}"
          homepage.href: "{{ netbootxyz_homepage_href }}"
          homepage.siteMonitor: "http://{{ hostvars[inventory_hostname]['ansible_facts']['default_ipv4']['address'] }}:{{ netbootxyz_port_http }}"
          homepage.description: "{{ 'Your favorite operating systems in one place. A network-based bootable operating system installer based on iPXE.' if homepage_show_description else omit }}"
          homepage.server: "my-docker"
          homepage.container: "{{ netbootxyz_container_name }}"
          homepage.showStats: "{{ netbootxyz_homepage_showstats | ternary('true', 'false') }}"
          repliqate.enabled: "{{ netbootxyz_repliqate_enabled | ternary('true', 'false') }}"
          repliqate.engine: "{{ netbootxyz_repliqate_engine }}"
          repliqate.schedule: "{{ netbootxyz_repliqate_schedule }}"
          repliqate.backup_id: "{{ netbootxyz_repliqate_backup_id }}"
          repliqate.retention: "{{ netbootxyz_repliqate_retention }}"
          traefik.enable: "{{ netbootxyz_traefik_enabled | ternary('true', 'false') }}"
          traefik.http.routers.netbootxyz.rule: "Host(`{{ netbootxyz_hostname }}.{{ ansible_nas_domain }}`)"
          traefik.http.routers.netbootxyz.entrypoints: "websecure"
          traefik.http.routers.netbootxyz.tls.certresolver: "letsencrypt"
          traefik.http.routers.netbootxyz.tls.domains[0].main: "{{ ansible_nas_domain }}"
          traefik.http.routers.netbootxyz.tls.domains[0].sans: "*.{{ ansible_nas_domain }}"
          traefik.http.routers.netbootxyz.middlewares: "netboot-whitelist,tinyauth-auth@docker"
          traefik.http.routers.netbootxyz.service: "netboot-main-svc"
          traefik.http.routers.netbootxyz-assets.rule: "Host(`{{ netbootxyz_hostname2 }}.{{ ansible_nas_domain }}`)"
          traefik.http.routers.netbootxyz-assets.entrypoints: "websecure"
          traefik.http.routers.netbootxyz-assets.tls.certresolver: "letsencrypt"
          traefik.http.routers.netbootxyz-assets.tls.domains[0].main: "{{ ansible_nas_domain }}"
          traefik.http.routers.netbootxyz-assets.tls.domains[0].sans: "*.{{ ansible_nas_domain }}"
          traefik.http.routers.netbootxyz-assets.middlewares: "netboot-whitelist,tinyauth-auth@docker"
          traefik.http.routers.netbootxyz-assets.service: "netboot-assets-svc"
          traefik.http.middlewares.netboot-whitelist.ipallowlist.sourcerange: "{{ netbootxyz_traefik_whitelist }}"
          traefik.http.services.netboot-main-svc.loadbalancer.server.port: "{{ netbootxyz_port_http }}"
          traefik.http.services.netboot-assets-svc.loadbalancer.server.port: "{{ netbootxyz_port_http2 }}"
          wud.tag.include: '^\d+\.\d+\.\d+$'
          wud.tag.transform.type: "semver"
          wud.link.template: "https://github.com/netbootxyz/netbootxyz/pkgs/container/netbootxyz"
        cpu_shares: "{{ netbootxyz_cpu_shares }}"
        memory: "{{ netbootxyz_memory }}"
        memory_swap: "{{ netbootxyz_memory_swap }}"
        restart_policy: unless-stopped

    - name: "Access {{ ansible_nas_app_name }} at"
      ansible.builtin.debug:
        msg: >-
          {{
            ['http://' + hostvars[inventory_hostname]['ansible_facts']['default_ipv4']['address'] + ':' + (netbootxyz_port_http | string)] +
            (['https://' + netbootxyz_hostname + '.' + ansible_nas_domain] if (netbootxyz_traefik_enabled is true or netbootxyz_dockflare_enabled is true) else []) +
            ['http://' + hostvars[inventory_hostname]['ansible_facts']['default_ipv4']['address'] + ':' + (netbootxyz_port_http2 | string) + ' (assets)'] +
            (['https://' + netbootxyz_hostname2 + '.' + ansible_nas_domain + '(assets)'] if (netbootxyz_traefik_enabled is true or netbootxyz_dockflare_enabled is true) else [])
          }}
  when: netbootxyz_enabled is true

- name: Stop {{ ansible_nas_app_name }}
  block:
    - name: Stop {{ ansible_nas_app_name }} Container
      community.docker.docker_container:
        name: "{{ netbootxyz_container_name }}"
        state: absent
  when: netbootxyz_enabled is false

- name: Data Archive {{ ansible_nas_app_name }}
  include_role:
    name: ansible-nas-archive
  vars:
    target_data_dir: "{{ netbootxyz_data_directory }}"
  when:
    - archive_app_data_enabled is true
    - netbootxyz_enabled is false