---
- name: Start {{ ansible_nas_app_name }}
  block:
    - name: Create {{ ansible_nas_app_name }} Directories
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
      with_items:
        - "{{ netbootxyz_data_directory }}"
        - "{{ netbootxyz_data_directory }}/assets"
        - "{{ netbootxyz_data_directory }}/data"

    - name: Create {{ ansible_nas_app_name }} Container
      community.docker.docker_container:
        container_default_behavior: "compatibility"
        name: "{{ netbootxyz_container_name }}"
        hostname: "{{ netbootxyz_container_name }}"
        image: "{{ netbootxyz_image_name }}:{{ netbootxyz_image_version }}"
        pull: true
        volumes:
          - "{{ netbootxyz_data_directory }}/assets:/assets:rw"
          - "{{ netbootxyz_data_directory }}/config:/config:rw"
        ports:
          - "{{ netbootxyz_port_http }}:{{ netbootxyz_port_http }}" # changed
          - "{{ netbootxyz_port_http2 }}:{{ netbootxyz_port_http2 }}"
          - "69/udp:69/udp"
        env:
          NGINX_PORT: "{{ netbootxyz_port_http2 }}"
          PUID: "{{ netbootxyz_user_id }}"
          PGID: "{{ netbootxyz_group_id }}"
          TZ: "{{ ansible_nas_timezone }}"
          WEB_APP_PORT: "{{ netbootxyz_port_http }}"
        labels:
          autoheal: "{{ netbootxyz_autoheal }}"
          com.centurylinklabs.watchtower.monitor-only: "{{ netbootxyz_watchtower_monitor_only }}"
          dockflare.enable: "{{ netbootxyz_dockflare_tunnel }}"
          dockflare.access.group: "{{ netbootxyz_dockflare_access_group }}"
          dockflare.hostname: "{{ netbootxyz_hostname }}.{{ ansible_nas_domain }}"
          dockflare.service: "http://{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}:{{ netbootxyz_port_http }}"
          homepage.name: "{{ ansible_nas_app_name }}"
          homepage.group: "{{ netbootxyz_homepage_group }}"
          homepage.icon: "{{ netbootxyz_homepage_icon }}"
          homepage.href: "{{ netbootxyz_homepage_href }}"
          homepage.siteMonitor: "http://{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}:{{ netbootxyz_port_http }}"
          homepage.description: "{{ 'Your favorite operating systems in one place. A network-based bootable operating system installer based on iPXE.' if homepage_show_description else omit }}"
          homepage.server: "my-docker"
          homepage.container: "{{ netbootxyz_container_name }}"
          homepage.showStats: "{{ netbootxyz_homepage_showStats }}"
          traefik.enable: "{{ netbootxyz_available_externally | string }}"
          traefik.http.routers.netbootxyz.rule: "Host(`{{ netbootxyz_hostname }}.{{ ansible_nas_domain }}`)"
          traefik.http.routers.netbootxyz.tls.certresolver: "letsencrypt"
          traefik.http.routers.netbootxyz.tls.domains[0].main: "{{ ansible_nas_domain }}"
          traefik.http.routers.netbootxyz.tls.domains[0].sans: "*.{{ ansible_nas_domain }}"
          traefik.http.routers.frontend.middlewares: "{{ netbootxyz_hostname }}"
          traefik.http.routers.netbootxyz.middlewares: "{{ netbootxyz_hostname }}@docker"
          traefik.http.middlewares.netbootxyz.IPAllowList.sourcerange: "{{ netbootxyz_traefik_whitelist }}"
          traefik.http.services.netbootxyz.loadbalancer.server.port: "{{ netbootxyz_port_http }}"
# TDL add the 2nd site (assets) - need to rename frontend router
#          traefik.http.routers.netbootxyz2.rule: "Host(`{{ netbootxyz_hostname2 }}.{{ ansible_nas_domain }}`)"
#          traefik.http.routers.netbootxyz2.tls.certresolver: "letsencrypt"
#          traefik.http.routers.netbootxyz2.tls.domains[0].main: "{{ ansible_nas_domain }}"
#          traefik.http.routers.netbootxyz2.tls.domains[0].sans: "*.{{ ansible_nas_domain }}"
#          traefik.http.routers.frontend.middlewares: "{{ netbootxyz_hostname2 }}"
#          traefik.http.routers.netbootxyz2.middlewares: "{{ netbootxyz_hostname2 }}@docker"
#          traefik.http.middlewares.netbootxyz2.IPAllowList.sourcerange: "{{ netbootxyz_traefik_whitelist }}"
#          traefik.http.services.netbootxyz2.loadbalancer.server.port: "{{ netbootxyz_port_http2 }}"
          wud.tag.include: '^\d+\.\d+\.\d+.*$'
          wud.tag.transform.type: "semver"
          wud.link.template: "https://github.com/netbootxyz/netboot.xyz/releases"
        cpu_shares: "{{ netbootxyz_cpu_shares }}"
        memory: "{{ netbootxyz_memory }}"
        restart_policy: unless-stopped
  when: netbootxyz_enabled is true

- name: Stop {{ ansible_nas_app_name }}
  block:
    - name: Stop {{ ansible_nas_app_name }} Container
      community.docker.docker_container:
        name: "{{ netbootxyz_container_name }}"
        state: absent
  when: netbootxyz_enabled is false

- name: Data Archive {{ ansible_nas_app_name }}
  block:
    - name: Check for {{ ansible_nas_app_name }} Data Directory
      stat:
        path: "{{ netbootxyz_data_directory }}"
      register: dir_stat

    - name: Archive {{ ansible_nas_app_name }} Data Directory
      ansible.builtin.archive:
        path: "{{ netbootxyz_data_directory }}"
        dest: "{{ docker_home }}/{{ ansible_nas_app_name | lower }}.zip"
        force_archive: true
        format: zip
        owner: ansible-nas
        group: ansible-nas
        mode: u=rw,g=rw
        remove: true
      when: dir_stat.stat.exists
  when: netbootxyz_enabled is false and archive_app_data_enabled is true
