---
# ANE
ansible_nas_app_name: "Emby"
emby_enabled: false
emby_available_externally: false
emby_traefik_whitelist: "{{ lan }}"

# directories
emby_data_directory: "{{ docker_home }}/emby"
emby_anime_directory: "{{ anime_root }}"
emby_audiobooks_directory: "{{ audiobooks_root }}"
emby_books_directory: "{{ books_root }}"
emby_movies_directory: "{{ movies_root }}"
emby_music_directory: "{{ music_root }}"
emby_photos_directory: "{{ photos_root }}"
emby_podcasts_directory: "{{ podcasts_root }}"
emby_porn_directory: "{{ porn_root }}"
emby_tv_directory: "{{ tv_root }}"

# media permissions (change to "ro" for ready only)
emby_anime_permissions: "rw"
emby_audiobooks_permissions: "rw"
emby_books_permissions: "rw"
emby_movies_permissions: "rw"
emby_music_permissions: "rw"
emby_photos_permissions: "rw"
emby_podcasts_permissions: "rw"
emby_porn_permissions: "rw"
emby_tv_permissions: "rw"

# uid / gid
emby_user_id: "0"
emby_group_id: "0"

# network
emby_port_http: "8096"
emby_port_https: "8920"
emby_hostname: "emby"

# specs
emby_memory: "1G"

# docker
emby_container_name: "emby"
emby_image: emby/embyserver
emby_image_tag: beta
emby_cpu_shares: 1024

# Device mappings for the docker container. E.g. To enable hardware transcoding:
# emby_devices:
#  - "/dev/dri:/dev/dri"

# autoheal
emby_autoheal: "false"

# dockflare
emby_dockflare_tunnel: "false"
emby_dockflare_access_group: ""

# homepage
emby_homepage_group: "Media Servers"
emby_homepage_icon: "emby.png"
emby_homepage_href: "http://{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}:{{ emby_port_http }}"
emby_homepage_showstats: "false"

# repliqate
emby_repliqate_enabled: "false"
emby_repliqate_engine: "restic"
emby_repliqate_schedule: "@daily 3am"
emby_repliqate_backup_id: "{{ emby_container_name }}"
emby_repliqate_retention: "30d"

# tinyauth
emby_tinyauth_enabled: false

# watchtower
emby_watchtower_enable: "false"