---
- name: Create ansible-nas group
  ansible.builtin.group:
    name: ansible-nas
    state: present

- name: Create ansible-nas user
  ansible.builtin.user:
    name: ansible-nas
    state: present
    system: yes
    update_password: on_create
    create_home: no
    group: ansible-nas
    shell: /usr/sbin/nologin

- name: Add {{ ansible_nas_user }} to ansible-nas, video, and render groups
  ansible.builtin.user:
    name: "{{ ansible_nas_user }}"
    state: present
    groups: ansible-nas,video,render
    append: yes
