---
- name: Start {{ ansible_nas_app_name }}
  block:
    - name: Create {{ ansible_nas_app_name }} Directories
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
      with_items:
        - "{{ doublecommander_data_directory }}"
        - "{{ doublecommander_data_directory }}/config"

    - name: Create {{ ansible_nas_app_name }} Container
      community.docker.docker_container:
        container_default_behavior: "compatibility"
        name: "{{ doublecommander_container_name }}"
        hostname: "{{ doublecommander_container_name }}"
        image: "{{ doublecommander_image_name }}:{{ doublecommander_image_tag }}"
        pull: true
        volumes:
        - "{{ doublecommander_data_directory }}/config:/config"
        - "{{ doublecommander_browse_directory }}:/data"
        ports:
          - "{{ doublecommander_port_http }}:3000"
        env:
          DOCKER_MODS: "{{ doublecommander_env_docker_mods }}"
          INSTALL_PACKAGES: "{{ doublecommander_env_docker_mods_install_packages }}"
          INSTALL_PIP_PACKAGES: "{{ doublecommander_env_docker_mods_install_pip_packages}}"
          PUID: "{{ doublecommander_user_id }}"
          PGID: "{{ doublecommander_group_id }}"
          TZ: "{{ ansible_nas_timezone }}"
        labels:
          autoheal: "{{ doublecommander_autoheal | string }}"
          com.centurylinklabs.watchtower.enable: "{{ doublecommander_watchtower_enabled | string }}"
          dockflare.enable: "{{ doublecommander_dockflare_enabled | string }}"
          dockflare.access.group: "{{ doublecommander_dockflare_access_group }}"
          dockflare.hostname: "{{ doublecommander_hostname }}.{{ ansible_nas_domain }}"
          dockflare.service: "http://{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}:{{ doublecommander_port_http }}"
          homepage.name: "{{ ansible_nas_app_name }}"
          homepage.group: "{{ doublecommander_homepage_group }}"
          homepage.icon: "{{ doublecommander_homepage_icon }}"
          homepage.href: "{{ doublecommander_homepage_href }}"
          homepage.siteMonitor: "http://{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}:{{ doublecommander_port_http }}"
          homepage.description: "{{ 'Double Commander is a free cross platform open source file manager with two panels side by side.' if homepage_show_description else omit }}"
          homepage.server: "my-docker"
          homepage.container: "{{ doublecommander_container_name }}"
          homepage.showStats: "{{ doublecommander_homepage_showstats | string }}"
          repliqate.enabled: "{{ doublecommander_repliqate_enabled | string }}"
          repliqate.engine: "{{ doublecommander_repliqate_engine }}"
          repliqate.schedule: "{{ doublecommander_repliqate_schedule }}"
          repliqate.backup_id: "{{ doublecommander_repliqate_backup_id }}"
          repliqate.retention: "{{ doublecommander_repliqate_retention }}"
          traefik.enable: "{{ doublecommander_available_externally | string }}"
          traefik.http.routers.doublecommander.rule: "Host(`{{ doublecommander_hostname }}.{{ ansible_nas_domain }}`)"
          traefik.http.routers.doublecommander.tls.certresolver: "letsencrypt"
          traefik.http.routers.doublecommander.tls.domains[0].main: "{{ ansible_nas_domain }}"
          traefik.http.routers.doublecommander.tls.domains[0].sans: "*.{{ ansible_nas_domain }}"
          traefik.http.routers.doublecommander.middlewares: "doublecommander@docker{{ ',tinyauth-auth@docker' if doublecommander_tinyauth_enabled | bool else '' }}"
          traefik.http.middlewares.doublecommander.IPAllowList.sourcerange: "{{ doublecommander_traefik_whitelist }}"
          traefik.http.services.doublecommander.loadbalancer.server.port: "3000"
          wud.watch.digest: "true"
          wud.link.template: "https://lscr.io/linuxserver/doublecommander"
        cpu_shares: "{{ doublecommander_cpu_shares }}"
        memory: "{{ doublecommander_memory }}"
        memory_swap: "{{ doublecommander_memory_swap }}"
        restart_policy: unless-stopped

    - name: Access {{ ansible_nas_app_name }} at
      ansible.builtin.debug:
        msg: >-
              {{
                ['http://' + hostvars[inventory_hostname]['ansible_default_ipv4']['address'] + ':' + (doublecommander_port_http | string)] +
                (['https://' + doublecommander_hostname + '.' + ansible_nas_domain] if (doublecommander_available_externally is true or doublecommander_dockflare_enabled is true) else [])
              }}
  when: doublecommander_enabled is true

- name: Stop {{ ansible_nas_app_name }}
  block:
    - name: Stop {{ ansible_nas_app_name }} Container
      community.docker.docker_container:
        name: "{{ doublecommander_container_name }}"
        state: absent
  when: doublecommander_enabled is false

- name: Data Archive {{ ansible_nas_app_name }}
  include_role:
    name: ansible-nas-archive
  vars:
    target_data_dir: "{{ doublecommander_data_directory }}"
  when:
    - archive_app_data_enabled is true
    - doublecommander_enabled is false