---
# ANE
ansible_nas_app_name: "Jackett"
jackett_enabled: false
jackett_available_externally: false
jackett_traefik_whitelist: "{{ lan }}"

# directories
jackett_data_directory: "{{ docker_home }}/jackett"
jackett_torrents_root: "{{ torrents_root }}"

# network
jackett_hostname: "jackett"
jackett_port_http: "9117"

# docker
jackett_container_name: "jackett"
jackett_image_name: "lscr.io/linuxserver/jackett"
jackett_image_version: "latest"
jackett_cpu_shares: 1024

# specs
jackett_memory: "1g"

# autoheal
jackett_autoheal: "false"

# dockflare
jackett_dockflare_tunnel: "false"
jackett_dockflare_access_group: ""

# homepage
jackett_homepage_group: "Download Toos"
jackett_homepage_icon: "jackett.png"
jackett_homepage_href: "http://{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}:{{ jackett_port_http }}"
jackett_homepage_showstats: "false"

# linuxserver.io docker mods
jackett_env_docker_mods: ""
jackett_env_docker_mods_install_packages: ""
jackett_env_docker_mods_install_pip_packages: ""

# theme.park themes
# https://docs.theme-park.dev/themes/jackett/
jackett_env_docker_mods_tp_theme: ""
jackett_env_docker_mods_tp_community_theme: ""
jackett_env_docker_mods_tp_domain: ""
jackett_env_docker_mods_tp_addon: ""

# repliqate
jackett_repliqate_enabled: "false"
jackett_repliqate_engine: "restic"
jackett_repliqate_schedule: "@daily 3am"
jackett_repliqate_backup_id: "{{ jackett_container_name }}"
jackett_repliqate_retention: "30d"

# watchtower
jackett_watchtower_enable: "false"