---
# ANE
ansible_nas_app_name: "Cloud Commander"
cloudcmd_enabled: false
cloudcmd_available_externally: false
cloudcmd_traefik_whitelist: "{{ lan }}"

# directories
cloudcmd_data_directory: "{{ docker_home }}/cloudcmd"
cloudcmd_browse_directory: "/"

# uid / gid
cloudcmd_user_id: "0"
cloudcmd_group_id: "0"

# network
cloudcmd_hostname: "cloudcmd"
cloudcmd_port: "7373"

# specs
cloudcmd_memory: "1g"

# docker
cloudcmd_container_name: cloudcmd
cloudcmd_cpu_shares: 1024
cloudcmd_image_name: "ghcr.io/coderaiser/cloudcmd"
cloudcmd_image_tag: "latest"

# autoheal
cloudcmd_autoheal: "false"

# dockflare
cloudcmd_dockflare_tunnel: "false"
cloudcmd_dockflare_access_group: ""

# homepage
cloudcmd_homepage_group: "Apps"
cloudcmd_homepage_icon: "cloudcmd.png"
cloudcmd_homepage_href: "http://{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}:{{ cloudcmd_port }}"
cloudcmd_homepage_showstats: "false"

# watchtower
cloudcmd_watchtower_enable: "false"