---
# ANE
ansible_nas_app_name: "Cloud Commander"
cloudcmd_enabled: false
cloudcmd_available_externally: false
cloudcmd_traefik_whitelist: "{{ lan }}"

# directories
cloudcmd_data_directory: "{{ docker_home }}/cloudcmd"
cloudcmd_browse_directory: "/"

# uid / gid
cloudcmd_user_id: "0"
cloudcmd_group_id: "0"

# network
cloudcmd_hostname: "cloudcmd"
cloudcmd_port_http: "7373"

# docker
cloudcmd_container_name: "cloudcmd"
cloudcmd_image_name: "ghcr.io/coderaiser/cloudcmd"
cloudcmd_image_tag: "latest"

# specs
cloudcmd_cpu_shares: 1024
cloudcmd_memory: "1G"
cloudcmd_memory_swap: -1

# autoheal
cloudcmd_autoheal: false

# dockflare
cloudcmd_dockflare_enabled: false
cloudcmd_dockflare_access_group: ""

# homepage
cloudcmd_homepage_group: "Apps"
cloudcmd_homepage_icon: "cloudcmd.png"
cloudcmd_homepage_href: "http://{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}:{{ cloudcmd_port_http }}"
cloudcmd_homepage_showstats: false

# repliqate
cloudcmd_repliqate_enabled: false
cloudcmd_repliqate_engine: "restic"
cloudcmd_repliqate_schedule: "@daily 3am"
cloudcmd_repliqate_backup_id: "{{ cloudcmd_container_name }}"
cloudcmd_repliqate_retention: "30d"

# tinyauth
cloudcmd_tinyauth_enabled: false

# watchtower
cloudcmd_watchtower_enabled: false