---
- name: Start {{ ansible_nas_app_name }}
  block:
    - name: Create {{ ansible_nas_app_name }} Container
      community.docker.docker_container:
        name: "{{ doku_container_name }}"
        hostname: "{{ doku_container_name }}"
        image: "{{ doku_image_name }}:{{ doku_image_version }}"
        pull: true
        cpu_shares: "{{ doku_cpu_shares }}"
        volumes:
          - "/var/run/docker.sock:/var/run/docker.sock:ro"
          - "{{ docker_home }}:/hostroot:ro"
        ports:
          - "{{ doku_port }}:{{ doku_port }}"
        env:
          PORT: "{{ doku_port }}"
          TZ: "{{ ansible_nas_timezone }}"
        restart_policy: unless-stopped
        memory: "{{ doku_memory }}"
        labels:
          autoheal: "{{ doku_autoheal }}"
          com.centurylinklabs.watchtower.monitor-only: "{{ doku_watchtower_monitor_only }}"
          homepage.group: "{{ doku_homepage_group }}"
          homepage.name: "{{ doku_homepage_name}} "
          homepage.icon: "{{ doku_homepage_icon }}"
          homepage.href: "{{ doku_homepage_href }}"
          homepage.siteMonitor: "http://{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}:{{ doku_port }}"
          homepage.description: "{{ 'Docker disk space usage' if homepage_show_description else omit }}"
          homepage.server: "my-docker"
          homepage.container: "{{ doku_container_name }}"
          homepage.showStats: "{{ doku_homepage_showStats }}"
          traefik.enable: "{{ doku_available_externally | string }}"
          traefik.http.routers.doku.rule: "Host(`{{ doku_hostname }}.{{ ansible_nas_domain }}`)"
          traefik.http.routers.doku.tls.certresolver: "letsencrypt"
          traefik.http.routers.doku.tls.domains[0].main: "{{ ansible_nas_domain }}"
          traefik.http.routers.doku.tls.domains[0].sans: "*.{{ ansible_nas_domain }}"
          traefik.http.routers.frontend.middlewares: "{{ doku_hostname }}"
          traefik.http.routers.doku.middlewares: "{{ doku_hostname }}@docker"
          traefik.http.middlewares.doku.IPAllowList.sourcerange: "{{ doku_traefik_whitelist }}"
          traefik.http.services.doku.loadbalancer.server.port: "{{ doku_port }}"
          wud.tag.include: '^\d+\.\d+\.\d+$$'
          wud.link.template: "https://github.com/amerkurev/doku/releases/tag/$${major}.$${minor}.$${patch}"
  when: doku_enabled is true

- name: Stop {{ ansible_nas_app_name }}
  block:
    - name: Stop {{ ansible_nas_app_name }} Container
      community.docker.docker_container:
        name: "{{ doku_container_name }}"
        state: absent
  when: doku_enabled is false

- name: Data Archive {{ ansible_nas_app_name }}
  block:
    - name: Check for {{ ansible_nas_app_name }} Data Directory
      stat:
        path: "{{ doku_data_directory }}"
      register: dir_stat

    - name: Archive {{ ansible_nas_app_name }} Data Directory
      ansible.builtin.archive:
        path: "{{ doku_data_directory }}"
        dest: "{{ docker_home }}/{{ ansible_nas_app_name | lower }}.zip"
        force_archive: true
        format: zip
        owner: ansible-nas
        group: ansible-nas
        mode: u=rw,g=rw
        remove: true
      when: dir_stat.stat.exists
  when: doku_enabled is false and archive_app_data_enabled is true
