---
- name: Start {{ ansible_nas_app_name }}
  block:
    - name: Create Minecraft Server Directories
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
      with_items:
        - "{{ minecraft_server_data_directory }}"

    - name: Create {{ ansible_nas_app_name }} Container
      community.docker.docker_container:
        container_default_behavior: "compatibility"
        name: "{{ minecraft_server_container_name }}"
        hostname: "{{ minecraft_server_container_name }}"
        image: "{{ minecraft_server_image_name }}:{{ minecraft_server_image_version }}"
        pull: true
        volumes:
          - "{{ minecraft_server_data_directory }}:/data:rw"
        ports:
          - "{{ minecraft_server_port }}:25565"
        env:
          EULA: "TRUE"
        labels:
          autoheal: "{{ minecraft_server_autoheal | string }}"
          com.centurylinklabs.watchtower.enable: "{{ minecraft_server_watchtower_enabled | string }}"
          dockflare.enable: "false"
          homepage.name: "{{ ansible_nas_app_name }}"
          homepage.group: "{{ minecraft_server_homepage_group }}"
          homepage.icon: "{{ minecraft_server_homepage_icon }}"
          homepage.description: "{{ 'minecraft_server description' if homepage_show_description else omit }}"
          homepage.server: "my-docker"
          homepage.container: "{{ minecraft_server_container_name }}"
          homepage.showStats: "{{ minecraft_server_homepage_showstats | string }}"
          homepage.widget.type: "minecraft"
          homepage.widget.url: "udp://{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}:{{ minecraft_server_port }}"
          repliqate.enabled: "{{ minecraft_server_repliqate_enabled | string }}"
          repliqate.engine: "{{ minecraft_server_repliqate_engine }}"
          repliqate.schedule: "{{ minecraft_server_repliqate_schedule }}"
          repliqate.backup_id: "{{ minecraft_server_repliqate_backup_id }}"
          repliqate.retention: "{{ minecraft_server_repliqate_retention }}"
          traefik.enable: "false"
          wud.tag.include: '^\d{4}\.\d+\.\d+$'
          wud.tag.transform.type: "semver"
          wud.link.template: "https://github.com/itzg/docker-minecraft-server/pkgs/container/minecraft-server"
        cpu_shares: "{{ minecraft_server_cpu_shares }}"
        memory: "{{ minecraft_server_memory }}"
        memory_swap: "{{ minecraft_server_memory_swap }}"
        restart_policy: unless-stopped
  when: minecraft_server_enabled is true

- name: Stop {{ ansible_nas_app_name }}
  block:
    - name: Stop {{ ansible_nas_app_name }} Container
      community.docker.docker_container:
        name: "{{ minecraft_server_container_name }}"
        state: absent
  when: minecraft_server_enabled is false

- name: Data Archive {{ ansible_nas_app_name }}
  include_role:
    name: ansible-nas-archive
  vars:
    target_data_dir: "{{ minecraft_server_data_directory }}"
  when:
    - archive_app_data_enabled is true
    - minecraft_server_enabled is false