---
- name: Start Duplicacy
  block:
    - name: Create {{ duplicacy_proper_name }} Directories
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
      with_items:
        - "{{ duplicacy_data_directory }}"
        - "{{ duplicacy_data_directory }}/cache"
        - "{{ duplicacy_data_directory }}/config"
        - "{{ duplicacy_data_directory }}/logs"

    - name: Set {{ duplicacy_proper_name }} FQDN var overrides
      ansible.builtin.set_fact:
        duplicacy_homepage_href: "https://{{ duplicacy_hostname }}.{{ ansible_nas_domain }}"
      when: duplicacy_traefik_enabled | bool or duplicacy_dockflare_enabled | bool

    - name: Create {{ duplicacy_proper_name }} Container
      community.docker.docker_container:
        container_default_behavior: "compatibility"
        name: "{{ duplicacy_container_name }}"
        hostname: "{{ duplicacy_hostname }}"
        image: "{{ duplicacy_image_name }}:{{ duplicacy_image_tag }}"
        pull: true
        ports:
          - "{{ duplicacy_port_http }}:3875"
        volumes:
          - "{{ duplicacy_data_directory }}/cache:/cache:rw"
          - "{{ duplicacy_data_directory }}/config:/config:rw"
          - "{{ duplicacy_data_directory }}/logs:/logs:rw"
          - "{{ samba_shares_root }}:/backuproot:{{ duplicacy_data_permissions }}"
        env:
          DUPLICACY_WEB_VERSION: "{{ duplicacy_web_version }}"
          TZ: "{{ ansible_nas_timezone }}"
          USR_ID: "{{ duplicacy_user_id }}"
          GRP_ID: "{{ duplicacy_group_id }}"
        labels:
          autoheal: "{{ duplicacy_autoheal_enabled | ternary('true', 'false') }}"
          com.centurylinklabs.watchtower.enable: "{{ duplicacy_watchtower_enabled | ternary('true', 'false') }}"
          dockflare.enable: "{{ duplicacy_dockflare_enabled | ternary('true', 'false') }}"
          dockflare.access.group: "{{ duplicacy_dockflare_access_group }}"
          dockflare.hostname: "{{ duplicacy_hostname }}.{{ ansible_nas_domain }}"
          dockflare.service: "http://{{ hostvars[inventory_hostname]['ansible_facts']['default_ipv4']['address'] }}:{{ duplicacy_port_http }}"
          homepage.name: "{{ duplicacy_proper_name }}"
          homepage.group: "{{ duplicacy_homepage_group }}"
          homepage.icon: "{{ duplicacy_homepage_icon }}"
          homepage.href: "{{ duplicacy_homepage_href }}"
          homepage.description: "{{ 'duplicacy description' if homepage_show_description else omit }}"
          homepage.server: "my-docker"
          homepage.container: "{{ duplicacy_container_name }}"
          homepage.showStats: "{{ duplicacy_homepage_showstats | ternary('true', 'false') }}"
          homepage.siteMonitor: "http://{{ hostvars[inventory_hostname]['ansible_facts']['default_ipv4']['address'] }}:{{ duplicacy_port_http }}"
          repliqate.enabled: "{{ duplicacy_repliqate_enabled | ternary('true', 'false') }}"
          repliqate.engine: "{{ duplicacy_repliqate_engine }}"
          repliqate.schedule: "{{ duplicacy_repliqate_schedule }}"
          repliqate.backup_id: "{{ duplicacy_repliqate_backup_id }}"
          repliqate.retention: "{{ duplicacy_repliqate_retention }}"
          traefik.enable: "{{ duplicacy_traefik_enabled | ternary('true', 'false') }}"
          traefik.http.routers.duplicacy.rule: "Host(`{{ duplicacy_hostname }}.{{ ansible_nas_domain }}`)"
          traefik.http.routers.duplicacy.tls.certresolver: "letsencrypt"
          traefik.http.routers.duplicacy.tls.domains[0].main: "{{ ansible_nas_domain }}"
          traefik.http.routers.duplicacy.tls.domains[0].sans: "*.{{ ansible_nas_domain }}"
          traefik.http.routers.duplicacy.middlewares: "duplicacy@docker{{ ',tinyauth-auth@docker' if duplicacy_tinyauth_enabled | bool else '' }}"
          traefik.http.middlewares.duplicacy.IPAllowList.sourcerange: "{{ duplicacy_traefik_whitelist }}"
          traefik.http.services.duplicacy.loadbalancer.server.port: "3875"
          wud.display.name: "Duplicacy Web"
          wud.watch.digest: "true"
          wud.link.template: "https://hub.docker.com/r/saspus/duplicacy-web"
        cpu_shares: "{{ duplicacy_cpu_shares }}"
        memory: "{{ duplicacy_memory }}"
        memory_swap: "{{ duplicacy_memory_swap }}"
        restart_policy: unless-stopped

    - name: Access {{ duplicacy_proper_name }} at
      ansible.builtin.debug:
        msg: >-
              {{
                ['http://' + hostvars[inventory_hostname]['ansible_facts']['default_ipv4']['address'] + ':' + (duplicacy_port_http | string)] +
                (['https://' + duplicacy_hostname + '.' + ansible_nas_domain] if (duplicacy_traefik_enabled is true or duplicacy_dockflare_enabled is true) else [])
              }}
  when: duplicacy_enabled is true

- name: Stop {{ duplicacy_proper_name }}
  block:
    - name: Stop {{ duplicacy_proper_name }} Container
      community.docker.docker_container:
        name: "{{ duplicacy_container_name }}"
        state: absent
  when: duplicacy_enabled is false

- name: Data Archive {{ duplicacy_proper_name }}
  include_role:
    name: ansible-nas-archive
  vars:
    target_data_dir: "{{ duplicacy_data_directory }}"
  when:
    - archive_app_data_enabled is true
    - duplicacy_enabled is false