---
# ANE
ansible_nas_app_name: "Komga"
komga_enabled: false
komga_traefik_enabled: false
komga_traefik_whitelist: "{{ lan }}"

# directories
komga_data_directory: "{{ docker_home }}/komga"
komga_books_directory: "{{ books_root }}"
komga_comics_directory: "{{ comics_root }}"

# uid / gid
komga_user_id: "1000"
komga_group_id: "1000"

# network
komga_hostname: "komga"
komga_port_http: "8088"

# docker
komga_container_name: "komga"
komga_image_name: "ghcr.io/gotson/komga"
komga_image_version: "latest"

# specs
komga_cpu_shares: 1024
# Minimum (Small Library): 1 GB (Functional for <1,000 books).
# Recommended (Standard): 2 GB – 4 GB (Sweet spot for most collections).
# Performance (Huge Library/Large PDFs): 4 GB+.
komga_memory: "2G"
komga_memory_swap: -1

# autoheal
komga_autoheal_enabled: false

# dockflare
komga_dockflare_enabled: false
komga_dockflare_access_group: ""

# homepage
komga_homepage_group: "Media Servers"
komga_homepage_icon: "komga"
komga_homepage_href: "http://{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}:{{ komga_port_http }}"
komga_homepage_showstats: false
komga_homepage_widget_username: ""
komga_homepage_widget_password: ""
komga_homepage_widget_key: ""

# repliqate
komga_repliqate_enabled: false
komga_repliqate_engine: "restic"
komga_repliqate_schedule: "@daily 3am"
komga_repliqate_backup_id: "{{ komga_container_name }}"
komga_repliqate_retention: "30d"

# tinyauth
komga_tinyauth_enabled: false

# watchtower
komga_watchtower_enabled: false