---
- name: Start {{ cleanuparr_proper_name }}
  block:
    - name: Create {{ cleanuparr_proper_name }} Directories
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
      with_items:
        - "{{ cleanuparr_data_directory }}"
        - "{{ cleanuparr_data_directory }}/config"

    - name: Set {{ cleanuparr_proper_name }} FQDN var overrides
      ansible.builtin.set_fact:
        cleanuparr_homepage_href: "https://{{ cleanuparr_hostname }}.{{ ansible_nas_domain }}"
      when: cleanuparr_traefik_enabled | bool or cleanuparr_dockflare_enabled | bool

    - name: Create {{ cleanuparr_proper_name }} Container
      community.docker.docker_container:
        container_default_behavior: "compatibility"
        name: "{{ cleanuparr_container_name }}"
        hostname: "{{ cleanuparr_container_name }}"
        image: "{{ cleanuparr_image_name }}:{{ cleanuparr_image_tag }}"
        pull: true
        volumes:
          - "{{ cleanuparr_data_directory }}/config:/config"
        ports:
          - "{{ cleanuparr_port_http }}:11011"
        env:
          PUID: "{{ cleanuparr_user_id }}"
          PGID: "{{ cleanuparr_group_id }}"
          TZ: "{{ ansible_nas_timezone }}"
        healthcheck:
          test: ["CMD-SHELL", "curl -f http://localhost:11011/ || exit 1"]
          interval: "{{ cleanuparr_healthcheck_interval }}"
          timeout: "{{ cleanuparr_healthcheck_timeout }}"
          retries: "{{ cleanuparr_healthcheck_retries }}"
          start_period: "{{ cleanuparr_healthcheck_start_period }}"
        labels:
          autoheal: "{{ cleanuparr_autoheal_enabled | ternary('true', 'false') }}"
          com.centurylinklabs.watchtower.enable: "{{ cleanuparr_watchtower_enabled | ternary('true', 'false') }}"
          dockflare.enable: "{{ cleanuparr_dockflare_enabled | ternary('true', 'false') }}"
          dockflare.access.group: "{{ cleanuparr_dockflare_access_group }}"
          dockflare.hostname: "{{ cleanuparr_hostname }}.{{ ansible_nas_domain }}"
          dockflare.service: "http://{{ hostvars[inventory_hostname]['ansible_facts']['default_ipv4']['address'] }}:{{ cleanuparr_port_http }}"
          homepage.name: "{{ cleanuparr_proper_name }}"
          homepage.group: "{{ cleanuparr_homepage_group }}"
          homepage.icon: "{{ cleanuparr_homepage_icon }}"
          homepage.href: "{{ cleanuparr_homepage_href }}"
          homepage.description: "{{ 'a tool for automating the cleanup of unwanted or blocked files in Sonarr, Radarr, and supported download clients like qBittorrent.' if homepage_show_description else omit }}"
          homepage.server: "my-docker"
          homepage.container: "{{ cleanuparr_container_name }}"
          homepage.showStats: "{{ cleanuparr_homepage_showstats | ternary('true', 'false') }}"
          homepage.siteMonitor: "http://{{ hostvars[inventory_hostname]['ansible_facts']['default_ipv4']['address'] }}:{{ cleanuparr_port_http }}"
          repliqate.enabled: "{{ cleanuparr_repliqate_enabled | ternary('true', 'false') }}"
          repliqate.engine: "{{ cleanuparr_repliqate_engine }}"
          repliqate.schedule: "{{ cleanuparr_repliqate_schedule }}"
          repliqate.backup_id: "{{ cleanuparr_repliqate_backup_id }}"
          repliqate.retention: "{{ cleanuparr_repliqate_retention }}"
          traefik.enable: "{{ cleanuparr_traefik_enabled | ternary('true', 'false') }}"
          traefik.http.routers.cleanuparr.rule: "Host(`{{ cleanuparr_hostname }}.{{ ansible_nas_domain }}`)"
          traefik.http.routers.cleanuparr.tls.certresolver: "letsencrypt"
          traefik.http.routers.cleanuparr.tls.domains[0].main: "{{ ansible_nas_domain }}"
          traefik.http.routers.cleanuparr.tls.domains[0].sans: "*.{{ ansible_nas_domain }}"
          traefik.http.routers.cleanuparr.middlewares: "cleanuparr@docker{{ ',tinyauth-auth@docker' if cleanuparr_tinyauth_enabled | bool else '' }}"
          traefik.http.middlewares.cleanuparr.IPAllowList.sourcerange: "{{ cleanuparr_traefik_whitelist }}"
          traefik.http.services.cleanuparr.loadbalancer.server.port: "11011"
          wud.tag.include: '^v\d+\.\d+\.\d+$'
          wud.tag.transform.type: "semver"
          wud.link.template: "https://github.com/Cleanuparr/Cleanuparr/pkgs/container/cleanuparr"
        cpu_shares: "{{ cleanuparr_cpu_shares }}"
        memory: "{{ cleanuparr_memory }}"
        memory_swap: "{{ cleanuparr_memory_swap }}"
        restart_policy: unless-stopped

    - name: Access {{ cleanuparr_proper_name }} at
      ansible.builtin.debug:
        msg: >-
              {{
                ['http://' + hostvars[inventory_hostname]['ansible_facts']['default_ipv4']['address'] + ':' + (cleanuparr_port_http | string)] +
                (['https://' + cleanuparr_hostname + '.' + ansible_nas_domain] if (cleanuparr_traefik_enabled is true or cleanuparr_dockflare_enabled is true) else [])
              }}
  when: cleanuparr_enabled is true

- name: Stop {{ cleanuparr_proper_name }}
  block:
    - name: Stop {{ cleanuparr_proper_name }} Container
      community.docker.docker_container:
        name: "{{ cleanuparr_container_name }}"
        state: absent
  when: cleanuparr_enabled is false

- name: Data Archive {{ cleanuparr_proper_name }}
  include_role:
    name: ansible-nas-archive
  vars:
    target_data_dir: "{{ cleanuparr_data_directory }}"
  when:
    - archive_app_data_enabled is true
    - cleanuparr_enabled is false