---
- name: Start {{ linkwarden_proper_name }}
  block:
    - name: Create {{ linkwarden_proper_name }} Directories
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
      with_items:
        - "{{ linkwarden_data_directory }}"
        - "{{ linkwarden_data_directory }}/data"
        - "{{ linkwarden_data_directory }}/db"
        - "{{ linkwarden_data_directory }}/search"

    - name: Set {{ linkwarden_proper_name }} FQDN var overrides
      ansible.builtin.set_fact:
        linkwarden_env_nextauth_url: "https://{{ linkwarden_hostname }}.{{ ansible_nas_domain }}/api/v1/auth"
        linkwarden_homepage_href: "https://{{ linkwarden_hostname }}.{{ ansible_nas_domain }}"
      when: linkwarden_traefik_enabled | bool or linkwarden_dockflare_enabled | bool

    - name: Create {{ linkwarden_proper_name }} Meilisearch Container
      community.docker.docker_container:
        container_default_behavior: "compatibility"
        name: "{{ linkwarden_search_container_name }}"
        hostname: "{{ linkwarden_search_container_name }}"
        image: "{{ linkwarden_search_image_name }}:{{ linkwarden_search_image_tag }}"
        pull: true
        volumes:
          - "{{ linkwarden_data_directory }}/search:/meili_data"
        env:
          MEILI_MASTER_KEY: "{{ linkwarden_env_meili_master_key }}"
          TZ: "{{ ansible_nas_timezone }}"
        labels:
          autoheal: "{{ linkwarden_search_autoheal_enabled | ternary('true', 'false') }}"
          com.centurylinklabs.watchtower.enable: "{{ linkwarden_search_watchtower_enabled | ternary('true', 'false') }}"
          dockflare.enable: "false"
          homepage.name: "{{ linkwarden_proper_name }} Meilisearch"
          homepage.group: "{{ linkwarden_search_homepage_group }}"
          homepage.icon: "{{ linkwarden_search_homepage_icon }}"
          homepage.href: "{{ linkwarden_homepage_href }}"
          homepage.description: "{{ 'A lightning-fast search engine API bringing AI-powered hybrid search to your sites and applications.' if homepage_show_description else omit }}"
          homepage.server: "my-docker"
          homepage.container: "{{ linkwarden_search_container_name }}"
          homepage.showStats: "{{ linkwarden_search_homepage_showstats | ternary('true', 'false') }}"
          homepage.widget.type: "linkwarden"
          homepage.widget.url: "http://{{ hostvars[inventory_hostname]['ansible_facts']['default_ipv4']['address'] }}:{{ linkwarden_port_http }}"
          homepage.widget.key: "{{ linkwarden_homepage_widget_key }}"
          repliqate.enabled: "{{ linkwarden_search_repliqate_enabled | ternary('true', 'false') }}"
          repliqate.engine: "{{ linkwarden_search_repliqate_engine }}"
          repliqate.schedule: "{{ linkwarden_search_repliqate_schedule }}"
          repliqate.backup_id: "{{ linkwarden_search_repliqate_backup_id }}"
          repliqate.retention: "{{ linkwarden_search_repliqate_retention }}"
          traefik.enable: "false"
          wud.tag.include: '^\d+\.\d+\.\d+.*$'
          wud.tag.transform.type: "semver"
          wud.link.template: "https://hub.docker.com/r/getmeili/meilisearch"
        cpu_shares: "{{ linkwarden_search_cpu_shares }}"
        memory: "{{ linkwarden_search_memory }}"
        memory_swap: "{{ linkwarden_search_memory_swap }}"
        restart_policy: unless-stopped

    - name: Create {{ linkwarden_proper_name }} DB Container
      community.docker.docker_container:
        container_default_behavior: "compatibility"
        name: "{{ linkwarden_db_container_name }}"
        hostname: "{{ linkwarden_db_container_name }}"
        image: "{{ linkwarden_db_image_name }}:{{ linkwarden_db_image_tag }}"
        pull: true
        volumes:
          - "{{ linkwarden_data_directory }}/db:/var/lib/postgresql/data"
        env:
          POSTGRES_USER: "{{ linkwarden_env_postgres_user }}"
          POSTGRES_PASSWORD: "{{ linkwarden_env_postgres_password }}"
          POSTGRES_DB: "linkwarden_db"
          TZ: "{{ ansible_nas_timezone }}"
        healthcheck:
          test: ["CMD-SHELL", "pg_isready -U {{ linkwarden_env_postgres_user }}"]
          interval: 10s
          timeout: 5s
          retries: 5
          start_period: 30s
        labels:
          autoheal: "{{ linkwarden_db_autoheal_enabled | ternary('true', 'false') }}"
          com.centurylinklabs.watchtower.enable: "{{ linkwarden_db_watchtower_enabled | ternary('true', 'false') }}"
          dockflare.enable: "false"
          homepage.name: "{{ linkwarden_proper_name }} PostgreSQL"
          homepage.group: "{{ linkwarden_db_homepage_group }}"
          homepage.icon: "{{ linkwarden_db_homepage_icon }}"
          homepage.href: "{{ linkwarden_homepage_href }}"
          homepage.description: "{{ 'PostgreSQL Database Management System' if homepage_show_description else omit }}"
          homepage.server: "my-docker"
          homepage.container: "{{ linkwarden_db_container_name }}"
          homepage.showStats: "{{ linkwarden_db_homepage_showstats | ternary('true', 'false') }}"
          repliqate.enabled: "{{ linkwarden_db_repliqate_enabled | ternary('true', 'false') }}"
          repliqate.engine: "{{ linkwarden_db_repliqate_engine }}"
          repliqate.schedule: "{{ linkwarden_db_repliqate_schedule }}"
          repliqate.backup_id: "{{ linkwarden_db_repliqate_backup_id }}"
          repliqate.retention: "{{ linkwarden_db_repliqate_retention }}"
          traefik.enable: "false"
          wud.tag.include: '^\d+\.\d+.*$'
          wud.tag.transform.type: "semver"
          wud.link.template: "https://hub.docker.com/_/postgres"
        cpu_shares: "{{ linkwarden_db_cpu_shares }}"
        memory: "{{ linkwarden_db_memory }}"
        memory_swap: "{{ linkwarden_db_memory_swap }}"
        restart_policy: unless-stopped

    - name: Wait for {{ linkwarden_proper_name }} DB to become healthy
      community.docker.docker_container_info:
        name: "{{ linkwarden_db_container_name }}"
      register: db_info
      until: "db_info.container.State.Health.Status == 'healthy'"
      retries: 30
      delay: 5

    - name: Create {{ linkwarden_proper_name }} Container
      community.docker.docker_container:
        container_default_behavior: "compatibility"
        name: "{{ linkwarden_container_name }}"
        hostname: "{{ linkwarden_container_name }}"
        image: "{{ linkwarden_image_name }}:{{ linkwarden_image_tag }}"
        pull: true
        volumes:
          - "{{ linkwarden_data_directory }}/data:/data/data"
        ports:
          - "{{ linkwarden_port_http }}:3000"
        env:
          DATABASE_URL: "postgresql://{{ linkwarden_env_postgres_user }}:{{ linkwarden_env_postgres_password }}@{{ linkwarden_db_container_name }}:5432/postgres"
          NEXT_PUBLIC_DISABLE_REGISTRATION: "{{ linkwarden_env_next_public_disable_registration }}"
          NEXT_PUBLIC_EMAIL_PROVIDER: "{{ linkwarden_env_next_public_email_provider }}"
          EMAIL_FROM: "{{ linkwarden_env_email_from }}"
          EMAIL_SERVER: "{{ linkwarden_env_email_server }}"
          BASE_URL: "{{ linkwarden_env_base_url }}"
          MEILI_HOST: "http://{{ linkwarden_search_container_name }}:7700"
          MEILI_MASTER_KEY: "{{ linkwarden_env_meili_master_key }}"
          NEXTAUTH_URL: "{{ linkwarden_env_nextauth_url }}"
          NEXTAUTH_SECRET: "{{ linkwarden_env_nextauth_secret }}"
          TZ: "{{ ansible_nas_timezone }}"
        links:
          - "{{ linkwarden_db_container_name }}"
          - "{{ linkwarden_search_container_name }}"
        labels:
          autoheal: "{{ linkwarden_autoheal_enabled | ternary('true', 'false') }}"
          com.centurylinklabs.watchtower.enable: "{{ linkwarden_watchtower_enabled | ternary('true', 'false') }}"
          dockflare.enable: "{{ linkwarden_dockflare_enabled | ternary('true', 'false') }}"
          dockflare.access.group: "{{ linkwarden_dockflare_access_group }}"
          dockflare.hostname: "{{ linkwarden_hostname }}.{{ ansible_nas_domain }}"
          dockflare.service: "http://{{ hostvars[inventory_hostname]['ansible_facts']['default_ipv4']['address'] }}:{{ linkwarden_port_http }}"
          homepage.name: "{{ linkwarden_proper_name }}"
          homepage.group: "{{ linkwarden_homepage_group }}"
          homepage.icon: "{{ linkwarden_homepage_icon }}"
          homepage.href: "{{ linkwarden_homepage_href }}"
          homepage.description: "{{ 'linkwarden description' if homepage_show_description else omit }}"
          homepage.server: "my-docker"
          homepage.container: "{{ linkwarden_container_name }}"
          homepage.showStats: "{{ linkwarden_homepage_showstats | ternary('true', 'false') }}"
          homepage.siteMonitor: "http://{{ hostvars[inventory_hostname]['ansible_facts']['default_ipv4']['address'] }}:{{ linkwarden_port_http }}"
          repliqate.enabled: "{{ linkwarden_repliqate_enabled | ternary('true', 'false') }}"
          repliqate.engine: "{{ linkwarden_repliqate_engine }}"
          repliqate.schedule: "{{ linkwarden_repliqate_schedule }}"
          repliqate.backup_id: "{{ linkwarden_repliqate_backup_id }}"
          repliqate.retention: "{{ linkwarden_repliqate_retention }}"
          traefik.enable: "{{ linkwarden_traefik_enabled | ternary('true', 'false') }}"
          traefik.http.routers.linkwarden.rule: "Host(`{{ linkwarden_hostname }}.{{ ansible_nas_domain }}`)"
          traefik.http.routers.linkwarden.tls.certresolver: "letsencrypt"
          traefik.http.routers.linkwarden.tls.domains[0].main: "{{ ansible_nas_domain }}"
          traefik.http.routers.linkwarden.tls.domains[0].sans: "*.{{ ansible_nas_domain }}"
          traefik.http.routers.linkwarden.middlewares: "linkwarden@docker{{ ',tinyauth-auth@docker' if linkwarden_tinyauth_enabled | bool else '' }}"
          traefik.http.middlewares.linkwarden.IPAllowList.sourcerange: "{{ linkwarden_traefik_whitelist }}"
          traefik.http.services.linkwarden.loadbalancer.server.port: "3000"
          wud.tag.include: '^\d+\.\d+\.\d+.*$'
          wud.tag.transform.type: "semver"
          wud.link.template: "https://github.com/linkwarden/linkwarden/releases"
        cpu_shares: "{{ linkwarden_cpu_shares }}"
        memory: "{{ linkwarden_memory }}"
        memory_swap: "{{ linkwarden_memory_swap }}"
        restart_policy: unless-stopped

    - name: Access {{ linkwarden_proper_name }} at
      ansible.builtin.debug:
        msg: >-
              {{
                ['http://' + hostvars[inventory_hostname]['ansible_facts']['default_ipv4']['address'] + ':' + (linkwarden_port_http | string)] +
                (['https://' + linkwarden_hostname + '.' + ansible_nas_domain] if (linkwarden_traefik_enabled is true or linkwarden_dockflare_enabled is true) else [])
              }}
  when: linkwarden_enabled is true

- name: Stop {{ linkwarden_proper_name }}
  block:
    - name: Stop {{ linkwarden_proper_name }} Container
      community.docker.docker_container:
        name: "{{ linkwarden_container_name }}"
        state: absent

    - name: Stop {{ linkwarden_proper_name }} Meilisearch Container
      community.docker.docker_container:
        name: "{{ linkwarden_search_container_name }}"
        state: absent

    - name: Stop {{ linkwarden_proper_name }} DB Container
      community.docker.docker_container:
        name: "{{ linkwarden_db_container_name }}"
        state: absent
  when: linkwarden_enabled is false

- name: Data Archive {{ linkwarden_proper_name }}
  include_role:
    name: ansible-nas-archive
  vars:
    target_data_dir: "{{ linkwarden_data_directory }}"
  when:
    - archive_app_data_enabled is true
    - linkwarden_enabled is false