---
- name: Verify
  hosts: all
  gather_facts: false
  tasks:
    - ansible.builtin.include_vars:
        file: ../../defaults/main.yml

    - name: Try and stop and remove {{ komodo_periphery_proper_name }}
      community.docker.docker_container:
        name: "{{ komodo_periphery_container_name }}"
        state: absent
      register: result_periphery

    - name: Check if {{ komodo_periphery_proper_name }} is stopped
      ansible.builtin.assert:
        that:
          - not result_periphery.changed
