---
# ANE
ansible_nas_app_name: "ONLYOFFICE Docs"
onlyoffice_enabled: false
onlyoffice_available_externally: false
onlyoffice_traefik_whitelist: "{{ lan }}"

# directories
onlyoffice_data_directory: "{{ docker_home }}/onlyoffice"

# network
onlyoffice_hostname: "onlyoffice"
onlyoffice_port_http: "9015"

# docker
onlyoffice_container_name: "onlyoffice-document-server"
onlyoffice_image_name: "onlyoffice/documentserver"
onlyoffice_image_tag: "latest"

# specs
onlyoffice_cpu_shares: 1024
onlyoffice_memory: "2g"

# app
onlyoffice_env_document_server_port_80_tcp_addr: "172.26.0.5"

# autoheal
onlyoffice_autoheal: "false"

# dockflare
onlyoffice_dockflare_tunnel: "false"
onlyoffice_dockflare_access_group: ""

# homepage
onlyoffice_homepage_group: "Apps"
onlyoffice_homepage_icon: "onlyoffice.png"
onlyoffice_homepage_href: "http://{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}:{{ onlyoffice_port_http }}"
onlyoffice_homepage_showstats: "false"

# repliqate
onlyoffice_repliqate_enabled: "false"
onlyoffice_repliqate_engine: "restic"
onlyoffice_repliqate_schedule: "@daily 3am"
onlyoffice_repliqate_backup_id: "{{ onlyoffice_container_name }}"
onlyoffice_repliqate_retention: "30d"

# watchtower
onlyoffice_watchtower_enable: "false"