---
- name: Start {{ ansible_nas_app_name }}
  block:
    - name: Create {{ ansible_nas_app_name }} Directories
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
      with_items:
        - "{{ wizarr_data_directory }}"
        - "{{ wizarr_data_directory }}/db"

    - name: Create {{ ansible_nas_app_name }} Container
      community.docker.docker_container:
        container_default_behavior: "compatibility"
        name: "{{ wizarr_container_name }}"
        hostname: "{{ wizarr_container_name }}"
        image: "{{ wizarr_image_name }}:{{ wizarr_image_tag }}"
        pull: true
        volumes:
          - "{{ wizarr_data_directory }}/db:/data/database"
        ports:
          - "{{ wizarr_port_http }}:5690"
        env:
          DISABLE_BUILTIN_AUTH: "{{ wizarr_env_disable_builtin_auth }}"
          PUID: "{{ wizarr_user_id }}"
          PGID: "{{ wizarr_group_id }}"
          TZ: "{{ ansible_nas_timezone }}"
        labels:
          autoheal: "{{ wizarr_autoheal | string }}"
          com.centurylinklabs.watchtower.enable: "{{ wizarr_watchtower_enabled | string }}"
          dockflare.enable: "{{ wizarr_dockflare_enabled | string }}"
          dockflare.access.group: "{{ wizarr_dockflare_access_group }}"
          dockflare.hostname: "{{ wizarr_hostname }}.{{ ansible_nas_domain }}"
          dockflare.service: "http://{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}:{{ wizarr_port_http }}"
          homepage.name: "{{ ansible_nas_app_name }}"
          homepage.group: "{{ wizarr_homepage_group }}"
          homepage.icon: "{{ wizarr_homepage_icon }}"
          homepage.href: "{{ wizarr_homepage_href }}"
          homepage.description: "{{ ' an advanced user invitation and management system for Jellyfin, Plex, Emby etc.' if homepage_show_description else omit }}"
          homepage.server: "my-docker"
          homepage.container: "{{ wizarr_container_name }}"
          homepage.showStats: "{{ wizarr_homepage_showstats | string }}"
          homepage.siteMonitor: "http://{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}:{{ wizarr_port_http }}"
          repliqate.enabled: "{{ wizarr_repliqate_enabled | string }}"
          repliqate.engine: "{{ wizarr_repliqate_engine }}"
          repliqate.schedule: "{{ wizarr_repliqate_schedule }}"
          repliqate.backup_id: "{{ wizarr_repliqate_backup_id }}"
          repliqate.retention: "{{ wizarr_repliqate_retention }}"
          traefik.enable: "{{ wizarr_available_externally | string }}"
          traefik.http.routers.wizarr.rule: "Host(`{{ wizarr_hostname }}.{{ ansible_nas_domain }}`)"
          traefik.http.routers.wizarr.tls.certresolver: "letsencrypt"
          traefik.http.routers.wizarr.tls.domains[0].main: "{{ ansible_nas_domain }}"
          traefik.http.routers.wizarr.tls.domains[0].sans: "*.{{ ansible_nas_domain }}"
          traefik.http.routers.wizarr.middlewares: "wizarr@docker{{ ',tinyauth-auth@docker' if wizarr_tinyauth_enabled | bool else '' }}"
          traefik.http.middlewares.wizarr.IPAllowList.sourcerange: "{{ wizarr_traefik_whitelist }}"
          traefik.http.services.wizarr.loadbalancer.server.port: "5690"
          wud.tag.include: '^v\d+\.\d+\.\d+$'
          wud.tag.transform.type: "semver"
          wud.link.template: "https://github.com/wizarrrr/wizarr/pkgs/container/wizarr"
        cpu_shares: "{{ wizarr_cpu_shares }}"
        memory: "{{ wizarr_memory }}"
        restart_policy: unless-stopped

    - name: Access {{ ansible_nas_app_name }} at
      ansible.builtin.debug:
        msg: >-
              {{
                ['http://' + hostvars[inventory_hostname]['ansible_default_ipv4']['address'] + ':' + (wizarr_port_http | string)] +
                (['https://' + wizarr_hostname + '.' + ansible_nas_domain] if (wizarr_available_externally is true or wizarr_dockflare_enabled is true) else [])
              }}
  when: wizarr_enabled is true

- name: Stop {{ ansible_nas_app_name }}
  block:
    - name: Stop {{ ansible_nas_app_name }} Container
      community.docker.docker_container:
        name: "{{ wizarr_container_name }}"
        state: absent
  when: wizarr_enabled is false

- name: Data Archive {{ ansible_nas_app_name }}
  include_role:
    name: ansible-nas-archive
  vars:
    target_data_dir: "{{ wizarr_data_directory }}"
  when:
    - archive_app_data_enabled is true
    - wizarr_enabled is false