---
- name: Start {{ ansible_nas_app_name }}
  block:
    - name: Create {{ ansible_nas_app_name }} Directories
      ansible.builtin.file:
        path: "{{ ddns_route53_data_directory }}"
        state: directory

    - name: Generate {{ ansible_nas_app_name }} config file
      ansible.builtin.template:
        src: config.yml
        dest: "{{ ddns_route53_data_directory }}/ddns-route53.yml"
      register: template_config

    - name: Create {{ ansible_nas_app_name }} Container
      community.docker.docker_container:
        container_default_behavior: "compatibility"
        name: "{{ ddns_route53_container_name }}"
        hostname: "{{ ddns_route53_container_name }}"
        image: "{{ ddns_route53_image_name }}:{{ ddns_route53_image_version }}"
        pull: true
        env:
          SCHEDULE: "{{ ddns_route53_schedule | string }}"
          TZ: "{{ ansible_nas_timezone }}"
        volumes:
          - "{{ ddns_route53_data_directory }}/ddns-route53.yml:/etc/ddns-route53/ddns-route53.yml"
        labels:
          autoheal: "{{ ddns_route53_autoheal | string }}"
          com.centurylinklabs.watchtower.enable: "{{ ddns_route53_watchtower_enabled | string }}"
          dockflare.enable: "false"
          homepage.name: "{{ ansible_nas_app_name }}"
          homepage.group: "{{ ddns_route53_homepage_group }}"
          homepage.icon: "{{ ddns_route53_homepage_icon }}"
          homepage.description: "{{ 'Dynamic DNS for Amazon Route 53 on a time-based schedule' if homepage_show_description else omit }}"
          homepage.server: "my-docker"
          homepage.container: "{{ ddns_route53_container_name }}"
          homepage.showStats: "{{ ddns_route53_homepage_showstats | string }}"
          repliqate.enabled: "false"
          traefik.enable: "false"
          wud.tag.include: '^\d+\.\d+\.\d+$'
          wud.tag.transform.type: "semver"
          wud.link.template: "https://github.com/crazy-max/ddns-route53/pkgs/container/ddns-route53"
        cpu_shares: "{{ ddns_route53_cpu_shares }}"
        memory: "{{ ddns_route53_memory }}"
        memory_swap: "{{ ddns_route53_memory_swap }}"
        recreate: "{{ template_config is changed }}"
        restart_policy: unless-stopped
  when: ddns_route53_enabled is true

- name: Stop {{ ansible_nas_app_name }}
  block:
    - name: Stop {{ ansible_nas_app_name }} Container
      community.docker.docker_container:
        name: "{{ ddns_route53_container_name }}"
        state: absent
  when: ddns_route53_enabled is false

- name: Data Archive {{ ansible_nas_app_name }}
  include_role:
    name: ansible-nas-archive
  vars:
    target_data_dir: "{{ ddns_route53_data_directory }}"
  when:
    - archive_app_data_enabled is true
    - ddns_route53_enabled is false