---
- name: Start {{ ansible_nas_app_name }}
  block:
    - name: Create {{ ansible_nas_app_name }} Directories
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
      with_items:
        - "{{ tdarr_node_data_directory }}"
        - "{{ tdarr_node_data_directory }}/configs"
        - "{{ tdarr_node_data_directory }}/logs"
        - "{{ tdarr_node_cache_directory }}"
        - "{{ tdarr_node_media_directory }}"

    - name: Create {{ ansible_nas_app_name }} Container
      community.docker.docker_container:
        container_default_behavior: "compatibility"
        name: "{{ tdarr_node_container_name }}"
        hostname: "{{ tdarr_node_container_name }}"
        image: "{{ tdarr_node_image_name }}:{{ tdarr_node_image_tag }}"
        network_mode: bridge
        pull: true
        device_requests: "{{
          [{'driver': 'nvidia', 'count': -1, 'capabilities': ['gpu']}]
          if nvidia_runtime_enabled | default(false) | bool else omit
        }}"
        devices: >-
          {%- set dev_list = (app_devices | default([])) -%}
          {%- if intel_igpu_enabled | default(false) | bool or amd_gpu_enabled | default(false) | bool -%}
            {%- set _ = dev_list.append('/dev/dri:/dev/dri') -%}
          {%- endif -%}
          {{ dev_list if dev_list | length > 0 else omit }}
        group_add: "{{ ['render', 'video'] if (amd_gpu_enabled | default(false) | bool or intel_igpu_enabled | default(false) | bool) else omit }}"
        runtime: "{{ 'nvidia' if nvidia_runtime_enabled | default(false) | bool else omit }}"
        volumes: >-
          {{ [
            tdarr_node_data_directory ~ '/configs:/app/configs',
            tdarr_node_data_directory ~ '/logs:/app/logs',
            tdarr_node_cache_directory ~ ':/temp',
            tdarr_node_media_directory ~ ':/media',
            tdarr_node_extra_directory if (tdarr_node_extra_directory is defined and ':' in tdarr_node_extra_directory) else none
          ] | reject("none") | list }}
        ports:
          - "{{ tdarr_node_port_http }}:8268"
        env:
          nodeName: "{{ ansible_nas_hostname }} Node"
          serverIP: "http://{{ hostvars[inventory_hostname]['ansible_facts']['default_ipv4']['address'] }}"
          serverPort: "{{ tdarr_node_port_server }}"
          inContainer: "true"
          ffmpegVersion: "{{ tdarr_node_env_ffmpegversion }}"
          PUID: "{{ tdarr_node_user_id }}"
          PGID: "{{ tdarr_node_group_id }}"
          NVIDIA_DRIVER_CAPABILITIES: "all"
          NVIDIA_VISIBLE_DEVICES: "all"
          TZ: "{{ ansible_nas_timezone }}"
        labels:
          autoheal: "{{ tdarr_node_autoheal_enabled | ternary('true', 'false') }}"
          com.centurylinklabs.watchtower.enable: "{{ tdarr_node_watchtower_enabled | ternary('true', 'false') }}"
          dockflare.enable: "false"
          homepage.name: "{{ ansible_nas_app_name }}"
          homepage.group: "{{ tdarr_node_homepage_group }}"
          homepage.icon: "{{ tdarr_node_homepage_icon }}"
          homepage.description: "{{ 'Tdarr Node' if homepage_show_description else omit }}"
          homepage.server: "my-docker"
          homepage.container: "{{ tdarr_node_container_name }}"
          homepage.showStats: "{{ tdarr_node_homepage_showstats | ternary('true', 'false') }}"
          repliqate.enabled: "{{ tdarr_node_repliqate_enabled | ternary('true', 'false') }}"
          repliqate.engine: "{{ tdarr_node_repliqate_engine }}"
          repliqate.schedule: "{{ tdarr_node_repliqate_schedule }}"
          repliqate.backup_id: "{{ tdarr_node_repliqate_backup_id }}"
          repliqate.retention: "{{ tdarr_node_repliqate_retention }}"
          traefik.enable: "false"
          wud.tag.include: '^\d+\.\d+\.\d+$'
          wud.tag.transform.type: "semver"
          wud.link.template: "https://github.com/HaveAGitGat/Tdarr/pkgs/container/tdarr_node"
        cpu_shares: "{{ tdarr_node_cpu_shares }}"
        log_driver: json-file
        log_options:
            max-file: "10"
            max-size: "200k"
        memory: "{{ tdarr_node_memory }}"
        memory_swap: "{{ tdarr_node_memory_swap }}"
        restart_policy: unless-stopped
  when: tdarr_node_enabled is true

- name: Stop {{ ansible_nas_app_name }}
  block:
    - name: Stop {{ ansible_nas_app_name }} Container
      community.docker.docker_container:
        name: "{{ tdarr_node_container_name }}"
        state: absent
  when: tdarr_node_enabled is false

- name: Data Archive {{ ansible_nas_app_name }}
  include_role:
    name: ansible-nas-archive
  vars:
    target_data_dir: "{{ tdarr_node_data_directory }}"
  when:
    - archive_app_data_enabled is true
    - tdarr_node_enabled is false