- name: Start {{ watchyourlan_proper_name }}
  block:
    - name: Create {{ watchyourlan_proper_name }} Container
      community.docker.docker_container:
        container_default_behavior: "compatibility"
        name: "{{ watchyourlan_container_name }}"
        hostname: "{{ watchyourlan_container_name }}"
        image: "{{ watchyourlan_image_name }}:{{ watchyourlan_image_tag }}"
        pull: true
        network_mode: host
        env:
          IFACES: "{{ watchyourlan_ifaces }}"
          HOST: "{{ watchyourlan_env_host }}"
          PORT: "{{ watchyourlan_port_http }}"
          TIMEOUT: "{{ watchyourlan_env_timeout  }}"                       
          SHOUTRRR_URL: "{{ watchyourlan_shoutrrr_url }}"
          THEME: "{{ watchyourlan_env_theme  }}"
          COLOR: "{{ watchyourlan_env_color  }}"
          TZ: "{{ ansible_nas_timezone }}"
        labels:
          autoheal: "{{ watchyourlan_autoheal_enabled | ternary('true', 'false') }}"
          com.centurylinklabs.watchtower.enable: "{{ watchyourlan_watchtower_enabled | ternary('true', 'false') }}"
          dockflare.enable: "false"
          homepage.name: "{{ watchyourlan_proper_name }}"
          homepage.group: "{{ watchyourlan_homepage_group }}"
          homepage.icon: "{{ watchyourlan_homepage_icon }}"
          homepage.href: "http://{{ hostvars[inventory_hostname]['ansible_facts']['default_ipv4']['address'] }}:{{ watchyourlan_port_http }}"
          homepage.siteMonitor: "http://{{ hostvars[inventory_hostname]['ansible_facts']['default_ipv4']['address'] }}:{{ watchyourlan_port_http }}"
          homepage.description: "{{ 'Lightweight network IP scanner.' if homepage_show_description else omit }}"
          homepage.server: "my-docker"
          homepage.container: "{{ watchyourlan_container_name }}"
          homepage.showStats: "{{ watchyourlan_homepage_showstats | ternary('true', 'false') }}"
          repliqate.enabled: "false"
          traefik.enable: "false"
          wud.tag.include: '^\d+\.\d+\.\d+$'
          wud.tag.transform.type: "semver"
          wud.link.template: "https://github.com/aceberg/watchyourlan/pkgs/container/watchyourlan"
        cpu_shares: "{{ watchyourlan_cpu_shares }}"
        memory: "{{ watchyourlan_memory }}"
        memory_swap: "{{ watchyourlan_memory_swap }}"
        restart_policy: unless-stopped

    - name: Access {{ watchyourlan_proper_name }} at
      ansible.builtin.debug:
        msg: >-
              {{
                ['http://' + hostvars[inventory_hostname]['ansible_facts']['default_ipv4']['address'] + ':' + (watchyourlan_port_http | string)] +
                (['https://' + watchyourlan_hostname + '.' + ansible_nas_domain] if (watchyourlan_dockflare_enabled is true) else [])
              }}
  when: watchyourlan_enabled is true

- name: Stop {{ watchyourlan_proper_name }}
  block:
    - name: Stop {{ watchyourlan_proper_name }} Container
      community.docker.docker_container:
        name: "{{ watchyourlan_container_name }}"
        state: absent
  when: watchyourlan_enabled is false

- name: Data Archive {{ watchyourlan_proper_name }}
  include_role:
    name: ansible-nas-archive
  vars:
    target_data_dir: "{{ watchyourlan_data_directory }}"
  when:
    - archive_app_data_enabled is true
    - watchyourlan_enabled is false