---
# ANE
ansible_nas_app_name: "Threadfin"
threadfin_enabled: false
threadfin_data_directory: "{{ docker_home }}/threadfin"
threadfin_traefik_whitelist: "{{ lan }}"

# network
threadfin_port_http: 34400

# docker
threadfin_container_name: "threadfin"
threadfin_image_name: "fyb3roptik/threadfin"
threadfin_image_version: "latest" # latest-nvidia - should this have nvidia runtime suport added?

# uid / gid
threadfin_user_id: "1001"
threadfin_group_id: "1001"

# specs
threadfin_cpu_shares: 1024
threadfin_memory: "1G"

# autoheal
threadfin_autoheal_enabled: false

# homepage
threadfin_homepage_group: "Misc"
threadfin_homepage_icon: "xteve"
threadfin_homepage_href: "http://{{ hostvars[inventory_hostname]['ansible_facts']['default_ipv4']['address'] }}:{{ threadfin_port_http }}"
threadfin_homepage_showstats: false

# repliqate
threadfin_repliqate_enabled: false
threadfin_repliqate_engine: "restic"
threadfin_repliqate_schedule: "@daily 3am"
threadfin_repliqate_backup_id: "{{ threadfin_container_name }}"
threadfin_repliqate_retention: "30d"

# watchtower
threadfin_watchtower_enabled: false