---
# ANE
ansible_nas_app_name: "Threadfin"
threadfin_enabled: false
threadfin_data_directory: "{{ docker_home }}/threadfin"
threadfin_traefik_whitelist: "{{ lan }}"

# network
threadfin_port: 34400

# docker
threadfin_container_name: "threadfin"
threadfin_image_name: "fyb3roptik/threadfin"
threadfin_image_version: "latest" # latest-nvidia - should this have nvidia runtime suport added?

# specs
threadfin_cpu_shares: 1024
threadfin_memory: 1g

# autoheal
threadfin_autoheal: "false"

# homepage
threadfin_homepage_group: "Apps"
threadfin_homepage_icon: "xteve"
threadfin_homepage_href: "http://{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}:{{ threadfin_port }}"
threadfin_homepage_showstats: "false"

# watchtower
threadfin_watchtower_enable: "false"