---
# ANE
ansible_nas_app_name: "Portainer"
portainer_enabled: false
portainer_available_externally: false
portainer_traefik_whitelist: "{{ lan }}"

# directories
portainer_data_directory: "{{ docker_home }}/portainer"

# network
portainer_port: "9000"
portainer_hostname: "portainer"
portainer_ip_allowlist: "0.0.0.0/0"

# docker
portainer_container_name: "portainer"
portainer_image_name: "portainer/portainer-ce"
portainer_image_version: "latest"

# specs
portainer_cpu_shares: 1024
portainer_memory: 1g

# autoheal
portainer_autoheal: "false"

# dockflare
portainer_dockflare_tunnel: "false"
portainer_dockflare_access_group: ""

# homepage
portainer_homepage_group: "Apps"
portainer_homepage_icon: "portainer.png"
portainer_homepage_href: "http://{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}:{{ portainer_port }}"
portainer_homepage_showStats: "false"
portainer_homepage_widget_key: "override_me_in_group_vars"

# watchtower
portainer_watchtower_monitor_only: "true"