---
- name: Start {{ ansible_nas_app_name }}
  block:
    - name: Create {{ ansible_nas_app_name }} Directories
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
      with_items:
        - "{{ containery_data_directory }}"
        - "{{ containery_data_directory }}/data"
        - "{{ containery_data_directory }}/static"

    - name: Create {{ ansible_nas_app_name }} Container
      community.docker.docker_container:
        container_default_behavior: "compatibility"
        name: "{{ containery_container_name }}"
        hostname: "{{ containery_container_name }}"
        image: "{{ containery_image_name }}:{{ containery_image_tag }}"
        pull: true
        volumes:
          - "{{ containery_data_directory }}/data:/containery_data"
          - "{{ containery_data_directory }}/static:/containery/app/static/dist"
          - "/var/run/docker.sock:/var/run/docker.sock:ro"
        ports:
          - "{{ containery_port_http }}:5000"
        env:
          TZ: "{{ ansible_nas_timezone }}"
        labels:
          autoheal: "{{ containery_autoheal }}"
          com.centurylinklabs.watchtower.enable: "{{ containery_watchtower_enable }}"
          dockflare.enable: "{{ containery_dockflare_tunnel }}"
          dockflare.access.group: "{{ containery_dockflare_access_group }}"
          dockflare.hostname: "{{ containery_hostname }}.{{ ansible_nas_domain }}"
          dockflare.service: "http://{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}:{{ containery_port_http }}"
          homepage.name: "{{ ansible_nas_app_name }}"
          homepage.group: "{{ containery_homepage_group }}"
          homepage.icon: "{{ containery_homepage_icon }}"
          homepage.href: "{{ containery_homepage_href }}"
          homepage.description: "{{ 'Powerfull, fast and lightweight container managment web application' if homepage_show_description else omit }}"
          homepage.server: "my-docker"
          homepage.container: "{{ containery_container_name }}"
          homepage.showStats: "{{ containery_homepage_showstats }}"
          homepage.siteMonitor: "http://{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}:{{ containery_port_http }}"
          repliqate.enabled: "{{ containery_repliqate_enabled }}"
          repliqate.engine: "{{ containery_repliqate_engine }}"
          repliqate.schedule: "{{ containery_repliqate_schedule }}"
          repliqate.backup_id: "{{ containery_repliqate_backup_id }}"
          repliqate.retention: "{{ containery_repliqate_retention }}"
          traefik.enable: "{{ containery_available_externally | string }}"
          traefik.http.routers.containery.rule: "Host(`{{ containery_hostname }}.{{ ansible_nas_domain }}`)"
          traefik.http.routers.containery.tls.certresolver: "letsencrypt"
          traefik.http.routers.containery.tls.domains[0].main: "{{ ansible_nas_domain }}"
          traefik.http.routers.containery.tls.domains[0].sans: "*.{{ ansible_nas_domain }}"
          traefik.http.routers.containery.middlewares: "containery@docker{{ ',tinyauth-auth@docker' if containery_tinyauth_enabled | bool else '' }}"
          traefik.http.middlewares.containery.IPAllowList.sourcerange: "{{ containery_traefik_whitelist }}"
          traefik.http.services.containery.loadbalancer.server.port: "5000"
          wud.tag.include: '^\d+\.\d+\.\d+.*$'
          wud.tag.transform.type: "semver"
          wud.link.template: "https://github.com/danylo829/containery/releases"
        cpu_shares: "{{ containery_cpu_shares }}"
        memory: "{{ containery_memory }}"
        memory_swap: "{{ containery_memory_swap }}"
        restart_policy: unless-stopped

    - name: Access {{ ansible_nas_app_name }} at
      ansible.builtin.debug:
        msg: >-
              {{
                ['http://' + hostvars[inventory_hostname]['ansible_default_ipv4']['address'] + ':' + (containery_port_http | string)] +
                (['https://' + containery_hostname + '.' + ansible_nas_domain] if (containery_available_externally is true or containery_dockflare_tunnel is true) else [])
              }}
  when: containery_enabled is true

- name: Stop {{ ansible_nas_app_name }}
  block:
    - name: Stop {{ ansible_nas_app_name }} Container
      community.docker.docker_container:
        name: "{{ containery_container_name }}"
        state: absent
  when: containery_enabled is false

- name: Data Archive {{ ansible_nas_app_name }}
  include_role:
    name: ansible-nas-archive
  vars:
    target_data_dir: "{{ containery_data_directory }}"
  when:
    - archive_app_data_enabled is true
    - containery_enabled is false