---
- name: Start {{ ansible_nas_app_name }}
  block:
    - name: Create {{ ansible_nas_app_name }} Directories
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
      with_items:
        - "{{ silverbullet_data_directory }}"

    - name: Create {{ ansible_nas_app_name }} Container
      community.docker.docker_container:
        container_default_behavior: "compatibility"
        name: "{{ silverbullet_container_name }}"
        hostname: "{{ silverbullet_hostname }}"
        image: "{{ silverbullet_image_name }}:{{ silverbullet_image_version }}"
        pull: true
        ports:
          - "{{ silverbullet_port_http }}:3000"
        volumes:
          - "{{ silverbullet_data_directory }}:/space"
        env:
          SB_USER: "{{ silverbullet_username }}:{{ silverbullet_password }}"
          TZ: "{{ ansible_nas_timezone }}"
        labels:
          autoheal: "{{ silverbullet_autoheal }}"
          com.centurylinklabs.watchtower.enable: "{{ silverbullet_watchtower_enable }}"
          dockflare.enable: "{{ silverbullet_dockflare_tunnel }}"
          dockflare.access.group: "{{ silverbullet_dockflare_access_group }}"
          dockflare.hostname: "{{ silverbullet_hostname }}.{{ ansible_nas_domain }}"
          dockflare.service: "http://{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}:{{ silverbullet_port_http }}"
          homepage.name: "{{ ansible_nas_app_name }}"
          homepage.group: "{{ silverbullet_homepage_group }}"
          homepage.icon: "{{ silverbullet_homepage_icon }}"
          homepage.href: "{{ silverbullet_homepage_href }}"
          homepage.description: "{{ 'Notes for developers' if homepage_show_description else omit }}"
          homepage.server: "my-docker"
          homepage.container: "{{ silverbullet_container_name }}"
          homepage.showStats: "{{ silverbullet_homepage_showstats }}"
          homepage.siteMonitor: "http://{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}:{{ silverbullet_port_http }}"
          repliqate.enabled: "{{ silverbullet_repliqate_enabled }}"
          repliqate.engine: "{{ silverbullet_repliqate_engine }}"
          repliqate.schedule: "{{ silverbullet_repliqate_schedule }}"
          repliqate.backup_id: "{{ silverbullet_repliqate_backup_id }}"
          repliqate.retention: "{{ silverbullet_repliqate_retention }}"
          traefik.enable: "{{ silverbullet_available_externally | string }}"
          traefik.http.routers.silverbullet.rule: "Host(`{{ silverbullet_hostname }}.{{ ansible_nas_domain }}`)"
          traefik.http.routers.silverbullet.tls.certresolver: "letsencrypt"
          traefik.http.routers.silverbullet.tls.domains[0].main: "{{ ansible_nas_domain }}"
          traefik.http.routers.silverbullet.tls.domains[0].sans: "*.{{ ansible_nas_domain }}"
          traefik.http.routers.silverbullet.middlewares: "silverbullet@docker{{ ',tinyauth-auth@docker' if silverbullet_tinyauth_enabled | bool else '' }}"
          traefik.http.middlewares.silverbullet.IPAllowList.sourcerange: "{{ silverbullet_traefik_whitelist }}"
          traefik.http.services.silverbullet.loadbalancer.server.port: "3000"
          wud.tag.include: '^\d+\.\d+\.\d+.*$'
          wud.tag.transform.type: "semver"
          wud.link.template: "https://hub.docker.com/r/zefhemel/silverbullet"
        cpu_shares: "{{ silverbullet_cpu_shares }}"
        memory: "{{ silverbullet_memory }}"
        restart_policy: unless-stopped

    - name: Access {{ ansible_nas_app_name }} at
      ansible.builtin.debug:
        msg: >-
              {{
                ['https://' + hostvars[inventory_hostname]['ansible_default_ipv4']['address'] + ':' + (silverbullet_port_http | string)] +
                (['https://' + silverbullet_hostname + '.' + ansible_nas_domain] if (silverbullet_available_externally is true or silverbullet_dockflare_tunnel is true) else [])
              }}
  when: silverbullet_enabled is true

- name: Stop {{ ansible_nas_app_name }}
  block:
    - name: Stop {{ ansible_nas_app_name }} Container
      community.docker.docker_container:
        name: "{{ silverbullet_container_name }}"
        state: absent
  when: silverbullet_enabled is false

- name: Data Archive {{ ansible_nas_app_name }}
  include_role:
    name: ansible-nas-archive
  vars:
    target_data_dir: "{{ silverbullet_data_directory }}"
  when:
    - archive_app_data_enabled is true
    - silverbullet_enabled is false