---
- name: Start {{ ansible_nas_app_name }}
  block:
    - name: Create {{ ansible_nas_app_name }} Directories
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        mode: 0775
      with_items:
        - "{{ heimdall_data_directory }}"

    - name: Create {{ ansible_nas_app_name }} Container
      community.docker.docker_container:
        container_default_behavior: "compatibility"
        name: "{{ heimdall_container_name }}"
        hostname: "{{ heimdall_container_name }}"
        image: "{{ heimdall_docker_image }}:{{ heimdall_docker_image_tag }}"
        pull: true
        volumes:
          - "{{ heimdall_data_directory }}:/config:rw"
        env:
#         PUID: "{{ heimdall_puid }}"    # unknown effects on existing installs
#         PGID: "{{ heimdall_pgid }}"    # unknown effects on existing installs
          TZ: "{{ ansible_nas_timezone }}"
        ports:
          - "{{ heimdall_port_http }}:80"
        labels:
          autoheal: "{{ heimdall_autoheal }}"
          com.centurylinklabs.watchtower.monitor-only: "{{ heimdall_watchtower_monitor_only }}"
          homepage.name: "{{ ansible_nas_app_name }}"
          homepage.group: "{{ heimdall_homepage_group }}"
          homepage.icon: "{{ heimdall_homepage_icon }}"
          homepage.href: "{{ heimdall_homepage_href }}"
          homepage.siteMonitor: "http://{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}:{{ heimdall_port_http }}"
          homepage.description: "{{ 'An application dashboard and launcher' if homepage_show_description else omit }}"
          homepage.server: "my-docker"
          homepage.container: "{{ heimdall_container_name }}"
          homepage.showStats: "{{ heimdall_homepage_showStats }}"
          traefik.enable: "{{ heimdall_available_externally | string }}"
          traefik.http.routers.heimdall.rule: "Host(`{{ heimdall_hostname }}.{{ ansible_nas_domain }}`)"
          traefik.http.routers.heimdall.tls.certresolver: "letsencrypt"
          traefik.http.routers.heimdall.tls.domains[0].main: "{{ ansible_nas_domain }}"
          traefik.http.routers.heimdall.tls.domains[0].sans: "*.{{ ansible_nas_domain }}"
          traefik.http.routers.frontend.middlewares: "{{ heimdall_hostname }}"
          traefik.http.routers.heimdall.middlewares: "{{ heimdall_hostname }}@docker"
          traefik.http.middlewares.heimdall.IPAllowList.sourcerange: "{{ heimdall_traefik_whitelist }}"
          traefik.http.services.heimdall.loadbalancer.server.port: "80"
          wud.tag.include: '^\d+\.\d+\.\d+$$'
          wud.link.template: "https://github.com/linuxserver/docker-heimdall/releases/tag/$${major}.$${minor}.$${patch}"
        cpu_shares: "{{ heimdall_cpu_shares }}"
        memory: "{{ heimdall_memory }}"
        restart_policy: unless-stopped
  when: heimdall_enabled is true

- name: Stop {{ ansible_nas_app_name }}
  block:
    - name: Stop {{ ansible_nas_app_name }} Container
      community.docker.docker_container:
        name: "{{ heimdall_container_name }}"
        state: absent
  when: heimdall_enabled is false

- name: Data Archive {{ ansible_nas_app_name }}
  block:
    - name: Check for {{ ansible_nas_app_name }} Data Directory
      stat:
        path: "{{ heimdall_data_directory }}"
      register: dir_stat

    - name: Archive {{ ansible_nas_app_name }} Data Directory
      ansible.builtin.archive:
        path: "{{ heimdall_data_directory }}"
        dest: "{{ docker_home }}/{{ ansible_nas_app_name | lower }}.zip"
        force_archive: true
        format: zip
        owner: ansible-nas
        group: ansible-nas
        mode: u=rw,g=rw
        remove: true
      when: dir_stat.stat.exists
  when: heimdall_enabled is false and archive_app_data_enabled is true
