---
- name: Start {{ ansible_nas_app_name }}
  block:
    - name: Create {{ ansible_nas_app_name }} Directories
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        owner: "1001"
        group: "1001"
      with_items:
        - "{{ osticket_data_directory }}/osticket"
        - "{{ osticket_data_directory }}/db"

    - name: Set {{ ansible_nas_app_name }} FQDN var overrides
      ansible.builtin.set_fact:
        osticket_homepage_href: "https://{{ osticket_hostname }}.{{ ansible_nas_domain }}"
      when: osticket_traefik_enabled | bool or osticket_dockflare_enabled | bool

    - name: Create {{ ansible_nas_app_name }} DB Container
      community.docker.docker_container:
        container_default_behavior: "compatibility"
        name: "{{ osticket_db_container_name }}"
        hostname: "{{ osticket_db_container_name }}"
        image: "{{ osticket_db_image_name }}:{{ osticket_db_image_tag }}"
        pull: true
        network_mode: bridge
        volumes:
          - "{{ osticket_data_directory }}/db:/config"
        env:
          ALLOW_EMPTY_PASSWORD: "{{ osticket_env_allow_empty_password }}"
          CONTAINER_NAME: "{{ osticket_db_container_name }}"
          DOCKER_MODS: "{{ osticket_db_env_docker_mods }}"
          INSTALL_PACKAGES: "{{ osticket_db_env_docker_mods_install_packages }}"
          INSTALL_PIP_PACKAGES: "{{ osticket_db_env_docker_mods_install_pip_packages}}"
          MYSQL_ROOT_PASSWORD: "{{ osticket_env_mysql_root_password }}"
          MYSQL_DATABASE: "{{ osticket_env_mysql_database }}"
          MYSQL_USER: "{{ osticket_env_mysql_user }}"
          MYSQL_PASSWORD: "{{ osticket_env_mysql_password }}"
          TZ: "{{ ansible_nas_timezone }}"
        healthcheck:
          test: "{{ osticket_db_healthcheck_test }}"
          interval: "{{ osticket_db_healthcheck_interval }}"
          timeout: "{{ osticket_db_healthcheck_timeout }}"
          retries: "{{ osticket_db_healthcheck_retries }}"
          start_period: "{{ osticket_db_healthcheck_start_period }}"
        labels:
          autoheal: "{{ osticket_db_autoheal_enabled | ternary('true', 'false') }}"
          com.centurylinklabs.watchtower.enable: "{{ osticket_db_watchtower_enabled | ternary('true', 'false') }}"
          dockflare.enable: "false"
          homepage.name: "{{ ansible_nas_app_name }} MariaDB"
          homepage.group: "{{ osticket_db_homepage_group }}"
          homepage.icon: "{{ osticket_db_homepage_icon }}"
          homepage.href: "{{ osticket_homepage_href }}"
          homepage.description: "{{ 'MariaDB Server is a high performing open source relational database, forked from MySQL.' if homepage_show_description else omit }}"
          homepage.server: "my-docker"
          homepage.container: "{{ osticket_db_container_name }}"
          homepage.showStats: "{{ osticket_homepage_showstats | ternary('true', 'false') }}"
          repliqate.enabled: "{{ osticket_db_repliqate_enabled | ternary('true', 'false') }}"
          repliqate.engine: "{{ osticket_db_repliqate_engine }}"
          repliqate.schedule: "{{ osticket_db_repliqate_schedule }}"
          repliqate.backup_id: "{{ osticket_db_repliqate_backup_id }}"
          repliqate.retention: "{{ osticket_db_repliqate_retention }}"
          traefik.enable: "false"
          wud.tag.include: '^\d+\.\d+\.\d+$'
          wud.tag.transform.type: "semver"
          wud.link.template: "lscr.io/linuxserver/mariadb"
        cpu_shares: "{{ osticket_db_cpu_shares }}"
        memory: "{{ osticket_db_memory }}"
        memory_swap: "{{ osticket_db_memory_swap }}"
        restart_policy: unless-stopped

    - name: Verify {{ ansible_nas_app_name }} DB is healthy
      community.docker.docker_container_info:
        name: "{{ osticket_db_container_name }}"
      register: db_info
      until: "db_info.container.State.Health.Status == 'healthy'"
      retries: 30
      delay: 5

    - name: Create {{ ansible_nas_app_name }} Container
      community.docker.docker_container:
        container_default_behavior: "compatibility"
        name: "{{ osticket_container_name }}"
        hostname: "{{ osticket_container_name }}"
        image: "{{ osticket_image_name }}:{{ osticket_image_tag }}"
        pull: true
        network_mode: bridge
        ports:
          - "{{ osticket_port_http }}:80"
        env:
          ALLOW_EMPTY_PASSWORD: "{{ osticket_env_allow_empty_password }}"
          ADMIN_USERNAME: "{{ osticket_env_admin_username }}"
          ADMIN_PASSWORD: "{{ osticket_env_admin_password }}"
          CONTAINER_NAME: "{{ osticket_container_name }}"
          MYSQL_ROOT_PASSWORD: "{{ osticket_env_mysql_root_password }}"
          MYSQL_DATABASE: "{{ osticket_env_mysql_database }}"
          MYSQL_HOST: "{{ osticket_db_container_name }}"
          MYSQL_USER: "{{ osticket_env_mysql_user }}"
          MYSQL_PASSWORD: "{{ osticket_env_mysql_password }}"
          TZ: "{{ ansible_nas_timezone }}"
        healthcheck:
          test: "{{ osticket_healthcheck_test }}"
          interval: "{{ osticket_healthcheck_interval }}"
          timeout: "{{ osticket_healthcheck_timeout }}"
          retries: "{{ osticket_healthcheck_retries }}"
          start_period: "{{ osticket_healthcheck_start_period }}"
        links:
          - "{{ osticket_db_container_name }}"
        labels:
          autoheal: "{{ osticket_autoheal_enabled | ternary('true', 'false') }}"
          com.centurylinklabs.watchtower.enable: "{{ osticket_watchtower_enabled | ternary('true', 'false') }}"
          dockflare.enable: "{{ osticket_dockflare_enabled | ternary('true', 'false') }}"
          dockflare.access.group: "{{ osticket_dockflare_access_group }}"
          dockflare.hostname: "{{ osticket_hostname }}.{{ ansible_nas_domain }}"
          dockflare.service: "http://{{ hostvars[inventory_hostname]['ansible_facts']['default_ipv4']['address'] }}:{{ osticket_port_http }}"
          homepage.name: "{{ ansible_nas_app_name }}"
          homepage.group: "{{ osticket_homepage_group }}"
          homepage.icon: "{{ osticket_homepage_icon }}"
          homepage.href: "{{ osticket_homepage_href }}"
          homepage.siteMonitor: "http://{{ hostvars[inventory_hostname]['ansible_facts']['default_ipv4']['address'] }}:{{ osticket_port_http }}"
          homepage.description: "{{ 'OsTicket' if homepage_show_description else omit }}"
          homepage.server: "my-docker"
          homepage.container: "{{ osticket_container_name }}"
          homepage.showStats: "{{ osticket_homepage_showstats | ternary('true', 'false') }}"
          repliqate.enabled: "{{ osticket_repliqate_enabled | ternary('true', 'false') }}"
          repliqate.engine: "{{ osticket_repliqate_engine }}"
          repliqate.schedule: "{{ osticket_repliqate_schedule }}"
          repliqate.backup_id: "{{ osticket_repliqate_backup_id }}"
          repliqate.retention: "{{ osticket_repliqate_retention }}"
          traefik.enable: "{{ osticket_traefik_enabled | ternary('true', 'false') }}"
          traefik.http.routers.osticket.rule: "Host(`{{ osticket_hostname }}.{{ ansible_nas_domain }}`)"
          traefik.http.routers.osticket.tls.certresolver: "letsencrypt"
          traefik.http.routers.osticket.tls.domains[0].main: "{{ ansible_nas_domain }}"
          traefik.http.routers.osticket.tls.domains[0].sans: "*.{{ ansible_nas_domain }}"
          traefik.http.routers.osticket.middlewares: "osticket@docker{{ ',tinyauth-auth@docker' if osticket_tinyauth_enabled | bool else '' }}"
          traefik.http.middlewares.osticket.IPAllowList.sourcerange: "{{ osticket_traefik_whitelist }}"
          traefik.http.services.osticket.loadbalancer.server.port: "80"
          wud.tag.include: '^\d+\.\d+\.\d+$'
          wud.tag.transform.type: "semver"
          wud.link.template: "https://hub.docker.com/r/ahkarswe/osticket"
        cpu_shares: "{{ osticket_cpu_shares }}"
        memory: "{{ osticket_memory }}"
        memory_swap: "{{ osticket_memory_swap }}"
        restart_policy: unless-stopped

    - name: Access {{ ansible_nas_app_name }} at
      ansible.builtin.debug:
        msg: >-
              {{
                ['http://' + hostvars[inventory_hostname]['ansible_facts']['default_ipv4']['address'] + ':' + (osticket_port_http | string)] +
                (['https://' + osticket_hostname + '.' + ansible_nas_domain] if (osticket_traefik_enabled is true or osticket_dockflare_enabled is true) else [])
              }}
  when: osticket_enabled is true

- name: Stop {{ ansible_nas_app_name }}
  block:
    - name: Stop {{ ansible_nas_app_name }} Container
      community.docker.docker_container:
        name: "{{ osticket_container_name }}"
        state: absent

    - name: Stop {{ ansible_nas_app_name }} DB Container
      community.docker.docker_container:
        name: "{{ osticket_db_container_name }}"
        state: absent
  when: osticket_enabled is false

- name: Data Archive {{ ansible_nas_app_name }}
  include_role:
    name: ansible-nas-archive
  vars:
    target_data_dir: "{{ osticket_data_directory }}"
  when:
    - archive_app_data_enabled is true
    - osticket_enabled is false