---
- name: Verify
  hosts: all
  gather_facts: false
  tasks:
    - ansible.builtin.include_vars:
        file: ../../defaults/main.yml

    - name: Try and stop and remove {{ uptime_kuma_proper_name }}
      community.docker.docker_container:
        name: "{{ uptime_kuma_container_name }}"
        state: absent
      register: result

    - name: Check {{ uptime_kuma_proper_name }} is stopped
      ansible.builtin.assert:
        that:
          - not result.changed
