---
# ANE
ansible_nas_app_name: "Wireshark"
wireshark_enabled: false
wireshark_available_externally: false
wireshark_traefik_whitelist: "{{ lan }}"

# directories
wireshark_data_directory: "{{ docker_home }}/wireshark"

# uid / gid
wireshark_user_id: "1000"
wireshark_group_id: "1000"

# network
wireshark_hostname: "wireshark"

# docker
wireshark_container_name: "wireshark"
wireshark_image_name: "lscr.io/linuxserver/wireshark"
wireshark_image_version: "latest"
wireshark_env_docker_mods: ""

# specs
wireshark_cpu_shares: 1024
wireshark_memory: "512m"

# autoheal
wireshark_autoheal: "false"

# watchtower
wireshark_watchtower_monitor_only: "true"