---
# ANE
ansible_nas_app_name: "Wireshark"
wireshark_enabled: false
wireshark_available_externally: false
wireshark_traefik_whitelist: "{{ lan }}"

# directories
wireshark_data_directory: "{{ docker_home }}/wireshark"

# uid / gid
wireshark_user_id: "1000"
wireshark_group_id: "1000"

# network
wireshark_hostname: "wireshark"
wireshark_port_http: "3000"
wireshark_port_https: "3001"
wireshark_port_kasmvnc: "8082"

# docker
wireshark_container_name: "wireshark"
wireshark_image_name: "lscr.io/linuxserver/wireshark"
wireshark_image_version: "latest"

# specs
wireshark_cpu_shares: 1024
wireshark_memory: "512M"

# app
wireshark_env_custom_user: "{{ ansible_nas_user }}"
wireshark_env_password: "{{ ansible_nas_app_admin_password }}"

# autoheal
wireshark_autoheal: "false"

# linuxserver.io docker mods
wireshark_env_docker_mods: ""
wireshark_env_docker_mods_install_packages: ""
wireshark_env_docker_mods_install_pip_packages: ""

# homepage
wireshark_homepage_group: "Network"
#wireshark_homepage_group: "Apps"
wireshark_homepage_icon: "wireshark.png"
wireshark_homepage_href: "https://{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}:{{ wireshark_port_http }}"
wireshark_homepage_showstats: "false"

# repliqate
wireshark_repliqate_enabled: "false"
wireshark_repliqate_engine: "restic"
wireshark_repliqate_schedule: "@daily 3am"
wireshark_repliqate_backup_id: "{{ wireshark_container_name }}"
wireshark_repliqate_retention: "30d"

# tinyauth
wireshark_tinyauth_enabled: false

# watchtower
wireshark_watchtower_enable: "false"

# TDL: more env vars can be added
# # https://github.com/linuxserver/docker-wireshark