---
# ANE
ansible_nas_app_name: "Node-RED"
node_red_enabled: false
node_red_traefik_enabled: false
node_red_traefik_whitelist: "{{ lan }}"

# directories
node_red_data_directory: "{{ docker_home }}/node-red"

# docker
node_red_container_name: "nodered"
node_red_image_name: "ghcr.io/node-red/node-red"
node_red_image_tag: "latest"

# network
node_red_port_http: "1880"
node_red_hostname: "nodered"

# specs
node_red_cpu_shares: 1024
node_red_memory: "1G"
node_red_memory_swap: -1

# autoheal
node_red_autoheal_enabled: false

# dockflare
node_red_dockflare_enabled: false
node_red_dockflare_access_group: ""

# homepage
node_red_homepage_group: "Apps"
node_red_homepage_icon: "node-red.png"
node_red_homepage_href: "http://{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}:{{ node_red_port_http }}"
node_red_homepage_showstats: false

# repliqate
node_red_repliqate_enabled: false
node_red_repliqate_engine: "restic"
node_red_repliqate_schedule: "@daily 3am"
node_red_repliqate_backup_id: "{{ node_red_container_name }}"
node_red_repliqate_retention: "30d"

# tinyauth
node_red_tinyauth_enabled: false

# watchtower
node_red_watchtower_enabled: false
