---
# ANE
ansible_nas_app_name: "Conduit"
conduit_enabled: false
conduit_available_externally: false
conduit_traefik_whitelist: "{{ lan }}"

# directories
conduit_data_directory: "{{ docker_home }}/conduit"

# network
conduit_hostname: "conduit"
conduit_port_http: "6167"

# docker
conduit_container_name: "conduit"
conduit_image_name: "matrixconduit/matrix-conduit"
conduit_image_tag: "latest"
conduit_cpu_shares: 1024
conduit_memory: "1G"

# autoheal
conduit_autoheal: "false"

# dockflare
conduit_dockflare_tunnel: "false"
conduit_dockflare_access_group: ""

# homepage
conduit_homepage_group: "Apps"
conduit_homepage_icon: "conduit.png"
conduit_homepage_href: "http://{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}:{{ conduit_port_http }}"
conduit_homepage_showstats: "false"

# repliqate
conduit_repliqate_enabled: "false"
conduit_repliqate_engine: "restic"
conduit_repliqate_schedule: "@daily 3am"
conduit_repliqate_backup_id: "{{ conduit_container_name }}"
conduit_repliqate_retention: "30d"

# watchtower
conduit_watchtower_enable: "false"
