---
- name: Start {{ ansible_nas_app_name }}
  block:
    - name: Create {{ ansible_nas_app_name }} Directories
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        # mode: 0755
      with_items:
        - "{{ tautulli_data_directory }}"
        - "{{ tautulli_data_directory }}/config"
        - "{{ plex_data_directory }}/logs"

    - name: Create {{ ansible_nas_app_name }} Container
      community.docker.docker_container:
        container_default_behavior: "compatibility"
        name: "{{ tautulli_container_name }}"
        hostname: "{{ tautulli_container_name }}"
        image: "{{ tautulli_image_name }}:{{ tautulli_image_version }}"
        pull: true
        volumes:
          - "{{ tautulli_data_directory }}/config:/config:rw"
          - "{{ plex_data_directory }}/logs:/logs:ro"
        ports:
          - "{{ tautulli_port }}:8181"
        env:
          DOCKER_MODS: "{{ tautulli_env_docker_mods }}"
          TP_DOMAIN: "{{ tautulli_env_docker_mods_tp_domain }}"
          TP_THEME: "{{ tautulli_env_docker_mods_tp_theme }}"
          TP_COMMUNITY_THEME: "{{ tautulli_env_docker_mods_tp_community_theme }}"
          TP_ADDON: "{{ tautulli_env_docker_mods_tp_addon }}"
          PUID: "{{ tautulli_user_id }}"
          PGID: "{{ tautulli_group_id }}"
          TZ: "{{ ansible_nas_timezone }}"
        labels:
          autoheal: "{{ tautulli_autoheal }}"
          com.centurylinklabs.watchtower.enable: "{{ tautulli_watchtower_enable }}"
          dockflare.enable: "{{ tautulli_dockflare_tunnel }}"
          dockflare.access.group: "{{ tautulli_dockflare_access_group }}"
          dockflare.hostname: "{{ tautulli_hostname }}.{{ ansible_nas_domain }}"
          dockflare.service: "http://{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}:{{ tautulli_port }}"
          homepage.name: "{{ ansible_nas_app_name }}"
          homepage.group: "{{ tautulli_homepage_group }}"
          homepage.icon: "{{ tautulli_homepage_icon }}"
          homepage.href: "{{ tautulli_homepage_href }}"
          homepage.description: "{{ 'a python based web application for monitoring, analytics and notifications for Plex Media Server' if homepage_show_description else omit }}"
          homepage.server: "my-docker"
          homepage.container: "{{ tautulli_container_name }}"
          homepage.showStats: "{{ tautulli_homepage_showstats }}"
          homepage.siteMonitor: "http://{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}:{{ tautulli_port }}"
          traefik.enable: "{{ tautulli_available_externally | string }}"
          traefik.http.routers.tautulli.rule: "Host(`{{ tautulli_hostname }}.{{ ansible_nas_domain }}`)"
          traefik.http.routers.tautulli.tls.certresolver: "letsencrypt"
          traefik.http.routers.tautulli.tls.domains[0].main: "{{ ansible_nas_domain }}"
          traefik.http.routers.tautulli.tls.domains[0].sans: "*.{{ ansible_nas_domain }}"
          traefik.http.routers.frontend.middlewares: "{{ tautulli_hostname }}"
          traefik.http.routers.tautulli.middlewares: "{{ tautulli_hostname }}@docker"
          traefik.http.middlewares.tautulli.IPAllowList.sourcerange: "{{ tautulli_traefik_whitelist }}"
          traefik.http.services.tautulli.loadbalancer.server.port: "8181"
          wud.tag.include: '^\d+\.\d+\.\d+.*$'
          wud.tag.transform.type: "semver"
          wud.link.template: "https://lscr.io/linuxserver/tautulli"
        cpu_shares: "{{ tautulli_cpu_shares }}"
        memory: "{{ tautulli_memory }}"
        restart_policy: unless-stopped

    - name: Access {{ ansible_nas_app_name }} at
      ansible.builtin.debug:
        msg: >-
              {{
                ['http://' + hostvars[inventory_hostname]['ansible_default_ipv4']['address'] + ':' + (tautulli_port | string)] +
                (['https://' + tautulli_hostname + '.' + ansible_nas_domain] if (tautulli_available_externally is true or tautulli_dockflare_tunnel is true) else [])
              }}
  when: tautulli_enabled is true

- name: Stop {{ ansible_nas_app_name }}
  block:
    - name: Stop {{ ansible_nas_app_name }} Container
      community.docker.docker_container:
        name: "{{ tautulli_container_name }}"
        state: absent
  when: tautulli_enabled is false

- name: Data Archive {{ ansible_nas_app_name }}
  block:
    - name: Check for {{ ansible_nas_app_name }} Data Directory
      stat:
        path: "{{ tautulli_data_directory }}"
      register: dir_stat

    - name: Archive {{ ansible_nas_app_name }} Data Directory
      ansible.builtin.archive:
        path: "{{ tautulli_data_directory }}"
        dest: "{{ docker_home }}/{{ ansible_nas_app_name | lower }}.zip"
        force_archive: true
        format: zip
        owner: ansible-nas
        group: ansible-nas
        mode: u=rw,g=rw
        remove: true
      when: dir_stat.stat.exists
  when: tautulli_enabled is false and archive_app_data_enabled is true
