---
# ANE
gpu_hot_proper_name: "GPU Hot"
gpu_hot_enabled: false
gpu_hot_traefik_enabled: false
gpu_hot_traefik_whitelist: "{{ lan }}"

# docker
gpu_hot_container_name: "gpu-hot"
gpu_hot_image_name: "ghcr.io/psalias2006/gpu-hot"
gpu_hot_image_tag: "latest"

# network
gpu_hot_hostname: "gpuhot"
gpu_hot_port_http: "1312"

# specs
gpu_hot_cpu_shares: 1024
gpu_hot_memory: "256M"
gpu_hot_memory_swap: -1

# app
gpu_hot_env_nvidia_visible_devices: "all" # Specific GPUs (default: all)
gpu_hot_env_nvidia_smi: "false" # Force nvidia-smi mode for all GPUs

# autoheal
gpu_hot_autoheal_enabled: false

# dockflare
gpu_hot_dockflare_enabled: false
gpu_hot_dockflare_access_group: ""

# homepage
gpu_hot_homepage_group: "Apps"
#gpu_hot_homepage_icon: "gpu-hot.png"
#gpu_hot_homepage_icon: "🔥"
gpu_hot_homepage_icon: "https://1000logos.net/wp-content/uploads/2023/10/Meaning-of-the-Fire-Emoji-768x432.png"
gpu_hot_homepage_href: "http://{{ hostvars[inventory_hostname]['ansible_facts']['default_ipv4']['address'] }}:{{ gpu_hot_port_http }}"
gpu_hot_homepage_showstats: false

# tinyauth
gpu_hot_tinyauth_enabled: false

# watchtower
gpu_hot_watchtower_enabled: false
