---
# ANE
ansible_nas_app_name: "GPU Hot"
gpuhot_enabled: false
gpuhot_traefik_enabled: false
gpuhot_traefik_whitelist: "{{ lan }}"

# docker
gpuhot_container_name: "gpu-hot"
gpuhot_image_name: "ghcr.io/psalias2006/gpu-hot"
gpuhot_image_tag: "latest"

# network
gpuhot_hostname: "gpuhot"
gpuhot_port_http: "1312"

# specs
gpuhot_cpu_shares: 1024
gpuhot_memory: "256M"
gpuhot_memory_swap: -1

# app
gpuhot_env_nvidia_visible_devices: "all" # Specific GPUs (default: all)
gpuhot_env_nvidia_smi: "false" # Force nvidia-smi mode for all GPUs

# autoheal
gpuhot_autoheal_enabled: false

# dockflare
gpuhot_dockflare_enabled: false
gpuhot_dockflare_access_group: ""

# homepage
gpuhot_homepage_group: "Apps"
#gpuhot_homepage_icon: "gpu-hot.png"
#gpuhot_homepage_icon: "🔥"
gpuhot_homepage_icon: "https://1000logos.net/wp-content/uploads/2023/10/Meaning-of-the-Fire-Emoji-768x432.png"
gpuhot_homepage_href: "http://{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}:{{ gpuhot_port_http }}"
gpuhot_homepage_showstats: false

# tinyauth
gpuhot_tinyauth_enabled: false

# watchtower
gpuhot_watchtower_enabled: false
