---
# WIP - traefik headers need work
- name: Start {{ ansible_nas_app_name }}
  block:
    - name: Create {{ ansible_nas_app_name }} Directories
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
      with_items:
        - "{{ kasm_data_directory }}"
        - "{{ kasm_data_directory }}/opt"
        - "{{ kasm_data_directory }}/profiles"

    - name: Set {{ ansible_nas_app_name }} FQDN var overrides
      ansible.builtin.set_fact:
        kasm_homepage_href: "https://{{ kasm_hostname }}.{{ ansible_nas_domain }}"
      when: kasm_traefik_enabled | bool or kasm_dockflare_enabled | bool

    - name: Create {{ ansible_nas_app_name }} Container
      community.docker.docker_container:
        container_default_behavior: "compatibility"
        name: "{{ kasm_container_name }}"
        hostname: "{{ kasm_container_name }}"
        image: "{{ kasm_image_name }}:{{ kasm_image_tag }}"
        pull: true
        network_mode: bridge
        volumes:
          - "{{ kasm_data_directory }}/opt:/opt"
          - "{{ kasm_data_directory }}/profiles:/profiles" #optional
          - "/dev/input:/dev/input" #optional
          - "/run/udev/data:/run/udev/data" #optional
        device_requests: "{{
          [{'driver': 'nvidia', 'count': -1, 'capabilities': ['gpu']}]
          if nvidia_runtime_enabled | default(false) | bool else omit
        }}"
        devices: >-
          {%- set dev_list = (app_devices | default([])) -%}
          {%- if intel_igpu_enabled | default(false) | bool or amd_gpu_enabled | default(false) | bool -%}
            {%- set _ = dev_list.append('/dev/dri:/dev/dri') -%}
          {%- endif -%}
          {%- if amd_gpu_enabled | default(false) | bool and ansible_nas_app_name | lower is search('ollama|localai') -%}
            {%- set _ = dev_list.append('/dev/kfd:/dev/kfd') -%}
          {%- endif -%}
          {{ dev_list if dev_list | length > 0 else omit }}
        group_add: "{{ ['render', 'video'] if (amd_gpu_enabled | default(false) | bool or intel_igpu_enabled | default(false) | bool) else omit }}"
        runtime: "{{ 'nvidia' if nvidia_runtime_enabled | default(false) | bool else omit }}"
        env:
          KASM_PORT: "{{ kasm_port_https }}"
          DOCKER_HUB_USERNAME: "{{ kasm_docker_hub_username }}" #optional
          DOCKER_HUB_PASSWORD: "{{ kasm_docker_hub_password }}" #optional
          DOCKER_MTU: "1500" #optional
          DOCKER_MODS: "{{ kasm_env_docker_mods }}"
          INSTALL_PACKAGES: "{{ kasm_env_docker_mods_install_packages }}"
          INSTALL_PIP_PACKAGES: "{{ kasm_env_docker_mods_install_pip_packages}}"
          TZ: "{{ ansible_nas_timezone }}"
        ports:
          - "{{ kasm_port_https }}:{{ kasm_port_https }}" # user access
          - "{{ kasm_port_install_https }}:3000" # admin/installation
        privileged: true
#       security_opts: ["apparmor=rootlesskit"] #optional
        labels:
          autoheal: "{{ kasm_autoheal_enabled | ternary('true', 'false') }}"
          com.centurylinklabs.watchtower.enable: "{{ kasm_watchtower_enabled | ternary('true', 'false') }}"
          dockflare.enable: "{{ kasm_dockflare_enabled | ternary('true', 'false') }}"
          dockflare.access.group: "{{ kasm_dockflare_access_group }}"
          dockflare.hostname: "{{ kasm_hostname }}.{{ ansible_nas_domain }}"
          dockflare.service: "https://{{ hostvars[inventory_hostname]['ansible_facts']['default_ipv4']['address'] }}:{{ kasm_port_https }}"
          homepage.name: "{{ ansible_nas_app_name }}"
          homepage.group: "{{ kasm_homepage_group }}"
          homepage.icon: "{{ kasm_homepage_icon }}"
          homepage.href: "{{ kasm_homepage_href }}"
          homepage.siteMonitor: "https://{{ hostvars[inventory_hostname]['ansible_facts']['default_ipv4']['address'] }}:{{ kasm_port_https }}"
          homepage.description: "{{ 'Kasm⁠ Workspaces is a docker container streaming platform for delivering browser-based access to desktops, applications, and web services.' if homepage_show_description else omit }}"
          homepage.server: "my-docker"
          homepage.container: "{{ kasm_container_name }}"
          homepage.showStats: "{{ kasm_homepage_showstats | ternary('true', 'false') }}"
          repliqate.enabled: "{{ kasm_repliqate_enabled | ternary('true', 'false') }}"
          repliqate.engine: "{{ kasm_repliqate_engine }}"
          repliqate.schedule: "{{ kasm_repliqate_schedule }}"
          repliqate.backup_id: "{{ kasm_repliqate_backup_id }}"
          repliqate.retention: "{{ kasm_repliqate_retention }}"
          traefik.enable: "{{ kasm_traefik_enabled | ternary('true', 'false') }}"
          traefik.http.routers.kasm-main.rule: "Host(`{{ kasm_hostname }}.{{ ansible_nas_domain }}`)"
          traefik.http.routers.kasm-main.entrypoints: "websecure"
          traefik.http.routers.kasm-main.tls.certresolver: "letsencrypt"
          traefik.http.routers.kasm-main.tls.domains[0].main: "{{ ansible_nas_domain }}"
          traefik.http.routers.kasm-main.tls.domains[0].sans: "*.{{ ansible_nas_domain }}"
          traefik.http.routers.kasm-main.middlewares: "kasm-whitelist,tinyauth-auth@docker,kasm-headers"
          traefik.http.routers.kasm-main.service: "kasm-main-svc"
          traefik.http.routers.kasm-admin.rule: "Host(`{{ kasm_hostname }}-admin.{{ ansible_nas_domain }}`)"
          traefik.http.routers.kasm-admin.entrypoints: "websecure"
          traefik.http.routers.kasm-admin.tls.certresolver: "letsencrypt"
          traefik.http.routers.kasm-admin.tls.domains[0].main: "{{ ansible_nas_domain }}"
          traefik.http.routers.kasm-admin.tls.domains[0].sans: "*.{{ ansible_nas_domain }}"
          traefik.http.routers.kasm-admin.middlewares: "kasm-whitelist,tinyauth-auth@docker,kasm-headers"
          traefik.http.routers.kasm-admin.service: "kasm-admin-svc"
          traefik.http.services.kasm-main-svc.loadbalancer.server.port: "{{ kasm_port_https }}"
          traefik.http.services.kasm-main-svc.loadbalancer.server.scheme: "https"
          traefik.http.services.kasm-main-svc.loadbalancer.serversTransport: "ignore-cert@file"
          traefik.http.services.kasm-admin-svc.loadbalancer.server.port: "3000"
          traefik.http.services.kasm-admin-svc.loadbalancer.server.scheme: "https"
          traefik.http.services.kasm-admin-svc.loadbalancer.serversTransport: "ignore-cert@file"
          traefik.http.middlewares.kasm-whitelist.ipallowlist.sourcerange: "{{ kasm_traefik_whitelist }}"
          traefik.http.middlewares.kasm-headers.headers.customrequestheaders.X-Forwarded-Proto: "https"
          traefik.http.middlewares.kasm-headers.headers.accessControlAllowOriginList: "*"
          wud.tag.include: '^\d+\.\d+\.\d+.*$'
          wud.tag.transform.type: "semver"
          wud.link.template: "https://lscr.io/linuxserver/kasm"
        cpu_shares: "{{ kasm_cpu_shares }}"
        memory: "{{ kasm_memory }}"
        memory_swap: "{{ kasm_memory_swap }}"
        restart_policy: unless-stopped

    - name: Access {{ ansible_nas_app_name }} at
      ansible.builtin.debug:
        msg: >-
          {{
            ['https://' + ansible_facts['default_ipv4']['address'] + ':' + (kasm_port_https | string)] +
            (['https://' + kasm_hostname + '.' + ansible_nas_domain] if (kasm_traefik_enabled is true or kasm_dockflare_enabled is true) else []) +
            ['https://' + ansible_facts['default_ipv4']['address'] + ':' + (kasm_port_install_https | string) + ' (Kasm Install)'] +
            (['https://' + kasm_hostname + '-admin.' + ansible_nas_domain + ' (Kasm Install)'] if (kasm_traefik_enabled is true or kasm_dockflare_enabled is true) else [])
          }}
  when: kasm_enabled is true

- name: Stop {{ ansible_nas_app_name }}
  block:
    - name: Stop {{ ansible_nas_app_name }} Container
      community.docker.docker_container:
        name: "{{ kasm_container_name }}"
        state: absent
  when: kasm_enabled is false

- name: Data Archive {{ ansible_nas_app_name }}
  include_role:
    name: ansible-nas-archive
  vars:
    target_data_dir: "{{ kasm_data_directory }}"
  when:
    - archive_app_data_enabled is true
    - kasm_enabled is false