---
- name: Start {{ ansible_nas_app_name }}
  block:
    - name: Create {{ ansible_nas_app_name }} Directories
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        # mode: 0755
      with_items:
        - "{{ navidrome_data_directory }}/data"
        - "{{ navidrome_data_directory }}/playlists"

    - name: Create {{ ansible_nas_app_name }} Container
      community.docker.docker_container:
        container_default_behavior: "compatibility"
        name: "{{ navidrome_container_name }}"
        hostname: "{{ navidrome_container_name }}"
        image: "{{ navidrome_image_name }}:{{ navidrome_image_version }}"
        pull: true
        cpu_shares: "{{ navidrome_cpu_shares }}"
        volumes:
          - "{{ navidrome_data_directory }}/data:/navidrome/data:rw"
          - "{{ navidrome_music_directory }}:/navidrome/music:rw"
        ports:
          - "{{ navidrome_port }}:4533"
        env:
          ND_MUSICFOLDER: "/navidrome/music"
          ND_DATAFOLDER: "/navidrome/data"
          ND_SCANSCHEDULE: "{{ navidrome_scan_schedule }}"
          ND_LOGLEVEL: "{{ navidrome_log_level }}"
          ND_SESSIONTIMEOUT: "{{ navidrome_session_timeout }}"
        restart_policy: unless-stopped
        memory: "{{ navidrome_memory }}"
        labels:
          autoheal: "{{ navidrome_autoheal }}"
          com.centurylinklabs.watchtower.monitor-only: "{{ navidrome_watchtower_monitor_only }}"
          traefik.enable: "{{ navidrome_available_externally | string }}"
          traefik.http.routers.navidrome.rule: "Host(`{{ navidrome_hostname }}.{{ ansible_nas_domain }}`)"
          traefik.http.routers.navidrome.tls.certresolver: "letsencrypt"
          traefik.http.routers.navidrome.tls.domains[0].main: "{{ ansible_nas_domain }}"
          traefik.http.routers.navidrome.tls.domains[0].sans: "*.{{ ansible_nas_domain }}"
          traefik.http.routers.frontend.middlewares: "{{ navidrome_hostname }}"
          traefik.http.routers.navidrome.middlewares: "{{ navidrome_hostname }}@docker"
          traefik.http.middlewares.navidrome.IPAllowList.sourcerange: "{{ navidrome_traefik_whitelist }}"
          traefik.http.services.navidrome.loadbalancer.server.port: "4533"
  when: navidrome_enabled is true

- name: Stop {{ ansible_nas_app_name }}
  block:
    - name: Stop {{ ansible_nas_app_name }} Container
      community.docker.docker_container:
        name: "{{ navidrome_container_name }}"
        state: absent
  when: navidrome_enabled is false

- name: Data Archive {{ ansible_nas_app_name }}
  block:
    - name: Check for {{ ansible_nas_app_name }} Data Directory
      stat:
        path: "{{ navidrome_data_directory }}"
      register: dir_stat

    - name: Archive {{ ansible_nas_app_name }} Data Directory
      ansible.builtin.archive:
        path: "{{ navidrome_data_directory }}"
        dest: "{{ docker_home }}/{{ ansible_nas_app_name | lower }}.zip"
        force_archive: true
        format: zip
        owner: ansible-nas
        group: ansible-nas
        mode: u=rw,g=rw
        remove: true
      when: dir_stat.stat.exists
  when: navidrome_enabled is false and archive_app_data_enabled is true
