---
- name: Verify
  hosts: all
  gather_facts: false
  tasks:
    - ansible.builtin.include_vars:
        file: ../../defaults/main.yml

    - name: Try and stop and remove {{ activepieces_proper_name }}
      community.docker.docker_container:
        name: "{{ activepieces_container_name }}"
        state: absent
      register: result

    - name: Try and stop and remove {{ activepieces_proper_name }} DB
      community.docker.docker_container:
        name: "{{ activepieces_db_container_name }}"
        state: absent
      register: result_db

    - name: Try and stop and remove {{ activepieces_proper_name }} Redis
      community.docker.docker_container:
        name: "{{ activepieces_redis_container_name }}"
        state: absent
      register: result_redis

    - name: Check if {{ activepieces_proper_name }} is stopped
      ansible.builtin.assert:
        that:
          - not result.changed
          - not result_db.changed
          - not result_redis.changed
