---
  # NOTE: deprecated / retired
- name: Start {{ ansible_nas_app_name }}
  block:
    - name: Create {{ ansible_nas_app_name }} Directories
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
      with_items:
        - "{{ readarr_data_directory }}"
        - "{{ readarr_data_directory }}/config"
        - "{{ readarr_books_directory }}"
        - "{{ readarr_download_directory}}"

    - name: Create {{ ansible_nas_app_name }} Container
      community.docker.docker_container:
        container_default_behavior: "compatibility"
        name: "{{ readarr_container_name }}"
        hostname: "{{ readarr_container_name }}"
        image: "{{ readarr_image_name }}:{{ readarr_image_version }}"
        pull: true
        volumes:
          - "{{ readarr_data_directory }}/config:/config:rw"
          - "{{ readarr_books_directory }}:/books:rw"
          - "{{ readarr_download_directory }}:/downloads:rw"
        env:
          DOCKER_MODS: "{{ readarr_env_docker_mods }}"
          INSTALL_PACKAGES: "{{ readarr_env_docker_mods_install_packages }}"
          INSTALL_PIP_PACKAGES: "{{ readarr_env_docker_mods_install_pip_packages}}"
          TP_DOMAIN: "{{ readarr_env_docker_mods_domain }}"
          TP_THEME: "{{ readarr_env_docker_mods_tp_theme }}"
          TP_COMMUNITY_THEME: "{{ readarr_env_docker_mods_community_theme }}"
          TP_ADDON: "{{ readarr_env_docker_mods_addon }}"
          PUID: "{{ readarr_user_id }}"
          PGID: "{{ readarr_group_id }}"
          TZ: "{{ ansible_nas_timezone }}"
        ports:
          - "{{ readarr_port_http }}:8787"
        labels:
          autoheal: "{{ readarr_autoheal | string }}"
          com.centurylinklabs.watchtower.enable: "{{ readarr_watchtower_enabled| string }}"
          dockflare.enable: "{{ readarr_dockflare_enabled | string }}"
          dockflare.access.group: "{{ readarr_dockflare_access_group }}"
          dockflare.hostname: "{{ readarr_hostname }}.{{ ansible_nas_domain }}"
          dockflare.service: "http://{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}:{{ readarr_port_http }}"
          homepage.name: "{{ ansible_nas_app_name }}"
          homepage.group: "{{ readarr_homepage_group }}"
          homepage.icon: "{{ readarr_homepage_icon }}"
          homepage.href: "{{ readarr_homepage_href }}"
          homepage.siteMonitor: "http://{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}:{{ readarr_port_http }}"
          homepage.description: "{{ 'Book Manager and Automation (Sonarr for Ebooks)' if homepage_show_description else omit }}"
          homepage.server: "my-docker"
          homepage.container: "{{ readarr_container_name }}"
          homepage.showStats: "{{ readarr_homepage_showstats | string }}"
          homepage.widget.type: "readarr"
          homepage.widget.url: "http://{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}:{{ readarr_port_http }}"
          homepage.widget.key: "{{ readarr_homepage_widget_key }}"
          repliqate.enabled: "{{ readarr_repliqate_enabled | string }}"
          repliqate.engine: "{{ readarr_repliqate_engine }}"
          repliqate.schedule: "{{ readarr_repliqate_schedule }}"
          repliqate.backup_id: "{{ readarr_repliqate_backup_id }}"
          repliqate.retention: "{{ readarr_repliqate_retention }}"
          traefik.enable: "{{ readarr_available_externally | string }}"
          traefik.http.routers.readarr.rule: "Host(`{{ readarr_hostname }}.{{ ansible_nas_domain }}`)"
          traefik.http.routers.readarr.tls.certresolver: "letsencrypt"
          traefik.http.routers.readarr.tls.domains[0].main: "{{ ansible_nas_domain }}"
          traefik.http.routers.readarr.tls.domains[0].sans: "*.{{ ansible_nas_domain }}"
          traefik.http.routers.readarr.middlewares: "readarr@docker{{ ',tinyauth-auth@docker' if readarr_tinyauth_enabled | bool else '' }}"
          traefik.http.middlewares.readarr.IPAllowList.sourcerange: "{{ readarr_traefik_whitelist }}"
          traefik.http.services.readarr.loadbalancer.server.port: "8787"
          wud.watch.digest: "true"
          wud.link.template: "https://lscr.io/linuxserver/readarr"
        cpu_shares: "{{ readarr_cpu_shares }}"
        memory: "{{ readarr_memory }}"
        restart_policy: unless-stopped

    - name: Access {{ ansible_nas_app_name }} at
      ansible.builtin.debug:
        msg: >-
              {{
                ['http://' + hostvars[inventory_hostname]['ansible_default_ipv4']['address'] + ':' + (readarr_port_http | string)] +
                (['https://' + readarr_hostname + '.' + ansible_nas_domain] if (readarr_available_externally is true or readarr_dockflare_enabled is true) else [])
              }}
  when: readarr_enabled is true

- name: Stop {{ ansible_nas_app_name }}
  block:
    - name: Stop {{ ansible_nas_app_name }} Container
      community.docker.docker_container:
        name: "readarr"
        state: absent
  when: readarr_enabled is false

- name: Data Archive {{ ansible_nas_app_name }}
  include_role:
    name: ansible-nas-archive
  vars:
    target_data_dir: "{{ readarr_data_directory }}"
  when:
    - archive_app_data_enabled is true
    - readarr_enabled is false