---
- name: Start {{ ansible_nas_app_name }}
  block:
    - name: Create {{ ansible_nas_app_name }} Directories
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        owner: "{{ webtop_user_id }}"
        group: "{{ webtop_group_id }}"
      with_items:
        - "{{ webtop_data_directory }}"
        - "{{ webtop_data_directory }}/config"

    - name: Create {{ ansible_nas_app_name }} Container
      community.docker.docker_container:
        container_default_behavior: "compatibility"
        name: "{{ webtop_container_name }}"
        hostname: "{{ webtop_container_name }}"
        image: "{{ webtop_image_name }}:{{ webtop_image_tag }}"
        pull: true
        volumes:
          - "{{ webtop_data_directory }}/config:/config"
          - "/var/run/docker.sock:/var/run/docker.sock"
          - "/etc/timezone:/etc/timezone:ro"
        devices: >-
                  {{
                    (webtop_devices | default([])) + ['/dev/dri:/dev/dri']
                    if intel_igpu_enabled | default(false) | bool
                    else (webtop_devices | default(omit))
                  }}
        runtime: "{{ 'nvidia' if nvidia_runtime_enabled | bool else omit }}"
        device_requests: "{{
          [{'driver': 'nvidia', 'count': -1, 'capabilities': ['gpu']}]
          if nvidia_runtime_enabled | bool else omit
        }}"
        env:
          CUSTOM_USER: "{{ webtop_env_custom_user }}"
          PASSWORD: "{{ webtop_env_password }}"
          CUSTOM_PORT: "{{ webtop_port_http }}"
          CUSTOM_HTTPS_PORT: "{{ webtop_port_https }}"
          CUSTOM_WS_PORT: "8082"
          DISABLE_OPEN_TOOLS: "{{ webtop_env_disable_open_tools }}"
          DISABLE_SUDO: "{{ webtop_env_disable_sudo }}"
          DISABLE_TERMINALS: "{{ webtop_env_disable_terminals }}"
          DISABLE_CLOSE_BUTTON: "{{ webtop_env_disable_close_button }}"
          DISABLE_MOUSE_BUTTONS: "{{ webtop_env_disable_mouse_buttons }}"
          HARDEN_KEYBINDS: "{{ webtop_env_disable_harden_keybinds }}"
          RESTART_APP: "{{ webtop_env_disable_restart_app }}"
          TITLE: "{{ ansible_nas_app_name }}"
          DOCKER_MODS: "{{ webtop_env_docker_mods }}"
          INSTALL_PACKAGES: "{{ webtop_env_docker_mods_install_packages }}"
          INSTALL_PIP_PACKAGES: "{{ webtop_env_docker_mods_install_pip_packages}}"
          KEYBOARD: "{{ webtop_env_keyboard }}"
          PUID: "{{ webtop_user_id }}"
          PGID: "{{ webtop_group_id }}"
          UMASK: "{{ webtop_umask }}"
          SUBFOLDER: "{{ webtop_env_subfolder }}"
          TZ: "{{ ansible_nas_timezone }}"
        ports:
          - "{{ webtop_port_http }}:{{ webtop_port_http }}"
          - "{{ webtop_port_https }}:{{ webtop_port_https }}"
        labels:
          autoheal: "{{ webtop_autoheal_enabled | ternary('true', 'false') }}"
          com.centurylinklabs.watchtower.enable: "{{ webtop_watchtower_enabled | ternary('true', 'false') }}"
          dockflare.enable: "{{ webtop_dockflare_enabled | ternary('true', 'false') }}"
          dockflare.access.group: "{{ webtop_dockflare_access_group }}"
          dockflare.hostname: "{{ webtop_hostname }}.{{ ansible_nas_domain }}"
          dockflare.service: "https://{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}:{{ webtop_port_https }}"
          homepage.name: "{{ ansible_nas_app_name }}"
          homepage.group: "{{ webtop_homepage_group }}"
          homepage.icon: "{{ webtop_homepage_icon }}"
          homepage.href: "{{ webtop_homepage_href }}"
          homepage.siteMonitor: "https://{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}:{{ webtop_port_https }}"
          homepage.description: "{{ 'Alpine, Ubuntu, Fedora, and Arch based containers containing full desktop environments in officially supported flavors' if homepage_show_description else omit }}"
          homepage.server: "my-docker"
          homepage.container: "{{ webtop_container_name }}"
          homepage.showStats: "{{ webtop_homepage_showstats | ternary('true', 'false') }}"
          repliqate.enabled: "{{ webtop_repliqate_enabled | ternary('true', 'false') }}"
          repliqate.engine: "{{ webtop_repliqate_engine }}"
          repliqate.schedule: "{{ webtop_repliqate_schedule }}"
          repliqate.backup_id: "{{ webtop_repliqate_backup_id }}"
          repliqate.retention: "{{ webtop_repliqate_retention }}"
          traefik.enable: "{{ webtop_traefik_enabled | ternary('true', 'false') }}"
          traefik.http.routers.webtop.rule: "Host(`{{ webtop_hostname }}.{{ ansible_nas_domain }}`)"
          traefik.http.routers.webtop.tls.certresolver: "letsencrypt"
          traefik.http.routers.webtop.tls.domains[0].main: "{{ ansible_nas_domain }}"
          traefik.http.routers.webtop.tls.domains[0].sans: "*.{{ ansible_nas_domain }}"
          traefik.http.routers.webtop.middlewares: "webtop@docker{{ ',tinyauth-auth@docker' if webtop_tinyauth_enabled | bool else '' }}"
          traefik.http.middlewares.webtop.IPAllowList.sourcerange: "{{ webtop_traefik_whitelist }}"
          traefik.http.services.webtop.loadbalancer.server.port: "{{ webtop_port_http }}"
          wud.watch.digest: "true"
          wud.link.template: "lscr.io/linuxserver/webtop"
        cpu_shares: "{{ webtop_cpu_shares }}"
        memory: "{{ webtop_memory }}"
        shm_size: "1GB"
        restart_policy: unless-stopped

    - name: Access {{ ansible_nas_app_name }} at
      ansible.builtin.debug:
        msg: >-
          {{
            [
              'https://' ~ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] ~ ':' ~ webtop_port_https
            ] + (
              ['https://' ~ webtop_hostname ~ '.' ~ ansible_nas_domain]
              if (webtop_traefik_enabled is true or webtop_dockflare_enabled is true) else []
            )
          }}
  when: webtop_enabled is true

- name: Stop {{ ansible_nas_app_name }}
  block:
    - name: Stop {{ ansible_nas_app_name }} Container
      community.docker.docker_container:
        name: "{{ webtop_container_name }}"
        state: absent
  when: webtop_enabled is false

- name: Data Archive {{ ansible_nas_app_name }}
  include_role:
    name: ansible-nas-archive
  vars:
    target_data_dir: "{{ webtop_data_directory }}"
  when:
    - archive_app_data_enabled is true
    - webtop_enabled is false