---
- name: Start {{ ansible_nas_app_name }}
  block:
    - name: Create {{ ansible_nas_app_name }} Directories
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
      with_items:
        - "{{ webtop_data_directory }}"
        - "{{ webtop_data_directory }}/config"

    - name: Create {{ ansible_nas_app_name }} Container
      community.docker.docker_container:
        container_default_behavior: "compatibility"
        name: "{{ webtop_container_name }}"
        hostname: "{{ webtop_container_name }}"
        image: "{{ webtop_image_name }}:{{ webtop_image_tag }}"
        pull: true
        volumes:
          - "{{ webtop_data_directory }}/config:/config"
          - "/var/run/docker.sock:/var/run/docker.sock" #optional
        env:
          DOCKER_MODS: "{{ webtop_env_docker_mods }}"
          INSTALL_PACKAGES: "{{ webtop_env_docker_mods_install_packages }}"
          INSTALL_PIP_PACKAGES: "{{ webtop_env_docker_mods_install_pip_packages}}"
          KEYBOARD: "{{ webtop_env_keyboard }}"
          PUID: "{{ webtop_user_id }}"
          PGID: "{{ webtop_group_id }}"
          SUBFOLDER: "{{ webtop_env_subfolder }}"
          TZ: "{{ ansible_nas_timezone }}"
        ports:
          - "{{ webtop_port_http }}:3001"
        security_opts:
          - seccomp:unconfined          #optional
        labels:
          autoheal: "{{ webtop_autoheal }}"
          com.centurylinklabs.watchtower.enable: "{{ webtop_watchtower_enable }}"
          dockflare.enable: "{{ webtop_dockflare_tunnel }}"
          dockflare.access.group: "{{ webtop_dockflare_access_group }}"
          dockflare.hostname: "{{ webtop_hostname }}.{{ ansible_nas_domain }}"
          dockflare.service: "http://{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}:{{ webtop_port_http }}"
          homepage.name: "{{ ansible_nas_app_name }}"
          homepage.group: "{{ webtop_homepage_group }}"
          homepage.icon: "{{ webtop_homepage_icon }}"
          homepage.href: "{{ webtop_homepage_href }}"
          homepage.siteMonitor: "http://{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}:{{ webtop_port_http }}"
          homepage.description: "{{ 'Ubuntu, Alpine, Arch, and Fedora based Webtop images, Linux in a web browser supporting popular desktop environments.' if homepage_show_description else omit }}"
          homepage.server: "my-docker"
          homepage.container: "{{ webtop_container_name }}"
          homepage.showStats: "{{ webtop_homepage_showstats }}"
          repliqate.enabled: "{{ webtop_repliqate_enabled }}"
          repliqate.engine: "{{ webtop_repliqate_engine }}"
          repliqate.schedule: "{{ webtop_repliqate_schedule }}"
          repliqate.backup_id: "{{ webtop_repliqate_backup_id }}"
          repliqate.retention: "{{ webtop_repliqate_retention }}"
          traefik.enable: "{{ webtop_available_externally | string }}"
          traefik.http.routers.webtop.rule: "Host(`{{ webtop_hostname }}.{{ ansible_nas_domain }}`)"
          traefik.http.routers.webtop.tls.certresolver: "letsencrypt"
          traefik.http.routers.webtop.tls.domains[0].main: "{{ ansible_nas_domain }}"
          traefik.http.routers.webtop.tls.domains[0].sans: "*.{{ ansible_nas_domain }}"
          traefik.http.routers.frontend.middlewares: "{{ webtop_hostname }}"
          traefik.http.routers.webtop.middlewares: "{{ webtop_hostname }}@docker"
          traefik.http.middlewares.webtop.IPAllowList.sourcerange: "{{ webtop_traefik_whitelist }}"
          traefik.http.services.webtop.loadbalancer.server.port: "3001"
          wud.watch.digest: "true"
          wud.link.template: "lscr.io/linuxserver/webtop"
        cpu_shares: "{{ webtop_cpu_shares }}"
        memory: "{{ webtop_memory }}"
        restart_policy: unless-stopped

    - name: Access {{ ansible_nas_app_name }} at
      ansible.builtin.debug:
        msg: >-
              {{
                ['http://' + hostvars[inventory_hostname]['ansible_default_ipv4']['address'] + ':' + (webtop_port_http | string)] +
                (['https://' + webtop_hostname + '.' + ansible_nas_domain] if (webtop_available_externally is true or webtop_dockflare_tunnel is true) else [])
              }}
  when: webtop_enabled is true

- name: Stop {{ ansible_nas_app_name }}
  block:
    - name: Stop {{ ansible_nas_app_name }} Container
      community.docker.docker_container:
        name: "{{ webtop_container_name }}"
        state: absent
  when: webtop_enabled is false

- name: Data Archive {{ ansible_nas_app_name }}
  block:
    - name: Check for {{ ansible_nas_app_name }} Data Directory
      stat:
        path: "{{ webtop_data_directory }}"
      register: dir_stat

    - name: Archive {{ ansible_nas_app_name }} Data Directory
      ansible.builtin.archive:
        path: "{{ webtop_data_directory }}"
        dest: "{{ docker_home }}/{{ ansible_nas_app_name | lower }}.zip"
        force_archive: true
        format: zip
        owner: ansible-nas
        group: ansible-nas
        mode: u=rw,g=rw
        remove: true
      when: dir_stat.stat.exists
  when: webtop_enabled is false and archive_app_data_enabled is true
