---
# ANE
ansible_nas_app_name: "Dozzle Agent"
dozzle_agent_enabled: false

# network
dozzle_agent_hostname: "dozzle-agent"
dozzle_agent_port_http: "7007"

# docker
dozzle_agent_container_name: "dozzle-agent"
dozzle_agent_image_name: "ghcr.io/amir20/dozzle"
dozzle_agent_image_tag: "latest"

# specs
dozzle_agent_cpu_shares: 1024
dozzle_agent_memory: "256MB"
dozzle_agent_memory_swap: -1

# autoheal
dozzle_agent_autoheal: false

# homepage
dozzle_agent_homepage_group: "Misc"
dozzle_agent_homepage_icon: "dozzle.png"
dozzle_agent_homepage_showstats: false

# watchtower
dozzle_agent_watchtower_enabled: false