---
- name: Start {{ ansible_nas_app_name }}
  block:
    - name: Create {{ ansible_nas_app_name }} Directory
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
      with_items:
        - "{{ autobrr_data_directory }}"
        - "{{ autobrr_data_directory }}/config"

    - name: Create {{ ansible_nas_app_name }} Container
      community.docker.docker_container:
        container_default_behavior: "compatibility"
        name: "{{ autobrr_container_name }}"
        image: "{{ autobrr_image_name }}:{{ autobrr_image_tag }}"
        pull: true
        volumes:
          - "{{ autobrr_data_directory }}/config:/config"
        ports:
          - "{{ autobrr_port_http }}:7474"
        network_mode: "bridge"
        env:
          USER: "1000:1000"
          TZ: "{{ ansible_nas_timezone }}"
        labels:
          autoheal: "{{ autobrr_autoheal }}"
          com.centurylinklabs.watchtower.enable: "{{ autobrr_watchtower_enable }}"
          dockflare.enable: "{{ autobrr_dockflare_tunnel }}"
          dockflare.access.group: "{{ autobrr_dockflare_access_group }}"
          dockflare.hostname: "{{ autobrr_hostname }}.{{ ansible_nas_domain }}"
          dockflare.service: "http://{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}:{{ autobrr_port_http }}"
          homepage.name: "{{ ansible_nas_app_name }}"
          homepage.group: "{{ autobrr_homepage_group }}"
          homepage.href: "{{ autobrr_homepage_href }}"
          homepage.icon: "{{ autobrr_homepage_icon }}"
          homepage.siteMonitor: "http://{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}:{{ autobrr_port_http }}"
          homepage.description: "{{ 'Modern, easy to use download automation for torrents and usenet.' if homepage_show_description else omit }}"
          homepage.server: "my-docker"
          homepage.container: "{{ autobrr_container_name }}"
          homepage.showStats: "{{ autobrr_homepage_showstats }}"
          repliqate.enabled: "{{ autobrr_repliqate_enabled }}"
          repliqate.engine: "{{ autobrr_repliqate_engine }}"
          repliqate.schedule: "{{ autobrr_repliqate_schedule }}"
          repliqate.backup_id: "{{ autobrr_repliqate_backup_id }}"
          repliqate.retention: "{{ autobrr_repliqate_retention }}"
          traefik.enable: "{{ autobrr_available_externally | string }}"
          traefik.http.routers.autobrr.rule: "Host(`{{ autobrr_hostname }}.{{ ansible_nas_domain }}`)"
          traefik.http.routers.autobrr.tls.certresolver: "letsencrypt"
          traefik.http.routers.autobrr.tls.domains[0].main: "{{ ansible_nas_domain }}"
          traefik.http.routers.autobrr.tls.domains[0].sans: "*.{{ ansible_nas_domain }}"
          traefik.http.services.autobrr.loadbalancer.server.port: "7474"
          traefik.http.routers.frontend.middlewares: "{{ autobrr_hostname }}"
          traefik.http.routers.autobrr.middlewares: "{{ autobrr_hostname }}@docker"
          traefik.http.middlewares.autobrr.IPAllowList.sourcerange: "{{ autobrr_traefik_whitelist }}"
          wud.tag.include: '^\d+\.\d+\.\d+.*$'
          wud.tag.transform.type: "semver"
          wud.link.template: "https://github.com/autobrr/autobrr/releases"
        cpu_shares: "{{ autobrr_cpu_shares }}"
        memory: "{{ autobrr_memory }}"
        restart_policy: unless-stopped

    - name: Access {{ ansible_nas_app_name }} at
      ansible.builtin.debug:
        msg: >-
              {{
                ['http://' + hostvars[inventory_hostname]['ansible_default_ipv4']['address'] + ':' + (autobrr_port_http | string)] +
                (['https://' + autobrr_hostname + '.' + ansible_nas_domain] if (autobrr_available_externally is true or autobrr_dockflare_tunnel is true) else [])
              }}
  when: autobrr_enabled is true

- name: Stop {{ ansible_nas_app_name }}
  block:
    - name: Stop {{ ansible_nas_app_name }} Container
      community.docker.docker_container:
        name: "{{ autobrr_container_name }}"
        state: absent
  when: autobrr_enabled is false

- name: Data Archive {{ ansible_nas_app_name }}
  block:
    - name: Check for {{ ansible_nas_app_name }} Data Directory
      stat:
        path: "{{ autobrr_data_directory }}"
      register: dir_stat

    - name: Archive {{ ansible_nas_app_name }} Data Directory
      ansible.builtin.archive:
        path: "{{ autobrr_data_directory }}"
        dest: "{{ docker_home }}/{{ ansible_nas_app_name | lower }}.zip"
        force_archive: true
        format: zip
        owner: ansible-nas
        group: ansible-nas
        mode: u=rw,g=rw
        remove: true
      when: dir_stat.stat.exists
  when: autobrr_enabled is false and archive_app_data_enabled is true
