---
- name: Start {{ ansible_nas_app_name }}
  block:
    - name: Create {{ ansible_nas_app_name }} Directories
      file:
        path: "{{ item }}"
        state: directory
      with_items:
        - "{{ handbrake_data_directory }}"
        - "{{ handbrake_data_directory }}/config"
        - "{{ handbrake_output_directory }}"
        - "{{ handbrake_watch_directory }}"

    - name: Create {{ ansible_nas_app_name }} Container
      community.docker.docker_container:
        container_default_behavior: "compatibility"
        name: "{{ handbrake_container_name }}"
        hostname: "{{ handbrake_container_name }}"
        image: "{{ handbrake_image_name }}:{{ handbrake_image_tag }}"
        pull: true
        volumes:
          - "{{ handbrake_data_directory }}/config:/config:rw"
          - "{{ handbrake_storage_directory }}:/storage:ro"
          - "{{ handbrake_watch_directory }}:/watch:rw"
          - "{{ handbrake_output_directory }}:/output:rw"
        ports:
          - "{{ handbrake_port_http }}:5800"
        runtime: "{{ 'nvidia' if nvidia_runtime_enabled | bool else omit }}"
        device_requests: "{{
          [{'driver': 'nvidia', 'count': -1, 'capabilities': ['gpu']}]
          if nvidia_runtime_enabled | bool else omit
        }}"
        env:
          AUTOMATED_CONVERSION_PRESET: "{{ handbrake_automated_conversion_preset }}"
          AUTOMATED_CONVERSION_FORMAT: "{{ handbrake_automated_conversion_format }}"
          AUTOMATED_CONVERSION_KEEP_SOURCE: "{{ handbrake_automated_conversion_keep_source }}"
          AUTOMATED_CONVERSION_NON_VIDEO_FILE_EXTENSIONS: "{{ handbrake_automated_conversion_non_video_file_extensions }}"
          AUTOMATED_CONVERSION_NON_VIDEO_FILE_ACTION: "{{ handbrake_automated_conversion_non_video_file_action }}"
          AUTOMATED_CONVERSION_OUTPUT_SUBDIR: "{{ handbrake_automated_conversion_output_subdir }}"
          AUTOMATED_CONVERSION_SOURCE_STABLE_TIME: "{{ handbrake_automated_conversion_source_stable_time }}"
          AUTOMATED_CONVERSION_CHECK_INTERVAL: "{{ handbrake_automated_conversion_check_interval }}"
          AUTOMATED_CONVERSION_INSTALL_PKGS: "{{ handbrake_automated_conversion_install_pkgs }}"
          APP_NICENESS: "{{ handbrake_app_niceness }}"
          CLEAN_TMP_DIR: "{{ handbrake_clean_tmp_dir }}"
          DARK_MODE: " {{ handbrake_dark_mode }}"
          KEEP_APP_RUNNING: "{{ handbrake_keep_app_running }}"
          UMASK: "{{ handbrake_converted_files_umask }}"
          USER_ID: "{{ handbrake_user_id }}"
          GROUP_ID: "{{ handbrake_group_id }}"
          TZ: "{{ ansible_nas_timezone }}"
        labels:
          autoheal: "{{ handbrake_autoheal }}"
          com.centurylinklabs.watchtower.monitor-only: "{{ handbrake_watchtower_monitor_only }}"
          dockflare.enable: "{{ handbrake_dockflare_tunnel }}"
          dockflare.access.group: "{{ handbrake_dockflare_access_group }}"
          dockflare.hostname: "{{ handbrake_hostname }}.{{ ansible_nas_domain }}"
          dockflare.service: "http://{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}:{{ handbrake_port }}"
          homepage.name: "{{ ansible_nas_app_name }}"
          homepage.group: "{{ handbrake_homepage_group }}"
          homepage.href: "{{ handbrake_homepage_href }}"
          homepage.icon: "{{ handbrake_homepage_icon }}"
          homepage.siteMonitor: "http://{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}:{{ handbrake_port_http }}"
          homepage.description: "{{ 'an open-source, GPL-licensed, multiplatform video transcoder.' if homepage_show_description else omit }}"
          homepage.server: "my-docker"
          homepage.container: "{{ handbrake_container_name }}"
          homepage.showStats: "{{ handbrake_homepage_showStats }}"
          traefik.enable: "{{ handbrake_available_externally | string }}"
          traefik.http.routers.handbrake.rule: "Host(`{{ handbrake_hostname }}.{{ ansible_nas_domain }}`)"
          traefik.http.routers.handbrake.tls.certresolver: "letsencrypt"
          traefik.http.routers.handbrake.tls.domains[0].main: "{{ ansible_nas_domain }}"
          traefik.http.routers.handbrake.tls.domains[0].sans: "*.{{ ansible_nas_domain }}"
          traefik.http.routers.frontend.middlewares: "{{ handbrake_hostname }}"
          traefik.http.routers.handbrake.middlewares: "{{ handbrake_hostname }}@docker"
          traefik.http.middlewares.handbrake.IPAllowList.sourcerange: "{{ handbrake_traefik_whitelist }}"
          traefik.http.services.handbrake.loadbalancer.server.port: "5800"
          wud.tag.include: '^\d+\.\d+\.\d+$$'
          wud.link.template: "https://github.com/jlesage/docker-handbrake/releases/tag/$${major}.$${minor}.$${patch}"
        cpu_shares: "{{ handbrake_cpu_shares }}"
        memory: "{{ handbrake_memory }}"
        restart_policy: unless-stopped
  when: handbrake_enabled is true

- name: Stop {{ ansible_nas_app_name }}
  block:
    - name: Stop {{ ansible_nas_app_name }} Container
      community.docker.docker_container:
        name: "{{ handbrake_container_name }}"
        state: absent
  when: handbrake_enabled is false

- name: Data Archive {{ ansible_nas_app_name }}
  block:
    - name: Check for {{ ansible_nas_app_name }} Data Directory
      stat:
        path: "{{ handbrake_data_directory }}"
      register: dir_stat

    - name: Archive {{ ansible_nas_app_name }} Data Directory
      ansible.builtin.archive:
        path: "{{ handbrake_data_directory }}"
        dest: "{{ docker_home }}/{{ ansible_nas_app_name | lower }}.zip"
        force_archive: true
        format: zip
        owner: ansible-nas
        group: ansible-nas
        mode: u=rw,g=rw
        remove: true
      when: dir_stat.stat.exists
  when: handbrake_enabled is false and archive_app_data_enabled is true
