---
# ANE
ansible_nas_app_name: "What's Up Docker?"
wud_enabled: false
wud_available_externally: false
wud_traefik_whitelist: "{{ lan }}"

wud_data_directory: "{{ docker_home }}/wud"

# network
wud_port_http: "3013"
wud_hostname: "wud"

# app
wud_admin_username: "admin"
wud_admin_password: "topsecret"

# docker
wud_container_name: "wud"
wud_image_name: "getwud/wud"
wud_image_tag: "latest"
wud_cpu_shares: "1024"
wud_memory: "128m"

# app
wud_env_wud_registry_hub_public_login: ""    # your https://hub.docker.com account
wud_env_wud_registry_hub_public_password: "" # your https://hub.docker.com token

# autoheal
wud_autoheal: "false"

# dockflare
wud_dockflare_tunnel: "false"
wud_dockflare_access_group: ""

# homepage
wud_homepage_group: "Apps"
wud_homepage_icon: "whats-up-docker.png"
wud_homepage_href: "http://{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}:{{ wud_port_http }}"
wud_homepage_showstats: "false"

# watchtower
wud_watchtower_enable: "false"