---
- name: Start {{ ansible_nas_app_name }}
  block:
    - name: Create DokuWiki Directories
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
      with_items:
        - "{{ dokuwiki_data_directory }}/data"

    - name: Create {{ ansible_nas_app_name }} Container
      community.docker.docker_container:
        container_default_behavior: "compatibility"
        name: "{{ dokuwiki_container_name }}"
        hostname: "{{ dokuwiki_container_name }}"
        image: "{{ dokuwiki_image_name }}:{{ dokuwiki_image_tag }}"
        pull: true
        cpu_shares: "{{ dokuwiki_cpu_shares }}"
        volumes:
          - "{{ dokuwiki_data_directory }}:/config/dokuwiki/data:rw"
        ports:
          - "{{ dokuwiki_port }}:80"
        env:
          TZ: "{{ ansible_nas_timezone }}"
          PUID: "{{ dokuwiki_user_id }}"
          PGID: "{{ dokuwiki_group_id }}"
        restart_policy: unless-stopped
        memory: "{{ dokuwiki_memory }}"
        labels:
          autoheal: "{{ dokuwiki_autoheal }}"
          com.centurylinklabs.watchtower.monitor-only: "{{ dokuwiki_watchtower_monitor_only }}"
          traefik.enable: "{{ dokuwiki_available_externally | string }}"
          traefik.http.routers.dokuwiki.rule: "Host(`{{ dokuwiki_hostname }}.{{ ansible_nas_domain }}`)"
          traefik.http.routers.dokuwiki.tls.certresolver: "letsencrypt"
          traefik.http.routers.dokuwiki.tls.domains[0].main: "{{ ansible_nas_domain }}"
          traefik.http.routers.dokuwiki.tls.domains[0].sans: "*.{{ ansible_nas_domain }}"
          traefik.http.routers.frontend.middlewares: "{{ dokuwiki_hostname }}"
          traefik.http.routers.dokuwiki.middlewares: "{{ dokuwiki_hostname }}@docker"
          traefik.http.middlewares.dokuwiki.IPAllowList.sourcerange: "{{ dokuwiki_traefik_whitelist }}"
          traefik.http.services.dokuwiki.loadbalancer.server.port: "80"
  when: dokuwiki_enabled is true

- name: Stop {{ ansible_nas_app_name }}
  block:
    - name: Stop {{ ansible_nas_app_name }} Container
      community.docker.docker_container:
        name: "{{ dokuwiki_container_name }}"
        state: absent
  when: dokuwiki_enabled is false

- name: Data Archive {{ ansible_nas_app_name }}
  block:
    - name: Check for {{ ansible_nas_app_name }} Data Directory
      stat:
        path: "{{ dokuwiki_data_directory }}"
      register: dir_stat

    - name: Archive {{ ansible_nas_app_name }} Data Directory
      ansible.builtin.archive:
        path: "{{ dokuwiki_data_directory }}"
        dest: "{{ docker_home }}/{{ ansible_nas_app_name | lower }}.zip"
        force_archive: true
        format: zip
        owner: ansible-nas
        group: ansible-nas
        mode: u=rw,g=rw
        remove: true
      when: dir_stat.stat.exists
  when: dokuwiki_enabled is false and archive_app_data_enabled is true
