---
- name: Start {{ ansible_nas_app_name }}
  block:
    - name: Create {{ ansible_nas_app_name }} Container
      community.docker.docker_container:
        container_default_behavior: "compatibility"
        name: "{{ karaoke_forever_container_name }}"
        hostname: "{{ karaoke_forever_container_name }}"
        image: "{{ karaoke_forever_image_name }}:{{ karaoke_forever_image_tag }}"
        pull: true
        volumes:
          - "{{ karaoke_forever_cdgfiles }}:/cdgfiles:ro"
        ports:
          - "{{ karaoke_forever_port_http }}:80"
        env:
          TZ: "{{ ansible_nas_timezone }}"
        labels:
          autoheal: "{{ karaoke_forever_autoheal }}"
          com.centurylinklabs.watchtower.enable: "{{ karaoke_forever_watchtower_enable }}"
          dockflare.enable: "{{ karaoke_forever_dockflare_tunnel }}"
          dockflare.access.group: "{{ karaoke_forever_dockflare_access_group }}"
          dockflare.hostname: "{{ karaoke_forever_hostname }}.{{ ansible_nas_domain }}"
          dockflare.service: "http://{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}:{{ karaoke_forever_port_http }}"
          homepage.name: "{{ ansible_nas_app_name }}"
          homepage.group: "{{ karaoke_forever_homepage_group }}"
          homepage.icon: "{{ karaoke_forever_homepage_icon }}"
          homepage.href: "{{ karaoke_forever_homepage_href }}"
          homepage.siteMonitor: "http://{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}:{{ karaoke_forever_port_http }}"
          homepage.description: "{{ 'Open karaoke party system' if homepage_show_description else omit }}"
          homepage.server: "my-docker"
          homepage.container: "{{ karaoke_forever_container_name }}"
          homepage.showStats: "{{ karaoke_forever_homepage_showstats }}"
          repliqate.enabled: "{{ karaoke_forever_repliqate_enabled }}"
          repliqate.engine: "{{ karaoke_forever_repliqate_engine }}"
          repliqate.schedule: "{{ karaoke_forever_repliqate_schedule }}"
          repliqate.backup_id: "{{ karaoke_forever_repliqate_backup_id }}"
          repliqate.retention: "{{ karaoke_forever_repliqate_retention }}"
          traefik.enable: "{{ karaoke_forever_available_externally | string }}"
          traefik.http.routers.karaoke_forever.rule: "Host(`karaoke_forever.{{ ansible_nas_domain }}`)"
          traefik.http.routers.karaoke_forever.tls.certresolver: "letsencrypt"
          traefik.http.routers.karaoke_forever.tls.domains[0].main: "{{ ansible_nas_domain }}"
          traefik.http.routers.karaoke_forever.tls.domains[0].sans: "*.{{ ansible_nas_domain }}"
          traefik.http.routers.frontend.middlewares: "{{ karaoke_forever_hostname }}"
          traefik.http.routers.karaoke_forever.middlewares: "{{ karaoke_forever_hostname }}@docker"
          traefik.http.middlewares.karaoke_forever.IPAllowList.sourcerange: "{{ karaoke_forever_traefik_whitelist }}"
          traefik.http.services.karaoke_forever.loadbalancer.server.port: "80"
          wud.watch.digest: "true"
          wud.link.template: "https://hub.docker.com/r/david510c/karaoke-forever"
        cpu_shares: "{{ karaoke_forever_cpu_shares }}"
        memory: "{{ karaoke_forever_memory }}"
        restart_policy: unless-stopped

    - name: Access {{ ansible_nas_app_name }} at
      ansible.builtin.debug:
        msg: >-
              {{
                ['http://' + hostvars[inventory_hostname]['ansible_default_ipv4']['address'] + ':' + (karaoke_forever_port_http | string)] +
                (['https://' + karaoke_forever_hostname + '.' + ansible_nas_domain] if (karaoke_forever_available_externally is true or karaoke_forever_dockflare_tunnel is true) else [])
              }}
  when: karaoke_forever_enabled is true

- name: Stop {{ ansible_nas_app_name }}
  block:
    - name: Stop {{ ansible_nas_app_name }} Container
      community.docker.docker_container:
        name: "{{ karaoke_forever_container_name }}"
        state: absent
  when: karaoke_forever_enabled is false

# NOTE:
# probably not up-to-date with source
# https://github.com/bhj/KaraokeEternal
