---
- name: Start {{ ansible_nas_app_name }}
  block:
    - name: Create {{ ansible_nas_app_name }} Directories
      ansible.builtin.file:
        path: "{{ timemachine_data_directory }}"
        state: directory

    - name: Create {{ ansible_nas_app_name }} Container
      community.docker.docker_container:
        container_default_behavior: "compatibility"
        name: "{{ timemachine_container_name }}"
        hostname: "{{ timemachine_container_name }}"
        image: "{{ timemachine_image_name }}:{{ timemachine_image_version }}"
        pull: true
        ports:
          - "{{ timemachine_port }}:445"
        env:
          TMSIZE: "{{ timemachine_volume_size_limit }}"
          PASS: "{{ timemachine_password }}"
          SHARENAME: "{{ timemachine_share_name }}"
        volumes:
          - "{{ timemachine_data_directory }}/data:/backups"
        ulimits:
          - "nofile:1048576:1048576"
        network_mode: bridge
        labels:
          autoheal: "{{ timemachine_autoheal_enabled | ternary('true', 'false') }}"
          com.centurylinklabs.watchtower.enable: "{{ timemachine_watchtower_enabled | ternary('true', 'false') }}"
          dockflare.enable: "false"
          homepage.name: "{{ ansible_nas_app_name }}"
          homepage.group: "{{ timemachine_homepage_group }}"
          homepage.icon: "{{ timemachine_homepage_icon }}"
          homepage.description: "{{ 'Docker Container to run a TimeMachine Backup target' if homepage_show_description else omit }}"
          homepage.server: "my-docker"
          homepage.container: "{{ timemachine_container_name }}"
          homepage.showStats: "{{ timemachine_homepage_showstats | ternary('true', 'false') }}"
          repliqate.enabled: "{{ timemachine_repliqate_enabled | ternary('true', 'false') }}"
          repliqate.engine: "{{ timemachine_repliqate_engine }}"
          repliqate.schedule: "{{ timemachine_repliqate_schedule }}"
          repliqate.backup_id: "{{ timemachine_repliqate_backup_id }}"
          repliqate.retention: "{{ timemachine_repliqate_retention }}"
          traefik.enable: "false"
          wud.tag.include: '^v\d+\.\d+\.\d+-\d+$'
          wud.tag.transform.type: "semver"
          wud.link.template: "https://hub.docker.com/r/awlnx/samba-timemachine"
        cpu_shares: "{{ timemachine_cpu_shares }}"
        memory: "{{ timemachine_memory }}"
        memory_swap: "{{ timemachine_memory_swap }}"
        restart_policy: unless-stopped

    - name: Install avahi
      ansible.builtin.apt:
        name: "avahi-daemon"
        state: present
        update_cache: yes
      register: result
      until: result is succeeded

    - name: Setup {{ ansible_nas_app_name }} service for avahi
      ansible.builtin.template:
        src: timemachine.service
        dest: "/etc/avahi/services/timemachine.service"
      notify: reload avahi configuration
  when: timemachine_enabled is true

- name: Stop {{ ansible_nas_app_name }}
  block:
    - name: Stop {{ ansible_nas_app_name }} Container
      community.docker.docker_container:
        name: "{{ timemachine_container_name }}"
        state: absent

# NOTE: I don't use this and don't know the ramifications of adding it - not tested
#    - name: Remove avahi
#      ansible.builtin.apt:
#        name: "avahi-daemon"
#        state: absent
#        update_cache: yes
#      register: result
#      until: result is succeeded
  when: timemachine_enabled is false

- name: Data Archive {{ ansible_nas_app_name }}
  include_role:
    name: ansible-nas-archive
  vars:
    target_data_dir: "{{ timemachine_data_directory }}"
  when:
    - archive_app_data_enabled is true
    - timemachine_enabled is false