---
- name: Start {{ ansible_nas_app_name }}
  block:
    - name: Create {{ ansible_nas_app_name }} Directories
      ansible.builtin.file:
        path: "{{ timemachine_data_directory }}"
        state: directory

    - name: Create {{ ansible_nas_app_name }} Container
      community.docker.docker_container:
        name: "{{ timemachine_container_name }}"
        image: "{{ timemachine_image_name }}:{{ timemachine_image_version }}"
        pull: true
        ports:
          - "{{ timemachine_port }}:445"
        env:
          TMSIZE: "{{ timemachine_volume_size_limit }}"
          PASS: "{{ timemachine_password }}"
          SHARENAME: "{{ timemachine_share_name }}"
        volumes:
          - "{{ timemachine_data_directory }}/data:/backups"
        ulimits:
          - "nofile:1048576:1048576"
        network_mode: bridge
        restart_policy: unless-stopped
        cpu_shares: "{{ timemachine_cpu_shares }}"
        memory: "{{ timemachine_memory }}"
        labels:
          autoheal: "{{ timemachine_autoheal }}"
          com.centurylinklabs.watchtower.monitor-only: "{{ timemachine_watchtower_monitor_only }}"

    - name: Install avahi
      ansible.builtin.apt:
        name: "avahi-daemon"
        state: present
        update_cache: yes
      register: result
      until: result is succeeded

    - name: Setup {{ ansible_nas_app_name }} service for avahi
      ansible.builtin.template:
        src: timemachine.service
        dest: "/etc/avahi/services/timemachine.service"
      notify: reload avahi configuration
  when: timemachine_enabled is true

- name: Stop {{ ansible_nas_app_name }}
  block:
    - name: Stop {{ ansible_nas_app_name }} Container
      community.docker.docker_container:
        name: "{{ timemachine_container_name }}"
        state: absent
# Needs avahi removal task here
  when: timemachine_enabled is false

- name: Data Archive {{ ansible_nas_app_name }}
  block:
    - name: Check for {{ ansible_nas_app_name }} Data Directory
      stat:
        path: "{{ timemachine_data_directory }}"
      register: dir_stat

    - name: Archive {{ ansible_nas_app_name }} Data Directory
      ansible.builtin.archive:
        path: "{{ timemachine_data_directory }}"
        dest: "{{ docker_home }}/{{ ansible_nas_app_name | lower }}.zip"
        force_archive: true
        format: zip
        owner: ansible-nas
        group: ansible-nas
        mode: u=rw,g=rw
        remove: true
      when: dir_stat.stat.exists
  when: timemachine_enabled is false and archive_app_data_enabled is true
