---
- name: Start {{ ansible_nas_app_name }}
  block:
    - name: Check for deprecated API key
      ansible.builtin.fail:
        msg: "Using a Cloudflare global API key is no longer supported. Please unset cloudflare_api_key and set cloudflare_ddns_token"
      when: cloudflare_api_key is defined

    - name: Create {{ ansible_nas_app_name }} Directories
      ansible.builtin.file:
        path: "{{ cloudflare_ddns_data_directory }}"
        state: directory

    - name: Template {{ ansible_nas_app_name }} config.yml with scoped token
      ansible.builtin.template:
        src: config.yml
        dest: "{{ cloudflare_ddns_data_directory }}/config.yml"
      register: template_files_result

    - name: Create {{ ansible_nas_app_name }} Container
      community.docker.docker_container:
        container_default_behavior: "compatibility"
        name: "{{ cloudflare_ddns_container_name }}"
        hostname: "{{ cloudflare_ddns_container_name }}"
        image: "{{ cloudflare_ddns_image_name }}:{{ cloudflare_ddns_image_version }}"
        pull: true
        volumes:
          - "{{ cloudflare_ddns_data_directory }}/config.yml:/app/config.yaml"
          - "/etc/timezone:/etc/timezone:ro"
        env:
          TZ: "{{ ansible_nas_timezone }}"
        recreate: "{{ template_files_result is changed }}"
        labels:
          autoheal: "{{ cloudflare_ddns_autoheal_enabled | ternary('true', 'false') }}"
          com.centurylinklabs.watchtower.enable: "{{ cloudflare_ddns_watchtower_enabled | ternary('true', 'false') }}"
          dockflare.enable: "false"
          homepage.name: "{{ ansible_nas_app_name }}"
          homepage.group: "{{ cloudflare_ddns_homepage_group }}"
          homepage.icon: "{{ cloudflare_ddns_homepage_icon }}"
          homepage.href: "https://dash.cloudflare.com/login"
          homepage.description: "{{ 'Cloudflare DDNS minimal docker.' if homepage_show_description else omit }}"
          homepage.server: "my-docker"
          homepage.container: "{{ cloudflare_ddns_container_name }}"
          homepage.showStats: "{{ cloudflare_ddns_homepage_showstats | ternary('true', 'false') }}"
          repliqate.enabled: "{{ cloudflare_ddns_repliqate_enabled | ternary('true', 'false') }}"
          repliqate.engine: "{{ cloudflare_ddns_repliqate_engine }}"
          repliqate.schedule: "{{ cloudflare_ddns_repliqate_schedule }}"
          repliqate.backup_id: "{{ cloudflare_ddns_repliqate_backup_id }}"
          repliqate.retention: "{{ cloudflare_ddns_repliqate_retention }}"
          traefik.enable: "false"
          wud.tag.include: "^latest$"
          wud.tag.transform.type: "semver"
          wud.link.template: "https://github.com/joshua-v/cloudflare-ddns/releases"
        cpu_shares: "{{ cloudflare_ddns_cpu_shares }}"
        restart_policy: unless-stopped
        memory: "{{ cloudflare_ddns_memory }}"
        memory_swap: "{{ cloudflare_ddns_memory_swap }}"
  when: cloudflare_ddns_enabled is true

- name: Stop {{ ansible_nas_app_name }}
  block:
    - name: Stop {{ ansible_nas_app_name }} Container
      community.docker.docker_container:
        name: "{{ cloudflare_ddns_container_name }}"
        state: absent
  when: cloudflare_ddns_enabled is false

- name: Data Archive {{ ansible_nas_app_name }}
  include_role:
    name: ansible-nas-archive
  vars:
    target_data_dir: "{{ cloudflare_ddns_data_directory }}"
  when:
    - archive_app_data_enabled is true
    - cloudflare_ddns_enabled is false