---
- name: Start {{ ansible_nas_app_name }}
  block:
    - name: Create {{ ansible_nas_app_name }} Directories
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
      with_items:
        - "{{ fasten_data_directory }}"
        - "{{ fasten_data_directory }}/cache"
        - "{{ fasten_data_directory }}/db"

    - name: Create {{ ansible_nas_app_name }} Container
      community.docker.docker_container:
        container_default_behavior: "compatibility"
        name: "{{ fasten_container_name }}"
        hostname: "{{ fasten_container_name }}"
        image: "{{ fasten_image_name }}:{{ fasten_image_tag }}"
        pull: true
        ports:
          - "{{ fasten_port_http }}:8080"
        volumes:
          - "{{ fasten_data_directory }}/cache:/opt/fasten/cache"
          - "{{ fasten_data_directory }}/db:/opt/fasten/db"
        env:
          TZ: "{{ ansible_nas_timezone }}"
        labels:
          autoheal: "{{ fasten_autoheal | string }}"
          com.centurylinklabs.watchtower.enable: "{{ fasten_watchtower_enabled| string }}"
          dockflare.enable: "{{ fasten_dockflare_enabled | string }}"
          dockflare.access.group: "{{ fasten_dockflare_access_group }}"
          dockflare.hostname: "{{ fasten_hostname }}.{{ ansible_nas_domain }}"
          dockflare.service: "http://{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}:{{ fasten_port_http }}"
          homepage.name: "{{ ansible_nas_app_name }}"
          homepage.group: "{{ fasten_homepage_group }}"
          homepage.icon: "{{ fasten_homepage_icon }}"
          homepage.href: "{{ fasten_homepage_href }}"
          homepage.siteMonitor: "http://{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}:{{ fasten_port_http }}"
          homepage.description: "{{ 'Fasten is an open-source, self-hosted, personal/family electronic medical record aggregator, designed to integrate with 100,000s of insurances/hospitals/clinic' if homepage_show_description else omit }}"
          homepage.server: "my-docker"
          homepage.container: "{{ fasten_container_name }}"
          homepage.showStats: "{{ fasten_homepage_showstats | string }}"
          repliqate.enabled: "{{ fasten_repliqate_enabled | string }}"
          repliqate.engine: "{{ fasten_repliqate_engine }}"
          repliqate.schedule: "{{ fasten_repliqate_schedule }}"
          repliqate.backup_id: "{{ fasten_repliqate_backup_id }}"
          repliqate.retention: "{{ fasten_repliqate_retention }}"
          traefik.enable: "{{ fasten_available_externally | string }}"
          traefik.http.routers.fasten.rule: "Host(`{{ fasten_hostname }}.{{ ansible_nas_domain }}`)"
          traefik.http.routers.fasten.tls.certresolver: "letsencrypt"
          traefik.http.routers.fasten.tls.domains[0].main: "{{ ansible_nas_domain }}"
          traefik.http.routers.fasten.tls.domains[0].sans: "*.{{ ansible_nas_domain }}"
          traefik.http.routers.fasten.middlewares: "fasten@docker{{ ',tinyauth-auth@docker' if fasten_tinyauth_enabled | bool else '' }}"
          traefik.http.middlewares.fasten.IPAllowList.sourcerange: "{{ fasten_traefik_whitelist }}"
          traefik.http.services.fasten.loadbalancer.server.port: "8080"
          wud.tag.include: '^v?\d+\.\d+\.\d+.*$'
          wud.tag.transform.type: "semver"
          wud.link.template: "https://github.com/fastenhealth/fasten-onprem/releases"
        cpu_shares: "{{ fasten_cpu_shares }}"
        memory: "{{ fasten_memory }}"
        memory_swap: "{{ fasten_memory_swap }}"
        restart_policy: unless-stopped

    - name: Access {{ ansible_nas_app_name }} at
      ansible.builtin.debug:
        msg: >-
              {{
                ['http://' + hostvars[inventory_hostname]['ansible_default_ipv4']['address'] + ':' + (fasten_port_http | string)] +
                (['https://' + fasten_hostname + '.' + ansible_nas_domain] if (fasten_available_externally is true or fasten_dockflare_enabled is true) else [])
              }}
  when: fasten_enabled is true

- name: Stop {{ ansible_nas_app_name }}
  block:
    - name: Stop {{ ansible_nas_app_name }} Container
      community.docker.docker_container:
        name: "{{ fasten_container_name }}"
        state: absent
  when: fasten_enabled is false

- name: Data Archive {{ ansible_nas_app_name }}
  include_role:
    name: ansible-nas-archive
  vars:
    target_data_dir: "{{ fasten_data_directory }}"
  when:
    - archive_app_data_enabled is true
    - fasten_enabled is false