---
- name: Start {{ ansible_nas_app_name }}
  block:
    - name: Create {{ ansible_nas_app_name }} Directory
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
      with_items:
        - "{{ speedtest_tracker_data_directory }}/config"

    - name: Set {{ ansible_nas_app_name }} FQDN var overrides
      ansible.builtin.set_fact:
        speedtest_tracker_homepage_href: "https://{{ speedtest_tracker_hostname }}.{{ ansible_nas_domain }}"
      when: speedtest_tracker_traefik_enabled | bool or speedtest_tracker_dockflare_enabled | bool

    - name: Remove old {{ ansible_nas_app_name }} Container
      community.docker.docker_container:
        container_default_behavior: "compatibility"
        name: "{{ speedtest_tracker_container_name }}"
        state: absent
      tags: molecule-idempotence-notest

    - name: Create {{ ansible_nas_app_name }} Container
      community.docker.docker_container:
        container_default_behavior: "compatibility"
        name: "{{ speedtest_tracker_container_name }}"
        hostname: "{{ speedtest_tracker_container_name }}"
        image: "{{ speedtest_tracker_image_name }}:{{ speedtest_tracker_image_version }}"
        pull: true
        volumes:
          - "{{ speedtest_tracker_data_directory }}/config:/config:rw"
        ports:
          - "{{ speedtest_tracker_port_http }}:80"
        env:
          AUTH: "{{ speedtest_tracker_auth }}"
          OOKLA_EULA_GDPR: "true"
          PUID: "{{ speedtest_tracker_puid }}"
          PGID: " {{ speedtest_tracker_pgid }}"
          TZ: "{{ ansible_nas_timezone }}"
        labels:
          autoheal: "{{ speedtest_tracker_autoheal_enabled | ternary('true', 'false') }}"
          com.centurylinklabs.watchtower.enable: "{{ speedtest_tracker_watchtower_enabled | ternary('true', 'false') }}"
          dockflare.enable: "{{ speedtest_tracker_dockflare_enabled | ternary('true', 'false') }}"
          dockflare.access.group: "{{ speedtest_tracker_dockflare_access_group }}"
          dockflare.hostname: "{{ speedtest_tracker_hostname }}.{{ ansible_nas_domain }}"
          dockflare.service: "http://{{ hostvars[inventory_hostname]['ansible_facts']['default_ipv4']['address'] }}:{{ speedtest_tracker_port_http }}"
          homepage.name: "{{ ansible_nas_app_name }}"
          homepage.group: "{{ speedtest_tracker_homepage_group }}"
          homepage.icon: "{{ speedtest_tracker_homepage_icon }}"
          homepage.href: "{{ speedtest_tracker_homepage_href }}"
          homepage.siteMonitor: "http://{{ hostvars[inventory_hostname]['ansible_facts']['default_ipv4']['address'] }}:{{ speedtest_tracker_port_http }}"
          homepage.description: "{{ 'Continuously track your internet speed' if homepage_show_description else omit }}"
          homepage.server: "my-docker"
          homepage.container: "{{ speedtest_tracker_container_name }}"
          homepage.showStats: "{{ speedtest_tracker_homepage_showstats | ternary('true', 'false') }}"
          homepage.widget.type: "speedtest"
          homepage.widget.url: "http://{{ hostvars[inventory_hostname]['ansible_facts']['default_ipv4']['address'] }}:{{ speedtest_tracker_port_http }}"
          homepage.widget.version: "{{ speedtest_tracker_homepage_widget_version }}"
          repliqate.enabled: "{{ speedtest_tracker_repliqate_enabled | ternary('true', 'false') }}"
          repliqate.engine: "{{ speedtest_tracker_repliqate_engine }}"
          repliqate.schedule: "{{ speedtest_tracker_repliqate_schedule }}"
          repliqate.backup_id: "{{ speedtest_tracker_repliqate_backup_id }}"
          repliqate.retention: "{{ speedtest_tracker_repliqate_retention }}"
          traefik.enable: "{{ speedtest_tracker_traefik_enabled | ternary('true', 'false') }}"
          traefik.http.routers.speedtesttracker.rule: "Host(`{{ speedtest_tracker_hostname }}.{{ ansible_nas_domain }}`)"
          traefik.http.routers.speedtesttracker.tls.certresolver: "letsencrypt"
          traefik.http.routers.speedtesttracker.tls.domains[0].main: "{{ ansible_nas_domain }}"
          traefik.http.routers.speedtesttracker.tls.domains[0].sans: "*.{{ ansible_nas_domain }}"
          traefik.http.routers.speedtesttracker.middlewares: "speedtesttracker@docker{{ ',tinyauth-auth@docker' if speedtest_tracker_tinyauth_enabled | bool else '' }}"
          traefik.http.middlewares.speedtesttracker.IPAllowList.sourcerange: "{{ speedtest_tracker_traefik_whitelist }}"
          traefik.http.services.speedtesttracker.loadbalancer.server.port: "80"
          wud.tag.include: '^\d+\.\d+\.\d+.*$'
          wud.tag.transform.type: "semver"
          wud.link.template: "https://hub.docker.com/r/henrywhitaker3/speedtest-tracker"
        cpu_shares: "{{ speedtest_tracker_cpu_shares }}"
        memory: "{{ speedtest_tracker_memory}}"
        memory_swap: "{{ speedtest_tracker_memory_swap }}"
        restart_policy: unless-stopped

    - name: Access {{ ansible_nas_app_name }} at
      ansible.builtin.debug:
        msg: >-
              {{
                ['http://' + hostvars[inventory_hostname]['ansible_facts']['default_ipv4']['address'] + ':' + (speedtest_tracker_port_http | string)] +
                (['https://' + speedtest_tracker_hostname + '.' + ansible_nas_domain] if (speedtest_tracker_traefik_enabled is true or speedtest_tracker_dockflare_enabled is true) else [])
              }}
  when: speedtest_tracker_enabled is true

- name: Stop {{ ansible_nas_app_name }}
  block:
    - name: Stop {{ ansible_nas_app_name }} Container
      community.docker.docker_container:
        name: "{{ speedtest_tracker_container_name }}"
        state: absent
  when: speedtest_tracker_enabled is false

- name: Data Archive {{ ansible_nas_app_name }}
  include_role:
    name: ansible-nas-archive
  vars:
    target_data_dir: "{{ speedtest_tracker_data_directory }}"
  when:
    - archive_app_data_enabled is true
    - speedtest_tracker_enabled is false