---
- name: Start {{ ansible_nas_app_name }}
  block:
    - name: Create {{ ansible_nas_app_name }} Directories
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
      with_items:
        - "{{ tugtainer_data_directory }}"

    - name: Create {{ ansible_nas_app_name }} Container
      community.docker.docker_container:
        container_default_behavior: "compatibility"
        name: "{{ tugtainer_container_name }}"
        hostname: "{{ tugtainer_container_name }}"
        image: "{{ tugtainer_image_name }}:{{ tugtainer_image_tag }}"
        pull: true
        volumes:
          - "{{ tugtainer_data_directory }}:/tugtainer"
          - /var/run/docker.sock:/var/run/docker.sock
        ports:
          - "{{ tugtainer_port_http }}:80"
        env:
          TZ: "{{ ansible_nas_timezone }}"
        labels:
          autoheal: "{{ tugtainer_autoheal_enabled | ternary('true', 'false') }}"
          com.centurylinklabs.watchtower.enable: "{{ tugtainer_watchtower_enabled | ternary('true', 'false') }}"
          dockflare.enable: "{{ tugtainer_dockflare_enabled | ternary('true', 'false') }}"
          dockflare.access.group: "{{ tugtainer_dockflare_access_group }}"
          dockflare.hostname: "{{ tugtainer_hostname }}.{{ ansible_nas_domain }}"
          dockflare.service: "http://{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}:{{ tugtainer_port_http }}"
          homepage.name: "{{ ansible_nas_app_name }}"
          homepage.group: "{{ tugtainer_homepage_group }}"
          homepage.icon: "{{ tugtainer_homepage_icon }}"
          homepage.href: "{{ tugtainer_homepage_href }}"
          homepage.description: "{{ 'application for automating docker containers updates with a web ui' if homepage_show_description else omit }}"
          homepage.server: "my-docker"
          homepage.container: "{{ tugtainer_container_name }}"
          homepage.showStats: "{{ tugtainer_homepage_showstats | ternary('true', 'false') }}"
          homepage.siteMonitor: "http://{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}:{{ tugtainer_port_http }}"
          repliqate.enabled: "{{ tugtainer_repliqate_enabled | ternary('true', 'false') }}"
          repliqate.engine: "{{ tugtainer_repliqate_engine }}"
          repliqate.schedule: "{{ tugtainer_repliqate_schedule }}"
          repliqate.backup_id: "{{ tugtainer_repliqate_backup_id }}"
          repliqate.retention: "{{ tugtainer_repliqate_retention }}"
          traefik.enable: "{{ tugtainer_traefik_enabled | ternary('true', 'false') }}"
          traefik.http.routers.tugtainer.rule: "Host(`{{ tugtainer_hostname }}.{{ ansible_nas_domain }}`)"
          traefik.http.routers.tugtainer.tls.certresolver: "letsencrypt"
          traefik.http.routers.tugtainer.tls.domains[0].main: "{{ ansible_nas_domain }}"
          traefik.http.routers.tugtainer.tls.domains[0].sans: "*.{{ ansible_nas_domain }}"
          traefik.http.routers.tugtainer.middlewares: "tugtainer@docker{{ ',tinyauth-auth@docker' if tugtainer_tinyauth_enabled | bool else '' }}"
          traefik.http.middlewares.tugtainer.IPAllowList.sourcerange: "{{ tugtainer_traefik_whitelist }}"
          traefik.http.services.tugtainer.loadbalancer.server.port: "80"
          wud.tag.include: '^v\d+\.\d+\.\d+$'
          wud.tag.transform.type: "semver"
          wud.link.template: "https://github.com/quenary/tugtainer/pkgs/container/tugtainer"
        cpu_shares: "{{ tugtainer_cpu_shares }}"
        memory: "{{ tugtainer_memory }}"
        restart_policy: unless-stopped

    - name: Access {{ ansible_nas_app_name }} at
      ansible.builtin.debug:
        msg: >-
              {{
                ['http://' + hostvars[inventory_hostname]['ansible_default_ipv4']['address'] + ':' + (tugtainer_port_http | string)] +
                (['https://' + tugtainer_hostname + '.' + ansible_nas_domain] if (tugtainer_traefik_enabled is true or tugtainer_dockflare_enabled is true) else [])
              }}
  when: tugtainer_enabled is true

- name: Stop {{ ansible_nas_app_name }}
  block:
    - name: Stop {{ ansible_nas_app_name }} Container
      community.docker.docker_container:
        name: "{{ tugtainer_container_name }}"
        state: absent
  when: tugtainer_enabled is false

- name: Data Archive {{ ansible_nas_app_name }}
  include_role:
    name: ansible-nas-archive
  vars:
    target_data_dir: "{{ tugtainer_data_directory }}"
  when:
    - archive_app_data_enabled is true
    - tugtainer_enabled is false