---
# ANE
ansible_nas_app_name: "Rocket.Chat"
rocket_chat_enabled: false
rocket_chat_traefik_enabled: false
rocket_chat_traefik_whitelist: "{{ lan }}"
rocket_chat_data_directory: "{{ docker_home }}/rocket-chat"

# network
rocket_chat_hostname: "rocketchat"
rocket_chat_port_http: "3055"

# docker
rocket_chat_network_name: "rocket-chat"
rocket_chat_container_name: "rocket-chat"
rocket_chat_image_name: "docker.io/rocketchat/rocket.chat"
rocket_chat_image_tag: "latest"
rocket_chat_db_container_name: "rocket-chat-db"
rocket_chat_db_image_name: "docker.io/bitnamilegacy/mongodb"
rocket_chat_db_image_tag: "6.0"

# specs
rocket_chat_cpu_shares: 1024
rocket_chat_memory: "1G"
rocket_chat_db_cpu_shares: 1024
rocket_chat_db_memory: "1G"

# app
rocket_chat_env_reg_token: ""

# autoheal
rocket_chat_autoheal_enabled: false
rocket_chat_db_autoheal_enabled: false

# dockflare
rocket_chat_dockflare_enabled: false
rocket_chat_dockflare_access_group: ""

# homepage
rocket_chat_homepage_group: "Apps"
rocket_chat_homepage_icon: "rocket-chat.png"
rocket_chat_homepage_href: "https://{{ rocket_chat_hostname }}.{{ ansible_nas_domain }}"
rocket_chat_homepage_showstats: false
rocket_chat_db_homepage_group: "DBs"
rocket_chat_db_homepage_icon: "mongodb.png"
rocket_chat_db_homepage_href: "{{ rocket_chat_homepage_href }}"
rocket_chat_db_homepage_showstats: false

# repliqate
rocket_chat_repliqate_enabled: false
rocket_chat_repliqate_engine: "restic"
rocket_chat_repliqate_schedule: "@daily 3am"
rocket_chat_repliqate_backup_id: "{{ rocket_chat_container_name }}"
rocket_chat_repliqate_retention: "30d"
rocket_chat_db_repliqate_enabled: false
rocket_chat_db_repliqate_engine: "restic"
rocket_chat_db_repliqate_schedule: "@daily 3am"
rocket_chat_db_repliqate_backup_id: "{{ rocket_chat_container_name }}"
rocket_chat_db_repliqate_retention: "30d"

# tinyauth
rocket_chat_tinyauth_enabled: false

# watchtower
rocket_chat_watchtower_enabled: false
rocket_chat_db_watchtower_enabled: false