---
- name: Start {{ ansible_nas_app_name }}
  block:
    - name: Create {{ ansible_nas_app_name }} Directories
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
      with_items:
        - "{{ flaresolverr_config_directory }}"

    - name: Create {{ ansible_nas_app_name }} Container
      community.docker.docker_container:
        container_default_behavior: "compatibility"
        name: "{{ flaresolverr_container_name }}"
        hostname: "{{ flaresolverr_container_name }}"
        image: "{{ flaresolverr_image_name }}:{{ flaresolverr_image_version }}"
        pull: true
        volumes:
          - "{{ flaresolverr_config_directory }}:/config:rw"
        ports:
          - "{{ flaresolverr_port }}:8191"
        env:
          LOG_LEVEL: "info"
          LOG_HTML: "false"
          TZ: "{{ ansible_nas_timezone }}"
        labels:
          autoheal: "{{ flaresolverr_autoheal }}"
          com.centurylinklabs.watchtower.monitor-only: "{{ flaresolverr_watchtower_monitor_only }}"
          dockflare.enable: "{{ flaresolverr_dockflare_tunnel }}"
          dockflare.access.group: "{{ flaresolverr_dockflare_access_group }}"
          dockflare.hostname: "{{ flaresolverr_hostname }}.{{ ansible_nas_domain }}"
          dockflare.service: "http://{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}:{{ flaresolverr_port }}"
          homepage.name: "{{ ansible_nas_app_name }}"
          homepage.group: "{{ flaresolverr_homepage_group }}"
          homepage.href: "{{ flaresolverr_homepage_href }}"
          homepage.icon: "{{ flaresolverr_homepage_icon }}"
          homepage.siteMonitor: "http://{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}:{{ flaresolverr_port }}"
          homepage.description: "{{ 'Proxy server to bypass Cloudflare protection' if homepage_show_description else omit }}"
          homepage.server: "my-docker"
          homepage.container: "{{ flaresolverr_container_name }}"
          homepage.showStats: "{{ flaresolverr_homepage_showStats }}"
          traefik.enable: "{{ flaresolverr_available_externally | string }}"
          traefik.http.routers.flaresolverr.rule: "Host(`flaresolverr.{{ ansible_nas_domain }}`)"
          traefik.http.routers.flaresolverr.tls.certresolver: "letsencrypt"
          traefik.http.routers.flaresolverr.tls.domains[0].main: "{{ ansible_nas_domain }}"
          traefik.http.routers.flaresolverr.tls.domains[0].sans: "*.{{ ansible_nas_domain }}"
          traefik.http.routers.frontend.middlewares: "{{ flaresolverr_hostname }}"
          traefik.http.routers.flaresolverr.middlewares: "{{ flaresolverr_hostname }}@docker"
          traefik.http.middlewares.flaresolverr.IPAllowList.sourcerange: "{{ flaresolverr_traefik_whitelist }}"
          traefik.http.services.flaresolverr.loadbalancer.server.port: "8191"
          wud.tag.include: '^\d+\.\d+\.\d+$$'
          wud.link.template: "https://github.com/FlareSolverr/FlareSolverr/releases/tag/$${major}.$${minor}.$${patch}"
        cpu_shares: "{{ flaresolverr_cpu_shares }}"
        memory: "{{ flaresolverr_memory }}"
        restart_policy: unless-stopped
  when: flaresolverr_enabled is true

- name: Stop {{ ansible_nas_app_name }}
  block:
    - name: Stop {{ ansible_nas_app_name }} Container
      community.docker.docker_container:
        name: "{{ flaresolverr_container_name }}"
        state: absent
  when: flaresolverr_enabled is false

- name: Data Archive {{ ansible_nas_app_name }}
  block:
    - name: Check for {{ ansible_nas_app_name }} Data Directory
      stat:
        path: "{{ flaresolverr_data_directory }}"
      register: dir_stat

    - name: Archive {{ ansible_nas_app_name }} Data Directory
      ansible.builtin.archive:
        path: "{{ flaresolverr_data_directory }}"
        dest: "{{ docker_home }}/{{ ansible_nas_app_name | lower }}.zip"
        force_archive: true
        format: zip
        owner: ansible-nas
        group: ansible-nas
        mode: u=rw,g=rw
        remove: true
      when: dir_stat.stat.exists
  when: flaresolverr_enabled is false and archive_app_data_enabled is true
