---
- name: Start {{ ansible_nas_app_name }}
  block:
    - name: Create {{ ansible_nas_app_name }} Directories
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
      with_items:
        - "{{ flaresolverr_data_directory }}"

    - name: Set {{ ansible_nas_app_name }} FQDN var overrides
      ansible.builtin.set_fact:
        flaresolverr_homepage_href: "https://{{ flaresolverr_hostname }}.{{ ansible_nas_domain }}"
      when: flaresolverr_traefik_enabled | bool or flaresolverr_dockflare_enabled | bool

    - name: Create {{ ansible_nas_app_name }} Container
      community.docker.docker_container:
        container_default_behavior: "compatibility"
        name: "{{ flaresolverr_container_name }}"
        hostname: "{{ flaresolverr_container_name }}"
        image: "{{ flaresolverr_image_name }}:{{ flaresolverr_image_version }}"
        pull: true
        volumes:
          - "{{ flaresolverr_data_directory }}:/config:rw"
        ports:
          - "{{ flaresolverr_port_http }}:8191"
        env:
          LOG_LEVEL: "info"
          LOG_HTML: "false"
          TZ: "{{ ansible_nas_timezone }}"
        labels:
          autoheal: "{{ flaresolverr_autoheal_enabled | ternary('true', 'false') }}"
          com.centurylinklabs.watchtower.enable: "{{ flaresolverr_watchtower_enabled | ternary('true', 'false') }}"
          dockflare.enable: "{{ flaresolverr_dockflare_enabled | ternary('true', 'false') }}"
          dockflare.access.group: "{{ flaresolverr_dockflare_access_group }}"
          dockflare.hostname: "{{ flaresolverr_hostname }}.{{ ansible_nas_domain }}"
          dockflare.service: "http://{{ hostvars[inventory_hostname]['ansible_facts']['default_ipv4']['address'] }}:{{ flaresolverr_port_http }}"
          homepage.name: "{{ ansible_nas_app_name }}"
          homepage.group: "{{ flaresolverr_homepage_group }}"
          homepage.href: "{{ flaresolverr_homepage_href }}"
          homepage.icon: "{{ flaresolverr_homepage_icon }}"
          homepage.siteMonitor: "http://{{ hostvars[inventory_hostname]['ansible_facts']['default_ipv4']['address'] }}:{{ flaresolverr_port_http }}"
          homepage.description: "{{ 'Proxy server to bypass Cloudflare protection' if homepage_show_description else omit }}"
          homepage.server: "my-docker"
          homepage.container: "{{ flaresolverr_container_name }}"
          homepage.showStats: "{{ flaresolverr_homepage_showstats | ternary('true', 'false') }}"
          repliqate.enabled: "{{ flaresolverr_repliqate_enabled | ternary('true', 'false') }}"
          repliqate.engine: "{{ flaresolverr_repliqate_engine }}"
          repliqate.schedule: "{{ flaresolverr_repliqate_schedule }}"
          repliqate.backup_id: "{{ flaresolverr_repliqate_backup_id }}"
          repliqate.retention: "{{ flaresolverr_repliqate_retention }}"
          traefik.enable: "{{ flaresolverr_traefik_enabled | ternary('true', 'false') }}"
          traefik.http.routers.flaresolverr.rule: "Host(`{{ flaresolverr_hostname }}.{{ ansible_nas_domain }}`)"
          traefik.http.routers.flaresolverr.tls.certresolver: "letsencrypt"
          traefik.http.routers.flaresolverr.tls.domains[0].main: "{{ ansible_nas_domain }}"
          traefik.http.routers.flaresolverr.tls.domains[0].sans: "*.{{ ansible_nas_domain }}"
          traefik.http.routers.flaresolverr.middlewares: "flaresolverr@docker{{ ',tinyauth-auth@docker' if flaresolverr_tinyauth_enabled | bool else '' }}"
          traefik.http.middlewares.flaresolverr.IPAllowList.sourcerange: "{{ flaresolverr_traefik_whitelist }}"
          traefik.http.services.flaresolverr.loadbalancer.server.port: "8191"
          wud.tag.include: '^v?\d+\.\d+\.\d+.*$'
          wud.tag.transform.type: "semver"
          wud.link.template: "https://github.com/FlareSolverr/FlareSolverr/releases"
        cpu_shares: "{{ flaresolverr_cpu_shares }}"
        memory: "{{ flaresolverr_memory }}"
        memory_swap: "{{ flaresolverr_memory_swap }}"
        restart_policy: unless-stopped

    - name: Access {{ ansible_nas_app_name }} at
      ansible.builtin.debug:
        msg: >-
              {{
                ['http://' + hostvars[inventory_hostname]['ansible_facts']['default_ipv4']['address'] + ':' + (flaresolverr_port_http | string)] +
                (['https://' + flaresolverr_hostname + '.' + ansible_nas_domain] if (flaresolverr_traefik_enabled is true or flaresolverr_dockflare_enabled is true) else [])
              }}
  when: flaresolverr_enabled is true

- name: Stop {{ ansible_nas_app_name }}
  block:
    - name: Stop {{ ansible_nas_app_name }} Container
      community.docker.docker_container:
        name: "{{ flaresolverr_container_name }}"
        state: absent
  when: flaresolverr_enabled is false

- name: Data Archive {{ ansible_nas_app_name }}
  include_role:
    name: ansible-nas-archive
  vars:
    target_data_dir: "{{ flaresolverr_data_directory }}"
  when:
    - archive_app_data_enabled is true
    - flaresolverr_enabled is false