---
# ANE
ansible_nas_app_name: "qBittorrent"
qbittorrent_enabled: false
qbittorrent_available_externally: false
qbittorrent_traefik_whitelist: "{{ lan }}"

# directories
qbittorrent_data_directory: "{{ docker_home }}/qbittorrent"
qbittorrent_download_directory: "{{ downloads_root }}"
qbittorrent_watch_directory: "{{ torrents_root }}"
qbittorrent_extra_directory_mapping: "" # e.g. "/host/dir:/container/dir:rw"

# uid / gid
qbittorrent_user_id: "1000"
qbittorrent_group_id: "1000"
qbittorrent_umask: "000"

# network
qbittorrent_hostname: "qbittorrent"
qbittorrent_port_http: "8113"
qbittorrent_port_bt: "6882"

# docker
qbittorrent_container_name: "qbittorrent"
qbittorrent_image_name: "lscr.io/linuxserver/qbittorrent"
qbittorrent_image_tag: "latest"

# specs
qbittorrent_cpu_shares: 1024
qbittorrent_memory: "1G"

# autoheal
qbittorrent_autoheal: "false"

# dockflare
qbittorrent_dockflare_tunnel: "false"
qbittorrent_dockflare_access_group: ""

# homepage
qbittorrent_homepage_group: "Download Tools"
qbittorrent_homepage_icon: "qbittorrent.png"
qbittorrent_homepage_href: "http://{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}:{{ qbittorrent_port_http }}"
qbittorrent_homepage_widget_username: "admin"
qbittorrent_homepage_widget_password: "{{ ansible_nas_app_admin_password }}"
qbittorrent_homepage_showstats: "false"

# linuxserver.io docker mods
qbittorrent_env_docker_mods: ""
qbittorrent_env_docker_mods_install_packages: ""
qbittorrent_env_docker_mods_install_pip_packages: ""

# theme.park themes
# https://docs.theme-park.dev/themes/qbittorrent/
qbittorrent_env_docker_mods_tp_theme: ""
qbittorrent_env_docker_mods_tp_community_theme: ""
qbittorrent_env_docker_mods_tp_domain: ""
qbittorrent_env_docker_mods_tp_addon: ""

# repliqate
qbittorrent_repliqate_enabled: "false"
qbittorrent_repliqate_engine: "restic"
qbittorrent_repliqate_schedule: "@daily 3am"
qbittorrent_repliqate_backup_id: "{{ qbittorrent_container_name }}"
qbittorrent_repliqate_retention: "30d"

# watchtower
qbittorrent_watchtower_enable: "false"