---
- name: Start {{ ansible_nas_app_name }}
  block:
    - name: Create {{ ansible_nas_app_name }} Directories
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
      with_items:
        - "{{ homepage_data_directory }}/"
        - "{{ homepage_data_directory }}/config"
        - "{{ homepage_data_directory }}/config/logs"
        - "{{ homepage_data_directory }}/images"

    - name: Create {{ ansible_nas_app_name }} Template config files
      ansible.builtin.template:
        src: "{{ item }}"
        dest: "{{ homepage_data_directory }}/config/{{ item }}"
      with_items:
        - bookmarks.yaml
        - docker.yaml
        - kubernetes.yaml
        - proxmox.yaml
        - services.yaml
        - settings.yaml
        - widgets.yaml
      register: homepage_config

    - name: Create {{ ansible_nas_app_name }} Container
      community.docker.docker_container:
        container_default_behavior: "compatibility"
        name: "{{ homepage_container_name }}"
        hostname: "{{ homepage_hostname }}"
        image: "{{ homepage_image_name }}:{{ homepage_image_tag }}"
        pull: true
        volumes:
          - "{{ homepage_data_directory }}/config:/app/config"
          - "{{ homepage_data_directory }}/images:/app/public/images"
          - "/var/run/docker.sock:/var/run/docker.sock:ro"
        ports:
          - "{{ homepage_port_http }}:3000"
        env:
          HOMEPAGE_ALLOWED_HOSTS: "{{ homepage_allowed_hosts }}"
          LOG_LEVEL: "debug"
          PUID: "{{ homepage_puid }}"
          PGID: "{{ homepage_pgid }}"
          TZ: "{{ ansible_nas_timezone }}"
        labels:
          autoheal: "{{ homepage_autoheal_enabled | ternary('true', 'false') }}"
          com.centurylinklabs.watchtower.enable: "{{ homepage_watchtower_enabled | ternary('true', 'false') }}"
          dockflare.enable: "{{ homepage_dockflare_enabled | ternary('true', 'false') }}"
          dockflare.access.group: "{{ homepage_dockflare_access_group }}"
          dockflare.hostname: "{{ homepage_hostname }}.{{ ansible_nas_domain }}"
          dockflare.service: "http://{{ hostvars[inventory_hostname]['ansible_facts']['default_ipv4']['address'] }}:{{ homepage_port_http }}"
          repliqate.enabled: "{{ homepage_repliqate_enabled | ternary('true', 'false') }}"
          repliqate.engine: "{{ homepage_repliqate_engine }}"
          repliqate.schedule: "{{ homepage_repliqate_schedule }}"
          repliqate.backup_id: "{{ homepage_repliqate_backup_id }}"
          repliqate.retention: "{{ homepage_repliqate_retention }}"
          traefik.enable: "{{ homepage_traefik_enabled | ternary('true', 'false') }}"
          traefik.http.routers.homepage.rule: "Host(`{{ homepage_hostname }}.{{ ansible_nas_domain }}`)"
          traefik.http.routers.homepage.tls.certresolver: "letsencrypt"
          traefik.http.routers.homepage.tls.domains[0].main: "{{ ansible_nas_domain }}"
          traefik.http.routers.homepage.tls.domains[0].sans: "*.{{ ansible_nas_domain }}"
          traefik.http.routers.homepage.middlewares: "homepage@docker{{ ',tinyauth-auth@docker' if homepage_tinyauth_enabled | bool else '' }}"
          traefik.http.middlewares.homepage.IPAllowList.sourcerange: "{{ homepage_traefik_whitelist }}"
          traefik.http.services.homepage.loadbalancer.server.port: "3000"
          wud.tag.include: '^v?\d+\.\d+\.\d+.*$'
          wud.tag.transform.type: "semver"
          wud.link.template: "https://github.com/gethomepage/homepage/releases"
        cpu_shares: "{{ homepage_cpu_shares }}"
        memory: "{{ homepage_memory }}"
        memory_swap: "{{ homepage_memory_swap }}"
        restart_policy: unless-stopped

    - name: Access {{ ansible_nas_app_name }} at
      ansible.builtin.debug:
        msg: >-
              {{
                ['http://' + hostvars[inventory_hostname]['ansible_facts']['default_ipv4']['address'] + ':' + (homepage_port_http | string)] +
                (['https://' + homepage_hostname + '.' + ansible_nas_domain] if (homepage_traefik_enabled is true or homepage_dockflare_enabled is true) else [])
              }}
  when: homepage_enabled is true

- name: Stop {{ ansible_nas_app_name }}
  block:
    - name: Stop {{ ansible_nas_app_name }} Container
      community.docker.docker_container:
        name: "{{ homepage_container_name }}"
        state: absent
  when: homepage_enabled is false

- name: Data Archive {{ ansible_nas_app_name }}
  include_role:
    name: ansible-nas-archive
  vars:
    target_data_dir: "{{ homepage_data_directory }}"
  when:
    - archive_app_data_enabled is true
    - homepage_enabled is false