---
ansible_nas_app_name: "Dozzle"

#
dozzle_enabled: false
dozzle_available_externally: false
dozzle_traefik_whitelist: "{{ lan }}"
dozzle_data_directory: "{{ docker_home }}/dozzle"

# network
dozzle_hostname: "dozzle"
dozzle_port_http: "9999"

# docker
dozzle_container_name: "dozzle"
dozzle_image_name: "amir20/dozzle"
dozzle_image_tag: "latest"
dozzle_cpu_shares: "1024"
dozzle_memory: "512m"

# autoheal
dozzle_autoheal: "false"

# homepage
dozzle_homepage_group: "Apps"
dozzle_homepage_icon: "dozzle.png"
dozzle_homepage_href: "http://{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}:{{ dozzle_port_http }}"
dozzle_homepage_showStats: "false"

# watchtower
dozzle_watchtower_monitor_only: "true"