---
# ANE
ansible_nas_app_name: "Joomla!"
joomla_enabled: false
joomla_traefik_enabled: false
joomla_traefik_whitelist: "{{ lan }}"

# directories
joomla_data_directory: "{{ docker_home }}/joomla"

# network
joomla_port_http: "8181"
joomla_hostname: "joomla"
joomla_network_name: "joomla"

# docker
joomla_container_name: "joomla"
joomla_image_name: "joomla"
joomla_image_version: "latest"
joomla_db_container_name: "joomla-db"
joomla_db_image_name: "mysql"
joomla_db_image_version: "8.0"

# specs
joomla_cpu_shares: 1024
joomla_memory: "1G"
joomla_memory_swap: -1
joomla_db_cpu_shares: 1024
joomla_db_memory: "1G"
joomla_db_memory_swap: "{{ joomla_db_memory }}"

# app
joomla_env_joomla_db_user: "joomla"
joomla_env_joomla_db_name: "joomla_db"
joomla_env_joomla_db_password: "topsecret"
joomla_env_joomla_db_type: "mysqli"
joomla_env_joomla_site_name: "{{ ansible_nas_app_name }} for {{ ansible_nas_user }}"
joomla_env_joomla_admin_user: "ANE {{ ansible_nas_user }}"
joomla_env_joomla_admin_username: "admin"
joomla_env_joomla_admin_password: "{{ ansible_nas_app_admin_password }}"
joomla_env_joomla_admin_email: ""
joomla_env_joomla_extensions_urls: ""
joomla_env_joomla_extensions_paths: ""
joomla_env_joomla_smtp_host: ""
joomla_env_joomla_smtp_host_port: ""

# autoheal
joomla_autoheal_enabled: false
joomla_db_autoheal_enabled: false

# dockflare
joomla_dockflare_enabled: false
joomla_dockflare_access_group: ""

# homepage
joomla_homepage_group: "Apps"
joomla_homepage_icon: "joomla.png"
joomla_homepage_href: "http://{{ hostvars[inventory_hostname]['ansible_facts']['default_ipv4']['address'] }}:{{ joomla_port_http }}"
joomla_homepage_showstats: false
joomla_db_homepage_group: "DBs"
joomla_db_homepage_icon: "mysql.png"
joomla_db_homepage_href: "{{ joomla_homepage_href }}"
joomla_db_homepage_showstats: false

# repliqate
joomla_repliqate_enabled: false
joomla_repliqate_engine: "restic"
joomla_repliqate_schedule: "@daily 3am"
joomla_repliqate_backup_id: "{{ joomla_container_name }}"
joomla_repliqate_retention: "30d"
joomla_db_repliqate_enabled: false
joomla_db_repliqate_engine: "restic"
joomla_db_repliqate_schedule: "@daily 3am"
joomla_db_repliqate_backup_id: "{{ joomla_db_container_name }}"
joomla_db_repliqate_retention: "30d"

# tinyauth
joomla_tinyauth_enabled: false

# watchtower
joomla_watchtower_enabled: false
joomla_db_watchtower_enabled: false