---
ansible_nas_app_name: "Joomla"

joomla_enabled: false
joomla_available_externally: false
joomla_traefik_whitelist: "{{ lan }}"

joomla_database_password: top_secret

# directories
joomla_data_directory: "{{ docker_home }}/joomla"

# network
joomla_port: "8181"
joomla_hostname: "joomla"
joomla_network_name: "joomla"

# docker
joomla_container_name: "joomla"
joomla_image_name: "joomla"
joomla_image_version: "latest"
joomla_cpu_shares: 1024
joomla_db_container_name: "joomla-db"
joomla_db_image_name: "mysql"
joomla_db_image_version: "5.7"
joomla_db_cpu_shares: 1024

# specs
joomla_memory: 1g
joomla_db_memory: 1g

# autoheal
joomla_autoheal: "false"
joomla_db_autoheal: "false"

# dockflare
joomla_dockflare_tunnel: "false"
joomla_dockflare_access_group: ""

# homepage
joomla_homepage_group: "Apps"
joomla_homepage_icon: "joomla.png"
joomla_homepage_href: "http://{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}:{{ joomla_port }}"
joomla_homepage_showStats: "false"
joomla_db_homepage_group: "DBs"
joomla_db_homepage_icon: "mysql.png"
joomla_db_homepage_href: "http://{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}:{{ joomla_port }}"
joomla_db_homepage_showStats: "false"

# watchtower
joomla_watchtower_monitor_only: "true"
joomla_db_watchtower_monitor_only: "true"