---
- name: Start {{ ansible_nas_app_name }}
  block:
    - name: Create{{ ansible_nas_app_name }} Directory
      file:
        path: "{{ item }}"
        state: directory
      with_items:
        - "{{ shoutcast_data_directory }}"

    - name: Create {{ ansible_nas_app_name }} Container
      community.docker.docker_container:
        container_default_behavior: "compatibility"
        name: "{{ shoutcast_container_name}}"
        hostname: "{{ shoutcast_container_name}}"
        image: "{{ shoutcast_image_name }}:{{ shoutcast_image_tag }}"
        pull: true
        volumes:
          - "{{ shoutcast_media_directory }}:/media:ro"
          - "{{ shoutcast_data_directory }}:/etc/shoutcast:rw"
        ports:
          - "{{ shoutcast_port_http }}:8001"
        env:
          TZ: "{{ ansible_nas_timezone }}"
        labels:
          autoheal: "{{ shoutcast_autoheal }}"
          com.centurylinklabs.watchtower.enable: "{{ shoutcast_watchtower_enable }}"
          dockflare.enable: "{{ shoutcast_dockflare_tunnel }}"
          dockflare.access.group: "{{ shoutcast_dockflare_access_group }}"
          dockflare.hostname: "{{ shoutcast_hostname }}.{{ ansible_nas_domain }}"
          dockflare.service: "http://{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}:{{ shoutcast_port_http }}"
          homepage.name: "{{ ansible_nas_app_name }}"
          homepage.group: "{{ shoutcast_homepage_group }}"
          homepage.icon: "{{ shoutcast_homepage_icon }}"
          homepage.href: "{{ shoutcast_homepage_href }}"
          homepage.siteMonitor: "http://{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}:{{ shoutcast_port_http }}"
          homepage.description: "{{ 'Shoutcast Radio Media Streaming Server' if homepage_show_description else omit }}"
          homepage.server: "my-docker"
          homepage.container: "{{ shoutcast_container_name }}"
          homepage.showStats: "{{ shoutcast_homepage_showstats }}"
          traefik.enable: "{{ shoutcast_available_externally | string }}"
          traefik.http.routers.shoutcast.rule: "Host(`shoutcast.{{ ansible_nas_domain }}`)"
          traefik.http.routers.shoutcast.tls.certresolver: "letsencrypt"
          traefik.http.routers.shoutcast.tls.domains[0].main: "{{ ansible_nas_domain }}"
          traefik.http.routers.shoutcast.tls.domains[0].sans: "*.{{ ansible_nas_domain }}"
          traefik.http.routers.frontend.middlewares: "{{ shoutcast_hostname }}"
          traefik.http.routers.shoutcast.middlewares: "{{ shoutcast_hostname }}@docker"
          traefik.http.middlewares.shoutcast.IPAllowList.sourcerange: "{{ shoutcast_traefik_whitelist }}"
          traefik.http.services.shoutcast.loadbalancer.server.port: "8001"
          wud.watch.digest: "true"
          wud.link.template: "https://hub.docker.com/r/luzifer/shoutcast"
        cpu_shares: "{{ shoutcast_cpu_shares }}"
        memory: "{{ shoutcast_memory }}"
        restart_policy: unless-stopped
  when: shoutcast_enabled is true

- name: Stop {{ ansible_nas_app_name }}
  block:
    - name: Stop {{ ansible_nas_app_name }} Container
      community.docker.docker_container:
        name: "{{ shoutcast_container_name }}"
        state: absent
  when: shoutcast_enabled is false

- name: Data Archive {{ ansible_nas_app_name }}
  block:
    - name: Check for {{ ansible_nas_app_name }} Data Directory
      stat:
        path: "{{ shoutcast_data_directory }}"
      register: dir_stat

    - name: Archive {{ ansible_nas_app_name }} Data Directory
      ansible.builtin.archive:
        path: "{{ shoutcast_data_directory }}"
        dest: "{{ docker_home }}/{{ ansible_nas_app_name | lower }}.zip"
        force_archive: true
        format: zip
        owner: ansible-nas
        group: ansible-nas
        mode: u=rw,g=rw
        remove: true
      when: dir_stat.stat.exists
  when: shoutcast_enabled is false and archive_app_data_enabled is true
