---
- name: Start {{ ansible_nas_app_name }}
  block:
    - name: Create EspHome Directories
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
      with_items:
        - "{{ esphome_data_directory }}/data"

    - name: Set {{ ansible_nas_app_name }} FQDN var overrides
      ansible.builtin.set_fact:
        esphome_homepage_href: "https://{{ esphome_hostname }}.{{ ansible_nas_domain }}"
      when: esphome_traefik_enabled | bool or esphome_dockflare_enabled | bool

    - name: Create {{ ansible_nas_app_name }} Container
      community.docker.docker_container:
        container_default_behavior: "compatibility"
        name: "{{ esphome_container_name }}"
        hostname: "{{ esphome_container_name }}"
        image: "{{ esphome_image_name }}:{{ esphome_image_tag }}"
        pull: true
        volumes:
          - "{{ esphome_data_directory }}:/config:rw"
          - "/etc/localtime:/etc/localtime:ro"
        ports:
          - "{{ esphome_port_http }}:6052"
        env:
          TZ: "{{ ansible_nas_timezone }}"
          PUID: "{{ esphome_user_id }}"
          PGID: "{{ esphome_group_id }}"
        labels:
          autoheal: "{{ esphome_autoheal_enabled | ternary('true', 'false') }}"
          com.centurylinklabs.watchtower.enable: "{{ esphome_watchtower_enabled | ternary('true', 'false') }}"
          dockflare.enable: "{{ esphome_dockflare_enabled | ternary('true', 'false') }}"
          dockflare.access.group: "{{ esphome_dockflare_access_group }}"
          dockflare.hostname: "{{ esphome_hostname }}.{{ ansible_nas_domain }}"
          dockflare.service: "http://{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}:{{ esphome_port_http }}"
          homepage.name: "{{ ansible_nas_app_name }}"
          homepage.group: "{{ esphome_homepage_group }}"
          homepage.icon: "{{ esphome_homepage_icon }}"
          homepage.href: "{{ esphome_homepage_href }}"
          homepage.description: "{{ 'a system to control your ESP8266/ESP32' if homepage_show_description else omit }}"
          homepage.server: "my-docker"
          homepage.container: "{{ esphome_container_name }}"
          homepage.showStats: "{{ esphome_homepage_showstats | ternary('true', 'false') }}"
          homepage.siteMonitor: "http://{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}:{{ esphome_port_http }}"
          repliqate.enabled: "{{ esphome_repliqate_enabled | ternary('true', 'false') }}"
          repliqate.engine: "{{ esphome_repliqate_engine }}"
          repliqate.schedule: "{{ esphome_repliqate_schedule }}"
          repliqate.backup_id: "{{ esphome_repliqate_backup_id }}"
          repliqate.retention: "{{ esphome_repliqate_retention }}"
          traefik.enable: "{{ esphome_traefik_enabled | ternary('true', 'false') }}"
          traefik.http.routers.esphome.rule: "Host(`{{ esphome_hostname }}.{{ ansible_nas_domain }}`)"
          traefik.http.routers.esphome.tls.certresolver: "letsencrypt"
          traefik.http.routers.esphome.tls.domains[0].main: "{{ ansible_nas_domain }}"
          traefik.http.routers.esphome.tls.domains[0].sans: "*.{{ ansible_nas_domain }}"
          traefik.http.routers.esphome.middlewares: "esphome@docker{{ ',tinyauth-auth@docker' if esphome_tinyauth_enabled | bool else '' }}"
          traefik.http.middlewares.esphome.IPAllowList.sourcerange: "{{ esphome_traefik_whitelist }}"
          traefik.http.services.esphome.loadbalancer.server.port: "80"
          wud.tag.include: '^\d{4}\.\d+\.\d+$'
          wud.tag.transform.type: "semver"
          wud.link.template: "https://github.com/esphome/esphome/pkgs/container/esphome"
        cpu_shares: "{{ esphome_cpu_shares }}"
        memory: "{{ esphome_memory }}"
        memory_swap: "{{ esphome_memory_swap }}"
        restart_policy: unless-stopped

    - name: Access {{ ansible_nas_app_name }} at
      ansible.builtin.debug:
        msg: >-
              {{
                ['http://' + hostvars[inventory_hostname]['ansible_default_ipv4']['address'] + ':' + (esphome_port_http | string)] +
                (['https://' + esphome_hostname + '.' + ansible_nas_domain] if (esphome_traefik_enabled is true or esphome_dockflare_enabled is true) else [])
              }}
  when: esphome_enabled is true

- name: Stop {{ ansible_nas_app_name }}
  block:
    - name: Stop {{ ansible_nas_app_name }} Container
      community.docker.docker_container:
        name: "{{ esphome_container_name }}"
        state: absent
  when: esphome_enabled is false

- name: Data Archive {{ ansible_nas_app_name }}
  include_role:
    name: ansible-nas-archive
  vars:
    target_data_dir: "{{ esphome_data_directory }}"
  when:
    - archive_app_data_enabled is true
    - esphome_enabled is false