---
- name: Start {{ ansible_nas_app_name }}
  block:
    - name: Create EspHome Directories
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
      with_items:
        - "{{ esphome_data_directory }}/data"

    - name: Create {{ ansible_nas_app_name }} Container
      community.docker.docker_container:
        container_default_behavior: "compatibility"
        name: "{{ esphome_container_name }}"
        hostname: "{{ esphome_container_name }}"
        image: "{{ esphome_image_name }}:{{ esphome_image_tag }}"
        pull: true
        volumes:
          - "{{ esphome_data_directory }}:/config:rw"
          - "/etc/localtime:/etc/localtime:ro"
        ports:
          - "{{ esphome_port }}:6052"
        env:
          TZ: "{{ ansible_nas_timezone }}"
          PUID: "{{ esphome_user_id }}"
          PGID: "{{ esphome_group_id }}"
        labels:
          autoheal: "{{ esphome_autoheal }}"
          com.centurylinklabs.watchtower.enable: "{{ esphome_watchtower_enable }}"
          dockflare.enable: "{{ esphome_dockflare_tunnel }}"
          dockflare.access.group: "{{ esphome_dockflare_access_group }}"
          dockflare.hostname: "{{ esphome_hostname }}.{{ ansible_nas_domain }}"
          dockflare.service: "http://{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}:{{ esphome_port }}"
          homepage.name: "{{ ansible_nas_app_name }}"
          homepage.group: "{{ esphome_homepage_group }}"
          homepage.icon: "{{ esphome_homepage_icon }}"
          homepage.href: "{{ esphome_homepage_href }}"
          homepage.description: "{{ 'esphome description' if homepage_show_description else omit }}"
          homepage.server: "my-docker"
          homepage.container: "{{ esphome_container_name }}"
          homepage.showStats: "{{ esphome_homepage_showstats }}"
          homepage.siteMonitor: "http://{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}:{{ esphome_port }}"
          traefik.enable: "{{ esphome_available_externally | string }}"
          traefik.http.routers.esphome.rule: "Host(`{{ esphome_hostname }}.{{ ansible_nas_domain }}`)"
          traefik.http.routers.esphome.tls.certresolver: "letsencrypt"
          traefik.http.routers.esphome.tls.domains[0].main: "{{ ansible_nas_domain }}"
          traefik.http.routers.esphome.tls.domains[0].sans: "*.{{ ansible_nas_domain }}"
          traefik.http.routers.frontend.middlewares: "{{ esphome_hostname }}"
          traefik.http.routers.esphome.middlewares: "{{ esphome_hostname }}@docker"
          traefik.http.middlewares.esphome.IPAllowList.sourcerange: "{{ esphome_traefik_whitelist }}"
          traefik.http.services.esphome.loadbalancer.server.port: "80"
          wud.tag.include: '^\d+\.\d+\.\d+.*$'
          wud.tag.transform.type: "semver"
          wud.link.template: "https://hub.docker.com/r/esphome/esphome"
        cpu_shares: "{{ esphome_cpu_shares }}"
        memory: "{{ esphome_memory }}"
        restart_policy: unless-stopped

    - name: Access {{ ansible_nas_app_name }} at
      ansible.builtin.debug:
        msg: >-
              {{
                ['http://' + hostvars[inventory_hostname]['ansible_default_ipv4']['address'] + ':' + (esphome_port | string)] +
                (['https://' + esphome_hostname + '.' + ansible_nas_domain] if (esphome_available_externally is true or esphome_dockflare_tunnel is true) else [])
              }}
  when: esphome_enabled is true

- name: Stop {{ ansible_nas_app_name }}
  block:
    - name: Stop {{ ansible_nas_app_name }} Container
      community.docker.docker_container:
        name: "{{ esphome_container_name }}"
        state: absent
  when: esphome_enabled is false

- name: Data Archive {{ ansible_nas_app_name }}
  block:
    - name: Check for {{ ansible_nas_app_name }} Data Directory
      stat:
        path: "{{ esphome_data_directory }}"
      register: dir_stat

    - name: Archive {{ ansible_nas_app_name }} Data Directory
      ansible.builtin.archive:
        path: "{{ esphome_data_directory }}"
        dest: "{{ docker_home }}/{{ ansible_nas_app_name | lower }}.zip"
        force_archive: true
        format: zip
        owner: ansible-nas
        group: ansible-nas
        mode: u=rw,g=rw
        remove: true
      when: dir_stat.stat.exists
  when: esphome_enabled is false and archive_app_data_enabled is true
