---
# WORK IN PROGRESS
# https://docs.checkmate.so/checkmate-2.1/users-guide/quickstart
- name: Start {{ ansible_nas_app_name }}
  block:
    - name: Create {{ ansible_nas_app_name }} Directories
      file:
        path: "{{ item }}"
        state: directory
      with_items:
        - "{{ checkmate_data_directory }}"
        - "{{ checkmate_data_directory }}/db"

    - name: Create {{ ansible_nas_app_name }} DB Container
      community.docker.docker_container:
        container_default_behavior: "compatibility"
        name: "{{ checkmate_db_container_name }}"
        hostname: "{{ checkmate_db_container_name }}"
        image: "{{ checkmate_db_image_name }}:{{ checkmate_db_image_tag }}"
        pull: true
        command: ["mongod", "--quiet", "--replSet", "rs0", "--bind_ip_all"]
        volumes:
          - "{{ checkmate_data_directory }}/db:/data/db"
        network_mode: bridge
        env:
          TZ: "{{ ansible_nas_timezone }}"
#        healthcheck:
#          test: echo "try { rs.status() } catch (err) { rs.initiate({_id:'rs0',members:[{_id:0,host:'{{ checkmate_db_container_name }}":27017'}]}) }" | mongosh --port 27017 --quiet
#          interval: 5s
#          timeout: 30s
#          start_period: 0s
#          start_interval: 1s
#          retries: 30
        labels:
          autoheal: "{{ checkmate_db_autoheal }}"
          com.centurylinklabs.watchtower.monitor-only: "{{ checkmate_db_watchtower_monitor_only }}"
          homepage.name: "{{ ansible_nas_app_name }} MongoDB"
          homepage.group: "{{ checkmate_db_homepage_group }}"
          homepage.icon: "{{ checkmate_db_homepage_icon }}"
          homepage.href: "{{ checkmate_db_homepage_href }}"
          homepage.description: "{{ 'The MongoDB Database' if homepage_show_description else omit }}"
          homepage.server: "my-docker"
          homepage.container: "{{ checkmate_db_container_name }}"
          homepage.showStats: "{{ checkmate_db_homepage_showStats }}"
          traefik.enable: "false"
#         wud.tag.include: '^\d+\.\d+\.\d+$$'
#         wud.link.template: "https://github.com/fmartinou/whats-up-docker/releases/tag/$${major}.$${minor}.$${patch}"
        cpu_shares: "{{ checkmate_db_cpu_shares }}"
        memory: "{{ checkmate_db_memory }}"
        restart_policy: unless-stopped

    - name: Create {{ ansible_nas_app_name }} Server Container
      community.docker.docker_container:
        container_default_behavior: "compatibility"
        name: "{{ checkmate_server_container_name }}"
        hostname: "{{ checkmate_server_container_name }}"
        image: "{{ checkmate_server_image_name }}:{{ checkmate_server_image_tag }}"
        pull: true
        ports:
          - "{{ checkmate_server_port_http }}:52345"
        volumes:
          - "/var/run/docker.sock:/var/run/docker.sock:ro"
        network_mode: bridge
        env:
          UPTIME_APP_API_BASE_URL: 'http://localhost:52345/api/v1'
          UPTIME_APP_CLIENT_HOST: 'http://localhost'
          DB_CONNECTION_STRING: "mongodb://{{ checkmate_db_container_name }}:27017/uptime_db?replicaSet=rs0"
          REDIS_URL: "redis://redis:6379"
          CLIENT_HOST: 'http://localhost'
#         CLIENT_HOST: "http://192.168.69.210"
          JWT_SECRET: "EtNCM7ibSBHF33XB5q+zwOumszdQPvWo+mPF3HF0lUQ="
          TZ: "{{ ansible_nas_timezone }}"
        links:
          - "{{ checkmate_db_container_name }}"
        labels:
          autoheal: "{{ checkmate_server_autoheal }}"
          com.centurylinklabs.watchtower.monitor-only: "{{ checkmate_server_watchtower_monitor_only }}"
          homepage.name: "{{ ansible_nas_app_name }} Server"
          homepage.group: "{{ checkmate_server_homepage_group }}"
          homepage.icon: "{{ checkmate_server_homepage_icon }}"
          homepage.href: "{{ checkmate_server_homepage_href }}"
          homepage.description: "{{ 'Checkmate is an open-source, self-hosted tool designed to track and monitor server hardware, uptime, response times, and incidents in real-time with beautiful visualizations.' if homepage_show_description else omit }}"
          homepage.siteMonitor: "http://{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}:{{ checkmate_server_port_http }}"
          homepage.server: "my-docker"
          homepage.container: "{{ checkmate_server_container_name }}"
          homepage.showStats: "{{ checkmate_server_homepage_showStats }}"
          traefik.enable: "{{ checkmate_available_externally | string }}"
          traefik.http.routers.checkmate.rule: "Host(`{{ checkmate_server_hostname }}.{{ ansible_nas_domain }}`)"
          traefik.http.routers.checkmate.tls.certresolver: "letsencrypt"
          traefik.http.routers.checkmate.tls.domains[0].main: "{{ ansible_nas_domain }}"
          traefik.http.routers.checkmate.tls.domains[0].sans: "*.{{ ansible_nas_domain }}"
          traefik.http.routers.frontend.middlewares: "{{ checkmate_server_hostname }}"
          traefik.http.routers.checkmate.middlewares: "{{ checkmate_server_hostname }}@docker"
          traefik.http.middlewares.checkmate.IPAllowList.sourcerange: "{{ checkmate_traefik_whitelist }}"
          traefik.http.services.checkmate.loadbalancer.server.port: "52345"
          wud.tag.include: '^\d+\.\d+\.\d+$$'
          wud.link.template: "https://github.com/bluewave-labs/Checkmate/releases/tag/$${major}.$${minor}.$${patch}"
        cpu_shares: "{{ checkmate_server_cpu_shares }}"
        memory: "{{ checkmate_server_memory }}"
        restart_policy: unless-stopped

  when: checkmate_enabled is true

- name: Stop {{ ansible_nas_app_name }}
  block:
    - name: Stop {{ ansible_nas_app_name }} Server Container
      community.docker.docker_container:
        name: "{{ checkmate_server_container_name }}"
        state: absent

    - name: Stop {{ ansible_nas_app_name }} DB Container
      community.docker.docker_container:
        name: "{{ checkmate_db_container_name }}"
        state: absent
  when: checkmate_enabled is false

- name: Data Archive {{ ansible_nas_app_name }}
  block:
    - name: Check for {{ ansible_nas_app_name }} Data Directory
      stat:
        path: "{{ checkmate_data_directory }}"
      register: dir_stat

    - name: Archive {{ ansible_nas_app_name }} Data Directory
      ansible.builtin.archive:
        path: "{{ checkmate_data_directory }}"
        dest: "{{ docker_home }}/{{ ansible_nas_app_name | lower }}.zip"
        force_archive: true
        format: zip
        owner: ansible-nas
        group: ansible-nas
        mode: u=rw,g=rw
        remove: true
      when: dir_stat.stat.exists
  when: checkmate_enabled is false and archive_app_data_enabled is true
