---
# NOTE: there are some env vars that can be templated still
- name: Start {{ ansible_nas_app_name }}
  block:
    - name: Create {{ ansible_nas_app_name }} Directories
      file:
        path: "{{ item }}"
        state: directory
        owner: "1000"
        group: "1000"
      with_items:
        - "{{ twofauth_data_directory }}"
        - "{{ twofauth_data_directory }}/data"

    - name: Create {{ ansible_nas_app_name }} Container
      community.docker.docker_container:
        container_default_behavior: "compatibility"
        name: "{{ twofauth_container_name }}"
        hostname: "{{ twofauth_container_name }}"
        image: "{{ twofauth_image_name }}:{{ twofauth_image_tag }}"
        pull: true
        ports:
          - "{{ twofauth_port_http }}:8000"
        volumes:
          - "{{ twofauth_data_directory }}/data:/twofauth"
        network_mode: "bridge"
        env:
          APP_NAME: "{{ ansible_nas_app_name }}"
          APP_ENV: "local"
          APP_DEBUG: "false"
          SITE_OWNER: "{{ ansible_nas_email }}"
          APP_KEY: "{{ twofauth_app_key }}"
          # This variable must match your installation's external address.
          # Webauthn won't work otherwise.
          APP_URL: "https://{{ twofauth_hostname }}.{{ ansible_nas_domain }}"
          # If you want to serve js assets from a CDN (like https://cdn.example.com),
          # you need to set this custom URL here.
          # Otherwise, this should be the exact same value as APP_URL.
          ASSET_URL: "https://{{ twofauth_hostname }}.{{ ansible_nas_domain }}"
          IS_DEMO_APP: "false"
          LOG_CHANNEL: "daily"
          LOG_LEVEL: "notice"
          DB_DATABASE: "/srv/database/database.sqlite"
          CACHE_DRIVER: "file"
          SESSION_DRIVER: "file"
          # Mail settings
          MAIL_DRIVER: "{{ twofauth_mail_driver }}"
          MAIL_HOST: "{{ twofauth_mail_host }}"
          MAIL_PORT: "{{ twofauth_mail_port }}"
          MAIL_USERNAME: "{{ twofauth_mail_username }}"
          MAIL_PASSWORD: "{{ twofauth_mail_password }}"
          MAIL_ENCRYPTION: "{{ twofauth_mail_encryption }}"
          MAIL_FROM_NAME: "{{ twofauth_mail_from_name }}"
          MAIL_FROM_ADDRESS: "{{ twofauth_mail_from_addres }}"
          # SSL peer verification.
          # Set this to false to disable the SSL certificate validation.
          # WARNING
          # Disabling peer verification can result in a major security flaw.
          # Change it only if you know what you're doing.
          MAIL_VERIFY_SSL_PEER: "{{ twofauth_mail_verify_ssl_peer }}"
          THROTTLE_API: "60"
          LOGIN_THROTTLE: "5"
          # The default authentication guard
          # Supported:
          #   'web-guard' : The Laravel built-in auth system (default if nulled)
          #   'reverse-proxy-guard' : When 2FAuth is deployed behind a reverse-proxy that handle authentication
          # WARNING
          # When using 'reverse-proxy-guard' 2FAuth only look for the dedicated headers and skip all other built-in
          # authentication checks. That means your proxy is fully responsible of the authentication process, 2FAuth will
          # trust him as long as headers are presents.
          AUTHENTICATION_GUARD: "web-guard"
          # Name of the HTTP headers sent by the reverse proxy that identifies the authenticated user at proxy level.
          # Check your proxy documentation to find out how these headers are named (i.e 'REMOTE_USER', 'REMOTE_EMAIL', etc...)
          # (only relevant when AUTHENTICATION_GUARD is set to 'reverse-proxy-guard')
          AUTH_PROXY_HEADER_FOR_USER: "null"
          AUTH_PROXY_HEADER_FOR_EMAIL: "null"
          # Custom logout URL to open when using an auth proxy.
          PROXY_LOGOUT_URL: "null"
          # WebAuthn settings
          # Relying Party name, aka the name of the application. If null, defaults to APP_NAME
          WEBAUTHN_NAME: "2FAuth"
          # Relying Party ID. If null, the device will fill it internally.
          # See https://webauthn-doc.spomky-labs.com/prerequisites/the-relying-party#how-to-determine-the-relying-party-id
          WEBAUTHN_ID: "null"
          # Optional image data in BASE64 (128 bytes maximum) or an image url
          # See https://webauthn-doc.spomky-labs.com/prerequisites/the-relying-party#relying-party-icon
          WEBAUTHN_ICON: "null"
          # Use this setting to control how user verification behave during the
          # WebAuthn authentication flow.
          #
          # Most authenticators and smartphones will ask the user to actively verify
          # themselves for log in. For example, through a touch plus pin code,
          # password entry, or biometric recognition (e.g., presenting a fingerprint).
          # The intent is to distinguish one user from any other.
          #
          # Supported:
          #   'required': Will ALWAYS ask for user verification
          #   'preferred' (default) : Will ask for user verification IF POSSIBLE
          #   'discouraged' : Will NOT ask for user verification (for example, to minimize disruption to the user interaction flow)
          WEBAUTHN_USER_VERIFICATION: "preferred"
          #### SSO settings (for Socialite) ####
          # Uncomment and complete lines for the OAuth providers you want to enable.
          # - OPENID_AUTHORIZE_URL=
          # - OPENID_TOKEN_URL=
          # - OPENID_USERINFO_URL=
          # - OPENID_CLIENT_ID=
          # - OPENID_CLIENT_SECRET=
          # - GITHUB_CLIENT_ID=
          # - GITHUB_CLIENT_SECRET=
          # Use this setting to declare trusted proxied.
          # Supported:
          #   '*': to trust any proxy
          #   A comma separated IP list: The list of proxies IP to trust
          TRUSTED_PROXIES: "null"
          # Proxy for outgoing requests like new releases detection or logo fetching.
          # You can provide a proxy URL that contains a scheme, username, and password.
          # For example, "http://username:password@192.168.16.1:10".
          PROXY_FOR_OUTGOING_REQUESTS: "null"
          # Leave the following configuration vars as is.
          # Unless you like to tinker and know what you're doing.
          BROADCAST_DRIVER: "log"
          QUEUE_DRIVER: "sync"
          SESSION_LIFETIME: "120"
          REDIS_HOST: "127.0.0.1"
          REDIS_PASSWORD: "null"
          REDIS_PORT: "6379"
          PUSHER_APP_ID: ""
          PUSHER_APP_KEY: ""
          PUSHER_APP_SECRET: ""
          PUSHER_APP_CLUSTER: "mt1"
          VITE_PUSHER_APP_KEY: "${PUSHER_APP_KEY}"
          VITE_PUSHER_APP_CLUSTER: "${PUSHER_APP_CLUSTER}"
          MIX_ENV: "local"
          TZ: "{{ ansible_nas_timezone }}"
        labels:
          autoheal: "{{ twofauth_autoheal }}"
          com.centurylinklabs.watchtower.enable: "{{ twofauth_watchtower_enable }}"
          dockflare.enable: "{{ twofauth_dockflare_tunnel }}"
          dockflare.access.group: "{{ twofauth_dockflare_access_group }}"
          dockflare.hostname: "{{ twofauth_hostname }}.{{ ansible_nas_domain }}"
          dockflare.service: "http://{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}:{{ twofauth_port_http }}"
          homepage.name: "{{ ansible_nas_app_name }}"
          homepage.group: "{{ twofauth_homepage_group }}"
          homepage.href: "{{ twofauth_homepage_href }}"
          homepage.icon: "{{ twofauth_homepage_icon }}"
          homepage.siteMonitor: "http://{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}:{{ twofauth_port_http }}"
          homepage.description: "{{ 'A Web app to manage your Two-Factor Authentication (2FA) accounts' if homepage_show_description else omit }}"
          homepage.server: "my-docker"
          homepage.container: "{{ twofauth_container_name }}"
          homepage.showStats: "{{ twofauth_homepage_showstats }}"
          repliqate.enabled: "{{ twofauth_repliqate_enabled }}"
          repliqate.engine: "{{ twofauth_repliqate_engine }}"
          repliqate.schedule: "{{ twofauth_repliqate_schedule }}"
          repliqate.backup_id: "{{ twofauth_repliqate_backup_id }}"
          repliqate.retention: "{{ twofauth_repliqate_retention }}"
          traefik.enable: "{{ twofauth_available_externally | string }}"
          traefik.http.routers.twofauth.rule: "Host(`{{ twofauth_hostname }}.{{ ansible_nas_domain }}`)"
          traefik.http.routers.twofauth.tls.certresolver: "letsencrypt"
          traefik.http.routers.twofauth.tls.domains[0].main: "{{ ansible_nas_domain }}"
          traefik.http.routers.twofauth.tls.domains[0].sans: "*.{{ ansible_nas_domain }}"
          traefik.http.routers.frontend.middlewares: "{{ twofauth_hostname }}"
          traefik.http.routers.twofauth.middlewares: "{{ twofauth_hostname }}@docker"
          traefik.http.middlewares.twofauth.IPAllowList.sourcerange: "{{ twofauth_traefik_whitelist }}"
          traefik.http.services.twofauth.loadbalancer.server.port: "8000"
          wud.tag.include: '^v?\d+\.\d+\.\d+.*$'
          wud.tag.transform.type: "semver"
          wud.link.template: "https://github.com/2FAuth/2FAuth/releases"
        cpu_shares: "{{ twofauth_cpu_shares }}"
        memory: "{{ twofauth_memory_limit }}"
        restart_policy: unless-stopped

    - name: Access {{ ansible_nas_app_name }} at
      ansible.builtin.debug:
        msg: >-
              {{
                ['http://' + hostvars[inventory_hostname]['ansible_default_ipv4']['address'] + ':' + (twofauth_port_http | string)] +
                (['https://' + twofauth_hostname + '.' + ansible_nas_domain] if (twofauth_available_externally is true or twofauth_dockflare_tunnel is true) else [])
              }}
  when: twofauth_enabled is true

- name: Stop {{ ansible_nas_app_name }}
  block:
    - name: Stop {{ ansible_nas_app_name }} Container
      community.docker.docker_container:
        name: "{{ twofauth_container_name }}"
        state: absent
  when: twofauth_enabled is false

- name: Data Archive {{ ansible_nas_app_name }}
  block:
    - name: Check for {{ ansible_nas_app_name }} Data Directory
      stat:
        path: "{{ twofauth_data_directory }}"
      register: dir_stat

    - name: Archive {{ ansible_nas_app_name }} Data Directory
      ansible.builtin.archive:
        path: "{{ twofauth_data_directory }}"
        dest: "{{ docker_home }}/{{ ansible_nas_app_name | lower }}.zip"
        force_archive: true
        format: zip
        owner: ansible-nas
        group: ansible-nas
        mode: u=rw,g=rw
        remove: true
      when: dir_stat.stat.exists
  when: twofauth_enabled is false and archive_app_data_enabled is true
