---
ansible_nas_app_name: "Speedtest Tracker"

speedtest_tracker_enabled: false
speedtest_tracker_available_externally: false
speedtest_tracker_traefik_whitelist: "{{ lan }}"

# directories
speedtest_tracker_data_directory: "{{ docker_home }}/speedtest-tracker"

# uid / gid
speedtest_tracker_puid: "1000"
speedtest_tracker_pgid: "1000"

# network
speedtest_tracker_port: "8765"
speedtest_tracker_hostname: "speedtest-tracker"

# docker
speedtest_tracker_container_name: "speedtest-tracker"
speedtest_tracker_image_name: "henrywhitaker3/speedtest-tracker"
speedtest_tracker_image_version: "latest"

# app
speedtest_tracker_auth: "false"

# dockflare
speedtest_tracker_dockflare_tunnel: "false"

# specs
speedtest_tracker_cpu_shares: 1024
speedtest_tracker_memory: 256m

# autoheal
speedtest_tracker_autoheal: "false"

# dockflare
speedtest_tracker_dockflare_tunnel: "false"
speedtest_tracker_dockflare_access_group: ""

# homepage
speedtest_tracker_homepage_group: "Network"
speedtest_tracker_homepage_icon: "speedtest-tracker.png"
speedtest_tracker_homepage_href: "http://{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}:{{ speedtest_tracker_port }}"
speedtest_tracker_homepage_showStats: "false"
speedtest_tracker_homepage_widget_version: "1" # version 2 is only compatible with alexjustesen/speedtest-tracker

# watchtower
speedtest_tracker_watchtower_monitor_only: "true"