---
# ANE
filebrowser_proper_name: "File Browser"
filebrowser_enabled: false
filebrowser_traefik_enabled: false
filebrowser_traefik_whitelist: "{{ lan }}"
filebrowser_data_directory: "{{ docker_home }}/filebrowser"

# network
filebrowser_port_http: "9013"
filebrowser_hostname: "filebrowser"

# user to run container with
filebrowser_user_id: "0"
filebrowser_group_id: "0"

# app
filebrowser_root_dir: "/"

# docker
filebrowser_container_name: "filebrowser"
filebrowser_image_name: "filebrowser/filebrowser"
filebrowser_image_tag: "latest"

# specs
filebrowser_cpu_shares: 1024
filebrowser_memory: "256M"
filebrowser_memory_swap: -1

# autoheal
filebrowser_autoheal_enabled: false

# dockflare
filebrowser_dockflare_enabled: false
filebrowser_dockflare_access_group: ""

# homepage
filebrowser_homepage_group: "Apps"
filebrowser_homepage_icon: "filebrowser.png"
filebrowser_homepage_href: "http://{{ hostvars[inventory_hostname]['ansible_facts']['default_ipv4']['address'] }}:{{ filebrowser_port_http }}"
filebrowser_homepage_showstats: false

# repliqate
filebrowser_repliqate_enabled: false
filebrowser_repliqate_engine: "restic"
filebrowser_repliqate_schedule: "@daily 3am"
filebrowser_repliqate_backup_id: "{{ filebrowser_container_name }}"
filebrowser_repliqate_retention: "30d"

# tinyauth
filebrowser_tinyauth_enabled: false

# watchtower
filebrowser_watchtower_enabled: false