---
- name: Start {{ tasksmd_proper_name }}
  block:
    - name: Create {{ tasksmd_proper_name }} Directories
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
      with_items:
        - "{{ tasksmd_data_directory }}"
        - "{{ tasksmd_data_directory }}/config"
        - "{{ tasksmd_data_directory }}/tasks"

    - name: Set {{ tasksmd_proper_name }} FQDN var overrides
      ansible.builtin.set_fact:
        tasksmd_homepage_href: "https://{{ tasksmd_hostname }}.{{ ansible_nas_domain }}"
      when: tasksmd_traefik_enabled | bool or tasksmd_dockflare_enabled | bool

    - name: Create {{ tasksmd_proper_name }} Container
      community.docker.docker_container:
        container_default_behavior: "compatibility"
        name: "{{ tasksmd_container_name }}"
        hostname: "{{ tasksmd_container_name }}"
        image: "{{ tasksmd_image_name }}:{{ tasksmd_image_tag }}"
        pull: true
        ports:
          - "{{ tasksmd_port_http }}:8080"
        volumes:
          - "{{ tasksmd_data_directory }}/config:/config"
          - "{{ tasksmd_data_directory }}/tasks:/tasks"
        network_mode: bridge
        env:
          PUID: "{{ tasksmd_puid }}"
          PGID: "{{ tasksmd_pgid }}"
          TZ: "{{ ansible_nas_timezone }}"
        labels:
          autoheal: "{{ tasksmd_autoheal_enabled | ternary('true', 'false') }}"
          com.centurylinklabs.watchtower.enable: "{{ tasksmd_watchtower_enabled | ternary('true', 'false') }}"
          dockflare.enable: "{{ tasksmd_dockflare_enabled | ternary('true', 'false') }}"
          dockflare.access.group: "{{ tasksmd_dockflare_access_group }}"
          dockflare.hostname: "{{ tasksmd_hostname }}.{{ ansible_nas_domain }}"
          dockflare.service: "http://{{ hostvars[inventory_hostname]['ansible_facts']['default_ipv4']['address'] }}:{{ tasksmd_port_http }}"
          homepage.name: "{{ tasksmd_proper_name }}"
          homepage.group: "{{ tasksmd_homepage_group }}"
          homepage.icon: "{{ tasksmd_homepage_icon }}"
          homepage.href: "{{ tasksmd_homepage_href }}"
          homepage.siteMonitor: "http://{{ hostvars[inventory_hostname]['ansible_facts']['default_ipv4']['address'] }}:{{ tasksmd_port_http }}"
          homepage.description: "{{ 'a self-hosted, Markdown file based task management board' if homepage_show_description else omit }}"
          homepage.server: "my-docker"
          homepage.container: "{{ tasksmd_container_name }}"
          homepage.showStats: "{{ tasksmd_homepage_showstats | ternary('true', 'false') }}"
          repliqate.enabled: "{{ tasksmd_repliqate_enabled | ternary('true', 'false') }}"
          repliqate.engine: "{{ tasksmd_repliqate_engine }}"
          repliqate.schedule: "{{ tasksmd_repliqate_schedule }}"
          repliqate.backup_id: "{{ tasksmd_repliqate_backup_id }}"
          repliqate.retention: "{{ tasksmd_repliqate_retention }}"
          traefik.enable: "{{ tasksmd_traefik_enabled | ternary('true', 'false') }}"
          traefik.http.routers.tasksmd.rule: "Host(`{{ tasksmd_hostname }}.{{ ansible_nas_domain }}`)"
          traefik.http.routers.tasksmd.tls.certresolver: "letsencrypt"
          traefik.http.routers.tasksmd.tls.domains[0].main: "{{ ansible_nas_domain }}"
          traefik.http.routers.tasksmd.tls.domains[0].sans: "*.{{ ansible_nas_domain }}"
          traefik.http.routers.tasksmd.middlewares: "tasksmd@docker{{ ',tinyauth-auth@docker' if tasksmd_tinyauth_enabled | bool else '' }}"
          traefik.http.middlewares.tasksmd.IPAllowList.sourcerange: "{{ tasksmd_traefik_whitelist }}"
          traefik.http.services.tasksmd.loadbalancer.server.port: "8080"
          wud.tag.include: '^\d+\.\d+.*$'
          wud.tag.transform.type: "semver"
          wud.link.template: "https://hub.docker.com/r/baldissaramatheus/tasks.md"
        cpu_shares: "{{ tasksmd_cpu_shares }}"
        memory: "{{ tasksmd_memory }}"
        memory_swap: "{{ tasksmd_memory_swap }}"
        restart_policy: unless-stopped

    - name: Access {{ tasksmd_proper_name }} at
      ansible.builtin.debug:
        msg: >-
              {{
                ['http://' + hostvars[inventory_hostname]['ansible_facts']['default_ipv4']['address'] + ':' + (tasksmd_port_http | string)] +
                (['https://' + tasksmd_hostname + '.' + ansible_nas_domain] if (tasksmd_traefik_enabled is true or tasksmd_dockflare_enabled is true) else [])
              }}
  when: tasksmd_enabled is true

- name: Stop {{ tasksmd_proper_name }}
  block:
    - name: Stop {{ tasksmd_proper_name }} Container
      community.docker.docker_container:
        name: "{{ tasksmd_container_name }}"
        state: absent
  when: tasksmd_enabled is false

- name: Data Archive {{ tasksmd_proper_name }}
  include_role:
    name: ansible-nas-archive
  vars:
    target_data_dir: "{{ tasksmd_data_directory }}"
  when:
    - archive_app_data_enabled is true
    - tasksmd_enabled is false