---
- name: Start {{ ansible_nas_app_name }}
  block:
    - name: Create {{ ansible_nas_app_name }} Directories
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
      with_items:
        - "{{ tvheadend_data_directory }}"
        - "{{ tvheadend_data_directory }}/config"

    - name: Create {{ ansible_nas_app_name }} Container
      community.docker.docker_container:
        container_default_behavior: "compatibility"
        name: "{{ tvheadend_container_name }}"
        hostname: "{{ tvheadend_container_name }}"
        image: "{{ tvheadend_image_name }}:{{ tvheadend_image_tag }}"
        pull: true
        volumes:
          - "{{ tvheadend_data_directory }}/config:/config"
          - "{{ tvheadend_tv_directory }}:/recordings"
        ports:
          - "{{ tvheadend_port_http }}:9981"
          - "{{ tvheadend_port_htsp }}:9982"
        env:
          DOCKER_MODS: "{{ tvheadend_env_docker_mods }}"
          INSTALL_PACKAGES: "{{ tvheadend_env_docker_mods_install_packages }}"
          INSTALL_PIP_PACKAGES: "{{ tvheadend_env_docker_mods_install_pip_packages}}"
          PUID: "{{ tvheadend_user_id }}"
          PGID: "{{ tvheadend_group_id }}"
          RUN_OPTS: "{{ tvheadend_env_run_opts }}"
          TZ: "{{ ansible_nas_timezone }}"
        labels:
          autoheal: "{{ tvheadend_autoheal | string }}"
          com.centurylinklabs.watchtower.enable: "{{ tvheadend_watchtower_enabled| string }}"
          dockflare.enable: "{{ tvheadend_dockflare_enabled | string }}"
          dockflare.access.group: "{{ tvheadend_dockflare_access_group }}"
          dockflare.hostname: "{{ tvheadend_hostname }}.{{ ansible_nas_domain }}"
          dockflare.service: "http://{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}:{{ tvheadend_port_http }}"
          homepage.name: "{{ ansible_nas_app_name }}"
          homepage.group: "{{ tvheadend_homepage_group }}"
          homepage.icon: "{{ tvheadend_homepage_icon }}"
          homepage.href: "{{ tvheadend_homepage_href }}"
          homepage.description: "{{ 'tvheadend description' if homepage_show_description else omit }}"
          homepage.server: "my-docker"
          homepage.container: "{{ tvheadend_container_name }}"
          homepage.showStats: "{{ tvheadend_homepage_showstats | string }}"
          homepage.siteMonitor: "http://{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}:{{ tvheadend_port_http }}"
          repliqate.enabled: "{{ tvheadend_repliqate_enabled | string }}"
          repliqate.engine: "{{ tvheadend_repliqate_engine }}"
          repliqate.schedule: "{{ tvheadend_repliqate_schedule }}"
          repliqate.backup_id: "{{ tvheadend_repliqate_backup_id }}"
          repliqate.retention: "{{ tvheadend_repliqate_retention }}"
          traefik.enable: "{{ tvheadend_available_externally | string }}"
          traefik.http.routers.tvheadend.rule: "Host(`{{ tvheadend_hostname }}.{{ ansible_nas_domain }}`)"
          traefik.http.routers.tvheadend.tls.certresolver: "letsencrypt"
          traefik.http.routers.tvheadend.tls.domains[0].main: "{{ ansible_nas_domain }}"
          traefik.http.routers.tvheadend.tls.domains[0].sans: "*.{{ ansible_nas_domain }}"
          traefik.http.routers.tvheadend.middlewares: "tvheadend@docker{{ ',tinyauth-auth@docker' if tvheadend_tinyauth_enabled | bool else '' }}"
          traefik.http.middlewares.tvheadend.IPAllowList.sourcerange: "{{ tvheadend_traefik_whitelist }}"
          traefik.http.services.tvheadend.loadbalancer.server.port: "80"
          wud.tag.include: '^version-\d+\.\d+.*$'
          wud.tag.transform.type: "semver"
          wud.link.template: "lscr.io/linuxserver/tvheadend"
        cpu_shares: "{{ tvheadend_cpu_shares }}"
        devices: "{{ tvheadend_devices | default(omit) }}"
        memory: "{{ tvheadend_memory }}"
        restart_policy: unless-stopped

    - name: Access {{ ansible_nas_app_name }} at
      ansible.builtin.debug:
        msg: >-
              {{
                ['http://' + hostvars[inventory_hostname]['ansible_default_ipv4']['address'] + ':' + (tvheadend_port_http | string)] +
                (['https://' + tvheadend_hostname + '.' + ansible_nas_domain] if (tvheadend_available_externally is true or tvheadend_dockflare_enabled is true) else [])
              }}
  when: tvheadend_enabled is true

- name: Stop {{ ansible_nas_app_name }}
  block:
    - name: Stop {{ ansible_nas_app_name }} Container
      community.docker.docker_container:
        name: "{{ tvheadend_container_name }}"
        state: absent
  when: tvheadend_enabled is false

- name: Data Archive {{ ansible_nas_app_name }}
  include_role:
    name: ansible-nas-archive
  vars:
    target_data_dir: "{{ tvheadend_data_directory }}"
  when:
    - archive_app_data_enabled is true
    - tvheadend_enabled is false