---
- name: Start {{ ansible_nas_app_name }}
  block:
    - name: Create Booksonic Directories
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        mode: 0755
      with_items:
        - "{{ booksonic_data_directory }}/data"
        - "{{ booksonic_data_directory }}/playlists"

    - name: Create {{ ansible_nas_app_name }} Container
      community.docker.docker_container:
        container_default_behavior: "compatibility"
        name: "{{ booksonic_container_name }}"
        hostname: "{{ booksonic_container_name }}"
        image: "{{ booksonic_image_name }}:{{ booksonic_image_tag }}"
        pull: true
        volumes:
          - "{{ booksonic_data_directory }}/data:/booksonic/data:rw"
          - "{{ booksonic_data_directory }}/playlists:/booksonic/playlists:rw"
          - "{{ booksonic_audiobooks_directory }}:/booksonic/audiobooks:rw"
          - "{{ booksonic_podcasts_directory }}:/booksonic/podcasts:rw"
        ports:
          - "{{ booksonic_port }}:4040"
        env:
          TZ: "{{ ansible_nas_timezone }}"
          PUID: "{{ booksonic_user_id }}"
          PGID: "{{ booksonic_group_id }}"
        labels:
          autoheal: "{{ booksonic_autoheal }}"
          com.centurylinklabs.watchtower.monitor-only: "{{ booksonic_watchtower_monitor_only }}"
          homepage.name: "{{ ansible_nas_app_name }}"
          homepage.group: "{{ booksonic_homepage_group }}"
          homepage.icon: "{{ booksonic_homepage_icon }}"
          homepage.href: "{{ booksonic_homepage_href }}"
          homepage.description: "{{ 'booksonic description' if homepage_show_description else omit }}"
          homepage.server: "my-docker"
          homepage.container: "{{ booksonic_container_name }}"
          homepage.showStats: "{{ booksonic_homepage_showStats }}"
          homepage.siteMonitor: "http://{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}:{{ booksonic_port }}"
          traefik.enable: "{{ booksonic_available_externally | string }}"
          traefik.http.routers.booksonic.rule: "Host(`{{ booksonic_hostname }}.{{ ansible_nas_domain }}`)"
          traefik.http.routers.booksonic.tls.certresolver: "letsencrypt"
          traefik.http.routers.booksonic.tls.domains[0].main: "{{ ansible_nas_domain }}"
          traefik.http.routers.booksonic.tls.domains[0].sans: "*.{{ ansible_nas_domain }}"
          traefik.http.routers.frontend.middlewares: "{{ booksonic_hostname }}"
          traefik.http.routers.booksonic.middlewares: "{{ booksonic_hostname }}@docker"
          traefik.http.middlewares.booksonic.IPAllowList.sourcerange: "{{ booksonic_traefik_whitelist }}"
          traefik.http.services.booksonic.loadbalancer.server.port: "4040"
          wud.tag.include: '^\d+\.\d+\.\d+$$'
          wud.link.template: "https://github.com/popeen/Booksonic-Air/releases/tag/$${major}.$${minor}.$${patch}"
        cpu_shares: "{{ booksonic_cpu_shares }}"
        memory: "{{ booksonic_memory }}"
        restart_policy: unless-stopped
  when: booksonic_enabled is true

- name: Stop {{ ansible_nas_app_name }}
  block:
    - name: Stop {{ ansible_nas_app_name }} Container
      community.docker.docker_container:
        name: "{{ booksonic_container_name }}"
        state: absent
  when: booksonic_enabled is false

- name: Data Archive {{ ansible_nas_app_name }}
  block:
    - name: Check for {{ ansible_nas_app_name }} Data Directory
      stat:
        path: "{{ booksonic_data_directory }}"
      register: dir_stat

    - name: Archive {{ ansible_nas_app_name }} Data Directory
      ansible.builtin.archive:
        path: "{{ booksonic_data_directory }}"
        dest: "{{ docker_home }}/{{ ansible_nas_app_name | lower }}.zip"
        force_archive: true
        format: zip
        owner: ansible-nas
        group: ansible-nas
        mode: u=rw,g=rw
        remove: true
      when: dir_stat.stat.exists
  when: booksonic_enabled is false and archive_app_data_enabled is true
