---
# ANE
ansible_nas_app_name: "Chatpad AI"
chatpadai_enabled: false
chatpadai_available_externally: false
chatpadai_traefik_whitelist: "{{ lan }}"

# network
chatpadai_hostname: "chatpadai"
chatpadai_port_http: "9009"

# docker
chatpadai_container_name: "chatpadai"
chatpadai_image_name: "ghcr.io/deiucanta/chatpad"
chatpadai_image_tag: "latest"
chatpadai_cpu_shares: 1024
chatpadai_memory: "512M"

# autoheal
chatpadai_autoheal: "false"

# dockflare
chatpadai_dockflare_tunnel: "false"
chatpadai_dockflare_access_group: ""

# homepage
chatpadai_homepage_group: "Apps"
chatpadai_homepage_icon: "chatpad-ai.png"
chatpadai_homepage_href: "http://{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}:{{ chatpadai_port_http }}"
chatpadai_homepage_showstats: "false"

# watchtower
chatpadai_watchtower_enable: "false"
