---
- name: Start {{ ansible_nas_app_name }}
  block:
    - name: Create {{ ansible_nas_app_name }} Directories
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
      with_items:
        - "{{ qdirstat_data_directory }}"
        - "{{ qdirstat_data_directory }}/config"

    - name: Create {{ ansible_nas_app_name }} Container
      community.docker.docker_container:
        container_default_behavior: "compatibility"
        name: "{{ qdirstat_container_name }}"
        hostname: "{{ qdirstat_container_name }}"
        image: "{{ qdirstat_image_name }}:{{ qdirstat_image_tag }}"
        pull: true
        volumes:
          - "{{ qdirstat_data_directory }}/config:/config:rw"
          - "{{ qdirstat_storage_directory }}:/storage:ro"
        ports:
          - "{{ qdirstat_port_http }}:{{ qdirstat_port_http }}"
          - "{{ qdirstat_port_vnc }}:{{ qdirstat_port_vnc }}"
        env:
          VNC_LISTENING_PORT: "{{ qdirstat_port_vnc }}"
          VNC_PASSWORD: "{{ qdirstat_env_vnc_password }}"
          WEB_LISTENING_PORT: "{{ qdirstat_port_http }}"
          TZ: "{{ ansible_nas_timezone }}"
        labels:
          autoheal: "{{ qdirstat_autoheal_enabled | ternary('true', 'false') }}"
          com.centurylinklabs.watchtower.enable: "{{ qdirstat_watchtower_enabled | ternary('true', 'false') }}"
          dockflare.enable: "{{ qdirstat_dockflare_enabled | ternary('true', 'false') }}"
          dockflare.access.group: "{{ qdirstat_dockflare_access_group }}"
          dockflare.hostname: "{{ qdirstat_hostname }}.{{ ansible_nas_domain }}"
          dockflare.service: "http://{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}:{{ qdirstat_port_http }}"
          homepage.name: "{{ ansible_nas_app_name }}"
          homepage.group: "{{ qdirstat_homepage_group }}"
          homepage.href: "{{ qdirstat_homepage_href }}"
          homepage.icon: "{{ qdirstat_homepage_icon }}"
          homepage.siteMonitor: "http://{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}:{{ qdirstat_port_http }}"
          homepage.description: "{{ 'Qt-based directory statistics' if homepage_show_description else omit }}"
          homepage.server: "my-docker"
          homepage.container: "{{ qdirstat_container_name }}"
          homepage.showStats: "{{ qdirstat_homepage_showstats | ternary('true', 'false') }}"
          repliqate.enabled: "{{ qdirstat_repliqate_enabled | ternary('true', 'false') }}"
          repliqate.engine: "{{ qdirstat_repliqate_engine }}"
          repliqate.schedule: "{{ qdirstat_repliqate_schedule }}"
          repliqate.backup_id: "{{ qdirstat_repliqate_backup_id }}"
          repliqate.retention: "{{ qdirstat_repliqate_retention }}"
          traefik.enable: "{{ qdirstat_traefik_enabled | ternary('true', 'false') }}"
          traefik.http.routers.qdirstat.rule: "Host(`{{ qdirstat_hostname }}.{{ ansible_nas_domain }}`)"
          traefik.http.routers.qdirstat.tls.certresolver: "letsencrypt"
          traefik.http.routers.qdirstat.tls.domains[0].main: "{{ ansible_nas_domain }}"
          traefik.http.routers.qdirstat.tls.domains[0].sans: "*.{{ ansible_nas_domain }}"
          traefik.http.routers.qdirstat.middlewares: "qdirstat@docker{{ ',tinyauth-auth@docker' if qdirstat_tinyauth_enabled | bool else '' }}"
          traefik.http.middlewares.qdirstat.IPAllowList.sourcerange: "{{ qdirstat_traefik_whitelist }}"
          traefik.http.services.qdirstat.loadbalancer.server.port: "{{ qdirstat_port_http }}"
          wud.tag.include: '^v\d+\.\d+\.\d+$'
          wud.tag.transform.type: "semver"
          wud.link.template: "https://github.com/jlesage/docker-qdirstat/pkgs/container/qdirstat"
        cpu_shares: "{{ qdirstat_cpu_shares }}"
        memory: "{{ qdirstat_memory }}"
        restart_policy: unless-stopped

    - name: Access {{ ansible_nas_app_name }} at
      ansible.builtin.debug:
        msg: >-
          {{
            [
              'http://' ~ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] ~ ':' ~ qdirstat_port_http
            ] + (
              [
                'https://' ~ qdirstat_hostname ~ '.' ~ ansible_nas_domain,
                'vnc://' ~ qdirstat_hostname ~ '.' ~ ansible_nas_domain ~ ':' ~ qdirstat_port_vnc
              ]
              if (qdirstat_traefik_enabled is true or qdirstat_dockflare_enabled is true) else []
            ) + [
              'vnc://' ~ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] ~ ':' ~ qdirstat_port_vnc
            ]
          }}
  when: qdirstat_enabled is true

- name: Stop {{ ansible_nas_app_name }}
  block:
    - name: Stop {{ ansible_nas_app_name }} Container
      community.docker.docker_container:
        name: "{{ qdirstat_container_name }}"
        state: absent
  when: qdirstat_enabled is false

- name: Data Archive {{ ansible_nas_app_name }}
  include_role:
    name: ansible-nas-archive
  vars:
    target_data_dir: "{{ qdirstat_data_directory }}"
  when:
    - archive_app_data_enabled is true
    - qdirstat_enabled is false