---
# ANE
ansible_nas_app_name: "GoToSocial"
gotosocial_enabled: false
gotosocial_traefik_enabled: false
gotosocial_traefik_whitelist: "{{ lan }}"
gotosocial_data_directory: "{{ docker_home }}/gotosocial"

# network
gotosocial_hostname: "gotosocial"
gotosocial_port_http: "3046"

# docker
gotosocial_container_name: "gotosocial"
gotosocial_image_name: "superseriousbusiness/gotosocial"
gotosocial_image_tag: "latest"  # or snapshot better?

# specs
gotosocial_cpu_shares: 1024
gotosocial_memory: "1G"
gotosocial_memory_swap: -1

# autoheal
gotosocial_autoheal_enabled: false

# dockflare
gotosocial_dockflare_enabled: false
gotosocial_dockflare_access_group: ""

# homepage
gotosocial_homepage_group: "Apps"
gotosocial_homepage_icon: "gotosocial.png"
gotosocial_homepage_href: "http://{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}:{{ gotosocial_port_http }}"
gotosocial_homepage_showstats: false

# repliqate
gotosocial_repliqate_enabled: false
gotosocial_repliqate_engine: "restic"
gotosocial_repliqate_schedule: "@daily 3am"
gotosocial_repliqate_backup_id: "{{ gotosocial_container_name }}"
gotosocial_repliqate_retention: "30d"

# tinyauth
gotosocial_tinyauth_enabled: false

# watchtower
gotosocial_watchtower_enabled: false