---
# ANE
ansible_nas_app_name: "MyBibliotheca"
mybibliotheca_enabled: false
mybibliotheca_available_externally: false
mybibliotheca_traefik_whitelist: "{{ lan }}"

# directories
mybibliotheca_data_directory: "{{ docker_home }}/mybibliotheca"

# docker
mybibliotheca_container_name: "mybibliotheca"
mybibliotheca_image_name: "pickles4evaaaa/mybibliotheca"
mybibliotheca_image_tag: "1.1.1"

# network
mybibliotheca_port_http: "5054"
mybibliotheca_hostname: "mybibliotheca"

# specs
mybibliotheca_cpu_shares: 1024
mybibliotheca_memory: "1G"
mybibliotheca_memory_swap: -1

# autoheal
mybibliotheca_autoheal: "false"

# dockflare
mybibliotheca_dockflare_tunnel: "false"
mybibliotheca_dockflare_access_group: ""

# homepage
mybibliotheca_homepage_group: "Apps"
mybibliotheca_homepage_icon: "mdi-bookshelf" #something better? 📚
mybibliotheca_homepage_href: "http://{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}:{{ mybibliotheca_port_http }}"
mybibliotheca_homepage_showstats: "false"

# repliqate
mybibliotheca_repliqate_enabled: "false"
mybibliotheca_repliqate_engine: "restic"
mybibliotheca_repliqate_schedule: "@daily 3am"
mybibliotheca_repliqate_backup_id: "{{ mybibliotheca_container_name }}"
mybibliotheca_repliqate_retention: "30d"

# tinyauth
mybibliotheca_tinyauth_enabled: false

# watchtower
mybibliotheca_watchtower_enable: "false"
