---
# ANE
ansible_nas_app_name: "netboot.xyz"
netbootxyz_enabled: false
netbootxyz_available_externally: false
netbootxyz_traefik_whitelist: "{{ lan }}"

# directories
netbootxyz_data_directory: "{{ docker_home }}/netbootxyz"

# network
netbootxyz_hostname: "netbootxyz"
netbootxyz_hostname2: "netbootxyz-assets"
netbootxyz_port_http: "3072"
netbootxyz_port_http2: "5803"

# docker
netbootxyz_container_name: "netbootxyz"
netbootxyz_image_name: "ghcr.io/netbootxyz/netbootxyz"
netbootxyz_image_version: "latest"

netbootxyz_user_id: "1000"
netbootxyz_group_id: "1000"

# specs
netbootxyz_cpu_shares: 1024
netbootxyz_memory: "512M"
netbootxyz_memory_swap: -1

# autoheal
netbootxyz_autoheal: "false"

# dockflare
netbootxyz_dockflare_tunnel: "false"
netbootxyz_dockflare_access_group: ""

# homepage
netbootxyz_homepage_group: "Apps"
netbootxyz_homepage_icon: "netbootxyz.png"
netbootxyz_homepage_href: "http://{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}:{{ netbootxyz_port_http }}"
netbootxyz_homepage_showstats: "false"

# repliqate
netbootxyz_repliqate_enabled: "false"
netbootxyz_repliqate_engine: "restic"
netbootxyz_repliqate_schedule: "@daily 3am"
netbootxyz_repliqate_backup_id: "{{ netbootxyz_container_name }}"
netbootxyz_repliqate_retention: "30d"

# tinyauth
netbootxyz_tinyauth_enabled: false

# watchtower
netbootxyz_watchtower_enable: "false"
