---
# ANE
ansible_nas_app_name: "Open Payment Host"
openpaymenthost_enabled: false
openpaymenthost_traefik_enabled: false
openpaymenthost_traefik_whitelist: "{{ lan }}"

# directories
openpaymenthost_data_directory: "{{ docker_home }}/openpaymenthost"

# docker
openpaymenthost_container_name: "open-payment-host"
openpaymenthost_image_name: "abishekmuthian/open-payment-host"
openpaymenthost_image_tag: "latest"

# network
openpaymenthost_hostname: "openpaymenthost"
openpaymenthost_port_http: "3000"

# specs
openpaymenthost_cpu_shares: 1024
openpaymenthost_memory: "1G"
openpaymenthost_memory_swap: -1

# app
#https://github.com/abishekmuthian/open-payment-host

# autoheal
openpaymenthost_autoheal_enabled: false

# dockflare
openpaymenthost_dockflare_enabled: false
openpaymenthost_dockflare_access_group: ""

# homepage
openpaymenthost_homepage_group: "Apps"
openpaymenthost_homepage_icon: "openpaymenthost.png"
openpaymenthost_homepage_href: "http://{{ hostvars[inventory_hostname]['ansible_facts']['default_ipv4']['address'] }}:{{ openpaymenthost_port_http }}"
openpaymenthost_homepage_showstats: false

# tinyauth
openpaymenthost_tinyauth_enabled: false

# watchtower
openpaymenthost_watchtower_enabled: false