---
# ANE
ansible_nas_app_name: "RomM"
romm_enabled: false
romm_available_externally: false
romm_traefik_whitelist: "{{ lan }}"

# directories
romm_data_directory: "{{ docker_home }}/romm"
romm_roms_directory: "{{ roms_root }}"

# network
romm_port_http: "8484"
romm_hostname: "romm"

# docker
romm_container_name: "romm"
romm_image_name: "ghcr.io/rommapp/romm"
romm_image_version: "latest"
romm_db_container_name: "romm-db"
romm_db_image_name: "mariadb"
romm_db_image_version: "11.2"
romm_redis_container_name: "romm-redis"
romm_redis_image_name: "redis"
romm_redis_image_version: "alpine"

# specs
romm_cpu_shares: 1024
romm_memory: 1g
romm_db_cpu_shares: 1024
romm_db_memory: 1g
romm_redis_cpu_shares: 1024
romm_redis_memory: 1g

# app
romm_database_username: "romm-user"
romm_database_password: "topsecret"
romm_database_root_password: "top_topsecret"
# RomM auth config
romm_auth_secret_key: "36ba154a0ce8fe34865b59c7a38596c50340a30ce2d5e9523ad387d663fd74b" # Generate a new key with `openssl rand -hex 32`
romm_auth_username: "admin"
romm_auth_password: "{{ ansible_nas_app_admin_password }}"
# IGDB auth credentials - see https://github.com/zurdi15/romm/tree/release#-docker for more info
romm_igdb_client_id: "abcd"
romm_igdb_client_secret: "abcd"
# MobyGames auth credentials
romm_mobygames_client_id: "abcd"
# SteamGridDB auth credentials
romm_steamgriddb_client_id: "abcd"

# autoheal
romm_autoheal: "false"
romm_db_autoheal: "false"
romm_redis_autoheal: "false"

# dockflare
romm_dockflare_tunnel: "false"
romm_dockflare_access_group: ""

# homepage
romm_homepage_group: "Apps"
romm_homepage_icon: "romm.png"
romm_homepage_href: "http://{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}:{{ romm_port_http }}"
romm_homepage_showstats: "false"
romm_homepage_widget_username: "{{ romm_auth_username }}"
romm_homepage_widget_password: "{{ romm_auth_password }}"
romm_homepage_widget_fields: '["platforms", "totalRoms", "saves", "states"]' # optional - default fields shown
romm_db_homepage_group: "DBs"
romm_db_homepage_icon: "mariadb.png"
romm_db_homepage_href: "http://{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}:{{ romm_port_http }}"
romm_db_homepage_showstats: "false"
romm_redis_homepage_group: "DBs"
romm_redis_homepage_icon: "redis.png"
romm_redis_homepage_href: "http://{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}:{{ romm_port_http }}"
romm_redis_homepage_showstats: "false"

# repliqate
romm_repliqate_enabled: "false"
romm_repliqate_engine: "restic"
romm_repliqate_schedule: "@daily 3am"
romm_repliqate_backup_id: "{{ romm_container_name }}"
romm_repliqate_retention: "30d"
romm_db_repliqate_enabled: "false"
romm_db_repliqate_engine: "restic"
romm_db_repliqate_schedule: "@daily 3am"
romm_db_repliqate_backup_id: "{{ romm_container_name }}"
romm_db_repliqate_retention: "30d"
romm_redis_repliqate_enabled: "false"
romm_redis_repliqate_engine: "restic"
romm_redis_repliqate_schedule: "@daily 3am"
romm_redis_repliqate_backup_id: "{{ romm_container_name }}"
romm_redis_repliqate_retention: "30d"

# watchtower
romm_watchtower_enable: "false"
romm_db_watchtower_enable: "false"
romm_redis_watchtower_enable: "false"