---
ansible_nas_app_name: "Agent DVR"

ispyagentdvr_enabled: false
ispyagentdvr_available_externally: false
ispyagentdvr_traefik_whitelist: "{{ lan }}"

# directories
ispyagentdvr_data_directory: "{{ docker_home }}/ispyagentdvr"
ispyagentdvr_recordings_directory: "{{ downloads_root }}/recordings"

# uid / gid
ispyagentdvr_user_id: "1000"
ispyagentdvr_group_id: "1000"

# network
ispyagentdvr_webui_port: "8097"
ispyagentdvr_turn_port: "3478"
ispyagentdvr_agentdvr_host_port: "50000-50010"
ispyagentdvr_cpu_shares: 1024

# specs
ispyagentdvr_memory: 1g

# docker
ispyagentdvr_container_name: ispyagentdvr

# autoheal
ispyagentdvr_autoheal: "false"

# watchtower
ispyagentdvr_watchtower_monitor_only: "true"