---
# This app was archived by the owner on Jan 20, 2022.
- name: Start {{ ansible_nas_app_name }}
  block:
    - name: Create {{ ansible_nas_app_name }} Directories
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
      with_items:
        - "{{ magnetico_data_directory }}"
        - "{{ magnetico_data_directory }}/config"
        - "{{ magnetico_data_directory }}/data"

    - name: Install python3-passlib package
      ansible.builtin.apt:
        pkg:
          - python3-passlib
        state: present

    - name: Create {{ ansible_nas_app_name }} Web UI password file
      community.general.htpasswd:
        path: "{{ magnetico_data_directory }}/config/credentials"
        name: "{{ magnetico_username }}"
        password: "{{ magnetico_password }}"
        crypt_scheme: bcrypt
        mode: '0640'
        create: true

    - name: Create {{ ansible_nas_app_name }} Crawler Container
      community.docker.docker_container:
        container_default_behavior: "compatibility"
        name: "{{ magneticod_container_name }}"
        hostname: "{{ magneticod_container_name }}"
        image: "{{ magneticod_image_name }}:{{ magneticod_image_tag }}"
        pull: true
        volumes:
          - "{{ magnetico_data_directory }}/config:/root/.config/magneticod"
          - "{{ magnetico_data_directory }}/data:/root/.local/share/magneticod"
        env:
          TZ: "{{ ansible_nas_timezone }}"
        command:
          - "--indexer-addr=0.0.0.0:1212"
        labels:
          autoheal: "{{ magneticod_autoheal | string }}"
          com.centurylinklabs.watchtower.enable: "{{ magnetico_watchtower_enabled| string }}"
          dockflare.enable: "false"
          homepage.name: "{{ ansible_nas_app_name }} Crawler"
          homepage.group: "{{ magneticod_homepage_group }}"
          homepage.icon: "{{ magnetico_homepage_icon }}"
          homepage.href: "{{ magnetico_homepage_href }}"
          homepage.description: "{{ 'Autonomous (self-hosted) BitTorrent DHT search engine suite.' if homepage_show_description else omit }}"
          homepage.server: "my-docker"
          homepage.container: "{{ magneticod_container_name }}"
          homepage.showStats: "{{ magneticod_homepage_showstats | string }}"
          repliqate.enabled: "{{ magneticod_repliqate_enabled | string }}"
          repliqate.engine: "{{ magneticod_repliqate_engine }}"
          repliqate.schedule: "{{ magneticod_repliqate_schedule }}"
          repliqate.backup_id: "{{ magneticod_repliqate_backup_id }}"
          repliqate.retention: "{{ magneticod_repliqate_retention }}"
          traefik.enable: "false"
          wud.tag.include: '^\d+\.\d+\.\d+.*$'
          wud.tag.transform.type: "semver"
          wud.link.template: "https://hub.docker.com/r/boramalper/magneticod"
        cpu_shares: "{{ magneticod_cpu_shares }}"
        memory: "{{ magneticod_memory }}"
        memory_swap: "{{ magneticod_memory_swap }}"
        restart_policy: unless-stopped

    - name: Create {{ ansible_nas_app_name }} Web UI Container
      community.docker.docker_container:
        container_default_behavior: "compatibility"
        name: "{{ magnetico_container_name }}"
        hostname: "{{ magnetico_container_name }}"
        image: "{{ magnetico_image_name }}:{{ magnetico_image_tag }}"
        pull: true
        ports:
          - "{{ magnetico_port_http }}:8080"
        volumes:
          - "{{ magnetico_data_directory }}/config:/root/.config/magneticow"
          - "{{ magnetico_data_directory }}/data:/root/.local/share/magneticod/"
        env:
          TZ: "{{ ansible_nas_timezone }}"
        links:
          - "{{ magneticod_container_name }}"
        labels:
          autoheal: "{{ magnetico_autoheal | string }}"
          com.centurylinklabs.watchtower.enable: "{{ magnetico_watchtower_enabled| string }}"
          dockflare.enable: "{{ magnetico_dockflare_enabled | string }}"
          dockflare.access.group: "{{ magnetico_dockflare_access_group }}"
          dockflare.hostname: "{{ magnetico_hostname }}.{{ ansible_nas_domain }}"
          dockflare.service: "http://{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}:{{ magnetico_port_http }}"
          homepage.name: "{{ ansible_nas_app_name }}"
          homepage.group: "{{ magnetico_homepage_group }}"
          homepage.icon: "{{ magnetico_homepage_icon }}"
          homepage.href: "{{ magnetico_homepage_href }}"
          homepage.siteMonitor: "http://{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}:{{ magnetico_port_http }}"
          homepage.description: "{{ 'Autonomous (self-hosted) BitTorrent DHT search engine suite.' if homepage_show_description else omit }}"
          homepage.server: "my-docker"
          homepage.container: "{{ magnetico_container_name }}"
          homepage.showStats: "{{ magnetico_homepage_showstats | string }}"
          repliqate.enabled: "{{ magnetico_repliqate_enabled | string }}"
          repliqate.engine: "{{ magnetico_repliqate_engine }}"
          repliqate.schedule: "{{ magnetico_repliqate_schedule }}"
          repliqate.backup_id: "{{ magnetico_repliqate_backup_id }}"
          repliqate.retention: "{{ magnetico_repliqate_retention }}"
          traefik.enable: "{{ magnetico_available_externally | string }}"
          traefik.http.routers.magnetico.rule: "Host(`{{ magnetico_hostname }}.{{ ansible_nas_domain }}`)"
          traefik.http.routers.magnetico.tls.certresolver: "letsencrypt"
          traefik.http.routers.magnetico.tls.domains[0].main: "{{ ansible_nas_domain }}"
          traefik.http.routers.magnetico.tls.domains[0].sans: "*.{{ ansible_nas_domain }}"
          traefik.http.routers.magnetico.middlewares: "magnetico@docker{{ ',tinyauth-auth@docker' if magnetico_tinyauth_enabled | bool else '' }}"
          traefik.http.middlewares.magnetico.IPAllowList.sourcerange: "{{ magnetico_traefik_whitelist }}"
          traefik.http.services.magnetico.loadbalancer.server.port: "8080"
          wud.tag.include: '^\d+\.\d+\.\d+.*$'
          wud.tag.transform.type: "semver"
          wud.link.template: "https://hub.docker.com/r/boramalper/magneticow"
        cpu_shares: "{{ magnetico_cpu_shares }}"
        memory: "{{ magnetico_memory }}"
        memory_swap: "{{ magnetico_memory_swap }}"
        restart_policy: unless-stopped

    - name: Access {{ ansible_nas_app_name }} at
      ansible.builtin.debug:
        msg: >-
              {{
                ['http://' + hostvars[inventory_hostname]['ansible_default_ipv4']['address'] + ':' + (magnetico_port_http | string)] +
                (['https://' + magnetico_hostname + '.' + ansible_nas_domain] if (magnetico_available_externally is true or magnetico_dockflare_enabled is true) else [])
              }}
  when: magnetico_enabled is true

- name: Stop {{ ansible_nas_app_name }}
  block:
    - name: Stop {{ ansible_nas_app_name }} Web UI Container
      community.docker.docker_container:
        name: "{{ magnetico_container_name }}"
        state: absent

    - name: Stop {{ ansible_nas_app_name }} Crawler Container
      community.docker.docker_container:
        name: "{{ magneticod_container_name }}"
        state: absent
  when: magnetico_enabled is false

- name: Data Archive {{ ansible_nas_app_name }}
  include_role:
    name: ansible-nas-archive
  vars:
    target_data_dir: "{{ magnetico_data_directory }}"
  when:
    - archive_app_data_enabled is true
    - magnetico_enabled is false
