---
# ANE
ansible_nas_app_name: "Stirling PDF"
stirling_pdf_enabled: false
stirling_pdf_available_externally: false
stirling_pdf_traefik_whitelist: "{{ lan }}"

stirling_pdf_data_directory: "{{ docker_home }}/stirling_pdf"

# network
stirling_pdf_port_http: "3011"
stirling_pdf_hostname: "stirlingpdf"

# docker
stirling_pdf_container_name: "stirling-pdf"
stirling_pdf_image_name: "ghcr.io/stirling-tools/stirling-pdf"
stirling_pdf_image_tag: "latest"

# specs
stirling_pdf_cpu_shares: 1024
stirling_pdf_memory: "1024M"

# autoheal
stirling_pdf_autoheal: "false"

# dockflare
stirling_pdf_dockflare_tunnel: "false"
stirling_pdf_dockflare_access_group: ""

# homepage
stirling_pdf_homepage_group: "Apps"
stirling_pdf_homepage_icon: "stirling-pdf.png"
stirling_pdf_homepage_href: "http://{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}:{{ stirling_pdf_port_http }}"
stirling_pdf_homepage_showstats: "false"
#stirling_pdf_homepage_widget_key: "" # Optional: only if you have auth enabled

# repliqate
stirling_pdf_repliqate_enabled: "false"
stirling_pdf_repliqate_engine: "restic"
stirling_pdf_repliqate_schedule: "@daily 3am"
stirling_pdf_repliqate_backup_id: "{{ stirling_pdf_container_name }}"
stirling_pdf_repliqate_retention: "30d"

# watchtower
stirling_pdf_watchtower_enable: "false"
