---
# ANE
stirling_pdf_proper_name: "Stirling PDF"
stirling_pdf_enabled: false
stirling_pdf_traefik_enabled: false
stirling_pdf_traefik_whitelist: "{{ lan }}"

# directories
stirling_pdf_data_directory: "{{ docker_home }}/stirling-pdf"

# network
stirling_pdf_port_http: "3011"
stirling_pdf_hostname: "stirlingpdf"

# docker
stirling_pdf_container_name: "stirling-pdf"
stirling_pdf_image_name: "ghcr.io/stirling-tools/stirling-pdf"
stirling_pdf_image_tag: "latest"

# specs
stirling_pdf_cpu_shares: 1024
# Minimum (Ultra-Lite Tag): 512 MB – 1 GB (Basic PDF merging/splitting only).
# Minimum (Standard Tag): 2 GB (Required for the full suite to boot and idle).
# Recommended (Standard): 4 GB (Safe for OCR and Office-to-PDF conversions).
# Performance (Heavy OCR): 4 GB – 8 GB (Tesseract can eat RAM linearly with page count/resolution).
stirling_pdf_memory: "2G"
stirling_pdf_memory_swap: -1

# autoheal
stirling_pdf_autoheal_enabled: false

# dockflare
stirling_pdf_dockflare_enabled: false
stirling_pdf_dockflare_access_group: ""

# homepage
stirling_pdf_homepage_group: "Apps"
stirling_pdf_homepage_icon: "stirling-pdf.png"
stirling_pdf_homepage_href: "http://{{ hostvars[inventory_hostname]['ansible_facts']['default_ipv4']['address'] }}:{{ stirling_pdf_port_http }}"
stirling_pdf_homepage_showstats: false
#stirling_pdf_homepage_widget_key: "" # Optional: only if you have auth enabled

# repliqate
stirling_pdf_repliqate_enabled: false
stirling_pdf_repliqate_engine: "restic"
stirling_pdf_repliqate_schedule: "@daily 3am"
stirling_pdf_repliqate_backup_id: "{{ stirling_pdf_container_name }}"
stirling_pdf_repliqate_retention: "30d"

# tinyauth
stirling_pdf_tinyauth_enabled: false

# watchtower
stirling_pdf_watchtower_enabled: false
