---
# ANE
ansible_nas_app_name: "Homarr"
homarr_enabled: false
homarr_traefik_enabled: false
homarr_traefik_whitelist: "{{ lan }}"
homarr_data_directory: "{{ docker_home }}/homarr"

# network
homarr_hostname: "homarr"
homarr_port_http: "7575"

# docker
homarr_container_name: "homarr"
homarr_image_name: "ghcr.io/homarr-labs/homarr"
homarr_image_tag: "latest"

# specs
homarr_cpu_shares: 1024
homarr_memory: "512M"
homarr_memory_swap: -1

# app
homarr_env_secret_encryption_key: "b94bd869f29f0cc43b4726c66b1ccdf00d6645144546f33a77366de7d10df1c8" # create using openssl rand -hex 32

# autoheal
homarr_autoheal_enabled: false

# dockflare
homarr_dockflare_enabled: false
homarr_dockflare_access_group: ""

# homepage
homarr_homepage_group: "Apps"
homarr_homepage_icon: "homarr.png"
homarr_homepage_href: "http://{{ hostvars[inventory_hostname]['ansible_facts']['default_ipv4']['address'] }}:{{ homarr_port_http }}"
homarr_homepage_showstats: false

# repliqate
homarr_repliqate_enabled: false
homarr_repliqate_engine: "restic"
homarr_repliqate_schedule: "@daily 3am"
homarr_repliqate_backup_id: "{{ homarr_container_name }}"
homarr_repliqate_retention: "30d"

# tinyauth
homarr_tinyauth_enabled: false

# watchtower
homarr_watchtower_enabled: false
