---
# ANE
ansible_nas_app_name: "Beszel"
beszel_enabled: false
beszel_traefik_enabled: false
beszel_traefik_whitelist: "{{ lan }}"
beszel_data_directory: "{{ docker_home }}/beszel"

# network
beszel_hostname: "beszel"
beszel_port_http: "3015"

# docker
beszel_container_name: "beszel"
beszel_image_name: "henrygd/beszel"
beszel_image_tag: "latest"

# specs
beszel_cpu_shares: 1024
beszel_memory: "1G"
beszel_memory_swap: -1

# autoheal
beszel_autoheal_enabled: false

# dockflare
beszel_dockflare_enabled: false
beszel_dockflare_access_group: ""

# homepage
beszel_homepage_group: "Apps"
beszel_homepage_icon: "beszel"
beszel_homepage_href: "http://{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}:{{ beszel_port_http }}"
beszel_homepage_showstats: false
beszel_homepage_widget_username: ""
beszel_homepage_widget_password: ""
beszel_homepage_widget_systemid: ""
beszel_homepage_widget_version: "2"

# repliqate
beszel_repliqate_enabled: false
beszel_repliqate_engine: "restic"
beszel_repliqate_schedule: "@daily 3am"
beszel_repliqate_backup_id: "{{ beszel_container_name }}"
beszel_repliqate_retention: "30d"

# tinyauth
beszel_tinyauth_enabled: false

# watchtower
beszel_watchtower_enabled: false