---
- name: Start {{ ansible_nas_app_name }}
  block:
    - name: Create {{ ansible_nas_app_name }} Directories
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
      with_items:
        - "{{ gokapi_data_directory }}"
        - "{{ gokapi_data_directory }}/config"
        - "{{ gokapi_data_directory }}/data"

    - name: Create {{ ansible_nas_app_name }} Container
      community.docker.docker_container:
        container_default_behavior: "compatibility"
        name: "{{ gokapi_container_name }}"
        hostname: "{{ gokapi_container_name }}"
        image: "{{ gokapi_image_name }}:{{ gokapi_image_tag }}"
        pull: true
        volumes:
          - "{{ gokapi_data_directory }}/config:/app/config"
          - "{{ gokapi_data_directory }}/data:/app/data"
        env:
          TZ: "{{ ansible_nas_timezone }}"
        ports:
          - "{{ gokapi_port_http }}:53842"
        labels:
          autoheal: "{{ gokapi_autoheal }}"
          com.centurylinklabs.watchtower.enable: "{{ gokapi_watchtower_enable }}"
          dockflare.enable: "{{ gokapi_dockflare_tunnel }}"
          dockflare.access.group: "{{ gokapi_dockflare_access_group }}"
          dockflare.hostname: "{{ gokapi_hostname }}.{{ ansible_nas_domain }}"
          dockflare.service: "http://{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}:{{ gokapi_port_http }}"
          homepage.name: "{{ ansible_nas_app_name }}"
          homepage.group: "{{ gokapi_homepage_group }}"
          homepage.icon: "{{ gokapi_homepage_icon }}"
          homepage.href: "{{ gokapi_homepage_href }}"
          homepage.siteMonitor: "http://{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}:{{ gokapi_port_http }}"
          homepage.description: "{{ 'Lightweight selfhosted Firefox Send alternative without public upload. AWS S3 supported.' if homepage_show_description else omit }}"
          homepage.server: "my-docker"
          homepage.container: "{{ gokapi_container_name }}"
          homepage.showStats: "{{ gokapi_homepage_showstats }}"
          repliqate.enabled: "{{ gokapi_repliqate_enabled }}"
          repliqate.engine: "{{ gokapi_repliqate_engine }}"
          repliqate.schedule: "{{ gokapi_repliqate_schedule }}"
          repliqate.backup_id: "{{ gokapi_repliqate_backup_id }}"
          repliqate.retention: "{{ gokapi_repliqate_retention }}"
          traefik.enable: "{{ gokapi_available_externally | string }}"
          traefik.http.routers.gokapi.rule: "Host(`{{ gokapi_hostname }}.{{ ansible_nas_domain }}`)"
          traefik.http.routers.gokapi.tls.certresolver: "letsencrypt"
          traefik.http.routers.gokapi.tls.domains[0].main: "{{ ansible_nas_domain }}"
          traefik.http.routers.gokapi.tls.domains[0].sans: "*.{{ ansible_nas_domain }}"
          traefik.http.routers.gokapi.middlewares: "gokapi@docker{{ ',tinyauth-auth@docker' if gokapi_tinyauth_enabled | bool else '' }}"
          traefik.http.middlewares.gokapi.IPAllowList.sourcerange: "{{ gokapi_traefik_whitelist }}"
          traefik.http.services.gokapi.loadbalancer.server.port: "53842"
          wud.tag.include: '^\d+\.\d+\.\d+.*$'
          wud.tag.transform.type: "semver"
          wud.link.template: "https://hub.docker.com/r/f0rc3/gokapi"
        cpu_shares: "{{ gokapi_cpu_shares }}"
        memory: "{{ gokapi_memory }}"
        memory_swap: "{{ gokapi_memory_swap }}"
        restart_policy: unless-stopped

    - name: Access {{ ansible_nas_app_name }} at
      ansible.builtin.debug:
        msg: >-
              {{
                ['http://' + hostvars[inventory_hostname]['ansible_default_ipv4']['address'] + ':' + (gokapi_port_http | string)] +
                (['https://' + gokapi_hostname + '.' + ansible_nas_domain] if (gokapi_available_externally is true or gokapi_dockflare_tunnel is true) else [])
              }}
  when: gokapi_enabled is true

- name: Stop {{ ansible_nas_app_name }}
  block:
    - name: Stop {{ ansible_nas_app_name }} Container
      community.docker.docker_container:
        name: "{{ gokapi_container_name }}"
        state: absent
  when: gokapi_enabled is false

- name: Data Archive {{ ansible_nas_app_name }}
  include_role:
    name: ansible-nas-archive
  vars:
    target_data_dir: "{{ gokapi_data_directory }}"
  when:
    - archive_app_data_enabled is true
    - gokapi_enabled is false