ansible_nas_app_name: "Change Detection"

#
change_detection_enabled: false
change_detection_available_externally: false
change_detection_traefik_whitelist: "{{ lan }}"

# network
change_detection_port_http: "3029"
change_detection_hostname: "changedetection"
change_detection_sockpuppet_hostname: "sockpuppetserver"

change_detection_data_directory: "{{ docker_home }}/change-detection"

# app
change_detection_base_url: "http://{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}:{{ change_detection_port_http }}"
change_detection_hide_referer: "true"

# docker
change_detection_container_name: "change-detection"
change_detection_image_name: "ghcr.io/dgtlmoon/changedetection.io"
change_detection_image_tag: "latest"
change_detection_cpu_shares: "1024"
change_detection_memory: "1G"
change_detection_sockpuppet_container_name: "sockpuppetserver"
change_detection_sockpuppet_image_name: "dgtlmoon/sockpuppetbrowser"
change_detection_sockpuppet_image_tag: "latest"
change_detection_sockpuppet_cpu_shares: "1024"
change_detection_sockpuppet_memory: "1G"

# autoheal
change_detection_autoheal: "false"

# homepage
change_detection_homepage_group: "Apps"
change_detection_homepage_icon: "changedetection.png"
change_detection_homepage_href: "http://{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}:{{ change_detection_port_http }}"
change_detection_homepage_showStats: "false"
change_detection_sockpuppet_homepage_group: "Apps"
change_detection_sockpuppet_homepage_icon: "chrome.png"
change_detection_sockpuppet_homepage_href: "http://{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}:{{ change_detection_port_http }}"
change_detection_sockpuppet_homepage_showStats: "false"
change_detection_widget_key: "enter_your_api_key"

# watchtower
change_detection_watchtower_monitor_only: "true"
change_detection_sockpuppet_watchtower_monitor_only: "true"
