---
# ANE
ansible_nas_app_name: "Shaarli"
shaarli_enabled: false
shaarli_available_externally: false
shaarli_traefik_whitelist: "{{ lan }}"
shaarli_data_directory: "{{ docker_home }}/shaarli"

shaarli_hostname: "shaarli"
shaarli_port_http: "3056"
shaarli_port_https: "5443"

# docker
shaarli_container_name: "shaarli"
shaarli_image_name: "shaarli/shaarli"
shaarli_image_tag: "latest"

# specs
shaarli_cpu_shares: 1024
shaarli_memory: "1G"

# autoheal
shaarli_autoheal: false

# dockflare
shaarli_dockflare_enabled: false
shaarli_dockflare_access_group: ""

# homepage
shaarli_homepage_group: "Apps"
shaarli_homepage_icon: "shaarli.png"
shaarli_homepage_href: "http://{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}:{{ shaarli_port_http }}"
shaarli_homepage_showstats: false

# repliqate
shaarli_repliqate_enabled: false
shaarli_repliqate_engine: "restic"
shaarli_repliqate_schedule: "@daily 3am"
shaarli_repliqate_backup_id: "{{ shaarli_container_name }}"
shaarli_repliqate_retention: "30d"

# tinyauth
shaarli_tinyauth_enabled: false

# watchtower
shaarli_watchtower_enabled: false