---
- name: Start {{ ansible_nas_app_name }}
  block:
    - name: Create {{ ansible_nas_app_name }} Directories
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
      with_items:
        - "{{ tandoor_recipes_data_directory }}"
        - "{{ tandoor_recipes_data_directory }}/db"
        - "{{ tandoor_recipes_data_directory }}/mediafiles"
        - "{{ tandoor_recipes_data_directory }}/staticfiles"

    - name: Create {{ ansible_nas_app_name }} DB Container
      community.docker.docker_container:
        container_default_behavior: "compatibility"
        name: "{{ tandoor_recipes_db_container_name }}"
        hostname: "{{ tandoor_recipes_db_container_name }}"
        image: "{{ tandoor_recipes_db_image_name }}:{{ tandoor_recipes_db_image_tag }}"
        pull: true
        volumes:
          - "{{ tandoor_recipes_data_directory }}/db:/var/lib/postgresql/data"
        env:
          POSTGRES_USER: "{{ tandoor_recipes_env_postgres_user }}"
          POSTGRES_PASSWORD: "{{ tandoor_recipes_env_postgres_password }}"
          POSTGRES_DB: "{{ tandoor_recipes_env_postgres_db }}"
          TZ: "{{ ansible_nas_timezone }}"
        labels:
          autoheal: "{{ tandoor_recipes_db_autoheal }}"
          com.centurylinklabs.watchtower.enable: "{{ tandoor_recipes_db_watchtower_enable }}"
          dockflare.enable: "false"
          homepage.name: "{{ ansible_nas_app_name }} PostgreSQL"
          homepage.group: "{{ tandoor_recipes_db_homepage_group }}"
          homepage.icon: "{{ tandoor_recipes_db_homepage_icon }}"
          homepage.href: "{{ tandoor_recipes_homepage_href }}"
          homepage.description: "{{ 'PostgreSQL Database Management System' if homepage_show_description else omit }}"
          homepage.server: "my-docker"
          homepage.container: "{{ tandoor_recipes_db_container_name }}"
          homepage.showStats: "{{ tandoor_recipes_db_homepage_showstats }}"
          repliqate.enabled: "{{ tandoor_recipes_db_repliqate_enabled }}"
          repliqate.engine: "{{ tandoor_recipes_db_repliqate_engine }}"
          repliqate.schedule: "{{ tandoor_recipes_db_repliqate_schedule }}"
          repliqate.backup_id: "{{ tandoor_recipes_db_repliqate_backup_id }}"
          repliqate.retention: "{{ tandoor_recipes_db_repliqate_retention }}"
          traefik.enable: "false"
          wud.tag.include: '^\d+\.\d+.*$'
          wud.tag.transform.type: "semver"
          wud.link.template: "https://hub.docker.com/_/postgres"
        cpu_shares: "{{ tandoor_recipes_db_cpu_shares }}"
        memory: "{{ tandoor_recipes_db_memory }}"
        restart_policy: unless-stopped

    - name: Create {{ ansible_nas_app_name }} Container
      community.docker.docker_container:
        container_default_behavior: "compatibility"
        name: "{{ tandoor_recipes_container_name }}"
        hostname: "{{ tandoor_recipes_container_name }}"
        image: "{{ tandoor_recipes_image_name }}:{{ tandoor_recipes_image_tag }}"
        pull: true
        volumes:
          - "{{ tandoor_recipes_data_directory }}/mediafiles:/opt/recipes/mediafiles"
          - "{{ tandoor_recipes_data_directory }}/staticfiles:/opt/recipes/staticfiles"
        ports:
          - "{{ tandoor_recipes_port_http }}:{{ tandoor_recipes_port_http }}"
        env:
          ALLOWED_HOSTS: "{{ tandoor_recipes_env_allowed_hosts }}"
          DATABASE_URL: "postgresql://{{ tandoor_recipes_env_postgres_user }}:{{ tandoor_recipes_env_postgres_password }}@{{ tandoor_recipes_db_container_name }}:5432/{{ tandoor_recipes_env_postgres_db }}?sslmode=disable"
          DB_ENGINE: "django.db.backends.postgresql"
          SECRET_KEY: "{{ tandoor_recipes_env_secret_key }}"
          TANDOOR_PORT: "{{ tandoor_recipes_port_http }}"
          TZ: "{{ ansible_nas_timezone }}"
#          GUNICORN_WORKERS: "{{ tandoor_recipes_env_gunicorn_workers }}"
#          GUNICORN_THREADS: "{{ tandoor_recipes_env_gunicorn_threads }}"
#          GUNICORN_TIMEOUT: "{{ tandoor_recipes_env_gunicorn_timeout }}"
#          GUNICORN_MEDIA: "{{ tandoor_recipes_env_gunicorn_media }}"
#          CSRF_TRUSTED_ORIGINS: "{{ tandoor_recipes_env_csrf_trusted_origins }}"
#          CORS_ALLOW_ALL_ORIGINS: "{{ tandoor_recipes_env_cors_allow_all_origins }}"
#          SESSION_COOKIE_DOMAIN: "{{ tandoor_recipes_env_session_cookie_domain }}"
#          SESSION_COOKIE_NAME: "{{ tandoor_recipes_env_session_cookie_name }}"
#          ENABLE_METRICS: "{{ tandoor_recipes_env_enable_metrics }}"
#          SORT_TREE_BY_NAME: "{{ tandoor_recipes_env_sort_tree_by_name }}"
#          ENABLE_PDF_EXPORT: "{{ tandoor_recipes_env_enable_pdf_export }}"
#          TERMS_URL: "{{ tandoor_recipes_env_terms_url }}"
#          PRIVACY_URL: "{{ tandoor_recipes_env_privacy_url }}"
#          IMPRINT_URL: "{{ tandoor_recipes_env_imprint_url }}"
#          RATELIMIT_URL_IMPORT_REQUESTS: "{{ tandoor_recipes_env_ratelimit_url_import_requests }}"
#          SOCIAL_DEFAULT_ACCESS: "{{ tandoor_recipes_env_social_default_access }}"
#          SOCIAL_DEFAULT_GROUP: "{{ tandoor_recipes_env_social_default_group }}"
#          ENABLE_SIGNUP: "{{ tandoor_recipes_env_enable_signup }}"
#          SOCIAL_PROVIDERS: "{{ tandoor_recipes_env_social_providers }}"
#          REMOTE_USER_AUTH: "{{ tandoor_recipes_env_remote_user_auth }}"
#          LDAP_AUTH: "{{ tandoor_recipes_env_ldap_auth }}"
#          AUTH_LDAP_SERVER_URI: "{{ tandoor_recipes_env_auth_ldap_server_uri }}"
#          AUTH_LDAP_BIND_DN: "{{ tandoor_recipes_env_auth_ldap_bind_dn }}"
#          AUTH_LDAP_BIND_PASSWORD: "{{ tandoor_recipes_env_auth_ldap_bind_password }}"
#          AUTH_LDAP_BIND_PASSWORD_FILE: "{{ tandoor_recipes_env_auth_ldap_bind_password_file }}"
#          AUTH_LDAP_USER_SEARCH_BASE_DN: "{{ tandoor_recipes_env_auth_ldap_user_search_base_dn }}"
#          AUTH_LDAP_TLS_CACERTFILE: "{{ tandoor_recipes_env_auth_ldap_tls_cacertfile }}"
#          AUTH_LDAP_START_TLS: "{{ tandoor_recipes_env_auth_ldap_start_tls }}"
#          EMAIL_HOST: "{{ tandoor_recipes_env_email_host }}"
#          EMAIL_PORT: "{{ tandoor_recipes_env_email_port }}"
#          EMAIL_HOST_USER: "{{ tandoor_recipes_env_email_host_user }}"
#          EMAIL_HOST_PASSWORD: "{{ tandoor_recipes_env_email_host_password }}"
#          EMAIL_HOST_PASSWORD_FILE: "{{ tandoor_recipes_env_email_host_password_file }}"
#          EMAIL_USE_TLS: "{{ tandoor_recipes_env_email_use_tls }}"
#          EMAIL_USE_SSL: "{{ tandoor_recipes_env_email_use_ssl }}"
#          DEFAULT_FROM_EMAIL: "{{ tandoor_recipes_env_default_from_email }}"
#          ACCOUNT_EMAIL_SUBJECT_PREFIX: "{{ tandoor_recipes_env_account_email_subject_prefix }}"
#          S3_REGION_NAME: "{{ tandoor_recipes_env_s3_region_name }}"
#          S3_QUERYSTRING_AUTH: "{{ tandoor_recipes_env_s3_querystring_auth }}"
#          S3_QUERYSTRING_EXPIRE: "{{ tandoor_recipes_env_s3_querystring_expire }}"
#          S3_ENDPOINT_URL: "{{ tandoor_recipes_env_s3_endpoint_url }}"
#          S3_CUSTOM_DOMAIN: "{{ tandoor_recipes_env_s3_custom_domain }}"
#          SPACE_AI_ENABLED: "{{ tandoor_recipes_env_space_ai_enabled }}"
#          SPACE_AI_CREDITS_MONTHLY: "{{ tandoor_recipes_env_space_ai_credits_monthly }}"
#          AI_RATELIMIT: "{{ tandoor_recipes_env_ai_ratelimit }}"
#          FDC_API_KEY: "{{ tandoor_recipes_env_fdc_api_key }}"
#          DISABLE_EXTERNAL_CONNECTORS: "{{ tandoor_recipes_env_disable_external_connectors }}"
#          EXTERNAL_CONNECTORS_QUEUE_SIZE: "{{ tandoor_recipes_env_external_connectors_queue_size }}"
#          DEBUG: "{{ tandoor_recipes_env_debug }}"
#          DEBUG_TOOLBAR: "{{ tandoor_recipes_env_debug_toolbar }}"
#          SQL_DEBUG: "{{ tandoor_recipes_env_sql_debug }}"
#          LOG_LEVEL: "{{ tandoor_recipes_env_log_level }}"
#          GUNICORN_LOG_LEVEL: "{{ tandoor_recipes_env_gunicorn_log_level }}"
#          FRACTION_PREF_DEFAULT: "{{ tandoor_recipes_env_fraction_pref_default }}"
#          COMMENT_PREF_DEFAULT: "{{ tandoor_recipes_env_comment_pref_default }}"
#          STICKY_NAV_PREF_DEFAULT: "{{ tandoor_recipes_env_sticky_nav_pref_default }}"
#          MAX_OWNED_SPACES_PREF_DEFAULT: "{{ tandoor_recipes_env_max_owned_spaces_pref_default }}"
#          UNAUTHENTICATED_THEME_FROM_SPACE: "{{ tandoor_recipes_env_unauthenticated_theme_from_space }}"
#          FORCE_THEME_FROM_SPACE: ""
#          SHOPPING_MIN_AUTOSYNC_INTERVAL: "{{ tandoor_recipes_env_shopping_min_autosync_interval }}"
#          DRF_THROTTLE_RECIPE_URL_IMPORT: "{{ tandoor_recipes_env_drf_throttle_recipe_url_import }}"
#          SPACE_DEFAULT_MAX_RECIPES: "{{ tandoor_recipes_env_space_default_max_recipes }}"
#          SPACE_DEFAULT_MAX_USERS: "{{ tandoor_recipes_env_space_default_max_users }}"
#          SPACE_DEFAULT_MAX_FILES: "{{ tandoor_recipes_env_space_default_max_files }}"
#          SPACE_DEFAULT_ALLOW_SHARING: "{{ tandoor_recipes_env_space_default_allow_sharing }}"
#          EXPORT_FILE_CACHE_DURATION: "{{ tandoor_recipes_env_export_file_cache_duration }}"
        links:
          - "{{ tandoor_recipes_db_container_name }}"
        labels:
          autoheal: "{{ tandoor_recipes_autoheal }}"
          com.centurylinklabs.watchtower.enable: "{{ tandoor_recipes_watchtower_enable }}"
          dockflare.enable: "{{ tandoor_recipes_dockflare_tunnel }}"
          dockflare.access.group: "{{ tandoor_recipes_dockflare_access_group }}"
          dockflare.hostname: "{{ tandoor_recipes_hostname }}.{{ ansible_nas_domain }}"
          dockflare.service: "http://{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}:{{ tandoor_recipes_port_http }}"
          homepage.name: "{{ ansible_nas_app_name }}"
          homepage.group: "{{ tandoor_recipes_homepage_group }}"
          homepage.icon: "{{ tandoor_recipes_homepage_icon }}"
          homepage.href: "{{ tandoor_recipes_homepage_href }}"
          homepage.description: "{{ 'tandoor_recipes description' if homepage_show_description else omit }}"
          homepage.server: "my-docker"
          homepage.container: "{{ tandoor_recipes_container_name }}"
          homepage.showStats: "{{ tandoor_recipes_homepage_showstats }}"
          homepage.siteMonitor: "http://{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}:{{ tandoor_recipes_port_http }}"
          repliqate.enabled: "{{ tandoor_recipes_repliqate_enabled }}"
          repliqate.engine: "{{ tandoor_recipes_repliqate_engine }}"
          repliqate.schedule: "{{ tandoor_recipes_repliqate_schedule }}"
          repliqate.backup_id: "{{ tandoor_recipes_repliqate_backup_id }}"
          repliqate.retention: "{{ tandoor_recipes_repliqate_retention }}"
          traefik.enable: "{{ tandoor_recipes_available_externally | string }}"
          traefik.http.routers.tandoorrecipes.rule: "Host(`{{ tandoor_recipes_hostname }}.{{ ansible_nas_domain }}`)"
          traefik.http.routers.tandoorrecipes.tls.certresolver: "letsencrypt"
          traefik.http.routers.tandoorrecipes.tls.domains[0].main: "{{ ansible_nas_domain }}"
          traefik.http.routers.tandoorrecipes.tls.domains[0].sans: "*.{{ ansible_nas_domain }}"
          traefik.http.routers.tandoorrecipes.middlewares: "tandoorrecipes@docker{{ ',tinyauth-auth@docker' if tandoor_recipes_tinyauth_enabled | bool else '' }}"
          traefik.http.middlewares.tandoorrecipes.IPAllowList.sourcerange: "{{ tandoor_recipes_traefik_whitelist }}"
          traefik.http.services.tandoor_recipes.loadbalancer.server.port: "{{ tandoor_recipes_port_http }}"
          wud.tag.include: '^\d+\.\d+\.\d+$'
          wud.tag.transform.type: "semver"
          wud.link.template: "https://github.com/TandoorRecipes/recipes/pkgs/container/recipes"
        cpu_shares: "{{ tandoor_recipes_cpu_shares }}"
        memory: "{{ tandoor_recipes_memory }}"
        restart_policy: unless-stopped

    - name: Access {{ ansible_nas_app_name }} at
      ansible.builtin.debug:
        msg: >-
              {{
                ['http://' + hostvars[inventory_hostname]['ansible_default_ipv4']['address'] + ':' + (tandoor_recipes_port_http | string)] +
                (['https://' + tandoor_recipes_hostname + '.' + ansible_nas_domain] if (tandoor_recipes_available_externally is true or tandoor_recipes_dockflare_tunnel is true) else [])
              }}
  when: tandoor_recipes_enabled is true

- name: Stop {{ ansible_nas_app_name }}
  block:
    - name: Stop {{ ansible_nas_app_name }} Container
      community.docker.docker_container:
        name: "{{ tandoor_recipes_container_name }}"
        state: absent

    - name: Stop {{ ansible_nas_app_name }} DB Container
      community.docker.docker_container:
        name: "{{ tandoor_recipes_db_container_name }}"
        state: absent
  when: tandoor_recipes_enabled is false

- name: Data Archive {{ ansible_nas_app_name }}
  include_role:
    name: ansible-nas-archive
  vars:
    target_data_dir: "{{ tandoor_recipes_data_directory }}"
  when:
    - archive_app_data_enabled is true
    - tandoor_recipes_enabled is false
