---
- name: Start {{ ansible_nas_app_name }}
  block:
    - name: Create {{ ansible_nas_app_name }} Directory
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
      with_items:
        - "{{ chowdown_data_directory }}"
        - "{{ chowdown_data_directory }}/config"

    - name: Create {{ ansible_nas_app_name }} Container
      community.docker.docker_container:
        container_default_behavior: "compatibility"
        name: "{{ chowdown_container_name }}"
        hostname: "{{ chowdown_container_name }}"
        image: "{{ chowdown_image_name }}:{{ chowdown_image_tag }}"
        pull: true
        network_mode: bridge
        volumes:
          - "{{ chowdown_data_directory }}/config:/config:rw"
        ports:
          - "{{ chowdown_port_http }}:4000"
        env:
          TZ: "{{ ansible_nas_timezone }}"
        labels:
          autoheal: "{{ chowdown_autoheal | string }}"
          com.centurylinklabs.watchtower.enable: "{{ chowdown_watchtower_enabled | string }}"
          dockflare.enable: "{{ chowdown_dockflare_enabled | string }}"
          dockflare.access.group: "{{ chowdown_dockflare_access_group }}"
          dockflare.hostname: "{{ chowdown_hostname }}.{{ ansible_nas_domain }}"
          dockflare.service: "http://{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}:{{ chowdown_port_http }}"
          homepage.name: "{{ ansible_nas_app_name }}"
          homepage.group: "{{ chowdown_homepage_group }}"
          homepage.icon: "{{ chowdown_homepage_icon }}"
          homepage.href: "{{ chowdown_homepage_href }}"
          homepage.siteMonitor: "http://{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}:{{ chowdown_port_http }}"
          homepage.description: "{{ 'Simple recipes in Markdown format' if homepage_show_description else omit }}"
          homepage.server: "my-docker"
          homepage.container: "{{ chowdown_container_name }}"
          homepage.showStats: "{{ chowdown_homepage_showstats | string }}"
          repliqate.enabled: "{{ chowdown_repliqate_enabled | string }}"
          repliqate.engine: "{{ chowdown_repliqate_engine }}"
          repliqate.schedule: "{{ chowdown_repliqate_schedule }}"
          repliqate.backup_id: "{{ chowdown_repliqate_backup_id }}"
          repliqate.retention: "{{ chowdown_repliqate_retention }}"
          traefik.enable: "{{ chowdown_available_externally | string }}"
          traefik.http.routers.chowdown.rule: "Host(`{{ chowdown_hostname }}.{{ ansible_nas_domain }}`)"
          traefik.http.routers.chowdown.tls.certresolver: "letsencrypt"
          traefik.http.routers.chowdown.tls.domains[0].main: "{{ ansible_nas_domain }}"
          traefik.http.routers.chowdown.tls.domains[0].sans: "*.{{ ansible_nas_domain }}"
          traefik.http.routers.chowdown.middlewares: "chowdown@docker{{ ',tinyauth-auth@docker' if chowdown_tinyauth_enabled | bool else '' }}"
          traefik.http.middlewares.chowdown.IPAllowList.sourcerange: "{{ chowdown_traefik_whitelist }}"
          traefik.http.services.chowdown.loadbalancer.server.port: "4000"
          wud.watch.digest: "true"
          wud.link.template: "https://hub.docker.com/r/gregyankovoy/chowdown"
        cpu_shares: "{{ chowdown_cpu_shares }}"
        memory: "{{ chowdown_memory }}"
        memory_swap: "{{ chowdown_memory_swap }}"
        restart_policy: unless-stopped

    - name: Access {{ ansible_nas_app_name }} at
      ansible.builtin.debug:
        msg: >-
              {{
                ['http://' + hostvars[inventory_hostname]['ansible_default_ipv4']['address'] + ':' + (chowdown_port_http | string)] +
                (['https://' + chowdown_hostname + '.' + ansible_nas_domain] if (chowdown_available_externally is true or chowdown_dockflare_enabled is true) else [])
              }}
  when: chowdown_enabled is true

- name: Stop {{ ansible_nas_app_name }}
  block:
    - name: Stop {{ ansible_nas_app_name }} Container
      community.docker.docker_container:
        name: "{{ chowdown_container_name }}"
        state: absent
  when: chowdown_enabled is false

- name: Data Archive {{ ansible_nas_app_name }}
  include_role:
    name: ansible-nas-archive
  vars:
    target_data_dir: "{{ chowdown_data_directory }}"
  when:
    - archive_app_data_enabled is true
    - chowdown_enabled is false