---
ansible_nas_app_name: "Guacamole"

guacamole_enabled: false
guacamole_available_externally: false
guacamole_traefik_whitelist: "{{ lan }}"

# directories
guacamole_data_directory: "{{ docker_home }}/guacamole"

# network
guacamole_port: "8090"
guacamole_hostname: "guacamole"

# docker
guacamole_container_name: "guacamole"
guacamole_image_name: "oznu/guacamole"
guacamole_image_version: "latest"
guacamole_cpu_shares: 1024

# specs
guacamole_memory: 1g

# autoheal
guacamole_autoheal: "false"

# homepage
guacamole_homepage_group: "Apps"
guacamole_homepage_icon: "guacamole.png"
guacamole_homepage_href: "http://{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}:{{ guacamole_port }}"
guacamole_homepage_showStats: "false"

# watchtower
guacamole_watchtower_monitor_only: "true"