---
# ANE
ansible_nas_app_name: "Syncthing"
syncthing_enabled: false
syncthing_available_externally: false
syncthing_traefik_whitelist: "{{ lan }}"

# directories
syncthing_data_directory: "{{ samba_shares_root }}/syncthing"

# these are the directories that you want to mount from the local ansible-nas filesystem into
# the syncthing container.
# format is:
#   - "/ansible/nas/filesystem/directory_name:/var/syncthing/directory_name"
syncthing_volumes:
  - "{{ syncthing_data_directory }}:/var/syncthing/"

syncthing_user_id: "0"
syncthing_group_id: "0"

# network
syncthing_port_http: 8384
syncthing_hostname: syncthing

# docker
syncthing_container_name: "syncthing"
syncthing_image_name: "ghcr.io/syncthing/syncthing"
syncthing_image_version: "latest"

# specs
syncthing_cpu_shares: 1024
syncthing_memory: 1g

# autoheal
syncthing_autoheal: "false"

# dockflare
syncthing_dockflare_tunnel: "false"
syncthing_dockflare_access_group: ""

# homepage
syncthing_homepage_group: "Apps"
syncthing_homepage_icon: "syncthing.png"
syncthing_homepage_href: "http://{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}:{{ syncthing_port_http }}"
syncthing_homepage_showstats: "false"

# repliqate
syncthing_repliqate_enabled: "false"
syncthing_repliqate_engine: "restic"
syncthing_repliqate_schedule: "@daily 3am"
syncthing_repliqate_backup_id: "{{ syncthing_container_name }}"
syncthing_repliqate_retention: "30d"

# watchtower
syncthing_watchtower_enable: "false"