---
# ANE
ansible_nas_app_name: "Reubah"
reubah_enabled: false
reubah_available_externally: false
reubah_traefik_whitelist: "{{ lan }}"

reubah_data_directory: "{{ docker_home }}/reubah"

# network
reubah_port_http: "3020"
reubah_hostname: "reubah"

# docker
reubah_container_name: "reubah"
reubah_image_name: "ghcr.io/dendianugerah/reubah"
reubah_image_tag: "latest"

# specs
reubah_cpu_shares: 1024
reubah_memory: "512M"

# autoheal
reubah_autoheal: "false"

# dockflare
reubah_dockflare_tunnel: "false"
reubah_dockflare_access_group: ""

# homepage
reubah_homepage_group: "Apps"
reubah_homepage_icon: "reubah.png"
reubah_homepage_href: "http://{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}:{{ reubah_port_http }}"
reubah_homepage_showstats: "false"

# repliqate
reubah_repliqate_enabled: "false"
reubah_repliqate_engine: "restic"
reubah_repliqate_schedule: "@daily 3am"
reubah_repliqate_backup_id: "{{ reubah_container_name }}"
reubah_repliqate_retention: "30d"

# watchtower
reubah_watchtower_enable: "false"