---
- name: Start {{ ansible_nas_app_name }}
  block:
    - name: Create {{ ansible_nas_app_name }} Directories
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
      with_items:
        - "{{ checkcle_data_directory }}"
        - "{{ checkcle_data_directory }}/data"

    - name: Set {{ ansible_nas_app_name }} FQDN var overrides
      ansible.builtin.set_fact:
        checkcle_homepage_href: "https://{{ checkcle_hostname }}.{{ ansible_nas_domain }}"
      when: checkcle_traefik_enabled | bool or checkcle_dockflare_enabled | bool

    - name: Create {{ ansible_nas_app_name }} Container
      community.docker.docker_container:
        container_default_behavior: "compatibility"
        name: "{{ checkcle_container_name }}"
        hostname: "{{ checkcle_container_name }}"
        image: "{{ checkcle_image_name }}:{{ checkcle_image_tag }}"
        pull: true
        volumes:
          - "{{ checkcle_data_directory }}/data:/mnt/pb_data"
        ports:
          - "{{ checkcle_port_http }}:8090"
        env:
          PUID: "{{ checkcle_user_id }}"
          PGID: "{{ checkcle_group_id }}"
          TZ: "{{ ansible_nas_timezone }}"
        ulimits:
          - "nofile:4096:8192"
        labels:
          autoheal: "{{ checkcle_autoheal_enabled | ternary('true', 'false') }}"
          com.centurylinklabs.watchtower.enable: "{{ checkcle_watchtower_enabled | ternary('true', 'false') }}"
          dockflare.enable: "{{ checkcle_dockflare_enabled | ternary('true', 'false') }}"
          dockflare.access.group: "{{ checkcle_dockflare_access_group }}"
          dockflare.hostname: "{{ checkcle_hostname }}.{{ ansible_nas_domain }}"
          dockflare.service: "http://{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}:{{ checkcle_port_http }}"
          homepage.name: "{{ ansible_nas_app_name }}"
          homepage.group: "{{ checkcle_homepage_group }}"
          homepage.icon: "{{ checkcle_homepage_icon }}"
          homepage.href: "{{ checkcle_homepage_href }}"
          homepage.description: "{{ 'a self-hosted, open-source monitoring platform for seamless, real-time full-stack systems, applications, and infrastructure' if homepage_show_description else omit }}"
          homepage.server: "my-docker"
          homepage.container: "{{ checkcle_container_name }}"
          homepage.showStats: "{{ checkcle_homepage_showstats | ternary('true', 'false') }}"
          homepage.siteMonitor: "http://{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}:{{ checkcle_port_http }}"
          repliqate.enabled: "{{ checkcle_repliqate_enabled | ternary('true', 'false') }}"
          repliqate.engine: "{{ checkcle_repliqate_engine }}"
          repliqate.schedule: "{{ checkcle_repliqate_schedule }}"
          repliqate.backup_id: "{{ checkcle_repliqate_backup_id }}"
          repliqate.retention: "{{ checkcle_repliqate_retention }}"
          traefik.enable: "{{ checkcle_traefik_enabled | ternary('true', 'false') }}"
          traefik.http.routers.checkcle.rule: "Host(`{{ checkcle_hostname }}.{{ ansible_nas_domain }}`)"
          traefik.http.routers.checkcle.tls.certresolver: "letsencrypt"
          traefik.http.routers.checkcle.tls.domains[0].main: "{{ ansible_nas_domain }}"
          traefik.http.routers.checkcle.tls.domains[0].sans: "*.{{ ansible_nas_domain }}"
          traefik.http.routers.checkcle.middlewares: "checkcle@docker{{ ',tinyauth-auth@docker' if checkcle_tinyauth_enabled | bool else '' }}"
          traefik.http.middlewares.checkcle.IPAllowList.sourcerange: "{{ checkcle_traefik_whitelist }}"
          traefik.http.services.checkcle.loadbalancer.server.port: "8090"
          wud.tag.include: '^\d+\.\d+\.\d+.*$'
          wud.tag.transform.type: "semver"
          wud.link.template: "https://hub.docker.com/r/operacle/checkcle"
        cpu_shares: "{{ checkcle_cpu_shares }}"
        memory: "{{ checkcle_memory }}"
        memory_swap: "{{ checkcle_memory_swap }}"
        restart_policy: unless-stopped

    - name: Access {{ ansible_nas_app_name }} at
      ansible.builtin.debug:
        msg: >-
              {{
                ['http://' + hostvars[inventory_hostname]['ansible_default_ipv4']['address'] + ':' + (checkcle_port_http | string)] +
                (['https://' + checkcle_hostname + '.' + ansible_nas_domain] if (checkcle_traefik_enabled is true or checkcle_dockflare_enabled is true) else [])
              }}
  when: checkcle_enabled is true

- name: Stop {{ ansible_nas_app_name }}
  block:
    - name: Stop {{ ansible_nas_app_name }} Container
      community.docker.docker_container:
        name: "{{ checkcle_container_name }}"
        state: absent
  when: checkcle_enabled is false

- name: Data Archive {{ ansible_nas_app_name }}
  include_role:
    name: ansible-nas-archive
  vars:
    target_data_dir: "{{ checkcle_data_directory }}"
  when:
    - archive_app_data_enabled is true
    - checkcle_enabled is false