---
- name: Start {{ ansible_nas_app_name }}
  block:
    - name: Create {{ ansible_nas_app_name }} Directories
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
      with_items:
        - "{{ gameyfin_data_directory }}"
        - "{{ gameyfin_data_directory }}/data"
        - "{{ gameyfin_data_directory }}/db"
        - "{{ gameyfin_data_directory }}/logs"
        - "{{ gameyfin_games_directory }}"

    - name: Set {{ ansible_nas_app_name }} FQDN var overrides
      ansible.builtin.set_fact:
        gameyfin_env_app_url: "https://{{ gameyfin_hostname }}.{{ ansible_nas_domain }}"
        gameyfin_homepage_href: "https://{{ gameyfin_hostname }}.{{ ansible_nas_domain }}"
      when: gameyfin_traefik_enabled | bool or gameyfin_dockflare_enabled | bool

    - name: Create {{ ansible_nas_app_name }} Container
      community.docker.docker_container:
        container_default_behavior: "compatibility"
        name: "{{ gameyfin_container_name }}"
        hostname: "{{ gameyfin_container_name }}"
        image: "{{ gameyfin_image_name }}:{{ gameyfin_image_tag }}"
        pull: true
        volumes:
          - "{{ gameyfin_data_directory }}/data:/opt/gameyfin/data"
          - "{{ gameyfin_data_directory }}/db:/opt/gameyfin/db"
          - "{{ gameyfin_data_directory }}/logs:/opt/gameyfin/logs"
          - "{{ gameyfin_games_directory }}:/games"
        ports:
          - "{{ gameyfin_port_http }}:8080"
        # If you plan to use the included torrent plugin, uncomment the following lines:
        # - "6969:6969"
        # - "6881:6881"
        env:
          APP_KEY: "{{ gameyfin_env_app_key }}"
          APP_URL: "{{ gameyfin_env_app_url }}"
          PUID: "{{ gameyfin_user_id }}"
          PGID: "{{ gameyfin_group_id }}"
          TZ: "{{ ansible_nas_timezone }}"
        labels:
          autoheal: "{{ gameyfin_autoheal_enabled | ternary('true', 'false') }}"
          com.centurylinklabs.watchtower.enable: "{{ gameyfin_watchtower_enabled | ternary('true', 'false') }}"
          dockflare.enable: "{{ gameyfin_dockflare_enabled | ternary('true', 'false') }}"
          dockflare.access.group: "{{ gameyfin_dockflare_access_group }}"
          dockflare.hostname: "{{ gameyfin_hostname }}.{{ ansible_nas_domain }}"
          dockflare.service: "http://{{ hostvars[inventory_hostname]['ansible_facts']['default_ipv4']['address'] }}:{{ gameyfin_port_http }}"
          homepage.name: "{{ ansible_nas_app_name }}"
          homepage.group: "{{ gameyfin_homepage_group }}"
          homepage.icon: "{{ gameyfin_homepage_icon }}"
          homepage.href: "{{ gameyfin_homepage_href }}"
          homepage.description: "{{ 'Manage your video games.' if homepage_show_description else omit }}"
          homepage.server: "my-docker"
          homepage.container: "{{ gameyfin_container_name }}"
          homepage.showStats: "{{ gameyfin_homepage_showstats | ternary('true', 'false') }}"
          homepage.siteMonitor: "http://{{ hostvars[inventory_hostname]['ansible_facts']['default_ipv4']['address'] }}:{{ gameyfin_port_http }}"
          repliqate.enabled: "{{ gameyfin_repliqate_enabled | ternary('true', 'false') }}"
          repliqate.engine: "{{ gameyfin_repliqate_engine }}"
          repliqate.schedule: "{{ gameyfin_repliqate_schedule }}"
          repliqate.backup_id: "{{ gameyfin_repliqate_backup_id }}"
          repliqate.retention: "{{ gameyfin_repliqate_retention }}"
          traefik.enable: "{{ gameyfin_traefik_enabled | ternary('true', 'false') }}"
          traefik.http.routers.gameyfin.rule: "Host(`{{ gameyfin_hostname }}.{{ ansible_nas_domain }}`)"
          traefik.http.routers.gameyfin.tls.certresolver: "letsencrypt"
          traefik.http.routers.gameyfin.tls.domains[0].main: "{{ ansible_nas_domain }}"
          traefik.http.routers.gameyfin.tls.domains[0].sans: "*.{{ ansible_nas_domain }}"
          traefik.http.routers.gameyfin.middlewares: "gameyfin@docker{{ ',tinyauth-auth@docker' if gameyfin_tinyauth_enabled | bool else '' }}"
          traefik.http.middlewares.gameyfin.IPAllowList.sourcerange: "{{ gameyfin_traefik_whitelist }}"
          traefik.http.services.gameyfin.loadbalancer.server.port: "8080"
          wud.tag.include: '^v\d+\.\d+\.\d+.*$'
          wud.tag.transform.type: "semver"
          wud.link.template: "https://github.com/Gameyfin/Gameyfin/pkgs/container/gameyfin"
        cpu_shares: "{{ gameyfin_cpu_shares }}"
        memory: "{{ gameyfin_memory }}"
        memory_swap: "{{ gameyfin_memory_swap }}"
        restart_policy: unless-stopped

    - name: Access {{ ansible_nas_app_name }} at
      ansible.builtin.debug:
        msg: >-
              {{
                ['http://' + hostvars[inventory_hostname]['ansible_facts']['default_ipv4']['address'] + ':' + (gameyfin_port_http | string)] +
                (['https://' + gameyfin_hostname + '.' + ansible_nas_domain] if (gameyfin_traefik_enabled is true or gameyfin_dockflare_enabled is true) else [])
              }}
  when: gameyfin_enabled is true

- name: Stop {{ ansible_nas_app_name }}
  block:
    - name: Stop {{ ansible_nas_app_name }} Container
      community.docker.docker_container:
        name: "{{ gameyfin_container_name }}"
        state: absent
  when: gameyfin_enabled is false

- name: Data Archive {{ ansible_nas_app_name }}
  include_role:
    name: ansible-nas-archive
  vars:
    target_data_dir: "{{ gameyfin_data_directory }}"
  when:
    - archive_app_data_enabled is true
    - gameyfin_enabled is false