---
- name: Start {{ ansible_nas_app_name }}
  block:
    - name: Create {{ ansible_nas_app_name }} Directories
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        recurse: yes
      with_items:
        - "{{ gitea_data_directory }}/gitea"
        - "{{ gitea_data_directory }}/db"

    - name: Create {{ ansible_nas_app_name }} DB Container
      community.docker.docker_container:
        container_default_behavior: "compatibility"
        name: "{{ gitea_db_container_name }}"
        hostname: "{{ gitea_db_container_name }}"
        image: "{{ gitea_db_image_name }}:{{ gitea_db_image_version }}"
        pull: true
        volumes:
          - "{{ gitea_data_directory }}/db:/var/lib/mysql:rw"
          - "/etc/timezone:/etc/timezone:ro"
          - "/etc/localtime:/etc/localtime:ro"
        env:
          MYSQL_DATABASE: "gitea"
          MYSQL_USER: "gitea"
          MYSQL_PASSWORD: "gitea"
          MYSQL_ROOT_PASSWORD: "gitea"
          TZ: "{{ ansible_nas_timezone }}"
        labels:
          autoheal: "{{ gitea_db_autoheal }}"
          com.centurylinklabs.watchtower.enable: "{{ gitea_db_watchtower_enable }}"
          dockflare.enable: "false"
          homepage.name: "{{ ansible_nas_app_name }} DB"
          homepage.group: "{{ gitea_db_homepage_group }}"
          homepage.icon: "{{ gitea_db_homepage_icon }}"
          homepage.href: "{{ gitea_db_homepage_href }}"
          homepage.description: "{{ 'MySQL Server, the world''s most popular open source database' if homepage_show_description else omit }}"
          homepage.server: "my-docker"
          homepage.container: "{{ gitea_db_container_name }}"
          homepage.showStats: "{{ gitea_db_homepage_showstats }}"
          traefik.enable: "false"
          wud.tag.include: '^9\.3\.\d+$'
          wud.tag.transform.type: "semver"
          wud.link.template: "https://hub.docker.com/_/mysql"
        cpu_shares: "{{ gitea_db_cpu_shares }}"
        memory: "{{ gitea_db_memory }}"
        restart_policy: unless-stopped

    - name: Create {{ ansible_nas_app_name }} Container
      community.docker.docker_container:
        name: "{{ gitea_container_name }}"
        hostname: "{{ gitea_container_name }}"
        image: "{{ gitea_image_name }}:{{ gitea_image_version }}"
        pull: true
        volumes:
          - "{{ gitea_data_directory }}/gitea:/data:rw"
          - "/etc/timezone:/etc/timezone:ro"
          - "/etc/localtime:/etc/localtime:ro"
        ports:
          - "{{ gitea_port_http }}:3000"
          - "{{ gitea_port_ssh }}:{{ gitea_port_ssh }}"
        links:
          - "{{ gitea_db_container_name }}"
        env:
          DB_TYPE: "mysql"
          DB_HOST: "{{ gitea_db_container_name }}:3306"
          DB_NAME: "gitea"
          DB_USER: "gitea"
          DB_PASSWD: "gitea"
          DISABLE_REGISTRATION: "{{ gitea_disable_registration }}"
          RUN_MODE: "prod"
          SSH_DOMAIN: "{{ ansible_nas_hostname }}"
          SSH_PORT: "{{ gitea_port_ssh }}"
          ROOT_URL: "https://{{ gitea_hostname }}.{{ ansible_nas_domain }}/"
          USER_UID: "{{ gitea_uid }}"
          USER_GID: "{{ gitea_gid }}"
          TZ: "{{ ansible_nas_timezone }}"
        labels:
          autoheal: "{{ gitea_autoheal }}"
          com.centurylinklabs.watchtower.enable: "{{ gitea_watchtower_enable }}"
          dockflare.enable: "{{ gitea_dockflare_tunnel }}"
          dockflare.access.group: "{{ gitea_dockflare_access_group }}"
          dockflare.hostname: "{{ gitea_hostname }}.{{ ansible_nas_domain }}"
          dockflare.service: "http://{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}:{{ gitea_port_http }}"
          homepage.name: "{{ ansible_nas_app_name }}"
          homepage.group: "{{ gitea_homepage_group }}"
          homepage.icon: "{{ gitea_homepage_icon }}"
          homepage.href: "{{ gitea_homepage_href }}"
          homepage.siteMonitor: "http://{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}:{{ gitea_port_http }}"
          homepage.description: "{{ 'git with a cup of tea' if homepage_show_description else omit }}"
          homepage.server: "my-docker"
          homepage.container: "{{ gitea_container_name }}"
          homepage.showStats: "{{ gitea_homepage_showstats }}"
          traefik.enable: "{{ gitea_available_externally | string }}"
          traefik.http.routers.gitea.rule: "Host(`{{ gitea_hostname }}.{{ ansible_nas_domain }}`)"
          traefik.http.routers.gitea.tls.certresolver: "letsencrypt"
          traefik.http.routers.gitea.tls.domains[0].main: "{{ ansible_nas_domain }}"
          traefik.http.routers.gitea.tls.domains[0].sans: "*.{{ ansible_nas_domain }}"
          traefik.http.routers.frontend.middlewares: "{{ gitea_hostname }}"
          traefik.http.routers.gitea.middlewares: "{{ gitea_hostname }}@docker"
          traefik.http.middlewares.gitea.IPAllowList.sourcerange: "{{ gitea_traefik_whitelist }}"
          traefik.http.services.gitea.loadbalancer.server.port: "3000"
          wud.tag.include: '^\d+\.\d+\.\d+.*$'
          wud.tag.transform.type: "semver"
          wud.link.template: "https://hub.docker.com/r/gitea/gitea"
        cpu_shares: "{{ gitea_cpu_shares }}"
        memory: "{{ gitea_memory }}"
        restart_policy: unless-stopped

    - name: Access {{ ansible_nas_app_name }} at
      ansible.builtin.debug:
        msg: >-
              {{
                ['http://' + hostvars[inventory_hostname]['ansible_default_ipv4']['address'] + ':' + (gitea_port_http | string)] +
                (['https://' + gitea_hostname + '.' + ansible_nas_domain] if (gitea_available_externally is true or gitea_dockflare_tunnel is true) else [])
              }}
  when: gitea_enabled is true

- name: Stop {{ ansible_nas_app_name }}
  block:
    - name: Stop {{ ansible_nas_app_name }} Container
      community.docker.docker_container:
        name: "{{ gitea_container_name }}"
        state: absent

    - name: Stop {{ ansible_nas_app_name }} DB Container
      community.docker.docker_container:
        name: "{{ gitea_db_container_name }}"
        state: absent
  when: gitea_enabled is false

- name: Data Archive {{ ansible_nas_app_name }}
  block:
    - name: Check for {{ ansible_nas_app_name }} Data Directory
      stat:
        path: "{{ gitea_data_directory }}"
      register: dir_stat

    - name: Archive {{ ansible_nas_app_name }} Data Directory
      ansible.builtin.archive:
        path: "{{ gitea_data_directory }}"
        dest: "{{ docker_home }}/{{ ansible_nas_app_name | lower }}.zip"
        force_archive: true
        format: zip
        owner: ansible-nas
        group: ansible-nas
        mode: u=rw,g=rw
        remove: true
      when: dir_stat.stat.exists
  when: gitea_enabled is false and archive_app_data_enabled is true


# NOTE: configuration options
# https://docs.gitea.com/next/administration/config-cheat-sheet#service-service
