---
ansible_nas_app_name: "Dashy"

dashy_enabled: false
dashy_available_externally: false
dashy_traefik_whitelist: "{{ lan }}"

# directories
dashy_data_directory: "{{ docker_home }}/dashy"

# network
dashy_port: "8082"
dashy_hostname: "dashy"

# specs
dashy_memory: 1g

# docker
dashy_container_name: dashy
dashy_cpu_shares: 1024

# autoheal
dashy_autoheal: "false"

# watchtower
dashy_watchtower_monitor_only: "true"