---
# ANE
ansible_nas_app_name: "Flood"
flood_enabled: false
flood_available_externally: false
flood_traefik_whitelist: "{{ lan }}"

flood_data_directory: "{{ docker_home }}/flood"

# network
flood_hostname: "flood"
flood_port_http: "3003"

# docker
flood_container_name: "flood"
flood_image_name: "jesec/flood"
flood_image_tag: "latest"
flood_cpu_shares: "1024"
flood_memory: "512m"

# autoheal
flood_autoheal: "false"

# dockflare
flood_dockflare_tunnel: "false"
flood_dockflare_access_group: ""

# homepage
flood_homepage_group: "Apps"
flood_homepage_icon: "flood.png"
flood_homepage_href: "http://{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}:{{ flood_port_http }}"
flood_homepage_showStats: "false"
flood_homepage_widget_username: "your username"
flood_homepage_widget_password: "your password"

# watchtower
flood_watchtower_monitor_only: "true"