---
# ANE
ansible_nas_app_name: "Containery"
containery_enabled: false
containery_available_externally: false
containery_traefik_whitelist: "{{ lan }}"

# directories
containery_data_directory: "{{ docker_home }}/containery"

# docker
containery_container_name: "containery"
containery_image_name: "ghcr.io/danylo829/containery"
containery_image_tag: "latest"

# network
containery_port_http: "5002"
containery_hostname: "containery"

# specs
containery_cpu_shares: 1024
containery_memory: "1G"
containery_memory_swap: -1

# autoheal
containery_autoheal: "false"

# dockflare
containery_dockflare_tunnel: "false"
containery_dockflare_access_group: ""

# homepage
containery_homepage_group: "Apps"
containery_homepage_icon: "https://raw.githubusercontent.com/danylo829/containery/master/src/app/static/images/Containery-white.png"
containery_homepage_href: "http://{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}:{{ containery_port_http }}"
containery_homepage_showstats: "false"

# repliqate
containery_repliqate_enabled: "false"
containery_repliqate_engine: "restic"
containery_repliqate_schedule: "@daily 3am"
containery_repliqate_backup_id: "{{ containery_container_name }}"
containery_repliqate_retention: "30d"

# tinyauth
containery_tinyauth_enabled: false

# watchtower
containery_watchtower_enable: "false"
