---
# ANE
ansible_nas_app_name: "ZNC"
znc_enabled: false
znc_available_externally: false
znc_traefik_whitelist: "{{ lan }}"

# directories
znc_data_directory: "{{ docker_home }}/znc"

# uid / gid
znc_user_id: "0"
znc_group_id: "0"

# network
znc_hostname: "znc"
znc_port_http: "6677"

# docker
znc_container_name: "znc"
znc_image_name: "znc"
znc_image_version: "latest"

# specs
znc_cpu_shares: 1024
znc_memory: "1G"

# znc
znc_user_password: "password"
znc_user_nick: "user"
znc_user_altnick: "user_"
znc_user_ident: "user"
znc_user_real_name: "User Name"

# autoheal
znc_autoheal: "false"

# dockflare
znc_dockflare_tunnel: "false"
znc_dockflare_access_group: ""

# homepage
znc_homepage_group: "Apps"
znc_homepage_icon: "znc.png"
znc_homepage_href: "http://{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}:{{ znc_port_http }}"
znc_homepage_showstats: "false"

# repliqate
znc_repliqate_enabled: "false"
znc_repliqate_engine: "restic"
znc_repliqate_schedule: "@daily 3am"
znc_repliqate_backup_id: "{{ znc_container_name }}"
znc_repliqate_retention: "30d"

# watchtower
znc_watchtower_enable: "false"