---
# ANE
ansible_nas_app_name: "Organizr"
organizr_enabled: false
organizr_available_externally: false
organizr_traefik_whitelist: "{{ lan }}"

# directories
organizr_data_directory: "{{ docker_home }}/organizr"

# network
organizr_port_http: "10081"
organizr_port_https: "10444"
organizr_hostname: "organizr"

# docker
organizr_container_name: "organizr"
organizr_image_name: "ghcr.io/organizr/organizr"
organizr_image_version: "latest"

organizr_user_id: "1000"
organizr_group_id: "1000"

# specs
organizr_cpu_shares: 1024
organizr_memory: "1G"

# autoheal
organizr_autoheal: false

# dockflare
organizr_dockflare_enabled: false
organizr_dockflare_access_group: ""

# homepage
organizr_homepage_group: "Apps"
organizr_homepage_icon: "organizr.png"
organizr_homepage_href: "http://{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}:{{ organizr_port_http }}"
organizr_homepage_showstats: false

# repliqate
organizr_repliqate_enabled: false
organizr_repliqate_engine: "restic"
organizr_repliqate_schedule: "@daily 3am"
organizr_repliqate_backup_id: "{{ organizr_container_name }}"
organizr_repliqate_retention: "30d"

# tinyauth
organizr_tinyauth_enabled: false

# watchtower
organizr_watchtower_enabled: false