---
# ANE
ansible_nas_app_name: "Flexget"
flexget_enabled: false
flexget_available_externally: false
flexget_traefik_whitelist: "{{ lan }}"
flexget_data_directory: "{{ docker_home }}/flexget"

# network
flexget_hostname: "flexget"
flexget_port_http: "3539"

# app
flexget_FG_WEBUI_PASSWD: "{{ ansible_nas_app_admin_password }}"
flexget_user_id: "0"
flexget_group_id: "0"

# docker
flexget_container_name: "flexget"
flexget_image_name: "wiserain/flexget"
flexget_image_tag: "latest"
flexget_cpu_shares: "1024"
flexget_memory: "1g"

# autoheal
flexget_autoheal: "false"

# dockflare
flexget_dockflare_tunnel: "false"
flexget_dockflare_access_group: ""

# homepage
flexget_homepage_group: "Apps"
flexget_homepage_icon: "flexget.png"
flexget_homepage_href: "http://{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}:{{ flexget_port_http }}"
flexget_homepage_showstats: "false"

# repliqate
flexget_repliqate_enabled: "false"
flexget_repliqate_engine: "restic"
flexget_repliqate_schedule: "@daily 3am"
flexget_repliqate_backup_id: "flexget"
flexget_repliqate_retention: "30d"

# watchtower
flexget_watchtower_enable: "false"
