---
# ANE
calibre_web_proper_name: "Calibre-Web"
calibre_web_enabled: false
calibre_web_traefik_enabled: false
calibre_web_traefik_whitelist: "{{ lan }}"

# uid / gid
calibre_web_user_id: "0"
calibre_web_group_id: "0"

# directories
calibre_web_data_directory: "{{ docker_home }}/calibre-web"
calibre_web_books_root: "{{ books_root }}"

# network
calibre_web_port_http: "8084"
calibre_web_hostname: "calibreweb"

# specs
calibre_web_cpu_shares: 1024
calibre_web_memory: "1G"
calibre_web_memory_swap: -1

# docker
calibre_web_container_name: "calibre-web"
calibre_web_image_name: "lscr.io/linuxserver/calibre-web"
calibre_web_image_tag: "latest"

# autoheal
calibre_web_autoheal_enabled: false

# dockflare
calibre_web_dockflare_enabled: false
calibre_web_dockflare_access_group: ""

# homepage
calibre_web_homepage_group: "Apps"
calibre_web_homepage_icon: "calibre-web.png"
calibre_web_homepage_href: "http://{{ hostvars[inventory_hostname]['ansible_facts']['default_ipv4']['address'] }}:{{ calibre_web_port_http }}"
calibre_web_homepage_showstats: false
calibre_web_homepage_widget_username: ""
calibre_web_homepage_widget_password: ""

# linuxserver.io docker mods
# https://mods.linuxserver.io/?mod=calibre-web
calibre_web_env_docker_mods: "lscr.io/linuxserver/calibre-web:calibre"
calibre_web_env_docker_mods_install_packages: ""
calibre_web_env_docker_mods_install_pip_packages: ""

# theme.park themes
# https://docs.theme-park.dev/themes/calibre_web/
calibre_web_env_docker_mods_tp_theme: ""
calibre_web_env_docker_mods_tp_community_theme: ""
calibre_web_env_docker_mods_tp_domain: ""
calibre_web_env_docker_mods_tp_addon: ""

# repliqate
calibre_web_repliqate_enabled: false
calibre_web_repliqate_engine: "restic"
calibre_web_repliqate_schedule: "@daily 3am"
calibre_web_repliqate_backup_id: "{{ calibre_web_container_name }}"
calibre_web_repliqate_retention: "30d"

# tinyauth
calibre_web_tinyauth_enabled: false

# watchtower
calibre_web_watchtower_enabled: false