---
- name: Start {{ ansible_nas_app_name }}
  block:
    - name: Create {{ ansible_nas_app_name }} Directories
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
      with_items:
        - "{{ qbittorrent_data_directory }}"
        - "{{ qbittorrent_data_directory }}/config"
        - "{{ qbittorrent_data_directory }}/custom-cont-init.d"
        - "{{ qbittorrent_download_directory }}"
        - "{{ qbittorrent_watch_directory }}"

    - name: Set {{ ansible_nas_app_name }} FQDN var overrides
      ansible.builtin.set_fact:
        qbittorrent_homepage_href: "https://{{ qbittorrent_hostname }}.{{ ansible_nas_domain }}"
      when: qbittorrent_traefik_enabled | bool or qbittorrent_dockflare_enabled | bool

    - name: Create {{ ansible_nas_app_name }} Container
      community.docker.docker_container:
        container_default_behavior: "compatibility"
        name: "{{ qbittorrent_container_name }}"
        hostname: "{{ qbittorrent_container_name }}"
        image: "{{ qbittorrent_image_name }}:{{ qbittorrent_image_tag }}"
        pull: true
        volumes: "{{ [
                  qbittorrent_data_directory ~ '/config:/config:rw',
                  qbittorrent_data_directory ~ '/custom-cont-init.d:/custom-cont-init.d:ro',
                  qbittorrent_download_directory ~ ':/downloads:rw',
                  (qbittorrent_watch_directory ~ ':/torrents:rw') if qbittorrent_watch_directory | default('') != '' else none,
                  qbittorrent_extra_directory | default(none)
                ] | reject('none') | list }}"
        ports:
          - "{{ qbittorrent_port_http }}:{{ qbittorrent_port_http }}"
          - "{{ qbittorrent_port_bt }}:6881"
          - "{{ qbittorrent_port_bt }}:6881/udp"
        env:
          DOCKER_MODS: "{{ qbittorrent_env_docker_mods }}"
          INSTALL_PACKAGES: "{{ qbittorrent_env_docker_mods_install_packages }}"
          INSTALL_PIP_PACKAGES: "{{ qbittorrent_env_docker_mods_install_pip_packages}}"
          TP_DOMAIN: "{{ qbittorrent_env_docker_mods_tp_domain }}"
          TP_THEME: "{{ qbittorrent_env_docker_mods_tp_theme }}"
          TP_COMMUNITY_THEME: "{{ qbittorrent_env_docker_mods_tp_community_theme }}"
          TP_ADDON: "{{ qbittorrent_env_docker_mods_tp_addon }}"
          PUID: "{{ qbittorrent_user_id }}"
          PGID: "{{ qbittorrent_group_id }}"
          UMASK_SET: "{{ qbittorrent_umask }}"
          WEBUI_PORT: "{{ qbittorrent_port_http }}"
          TZ: "{{ ansible_nas_timezone }}"
        labels:
          autoheal: "{{ qbittorrent_autoheal_enabled | ternary('true', 'false') }}"
          com.centurylinklabs.watchtower.enable: "{{ qbittorrent_watchtower_enabled | ternary('true', 'false') }}"
          dockflare.enable: "{{ qbittorrent_dockflare_enabled | ternary('true', 'false') }}"
          dockflare.access.group: "{{ qbittorrent_dockflare_access_group }}"
          dockflare.hostname: "{{ qbittorrent_hostname }}.{{ ansible_nas_domain }}"
          dockflare.service: "http://{{ hostvars[inventory_hostname]['ansible_facts']['default_ipv4']['address'] }}:{{ qbittorrent_port_http }}"
          homepage.name: "{{ ansible_nas_app_name }}"
          homepage.group: "{{ qbittorrent_homepage_group }}"
          homepage.href: "{{ qbittorrent_homepage_href }}"
          homepage.icon: "{{ qbittorrent_homepage_icon }}"
          homepage.siteMonitor: "http://{{ hostvars[inventory_hostname]['ansible_facts']['default_ipv4']['address'] }}:{{ qbittorrent_port_http }}"
          homepage.description: "{{ 'qBittorrent BitTorrent client' if homepage_show_description else omit }}"
          homepage.server: "my-docker"
          homepage.container: "{{ qbittorrent_container_name }}"
          homepage.showStats: "{{ qbittorrent_homepage_showstats | ternary('true', 'false') }}"
          homepage.widget.type: "qbittorrent"
          homepage.widget.url: "http://{{ hostvars[inventory_hostname]['ansible_facts']['default_ipv4']['address'] }}:{{ qbittorrent_port_http }}"
          homepage.widget.username: "{{ qbittorrent_homepage_widget_username }}"
          homepage.widget.password: "{{ qbittorrent_homepage_widget_password }}"
          repliqate.enabled: "{{ qbittorrent_repliqate_enabled | ternary('true', 'false') }}"
          repliqate.engine: "{{ qbittorrent_repliqate_engine }}"
          repliqate.schedule: "{{ qbittorrent_repliqate_schedule }}"
          repliqate.backup_id: "{{ qbittorrent_repliqate_backup_id }}"
          repliqate.retention: "{{ qbittorrent_repliqate_retention }}"
          traefik.enable: "{{ qbittorrent_traefik_enabled | ternary('true', 'false') }}"
          traefik.http.routers.qbittorrent.rule: "Host(`{{ qbittorrent_hostname }}.{{ ansible_nas_domain }}`)"
          traefik.http.routers.qbittorrent.tls.certresolver: "letsencrypt"
          traefik.http.routers.qbittorrent.tls.domains[0].main: "{{ ansible_nas_domain }}"
          traefik.http.routers.qbittorrent.tls.domains[0].sans: "*.{{ ansible_nas_domain }}"
          traefik.http.routers.qbittorrent.middlewares: "{{ qbittorrent_hostname }}@docker{{ ',tinyauth-auth@docker' if qbittorrent_tinyauth_enabled | bool else '' }}"
          traefik.http.middlewares.qbittorrent.IPAllowList.sourcerange: "{{ qbittorrent_traefik_whitelist }}"
          traefik.http.services.qbittorrent.loadbalancer.server.port: "{{ qbittorrent_port_http }}"
          wud.tag.include: '^\d+\.\d+\.\d+.*$'
          wud.tag.transform.type: "semver"
          wud.link.template: "https://lscr.io/linuxserver/qbittorrent"
        cpu_shares: "{{ qbittorrent_cpu_shares }}"
        memory: "{{ qbittorrent_memory }}"
        memory_swap: "{{ qbittorrent_memory_swap }}"
        restart_policy: unless-stopped

    - name: Access {{ ansible_nas_app_name }} at
      ansible.builtin.debug:
        msg: >-
              {{
                ['http://' + hostvars[inventory_hostname]['ansible_facts']['default_ipv4']['address'] + ':' + (qbittorrent_port_http | string)] +
                (['https://' + qbittorrent_hostname + '.' + ansible_nas_domain] if (qbittorrent_traefik_enabled is true or qbittorrent_dockflare_enabled is true) else [])
              }}
  when: qbittorrent_enabled is true

- name: Stop {{ ansible_nas_app_name }}
  block:
    - name: Stop {{ ansible_nas_app_name }} Container
      community.docker.docker_container:
        name: "{{ qbittorrent_container_name }}"
        state: absent
  when: qbittorrent_enabled is false

- name: Data Archive {{ ansible_nas_app_name }}
  include_role:
    name: ansible-nas-archive
  vars:
    target_data_dir: "{{ qbittorrent_data_directory }}"
  when:
    - archive_app_data_enabled is true
    - qbittorrent_enabled is false