---
- name: Start {{ ansible_nas_app_name }}
  block:
    - name: Create {{ ansible_nas_app_name }} Directories
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
      with_items:
        - "{{ freshrss_data_directory }}/db"
        - "{{ freshrss_data_directory }}/data"
        - "{{ freshrss_data_directory }}/extensions"

    - name: Set {{ ansible_nas_app_name }} FQDN var overrides
      ansible.builtin.set_fact:
        freshrss_homepage_href: "https://{{ freshrss_hostname }}.{{ ansible_nas_domain }}"
      when: freshrss_traefik_enabled | bool or freshrss_dockflare_enabled | bool

    - name: Create {{ ansible_nas_app_name }} DB Container
      community.docker.docker_container:
        container_default_behavior: "compatibility"
        name: "{{ freshrss_db_container_name }}"
        hostname: "{{ freshrss_db_container_name }}"
        image: "{{ freshrss_db_image_name }}:{{ freshrss_db_image_version }}"
        pull: true
        volumes:
          - "{{ freshrss_data_directory }}/db:/var/lib/postgresql/data"
        env:
          POSTGRES_USER: "{{ freshrss_db_user }}"
          POSTGRES_PASSWORD: "{{ freshrss_db_password }}"
          POSTGRES_DB: "{{ freshrss_db_base }}"
          TZ: "{{ ansible_nas_timezone }}"
        healthcheck:
          test: ["CMD-SHELL", "pg_isready -U {{ freshrss_db_user }}"]
          interval: 10s
          timeout: 5s
          retries: 5
          start_period: 30s
        labels:
          autoheal: "{{ freshrss_db_autoheal_enabled | ternary('true', 'false') }}"
          com.centurylinklabs.watchtower.enable: "{{ freshrss_db_watchtower_enabled | ternary('true', 'false') }}"
          dockflare.enable: "false"
          homepage.group: "{{ freshrss_db_homepage_group }}"
          homepage.name: "{{ ansible_nas_app_name }} PostgreSQL"
          homepage.icon: "{{ freshrss_db_homepage_icon }}"
          homepage.href: "{{ freshrss_db_homepage_href }}"
          homepage.description: "{{ 'PostgreSQL Database Management System' if homepage_show_description else omit }}"
          homepage.server: "my-docker"
          homepage.container: "{{ freshrss_db_container_name }}"
          homepage.showStats: "{{ freshrss_db_homepage_showstats | ternary('true', 'false') }}"
          repliqate.enabled: "{{ freshrss_db_repliqate_enabled | ternary('true', 'false') }}"
          repliqate.engine: "{{ freshrss_db_repliqate_engine }}"
          repliqate.schedule: "{{ freshrss_db_repliqate_schedule }}"
          repliqate.backup_id: "{{ freshrss_db_repliqate_backup_id }}"
          repliqate.retention: "{{ freshrss_db_repliqate_retention }}"
          traefik.enable: "false"
          wud.tag.include: '^16\.\d+(\.\d+)?-alpine.*$'
          wud.tag.transform.type: "semver"
          wud.link.template: "https://hub.docker.com/_/postgres"
        cpu_shares: "{{ freshrss_db_cpu_shares }}"
        memory: "{{ freshrss_db_memory }}"
        memory_swap: "{{ freshrss_db_memory_swap }}"
        restart_policy: unless-stopped
      register: freshrss_db_status

    - name: Verify {{ ansible_nas_app_name }} DB is healthy
      community.docker.docker_container_info:
        name: "{{ freshrss_db_container_name }}"
      register: db_info
      until: "db_info.container.State.Health.Status == 'healthy'"
      retries: 30
      delay: 5

    - name: Create {{ ansible_nas_app_name }} Container
      community.docker.docker_container:
        container_default_behavior: "compatibility"
        name: "{{ freshrss_container_name }}"
        hostname: "{{ freshrss_container_name }}"
        image: "{{ freshrss_image_name }}:{{ freshrss_image_version }}"
        pull: true
        volumes:
          - "{{ freshrss_data_directory }}/data:/var/www/FreshRSS/data:rw"
          - "{{ freshrss_data_directory }}/extensions:/var/www/FreshRSS/extensions:rw"
        ports:
          - "{{ freshrss_port_http }}:80"
        env:
          CRON_MIN: "{{ freshrss_env_cron_min }}"
          DB_HOST: "{{ freshrss_container_name }}"
          DB_BASE: "{{ freshrss_db_base }}"
          DB_PASSWORD: "{{ freshrss_db_password }}"
          DB_USER: "{{ freshrss_db_user }}"
          TZ: "{{ ansible_nas_timezone }}"
        links:
          - "{{ freshrss_db_container_name }}"
        labels:
          autoheal: "{{ freshrss_autoheal_enabled | ternary('true', 'false') }}"
          com.centurylinklabs.watchtower.enable: "{{ freshrss_watchtower_enabled | ternary('true', 'false') }}"
          dockflare.enable: "{{ freshrss_dockflare_enabled | ternary('true', 'false') }}"
          dockflare.access.group: "{{ freshrss_dockflare_access_group }}"
          dockflare.hostname: "{{ freshrss_hostname }}.{{ ansible_nas_domain }}"
          dockflare.service: "http://{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}:{{ freshrss_port_http }}"
          homepage.group: "{{ freshrss_homepage_group }}"
          homepage.name: "{{ ansible_nas_app_name }}"
          homepage.icon: "{{ freshrss_homepage_icon }}"
          homepage.href: "{{ freshrss_homepage_href }}"
          homepage.siteMonitor: "http://{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}:{{ freshrss_port_http }}"
          homepage.description: "{{ 'A free, self-hostable news aggregator.' if homepage_show_description else omit }}"
          homepage.server: "my-docker"
          homepage.container: "{{ freshrss_container_name }}"
          homepage.showStats: "{{ freshrss_homepage_showstats | ternary('true', 'false') }}"
          homepage.widget.type: "freshrss"
          homepage.widget.url: "http://{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}:{{ freshrss_port_http }}"
          homepage.widget.username: "{{ freshrss_homepage_widget_username }}"
          homepage.widget.password: "{{ freshrss_homepage_widget_password }}"
          repliqate.enabled: "{{ freshrss_repliqate_enabled | ternary('true', 'false') }}"
          repliqate.engine: "{{ freshrss_repliqate_engine }}"
          repliqate.schedule: "{{ freshrss_repliqate_schedule }}"
          repliqate.backup_id: "{{ freshrss_repliqate_backup_id }}"
          repliqate.retention: "{{ freshrss_repliqate_retention }}"
          traefik.enable: "{{ freshrss_traefik_enabled | ternary('true', 'false') }}"
          traefik.http.routers.freshrss.rule: "Host(`{{ freshrss_hostname }}.{{ ansible_nas_domain }}`)"
          traefik.http.routers.freshrss.tls.certresolver: "letsencrypt"
          traefik.http.routers.freshrss.tls.domains[0].main: "{{ ansible_nas_domain }}"
          traefik.http.routers.freshrss.tls.domains[0].sans: "*.{{ ansible_nas_domain }}"
          traefik.http.routers.freshrss.middlewares: "freshrss@docker{{ ',tinyauth-auth@docker' if freshrss_tinyauth_enabled | bool else '' }}"
          traefik.http.middlewares.freshrss.IPAllowList.sourcerange: "{{ freshrss_traefik_whitelist }}"
          traefik.http.services.freshrss.loadbalancer.server.port: "80"
          wud.tag.include: '^\d+\.\d+\.\d+.*$'
          wud.tag.transform.type: "semver"
          wud.link.template: "https://hub.docker.com/r/freshrss/freshrss"
        cpu_shares: "{{ freshrss_cpu_shares }}"
        memory: "{{ freshrss_memory }}"
        memory_swap: "{{ freshrss_memory_swap }}"
        restart_policy: unless-stopped

    - name: Access {{ ansible_nas_app_name }} at
      ansible.builtin.debug:
        msg: >-
              {{
                ['http://' + hostvars[inventory_hostname]['ansible_default_ipv4']['address'] + ':' + (freshrss_port_http | string)] +
                (['https://' + freshrss_hostname + '.' + ansible_nas_domain] if (freshrss_traefik_enabled is true or freshrss_dockflare_enabled is true) else [])
              }}
  when: freshrss_enabled is true

- name: Stop {{ ansible_nas_app_name }}
  block:
    - name: Stop {{ ansible_nas_app_name }} Container
      community.docker.docker_container:
        name: "{{ freshrss_container_name }}"
        state: absent

    - name: Stop {{ ansible_nas_app_name }} DB Container
      community.docker.docker_container:
        name: "{{ freshrss_db_container_name }}"
        state: absent
  when: freshrss_enabled is false

- name: Data Archive {{ ansible_nas_app_name }}
  include_role:
    name: ansible-nas-archive
  vars:
    target_data_dir: "{{ freshrss_data_directory }}"
  when:
    - archive_app_data_enabled is true
    - freshrss_enabled is false