---
# ANE
ansible_nas_app_name: "Loki"
loki_enabled: false
loki_available_externally: false
loki_traefik_whitelist: "{{ lan }}"

# directories
loki_data_directory: "{{ docker_home }}/loki"

# network
loki_hostname: "loki"
loki_network_name: "loki"
loki_port_http: "3100"

# docker
loki_container_name: "loki"
loki_image_name: "grafana/loki"
loki_image_version: "latest"
loki_cpu_shares: 1024

# specs
loki_memory: "1G"

# config
loki_log_retention: 672h
loki_log_level: warn

# autoheal
loki_autoheal: "false"

# dockflare
loki_dockflare_tunnel: "false"
loki_dockflare_access_group: ""

# homepage
loki_homepage_group: "Apps"
loki_homepage_icon: "loki.png"
loki_homepage_href: "http://{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}:{{ loki_port }}"
loki_homepage_showstats: "false"

# repliqate
loki_repliqate_enabled: "false"
loki_repliqate_engine: "restic"
loki_repliqate_schedule: "@daily 3am"
loki_repliqate_backup_id: "{{ loki_container_name }}"
loki_repliqate_retention: "30d"

# tinyauth
loki_tinyauth_enabled: false

# watchtower
loki_watchtower_enable: "false"