---
# ANE
ansible_nas_app_name: "WireGuard"
wireguard_enabled: false
wireguard_available_externally: false

# directories
wireguard_data_directory: "{{ docker_home }}/wireguard"

# app

# network
wireguard_port_http: "51821"
wireguard_port_udp: "51820"
wireguard_hostname: "wireguard"

# docker
wireguard_container_name: "wireguard"
wireguard_image_name: "ghcr.io/wg-easy/wg-easy"
wireguard_image_tag: "latest"

# specs
wireguard_cpu_shares: 1024
wireguard_memory: "512M"

# autoheal
wireguard_autoheal: "false"

# dockflare
wireguard_dockflare_tunnel: "false"
wireguard_dockflare_access_group: ""

# homepage
wireguard_homepage_group: "Apps"
wireguard_homepage_icon: "wireguard.png"
wireguard_homepage_href: "http://{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}:{{ wireguard_port_http }}"
wireguard_homepage_showstats: "false"

# repliqate
wireguard_repliqate_enabled: "false"
wireguard_repliqate_engine: "restic"
wireguard_repliqate_schedule: "@daily 3am"
wireguard_repliqate_backup_id: "{{ wireguard_container_name }}"
wireguard_repliqate_retention: "30d"

# watchtower
wireguard_watchtower_enable: "false"