---
# ANE
ansible_nas_app_name: "WireGuard"
wireguard_enabled: false
wireguard_traefik_enabled: false
wireguard_traefik_whitelist: "{{ lan }}"

# directories
wireguard_data_directory: "{{ docker_home }}/wireguard"

# app

# network
wireguard_port_http: "51821"
wireguard_port_udp: "51820"
wireguard_hostname: "wireguard"

# docker
wireguard_container_name: "wireguard"
wireguard_image_name: "ghcr.io/wg-easy/wg-easy"
wireguard_image_tag: "15"

# specs
wireguard_cpu_shares: 1024
wireguard_memory: "256M"

# app
wireguard_env_host: "0.0.0.0"
wireguard_env_insecure: "true"

# autoheal
wireguard_autoheal_enabled: false

# dockflare
wireguard_dockflare_enabled: false
wireguard_dockflare_access_group: ""

# homepage
wireguard_homepage_group: "Apps"
wireguard_homepage_icon: "wireguard.png"
wireguard_homepage_href: "http://{{ hostvars[inventory_hostname]['ansible_facts']['default_ipv4']['address'] }}:{{ wireguard_port_http }}"
wireguard_homepage_showstats: false
wireguard_homepage_widget_username: ""
wireguard_homepage_widget_password: ""
wireguard_homepage_widget_threshold: "2"
wireguard_homepage_widget_version: "2"

# repliqate
wireguard_repliqate_enabled: false
wireguard_repliqate_engine: "restic"
wireguard_repliqate_schedule: "@daily 3am"
wireguard_repliqate_backup_id: "{{ wireguard_container_name }}"
wireguard_repliqate_retention: "30d"

# tinyauth
wireguard_tinyauth_enabled: false

# watchtower
wireguard_watchtower_enabled: false