---
# ANE
ansible_nas_app_name: "Duplicacy"
duplicacy_enabled: false
duplicacy_available_externally: false
duplicacy_traefik_whitelist: "{{ lan }}"

# directories
duplicacy_data_directory: "{{ docker_home }}/duplicacy"

# permissions
duplicacy_data_permissions: "ro" # Change to 'rw' to allow the UI to restore data

# version
duplicacy_web_version: "Stable"

# uid / gid
duplicacy_user_id: "0"
duplicacy_group_id: "0"

# network
duplicacy_port_http: "3875"
duplicacy_hostname: "duplicacy"

# docker
duplicacy_container_name: "duplicacy"
duplicacy_image_name: "saspus/duplicacy-web"
duplicacy_image_tag: "mini"
duplicacy_cpu_shares: 1024
duplicacy_memory: "1G"

# autoheal
duplicacy_autoheal: "false"

# dockflare
duplicacy_dockflare_tunnel: "false"
duplicacy_dockflare_access_group: ""

# homepage
duplicacy_homepage_group: "Apps"
duplicacy_homepage_icon: "duplicacy.png"
duplicacy_homepage_href: "http://{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}:{{ duplicacy_port_http }}"
duplicacy_homepage_showstats: "false"

# repliqate
duplicacy_repliqate_enabled: "false"
duplicacy_repliqate_engine: "restic"
duplicacy_repliqate_schedule: "@daily 3am"
duplicacy_repliqate_backup_id: "{{ duplicacy_container_name }}"
duplicacy_repliqate_retention: "30d"

# tinyauth
duplicacy_tinyauth_enabled: false

# watchtower
duplicacy_watchtower_enable: "false"