---
# ANE
ansible_nas_app_name: "Heimdall"
heimdall_enabled: false
heimdall_available_externally: false
heimdall_traefik_whitelist: "{{ lan }}"

# directories
heimdall_data_directory: "{{ docker_home }}/heimdall"

# network
heimdall_port_http: "11112"
heimdall_hostname: heimdall

# specs
heimdall_memory: 256m  # changed

# docker
heimdall_container_name: heimdall
heimdall_cpu_shares: 1024
heimdall_docker_image: "lscr.io/linuxserver/heimdall"
heimdall_docker_image_tag: "latest"
heimdall_env_docker_mods: ""

# app
heimdall_puid: "1000"
heimdall_pgid: "1000"

# autoheal
heimdall_autoheal: "false"

# dockflare
heimdall_dockflare_tunnel: "false"
heimdall_dockflare_access_group: ""

# homepage
heimdall_homepage_group: "Apps"
heimdall_homepage_icon: "heimdall.png"
heimdall_homepage_href: "http://{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}:{{ heimdall_port_http }}"
heimdall_homepage_showStats: "false"

# watchtower
heimdall_watchtower_monitor_only: "true"