---
- name: Start {{ ansible_nas_app_name }}
  block:
    - name: Create {{ ansible_nas_app_name }} Directories
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
      with_items:
        - "{{ lancommander_data_directory }}"
        - "{{ lancommander_data_directory }}/config"

    - name: Create {{ ansible_nas_app_name }} Container
      community.docker.docker_container:
        container_default_behavior: "compatibility"
        name: "{{ lancommander_container_name }}"
        hostname: "{{ lancommander_container_name }}"
        image: "{{ lancommander_image_name }}:{{ lancommander_image_tag }}"
        pull: true
        ports:
          - "{{ lancommander_port_http }}:1337"
          - "35891:35891/udp"
        volumes:
          - "{{ lancommander_data_directory }}/config:/config"
        network_mode: bridge
        env:
          PUID: "{{ lancommander_puid }}"
          PGID: "{{ lancommander_pgid }}"
          TZ: "{{ ansible_nas_timezone }}"
        labels:
          autoheal: "{{ lancommander_autoheal | string }}"
          com.centurylinklabs.watchtower.enable: "{{ lancommander_watchtower_enabled | string }}"
          dockflare.enable: "{{ lancommander_dockflare_enabled | string }}"
          dockflare.access.group: "{{ lancommander_dockflare_access_group }}"
          dockflare.hostname: "{{ lancommander_hostname }}.{{ ansible_nas_domain }}"
          dockflare.service: "http://{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}:{{ lancommander_port_http }}"
          homepage.name: "{{ ansible_nas_app_name }}"
          homepage.group: "{{ lancommander_homepage_group }}"
          homepage.icon: "{{ lancommander_homepage_icon }}"
          homepage.href: "{{ lancommander_homepage_href }}"
          homepage.siteMonitor: "http://{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}:{{ lancommander_port_http }}"
          homepage.description: "{{ 'LANCommander is an open-source digital game platform.' if homepage_show_description else omit }}"
          homepage.server: "my-docker"
          homepage.container: "{{ lancommander_container_name }}"
          homepage.showStats: "{{ lancommander_homepage_showstats | string }}"
          repliqate.enabled: "{{ lancommander_repliqate_enabled | string }}"
          repliqate.engine: "{{ lancommander_repliqate_engine }}"
          repliqate.schedule: "{{ lancommander_repliqate_schedule }}"
          repliqate.backup_id: "{{ lancommander_repliqate_backup_id }}"
          repliqate.retention: "{{ lancommander_repliqate_retention }}"
          traefik.enable: "{{ lancommander_available_externally | string }}"
          traefik.http.routers.lancommander.rule: "Host(`{{ lancommander_hostname }}.{{ ansible_nas_domain }}`)"
          traefik.http.routers.lancommander.tls.certresolver: "letsencrypt"
          traefik.http.routers.lancommander.tls.domains[0].main: "{{ ansible_nas_domain }}"
          traefik.http.routers.lancommander.tls.domains[0].sans: "*.{{ ansible_nas_domain }}"
          traefik.http.routers.lancommander.middlewares: "lancommander@docker{{ ',tinyauth-auth@docker' if lancommander_tinyauth_enabled | bool else '' }}"
          traefik.http.middlewares.lancommander.IPAllowList.sourcerange: "{{ lancommander_traefik_whitelist }}"
          traefik.http.services.lancommander.loadbalancer.server.port: "1337"
          wud.tag.include: '^v?\d+\.\d+\.\d+.*$'
          wud.tag.transform.type: "semver"
          wud.link.template: "https://hub.docker.com/r/lancommander/lancommander"
        cpu_shares: "{{ lancommander_cpu_shares }}"
        memory: "{{ lancommander_memory }}"
        memory_swap: "{{ lancommander_memory_swap }}"
        restart_policy: unless-stopped

    - name: Access {{ ansible_nas_app_name }} at
      ansible.builtin.debug:
        msg: >-
              {{
                ['http://' + hostvars[inventory_hostname]['ansible_default_ipv4']['address'] + ':' + (lancommander_port_http | string)] +
                (['https://' + lancommander_hostname + '.' + ansible_nas_domain] if (lancommander_available_externally is true or lancommander_dockflare_enabled is true) else [])
              }}
  when: lancommander_enabled is true

- name: Stop {{ ansible_nas_app_name }}
  block:
    - name: Stop {{ ansible_nas_app_name }} Container
      community.docker.docker_container:
        name: "{{ lancommander_container_name }}"
        state: absent
  when: lancommander_enabled is false

- name: Data Archive {{ ansible_nas_app_name }}
  include_role:
    name: ansible-nas-archive
  vars:
    target_data_dir: "{{ lancommander_data_directory }}"
  when:
    - archive_app_data_enabled is true
    - lancommander_enabled is false