---
- name: Start Prowlarr
  block:
    - name: Create {{ ansible_nas_app_name }} Directories
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
      with_items:
        - "{{ prowlarr_data_directory }}"
        - "{{ prowlarr_data_directory }}/config"

    - name: Set {{ ansible_nas_app_name }} FQDN var overrides
      ansible.builtin.set_fact:
        prowlarr_homepage_href: "https://{{ prowlarr_hostname }}.{{ ansible_nas_domain }}"
      when: prowlarr_traefik_enabled | bool or prowlarr_dockflare_enabled | bool

    - name: Create {{ ansible_nas_app_name }} Container
      community.docker.docker_container:
        container_default_behavior: "compatibility"
        name: "{{ prowlarr_container_name }}"
        hostname: "{{ prowlarr_container_name }}"
        image: "{{ prowlarr_image_name }}:{{ prowlarr_image_version }}"
        pull: true
        volumes:
          - "{{ prowlarr_data_directory }}/config:/config:rw"
        ports:
          - "{{ prowlarr_port_http }}:9696"
        env:
          DOCKER_MODS: "{{ prowlarr_env_docker_mods }}"
          INSTALL_PACKAGES: "{{ prowlarr_env_docker_mods_install_packages }}"
          INSTALL_PIP_PACKAGES: "{{ prowlarr_env_docker_mods_install_pip_packages}}"
          TP_DOMAIN: "{{ prowlarr_env_docker_mods_tp_domain }}"
          TP_THEME: "{{ prowlarr_env_docker_mods_tp_theme }}"
          TP_COMMUNITY_THEME: "{{ prowlarr_env_docker_mods_tp_community_theme }}"
          TP_ADDON: "{{ prowlarr_env_docker_mods_tp_addon }}"
          PUID: "{{ prowlarr_user_id }}"
          PGID: "{{ prowlarr_group_id }}"
          TZ: "{{ ansible_nas_timezone }}"
        labels:
          autoheal: "{{ prowlarr_autoheal_enabled | ternary('true', 'false') }}"
          com.centurylinklabs.watchtower.enable: "{{ prowlarr_watchtower_enabled | ternary('true', 'false') }}"
          dockflare.enable: "{{ prowlarr_dockflare_enabled | ternary('true', 'false') }}"
          dockflare.access.group: "{{ prowlarr_dockflare_access_group }}"
          dockflare.hostname: "{{ prowlarr_hostname }}.{{ ansible_nas_domain }}"
          dockflare.service: "http://{{ hostvars[inventory_hostname]['ansible_facts']['default_ipv4']['address'] }}:{{ prowlarr_port_http }}"
          homepage.name: "{{ ansible_nas_app_name }}"
          homepage.group: "{{ prowlarr_homepage_group }}"
          homepage.icon: "{{ prowlarr_homepage_icon }}"
          homepage.href: "{{ prowlarr_homepage_href }}"
          homepage.siteMonitor: "http://{{ hostvars[inventory_hostname]['ansible_facts']['default_ipv4']['address'] }}:{{ prowlarr_port_http }}"
          homepage.description: "{{ 'Indexer Proxy' if homepage_show_description else omit }}"
          homepage.server: "my-docker"
          homepage.container: "{{ prowlarr_container_name }}"
          homepage.showStats: "{{ prowlarr_homepage_showstats | ternary('true', 'false') }}"
          homepage.widget.type: "prowlarr"
          homepage.widget.url: "http://{{ hostvars[inventory_hostname]['ansible_facts']['default_ipv4']['address'] }}:{{ prowlarr_port_http }}"
          homepage.widget.key: "{{ prowlarr_homepage_widget_key }}"
          repliqate.enabled: "{{ prowlarr_repliqate_enabled | ternary('true', 'false') }}"
          repliqate.engine: "{{ prowlarr_repliqate_engine }}"
          repliqate.schedule: "{{ prowlarr_repliqate_schedule }}"
          repliqate.backup_id: "{{ prowlarr_repliqate_backup_id }}"
          repliqate.retention: "{{ prowlarr_repliqate_retention }}"
          traefik.enable: "{{ prowlarr_traefik_enabled | ternary('true', 'false') }}"
          traefik.http.routers.prowlarr.rule: "Host(`{{ prowlarr_hostname }}.{{ ansible_nas_domain }}`)"
          traefik.http.routers.prowlarr.tls.certresolver: "letsencrypt"
          traefik.http.routers.prowlarr.tls.domains[0].main: "{{ ansible_nas_domain }}"
          traefik.http.routers.prowlarr.tls.domains[0].sans: "*.{{ ansible_nas_domain }}"
          traefik.http.routers.prowlarr.middlewares: "{{ prowlarr_hostname }}@docker{{ ',tinyauth-auth@docker' if prowlarr_tinyauth_enabled | bool else '' }}"
          traefik.http.middlewares.prowlarr.IPAllowList.sourcerange: "{{ prowlarr_traefik_whitelist }}"
          traefik.http.services.prowlarr.loadbalancer.server.port: "9696"
          wud.tag.include: '^\d+\.\d+\.\d+.*$'
          wud.tag.transform.type: "semver"
          wud.link.template: "https://lscr.io/linuxserver/prowlarr"
        cpu_shares: "{{ prowlarr_cpu_shares }}"
        memory: "{{ prowlarr_memory }}"
        memory_swap: "{{ prowlarr_memory_swap }}"
        restart_policy: unless-stopped

    - name: Access {{ ansible_nas_app_name }} at
      ansible.builtin.debug:
        msg: >-
              {{
                ['http://' + hostvars[inventory_hostname]['ansible_facts']['default_ipv4']['address'] + ':' + (prowlarr_port_http | string)] +
                (['https://' + prowlarr_hostname + '.' + ansible_nas_domain] if (prowlarr_traefik_enabled is true or prowlarr_dockflare_enabled is true) else [])
              }}
  when: prowlarr_enabled is true

- name: Stop {{ ansible_nas_app_name }}
  block:
    - name: Stop {{ ansible_nas_app_name }} Container
      community.docker.docker_container:
        name: "{{ prowlarr_container_name }}"
        state: absent
  when: prowlarr_enabled is false

- name: Data Archive {{ ansible_nas_app_name }}
  include_role:
    name: ansible-nas-archive
  vars:
    target_data_dir: "{{ prowlarr_data_directory }}"
  when:
    - archive_app_data_enabled is true
    - prowlarr_enabled is false