---
# ANE
ansible_nas_app_name: "DokuWiki"
dokuwiki_enabled: false
dokuwiki_available_externally: false
dokuwiki_traefik_whitelist: "{{ lan }}"

# directories
dokuwiki_data_directory: "{{ docker_home }}/dokuwiki"

# uid / gid
dokuwiki_user_id: "1000"
dokuwiki_group_id: "1000"

# network
dokuwiki_hostname: "dokuwiki"
dokuwiki_port: "8085"

# specs
dokuwiki_memory: 1g

# docker
dokuwiki_container_name: dokuwiki
dokuwiki_cpu_shares: 1024
dokuwiki_image_name: "lscr.io/linuxserver/dokuwiki"
dokuwiki_image_tag: "latest"
dokuwiki_env_docker_mods: ""

# autoheal
dokuwiki_autoheal: "false"

# dockflare
dokuwiki_dockflare_tunnel: "false"
dokuwiki_dockflare_access_group: ""

# homepage
dokuwiki_homepage_group: "Apps"
dokuwiki_homepage_icon: "dokuwiki.png"
dokuwiki_homepage_href: "http://{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}:{{ dokuwiki_port }}"
dokuwiki_homepage_showStats: "false"

# watchtower
dokuwiki_watchtower_monitor_only: "true"