---
# ANE
ansible_nas_app_name: "CouchDB"
couchdb_enabled: false
couchdb_available_externally: false
couchdb_traefik_whitelist: "{{ lan }}"

# Data directory for config and data directories
couchdb_data_directory: "{{ docker_home }}/couchdb"

# CouchDB local admin user
couchdb_admin_user: "admin"
couchdb_admin_password: "changeme"

# network
couchdb_hostname: "couchdb"
couchdb_port_http: "5984"

# docker
couchdb_container_name: "couchdb"
couchdb_image_name: "couchdb"
couchdb_image_version: "latest"

# specs
couchdb_cpu_shares: 1024
couchdb_memory: 1024MB
couchdb_memory_swap: -1

# autoheal
couchdb_autoheal: false

# dockflare
couchdb_dockflare_enabled: false
couchdb_dockflare_access_group: ""

# homepage
couchdb_homepage_group: "DBs"
couchdb_homepage_icon: "couchdb.png"
couchdb_homepage_href: "http://{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}:{{ couchdb_port_http }}"
couchdb_homepage_showstats: false

# repliqate
couchdb_repliqate_enabled: false
couchdb_repliqate_engine: "restic"
couchdb_repliqate_schedule: "@daily 3am"
couchdb_repliqate_backup_id: "{{ couchdb_container_name }}"
couchdb_repliqate_retention: "30d"

# tinyauth
couchdb_tinyauth_enabled: false

# watchtower
couchdb_watchtower_enabled: false