---
- name: Start {{ ansible_nas_app_name }}
  block:
    - name: Check for Minio installation
      ansible.builtin.fail:
        msg: "Loki requires Minio enabled and running for storage, please set that up first."
      when: minio_enabled is false

    - name: Check for Grafana installation
      ansible.builtin.fail:
        msg: "Loki requires Grafana enabled and running for visualisation, please set that up first."
      when: grafana_enabled is false

    - name: Include Stats variables
      ansible.builtin.include_vars: ../../stats/defaults/main.yml

    - name: Create {{ ansible_nas_app_name }} Directories
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
      with_items:
        - "{{ loki_data_directory }}"

    - name: Create Minio buckets for {{ ansible_nas_app_name }}
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
      with_items:
        - "{{ minio_data_directory }}/data/loki-data"
        - "{{ minio_data_directory }}/data/loki-ruler"

    - name: Copy {{ ansible_nas_app_name }} config
      ansible.builtin.template:
        src: config.yml
        dest: "{{ loki_data_directory }}/config.yml"
      register: loki_config

    - name: Create {{ ansible_nas_app_name }} Container
      community.docker.docker_container:
        container_default_behavior: "compatibility"
        name: "{{ loki_container_name }}"
        hostname: "{{ loki_container_name }}"
        image: "{{ loki_image_name }}:{{ loki_image_version }}"
        pull: true
        command: "-config.file=/etc/loki/config.yml"
        ports:
          - "{{ loki_http_port }}:3100"
          - 7946
          - 9095
        volumes:
          - "{{ loki_data_directory }}/config.yml:/etc/loki/config.yml"
        labels:
          autoheal: "{{ loki_autoheal }}"
          com.centurylinklabs.watchtower.monitor-only: "{{ loki_watchtower_monitor_only }}"
          homepage.name: "{{ ansible_nas_app_name }}"
          homepage.group: "{{ loki_homepage_group }}"
          homepage.icon: "{{ loki_homepage_icon }}"
          homepage.href: "{{ loki_homepage_href }}"
          homepage.description: "{{ 'loki description' if homepage_show_description else omit }}"
          homepage.server: "my-docker"
          homepage.container: "{{ loki_container_name }}"
          homepage.showStats: "{{ loki_homepage_showStats }}"
          homepage.siteMonitor: "http://{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}:{{ loki_port }}"
          prometheus.io/scrape: "true"
          prometheus.io/port: "3100"
          prometheus.io/path: "/metrics"
          traefik.enable: "{{ loki_available_externally | string }}"
          traefik.http.routers.loki.rule: "Host(`{{ loki_hostname }}.{{ ansible_nas_domain }}`)"
          traefik.http.routers.loki.tls.certresolver: "letsencrypt"
          traefik.http.routers.loki.tls.domains[0].main: "{{ ansible_nas_domain }}"
          traefik.http.routers.loki.tls.domains[0].sans: "*.{{ ansible_nas_domain }}"
          traefik.http.routers.frontend.middlewares: "{{ loki_hostname }}"
          traefik.http.routers.loki.middlewares: "{{ loki_hostname }}@docker"
          traefik.http.middlewares.loki.IPAllowList.sourcerange: "{{ loki_traefik_whitelist }}"
          traefik.http.services.loki.loadbalancer.server.port: "3100"
          wud.tag.include: '^\d+\.\d+\.\d+$$'
          wud.link.template: "https://github.com/grafana/loki/releases/tag/$${major}.$${minor}.$${patch}"
        cpu_shares: "{{ loki_cpu_shares }}"
        memory: "{{ loki_memory }}"
        restart: "{{ loki_config is changed }}"
        restart_policy: unless-stopped

    - name: Template Grafana {{ ansible_nas_app_name }} data source
      ansible.builtin.template:
        src: grafana-datasource.yml
        dest: "{{ stats_grafana_config_directory }}/provisioning/datasources/loki.yml"
        owner: "472"
      notify: restart grafana
  when: loki_enabled is true

- name: Stop {{ ansible_nas_app_name }}
  block:
    - name: Stop {{ ansible_nas_app_name }} Container
      community.docker.docker_container:
        name: "{{ loki_container_name }}"
        state: absent
  when: loki_enabled is false

- name: Data Archive {{ ansible_nas_app_name }}
  block:
    - name: Check for {{ ansible_nas_app_name }} Data Directory
      stat:
        path: "{{ loki_data_directory }}"
      register: dir_stat

    - name: Archive {{ ansible_nas_app_name }} Data Directory
      ansible.builtin.archive:
        path: "{{ loki_data_directory }}"
        dest: "{{ docker_home }}/{{ ansible_nas_app_name | lower }}.zip"
        force_archive: true
        format: zip
        owner: ansible-nas
        group: ansible-nas
        mode: u=rw,g=rw
        remove: true
      when: dir_stat.stat.exists
  when: loki_enabled is false and archive_app_data_enabled is true
