---
# ANE
ansible_nas_app_name: "DumbAssets"
dumbassets_enabled: false
dumbassets_traefik_enabled: false
dumbassets_traefik_whitelist: "{{ lan }}"

# directories
dumbassets_data_directory: "{{ docker_home }}/dumbassets"

# docker
dumbassets_container_name: "dumbassets"
dumbassets_image_name: "dumbwareio/dumbassets"
dumbassets_image_tag: "latest"

# network
dumbassets_hostname: "dumbassets"
dumbassets_port_http: "3057"

# specs
dumbassets_cpu_shares: 1024
dumbassets_memory: "1G"
dumbassets_memory_swap: -1

# app
dumbassets_node_env: "production"
dumbassets_debug: "true"
dumbassets_site_title: "DumbAssets"
dumbassets_base_url: "http://{{ hostvars[inventory_hostname]['ansible_facts']['default_ipv4']['address'] }}:{{ dumbassets_port_http }}"
dumbassets_pin: "1234"
dumbassets_allowed_origins: "*"
dumbassets_demo_mode: "false"
dumbassets_apprise_url: ""
dumbassets_currency_code: "USD"
dumbassets_locale: "en-US"

# autoheal
dumbassets_autoheal_enabled: false

# dockflare
dumbassets_dockflare_enabled: false
dumbassets_dockflare_access_group: ""

# homepage
dumbassets_homepage_group: "Apps"
dumbassets_homepage_icon: "dumbassets.png"
dumbassets_homepage_href: "http://{{ hostvars[inventory_hostname]['ansible_facts']['default_ipv4']['address'] }}:{{ dumbassets_port_http }}"
dumbassets_homepage_showstats: false

# repliqate
dumbassets_repliqate_enabled: false
dumbassets_repliqate_engine: "restic"
dumbassets_repliqate_schedule: "@daily 3am"
dumbassets_repliqate_backup_id: "{{ dumbassets_container_name }}"
dumbassets_repliqate_retention: "30d"

# tinyauth
dumbassets_tinyauth_enabled: false

# watchtower
dumbassets_watchtower_enabled: false
