---
# ANE
ansible_nas_app_name: "Diskover"
diskover_enabled: false
diskover_available_externally: false
diskover_traefik_whitelist: "{{ lan }}"

# directories
diskover_data_directory: "{{ docker_home }}/diskover"

# network
diskover_hostname: "diskover"
diskover_network_name: "diskover"
diskover_port_http: "3005"
diskover_elasticsearch_hostname: "elasticsearch"
diskover_elasticsearch_port_http: "9200"

# docker
diskover_container_name: "diskover"
diskover_image_name: "lscr.io/linuxserver/diskover"
diskover_image_tag: "latest"
diskover_cpu_shares: "1024"
diskover_memory: "4g"
diskover_elasticsearch_container_name: "diskover-elasticsearch"
diskover_elasticsearch_image_name: "public.ecr.aws/elastic/elasticsearch"
diskover_elasticsearch_image_tag: "8.16.2"
diskover_elasticsearch_cpu_shares: "1024"
diskover_elasticsearch_memory: "2g"
diskover_elasticsearch_helper_container_name: "diskover-elasticsearch-helper"
diskover_elasticsearch_helper_image_name: "alpine"
diskover_elasticsearch_helper_image_tag: "latest"

# autoheal
diskover_autoheal: "false"
diskover_elasticsearch_autoheal: "false"

# dockflare
diskover_dockflare_tunnel: "false"
diskover_dockflare_access_group: ""

# homepage
diskover_homepage_group: "Apps"
diskover_homepage_icon: "diskover.png"
diskover_homepage_href: "http://{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}:{{ diskover_port_http }}"
diskover_homepage_showstats: "false"
diskover_elasticsearch_homepage_group: "Apps"
diskover_elasticsearch_homepage_icon: "elasticsearch.png"
diskover_elasticsearch_homepage_href: "http://{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}:{{ diskover_elasticsearch_port_http }}"
diskover_elasticsearch_homepage_showstats: "false"

# linuxserver.io docker mods
diskover_env_docker_mods: ""

# watchtower
diskover_watchtower_enable: "false"
diskover_elasticsearch_watchtower_enable: "false"