---
- name: Start {{ yadnsb_proper_name }}
  block:

    - name: Set {{ yadnsb_proper_name }} FQDN var overrides
      ansible.builtin.set_fact:
        yadnsb_homepage_href: "https://{{ yadnsb_hostname }}.{{ ansible_nas_domain }}"
      when: yadnsb_traefik_enabled | bool or yadnsb_dockflare_enabled | bool

    - name: Create {{ yadnsb_proper_name }} Container
      community.docker.docker_container:
        container_default_behavior: "compatibility"
        name: "{{ yadnsb_container_name }}"
        hostname: "{{ yadnsb_container_name }}"
        image: "{{ yadnsb_image_name }}:{{ yadnsb_image_tag }}"
        pull: true
        ports:
          - "{{ yadnsb_port_http }}:3000"
        env:
          TZ: "{{ ansible_nas_timezone }}"
        healthcheck:
          test: wget --no-verbose --tries=1 --spider http://localhost:3000/ || exit 1
          interval: 15s
          timeout: 5s
          retries: 3
          start_period: 15s
        labels:
          autoheal: "{{ yadnsb_autoheal_enabled | ternary('true', 'false') }}"
          com.centurylinklabs.watchtower.enable: "{{ yadnsb_watchtower_enabled | ternary('true', 'false') }}"
          dockflare.enable: "{{ yadnsb_dockflare_enabled | ternary('true', 'false') }}"
          dockflare.access.group: "{{ yadnsb_dockflare_access_group }}"
          dockflare.hostname: "{{ yadnsb_hostname }}.{{ ansible_nas_domain }}"
          dockflare.service: "http://{{ hostvars[inventory_hostname]['ansible_facts']['default_ipv4']['address'] }}:{{ yadnsb_port_http }}"
          homepage.name: "{{ yadnsb_proper_name }}"
          homepage.group: "{{ yadnsb_homepage_group }}"
          homepage.icon: "{{ yadnsb_homepage_icon }}"
          homepage.href: "{{ yadnsb_homepage_href }}"
          homepage.description: "{{ 'DNS performance benchmarks' if homepage_show_description else omit }}"
          homepage.server: "my-docker"
          homepage.container: "{{ yadnsb_container_name }}"
          homepage.showStats: "{{ yadnsb_homepage_showstats | ternary('true', 'false') }}"
          homepage.siteMonitor: "http://{{ hostvars[inventory_hostname]['ansible_facts']['default_ipv4']['address'] }}:{{ yadnsb_port_http }}"
          repliqate.enabled: "false"
          traefik.enable: "{{ yadnsb_traefik_enabled | ternary('true', 'false') }}"
          traefik.http.routers.yadnsb.rule: "Host(`{{ yadnsb_hostname }}.{{ ansible_nas_domain }}`)"
          traefik.http.routers.yadnsb.tls.certresolver: "letsencrypt"
          traefik.http.routers.yadnsb.tls.domains[0].main: "{{ ansible_nas_domain }}"
          traefik.http.routers.yadnsb.tls.domains[0].sans: "*.{{ ansible_nas_domain }}"
          traefik.http.routers.yadnsb.middlewares: "yadnsb@docker{{ ',tinyauth-auth@docker' if yadnsb_tinyauth_enabled | bool else '' }}"
          traefik.http.middlewares.yadnsb.IPAllowList.sourcerange: "{{ yadnsb_traefik_whitelist }}"
          traefik.http.services.yadnsb.loadbalancer.server.port: "3000"
          wud.tag.include: '^v\d+\.\d+\.\d+.*$'
          wud.tag.transform.type: "semver"
          wud.link.template: "https://github.com/altendorfme/yadnsb/pkgs/container/yadnsb"
        cpu_shares: "{{ yadnsb_cpu_shares }}"
        memory: "{{ yadnsb_memory }}"
        memory_swap: "{{ yadnsb_memory_swap }}"
        security_opts: ["no-new-privileges:true"]
        restart_policy: unless-stopped

    - name: Access {{ yadnsb_proper_name }} at
      ansible.builtin.debug:
        msg: >-
              {{
                ['http://' + hostvars[inventory_hostname]['ansible_facts']['default_ipv4']['address'] + ':' + (yadnsb_port_http | string)] +
                (['https://' + yadnsb_hostname + '.' + ansible_nas_domain] if (yadnsb_traefik_enabled is true or yadnsb_dockflare_enabled is true) else [])
              }}
  when: yadnsb_enabled is true

- name: Stop {{ yadnsb_proper_name }}
  block:
    - name: Stop {{ yadnsb_proper_name }} Container
      community.docker.docker_container:
        name: "{{ yadnsb_container_name }}"
        state: absent
  when: yadnsb_enabled is false
