---
# This repository was archived by the owner on Jun 29, 2025. It is now read-only.
- name: Start {{ ansible_nas_app_name }}
  block:
    - name: Create {{ ansible_nas_app_name }} Directories
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
      with_items:
        - "{{ pingvin_share_data_directory }}"
        - "{{ pingvin_share_data_directory }}/data"
        - "{{ pingvin_share_data_directory }}/data/images"

    - name: Create {{ ansible_nas_app_name }} Container
      community.docker.docker_container:
        container_default_behavior: "compatibility"
        name: "{{ pingvin_share_container_name }}"
        hostname: "{{ pingvin_share_container_name }}"
        image: "{{ pingvin_share_image_name }}:{{ pingvin_share_image_tag }}"
        pull: true
        ports:
          - "{{ pingvin_share_port_http }}:3333"
        volumes:
          - "{{ pingvin_share_data_directory }}/data:/opt/app/backend/data"
          - "{{ pingvin_share_data_directory }}/data/images:/opt/app/frontend/public/img"
        network_mode: bridge
        env:
          TZ: "{{ ansible_nas_timezone }}"
        labels:
          autoheal: "{{ pingvin_share_autoheal }}"
          com.centurylinklabs.watchtower.enable: "{{ pingvin_share_watchtower_enable }}"
          dockflare.enable: "{{ pingvin_share_dockflare_tunnel }}"
          dockflare.access.group: "{{ pingvin_share_dockflare_access_group }}"
          dockflare.hostname: "{{ pingvin_share_hostname }}.{{ ansible_nas_domain }}"
          dockflare.service: "http://{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}:{{ pingvin_share_port_http }}"
          homepage.name: "{{ ansible_nas_app_name }}"
          homepage.group: "{{ pingvin_share_homepage_group }}"
          homepage.icon: "{{ pingvin_share_homepage_icon }}"
          homepage.href: "{{ pingvin_share_homepage_href }}"
          homepage.siteMonitor: "http://{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}:{{ pingvin_share_port_http }}"
          homepage.description: "{{ 'A self-hosted file sharing platform that combines lightness and beauty, perfect for seamless and efficient file sharing.' if homepage_show_description else omit }}"
          homepage.server: "my-docker"
          homepage.container: "{{ pingvin_share_container_name }}"
          homepage.showStats: "{{ pingvin_share_homepage_showstats }}"
          repliqate.enabled: "{{ pingvin_share_repliqate_enabled }}"
          repliqate.engine: "{{ pingvin_share_repliqate_engine }}"
          repliqate.schedule: "{{ pingvin_share_repliqate_schedule }}"
          repliqate.backup_id: "{{ pingvin_share_repliqate_backup_id }}"
          repliqate.retention: "{{ pingvin_share_repliqate_retention }}"
          traefik.enable: "{{ pingvin_share_available_externally | string }}"
          traefik.http.routers.pingvinshare.rule: "Host(`{{ pingvin_share_hostname }}.{{ ansible_nas_domain }}`)"
          traefik.http.routers.pingvinshare.tls.certresolver: "letsencrypt"
          traefik.http.routers.pingvinshare.tls.domains[0].main: "{{ ansible_nas_domain }}"
          traefik.http.routers.pingvinshare.tls.domains[0].sans: "*.{{ ansible_nas_domain }}"
          traefik.http.routers.pingvinshare.middlewares: "pingvinshare@docker{{ ',tinyauth-auth@docker' if pingvin_share_tinyauth_enabled | bool else '' }}"
          traefik.http.middlewares.pingvinshare.IPAllowList.sourcerange: "{{ pingvin_share_traefik_whitelist }}"
          traefik.http.services.pingvinshare.loadbalancer.server.port: "3333"
          wud.tag.include: '^v\d+\.\d+\.\d+$'
          wud.tag.transform.type: "semver"
          wud.link.template: "https://github.com/stonith404/pingvin-share/pkgs/container/pingvin-share"
        cpu_shares: "{{ pingvin_share_cpu_shares }}"
        memory: "{{ pingvin_share_memory }}"
        restart_policy: unless-stopped

    - name: Access {{ ansible_nas_app_name }} at
      ansible.builtin.debug:
        msg: >-
              {{
                ['http://' + hostvars[inventory_hostname]['ansible_default_ipv4']['address'] + ':' + (pingvin_share_port_http | string)] +
                (['https://' + pingvin_share_hostname + '.' + ansible_nas_domain] if (pingvin_share_available_externally is true or pingvin_share_dockflare_tunnel is true) else [])
              }}
  when: pingvin_share_enabled is true

- name: Stop {{ ansible_nas_app_name }}
  block:
    - name: Stop {{ ansible_nas_app_name }} Container
      community.docker.docker_container:
        name: "{{ pingvin_share_container_name }}"
        state: absent
  when: pingvin_share_enabled is false

- name: Data Archive {{ ansible_nas_app_name }}
  include_role:
    name: ansible-nas-archive
  vars:
    target_data_dir: "{{ pingvin_share_data_directory }}"
  when:
    - archive_app_data_enabled is true
    - pingvin_share_enabled is false