---
- name: Start {{ ansible_nas_app_name }}
  block:
    - name: Create {{ ansible_nas_app_name }} Directory
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
      with_items:
        - "{{ homebox_data_directory }}"
        - "{{ homebox_data_directory }}/data"

    - name: Create {{ ansible_nas_app_name }} Container
      community.docker.docker_container:
        container_default_behavior: "compatibility"
        name: "{{ homebox_container_name }}"
        hostname: "{{ homebox_container_name }}"
        image: "{{ homebox_image_name }}:{{ homebox_image_tag }}"
        pull: true
        volumes:
          - "{{ homebox_data_directory }}/data:/data"
        ports:
          - "{{ homebox_port_http }}:7745"
        env:
          HBOX_MAILER_HOST: "{{ homebox_mail_host }}"
          HBOX_MAILER_PORT: "{{ homebox_mail_port }}"
          HBOX_MAILER_USERNAME: "{{ homebox_mail_username }}"
          HBOX_MAILER_PASSWORD: "{{ homebox_mail_password }}"
          HBOX_MAILER_FROM: "{{ homebox_mail_from }}"
          TZ: "{{ ansible_nas_timezone }}"
        labels:
          autoheal: "{{ homebox_autoheal | string }}"
          com.centurylinklabs.watchtower.enable: "{{ homebox_watchtower_enabled | string }}"
          dockflare.enable: "{{ homebox_dockflare_enabled | string }}"
          dockflare.access.group: "{{ homebox_dockflare_access_group }}"
          dockflare.hostname: "{{ homebox_hostname }}.{{ ansible_nas_domain }}"
          dockflare.service: "http://{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}:{{ homebox_port_http }}"
          homepage.name: "{{ ansible_nas_app_name }}"
          homepage.group: "{{ homebox_homepage_group }}"
          homepage.icon: "{{ homebox_homepage_icon }}"
          homepage.href: "{{ homebox_homepage_href }}"
          homepage.description: "{{ 'Homebox is the inventory and organization system built for the Home User!' if homepage_show_description else omit }}"
          homepage.siteMonitor: "http://{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}:{{ homebox_port_http }}"
          homepage.server: "my-docker"
          homepage.container: "{{ homebox_container_name }}"
          homepage.showStats: "{{ homebox_homepage_showstats | string }}"
          homepage.widget.type: "homebox"
          homepage.widget.url: "http://{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}:{{ homebox_port_http }}"
          homepage.widget.username: "{{ homebox_homepage_widget_username }}"
          homepage.widget.password: "{{ homebox_homepage_widget_password }}"
          repliqate.enabled: "{{ homebox_repliqate_enabled | string }}"
          repliqate.engine: "{{ homebox_repliqate_engine }}"
          repliqate.schedule: "{{ homebox_repliqate_schedule }}"
          repliqate.backup_id: "{{ homebox_repliqate_backup_id }}"
          repliqate.retention: "{{ homebox_repliqate_retention }}"
          traefik.enable: "{{ homebox_available_externally | string }}"
          traefik.http.routers.homebox.rule: "Host(`{{ homebox_hostname }}.{{ ansible_nas_domain }}`)"
          traefik.http.routers.homebox.tls.certresolver: "letsencrypt"
          traefik.http.routers.homebox.tls.domains[0].main: "{{ ansible_nas_domain }}"
          traefik.http.routers.homebox.tls.domains[0].sans: "*.{{ ansible_nas_domain }}"
          traefik.http.routers.homebox.middlewares: "homebox@docker{{ ',tinyauth-auth@docker' if homebox_tinyauth_enabled | bool else '' }}"
          traefik.http.middlewares.homebox.IPAllowList.sourcerange: "{{ homebox_traefik_whitelist }}"
          traefik.http.services.homebox.loadbalancer.server.port: "7745"
          wud.tag.include: '^\d+\.\d+\.\d+.*$'
          wud.tag.transform.type: "semver"
          wud.link.template: "https://github.com/hay-kot/homebox/releases"
        cpu_shares: "{{ homebox_cpu_shares }}"
        memory: "{{ homebox_memory }}"
        memory_swap: "{{ homebox_memory_swap }}"
        restart_policy: unless-stopped

    - name: Access {{ ansible_nas_app_name }} at
      ansible.builtin.debug:
        msg: >-
              {{
                ['http://' + hostvars[inventory_hostname]['ansible_default_ipv4']['address'] + ':' + (homebox_port_http | string)] +
                (['https://' + homebox_hostname + '.' + ansible_nas_domain] if (homebox_available_externally is true or homebox_dockflare_enabled is true) else [])
              }}
  when: homebox_enabled is true

- name: Stop {{ ansible_nas_app_name }}
  block:
    - name: Stop {{ ansible_nas_app_name }} Container
      community.docker.docker_container:
        name: "{{ homebox_container_name }}"
        state: absent
  when: homebox_enabled is false

- name: Data Archive {{ ansible_nas_app_name }}
  include_role:
    name: ansible-nas-archive
  vars:
    target_data_dir: "{{ homebox_data_directory }}"
  when:
    - archive_app_data_enabled is true
    - homebox_enabled is false