---
ansible_nas_app_name: "Mumble"

mumble_enabled: false
mumble_available_externally: false
mumble_traefik_whitelist: "{{ lan }}"

# Directories
mumble_data_directory: "{{ docker_home }}/mumble"

# Networking
mumble_tcp_port: "64738"
mumble_udp_port: "64738"
mumble_hostname: mumble

# Configuration
# It is strongly advised this password is change, especially if this is publicly available.
mumble_server_password: "abcpassword123"

# docker
mumble_container_name: mumble-server
mumble_cpu_shares: 1024

# autoheal
mumble_autoheal: "false"

# watchtower
mumble_watchtower_monitor_only: "true"