---
# ANE
ansible_nas_app_name: "Mumble"
mumble_enabled: false
mumble_available_externally: false
mumble_traefik_whitelist: "{{ lan }}"

# Directories
mumble_data_directory: "{{ docker_home }}/mumble"

# Networking
mumble_port_tcp: "64738"
mumble_port_udp: "64738"
mumble_hostname: mumble

# Configuration
mumble_server_password: "{{ ansible_nas_app_admin_password }}"

# docker
mumble_container_name: mumble-server
mumble_cpu_shares: 1024
mumble_memory: 1G
mumble_image_name: "mumblevoip/mumble-server"
mumble_image_tag: "latest"

# autoheal
mumble_autoheal: "false"

# dockflare
mumble_dockflare_tunnel: "false"
mumble_dockflare_access_group: ""

# homepage
mumble_homepage_group: "Apps"
mumble_homepage_icon: "mumble.png"
mumble_homepage_href: "http://{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}:{{ mumble_port_tcp }}"
mumble_homepage_showstats: "false"

# repliqate
mumble_repliqate_enabled: "false"
mumble_repliqate_engine: "restic"
mumble_repliqate_schedule: "@daily 3am"
mumble_repliqate_backup_id: "{{ mumble_container_name }}"
mumble_repliqate_retention: "30d"

# watchtower
mumble_watchtower_enable: "false"