---
- name: Start {{ vaultwarden_proper_name }}
  block:
    - name: Check if {{ vaultwarden_hostname }}.{{ ansible_nas_domain }} resolves
      ansible.builtin.shell: dig +short {{ vaultwarden_hostname }}.{{ ansible_nas_domain }}
      register: dns_check
      changed_when: false

    - name: Set DNS status fact
      set_fact:
        dns_exists: "{{ dns_check.stdout | length > 0 }}"

# https://github.com/dani-garcia/vaultwarden#Usage
    - name: Report DNS and Access Status
      ansible.builtin.debug:
        msg: >-
          {{
            "DNS record found!"
            if dns_exists
            else
            "DNS record not found. External access to be configured."
            if (vaultwarden_traefik_enabled | bool or vaultwarden_dockflare_enabled | bool)
            else
            "DNS record not found. External access not configured. Skipping container creation."
          }}

    - name: Continue {{ vaultwarden_proper_name }}
      block:
        - name: Create {{ vaultwarden_proper_name }} Directories
          ansible.builtin.file:
            path: "{{ item }}"
            state: directory
            mode: "0755"
          with_items:
            - "{{ vaultwarden_data_directory }}"
            - "{{ vaultwarden_data_directory }}/data"

        - name: Create {{ vaultwarden_proper_name }} Container
          community.docker.docker_container:
            container_default_behavior: "compatibility"
            name: "{{ vaultwarden_container_name }}"
            hostname: "{{ vaultwarden_container_name }}"
            image: "{{ vaultwarden_image_name }}:{{ vaultwarden_image_tag }}"
            pull: true
            ports:
              - "{{ vaultwarden_port_http }}:80"
              - "{{ vaultwarden_port_websockets }}:3012"
            volumes:
              - "{{ vaultwarden_data_directory }}/data:/data:rw"
            env: >-
              {{
                {
                  'SIGNUPS_ALLOWED': (vaultwarden_env_allow_signups | string),
                  'ADMIN_TOKEN': vaultwarden_env_admin_token,
                  'DOMAIN': vaultwarden_env_domain,
                  'LOG_FILE': '/data/vaultwarden.log',
                  'SMTP_HOST': vaultwarden_env_smtp_host,
                  'SMTP_FROM': vaultwarden_env_smtp_from,
                  'SMTP_FROM_NAME': vaultwarden_env_smtp_from_name,
                  'SMTP_SECURITY': vaultwarden_env_smtp_security,
                  'SMTP_PORT': vaultwarden_env_smtp_port,
                  'SMTP_USERNAME': vaultwarden_env_smtp_username,
                  'SMTP_PASSWORD': vaultwarden_env_smtp_password,
                  'SMTP_TIMEOUT': vaultwarden_env_smtp_timeout,
                  'WEBSOCKET_ENABLED': vaultwarden_websocket_enabled,
                  'TZ': ansible_nas_timezone
                } | dict2items | selectattr('value', 'ne', none) | selectattr('value', 'ne', '') | items2dict
              }}
            healthcheck:
              test: "{{ vaultwarden_healthcheck_test }}"
              interval: "{{ vaultwarden_healthcheck_interval }}"
              timeout: "{{ vaultwarden_healthcheck_timeout }}"
              retries: "{{ vaultwarden_healthcheck_retries }}"
              start_period: "{{ vaultwarden_healthcheck_start_period }}"
            labels:
              autoheal: "{{ vaultwarden_autoheal_enabled | ternary('true', 'false') }}"
              com.centurylinklabs.watchtower.enable: "{{ vaultwarden_watchtower_enabled | ternary('true', 'false') }}"
              dockflare.enable: "{{ vaultwarden_dockflare_enabled | ternary('true', 'false') }}"
              dockflare.access.group: "{{ vaultwarden_dockflare_access_group }}"
              dockflare.hostname: "{{ vaultwarden_hostname }}.{{ ansible_nas_domain }}"
              dockflare.service: "http://{{ hostvars[inventory_hostname]['ansible_facts']['default_ipv4']['address'] }}:{{ vaultwarden_port_http }}"
              homepage.name: "{{ vaultwarden_proper_name }}"
              homepage.group: "{{ vaultwarden_homepage_group }}"
              homepage.icon: "{{ vaultwarden_homepage_icon }}"
              homepage.href: "{{ vaultwarden_homepage_href }}"
              homepage.description: "{{ 'Unofficial Bitwarden compatible server written in Rust' if homepage_show_description else omit }}"
              homepage.siteMonitor: "https://{{ vaultwarden_hostname }}.{{ ansible_nas_domain }}"
              homepage.server: "my-docker"
              homepage.container: "{{ vaultwarden_container_name }}"
              homepage.showStats: "{{ vaultwarden_homepage_showstats | ternary('true', 'false') }}"
              repliqate.enabled: "{{ vaultwarden_repliqate_enabled | ternary('true', 'false') }}"
              repliqate.engine: "{{ vaultwarden_repliqate_engine }}"
              repliqate.schedule: "{{ vaultwarden_repliqate_schedule }}"
              repliqate.backup_id: "{{ vaultwarden_repliqate_backup_id }}"
              repliqate.retention: "{{ vaultwarden_repliqate_retention }}"
              traefik.enable: "{{ vaultwarden_traefik_enabled | ternary('true', 'false') }}"
              traefik.http.routers.vaultwarden.rule: "Host(`{{ vaultwarden_hostname }}.{{ ansible_nas_domain }}`)"
              traefik.http.routers.vaultwarden.tls.certresolver: "letsencrypt"
              traefik.http.routers.vaultwarden.tls.domains[0].main: "{{ ansible_nas_domain }}"
              traefik.http.routers.vaultwarden.tls.domains[0].sans: "*.{{ ansible_nas_domain }}"
              traefik.http.routers.vaultwarden.middlewares: "vaultwarden@docker{{ ',tinyauth-auth@docker' if vaultwarden_tinyauth_enabled | bool else '' }}"
              traefik.http.middlewares.vaultwarden.IPAllowList.sourcerange: "{{ vaultwarden_traefik_whitelist }}"
              traefik.http.services.vaultwarden.loadbalancer.server.port: "80"
              wud.tag.include: '^\\d+\\.\\d+\\.\\d+$'
              wud.tag.transform.type: "semver"
              wud.link.template: "https://github.com/dani-garcia/vaultwarden/pkgs/container/vaultwarden"
            cpu_shares: "{{ vaultwarden_cpu_shares }}"
            memory: "{{ vaultwarden_memory }}"
            memory_swap: "{{ vaultwarden_memory_swap }}"
            restart_policy: unless-stopped

        - name: Access {{ vaultwarden_proper_name }} at
          ansible.builtin.debug:
            msg: >-
                  {{
                    (['https://' + vaultwarden_hostname + '.' + ansible_nas_domain] if (vaultwarden_traefik_enabled is true or vaultwarden_dockflare_enabled is true) else [])
                  }}

        - name: Create {{ vaultwarden_proper_name }} Backup Container Directory
          ansible.builtin.file:
            path: "{{ item }}"
            state: directory
            mode: "0700"
          with_items:
            - "{{ vaultwarden_data_directory }}/backup"

        - name: Create {{ vaultwarden_proper_name }} Backup Container
          community.docker.docker_container:
            container_default_behavior: "compatibility"
            name: "{{ vaultwarden_backup_container_name }}"
            hostname: "{{ vaultwarden_backup_container_name }}"
            image: "{{ vaultwarden_backup_image_name }}:{{ vaultwarden_backup_image_tag }}"
            pull: true
            volumes:
              - "{{ vaultwarden_data_directory }}/data:/data"
              - "{{ vaultwarden_data_directory }}/backup:/backup"
            env:
              DELETE_AFTER: "{{ vaultwarden_backup_env_delete_after }}"
              UID: "{{ vaultwarden_backup_env_uid }}"
              TIMESTAMP: "{{ vaultwarden_backup_env_timestamp }}"
              TZ: "{{ ansible_nas_timezone }}"
            healthcheck:
              test: "{{ vaultwarden_backup_healthcheck_test }}"
              interval: "{{ vaultwarden_backup_healthcheck_interval }}"
              timeout: "{{ vaultwarden_backup_healthcheck_timeout }}"
              retries: "{{ vaultwarden_backup_healthcheck_retries }}"
              start_period: "{{ vaultwarden_backup_healthcheck_start_period }}"
            labels:
              autoheal: "{{ vaultwarden_backup_autoheal_enabled | ternary('true', 'false') }}"
              com.centurylinklabs.watchtower.enable: "{{ vaultwarden_backup_watchtower_enabled | ternary('true', 'false') }}"
              dockflare.enable: "false"
              homepage.name: "{{ vaultwarden_proper_name }} Backup"
              homepage.group: "{{ vaultwarden_backup_homepage_group }}"
              homepage.icon: "{{ vaultwarden_backup_homepage_icon }}"
              homepage.href: "{{ vaultwarden_backup_homepage_href }}"
              homepage.description: "{{ 'A simple cron powered backup image for vaultwarden.' if homepage_show_description else omit }}"
              homepage.server: "my-docker"
              homepage.container: "{{ vaultwarden_backup_container_name }}"
              homepage.showStats: "{{ vaultwarden_backup_homepage_showstats | ternary('true', 'false') }}"
              traefik.enable: "false"
              wud.tag.include: '^\d+\.\d+\.\d+$'
              wud.tag.transform.type: "semver"
              wud.link.template: "https://hub.docker.com/r/bruceforce/vaultwarden-backup"
            cpu_shares: "{{ vaultwarden_backup_cpu_shares }}"
            memory: "{{ vaultwarden_backup_memory }}"
            memory_swap: "{{ vaultwarden_backup_memory_swap }}"
            restart_policy: unless-stopped
      when:
        - dns_exists
        - (vaultwarden_dockflare_enabled | bool or vaultwarden_traefik_enabled | bool)
  when: vaultwarden_enabled is true

- name: Stop {{ vaultwarden_proper_name }}
  block:
    - name: Stop {{ vaultwarden_proper_name }} Container
      community.docker.docker_container:
        name: "{{ vaultwarden_container_name }}"
        state: absent

    - name: Stop {{ vaultwarden_proper_name }} Backup Container
      community.docker.docker_container:
        name: "{{ vaultwarden_backup_container_name }}"
        state: absent
  when: vaultwarden_enabled is false

- name: Data Archive {{ vaultwarden_proper_name }}
  include_role:
    name: ansible-nas-archive
  vars:
    target_data_dir: "{{ vaultwarden_data_directory }}"
  when:
    - archive_app_data_enabled is true
    - vaultwarden_enabled is false