---
# ANE
ansible_nas_app_name: "SABnzbd"
sabnzbd_enabled: false
sabnzbd_available_externally: false
sabnzbd_traefik_whitelist: "{{ lan }}"

# directories
sabnzbd_data_directory: "{{ docker_home }}/sabnzbd"
sabnzbd_downloads_directory: "{{ downloads_root }}"
sabnzbd_incomplete_directory: "{{ downloads_root }}/sabnzbd-incomplete"

# network
sabnzbd_port_http: "18080"
sabnzbd_hostname: "sabnzbd"

# specs
sabnzbd_memory: 1g

# uid / gid
sabnzbd_user_id: "0"
sabnzbd_group_id: "0"

# docker
sabnzbd_container_name: "sabnzbd"
sabnzbd_image_name: "lscr.io/linuxserver/sabnzbd"
sabnzbd_image_version: "latest"
sabnzbd_cpu_shares: 1024

# autoheal
sabnzbd_autoheal: "false"

# dockflare
sabnzbd_dockflare_tunnel: "false"
sabnzbd_dockflare_access_group: ""

# homepage
sabnzbd_homepage_group: "Apps"
sabnzbd_homepage_icon: "sabnzbd.png"
sabnzbd_homepage_href: "http://{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}:{{ sabnzbd_port_http }}"
sabnzbd_homepage_showstats: "false"

# linuxserver.io docker mods
sabnzbd_env_docker_mods: ""
sabnzbd_env_docker_mods_install_packages: ""
sabnzbd_env_docker_mods_install_pip_packages: ""

# theme.park themes
# https://docs.theme-park.dev/themes/sabnzbd/
sabnzbd_env_docker_mods_tp_theme: ""
sabnzbd_env_docker_mods_tp_community_theme: ""
sabnzbd_env_docker_mods_tp_domain: ""
sabnzbd_env_docker_mods_tp_addon: ""

# watchtower
sabnzbd_watchtower_enable: "false"