---
# ANE
ansible_nas_app_name: "Wizarr"
wizarr_enabled: false
wizarr_traefik_enabled: false
wizarr_traefik_whitelist: "{{ lan }}"

# directories
wizarr_data_directory: "{{ docker_home }}/wizarr"

# docker
wizarr_container_name: "wizarr"
wizarr_image_name: "ghcr.io/wizarrrr/wizarr"
wizarr_image_tag: "latest"

# uid / gid
wizarr_user_id: "1000"
wizarr_group_id: "1000"

# network
wizarr_port_http: "5690"
wizarr_hostname: "wizarr"

# specs
wizarr_cpu_shares: 1024
wizarr_memory: "1G"

# app
wizarr_env_disable_builtin_auth: "false"

# autoheal
wizarr_autoheal_enabled: false

# dockflare
wizarr_dockflare_enabled: false
wizarr_dockflare_access_group: ""

# homepage
wizarr_homepage_group: "Apps"
wizarr_homepage_icon: "wizarr.png"
wizarr_homepage_href: "http://{{ hostvars[inventory_hostname]['ansible_facts']['default_ipv4']['address'] }}:{{ wizarr_port_http }}"
wizarr_homepage_showstats: false

# repliqate
wizarr_repliqate_enabled: false
wizarr_repliqate_engine: "restic"
wizarr_repliqate_schedule: "@daily 3am"
wizarr_repliqate_backup_id: "{{ wizarr_container_name }}"
wizarr_repliqate_retention: "30d"

# tinyauth
wizarr_tinyauth_enabled: false

# watchtower
wizarr_watchtower_enabled: false
