- name: Start {{ ansible_nas_app_name }}
  block:
    - name: Create {{ ansible_nas_app_name }} Directories
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        owner: "{{ invoiceninja_user_id }}"
        group: "{{ invoiceninja_group_id }}"
        mode: "755"
      with_items:
        - "{{ invoiceninja_data_directory }}/public"
        - "{{ invoiceninja_data_directory }}/storage"
        - "{{ invoiceninja_data_directory }}/nginx"

    - name: Create {{ ansible_nas_app_name }} DB Directory
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        owner: "999"
        group: "999"
        mode: "755"
      with_items:
        - "{{ invoiceninja_data_directory }}/db"

    - name: Create {{ ansible_nas_app_name }} Network
      community.docker.docker_network:
        name: "{{ invoiceninja_network_name }}"

    - name: Template nginx conf
      template:
        src: in-vhost.conf
        dest: "{{ invoiceninja_data_directory }}/nginx/in-vhost.conf"
      register: template_config

    - name: Create {{ ansible_nas_app_name }} DB Container
      community.docker.docker_container:
        container_default_behavior: "compatibility"
        name: "{{ invoiceninja_db_container_name }}"
        hostname: "{{ invoiceninja_db_container_name }}"
        image: "{{ invoiceninja_db_image_name }}:{{ invoiceninja_db_image_tag }}"
        pull: true
        networks:
          - name: "{{ invoiceninja_network_name }}"
        network_mode: "{{ invoiceninja_network_name }}"
        networks_cli_compatible: "yes"
        volumes:
          - "{{ invoiceninja_data_directory }}/db:/var/lib/mysql"
          - "/etc/localtime:/etc/localtime:ro"
        env:
          PUID: "{{ invoiceninja_db_user_id }}"
          PGID: "{{ invoiceninja_db_group_id }}"
          MYSQL_ROOT_PASSWORD: "{{ invoiceninja_db_mysql_root_password }}"
          MYSQL_DATABASE: "{{ invoiceninja_db_mysql_database }}"
          MYSQL_USER: "{{ invoiceninja_db_mysql_user }}"
          MYSQL_PASSWORD: "{{ invoiceninja_db_mysql_password }}"
          TZ: "{{ ansible_nas_timezone }}"
        healthcheck:
              test:
                - CMD
                - /usr/local/bin/healthcheck.sh
                - --su-mysql
                - --connect
                - --innodb_initialized
              interval: "30s"
              timeout: "10s"
              retries: 3
              start_period: "30s"
        labels:
          autoheal: "{{ invoiceninja_db_autoheal }}"
          com.centurylinklabs.watchtower.enable: "{{ invoiceninja_db_watchtower_enable }}"
          dockflare.enable: "false"
          homepage.name: "{{ ansible_nas_app_name }} MariaDB"
          homepage.group: "{{ invoiceninja_db_homepage_group }}"
          homepage.icon: "{{ invoiceninja_db_homepage_icon }}"
          homepage.href: "{{ invoiceninja_web_homepage_href }}"
          homepage.description: "{{ 'MariaDB Server is a high performing open source relational database, forked from MySQL.' if homepage_show_description else omit }}"
          homepage.server: "my-docker"
          homepage.container: "{{ invoiceninja_db_container_name }}"
          homepage.showStats: "{{ invoiceninja_db_homepage_showstats }}"
          repliqate.enabled: "{{ invoiceninja_db_repliqate_enabled }}"
          repliqate.engine: "{{ invoiceninja_db_repliqate_engine }}"
          repliqate.schedule: "{{ invoiceninja_db_repliqate_schedule }}"
          repliqate.backup_id: "{{ invoiceninja_db_repliqate_backup_id }}"
          repliqate.retention: "{{ invoiceninja_db_repliqate_retention }}"
          traefik.enable: "false"
          wud.tag.include: '^\d+\.\d+\.\d+.*$'
          wud.tag.transform.type: "semver"
          wud.link.template: "https://hub.docker.com/_/mariadb"
        cpu_shares: "{{ invoiceninja_db_cpu_shares }}"
        memory: "{{ invoiceninja_db_memory }}"
        restart_policy: unless-stopped

    - name: Create {{ ansible_nas_app_name }} App Container
      community.docker.docker_container:
        container_default_behavior: "compatibility"
        name: "{{ invoiceninja_app_container_name }}"
        hostname: "{{ invoiceninja_app_container_name }}"
        image: "{{ invoiceninja_app_image_name }}:{{ invoiceninja_app_image_tag }}"
        pull: true
        networks:
          - name: "{{ invoiceninja_network_name }}"
        network_mode: "{{ invoiceninja_network_name }}"
        networks_cli_compatible: "yes"
        volumes:
          - "{{ invoiceninja_data_directory }}/public:/var/www/app/public"
          - "{{ invoiceninja_data_directory }}/storage:/var/www/app/storage"
        env:
          APP_ENV: "production"
          APP_URL: "{{ invoiceninja_app_url }}"
          APP_KEY: "{{ invoiceninja_app_key }}"
          APP_DEBUG: "{{ invoiceninja_app_debug }}"
          APP_NAME: "{{ invoiceninja_app_name }}"
          API_SECRET: "{{ invoiceninja_api_secret }}"
          REQUIRE_HTTPS: "{{ invoiceninja_require_https }}"
          LICENSE_KEY:  "{{ invoiceninja_license_key }}"
          PHANTOMJS_PDF_GENERATION: "{{ invoiceninja_phantomjs_pdf_generation }}"
          PDF_GENERATOR: "{{ invoiceninja_pdf_generator }}"
          TRUSTED_PROXIES: "{{ invoiceninja_trusted_proxies }}"
          IS_DOCKER: "TRUE"
          NINJA_ENVIRONMENT: "selfhost"
          UPDATE_SECRET: "{{ invoiceninja_update_secret }}"
          NORDIGEN_SECRET_ID: "{{ invoiceninja_nordigen_secret_id }}"
          NORDIGEN_SECRET_KEY: "{{ invoiceninja_nordigen_secret_key }}"
          DELETE_BACKUP_DAYS: "{{ invoiceninja_delete_backup_days}}"
          ADDITIONAL_UPLOAD_EXTENSIONS: "{{ invoiceninja_additional_upload_extensions }}"
          DB_HOST: "{{ invoiceninja_db_container_name }}"
          DB_PORT: "3306"
          DB_STRICT: "false"
          DB_TYPE: "mysql"
          DB_DATABASE: "{{ invoiceninja_db_mysql_database }}"
          DB_USERNAME: "{{ invoiceninja_db_mysql_user }}"
          DB_PASSWORD: "{{ invoiceninja_db_mysql_password }}"
          ERROR_EMAIL: "{{ invoiceninja_error_email }}"
          IN_USER_EMAIL: "{{ invoiceninja_in_user_email }}"
          IN_PASSWORD: "{{ invoiceninja_in_password }}"
          MAIL_MAILER: "{{ invoiceninja_mail_mailer }}"
          MAIL_HOST: "{{ invoiceninja_mail_host }}"
          MAIL_PORT: "{{ invoiceninja_mail_port }}"
          MAIL_USERNAME: "{{ invoiceninja_mail_username }}"
          MAIL_PASSWORD: "{{ invoiceninja_mail_password }}"
          MAIL_ENCRYPTION: "{{ invoiceninja_mail_encryption }}"
          MAIL_FROM_ADDRESS: "{{ invoiceninja_mail_from_address }}"
          MAIL_FROM_NAME: "{{ invoiceninja_mail_from_name }}"
          TZ: "{{ ansible_nas_timezone }}"
        links:
          - "{{ invoiceninja_db_container_name }}"
        labels:
          autoheal: "{{ invoiceninja_app_autoheal }}"
          com.centurylinklabs.watchtower.enable: "{{ invoiceninja_app_watchtower_enable }}"
          dockflare.enable: "false"
          homepage.name: "{{ ansible_nas_app_name }} App"
          homepage.group: "{{ invoiceninja_app_homepage_group }}"
          homepage.icon: "{{ invoiceninja_app_homepage_icon }}"
          homepage.href: "{{ invoiceninja_web_homepage_href }}"
          homepage.description: "{{ 'invoice, quote, project and time-tracking app' if homepage_show_description else omit }}"
          homepage.server: "my-docker"
          homepage.container: "{{ invoiceninja_app_container_name }}"
          homepage.showStats: "{{ invoiceninja_app_homepage_showstats }}"
          repliqate.enabled: "{{ invoiceninja_app_repliqate_enabled }}"
          repliqate.engine: "{{ invoiceninja_app_repliqate_engine }}"
          repliqate.schedule: "{{ invoiceninja_app_repliqate_schedule }}"
          repliqate.backup_id: "{{ invoiceninja_app_repliqate_backup_id }}"
          repliqate.retention: "{{ invoiceninja_app_repliqate_retention }}"
          traefik.enable: "false"
          wud.tag.include: ^5\.\d+\.\d+$
          wud.link.template: https://github.com/invoiceninja/invoiceninja/releases/tag/v${major}.${minor}.${patch}
        cpu_shares: "{{ invoiceninja_app_cpu_shares }}"
        memory: "{{ invoiceninja_app_memory }}"
        restart_policy: unless-stopped

    - name: Create {{ ansible_nas_app_name }} Web UI Container
      community.docker.docker_container:
        container_default_behavior: "compatibility"
        name: "{{ invoiceninja_web_container_name }}"
        hostname: "{{ invoiceninja_web_container_name }}"
        image: "{{ invoiceninja_web_image_name }}:{{ invoiceninja_web_image_tag }}"
        pull: true
        networks:
          - name: "{{ invoiceninja_network_name }}"
        network_mode: "{{ invoiceninja_network_name }}"
        networks_cli_compatible: "yes"
        ports:
          - "{{ invoiceninja_port_http }}:80"
        volumes:
          - "{{ invoiceninja_data_directory }}/nginx/in-vhost.conf:/etc/nginx/conf.d/in-vhost.conf:ro"
          - "{{ invoiceninja_data_directory }}/public:/var/www/app/public:ro"
        env:
          TZ: "{{ ansible_nas_timezone }}"
        links:
          - "{{ invoiceninja_app_container_name }}"
          - "{{ invoiceninja_db_container_name }}"
        labels:
          autoheal: "{{ invoiceninja_web_autoheal }}"
          com.centurylinklabs.watchtower.enable: "{{ invoiceninja_web_watchtower_enable }}"
          dockflare.enable: "{{ invoiceninja_dockflare_tunnel }}"
          dockflare.access.group: "{{ invoiceninja_dockflare_access_group }}"
          dockflare.hostname: "{{ invoiceninja_hostname }}.{{ ansible_nas_domain }}"
          dockflare.service: "http://{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}:{{ invoiceninja_port_http }}"
          homepage.name: "{{ ansible_nas_app_name }}"
          homepage.group: "{{ invoiceninja_web_homepage_group }}"
          homepage.icon: "invoiceninja.png"
          homepage.href: "{{ invoiceninja_web_homepage_href }}"
          homepage.siteMonitor: "{{ invoiceninja_web_homepage_sitemonitor }}"
          homepage.description: "{{ 'the world''s most popular Web Server' if homepage_show_description else omit }}"
          homepage.server: "my-docker"
          homepage.container: "{{ invoiceninja_web_container_name }}"
          homepage.showStats: "{{ invoiceninja_web_homepage_showstats }}"
          repliqate.enabled: "{{ invoiceninja_web_repliqate_enabled }}"
          repliqate.engine: "{{ invoiceninja_web_repliqate_engine }}"
          repliqate.schedule: "{{ invoiceninja_web_repliqate_schedule }}"
          repliqate.backup_id: "{{ invoiceninja_web_repliqate_backup_id }}"
          repliqate.retention: "{{ invoiceninja_web_repliqate_retention }}"
          traefik.enable: "{{ invoiceninja_available_externally | string }}"
          traefik.http.routers.invoiceninja.rule: "Host(`invoiceninja.{{ ansible_nas_domain }}`)"
          traefik.http.routers.invoiceninja.tls.certresolver: "letsencrypt"
          traefik.http.routers.invoiceninja.tls.domains[0].main: "{{ ansible_nas_domain }}"
          traefik.http.routers.invoiceninja.tls.domains[0].sans: "*.{{ ansible_nas_domain }}"
          traefik.http.routers.frontend.middlewares: "{{ invoiceninja_hostname }}"
          traefik.http.routers.invoiceninja.middlewares: "{{ invoiceninja_hostname }}@docker"
          traefik.http.middlewares.invoiceninja.IPAllowList.sourcerange: "{{ invoiceninja_traefik_whitelist }}"
          traefik.http.services.invoiceninja.loadbalancer.server.port: "80"
          wud.tag.include: '^\d+\.\d+\.\d+$'
          wud.tag.transform.type: "semver"
          wud.link.template: "https://hub.docker.com/_/nginx"
        cpu_shares: "{{ invoiceninja_web_cpu_shares }}"
        memory: "{{ invoiceninja_web_memory }}"
        restart_policy: unless-stopped

    - name: Access {{ ansible_nas_app_name }} at
      ansible.builtin.debug:
        msg: >-
              {{
                ['http://' + hostvars[inventory_hostname]['ansible_default_ipv4']['address'] + ':' + (invoiceninja_port_http | string)] +
                (['https://' + invoiceninja_hostname + '.' + ansible_nas_domain] if (invoiceninja_available_externally is true or invoiceninja_dockflare_tunnel is true) else [])
              }}
  when: invoiceninja_enabled is true

- name: Stop {{ ansible_nas_app_name }}
  block:
    - name: Stop {{ ansible_nas_app_name }} Web UI Container
      community.docker.docker_container:
        name: "{{ invoiceninja_web_container_name }}"
        state: absent

    - name: Stop {{ ansible_nas_app_name }} App Container
      community.docker.docker_container:
        name: "{{ invoiceninja_app_container_name }}"
        state: absent

    - name: Stop {{ ansible_nas_app_name }} DB Container
      community.docker.docker_container:
        name: "{{ invoiceninja_db_container_name }}"
        state: absent

    - name: Delete {{ ansible_nas_app_name }} Network
      community.docker.docker_network:
        name: "{{ invoiceninja_network_name }}"
        state: absent
  when: invoiceninja_enabled is false

- name: Data Archive {{ ansible_nas_app_name }}
  block:
    - name: Check for {{ ansible_nas_app_name }} Data Directory
      stat:
        path: "{{ invoiceninja_data_directory }}"
      register: dir_stat

    - name: Archive {{ ansible_nas_app_name }} Data Directory
      ansible.builtin.archive:
        path: "{{ invoiceninja_data_directory }}"
        dest: "{{ docker_home }}/{{ ansible_nas_app_name | lower }}.zip"
        force_archive: true
        format: zip
        owner: ansible-nas
        group: ansible-nas
        mode: u=rw,g=rw
        remove: true
      when: dir_stat.stat.exists
  when: invoiceninja_enabled is false and archive_app_data_enabled is true
