---
- name: Start {{ ansible_nas_app_name }}
  block:
    - name: Create {{ ansible_nas_app_name }} Directories
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
      with_items:
        - "{{ nzbget_data_directory }}"

    - name: Set {{ ansible_nas_app_name }} FQDN var overrides
      ansible.builtin.set_fact:
        nzbget_homepage_href: "https://{{ nzbget_hostname }}.{{ ansible_nas_domain }}"
      when: nzbget_traefik_enabled | bool or nzbget_dockflare_enabled | bool

    - name: Create {{ ansible_nas_app_name }} Container
      community.docker.docker_container:
        container_default_behavior: "compatibility"
        name: "{{ nzbget_container_name }}"
        hostname: "{{ nzbget_container_name }}"
        image: "{{ nzbget_image_name }}:{{ nzbget_image_version }}"
        pull: true
        volumes:
          - "{{ nzbget_download_directory }}:/downloads:rw"
          - "{{ nzbget_data_directory }}:/config:rw"
        ports:
          - "{{ nzbget_port_http }}:6789"
        env:
          DOCKER_MODS: "{{ nzbget_env_docker_mods }}"
          INSTALL_PACKAGES: "{{ nzbget_env_docker_mods_install_packages }}"
          INSTALL_PIP_PACKAGES: "{{ nzbget_env_docker_mods_install_pip_packages}}"
          TP_DOMAIN: "{{ nzbget_env_docker_mods_tp_domain }}"
          TP_THEME: "{{ nzbget_env_docker_mods_tp_theme }}"
          TP_COMMUNITY_THEME: "{{ nzbget_env_docker_mods_tp_community_theme }}"
          TP_ADDON: "{{ nzbget_env_docker_mods_tp_addon }}"
          PUID: "{{ nzbget_user_id }}"
          PGID: "{{ nzbget_group_id }}"
          TZ: "{{ ansible_nas_timezone }}"
        labels:
          autoheal: "{{ nzbget_autoheal_enabled | ternary('true', 'false') }}"
          com.centurylinklabs.watchtower.enable: "{{ nzbget_watchtower_enabled | ternary('true', 'false') }}"
          dockflare.enable: "{{ nzbget_dockflare_enabled | ternary('true', 'false') }}"
          dockflare.access.group: "{{ nzbget_dockflare_access_group }}"
          dockflare.hostname: "{{ nzbget_hostname }}.{{ ansible_nas_domain }}"
          dockflare.service: "http://{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}:{{ nzbget_port_http }}"
          homepage.name: "{{ ansible_nas_app_name }}"
          homepage.group: "{{ nzbget_homepage_group }}"
          homepage.icon: "{{ nzbget_homepage_icon }}"
          homepage.href: "{{ nzbget_homepage_href }}"
          homepage.description: "{{ 'nzbget description' if homepage_show_description else omit }}"
          homepage.server: "my-docker"
          homepage.container: "{{ nzbget_container_name }}"
          homepage.showStats: "{{ nzbget_homepage_showstats | ternary('true', 'false') }}"
          homepage.siteMonitor: "http://{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}:{{ nzbget_port_http }}"
          homepage.widget.type: "nzbget"
          homepage.widget.url: "http://{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}:{{ nzbget_port_http }}"
          homepage.widget.username: "{{ nzbget_homepage_widget_username }}"
          homepage.widget.password: "{{ nzbget_homepage_widget_password }}"
          repliqate.enabled: "{{ nzbget_repliqate_enabled | ternary('true', 'false') }}"
          repliqate.engine: "{{ nzbget_repliqate_engine }}"
          repliqate.schedule: "{{ nzbget_repliqate_schedule }}"
          repliqate.backup_id: "{{ nzbget_repliqate_backup_id }}"
          repliqate.retention: "{{ nzbget_repliqate_retention }}"
          traefik.enable: "{{ nzbget_traefik_enabled | ternary('true', 'false') }}"
          traefik.http.routers.nzbget.rule: "Host(`{{ nzbget_hostname }}.{{ ansible_nas_domain }}`)"
          traefik.http.routers.nzbget.tls.certresolver: "letsencrypt"
          traefik.http.routers.nzbget.tls.domains[0].main: "{{ ansible_nas_domain }}"
          traefik.http.routers.nzbget.tls.domains[0].sans: "*.{{ ansible_nas_domain }}"
          traefik.http.routers.nzbget.middlewares: "nzbget@docker{{ ',tinyauth-auth@docker' if nzbget_tinyauth_enabled | bool else '' }}"
          traefik.http.middlewares.nzbget.IPAllowList.sourcerange: "{{ nzbget_traefik_whitelist }}"
          traefik.http.services.nzbget.loadbalancer.server.port: "6789"
          wud.tag.include: '^\d+\.\d+\.\d+.*$'
          wud.tag.transform.type: "semver"
          wud.link.template: "https://lscr.io/linuxserver/nzbget"
        cpu_shares: "{{ nzbget_cpu_shares }}"
        memory: "{{ nzbget_memory }}"
        memory_swap: "{{ nzbget_memory_swap }}"
        restart_policy: unless-stopped

    - name: Access {{ ansible_nas_app_name }} at
      ansible.builtin.debug:
        msg: >-
              {{
                ['http://' + hostvars[inventory_hostname]['ansible_default_ipv4']['address'] + ':' + (nzbget_port_http | string)] +
                (['https://' + nzbget_hostname + '.' + ansible_nas_domain] if (nzbget_traefik_enabled is true or nzbget_dockflare_enabled is true) else [])
              }}
  when: nzbget_enabled is true

- name: Stop {{ ansible_nas_app_name }}
  block:
    - name: Stop {{ ansible_nas_app_name }} Container
      community.docker.docker_container:
        name: "{{ nzbget_container_name }}"
        state: absent
  when: nzbget_enabled is false

- name: Data Archive {{ ansible_nas_app_name }}
  include_role:
    name: ansible-nas-archive
  vars:
    target_data_dir: "{{ nzbget_data_directory }}"
  when:
    - archive_app_data_enabled is true
    - nzbget_enabled is false