---
- name: Start {{ ansible_nas_app_name }}
  block:
    - name: Create {{ ansible_nas_app_name }} Directories
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
      with_items:
        - "{{ nzbget_data_directory }}"

    - name: Create {{ ansible_nas_app_name }} Container
      community.docker.docker_container:
        container_default_behavior: "compatibility"
        name: "{{ nzbget_container_name }}"
        hostname: "{{ nzbget_container_name }}"
        image: "{{ nzbget_image_name }}:{{ nzbget_image_version }}"
        pull: true
        volumes:
          - "{{ nzbget_download_directory }}:/downloads:rw"
          - "{{ nzbget_data_directory }}:/config:rw"
        ports:
          - "{{ nzbget_port }}:6789"
        env:
          DOCKER_MODS: "{{ nzbget_env_docker_mods }}"
          INSTALL_PACKAGES: "{{ nzbget_env_docker_mods_install_packages }}"
          INSTALL_PIP_PACKAGES: "{{ nzbget_env_docker_mods_install_pip_packages}}"
          TP_DOMAIN: "{{ nzbget_env_docker_mods_tp_domain }}"
          TP_THEME: "{{ nzbget_env_docker_mods_tp_theme }}"
          TP_COMMUNITY_THEME: "{{ nzbget_env_docker_mods_tp_community_theme }}"
          TP_ADDON: "{{ nzbget_env_docker_mods_tp_addon }}"
          PUID: "{{ nzbget_user_id }}"
          PGID: "{{ nzbget_group_id }}"
          TZ: "{{ ansible_nas_timezone }}"
        labels:
          autoheal: "{{ nzbget_autoheal }}"
          com.centurylinklabs.watchtower.enable: "{{ nzbget_watchtower_enable }}"
          dockflare.enable: "{{ nzbget_dockflare_tunnel }}"
          dockflare.access.group: "{{ nzbget_dockflare_access_group }}"
          dockflare.hostname: "{{ nzbget_hostname }}.{{ ansible_nas_domain }}"
          dockflare.service: "http://{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}:{{ nzbget_port }}"
          homepage.name: "{{ ansible_nas_app_name }}"
          homepage.group: "{{ nzbget_homepage_group }}"
          homepage.icon: "{{ nzbget_homepage_icon }}"
          homepage.href: "{{ nzbget_homepage_href }}"
          homepage.description: "{{ 'nzbget description' if homepage_show_description else omit }}"
          homepage.server: "my-docker"
          homepage.container: "{{ nzbget_container_name }}"
          homepage.showStats: "{{ nzbget_homepage_showstats }}"
          homepage.siteMonitor: "http://{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}:{{ nzbget_port }}"
          traefik.enable: "{{ nzbget_available_externally | string }}"
          traefik.http.routers.nzbget.rule: "Host(`{{ nzbget_hostname }}.{{ ansible_nas_domain }}`)"
          traefik.http.routers.nzbget.tls.certresolver: "letsencrypt"
          traefik.http.routers.nzbget.tls.domains[0].main: "{{ ansible_nas_domain }}"
          traefik.http.routers.nzbget.tls.domains[0].sans: "*.{{ ansible_nas_domain }}"
          traefik.http.routers.frontend.middlewares: "{{ nzbget_hostname }}"
          traefik.http.routers.nzbget.middlewares: "{{ nzbget_hostname }}@docker"
          traefik.http.middlewares.nzbget.IPAllowList.sourcerange: "{{ nzbget_traefik_whitelist }}"
          traefik.http.services.nzbget.loadbalancer.server.port: "6789"
          wud.tag.include: '^\d+\.\d+\.\d+.*$'
          wud.tag.transform.type: "semver"
          wud.link.template: "https://lscr.io/linuxserver/nzbget"
        cpu_shares: "{{ nzbget_cpu_shares }}"
        memory: "{{ nzbget_memory }}"
        restart_policy: unless-stopped

    - name: Access {{ ansible_nas_app_name }} at
      ansible.builtin.debug:
        msg: >-
              {{
                ['http://' + hostvars[inventory_hostname]['ansible_default_ipv4']['address'] + ':' + (nzbget_port | string)] +
                (['https://' + nzbget_hostname + '.' + ansible_nas_domain] if (nzbget_available_externally is true or nzbget_dockflare_tunnel is true) else [])
              }}
  when: nzbget_enabled is true

- name: Stop {{ ansible_nas_app_name }}
  block:
    - name: Stop {{ ansible_nas_app_name }} Container
      community.docker.docker_container:
        name: "{{ nzbget_container_name }}"
        state: absent
  when: nzbget_enabled is false

- name: Data Archive {{ ansible_nas_app_name }}
  block:
    - name: Check for {{ ansible_nas_app_name }} Data Directory
      stat:
        path: "{{ nzbget_data_directory }}"
      register: dir_stat

    - name: Archive {{ ansible_nas_app_name }} Data Directory
      ansible.builtin.archive:
        path: "{{ nzbget_data_directory }}"
        dest: "{{ docker_home }}/{{ ansible_nas_app_name | lower }}.zip"
        force_archive: true
        format: zip
        owner: ansible-nas
        group: ansible-nas
        mode: u=rw,g=rw
        remove: true
      when: dir_stat.stat.exists
  when: nzbget_enabled is false and archive_app_data_enabled is true
