---
# ANE
ansible_nas_app_name: "MakeMKV"
makemkv_enabled: false
makemkv_available_externally: false
makemkv_traefik_whitelist: "{{ lan }}"


makemkv_data_directory: "{{ docker_home }}/makemkv"
makemkv_storage_directory: "{{ samba_shares_root }}/dump/rip"
makemkv_output_directory: "{{ samba_shares_root }}/dump/ripped"

makemkv_hostname: "makemkv"
makemkv_port_http: "5804"

makemkv_user_id: "0"
makemkv_group_id: "1001"

# docker
makemkv_container_name: "makemkv"
makemkv_image_name: "ghcr.io/jlesage/makemkv"
makemkv_image_tag: "latest"

# specs
makemkv_cpu_shares: 1024
makemkv_memory: "1G"

# autoheal
makemkv_autoheal: "false"

# dockflare
makemkv_dockflare_tunnel: "false"
makemkv_dockflare_access_group: ""

# homepage
makemkv_homepage_group: "Apps"
makemkv_homepage_icon: "makemkv.png"
makemkv_homepage_href: "http://{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}:{{ makemkv_port_http }}"
makemkv_homepage_showstats: "false"

# repliqate
makemkv_repliqate_enabled: "false"
makemkv_repliqate_engine: "restic"
makemkv_repliqate_schedule: "@daily 3am"
makemkv_repliqate_backup_id: "{{ makemkv_container_name }}"
makemkv_repliqate_retention: "30d"

# tinyauth
makemkv_tinyauth_enabled: false

# watchtower
makemkv_watchtower_enable: "false"