---
ansible_nas_app_name: "MakeMKV"

#
makemkv_enabled: false
makemkv_available_externally: false
makemkv_traefik_whitelist: "{{ lan }}"

makemkv_hostname: "makemkv"
makemkv_data_directory: "{{ docker_home }}/makemkv"
makemkv_optical_drive: "/dev/sr0"
makemkv_storage_directory: "{{ samba_shares_root }}/dump/rip"
makemkv_output_directory: "{{ samba_shares_root }}/dump/ripped"
makemkv_port_http: "5804"
makemkv_user_id: "0"
makemkv_group_id: "1001"

# docker
makemkv_container_name: "makemkv"
makemkv_image_name: "jlesage/makemkv"
makemkv_image_tag: "latest"
makemkv_cpu_shares: "1024"
makemkv_memory: "1g"

# autoheal
makemkv_autoheal: "false"

# dockflare
makemkv_dockflare_tunnel: "false"
makemkv_dockflare_access_group: ""

# homepage
makemkv_homepage_group: "Apps"
makemkv_homepage_icon: "makemkv.png"
makemkv_homepage_href: "http://{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}:{{ makemkv_port_http }}"
makemkv_homepage_showStats: "false"

# watchtower
makemkv_watchtower_monitor_only: "true"