---
- name: Start {{ ansible_nas_app_name }}
  block:
    - name: Create {{ ansible_nas_app_name }} Directories
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
      with_items:
        - "{{ sonarr_data_directory }}"

    - name: Create {{ ansible_nas_app_name }} Container
      community.docker.docker_container:
        name: "{{ sonarr_container_name }}"
        hostname: "{{ sonarr_container_name }}"
        image: "{{ sonarr_image_name }}:{{ sonarr_image_version }}"
        pull: true
        volumes:
          - "{{ sonarr_tv_directory }}:/tv:rw"
          - "{{ sonarr_anime_directory }}:/anime:rw"
          - "{{ sonarr_download_directory }}:/downloads:rw"
          - "{{ sonarr_data_directory }}:/config:rw"
        ports:
          - "{{ sonarr_port }}:8989"
        env:
          TZ: "{{ ansible_nas_timezone }}"
          PUID: "{{ sonarr_user_id }}"
          PGID: "{{ sonarr_group_id }}"
#         DOCKER_MODS: "linuxserver/mods:radarr-striptracks"     # added
#         DOCKER_MODS: "ghcr.io/themepark-dev/theme.park:sonarr"
        restart_policy: unless-stopped
        cpu_shares: "{{ sonarr_cpu_shares }}"
        memory: "{{ sonarr_memory }}"
        labels:
          autoheal: "{{ sonarr_autoheal }}"
          com.centurylinklabs.watchtower.monitor-only: "{{ sonarr_watchtower_monitor_only }}"
          homepage.name: "Sonarr"
          homepage.group: "{{ sonarr_homepage_group }}"
          homepage.icon: "{{ sonarr_homepage_icon }}"
          homepage.href: "{{ sonarr_homepage_href}}"
          homepage.siteMonitor: "http://{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}:{{ sonarr_port }}"
#         homepage.description: "a PVR for usenet and bittorrent users"
          homepage.server: "my-docker"
          homepage.container: "{{ sonarr_container_name }}"
          homepage.showStats: "{{ sonarr_homepage_showStats }}"
          homepage.widget.type: "sonarr"
          homepage.widget.url: "http://{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}:{{ sonarr_port }}"
          homepage.widget.key: "{{ sonarr_homepage_widget_key }}"
          traefik.enable: "{{ sonarr_available_externally | string }}"
          traefik.http.routers.sonarr.rule: "Host(`{{ sonarr_hostname }}.{{ ansible_nas_domain }}`)"
          traefik.http.routers.sonarr.tls.certresolver: "letsencrypt"
          traefik.http.routers.sonarr.tls.domains[0].main: "{{ ansible_nas_domain }}"
          traefik.http.routers.sonarr.tls.domains[0].sans: "*.{{ ansible_nas_domain }}"
          traefik.http.routers.frontend.middlewares: "{{ sonarr_hostname }}"
          traefik.http.routers.sonarr.middlewares: "{{ sonarr_hostname }}@docker"
          traefik.http.middlewares.sonarr.IPAllowList.sourcerange: "{{ sonarr_traefik_whitelist }}"
          traefik.http.services.sonarr.loadbalancer.server.port: "8989"
          wud.tag.include: '^\d+\.\d+\.\d+$$'
          wud.link.template: "https://github.com/linuxserver/docker-sonarr/releases/tag/$${major}.$${minor}.$${patch}"
  when: sonarr_enabled is true

- name: Stop {{ ansible_nas_app_name }}
  block:
    - name: Stop {{ ansible_nas_app_name }} Container
      community.docker.docker_container:
        name: "{{ sonarr_container_name }}"
        state: absent
  when: sonarr_enabled is false

- name: Data Archive {{ ansible_nas_app_name }}
  block:
    - name: Check for {{ ansible_nas_app_name }} Data Directory
      stat:
        path: "{{ sonarr_data_directory }}"
      register: dir_stat

    - name: Archive {{ ansible_nas_app_name }} Data Directory
      ansible.builtin.archive:
        path: "{{ sonarr_data_directory }}"
        dest: "{{ docker_home }}/{{ ansible_nas_app_name | lower }}.zip"
        force_archive: true
        format: zip
        owner: ansible-nas
        group: ansible-nas
        mode: u=rw,g=rw
        remove: true
      when: dir_stat.stat.exists
  when: sonarr_enabled is false and archive_app_data_enabled is true
