---
- name: Start {{ ansible_nas_app_name }}
  block:
    - name: Create {{ ansible_nas_app_name }} Directories
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
      with_items:
        - "{{ sonarr_data_directory }}"
        - "{{ sonarr_data_directory }}/config"

    - name: Create {{ ansible_nas_app_name }} Container
      community.docker.docker_container:
        container_default_behavior: "compatibility"
        name: "{{ sonarr_container_name }}"
        hostname: "{{ sonarr_container_name }}"
        image: "{{ sonarr_image_name }}:{{ sonarr_image_version }}"
        pull: true
        volumes:
          - "{{ sonarr_data_directory }}/config:/config:rw"
          - "{{ sonarr_download_directory }}:/downloads:rw"
          - "{{ sonarr_anime_directory }}:/anime:rw"
          - "{{ sonarr_tv_directory }}:/tv:rw"
        ports:
          - "{{ sonarr_port_http }}:8989"
        env:
          DOCKER_MODS: "{{ sonarr_env_docker_mods }}"
          INSTALL_PACKAGES: "{{ sonarr_env_docker_mods_install_packages }}"
          INSTALL_PIP_PACKAGES: "{{ sonarr_env_docker_mods_install_pip_packages}}"
          TP_DOMAIN: "{{ sonarr_env_docker_mods_tp_domain }}"
          TP_THEME: "{{ sonarr_env_docker_mods_tp_theme }}"
          TP_COMMUNITY_THEME: "{{ sonarr_env_docker_mods_tp_community_theme }}"
          TP_ADDON: "{{ sonarr_env_docker_mods_tp_addon }}"
          PUID: "{{ sonarr_user_id }}"
          PGID: "{{ sonarr_group_id }}"
          TZ: "{{ ansible_nas_timezone }}"
        labels:
          autoheal: "{{ sonarr_autoheal }}"
          com.centurylinklabs.watchtower.enable: "{{ sonarr_watchtower_enable }}"
          dockflare.enable: "{{ sonarr_dockflare_tunnel }}"
          dockflare.access.group: "{{ sonarr_dockflare_access_group }}"
          dockflare.hostname: "{{ sonarr_hostname }}.{{ ansible_nas_domain }}"
          dockflare.service: "http://{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}:{{ sonarr_port_http }}"
          homepage.name: "{{ ansible_nas_app_name }}"
          homepage.group: "{{ sonarr_homepage_group }}"
          homepage.icon: "{{ sonarr_homepage_icon }}"
          homepage.href: "{{ sonarr_homepage_href}}"
          homepage.siteMonitor: "http://{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}:{{ sonarr_port_http }}"
          homepage.description: "{{ 'a PVR for usenet and bittorrent users' if homepage_show_description else omit }}"
          homepage.server: "my-docker"
          homepage.container: "{{ sonarr_container_name }}"
          homepage.showStats: "{{ sonarr_homepage_showstats }}"
          homepage.widget.type: "sonarr"
          homepage.widget.url: "http://{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}:{{ sonarr_port_http }}"
          homepage.widget.key: "{{ sonarr_homepage_widget_key }}"
          repliqate.enabled: "{{ sonarr_repliqate_enabled }}"
          repliqate.engine: "{{ sonarr_repliqate_engine }}"
          repliqate.schedule: "{{ sonarr_repliqate_schedule }}"
          repliqate.backup_id: "{{ sonarr_repliqate_backup_id }}"
          repliqate.retention: "{{ sonarr_repliqate_retention }}"
          traefik.enable: "{{ sonarr_available_externally | string }}"
          traefik.http.routers.sonarr.rule: "Host(`{{ sonarr_hostname }}.{{ ansible_nas_domain }}`)"
          traefik.http.routers.sonarr.tls.certresolver: "letsencrypt"
          traefik.http.routers.sonarr.tls.domains[0].main: "{{ ansible_nas_domain }}"
          traefik.http.routers.sonarr.tls.domains[0].sans: "*.{{ ansible_nas_domain }}"
          traefik.http.routers.sonarr.middlewares: "{{ sonarr_hostname }}@docker{{ ',tinyauth-auth@docker' if sonarr_tinyauth_enabled | bool else '' }}"
          traefik.http.middlewares.sonarr.IPAllowList.sourcerange: "{{ sonarr_traefik_whitelist }}"
          traefik.http.services.sonarr.loadbalancer.server.port: "8989"
          wud.tag.include: '^\d+\.\d+\.\d+.*$'
          wud.tag.transform.type: "semver"
          wud.link.template: "https://lscr.io/linuxserver/sonarr"
        cpu_shares: "{{ sonarr_cpu_shares }}"
        memory: "{{ sonarr_memory }}"
        restart_policy: unless-stopped

    - name: Access {{ ansible_nas_app_name }} at
      ansible.builtin.debug:
        msg: >-
              {{
                ['http://' + hostvars[inventory_hostname]['ansible_default_ipv4']['address'] + ':' + (sonarr_port_http | string)] +
                (['https://' + sonarr_hostname + '.' + ansible_nas_domain] if (sonarr_available_externally is true or sonarr_dockflare_tunnel is true) else [])
              }}
  when: sonarr_enabled is true

- name: Stop {{ ansible_nas_app_name }}
  block:
    - name: Stop {{ ansible_nas_app_name }} Container
      community.docker.docker_container:
        name: "{{ sonarr_container_name }}"
        state: absent
  when: sonarr_enabled is false

- name: Data Archive {{ ansible_nas_app_name }}
  include_role:
    name: ansible-nas-archive
  vars:
    target_data_dir: "{{ sonarr_data_directory }}"
  when:
    - archive_app_data_enabled is true
    - sonarr_enabled is false