---
# ANE
ansible_nas_app_name: "MIND"
mind_enabled: false
mind_available_externally: false
mind_traefik_whitelist: "{{ lan }}"

mind_data_directory: "{{ docker_home }}/mind"

# network
mind_port_http: "3023"
mind_hostname: "mind"

# docker
mind_container_name: "mind"
mind_image_name: "mrcas/mind"
mind_image_tag: "latest"

# specs
mind_cpu_shares: 1024
mind_memory: "1G"

# autoheal
mind_autoheal: "false"

# dockflare
mind_dockflare_tunnel: "false"
mind_dockflare_access_group: ""

# homepage
mind_homepage_group: "Apps"
# mind_homepage_icon: "http://{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}:{{ mind_port_http }}/static/img/favicon.svg"
mind_homepage_icon: "https://raw.githubusercontent.com/Casvt/MIND/refs/heads/Main/frontend/static/img/favicon.svg"
mind_homepage_href: "http://{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}:{{ mind_port_http }}"
mind_homepage_showstats: "false"

# repliqate
mind_repliqate_enabled: "false"
mind_repliqate_engine: "restic"
mind_repliqate_schedule: "@daily 3am"
mind_repliqate_backup_id: "{{ mind_container_name }}"
mind_repliqate_retention: "30d"

# watchtower
mind_watchtower_enable: "false"
