---
# ANE
ansible_nas_app_name: "uTorrent"
utorrent_enabled: false
utorrent_traefik_enabled: false
utorrent_traefik_whitelist: "{{ lan }}"

# directories
utorrent_data_directory: "{{ docker_home }}/utorrent"
utorrent_download_directory: "{{ downloads_root }}"
utorrent_download_directory_active: "{{ downloads_root }}/.incomplete"
utorrent_torrents_directory: "{{ torrents_root }}"

# uid / gid
utorrent_user_id: "0"
utorrent_group_id: "0"

# network
utorrent_port_http: "8111"
utorrent_port_bt: "6881"
utorrent_hostname: "utorrent"

# docker
utorrent_container_name: "utorrent"
utorrent_image_name: "ekho/utorrent"
utorrent_image_version: "latest"

# specs
utorrent_cpu_shares: 1024
utorrent_memory: "1G"

# autoheal
utorrent_autoheal_enabled: false

# dockflare
utorrent_dockflare_enabled: false
utorrent_dockflare_access_group: ""

# homepage
utorrent_homepage_group: "Download Tools"
utorrent_homepage_icon: "sh-utorrent.png"
utorrent_homepage_href: "http://{{ hostvars[inventory_hostname]['ansible_facts']['default_ipv4']['address'] }}:{{ utorrent_port_http }}/gui/"
utorrent_homepage_showstats: false

# repliqate
utorrent_repliqate_enabled: false
utorrent_repliqate_engine: "restic"
utorrent_repliqate_schedule: "@daily 3am"
utorrent_repliqate_backup_id: "{{ utorrent_container_name }}"
utorrent_repliqate_retention: "30d"

# tinyauth
utorrent_tinyauth_enabled: false

# watchtower
utorrent_watchtower_enabled: false