---
# ANE
ansible_nas_app_name: "acmenator"
acmenator_enabled: false
acmenator_data_directory: "{{ docker_home }}/acmenator"

acmenator_traefik_directory: "{{ docker_home }}/traefik/letsencrypt"

# docker
acmenator_container_name: "acmenator"
acmenator_image_name: "ummecasino/acmenator"
acmenator_image_tag: "latest"
acmenator_cpu_shares: "1024"
acmenator_memory: "256m"

# autoheal
acmenator_autoheal: "false"

# homepage
acmenator_homepage_group: "Apps"
acmenator_homepage_icon: "https://upload.wikimedia.org/wikipedia/commons/7/7c/ACME%E2%80%93protocol-icon.png"
acmenator_homepage_showstats: "false"

# repliqate
acmenator_repliqate_enabled: "false"
acmenator_repliqate_engine: "restic"
acmenator_repliqate_schedule: "@daily 3am"
acmenator_repliqate_backup_id: "{{ acmenator_container_name }}"
acmenator_repliqate_retention: "30d"

# watchtower
acmenator_watchtower_enable: "false"