---
# ANE
acmenator_proper_name: "acmenator"
acmenator_enabled: false
acmenator_data_directory: "{{ docker_home }}/acmenator"

acmenator_traefik_directory: "{{ docker_home }}/traefik/letsencrypt"

# docker
acmenator_container_name: "acmenator"
acmenator_image_name: "ummecasino/acmenator"
acmenator_image_tag: "latest"
acmenator_cpu_shares: 1024
acmenator_memory: "128M"
acmenator_memory_swap: -1

# autoheal
acmenator_autoheal_enabled: false

# healthcheck
acmenator_healthcheck_interval: 60s
acmenator_healthcheck_timeout: 10s
acmenator_healthcheck_retries: 3
acmenator_healthcheck_start_period: 10s

# homepage
acmenator_homepage_group: "Misc"
acmenator_homepage_icon: "https://upload.wikimedia.org/wikipedia/commons/7/7c/ACME%E2%80%93protocol-icon.png"
acmenator_homepage_showstats: false

# repliqate
acmenator_repliqate_enabled: false
acmenator_repliqate_engine: "restic"
acmenator_repliqate_schedule: "@daily 3am"
acmenator_repliqate_backup_id: "{{ acmenator_container_name }}"
acmenator_repliqate_retention: "30d"

# watchtower
acmenator_watchtower_enabled: false