---
- name: Start {{ emby_proper_name }}
  block:
    - name: Create {{ emby_proper_name }} Directories
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
      with_items:
        - "{{ emby_data_directory }}"
        - "{{ emby_data_directory }}/config"

    - name: Set {{ emby_proper_name }} FQDN var overrides
      ansible.builtin.set_fact:
        emby_homepage_href: "https://{{ emby_hostname }}.{{ ansible_nas_domain }}"
      when: emby_traefik_enabled | bool or emby_dockflare_enabled | bool

    - name: Create {{ emby_proper_name }} Container
      community.docker.docker_container:
        container_default_behavior: "compatibility"
        name: "{{ emby_container_name }}"
        hostname: "{{ emby_container_name }}"
        image: "{{ emby_image }}:{{ emby_image_tag }}"
        pull: true
        volumes:
          - "{{ emby_data_directory }}/config:/config:rw"
          - "{{ emby_anime_directory }}:/anime:{{ emby_anime_permissions }}"
          - "{{ emby_audiobooks_directory }}:/audiobooks:{{ emby_audiobooks_permissions }}"
          - "{{ emby_books_directory }}:/books:{{ emby_books_permissions }}"
          - "{{ emby_movies_directory }}:/movies:{{ emby_movies_permissions }}"
          - "{{ emby_music_directory }}:/music:{{ emby_music_permissions }}"
          - "{{ emby_photos_directory }}:/photos:{{ emby_photos_permissions }}"
          - "{{ emby_podcasts_directory }}:/podcasts:{{ emby_podcasts_permissions }}"
          - "{{ emby_porn_directory }}:/porn:{{ emby_porn_permissions }}"
          - "{{ emby_tv_directory }}:/tv:{{ emby_tv_permissions }}"
        ports:
          - "{{ emby_port_http }}:8096"
          - "{{ emby_port_https }}:8920"
        device_requests: "{{
          [{'driver': 'nvidia', 'count': -1, 'capabilities': ['gpu']}]
          if nvidia_runtime_enabled | default(false) | bool else omit
        }}"
        devices: >-
          {%- set dev_list = (app_devices | default([])) -%}
          {%- if intel_igpu_enabled | default(false) | bool or amd_gpu_enabled | default(false) | bool -%}
            {%- set _ = dev_list.append('/dev/dri:/dev/dri') -%}
          {%- endif -%}
          {{ dev_list if dev_list | length > 0 else omit }}
        group_add: "{{ ['render', 'video'] if (amd_gpu_enabled | default(false) | bool or intel_igpu_enabled | default(false) | bool) else omit }}"
        runtime: "{{ 'nvidia' if nvidia_runtime_enabled | default(false) | bool else omit }}"
        env:
          DOCKER_MODS: "{{ emby_env_docker_mods }}"
          INSTALL_PACKAGES: "{{ emby_env_docker_mods_install_packages }}"
          INSTALL_PIP_PACKAGES: "{{ emby_env_docker_mods_install_pip_packages}}"
          TZ: "{{ ansible_nas_timezone }}"
          PUID: "{{ emby_user_id }}"
          PGID: "{{ emby_group_id }}"
        healthcheck:
          test: "{{ emby_healthcheck_test }}"
          interval: "{{ emby_healthcheck_interval }}"
          timeout: "{{ emby_healthcheck_timeout }}"
          retries: "{{ emby_healthcheck_retries }}"
          start_period: "{{ emby_healthcheck_start_period }}"
        labels:
          autoheal: "{{ emby_autoheal_enabled | ternary('true', 'false') }}"
          com.centurylinklabs.watchtower.enable: "{{ emby_watchtower_enabled | ternary('true', 'false') }}"
          dockflare.enable: "{{ emby_dockflare_enabled | ternary('true', 'false') }}"
          dockflare.access.group: "{{ emby_dockflare_access_group }}"
          dockflare.hostname: "{{ emby_hostname }}.{{ ansible_nas_domain }}"
          dockflare.service: "http://{{ hostvars[inventory_hostname]['ansible_facts']['default_ipv4']['address'] }}:{{ emby_port_http }}"
          homepage.name: "{{ emby_proper_name }}"
          homepage.group: "{{ emby_homepage_group }}"
          homepage.icon: "{{ emby_homepage_icon }}"
          homepage.href: "{{ emby_homepage_href }}"
          homepage.description: "{{ 'emby description' if homepage_show_description else omit }}"
          homepage.server: "my-docker"
          homepage.container: "{{ emby_container_name }}"
          homepage.showStats: "{{ emby_homepage_showstats | ternary('true', 'false') }}"
          homepage.siteMonitor: "http://{{ hostvars[inventory_hostname]['ansible_facts']['default_ipv4']['address'] }}:{{ emby_port_http }}"
          repliqate.enabled: "{{ emby_repliqate_enabled | ternary('true', 'false') }}"
          repliqate.engine: "{{ emby_repliqate_engine }}"
          repliqate.schedule: "{{ emby_repliqate_schedule }}"
          repliqate.backup_id: "{{ emby_repliqate_backup_id }}"
          repliqate.retention: "{{ emby_repliqate_retention }}"
          traefik.enable: "{{ emby_traefik_enabled | ternary('true', 'false') }}"
          traefik.http.routers.emby.rule: "Host(`{{ emby_hostname }}.{{ ansible_nas_domain }}`)"
          traefik.http.routers.emby.tls.certresolver: "letsencrypt"
          traefik.http.routers.emby.tls.domains[0].main: "{{ ansible_nas_domain }}"
          traefik.http.routers.emby.tls.domains[0].sans: "*.{{ ansible_nas_domain }}"
          traefik.http.routers.emby.middlewares: "emby@docker{{ ',tinyauth-auth@docker' if emby_tinyauth_enabled | bool else '' }}"
          traefik.http.middlewares.emby.IPAllowList.sourcerange: "{{ emby_traefik_whitelist }}"
          traefik.http.services.emby.loadbalancer.server.port: "8096"
          emby_wud_tag_include: "^\\d+\\.\\d+\\.\\d+\\.\\d+-ls\\d+$"
          emby_wud_tag_transform_type: "semver"
          emby_wud_link_template: "https://github.com/linuxserver/docker-emby/pkgs/container/emby"
        cpu_shares: "{{ emby_cpu_shares }}"
        memory: "{{ emby_memory }}"
        memory_swap: "{{ emby_memory_swap }}"
        restart_policy: unless-stopped

    - name: Access {{ emby_proper_name }} at
      ansible.builtin.debug:
        msg: >-
              {{
                ['http://' + hostvars[inventory_hostname]['ansible_facts']['default_ipv4']['address'] + ':' + (emby_port_http | string)] +
                (['https://' + emby_hostname + '.' + ansible_nas_domain] if (emby_traefik_enabled is true or emby_dockflare_enabled is true) else [])
              }}
  when: emby_enabled is true

- name: Stop {{ emby_proper_name }}
  block:
    - name: Stop {{ emby_proper_name }} Container
      community.docker.docker_container:
        name: "{{ emby_container_name }}"
        state: absent
  when: emby_enabled is false

- name: Data Archive {{ emby_proper_name }}
  include_role:
    name: ansible-nas-archive
  vars:
    target_data_dir: "{{ emby_data_directory }}"
  when:
    - archive_app_data_enabled is true
    - emby_enabled is false