---
- name: Verify
  hosts: all
  gather_facts: false
  tasks:
    - ansible.builtin.include_vars:
        file: ../../defaults/main.yml

    - name: Try and stop and remove Gok{{ ansible_nas_app_name }}pi
      community.docker.docker_container:
        name: "{{ gokapi_container_name }}"
        state: absent
      register: result

    - name: Check {{ ansible_nas_app_name }} is stopped
      ansible.builtin.assert:
        that:
          - not result.changed
