---
- name: Start {{ ansible_nas_app_name }}
  block:
    - name: Create {{ ansible_nas_app_name }} Directories
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
      with_items:
        - "{{ openeats_data_directory }}/api"
        - "{{ openeats_data_directory }}/api/site-media"
        - "{{ openeats_data_directory }}/api/static-files"
        - "{{ openeats_data_directory }}/db"
        - "{{ openeats_data_directory }}/web"

    - name: Create {{ ansible_nas_app_name }} DB Container
      community.docker.docker_container:
        container_default_behavior: "compatibility"
        name: "{{ openeats_db_container_name }}"
        hostname: "{{ openeats_db_container_name }}"
        image: "{{ openeats_db_image_name }}:{{ openeats_db_image_tag }}"
        pull: true
        network_mode: "bridge"
        volumes:
          - "{{ openeats_data_directory }}/db:/var/lib/mysql"
        env:
          MARIADB_ROOT_PASSWORD: "{{ openeats_db_env_mariadb_root_password }}"
          MYSQL_DATABASE: "{{ openeats_db_env_mysql_database }}"
          MYSQL_USER: "{{ openeats_db_env_mysql_user }}"
          MYSQL_ROOT_PASSWORD: "{{ openeats_db_env_mysql_password }}"
          TZ: "{{ ansible_nas_timezone }}"
        healthcheck:
          test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
          timeout: "20s"
          retries: 20
        labels:
          autoheal: "{{ openeats_db_autoheal }}"
          com.centurylinklabs.watchtower.enable: "{{ openeats_db_watchtower_enable }}"
          dockflare.enable: "false"
          homepage.name: "{{ ansible_nas_app_name }} MariaDB"
          homepage.group: "{{ openeats_db_homepage_group }}"
          homepage.icon: "{{ openeats_db_homepage_icon }}"
          homepage.href: "{{ openeats_db_homepage_href }}"
          homepage.description: "{{ 'The innovative open source database' if homepage_show_description else omit }}"
          homepage.server: "my-docker"
          homepage.container: "{{ openeats_db_container_name }}"
          homepage.showStats: "{{ openeats_db_homepage_showstats }}"
          repliqate.enabled: "{{ openeats_db_repliqate_enabled }}"
          repliqate.engine: "{{ openeats_db_repliqate_engine }}"
          repliqate.schedule: "{{ openeats_db_repliqate_schedule }}"
          repliqate.backup_id: "{{ openeats_db_repliqate_backup_id }}"
          repliqate.retention: "{{ openeats_db_repliqate_retention }}"
          traefik.enable: "false"
          wud.tag.include: '^\d+\.\d+\.\d+.*$'
          wud.tag.transform.type: "semver"
          wud.link.template: "https://hub.docker.com/_/mariadb"
        cpu_shares: "{{ openeats_db_cpu_shares }}"
        memory: "{{ openeats_db_memory }}"
        restart_policy: unless-stopped

    - name: Create {{ ansible_nas_app_name }} API Container
      community.docker.docker_container:
        container_default_behavior: "compatibility"
        name: "{{ openeats_api_container_name }}"
        hostname: "{{ openeats_api_container_name }}"
        image: "{{ openeats_api_image_name }}:{{ openeats_api_image_tag }}"
        pull: true
        network_mode: "bridge"
        command: "/startup/prod-entrypoint.sh"
        volumes:
        - "site-media:/code/site-media"
        - "static-files:/code/static-files"
        ports:
          - "{{ openeats_port_api }}:8000"
        env:
          API_URL: "{{ openeats_api_env_api_url }}"
          API_PORT: "{{ openeats_port_api }}"
          DJANGO_SECRET_KEY: "{{ openeats_api_env_django_secret_key }}"
          DJANGO_SETTINGS_MODULE: "{{ openeats_api_env_django_settings_module }}"
          DJANGO_DEBUG: "{{ openeats_api_env_django_debug }}"
          ALLOWED_HOST: "{{ openeats_api_env_allowed_host }}"
          HTTP_X_FORWARDED_PROTO: "{{ openeats_api_env_http_x_forwarded_proto }}"
          MARIADB_ROOT_PASSWORD: "{{ openeats_db_env_mariadb_root_password }}"
          MYSQL_HOST: "{{ openeats_db_container_name }}"
          MYSQL_USER: "{{ openeats_db_env_mysql_user }}"
          MYSQL_PASSWORD: "{{ openeats_db_env_mysql_password }}"
          MYSQL_DATABASE: "{{ openeats_db_env_mysql_database }}"
          DB_PASSWORD: "{{ openeats_db_env_mysql_password }}"
          TZ: "{{ ansible_nas_timezone }}"
        links:
          - "{{ openeats_db_container_name }}"
        labels:
          autoheal: "{{ openeats_api_autoheal }}"
          com.centurylinklabs.watchtower.enable: "{{ openeats_api_watchtower_enable }}"
          dockflare.enable: "false"
          homepage.name: "{{ ansible_nas_app_name }} API"
          homepage.group: "{{ openeats_api_homepage_group }}"
          homepage.icon: "{{ openeats_api_homepage_icon }}"
          homepage.href: "{{ openeats_api_homepage_href }}"
          homepage.description: "{{ 'OpenEats API' if homepage_show_description else omit }}"
          homepage.server: "my-docker"
          homepage.container: "{{ openeats_api_container_name }}"
          homepage.showStats: "{{ openeats_api_homepage_showstats }}"
          repliqate.enabled: "{{ openeats_api_repliqate_enabled }}"
          repliqate.engine: "{{ openeats_api_repliqate_engine }}"
          repliqate.schedule: "{{ openeats_api_repliqate_schedule }}"
          repliqate.backup_id: "{{ openeats_api_repliqate_backup_id }}"
          repliqate.retention: "{{ openeats_api_repliqate_retention }}"
          traefik.enable: "false"
          wud.tag.include: '^\d+\.\d+\.\d+.*$'
          wud.tag.transform.type: "semver"
          wud.link.template: "https://hub.docker.com/r/openeats/openeats-api"
        cpu_shares: "{{ openeats_api_cpu_shares }}"
        memory: "{{ openeats_api_memory }}"
        restart_policy: unless-stopped

    - name: Create {{ ansible_nas_app_name }} Web UI Container
      community.docker.docker_container:
        container_default_behavior: "compatibility"
        name: "{{ openeats_web_container_name }}"
        hostname: "{{ openeats_web_container_name }}"
        image: "{{ openeats_web_image_name }}:{{ openeats_web_image_tag }}"
        pull: true
        network_mode: "bridge"
        command: "yarn start"
        links:
          - "{{ openeats_api_container_name }}"
        volumes:
          - "public-ui:/code/build"
        env:
          NODE_ENV: "{{ openeats_env_node_env }}"
          NODE_URL: "{{ openeats_env_node_url }}"
          NODE_API_URL: "{{ openeats_env_node_api_url }}"
          NODE_LOCALE: "{{ openeats_env_node_locale }}"
          TZ: "{{ ansible_nas_timezone }}"
        labels:
          autoheal: "{{ openeats_web_autoheal }}"
          com.centurylinklabs.watchtower.enable: "{{ openeats_web_watchtower_enable }}"
          dockflare.enable: "false"
          homepage.name: "{{ ansible_nas_app_name }} Web"
          homepage.group: "{{ openeats_web_homepage_group }}"
          homepage.icon: "{{ openeats_web_homepage_icon }}"
          homepage.href: "{{ openeats_web_homepage_href }}"
          homepage.description: "{{ 'OpenEats Web UI' if homepage_show_description else omit }}"
          homepage.server: "my-docker"
          homepage.container: "{{ openeats_web_container_name }}"
          homepage.showStats: "{{ openeats_web_homepage_showstats }}"
          repliqate.enabled: "{{ openeats_web_repliqate_enabled }}"
          repliqate.engine: "{{ openeats_web_repliqate_engine }}"
          repliqate.schedule: "{{ openeats_web_repliqate_schedule }}"
          repliqate.backup_id: "{{ openeats_web_repliqate_backup_id }}"
          repliqate.retention: "{{ openeats_web_repliqate_retention }}"
          traefik.enable: "false"
          wud.tag.include: '^\d+\.\d+\.\d+.*$'
          wud.tag.transform.type: "semver"
          wud.link.template: "https://hub.docker.com/r/openeats/openeats-web"
        cpu_shares: "{{ openeats_web_cpu_shares }}"
        memory: "{{ openeats_web_memory }}"
        restart_policy: unless-stopped

    - name: Create {{ ansible_nas_app_name }} Nginx Container
      community.docker.docker_container:
        container_default_behavior: "compatibility"
        name: "{{ openeats_nginx_container_name }}"
        hostname: "{{ openeats_nginx_container_name }}"
        image: "{{ openeats_nginx_image_name }}:{{ openeats_nginx_image_tag }}"
        pull: true
        network_mode: "bridge"
        command: "./start.sh"
        volumes:
        - "site-media:/var/www/html/openeats-static/site-media"
        - "static-files:/var/www/html/openeats-static/static-files"
        - "public-ui:/var/www/html/openeats-static/public-ui"
        ports:
          - "{{ openeats_port_http }}:80"
        env:
          API_PORT: "{{ openeats_port_api }}"
          WEB_PORT: "80"
          TZ: "{{ ansible_nas_timezone }}"
        links:
          - "{{ openeats_api_container_name }}:api"
          - "{{ openeats_web_container_name }}:web"
        labels:
          autoheal: "{{ openeats_nginx_autoheal }}"
          com.centurylinklabs.watchtower.enable: "{{ openeats_nginx_watchtower_enable }}"
          dockflare.enable: "{{ openeats_dockflare_tunnel }}"
          dockflare.access.group: "{{ openeats_dockflare_access_group }}"
          dockflare.hostname: "{{ openeats_hostname }}.{{ ansible_nas_domain }}"
          dockflare.service: "http://{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}:{{ openeats_port_http }}"
          homepage.name: "{{ ansible_nas_app_name }} Nginx"
          homepage.group: "{{ openeats_nginx_homepage_group }}"
          homepage.icon: "{{ openeats_nginx_homepage_icon }}"
          homepage.href: "{{ openeats_nginx_homepage_href }}"
          homepage.description: "{{ 'Self Hosted Recipe Management App' if homepage_show_description else omit }}"
          homepage.server: "my-docker"
          homepage.container: "{{ openeats_nginx_container_name }}"
          homepage.showStats: "{{ openeats_nginx_homepage_showstats }}"
          repliqate.enabled: "{{ openeats_nginx_repliqate_enabled }}"
          repliqate.engine: "{{ openeats_nginx_repliqate_engine }}"
          repliqate.schedule: "{{ openeats_nginx_repliqate_schedule }}"
          repliqate.backup_id: "{{ openeats_nginx_repliqate_backup_id }}"
          repliqate.retention: "{{ openeats_nginx_repliqate_retention }}"
          traefik.enable: "{{ openeats_available_externally | string }}"
          traefik.http.routers.openeats.rule: "Host(`{{ openeats_hostname }}.{{ ansible_nas_domain }}`)"
          traefik.http.routers.openeats.tls.certresolver: "letsencrypt"
          traefik.http.routers.openeats.tls.domains[0].main: "{{ ansible_nas_domain }}"
          traefik.http.routers.openeats.tls.domains[0].sans: "*.{{ ansible_nas_domain }}"
          traefik.http.routers.frontend.middlewares: "{{ openeats_hostname }}"
          traefik.http.routers.openeats.middlewares: "{{ openeats_hostname }}@docker"
          traefik.http.middlewares.openeats.IPAllowList.sourcerange: "{{ openeats_traefik_whitelist }}"
          traefik.http.services.openeats.loadbalancer.server.port: "80"
          wud.tag.include: '^\d+\.\d+\.\d+$'
          wud.tag.transform.type: "semver"
          wud.link.template: "https://hub.docker.com/r/openeats/openeats-nginx/tags"
        cpu_shares: "{{ openeats_nginx_cpu_shares }}"
        memory: "{{ openeats_nginx_memory }}"
        restart_policy: unless-stopped

    - name: Access {{ ansible_nas_app_name }} at
      ansible.builtin.debug:
        msg: >-
              {{
                ['http://' + hostvars[inventory_hostname]['ansible_default_ipv4']['address'] + ':' + (openeats_port_http | string)] +
                (['https://' + openeats_hostname + '.' + ansible_nas_domain] if (openeats_available_externally is true or openeats_dockflare_tunnel is true) else [])
              }}
  when: openeats_enabled is true

- name: Stop {{ ansible_nas_app_name }}
  block:
    - name: Stop {{ ansible_nas_app_name }} Nginx Container
      community.docker.docker_container:
        name: "{{ openeats_nginx_container_name }}"
        state: absent

    - name: Stop {{ ansible_nas_app_name }} API Container
      community.docker.docker_container:
        name: "{{ openeats_api_container_name }}"
        state: absent

    - name: Stop {{ ansible_nas_app_name }} Web Container
      community.docker.docker_container:
        name: "{{ openeats_web_container_name }}"
        state: absent

    - name: Stop {{ ansible_nas_app_name }} DB Container
      community.docker.docker_container:
        name: "{{ openeats_db_container_name }}"
        state: absent
  when: openeats_enabled is false

- name: Data Archive {{ ansible_nas_app_name }}
  block:
    - name: Check for {{ ansible_nas_app_name }} Data Directory
      stat:
        path: "{{ openeats_data_directory }}"
      register: dir_stat

    - name: Archive {{ ansible_nas_app_name }} Data Directory
      ansible.builtin.archive:
        path: "{{ openeats_data_directory }}"
        dest: "{{ docker_home }}/{{ ansible_nas_app_name | lower }}.zip"
        force_archive: true
        format: zip
        owner: ansible-nas
        group: ansible-nas
        mode: u=rw,g=rw
        remove: true
      when: dir_stat.stat.exists
  when: openeats_enabled is false and archive_app_data_enabled is true
