---
# ANE
ansible_nas_app_name: "QDirStat"
qdirstat_enabled: false
qdirstat_available_externally: false
qdirstat_traefik_whitelist: "{{ lan }}"
qdirstat_data_directory: "{{ docker_home }}/qdirstat"

# network
qdirstat_hostname: "qdirstat"
qdirstat_port_http: "5800"
qdirstat_port_vnc: "5800"

qdirstat_storage_directory: "{{ samba_shares_root }}"

# docker
qdirstat_container_name: "qdirstat"
qdirstat_image_name: "ghcr.io/jlesage/qdirstat"
qdirstat_image_tag: "latest"

# specs
qdirstat_cpu_shares: 1024
qdirstat_memory: "512M"

# app
# https://github.com/jlesage/docker-qdirstat
qdirstat_env_vnc_password: "{{ ansible_nas_app_admin_password }}"

# autoheal
qdirstat_autoheal: "false"

# dockflare
qdirstat_dockflare_tunnel: "false"
qdirstat_dockflare_access_group: ""

# homepage
qdirstat_homepage_group: "Apps"
qdirstat_homepage_icon: "qdirstat.png"
qdirstat_homepage_href: "http://{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}:{{ qdirstat_port_http }}"
qdirstat_homepage_showstats: "false"

# repliqate
qdirstat_repliqate_enabled: "false"
qdirstat_repliqate_engine: "restic"
qdirstat_repliqate_schedule: "@daily 3am"
qdirstat_repliqate_backup_id: "{{ qdirstat_container_name }}"
qdirstat_repliqate_retention: "30d"

# watchtower
qdirstat_watchtower_enable: "false"