---
- name: Start {{ ansible_nas_app_name }}
  block:
    - name: Create {{ ansible_nas_app_name }} Directories
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
      with_items:
        - "{{ bazarr_data_directory }}"
        - "{{ bazarr_data_directory }}/config"

    - name: Create {{ ansible_nas_app_name }} Container
      community.docker.docker_container:
        name: "{{ bazarr_container_name }}"
        image: linuxserver/bazarr
        pull: true
        cpu_shares: "{{ bazarr_cpu_shares }}"
        volumes:
          - "{{ bazarr_data_directory }}/config:/config:rw"
          - "{{ bazarr_tv_directory }}:/tv:rw"
          - "{{ bazarr_movies_directory }}:/movies:rw"
        ports:
          - "{{ bazarr_port }}:6767"
        env:
          TZ: "{{ ansible_nas_timezone }}"
          PUID: "{{ bazarr_user_id }}"
          PGID: "{{ bazarr_group_id }}"
        restart_policy: unless-stopped
        memory: "{{ bazarr_memory }}"
        labels:
          autoheal: "{{ bazarr_autoheal }}"
          com.centurylinklabs.watchtower.monitor-only: "{{ bazarr_watchtower_monitor_only }}"
          traefik.enable: "{{ bazarr_available_externally | string }}"
          traefik.http.routers.bazarr.rule: "Host(`{{ bazarr_hostname }}.{{ ansible_nas_domain }}`)"
          traefik.http.routers.bazarr.tls.certresolver: "letsencrypt"
          traefik.http.routers.bazarr.tls.domains[0].main: "{{ ansible_nas_domain }}"
          traefik.http.routers.bazarr.tls.domains[0].sans: "*.{{ ansible_nas_domain }}"
          traefik.http.services.bazarr.loadbalancer.server.port: "6767"
          homepage.group: Download Tools
          homepage.name: Bazarr
          homepage.icon: bazarr.png
          homepage.href: "http://{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}:{{ bazarr_port }}"
          homepage.description: "{{ 'Manage subtitles' if homepage_show_description else omit }}"
          homepage.widget.type: bazarr
          homepage.widget.url: "http://{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}:{{ bazarr_port }}"
  when: bazarr_enabled is true

- name: Stop {{ ansible_nas_app_name }}
  block:
    - name: Stop {{ ansible_nas_app_name }} Container
      community.docker.docker_container:
        name: "{{ bazarr_container_name }}"
        state: absent
  when: bazarr_enabled is false

- name: Data Archive {{ ansible_nas_app_name }}
  block:
    - name: Check for {{ ansible_nas_app_name }} Data Directory
      stat:
        path: "{{ bazarr_data_directory }}"
      register: dir_stat

    - name: Archive {{ ansible_nas_app_name }} Data Directory
      ansible.builtin.archive:
        path: "{{ bazarr_data_directory }}"
        dest: "{{ docker_home }}/{{ ansible_nas_app_name | lower }}.zip"
        force_archive: true
        format: zip
        owner: ansible-nas
        group: ansible-nas
        mode: u=rw,g=rw
        remove: true
      when: dir_stat.stat.exists
  when: bazarr_enabled is false and archive_app_data_enabled is true
