---
- name: Start {{ ansible_nas_app_name }}
  block:
    - name: Create {{ ansible_nas_app_name }} Directories
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
      with_items:
        - "{{ bazarr_data_directory }}"
        - "{{ bazarr_data_directory }}/config"

    - name: Create {{ ansible_nas_app_name }} Container
      community.docker.docker_container:
        container_default_behavior: "compatibility"
        name: "{{ bazarr_container_name }}"
        hostname: "{{ bazarr_container_name }}"
        image: "{{ bazarr_image_name }}:{{ bazarr_image_tag }}"
        pull: true
        volumes:
          - "{{ bazarr_data_directory }}/config:/config:rw"
          - "{{ bazarr_tv_directory }}:/tv:rw"
          - "{{ bazarr_movies_directory }}:/movies:rw"
        ports:
          - "{{ bazarr_port_http }}:6767"
        env:
          DOCKER_MODS: "{{ bazarr_env_docker_mods }}"
          INSTALL_PACKAGES: "{{ bazarr_env_docker_mods_install_packages }}"
          INSTALL_PIP_PACKAGES: "{{ bazarr_env_docker_mods_install_pip_packages}}"
          TP_DOMAIN: "{{ bazarr_env_docker_mods_tp_domain }}"
          TP_THEME: "{{ bazarr_env_docker_mods_tp_theme }}"
          TP_COMMUNITY_THEME: "{{ bazarr_env_docker_mods_tp_community_theme }}"
          TP_ADDON: "{{ bazarr_env_docker_mods_tp_addon }}"
          PUID: "{{ bazarr_user_id }}"
          PGID: "{{ bazarr_group_id }}"
          TZ: "{{ ansible_nas_timezone }}"
        labels:
          autoheal: "{{ bazarr_autoheal }}"
          com.centurylinklabs.watchtower.enable: "{{ bazarr_watchtower_enable }}"
          dockflare.enable: "{{ bazarr_dockflare_tunnel }}"
          dockflare.access.group: "{{ bazarr_dockflare_access_group }}"
          dockflare.hostname: "{{ bazarr_hostname }}.{{ ansible_nas_domain }}"
          dockflare.service: "http://{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}:{{ bazarr_port_http }}"
          homepage.name: "{{ ansible_nas_app_name }}"
          homepage.group: "{{ bazarr_homepage_group }}"
          homepage.icon: "{{ bazarr_homepage_icon }}"
          homepage.href: "{{ bazarr_homepage_href }}"
          homepage.description: "{{ 'Manage subtitles' if homepage_show_description else omit }}"
          homepage.server: "my-docker"
          homepage.container: "{{ bazarr_container_name }}"
          homepage.showStats: "{{ bazarr_homepage_showstats }}"
          homepage.siteMonitor: "http://{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}:{{ bazarr_port_http }}"
          homepage.widget.type: "bazarr"
          homepage.widget.url: "http://{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}:{{ bazarr_port_http }}"
          homepage.widget.key: "{{ bazarr_homepage_widget_key }}"
          repliqate.enabled: "{{ bazarr_repliqate_enabled }}"
          repliqate.engine: "{{ bazarr_repliqate_engine }}"
          repliqate.schedule: "{{ bazarr_repliqate_schedule }}"
          repliqate.backup_id: "{{ bazarr_repliqate_backup_id }}"
          repliqate.retention: "{{ bazarr_repliqate_retention }}"
          traefik.enable: "{{ bazarr_available_externally | string }}"
          traefik.http.routers.bazarr.rule: "Host(`{{ bazarr_hostname }}.{{ ansible_nas_domain }}`)"
          traefik.http.routers.bazarr.tls.certresolver: "letsencrypt"
          traefik.http.routers.bazarr.tls.domains[0].main: "{{ ansible_nas_domain }}"
          traefik.http.routers.bazarr.tls.domains[0].sans: "*.{{ ansible_nas_domain }}"
          traefik.http.routers.bazarr.middlewares: "bazarr@docker{{ ',tinyauth-auth@docker' if bazarr_tinyauth_enabled | bool else '' }}"
          traefik.http.middlewares.bazarr.IPAllowList.sourcerange: "{{ bazarr_traefik_whitelist }}"
          traefik.http.services.bazarr.loadbalancer.server.port: "6767"
          wud.tag.include: '^version-\d+\.\d+\.\d+$'
          wud.tag.transform.type: "semver"
          wud.link.template: "lscr.io/linuxserver/bazarr"
        cpu_shares: "{{ bazarr_cpu_shares }}"
        memory: "{{ bazarr_memory }}"
        restart_policy: unless-stopped

    - name: Access {{ ansible_nas_app_name }} at
      ansible.builtin.debug:
        msg: >-
              {{
                ['http://' + hostvars[inventory_hostname]['ansible_default_ipv4']['address'] + ':' + (bazarr_port_http | string)] +
                (['https://' + bazarr_hostname + '.' + ansible_nas_domain] if (bazarr_available_externally is true or bazarr_dockflare_tunnel is true) else [])
              }}
  when: bazarr_enabled is true

- name: Stop {{ ansible_nas_app_name }}
  block:
    - name: Stop {{ ansible_nas_app_name }} Container
      community.docker.docker_container:
        name: "{{ bazarr_container_name }}"
        state: absent
  when: bazarr_enabled is false

- name: Data Archive {{ ansible_nas_app_name }}
  include_role:
    name: ansible-nas-archive
  vars:
    target_data_dir: "{{ bazarr_data_directory }}"
  when:
    - archive_app_data_enabled is true
    - bazarr_enabled is false