---
- name: Start {{ ansible_nas_app_name }}
  block:
    - name: Create {{ ansible_nas_app_name }} Directories
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
      with_items:
        - "{{ filebrowser_quantum_data_directory }}"
        - "{{ filebrowser_quantum_data_directory }}/data"

    - name: Set {{ ansible_nas_app_name }} FQDN var overrides
      ansible.builtin.set_fact:
        filebrowser_quantum_homepage_href: "https://{{ filebrowser_quantum_hostname }}.{{ ansible_nas_domain }}"
      when: filebrowser_quantum_traefik_enabled | bool or filebrowser_quantum_dockflare_enabled | bool

    - name: Generate {{ ansible_nas_app_name }} config file
      ansible.builtin.template:
        src: config.yaml
        dest: "{{ filebrowser_quantum_data_directory }}/data/config.yaml"
      register: template_config

    - name: Create {{ ansible_nas_app_name }} Container
      community.docker.docker_container:
        container_default_behavior: "compatibility"
        name: "{{ filebrowser_quantum_container_name }}"
        hostname: "{{ filebrowser_quantum_container_name }}"
        image: "{{ filebrowser_quantum_image_name }}:{{ filebrowser_quantum_image_tag }}"
        pull: true
        volumes:
          - "{{ filebrowser_quantum_data_directory }}/data:/home/filebrowser/data"
          - "{{ filebrowser_quantum_folder }}:/{{ ansible_nas_hostname }}"
        ports:
          - "{{ filebrowser_quantum_port_http }}:80"
        env:
          FILEBROWSER_CONFIG: "data/config.yaml"
          FILEBROWSER_ADMIN_PASSWORD: "{{ filebrowser_quantum_env_filebrowser_admin_password }}"
          TZ: "{{ ansible_nas_timezone }}"
        labels:
          autoheal: "{{ filebrowser_quantum_autoheal_enabled | ternary('true', 'false') }}"
          com.centurylinklabs.watchtower.enable: "{{ filebrowser_quantum_watchtower_enabled | ternary('true', 'false') }}"
          dockflare.enable: "{{ filebrowser_quantum_dockflare_enabled | ternary('true', 'false') }}"
          dockflare.access.group: "{{ filebrowser_quantum_dockflare_access_group }}"
          dockflare.hostname: "{{ filebrowser_quantum_hostname }}.{{ ansible_nas_domain }}"
          dockflare.service: "http://{{ hostvars[inventory_hostname]['ansible_facts']['default_ipv4']['address'] }}:{{ filebrowser_quantum_port_http }}"
          homepage.name: "{{ ansible_nas_app_name }}"
          homepage.group: "{{ filebrowser_quantum_homepage_group }}"
          homepage.icon: "{{ filebrowser_quantum_homepage_icon }}"
          homepage.href: "{{ filebrowser_quantum_homepage_href }}"
          homepage.description: "{{ 'The best free self-hosted web-based file manager.' if homepage_show_description else omit }}"
          homepage.server: "my-docker"
          homepage.container: "{{ filebrowser_quantum_container_name }}"
          homepage.showStats: "{{ filebrowser_quantum_homepage_showstats | ternary('true', 'false') }}"
          homepage.siteMonitor: "http://{{ hostvars[inventory_hostname]['ansible_facts']['default_ipv4']['address'] }}:{{ filebrowser_quantum_port_http }}"
          repliqate.enabled: "{{ filebrowser_quantum_repliqate_enabled | ternary('true', 'false') }}"
          repliqate.engine: "{{ filebrowser_quantum_repliqate_engine }}"
          repliqate.schedule: "{{ filebrowser_quantum_repliqate_schedule }}"
          repliqate.backup_id: "{{ filebrowser_quantum_repliqate_backup_id }}"
          repliqate.retention: "{{ filebrowser_quantum_repliqate_retention }}"
          traefik.enable: "{{ filebrowser_quantum_traefik_enabled | ternary('true', 'false') }}"
          traefik.http.routers.filebrowserquantum.rule: "Host(`{{ filebrowser_quantum_hostname }}.{{ ansible_nas_domain }}`)"
          traefik.http.routers.filebrowserquantum.tls.certresolver: "letsencrypt"
          traefik.http.routers.filebrowserquantum.tls.domains[0].main: "{{ ansible_nas_domain }}"
          traefik.http.routers.filebrowserquantum.tls.domains[0].sans: "*.{{ ansible_nas_domain }}"
          traefik.http.routers.filebrowserquantum.middlewares: "filebrowserquantum@docker{{ ',tinyauth-auth@docker' if filebrowser_quantum_tinyauth_enabled | bool else '' }}"
          traefik.http.middlewares.filebrowserquantum.IPAllowList.sourcerange: "{{ filebrowser_quantum_traefik_whitelist }}"
          traefik.http.services.filebrowser.loadbalancer.server.port: "80"
          wud.tag.include: '^v\d+\.\d+\.\d+$'
          wud.tag.transform.type: "semver"
          wud.link.template: "https://github.com/gtsteffaniak/filebrowser/pkgs/container/filebrowser"
        cpu_shares: "{{ filebrowser_quantum_cpu_shares }}"
        memory: "{{ filebrowser_quantum_memory }}"
        memory_swap: "{{ filebrowser_quantum_memory_swap }}"
        recreate: "{{ template_config is changed }}"
        restart_policy: unless-stopped

    - name: Access {{ ansible_nas_app_name }} at
      ansible.builtin.debug:
        msg: >-
              {{
                ['http://' + hostvars[inventory_hostname]['ansible_facts']['default_ipv4']['address'] + ':' + (filebrowser_quantum_port_http | string)] +
                (['https://' + filebrowser_quantum_hostname + '.' + ansible_nas_domain] if (filebrowser_quantum_traefik_enabled is true or filebrowser_quantum_dockflare_enabled is true) else [])
              }}
  when: filebrowser_quantum_enabled is true

- name: Stop {{ ansible_nas_app_name }}
  block:
    - name: Stop {{ ansible_nas_app_name }} Container
      community.docker.docker_container:
        name: "{{ filebrowser_quantum_container_name }}"
        state: absent
  when: filebrowser_quantum_enabled is false

- name: Data Archive {{ ansible_nas_app_name }}
  include_role:
    name: ansible-nas-archive
  vars:
    target_data_dir: "{{ filebrowser_quantum_data_directory }}"
  when:
    - archive_app_data_enabled is true
    - filebrowser_quantum_enabled is false