---
#- name: Start Ubuntu 22.04 LTS Specific Setup
#  block:
#    DO NOTHING CURRENTLY
#  when: ansible_distribution == "Ubuntu" and ansible_distribution_version == "22.04"

#- name: Start Ubuntu 24.04 LTS Specific Setup
#  block:
#    DO NOTHING CURRENTLY
#  when: ansible_distribution == "Ubuntu" and ansible_distribution_version == "24.04"

#- name: Start Ubuntu 26.04 LTS Specific Setup
#  block:
#    DO NOTHING CURRENTLY
#  when: ansible_distribution == "Ubuntu" and ansible_distribution_version == "26.04"

- name: Update apt-cache
  ansible.builtin.apt:
    update_cache: yes
    cache_valid_time: 3600
  register: result
  until: result is succeeded

- name: Upgrade all packages
  ansible.builtin.apt:
    upgrade: yes
    state: latest
  when: keep_packages_updated
  tags:
    - skip_ansible_lint

- name: Install extra packages
  ansible.builtin.apt:
    name: "{{ ansible_nas_extra_packages }}"
    state: present
  register: result
  until: result is succeeded

- name: "Set hostname to {{ ansible_nas_hostname }}"
  ansible.builtin.hostname:
    name: "{{ ansible_nas_hostname }}"

- name: "Set timezone to {{ ansible_nas_timezone }}"
  community.general.timezone:
    name: "{{ ansible_nas_timezone }}"

- name: "Permission share directories"
  ansible.builtin.file:
    path: "{{ item.path }}"
    state: directory
    owner: ansible-nas
    group: ansible-nas
    mode: "u=rwX,g=rwX,o=rX"
    recurse: false
  loop: "{{ samba_shares }}"

- name: Install figlet
  ansible.builtin.apt:
    pkg:
    - figlet
    state: present
  register: result
  until: result is succeeded

- name: Install app data (un)archiving support
  ansible.builtin.apt:
    pkg:
    - unzip
    state: present
  register: result
  until: result is succeeded
  when: archive_app_data_enabled is true

- name: Install AMD GPU support software
  ansible.builtin.apt:
    pkg:
    - mesa-va-drivers
    - mesa-vdpau-drivers
    - vainfo
    - libdrm-amdgpu1
    - ocl-icd-libopencl1
    - beignet-opencl-icd  # may not be needed
    - libavutil58         # may need lower version on some 
    state: present
  register: result
  until: result is succeeded
  when: amd_gpu_enabled is true

- name: Install Intel iGPU support software
  ansible.builtin.apt:
    pkg:
    - intel-media-va-driver-non-free
#    - i965-va-driver  # for 9th gen CPUs and earlier
    - intel-gpu-tools
    - vainfo
    state: present
  register: result
  until: result is succeeded
  when: intel_igpu_enabled is true

- name: Check if generated login banner exists
  ansible.builtin.stat:
    path: motd.txt
  register: motd_exists

- name: Generate login banner using figlet if it doesn't exist
  ansible.builtin.shell: "echo \"{{ ansible_nas_hostname }}\" | figlet > motd.txt"
  when: not motd_exists.stat.exists

- name: Add text to generated login banner
  lineinfile:
    path: motd.txt
    line: "Ansible-NAS-Enhanced - https://github.com/bcurran3/ansible-nas-enhanced"
    create: yes

- name: Set login banner
  copy:
    src: motd.txt
    dest: /etc/motd
