---
# DO NOTHING CURRENTLY
#- name: Start Ubuntu 22.04 LTS Specific Setup
#  block:
#  when: ansible_distribution == "Ubuntu" and ansible_distribution_version == "22.04"

# DO NOTHING CURRENTLY
#- name: Start Ubuntu 24.04 LTS Specific Setup
#  block:
#  when: ansible_distribution == "Ubuntu" and ansible_distribution_version == "24.04"

- name: Check if generated login banner exists
  ansible.builtin.stat:
    path: files/motd.txt
  register: motd_exists

- name: Generate login banner using figlet if it doesn't exist
  ansible.builtin.shell: "echo \"{{ ansible_nas_hostname }}\" | figlet > files/motd.txt"
  when: not motd_exists.stat.exists

- name: Add text to generated login banner
  lineinfile:
    path: files/motd.txt
    line: "Ansible-NAS-Enhanced - https://github.com/bcurran3/ansible-nas-enhanced"
    create: yes

- name: Set login banner
  copy:
    src: files/motd.txt
    dest: /etc/motd

- name: Update apt-cache
  ansible.builtin.apt:
    update_cache: yes
    cache_valid_time: 3600
  register: result
  until: result is succeeded

- name: Upgrade all packages # noqa package-latest
  ansible.builtin.apt:
    upgrade: yes
    state: latest
  when: keep_packages_updated
  tags:
    - skip_ansible_lint

- name: Install some packages
  ansible.builtin.apt:
    name: "{{ ansible_nas_extra_packages }}"
    state: present
  register: result
  until: result is succeeded

- name: "Set hostname to {{ ansible_nas_hostname }}"
  ansible.builtin.hostname:
    name: "{{ ansible_nas_hostname }}"

- name: "Set timezone to {{ ansible_nas_timezone }}"
  community.general.timezone:
    name: "{{ ansible_nas_timezone }}"

- name: "Permission share directories"
  ansible.builtin.file:
    path: "{{ item.path }}"
    state: directory
    owner: ansible-nas
    group: ansible-nas
    mode: "u=rwX,g=rwX,o=rX"
    recurse: false
  loop: "{{ samba_shares }}"
