---
- name: Start Duplicati
  block:
    - name: Create Duplicati Directory
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
      with_items:
        - "{{ duplicati_data_directory }}"
        - "{{ duplicati_data_directory }}/custom-cont-init.d" # added

    - name: Dupicati Docker Container
      community.docker.docker_container:
        name: "{{ duplicati_container_name }}"
        hostname: "{{ duplicati_container_name }}"
        image: linuxserver/duplicati
        pull: true
        cpu_shares: "{{ duplicati_cpu_shares }}"
        ports:
          - "{{ duplicati_port }}:8200"
        volumes:
          - "{{ duplicati_data_directory }}:/config:rw"
          - "{{ samba_shares_root }}:/source/shares:{{ duplicati_data_permissions }}"
          - "{{ docker_home }}:/source/docker:{{ duplicati_data_permissions }}"
          - "/etc/timezone:/etc/timezone:ro"
          - "{{ duplicati_data_directory }}/custom-cont-init.d:/custom-cont-init.d:ro" # added
          - "{{ samba_shares_other_root }}/BACKUPS:/backups:rw" # my config only
        capabilities: # added
          - NET_ADMIN # added
          - DAC_READ_SEARCH # added
        env:
          PUID: "{{ duplicati_user_id }}"
          PGID: "{{ duplicati_group_id }}"
          TZ: "{{ ansible_nas_timezone }}"
          DOCKER_MODS: "linuxserver/mods:universal-package-install" # added
          INSTALL_PACKAGES: "smbclient|cifs-utils" # added
        restart_policy: unless-stopped
        memory: "{{ duplicati_memory }}"
        labels:
          autoheal: "{{ duplicati_autoheal }}"
          com.centurylinklabs.watchtower.monitor-only: "{{ duplicati_watchtower_monitor_only }}"
          homepage.group: "Apps"
          homepage.name: "Duplicati"
          homepage.icon: "duplicati.png"
          homepage.href: "http://{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}:{{ duplicati_port }}"
          homepage.siteMonitor: "http://{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}:{{ duplicati_port }}"
#         homepage.description: ""
          homepage.server: "my-docker"
          homepage.container: "duplicati"
          homepage.showStats: "false"
          traefik.enable: "{{ duplicati_available_externally | string }}"
          traefik.http.routers.duplicati.rule: "Host(`{{ duplicati_hostname }}.{{ ansible_nas_domain }}`)"
          traefik.http.routers.duplicati.tls.certresolver: "letsencrypt"
          traefik.http.routers.duplicati.tls.domains[0].main: "{{ ansible_nas_domain }}"
          traefik.http.routers.duplicati.tls.domains[0].sans: "*.{{ ansible_nas_domain }}"
          traefik.http.routers.frontend.middlewares: "{{ duplicati_hostname }}"
          traefik.http.routers.duplicati.middlewares: "{{ duplicati_hostname }}@docker"
          traefik.http.middlewares.duplicati.IPAllowList.sourcerange: "{{ duplicati_traefik_whitelist }}"
          traefik.http.services.duplicati.loadbalancer.server.port: "8200"
#         wud.tag.include: '^v\d+\.\d+\.\d+\.\d+-\d+\.\d+\.\d+\.\d+.*$$'
  when: duplicati_enabled is true

- name: Stop Duplicati
  block:
    - name: Stop Duplicati
      community.docker.docker_container:
        name: "{{ duplicati_container_name }}"
        state: absent
  when: duplicati_enabled is false
