---
- name: Start {{ youtarr_proper_name }}
  block:
    - name: Create {{ youtarr_proper_name }} Directories
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
      with_items:
        - "{{ youtarr_data_directory }}"
        - "{{ youtarr_data_directory }}/config"
        - "{{ youtarr_data_directory }}/db"
        - "{{ youtarr_data_directory }}/images"
        - "{{ youtarr_data_directory }}/jobs"
        - "{{ youtarr_download_directory }}"

    - name: Set {{ youtarr_proper_name }} FQDN var overrides
      ansible.builtin.set_fact:
        youtarr_homepage_href: "https://{{ youtarr_hostname }}.{{ ansible_nas_domain }}"
      when: youtarr_traefik_enabled | bool or youtarr_dockflare_enabled | bool

    - name: Create {{ youtarr_proper_name }} DB Container
      community.docker.docker_container:
        container_default_behavior: "compatibility"
        name: "{{ youtarr_db_container_name }}"
        hostname: "{{ youtarr_db_container_name }}"
        image: "{{ youtarr_db_image_name }}:{{ youtarr_db_image_tag }}"
        pull: true
        command: "--port=3321 --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci"
        volumes:
          - "{{ youtarr_data_directory }}/db:/var/lib/mysql"
          - "{{ youtarr_data_directory }}/migrations:/docker-entrypoint-initdb.d"
          - "{{ youtarr_data_directory }}/config/mariadb.cnf:/etc/mysql/conf.d/charset.cnf:ro"
        env:
          MYSQL_ROOT_PASSWORD: "{{ youtarr_env_db_password }}"
          MYSQL_DATABASE: "{{ youtarr_env_db_name }}"
          MYSQL_TCP_PORT: "3321"
          MYSQL_CHARSET: "utf8mb4"
          MYSQL_COLLATION: "utf8mb4_unicode_ci"
          TZ: "{{ ansible_nas_timezone }}"
        healthcheck:
          test: "{{ youtarr_db_healthcheck_test }}"
          interval: "{{ youtarr_db_healthcheck_interval }}"
          timeout: "{{ youtarr_db_healthcheck_timeout }}"
          retries: "{{ youtarr_db_healthcheck_retries }}"
          start_period: "{{ youtarr_db_healthcheck_start_period }}"
        labels:
          autoheal: "{{ youtarr_db_autoheal_enabled | ternary('true', 'false') }}"
          com.centurylinklabs.watchtower.enable: "{{ youtarr_db_watchtower_enabled | ternary('true', 'false') }}"
          dockflare.enable: "false"
          homepage.name: "{{ youtarr_proper_name }} MariaDB"
          homepage.group: "{{ youtarr_db_homepage_group }}"
          homepage.icon: "{{ youtarr_db_homepage_icon }}"
          homepage.href: "{{ youtarr_db_homepage_href }}"
          homepage.description: "{{ 'MariaDB Server is a high performing open source relational database, forked from MySQL.' if homepage_show_description else omit }}"
          homepage.server: "my-docker"
          homepage.container: "{{ youtarr_db_container_name }}"
          homepage.showStats: "{{ youtarr_db_homepage_showstats | ternary('true', 'false') }}"
          repliqate.enabled: "{{ youtarr_db_repliqate_enabled | ternary('true', 'false') }}"
          repliqate.engine: "{{ youtarr_db_repliqate_engine }}"
          repliqate.schedule: "{{ youtarr_db_repliqate_schedule }}"
          repliqate.backup_id: "{{ youtarr_db_repliqate_backup_id }}"
          repliqate.retention: "{{ youtarr_db_repliqate_retention }}"
          traefik.enable: "false"
          wud.tag.include: '^\d+\.\d+\.\d+.*$'
          wud.tag.transform.type: "semver"
          wud.link.template: "https://hub.docker.com/_/mariadb"
        cpu_shares: "{{ youtarr_db_cpu_shares }}"
        memory: "{{ youtarr_db_memory }}"
        memory_swap: "{{ youtarr_db_memory_swap }}"
        restart_policy: unless-stopped

    - name: Wait for {{ youtarr_proper_name }} DB to become healthy
      community.docker.docker_container_info:
        name: "{{ youtarr_db_container_name }}"
      register: db_info
      until: "db_info.container.State.Health.Status == 'healthy'"
      retries: 30
      delay: 5

    - name: Create {{ youtarr_proper_name }} Container
      community.docker.docker_container:
        container_default_behavior: "compatibility"
        name: "{{ youtarr_container_name }}"
        hostname: "{{ youtarr_container_name }}"
        image: "{{ youtarr_image_name }}:{{ youtarr_image_tag }}"
        pull: true
        volumes:
          - "{{ youtarr_data_directory }}/images:/app/server/images"
          - "{{ youtarr_data_directory }}/config:/app/config"
          - "{{ youtarr_data_directory }}/jobs:/app/jobs"
          - "{{ youtarr_download_directory }}:/usr/src/app/data"
        ports:
          - "{{ youtarr_port_http }}:3011"
        env:
          AUTH_ENABLED: "{{ youtarr_env_auth_enabled }}"
          AUTH_PRESET_USERNAME: "{{ youtarr_env_auth_preset_username }}"
          AUTH_PRESET_PASSWORD: "{{ youtarr_env_auth_preset_password }}"
          DB_HOST: "{{ youtarr_db_container_name }}"
          DB_PORT: "3321"
          DB_USER: "{{ youtarr_env_db_user }}"
          DB_PASSWORD: "{{ youtarr_env_db_password }}"
          DB_NAME: "{{ youtarr_env_db_name }}"
          IN_DOCKER_CONTAINER: "{{ youtarr_env_in_docker_container }}"
          PLEX_URL: "{{ youtarr_env_plex_url }}"
          YOUTUBE_OUTPUT_DIR: "/usr/src/app/data"
          TZ: "{{ ansible_nas_timezone }}"
        healthcheck:
          test: "{{ youtarr_healthcheck_test }}"
          interval: "{{ youtarr_healthcheck_interval }}"
          timeout: "{{ youtarr_healthcheck_timeout }}"
          retries: "{{ youtarr_healthcheck_retries }}"
          start_period: "{{ youtarr_healthcheck_start_period }}"
        links:
          - "{{ youtarr_db_container_name }}"
        labels:
          autoheal: "{{ youtarr_autoheal_enabled | ternary('true', 'false') }}"
          com.centurylinklabs.watchtower.enable: "{{ youtarr_watchtower_enabled | ternary('true', 'false') }}"
          dockflare.enable: "{{ youtarr_dockflare_enabled | ternary('true', 'false') }}"
          dockflare.access.group: "{{ youtarr_dockflare_access_group }}"
          dockflare.hostname: "{{ youtarr_hostname }}.{{ ansible_nas_domain }}"
          dockflare.service: "http://{{ hostvars[inventory_hostname]['ansible_facts']['default_ipv4']['address'] }}:{{ youtarr_port_http }}"
          homepage.name: "{{ youtarr_proper_name }}"
          homepage.group: "{{ youtarr_homepage_group }}"
          homepage.icon: "{{ youtarr_homepage_icon }}"
          homepage.href: "{{ youtarr_homepage_href }}"
          homepage.description: "{{ 'youtarr description' if homepage_show_description else omit }}"
          homepage.server: "my-docker"
          homepage.container: "{{ youtarr_container_name }}"
          homepage.showStats: "{{ youtarr_homepage_showstats | ternary('true', 'false') }}"
          homepage.siteMonitor: "http://{{ hostvars[inventory_hostname]['ansible_facts']['default_ipv4']['address'] }}:{{ youtarr_port_http }}"
          repliqate.enabled: "{{ youtarr_repliqate_enabled | ternary('true', 'false') }}"
          repliqate.engine: "{{ youtarr_repliqate_engine }}"
          repliqate.schedule: "{{ youtarr_repliqate_schedule }}"
          repliqate.backup_id: "{{ youtarr_repliqate_backup_id }}"
          repliqate.retention: "{{ youtarr_repliqate_retention }}"          
          traefik.enable: "{{ youtarr_traefik_enabled | ternary('true', 'false') }}"
          traefik.http.routers.youtarr.rule: "Host(`{{ youtarr_hostname }}.{{ ansible_nas_domain }}`)"
          traefik.http.routers.youtarr.tls.certresolver: "letsencrypt"
          traefik.http.routers.youtarr.tls.domains[0].main: "{{ ansible_nas_domain }}"
          traefik.http.routers.youtarr.tls.domains[0].sans: "*.{{ ansible_nas_domain }}"
          traefik.http.routers.youtarr.middlewares: "youtarr@docker{{ ',tinyauth-auth@docker' if youtarr_tinyauth_enabled | bool else '' }}"
          traefik.http.middlewares.youtarr.IPAllowList.sourcerange: "{{ youtarr_traefik_whitelist }}"
          traefik.http.services.youtarr.loadbalancer.server.port: "3011"
          wud.tag.include: '^v?\d+\.\d+\.\d+.*$'
          wud.tag.transform: "semver"
          wud.link.template: "https://hub.docker.com/r/dialmaster/youtarr"
        cpu_shares: "{{ youtarr_cpu_shares }}"
        memory: "{{ youtarr_memory }}"
        memory_swap: "{{ youtarr_memory_swap }}"
        restart_policy: unless-stopped

    - name: Access {{ youtarr_proper_name }} at
      ansible.builtin.debug:
        msg: >-
              {{
                ['http://' + hostvars[inventory_hostname]['ansible_facts']['default_ipv4']['address'] + ':' + (youtarr_port_http | string)] +
                (['https://' + youtarr_hostname + '.' + ansible_nas_domain] if (youtarr_traefik_enabled is true or youtarr_dockflare_enabled is true) else [])
              }}
  when: youtarr_enabled is true

- name: Stop {{ youtarr_proper_name }}
  block:
    - name: Stop {{ youtarr_proper_name }} Container
      community.docker.docker_container:
        name: "{{ youtarr_container_name }}"
        state: absent

    - name: Stop {{ youtarr_proper_name }} DB Container
      community.docker.docker_container:
        name: "{{ youtarr_db_container_name }}"
        state: absent
  when: youtarr_enabled is false

- name: Data Archive {{ youtarr_proper_name }}
  include_role:
    name: ansible-nas-archive
  vars:
    target_data_dir: "{{ youtarr_data_directory }}"
  when:
    - archive_app_data_enabled is true
    - youtarr_enabled is false