---
# ANE
navidrome_proper_name: "Navidrome"
navidrome_enabled: false
navidrome_traefik_enabled: false
navidrome_traefik_whitelist: "{{ lan }}"

# directories
navidrome_data_directory: "{{ docker_home }}/navidrome"
navidrome_music_directory: "{{ music_root }}"

# network
navidrome_port_http: "4533"
navidrome_hostname: "navidrome"

# docker
navidrome_container_name: "navidrome"
navidrome_image_name: "deluan/navidrome"
navidrome_image_version: "latest"

# specs
navidrome_cpu_shares: 1024
navidrome_memory: "1G"
navidrome_memory_swap: -1

# default config
navidrome_scan_schedule: "@every 1m" # Cron syntax (https://en.wikipedia.org/wiki/Cron)
navidrome_log_level: "info"
navidrome_session_timeout: "24h"

# autoheal
navidrome_autoheal_enabled: false

# dockflare
navidrome_dockflare_enabled: false
navidrome_dockflare_access_group: ""

# homepage
navidrome_homepage_group: "Media Servers"
navidrome_homepage_icon: "navidrome.png"
navidrome_homepage_href: "http://{{ hostvars[inventory_hostname]['ansible_facts']['default_ipv4']['address'] }}:{{ navidrome_port_http }}"
navidrome_homepage_showstats: false
navidrome_homepage_widget_user: ""
navidrome_homepage_widget_token: ""
navidrome_homepage_widget_salt: ""

# repliqate
navidrome_repliqate_enabled: false
navidrome_repliqate_engine: "restic"
navidrome_repliqate_schedule: "@daily 3am"
navidrome_repliqate_backup_id: "{{ navidrome_container_name }}"
navidrome_repliqate_retention: "30d"

# tinyauth
navidrome_tinyauth_enabled: false

# watchtower
navidrome_watchtower_enabled: false