---
# Page meta info, like heading, footer text and nav links
pageInfo:
  title: "{{ ansible_nas_hostname }} Dashboard"
  description: Welcome to your ANE dashboard
  navLinks:
    - title: Ansible-NAS-Enhanced Repo
      path: https://github.com/bcurran3/ansible-nas-enahanced

# Optional app settings and configuration
appConfig:
  theme: colorful

# Main content - An array of sections, each containing an array of items
sections:
  - name: ANE Applications
    icon: fas fa-tasks
    displayData:
      sortBy: most-used
      sectionLayout: grid
      itemCountX: 5
      cols: 2
    items:
    - title: Clock
      icon: fas fa-clock
