---
# ANE
ansible_nas_app_name: "Dasharr"
dasharr_enabled: false
dasharr_available_externally: false
dasharr_traefik_whitelist: "{{ lan }}"

# directories
dasharr_data_directory: "{{ docker_home }}/dasharr"

# docker
dasharr_container_name: "dasharr"
dasharr_image_name: "schenanigans/dasharr"
dasharr_image_tag: "latest"

# uid / gid
dasharr_user_id: "1000"
dasharr_group_id: "1000"

# network
dasharr_port_http: "3035"
dasharr_hostname: "dasharr"

# specs
dasharr_cpu_shares: 1024
dasharr_memory: "1G"
dasharr_memory_swap: -1

# app
# https://dasharr.io/docs/configuration
dasharr_env_app_url: "http://{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}:{{ dasharr_port_http }}" # Full URL where the application is accessible -  Used for generating absolute URLs
dasharr_env_trust_proxy: "false" # Set to true if using nginx, Caddy, Cloudflare, etc.
# You can generate one using: openssl rand -base64 32
dasharr_env_session_secret: "gKSGrTKtl1ZMIKmYkcUMmPp7/b9jsGy1WTPs7KYGKS4="

dasharr_env_jellyfin_url: "http://{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}:{{ jellyfin_port_http }}"
dasharr_env_jellyfin_api_key: ""
dasharr_env_jellyseerr_url: "http://{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}:{{ jellyseerr_port_http }}"
dasharr_env_jellyseerr_api_key: ""
dasharr_env_overseerr_url: "http://{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}:{{ overseerr_port_http }}"
dasharr_env_overseerr_api_key: ""
dasharr_env_plex_url: "https://{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}:32400"
dasharr_env_plex_token: ""
dasharr_env_prowlarr_url: "http://{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}:{{ prowlarr_port_http }}"
dasharr_env_prowlarr_api_key: ""
dasharr_env_qbittorrent_url: "http://{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}:{{ qbittorrent_port_http }}"
dasharr_env_qbittorrent_username: ""
dasharr_env_qbittorrent_password: ""
dasharr_env_radarr_url: "http://{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}:{{ radarr_port_http }}"
dasharr_env_radarr_api_key: ""
dasharr_env_sabnzbd_url: "http://{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}:{{ sabnzbd_port_http }}"
dasharr_env_sabnzbd_api_key: ""
dasharr_env_sonarr_url: "http://{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}:{{ sonarr_port_http }}"
dasharr_env_sonarr_api_key: ""
dasharr_env_tautulli_url: "http://{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}:{{ tautulli_port_http }}"
dasharr_env_tautulli_api_key: ""

# autoheal
dasharr_autoheal: "false"

# dockflare
dasharr_dockflare_tunnel: "false"
dasharr_dockflare_access_group: ""

# homepage
dasharr_homepage_group: "Apps"
dasharr_homepage_icon: "sh-dasharr.png"
dasharr_homepage_href: "http://{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}:{{ dasharr_port_http }}"
dasharr_homepage_showstats: "false"

# repliqate
dasharr_repliqate_enabled: "false"
dasharr_repliqate_engine: "restic"
dasharr_repliqate_schedule: "@daily 3am"
dasharr_repliqate_backup_id: "{{ dasharr_container_name }}"
dasharr_repliqate_retention: "30d"

# tinyauth
dasharr_tinyauth_enabled: false

# watchtower
dasharr_watchtower_enable: "false"
