---
# ANE
ansible_nas_app_name: "Homepage"
homepage_enabled: false
homepage_available_externally: false
homepage_traefik_whitelist: "{{ lan }}"

# directories
homepage_data_directory: "{{ docker_home }}/homepage"

# network
homepage_hostname: "homepage"
homepage_port_http: "11111"

# app
homepage_puid: "0"
homepage_pgid: "0"
homepage_allowed_hosts: "*"
homepage_show_description: false

# docker
homepage_container_name: "homepage"
homepage_image_name: "ghcr.io/gethomepage/homepage"
homepage_image_tag: "latest"

# specs
homepage_cpu_shares: 1024
homepage_memory: "512M"
homepage_memory_swap: -1

# autoheal
homepage_autoheal: false

# dockflare
homepage_dockflare_enabled: false
homepage_dockflare_access_group: ""

# repliqate
homepage_repliqate_enabled: false
homepage_repliqate_engine: "restic"
homepage_repliqate_schedule: "@daily 3am"
homepage_repliqate_backup_id: "{{ homepage_container_name }}"
homepage_repliqate_retention: "30d"

# tinyauth
homepage_tinyauth_enabled: false

# watchtower
homepage_watchtower_enabled: false

# https://gethomepage.dev/configs/settings/
homepage_title: "{{ ansible_nas_hostname }} Homepage"
homepage_locale: en-US

###
### Homepage config files template values
###

# https://gethomepage.dev/configs/bookmarks/
homepage_bookmarks_yaml:
  - Developer:
      - "Ansible-NAS-Enhanced":
          - abbr: ANE
            href: https://gitea.mrbillsabode.org/bill/ansible-nas-enhanced
      - Github:
          - abbr: GH
            href: https://github.com/
            icon: github
      - "Hacker News":
          - abbr: HN
            href: https://news.ycombinator.com/
  - Social:
      - Reddit:
          - abbr: RE
            href: https://reddit.com/
            icon: reddit
  - Entertainment:
      - YouTube:
          - abbr: YT
            href: https://youtube.com/
            icon: youtube

# https://gethomepage.dev/configs/services/
homepage_services_yaml:
#  - Networking:
#      - Router:
#          icon: asus-router
#          href: http://192.168.1.1/
#          description: Asus Router

# Homepage config files - the variables below are formatted to Homepage YAML config files
homepage_settings_yaml:
  title: "{{ homepage_title }}" # You can customize the title of the page if you'd like.
#  description: "" # You can customize the description of the page if you'd like.
  startUrl: "http://{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}:{{ homepage_port_http }}" # You can customize the start_url as required for installable apps. The default is "/".
#  background: "" # f you'd like to use a background image instead of the solid theme color, you may provide a full URL to an image of your choice.
#  favicon: "sh-ansible.png" # If you'd like to use a custom favicon instead of the included one, you may provide a full URL to an image of your choice.
#  base: "https://{{ homepage_hostname }}.{{ ansible_nas_domain }}"
  instanceName: "{{ ansible_nas_user }}"
#  image: "https://bing.biturl.top/?resolution=1920&format=image&index=0&mkt=en-US" # Bing Wallpaper of the Day
#  image: "https://loremflickr.com/1920/1080/space" # space pics
  image: "https://picsum.photos/1200/800" # changes on every refresh
  hideErrors: true # hide widget error messages
  language: "{{ homepage_locale }}"
# fiveColumns: true
  fullWidth: true
  useEqualHeights: false
  backgroundOpacity: 50
  cardBlur: xl # xs, md, etc... see https://tailwindcss.com/docs/backdrop-blur
  color: slate # Supported colors are: slate, gray, zinc, neutral, stone, amber, yellow, lime, green, emerald, teal, cyan, sky, blue, indigo, violet, purple, fuchsia, pink, rose, red, white
  headerStyle: boxedWidgets # underlined, boxed, clean, boxedWidgets
  target: _blank # Possible options include _blank, _self, and _top
  theme: dark # or light
  showStats: true
  layout:
    Favorites:
      style: row
      columns: 4
    Apps:
      style: row
      columns: 5
    Media Management:
      style: row
      columns: 4
    Media Servers:
      style: row
      columns: 4
    Download Tools:
      style: row
      columns: 4
    Network:
      style: row
      columns: 4
    DBs:
      style: row
      columns: 4
    Misc:
      style: row
      columns: 4
#    providers:
#      openweathermap: openweathermapapikey
#      weatherapi: weatherapiapikey

# https://gethomepage.dev/widgets/
homepage_widgets_yaml:
  - search:
      provider: google # google, duckduckgo, bing, baidu, brave or custom
      focus: true # Optional, will set focus to the search bar on page load
      target: _blank # One of _self, _blank, _parent or _top
  - greeting:
      text_size: xl
      text: "{{ ansible_nas_hostname }}"
  - datetime:
      text_size: xl # Valid text sizes are 4xl, 3xl, 2xl, xl, md, sm, xs
      format:
        timeStyle: short
        hour12: true
        dateStyle: short
  - resources:
      cpu: true
      memory: true
      cputemp: true
      uptime: true
      units: metric # only used by cpu temp
      refresh: 60000 # optional, in ms

# https://gethomepage.dev/configs/proxmox/
homepage_proxmox_yaml:
#  - pve: # must match your actual Proxmox node name
#      url: "" # https://proxmox.host.or.ip:8006
#      token: "" # username@pam!Token ID
#      secret: "" # secret

# https://gethomepage.dev/configs/docker/
homepage_docker_yaml:
  my-docker:
    socket: /var/run/docker.sock

# https://gethomepage.dev/configs/kubernetes/
homepage_kubernetes_yaml:
  mode: disabled
