---
# ANE
ansible_nas_app_name: "Homepage"
homepage_enabled: false
homepage_available_externally: false
homepage_traefik_whitelist: "{{ lan }}"

# directories
homepage_data_directory: "{{ docker_home }}/homepage"

# network
homepage_hostname: "homepage"
homepage_port_http: "11111"

# app
homepage_puid: "0"
homepage_pgid: "0"
homepage_allowed_hosts: "*"
homepage_show_description: "false"

# docker
homepage_container_name: "homepage"
homepage_image_name: "ghcr.io/gethomepage/homepage"
homepage_image_tag: "latest"
homepage_cpu_shares: 1024
homepage_memory: "512M"

# autoheal
homepage_autoheal: "false"

# dockflare
homepage_dockflare_tunnel: "false"
homepage_dockflare_access_group: ""

# repliqate
homepage_repliqate_enabled: "false"
homepage_repliqate_engine: "restic"
homepage_repliqate_schedule: "@daily 3am"
homepage_repliqate_backup_id: "{{ homepage_container_name }}"
homepage_repliqate_retention: "30d"

# watchtower
homepage_watchtower_enable: "false"

# App template file values
###############################
homepage_bookmarks_yaml:
  - Developer:
      - "Ansible-NAS-Enhanced":
          - abbr: ANE
            href: https://gitea.mrbillsabode.org/bill/ansible-nas-enhanced
      - Github:
          - abbr: GH
            href: https://github.com/
            icon: github
      - "Hacker News":
          - abbr: HN
            href: https://news.ycombinator.com/
  - Social:
      - Reddit:
          - abbr: RE
            href: https://reddit.com/
            icon: reddit
  - Entertainment:
      - YouTube:
          - abbr: YT
            href: https://youtube.com/
            icon: youtube

homepage_services_yaml:
#  - Networking:
#      - Router:
#          icon: asus-router
#          href: http://192.168.1.1/
#          description: Asus Router

# settings
homepage_title: "{{ ansible_nas_hostname }} Homepage"
homepage_locale: en-US

# Homepage config files - the variables below are formatted to Homepage YAML config files
homepage_settings_yaml:
  title: "{{ homepage_title }}"
  favicon: "sh-ansible.png"
#  base: "https://{{ homepage_hostname }}.{{ ansible_nas_domain }}"
  instanceName: "{{ ansible_nas_user }}"
  language: "{{ homepage_locale }}"
# fiveColumns: true
  fullWidth: true
  useEqualHeights: false
  backgroundOpacity: 50
  cardBlur: xl # xs, md, etc... see https://tailwindcss.com/docs/backdrop-blur
  color: slate # Supported colors are: slate, gray, zinc, neutral, stone, amber, yellow, lime, green, emerald, teal, cyan, sky, blue, indigo, violet, purple, fuchsia, pink, rose, red, white
  headerStyle: boxedWidgets # underlined, boxed, clean, boxedWidgets
  target: _blank # Possible options include _blank, _self, and _top
  theme: dark # or light
  showStats: true
  layout:
    Apps:
      style: row
      columns: 6
    Media Management:
      style: column
  #    columns: 4
    Media Servers:
      style: column
  #    columns: 2
  #  Server Utils:
  #    style: row
  #    columns: 4
    Download Tools:
      style: row
      columns: 4
    Docker Utils:
      style: column
  #   columns: 4
    Network:
      style: column
  #    columns: 4
    DBs:
      style: row
      columns: 4
    Misc:
      style: row
      columns: 4

homepage_widgets_yaml:
  - search:
      provider: google # google, duckduckgo, bing, baidu, brave or custom
      focus: true # Optional, will set focus to the search bar on page load
      target: _blank # One of _self, _blank, _parent or _top
  - greeting:
      text_size: xl
      text: "{{ ansible_nas_hostname }}"
  - datetime:
      text_size: xl # Valid text sizes are 4xl, 3xl, 2xl, xl, md, sm, xs
      format:
        timeStyle: short
        hour12: true
        dateStyle: short
  - resources:
      cpu: true
      memory: true
      cputemp: true
      uptime: true
      units: metric # only used by cpu temp
      refresh: 60000 # optional, in ms
