---
- name: Start {{ ansible_nas_app_name }}
  block:
    - name: Create {{ ansible_nas_app_name }} Container
      community.docker.docker_container:
        container_default_behavior: "compatibility"
        name: "{{ autoheal_container_name }}"
        hostname: "{{ autoheal_container_name }}"
        image: "{{ autoheal_image_name }}:{{ autoheal_image_tag }}"
        pull: true
        cpu_shares: "{{ autoheal_cpu_shares }}"
        network_mode: "none"
        env:
          AUTOHEAL_CONTAINER_LABEL: "autoheal"
          AUTOHEAL_INTERVAL: "10"
          AUTOHEAL_START_PERIOD: "30"
          AUTOHEAL_DEFAULT_STOP_TIMEOUT: "10"
          AUTOHEAL_ONLY_MONITOR_RUNNING: "true"
          TZ: "{{ ansible_nas_timezone }}"
        volumes:
          - "/etc/localtime:/etc/localtime:ro"
          - "/var/run/docker.sock:/var/run/docker.sock"
        labels:
          autoheal: "{{ autoheal_autoheal }}"
          com.centurylinklabs.watchtower.monitor-only: "{{ autoheal_watchtower_monitor_only }}"
          homepage.name: "{{ ansible_nas_app_name }}"
          homepage.group: "{{ autoheal_homepage_group }}"
          homepage.icon: "{{ autoheal_homepage_icon }}"
          homepage.description: "{{ 'Monitor and restart unhealthy docker containers.' if homepage_show_description else omit }}"
          homepage.server: "my-docker"
          homepage.container: "{{ autoheal_container_name }}"
          homepage.showStats: "{{ autoheal_homepage_showStats }}"
          traefik.enable: "false"
          wud.tag.include: '^\d+\.\d+\.\d+$$'
          wud.link.template: "https://github.com/willfarrell/docker-autoheal/releases/tag/$${major}.$${minor}.$${patch}"
        memory: "{{ autoheal_memory }}"
        restart_policy: unless-stopped
  when: autoheal_enabled is true

- name: Stop {{ ansible_nas_app_name }}
  block:
    - name: Stop {{ ansible_nas_app_name }} Container
      community.docker.docker_container:
        name: "{{ autoheal_container_name }}"
        state: absent
  when: autoheal_enabled is false
