---
- name: Start Telegraf
  block:
    - name: Create Telegraf Directory
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
      with_items:
        - "{{ stats_telegraf_data_directory }}"
        - "{{ stats_telegraf_data_directory }}/data"

    - name: Template telegraf.conf
      ansible.builtin.template:
        src: telegraf.conf.j2
        dest: "{{ stats_telegraf_data_directory }}/data/telegraf.conf"
      register: telegraf_config

    - name: Get Docker daemon uid
      ansible.builtin.command: stat -c '%g' /var/run/docker.sock
      register: docker_uid
      changed_when: false

    - name: Telegraf Docker Container
      community.docker.docker_container:
        name: "{{ stats_telegraf_container_name }}"
        hostname: "{{ stats_telegraf_container_name }}"
        image: "{{ stats_telegraf_image_name }}:{{ stats_telegraf_image_version }}"
        pull: true
        privileged: true
        ipc_mode: host
        ports:
          - "{{ stats_telegraf_influxdb_port }}:8086"
          - "{{ stats_telegraf_port }}:9273"
        user: "telegraf:{{ docker_uid.stdout }}"
        volumes:
          - "{{ stats_telegraf_data_directory }}/data:/etc/telegraf/:ro"
          - "/var/run/docker.sock:/var/run/docker.sock:ro"
          - "/:/hostfs:ro"
          - "/etc:/hostfs/etc:ro"
          - "/proc:/hostfs/proc:ro"
          - "/sys:/hostfs/sys:ro"
          - "/var:/hostfs/var:ro"
          - "/run:/hostfs/run:ro"
        env:
          HOST_ETC: "/hostfs/etc"
          HOST_PROC: "/hostfs/proc"
          HOST_SYS: "/hostfs/sys"
          HOST_VAR: "/hostfs/var"
          HOST_RUN: "/hostfs/run"
          HOST_MOUNT_PREFIX: "/hostfs"
          TZ: "{{ ansible_nas_timezone }}"
        restart: "{{ telegraf_config is changed }}"
        labels:
          autoheal: "{{ stats_telegraf_autoheal }}"
          com.centurylinklabs.watchtower.enable: "{{ stats_telegraf_watchtower_enable }}"
          dockflare.enable: "false"
          homepage.name: "Telegraf"
          homepage.group: "{{ stats_telegraf_homepage_group }}"
          homepage.icon: "{{ stats_telegraf_homepage_icon }}"
          homepage.description: "{{ 'Agent for collecting, processing, aggregating, and writing metrics, logs, and other arbitrary data.' if homepage_show_description else omit }}"
          homepage.server: "my-docker"
          homepage.container: "{{ stats_telegraf_container_name }}"
          homepage.showStats: "{{ stats_telegraf_homepage_showstats }}"
          traefik.enable: "false"
          wud.tag.include: '^\d+\.\d+\.\d+.*$'
          wud.tag.transform.type: "semver"
          wud.link.template: "https://hub.docker.com/_/telegraf"
        cpu_shares: "{{ telegraf_cpu_shares }}"
        memory: "{{ telegraph_memory}}"
        restart_policy: unless-stopped
  when: stats_enabled is true

- name: Stop Telegraf
  block:
    - name: Stop stats_telegraf
      community.docker.docker_container:
        name: "{{ stats_telegraf_container_name }}"
        state: absent
  when: stats_enabled is false

- name: Data Archive Telegraf
  block:
    - name: Check for Telegraf Data Directory
      stat:
        path: "{{ stats_telegraf_data_directory }}"
      register: dir_stat

    - name: Archive Telegraf Data Directory
      ansible.builtin.archive:
        path: "{{ stats_telegraf_data_directory }}"
        dest: "{{ docker_home }}/telegraf.zip"
        force_archive: true
        format: zip
        owner: ansible-nas
        group: ansible-nas
        mode: u=rw,g=rw
        remove: true
      when: dir_stat.stat.exists
  when: stats_enabled is false and archive_app_data_enabled is true
