---
- name: Start {{ ansible_nas_app_name }}
  block:
    - name: Create {{ ansible_nas_app_name }} Directories
      ansible.builtin.file:
        path: "{{ route53_data_directory }}"
        state: directory

    - name: Generate {{ ansible_nas_app_name }} config file
      ansible.builtin.template:
        src: config.yml
        dest: "{{ route53_data_directory }}/ddns-route53.yml"
      register: template_config

    - name: Create {{ ansible_nas_app_name }} Container
      community.docker.docker_container:
        name: "{{ route53_container_name }}"
        hostname: "{{ route53_container_name }}"
        image: "{{ route53_image_name }}:{{ route53_image_version }}"
        pull: true
        env:
          SCHEDULE: "{{ route53_schedule | string }}"
        volumes:
          - "{{ route53_data_directory }}/ddns-route53.yml:/etc/ddns-route53/ddns-route53.yml"
        restart_policy: unless-stopped
        cpu_shares: "{{ route53_cpu_shares }}"
        memory: "{{ route53_memory }}"
        recreate: "{{ template_config is changed }}"
        labels:
          autoheal: "{{ route53_autoheal }}"
          com.centurylinklabs.watchtower.monitor-only: "{{ route53_watchtower_monitor_only }}"
  when: route53_enabled is true

- name: Stop {{ ansible_nas_app_name }}
  block:
    - name: Stop {{ ansible_nas_app_name }} Container
      community.docker.docker_container:
        name: "{{ route53_container_name }}"
        state: absent
  when: route53_enabled is false

- name: Data Archive {{ ansible_nas_app_name }}
  block:
    - name: Check for {{ ansible_nas_app_name }} Data Directory
      stat:
        path: "{{ route53_data_directory }}"
      register: dir_stat

    - name: Archive {{ ansible_nas_app_name }} Data Directory
      ansible.builtin.archive:
        path: "{{ route53_data_directory }}"
        dest: "{{ docker_home }}/{{ ansible_nas_app_name | lower }}.zip"
        force_archive: true
        format: zip
        owner: ansible-nas
        group: ansible-nas
        mode: u=rw,g=rw
        remove: true
      when: dir_stat.stat.exists
  when: route53_enabled is false and archive_app_data_enabled is true
