---
- name: Start {{ ansible_nas_app_name }}
  block:
    - name: Create {{ ansible_nas_app_name }} Container
      community.docker.docker_container:
        container_default_behavior: "compatibility"
        name: "{{ striparr_container_name }}"
        hostname: "{{ striparr_container_name }}"
        image: "{{ striparr_image_name }}:{{ striparr_image_tag }}"
        pull: true
        volumes:
          - "{{ tv_root }}:/path/to/tv:rw"
          - "{{ movies_root }}:/path/to/movies:rw"
        network_mode: bridge
        env:
          PUID: "{{ striparr_puid }}"
          PGID: "{{ striparr_pgid }}"
          TZ: "{{ ansible_nas_timezone }}"
        labels:
          autoheal: "{{ striparr_autoheal | string }}"
          com.centurylinklabs.watchtower.enable: "{{ striparr_watchtower_enabled| string }}"
          dockflare.enable: "false"
          homepage.name: "{{ ansible_nas_app_name }}"
          homepage.group: "{{ striparr_homepage_group }}"
          homepage.icon: "{{ striparr_homepage_icon }}"
          homepage.description: "{{ 'Strips metadata from files downloaded by Sonarr and Radarr.' if homepage_show_description else omit }}"
          homepage.server: "my-docker"
          homepage.container: "{{ striparr_container_name }}"
          homepage.showStats: "{{ striparr_homepage_showstats | string }}"
          repliqate.enabled: "false"
          traefik.enable: "false"
          wud.watch.digest: "true"
          wud.link.template: "https://github.com/mikenye/docker-striparr/pkgs/container/docker-striparr"
        cpu_shares: "{{ striparr_cpu_shares }}"
        memory: "{{ striparr_memory }}"
        memory_swap: "{{ striparr_memory_swap }}"
        restart_policy: unless-stopped
  when: striparr_enabled is true

- name: Stop {{ ansible_nas_app_name }}
  block:
    - name: Stop {{ ansible_nas_app_name }} Container
      community.docker.docker_container:
        name: "{{ striparr_container_name }}"
        state: absent
  when: striparr_enabled is false

- name: Data Archive {{ ansible_nas_app_name }}
  include_role:
    name: ansible-nas-archive
  vars:
    target_data_dir: "{{ striparr_data_directory }}"
  when:
    - archive_app_data_enabled is true
    - striparr_enabled is false