---
- name: Start {{ ansible_nas_app_name }}
  block:
    - name: Create {{ ansible_nas_app_name }} Directories
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
      with_items:
        - "{{ onlyoffice_data_directory }}/data"
        - "{{ onlyoffice_data_directory }}/logs"

    - name: Set {{ ansible_nas_app_name }} FQDN var overrides
      ansible.builtin.set_fact:
        onlyoffice_homepage_href: "https://{{ onlyoffice_hostname }}.{{ ansible_nas_domain }}"
      when: onlyoffice_traefik_enabled | bool or onlyoffice_dockflare_enabled | bool

    - name: Create {{ ansible_nas_app_name }} Network
      community.docker.docker_network:
        name: "{{ nextcloud_network_name }}"

    - name: Create {{ ansible_nas_app_name }} Container
      community.docker.docker_container:
        container_default_behavior: "compatibility"
        name: "{{ onlyoffice_container_name }}"
        hostname: "{{ onlyoffice_container_name }}"
        image: "{{ onlyoffice_image_name }}:{{ onlyoffice_image_tag }}"
        pull: true
        networks:
          - name: "{{ nextcloud_network_name }}"
        network_mode: "{{ nextcloud_network_name }}"
        networks_cli_compatible: "yes"
        volumes:
          - "{{ onlyoffice_data_directory }}/data:/var/www/onlyoffice/Data"
          - "{{ onlyoffice_data_directory }}/logs:/var/log/onlyoffice"
        env:
          JWT_SECRET: "{{ onlyoffice_env_jwt_secret }}"
          USE_UNAUTHORIZED_STORAGE: "{{ onlyoffice_env_use_unauthorized_storage }}"
          TZ: "{{ ansible_nas_timezone }}"
        ports:
          - "{{ onlyoffice_port_http }}:80"
          - "5222:5222" # ONLYOFFICE Talk (XMPP client connections)
        labels:
          autoheal: "{{ onlyoffice_autoheal_enabled | ternary('true', 'false') }}"
          com.centurylinklabs.watchtower.enable: "{{ onlyoffice_watchtower_enabled | ternary('true', 'false') }}"
          dockflare.enable: "{{ onlyoffice_dockflare_enabled | ternary('true', 'false') }}"
          dockflare.access.group: "{{ onlyoffice_dockflare_access_group }}"
          dockflare.hostname: "{{ onlyoffice_hostname }}.{{ ansible_nas_domain }}"
          dockflare.service: "http://{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}:{{ onlyoffice_port_http }}"
          homepage.name: "{{ ansible_nas_app_name }}"
          homepage.group: "{{ onlyoffice_homepage_group }}"
          homepage.icon: "{{ onlyoffice_homepage_icon }}"
          homepage.href: "{{ onlyoffice_homepage_href }}"
          homepage.siteMonitor: "http://{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}:{{ onlyoffice_port_http }}"
          homepage.description: "{{ 'A free and open source office and productivity suite' if homepage_show_description else omit }}"
          homepage.server: "my-docker"
          homepage.container: "{{ onlyoffice_container_name }}"
          homepage.showStats: "{{ onlyoffice_homepage_showstats | ternary('true', 'false') }}"
          repliqate.enabled: "{{ onlyoffice_repliqate_enabled | ternary('true', 'false') }}"
          repliqate.engine: "{{ onlyoffice_repliqate_engine }}"
          repliqate.schedule: "{{ onlyoffice_repliqate_schedule }}"
          repliqate.backup_id: "{{ onlyoffice_repliqate_backup_id }}"
          repliqate.retention: "{{ onlyoffice_repliqate_retention }}"
          traefik.enable: "{{ onlyoffice_traefik_enabled | ternary('true', 'false') }}"
          traefik.http.routers.onlyoffice.rule: "Host(`{{ onlyoffice_hostname }}.{{ ansible_nas_domain }}`)"
          traefik.http.routers.onlyoffice.tls.certresolver: "letsencrypt"
          traefik.http.routers.onlyoffice.tls.domains[0].main: "{{ ansible_nas_domain }}"
          traefik.http.routers.onlyoffice.tls.domains[0].sans: "*.{{ ansible_nas_domain }}"
          traefik.http.routers.onlyoffice.middlewares: "onlyoffice-headers@docker,onlyoffice@docker{{ ',tinyauth-auth@docker' if onlyoffice_tinyauth_enabled | bool else '' }}"
          traefik.http.middlewares.onlyoffice-headers.headers.customrequestheaders.X-Forwarded-Proto: "https"
          traefik.http.middlewares.onlyoffice-headers.headers.accessControlAllowOriginList: "*"
          traefik.http.middlewares.onlyoffice.IPAllowList.sourcerange: "{{ onlyoffice_traefik_whitelist }}"
          traefik.http.services.onlyoffice.loadbalancer.passhostheader: "true"
          traefik.http.services.onlyoffice.loadbalancer.server.port: "80"
          wud.tag.include: '^\d+\.\d+\.\d+.*$'
          wud.tag.transform.type: "semver"
          wud.link.template: "https://hub.docker.com/r/onlyoffice/documentserver"
        cpu_shares: "{{ onlyoffice_cpu_shares }}"
        memory: "{{ onlyoffice_memory }}"
        memory_swap: "{{ onlyoffice_memory_swap }}"
        restart_policy: unless-stopped

    - name: Access {{ ansible_nas_app_name }} at
      ansible.builtin.debug:
        msg: >-
              {{
                ['http://' + hostvars[inventory_hostname]['ansible_default_ipv4']['address'] + ':' + (onlyoffice_port_http | string)] +
                (['https://' + onlyoffice_hostname + '.' + ansible_nas_domain] if (onlyoffice_traefik_enabled is true or onlyoffice_dockflare_enabled is true) else [])
              }}
  when: onlyoffice_enabled is true

- name: Stop {{ ansible_nas_app_name }}
  block:
    - name: Stop {{ ansible_nas_app_name }} Container
      community.docker.docker_container:
        name: "{{ onlyoffice_container_name }}"
        state: absent
  when: onlyoffice_enabled is false

- name: Data Archive {{ ansible_nas_app_name }}
  include_role:
    name: ansible-nas-archive
  vars:
    target_data_dir: "{{ onlyoffice_data_directory }}"
  when:
    - archive_app_data_enabled is true
    - onlyoffice_enabled is false