---
- name: Start {{ pornvault_proper_name }}
  block:
    - name: Create {{ pornvault_proper_name }} Directories
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
      with_items:
        - "{{ pornvault_data_directory }}"
        - "{{ pornvault_data_directory }}/config"
        - "{{ pornvault_porn_images_directory }}"
        - "{{ pornvault_porn_videos_directory }}"

    - name: Set {{ pornvault_proper_name }} FQDN var overrides
      ansible.builtin.set_fact:
        pornvault_homepage_href: "https://{{ pornvault_hostname }}.{{ ansible_nas_domain }}"
      when: pornvault_traefik_enabled | bool or pornvault_dockflare_enabled | bool

    - name: Create {{ pornvault_proper_name }} Container
      community.docker.docker_container:
        container_default_behavior: "compatibility"
        name: "{{ pornvault_container_name }}"
        hostname: "{{ pornvault_container_name }}"
        image: "{{ pornvault_image_name }}:{{ pornvault_image_tag }}"
        pull: true
        volumes:
          - "/etc/localtime:/etc/localtime:ro"
          - "{{ pornvault_data_directory }}/config:/config:rw"
          - "{{ pornvault_porn_images_directory }}:/images:ro"
          - "{{ pornvault_porn_videos_directory }}:/videos:ro"
        ports:
          - "{{ pornvault_port_http }}:3000"
        labels:
          autoheal: "{{ pornvault_autoheal_enabled | ternary('true', 'false') }}"
          com.centurylinklabs.watchtower.enable: "{{ pornvault_watchtower_enabled | ternary('true', 'false') }}"
          dockflare.enable: "{{ pornvault_dockflare_enabled | ternary('true', 'false') }}"
          dockflare.access.group: "{{ pornvault_dockflare_access_group }}"
          dockflare.hostname: "{{ pornvault_hostname }}.{{ ansible_nas_domain }}"
          dockflare.service: "http://{{ hostvars[inventory_hostname]['ansible_facts']['default_ipv4']['address'] }}:{{ pornvault_port_http }}"
          homepage.name: "{{ pornvault_proper_name }}"
          homepage.group: "{{ pornvault_homepage_group }}"
          homepage.icon: "{{ pornvault_homepage_icon }}"
          homepage.href: "{{ pornvault_homepage_href }}"
          homepage.siteMonitor: "http://{{ hostvars[inventory_hostname]['ansible_facts']['default_ipv4']['address'] }}:{{ pornvault_port_http }}"
          homepage.description: "{{ 'Porn-Vault is a self hosted organizer for adult videos and imagery.' if homepage_show_description else omit }}"
          homepage.server: "my-docker"
          homepage.container: "{{ pornvault_container_name }}"
          homepage.showStats: "{{ pornvault_homepage_showstats | ternary('true', 'false') }}"
          repliqate.enabled: "{{ pornvault_repliqate_enabled | ternary('true', 'false') }}"
          repliqate.engine: "{{ pornvault_repliqate_engine }}"
          repliqate.schedule: "{{ pornvault_repliqate_schedule }}"
          repliqate.backup_id: "{{ pornvault_repliqate_backup_id }}"
          repliqate.retention: "{{ pornvault_repliqate_retention }}"
          traefik.enable: "{{ pornvault_traefik_enabled | ternary('true', 'false') }}"
          traefik.http.routers.pornvault.rule: "Host(`{{ pornvault_hostname }}.{{ ansible_nas_domain }}`)"
          traefik.http.routers.pornvault.tls.certresolver: "letsencrypt"
          traefik.http.routers.pornvault.tls.domains[0].main: "{{ ansible_nas_domain }}"
          traefik.http.routers.pornvault.tls.domains[0].sans: "*.{{ ansible_nas_domain }}"
          traefik.http.routers.pornvault.middlewares: "pornvault@docker{{ ',tinyauth-auth@docker' if pornvault_tinyauth_enabled | bool else '' }}"
          traefik.http.middlewares.pornvault.IPAllowList.sourcerange: "{{ pornvault_traefik_whitelist }}"
          traefik.http.services.pornvault.loadbalancer.server.port: "3000"
          wud.watch.digest: "true"
          wud.tag.include: ^alpine-edge$
          wud.link.template: https://gitlab.com/porn-vault/porn-vault/-/commits/master
        cpu_shares: "{{ pornvault_cpu_shares }}"
        memory: "{{ pornvault_memory }}"
        memory_swap: "{{ pornvault_memory_swap }}"
        restart_policy: unless-stopped

    - name: Access {{ pornvault_proper_name }} at
      ansible.builtin.debug:
        msg: >-
              {{
                ['http://' + hostvars[inventory_hostname]['ansible_facts']['default_ipv4']['address'] + ':' + (pornvault_port_http | string)] +
                (['https://' + pornvault_hostname + '.' + ansible_nas_domain] if (pornvault_traefik_enabled is true or pornvault_dockflare_enabled is true) else [])
              }}
  when: pornvault_enabled is true

- name: Stop {{ pornvault_proper_name }}
  block:
    - name: Stop {{ pornvault_proper_name }} Container
      community.docker.docker_container:
        name: "{{ pornvault_container_name }}"
        state: absent
  when: pornvault_enabled is false

- name: Data Archive {{ pornvault_proper_name }}
  include_role:
    name: ansible-nas-archive
  vars:
    target_data_dir: "{{ pornvault_data_directory }}"
  when:
    - archive_app_data_enabled is true
    - pornvault_enabled is false