---
- name: Start {{ ansible_nas_app_name }}
  block:
    - name: Create {{ ansible_nas_app_name }} Directories
      file:
        path: "{{ item }}"
        state: directory
      with_items:
        - "{{ pornvault_data_directory }}"
        - "{{ pornvault_data_directory }}/config"

    - name: Create {{ ansible_nas_app_name }} Container
      community.docker.docker_container:
        container_default_behavior: "compatibility"
        name: "{{ pornvault_container_name }}"
        hostname: "{{ pornvault_container_name }}"
        image: "{{ pornvault_image_name }}:{{ pornvault_image_tag }}"
        pull: true
        volumes:
          - "/etc/localtime:/etc/localtime:ro"
          - "{{ pornvault_data_directory }}/config:/config:rw"
          - "{{ porn_root }}:/videos:ro"
          - "{{ porn_root }}/pix:/images:ro"
        ports:
          - "{{ pornvault_port_http }}:3000"
        labels:
          autoheal: "{{ pornvault_autoheal }}"
          com.centurylinklabs.watchtower.enable: "{{ pornvault_watchtower_enable }}"
          dockflare.enable: "{{ pornvault_dockflare_tunnel }}"
          dockflare.access.group: "{{ pornvault_dockflare_access_group }}"
          dockflare.hostname: "{{ pornvault_hostname }}.{{ ansible_nas_domain }}"
          dockflare.service: "http://{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}:{{ pornvault_port_http }}"
          homepage.name: "{{ ansible_nas_app_name }}"
          homepage.group: "{{ pornvault_homepage_group }}"
          homepage.icon: "{{ pornvault_homepage_icon }}"
          homepage.href: "{{ pornvault_homepage_href }}"
          homepage.siteMonitor: "http://{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}:{{ pornvault_port_http }}"
          homepage.description: "{{ 'Porn-Vault is a self hosted organizer for adult videos and imagery.' if homepage_show_description else omit }}"
          homepage.server: "my-docker"
          homepage.container: "{{ pornvault_container_name }}"
          homepage.showStats: "{{ pornvault_homepage_showstats }}"
          traefik.enable: "{{ pornvault_available_externally | string }}"
          traefik.http.routers.pornvault.rule: "Host(`pornvault.{{ ansible_nas_domain }}`)"
          traefik.http.routers.pornvault.tls.certresolver: "letsencrypt"
          traefik.http.routers.pornvault.tls.domains[0].main: "{{ ansible_nas_domain }}"
          traefik.http.routers.pornvault.tls.domains[0].sans: "*.{{ ansible_nas_domain }}"
          traefik.http.routers.frontend.middlewares: "{{ pornvault_hostname }}"
          traefik.http.routers.pornvault.middlewares: "{{ pornvault_hostname }}@docker"
          traefik.http.middlewares.pornvault.IPAllowList.sourcerange: "{{ pornvault_traefik_whitelist }}"
          traefik.http.services.pornvault.loadbalancer.server.port: "3000"
          wud.tag.include: '^v?\d+\.\d+\.\d+.*$'
          wud.tag.transform.type: "semver"
          wud.link.template: "https://hub.docker.com/r/boi12321/porn-vault"
        cpu_shares: "{{ pornvault_cpu_shares }}"
        memory: "{{ pornvault_memory }}"
        restart_policy: unless-stopped

    - name: Access {{ ansible_nas_app_name }} at
      ansible.builtin.debug:
        msg: >-
              {{
                ['http://' + hostvars[inventory_hostname]['ansible_default_ipv4']['address'] + ':' + (pornvault_port_http | string)] +
                (['https://' + pornvault_hostname + '.' + ansible_nas_domain] if (pornvault_available_externally is true or pornvault_dockflare_tunnel is true) else [])
              }}
  when: pornvault_enabled is true

- name: Stop {{ ansible_nas_app_name }}
  block:
    - name: Stop {{ ansible_nas_app_name }} Container
      community.docker.docker_container:
        name: "{{ pornvault_container_name }}"
        state: absent
  when: pornvault_enabled is false

- name: Data Archive {{ ansible_nas_app_name }}
  block:
    - name: Check for {{ ansible_nas_app_name }} Data Directory
      stat:
        path: "{{ pornvault_data_directory }}"
      register: dir_stat

    - name: Archive {{ ansible_nas_app_name }} Data Directory
      ansible.builtin.archive:
        path: "{{ pornvault_data_directory }}"
        dest: "{{ docker_home }}/{{ ansible_nas_app_name | lower }}.zip"
        force_archive: true
        format: zip
        owner: ansible-nas
        group: ansible-nas
        mode: u=rw,g=rw
        remove: true
      when: dir_stat.stat.exists
  when: pornvault_enabled is false and archive_app_data_enabled is true
