---
- name: Install Usermin
  ansible.builtin.apt:
    name: usermin
    state: present
    update_cache: yes
  when: usermin_enabled is true

- name: Start Usermin service
  ansible.builtin.service:
    name: usermin
    state: started
    enabled: true
  when: usermin_enabled is true

- name: Access Usermin at
  ansible.builtin.debug:
    msg: >-
          {{
            ['http://' + hostvars[inventory_hostname]['ansible_facts']['default_ipv4']['address'] + ':' + (usermin_port_http | string)]
          }}
  when: usermin_enabled is true

- name: Uninstall Usermin
  ansible.builtin.apt:
    name: usermin
    state: absent
    autoremove: yes
  when: usermin_enabled is false