---
- name: Start Docker setup for Ubuntu 22.04 LTS
  block:
    - name: Install python3-pip
      ansible.builtin.apt:
        name: python3-pip
        state: present
      register: result
      until: result is succeeded

    - name: Remove docker-py python module
      ansible.builtin.pip:
        name: docker-py
        state: absent
      register: result
      until: result is succeeded

    - name: Install docker python module
      ansible.builtin.pip:
        name: docker
        state: present
      register: result
      until: result is succeeded
  when: (ansible_distribution == "Ubuntu") and (ansible_distribution_version == "22.04")

- name: Create Docker home directory
  ansible.builtin.file:
    path: "{{ docker_home }}"
    mode: 0755
    state: directory

- name: Add {{ ansible_nas_user }} to docker group
  ansible.builtin.user:
    name: "{{ ansible_nas_user }}"
    state: present
    groups: docker
    append: yes

- name: Check for NVIDIA driver
  ansible.builtin.stat:
    path: /usr/bin/nvidia-smi
  register: nvidia_smi
  check_mode: false
  when: nvidia_runtime_enabled is true

- name: Check for NVIDIA Container Runtime
  ansible.builtin.stat:
    path: /usr/bin/nvidia-container-runtime
  register: nvidia_runtime_executable
  check_mode: false
  when: nvidia_runtime_enabled is true

- name: Warn if NVIDIA drivers are not installed for NVIDIA Container Runtime
  ansible.builtin.pause:
    prompt: |
      ** ANE cannot install the NVIDIA Container Runtime.
      ** You must install the NVIDIA driver first.
      ** Set nvidia_runtime_enabled: false or containers relying on it will fail.
      ** Press ENTER to continue or CTRL+C and A to abort...
  when: (not nvidia_smi.stat.exists) and (nvidia_runtime_enabled is true)

# how to install NVIDIA drivers
# https://documentation.ubuntu.com/server/how-to/graphics/install-nvidia-drivers/

# how to install NVIDIA Container Toolkit
# https://docs.nvidia.com/datacenter/cloud-native/container-toolkit/latest/install-guide.html

- name: Install NVIDIA Container Runtime
  # This can be better done using ansible.builtin.apt_repository
  # https://docs.ansible.com/ansible/latest/collections/ansible/builtin/apt_key_module.html
  block:
    - name: Add NVIDIA Container Toolkit GPG key
      ansible.builtin.shell: |
        curl -fsSL https://nvidia.github.io/libnvidia-container/gpgkey | sudo gpg --dearmor -o /usr/share/keyrings/nvidia-container-toolkit-keyring.gpg
      args:
        creates: /usr/share/keyrings/nvidia-container-toolkit-keyring.gpg

    - name: Add NVIDIA Container Toolkit repository to APT sources
      ansible.builtin.shell: |
        curl -s -L https://nvidia.github.io/libnvidia-container/stable/deb/nvidia-container-toolkit.list | \
        sed 's#deb https://#deb [signed-by=/usr/share/keyrings/nvidia-container-toolkit-keyring.gpg] https://#g' | \
        sudo tee /etc/apt/sources.list.d/nvidia-container-toolkit.list
      args:
        creates: /etc/apt/sources.list.d/nvidia-container-toolkit.list

    - name: Install NVIDIA Container Runtime packages
      ansible.builtin.apt:
        pkg:
          - nvidia-container-toolkit
          - nvidia-container-toolkit-base
          - libnvidia-container-tools
          - libnvidia-container1
        update_cache: yes
        state: present
  when: (nvidia_runtime_enabled is true) and (nvidia_smi.stat.exists) and (not nvidia_runtime_executable.stat.exists)

- name: Generate Docker daemon.json
  ansible.builtin.copy:
    dest: /etc/docker/daemon.json
    content: "{{ docker_daemon_json | to_nice_json }}"
  register: docker_config
  when: (nvidia_runtime_enabled is false) or (not nvidia_smi.stat.exists)

- name: Generate Docker daemon.json with NVIDIA runtime
  ansible.builtin.copy:
    dest: /etc/docker/daemon.json
    content: "{{ docker_daemon_with_nvidia_json | to_nice_json }}"
  register: docker_config
  when: (nvidia_runtime_enabled is true) and (nvidia_smi.stat.exists) and (nvidia_runtime_executable.stat.exists)

- name: Remove NVIDIA Container Runtime packages
  ansible.builtin.apt:
    pkg:
      - nvidia-container-toolkit
      - nvidia-container-toolkit-base
      - libnvidia-container-tools
      - libnvidia-container1
    update_cache: no
    state: absent
  when: (nvidia_runtime_enabled is false) or (not nvidia_smi.stat.exists)

- name: Restart Docker
  ansible.builtin.service:
    name: docker
    state: restarted
  when: docker_config.changed
