---
- name: Start Docker setup for Ubuntu 22.04 LTS
  block:
    - name: (Ubuntu 22.04 LTS) Install python3-pip
      ansible.builtin.apt:
        name: python3-pip
        state: present
      register: result
      until: result is succeeded

    - name: (Ubuntu 22.04 LTS) Remove docker-py python module
      ansible.builtin.pip:
        name: docker-py
        state: absent
      register: result
      until: result is succeeded

    - name: (Ubuntu 22.04 LTS) Install docker python module
      ansible.builtin.pip:
        name: docker
        state: present
      register: result
      until: result is succeeded
  when: 
    - ansible_facts['distribution'] == "Ubuntu"
    - ansible_facts['distribution_version'] == "22.04"

- name: Create docker_home directory
  ansible.builtin.file:
    path: "{{ docker_home }}"
    mode: 0755
    state: directory

- name: Add {{ ansible_nas_user }} to docker group
  ansible.builtin.user:
    name: "{{ ansible_nas_user }}"
    state: present
    groups: docker
    append: yes

##### BEGIN NVIDIA STUFF #####

- name: Check for NVIDIA GPU
  ansible.builtin.command: "lspci -d 10de::0300"
  register: nvidia_gpu_check
  changed_when: false
  failed_when: false

- name: Report NVIDIA GPU Status
  ansible.builtin.debug:
    msg: "{{ 'NVIDIA GPU detected: ' + nvidia_gpu_check.stdout if nvidia_gpu_check.stdout | length > 0 else 'No NVIDIA GPU detected.' }}"

- name: Set nvidia_runtime_enabled based on hardware detection
  ansible.builtin.set_fact:
    nvidia_runtime_enabled: "{{ nvidia_gpu_check.stdout | length > 0 }}"

- name: Install NVIDIA driver
  block:
    - name: Install NVIDIA driver ({{ nvidia_driver_ver }})
      ansible.builtin.apt:
        name: "{{ nvidia_driver_ver }}"
        state: present
      register: nvidia_driver_result
      until: nvidia_driver_result is succeeded

    - name: Notify if reboot required for NVIDIA driver
      ansible.builtin.debug:
        msg:
          - "SYSTEM NOTIFICATION: NVIDIA drivers have been installed."
          - "A manual reboot is REQUIRED."
      when: nvidia_driver_result.changed

    - name: Check NVIDIA driver is running
      ansible.builtin.command: nvidia-smi
      register: nvidia_smi_result
      changed_when: false
      failed_when: false

    - name: Disable NVIDIA Container Runtime if driver fails
      ansible.builtin.set_fact:
        nvidia_runtime_enabled: false
      when: nvidia_smi_result.rc != 0
  when: nvidia_runtime_enabled | bool

- name: Manage NVIDIA Container Runtime
  block:
    - name: Check for NVIDIA Container Runtime binary
      ansible.builtin.stat:
        path: /usr/bin/nvidia-container-runtime
      register: nvidia_runtime_presence

    - name: Install NVIDIA Container Toolkit
      block:
        - name: Download NVIDIA Container Toolkit GPG key
          ansible.builtin.get_url:
            url: https://nvidia.github.io/libnvidia-container/gpgkey
            dest: /usr/share/keyrings/nvidia-container-toolkit-keyring.gpg
            mode: '0644'

        - name: Add NVIDIA Container Toolkit repository
          ansible.builtin.apt_repository:
            repo: "deb [signed-by=/usr/share/keyrings/nvidia-container-toolkit-keyring.gpg] https://nvidia.github.io/libnvidia-container/stable/deb/{{ 'amd64' if ansible_facts['architecture'] == 'x86_64' else ansible_facts['architecture'] }} /"
            filename: nvidia-container-toolkit
            state: present
            update_cache: yes

        - name: Install NVIDIA Container Runtime packages
          ansible.builtin.apt:
            pkg:
              - nvidia-container-toolkit
            state: present
      when: not nvidia_runtime_presence.stat.exists

    - name: Generate Docker daemon.json with NVIDIA runtime
      ansible.builtin.copy:
        dest: /etc/docker/daemon.json
        content: "{{ docker_daemon_with_nvidia_json | to_nice_json }}"
      register: docker_config_nvidia
  when: nvidia_runtime_enabled | bool

- name: Remove NVIDIA Container Runtime if hardware not present
  ansible.builtin.apt:
    pkg:
      - nvidia-container-toolkit
      - libnvidia-container-tools
    state: absent
  when: not (nvidia_runtime_enabled | bool)

##### END NVIDIA STUFF #####

- name: Generate Docker daemon.json
  ansible.builtin.copy:
    dest: /etc/docker/daemon.json
    content: "{{ docker_daemon_json | to_nice_json }}"
  register: docker_config
  when: nvidia_runtime_enabled is false

- name: Restart Docker
  ansible.builtin.service:
    name: docker
    state: restarted
  when: (docker_config.changed) or (nvidia_runtime_enabled | bool and docker_config_nvidia.changed)
