---
# ANE
ansible_nas_app_name: "Netdata"
netdata_enabled: false
netdata_traefik_enabled: false
netdata_traefik_whitelist: "{{ lan }}"

# directories
netdata_data_directory: "{{ docker_home }}/netdata"

# network
netdata_hostname: "netdata"
netdata_port_http: "19999"

# docker
netdata_container_name: "netdata"
netdata_image_name: "ghcr.io/netdata/netdata"
#netdata_image_version: "latest"
netdata_image_version: "stable"

# specs
netdata_cpu_shares: 1024
netdata_memory: "1G"
netdata_memory_swap: -1

# app
netdata_env_netdata_extra_deb_packages: "" # apcupsd, lm-sensors
# Below to variables are for future use
#netdata_mariadb_monitoring_password: ""
#netdata_postgres_monitoring_password: ""

# autoheal
netdata_autoheal_enabled: false

# dockflare
netdata_dockflare_enabled: false
netdata_dockflare_access_group: ""

# healthcheck
netdata_healthcheck_test: ["CMD-SHELL", "curl -f http://127.0.0.1:19999/api/v1/info || exit 1"]
netdata_healthcheck_interval: 30s
netdata_healthcheck_timeout: 10s
netdata_healthcheck_retries: 3
netdata_healthcheck_start_period: 20s

# homepage
netdata_homepage_group: "Apps"
netdata_homepage_icon: "netdata.png"
netdata_homepage_href: "http://{{ hostvars[inventory_hostname]['ansible_facts']['default_ipv4']['address'] }}:{{ netdata_port_http }}/v3"
netdata_homepage_showstats: false

# tinyauth
netdata_tinyauth_enabled: false

# watchtower
netdata_watchtower_enabled: false
