---
# ANE
ansible_nas_app_name: "WatchYourLAN"
watchyourlan_enabled: false
watchyourlan_available_externally: false
watchyourlan_traefik_whitelist: "{{ lan }}"
watchyourlan_data_directory: "{{ docker_home }}/watchyourlan"

# network
watchyourlan_hostname: "watchyourlan"
watchyourlan_port_http: "8840"
watchyourlan_ifaces: "en0 en1 bond0 enp6s18"

# docker
watchyourlan_container_name: "watchyourlan"
watchyourlan_image_name: "ghcr.io/aceberg/watchyourlan"
watchyourlan_image_tag: "latest"

# specs
watchyourlan_cpu_shares: 1024
watchyourlan_memory: "1G"

watchyourlan_shoutrrr_url: ""

# autoheal
watchyourlan_autoheal: "false"

# homepage
watchyourlan_homepage_group: "Apps"
watchyourlan_homepage_icon: "watchyourlan.png"
watchyourlan_homepage_showstats: "false"

# watchtower
watchyourlan_watchtower_enable: "false"