---
# ANE
ansible_nas_app_name: "WatchYourLAN"
watchyourlan_enabled: false
watchyourlan_traefik_enabled: false
watchyourlan_traefik_whitelist: "{{ lan }}"
watchyourlan_data_directory: "{{ docker_home }}/watchyourlan"

# network
watchyourlan_hostname: "watchyourlan"
watchyourlan_port_http: "8840"
watchyourlan_ifaces: "en0 en1 bond0 enp6s18"

# docker
watchyourlan_container_name: "watchyourlan"
watchyourlan_image_name: "ghcr.io/aceberg/watchyourlan"
watchyourlan_image_tag: "latest"

# specs
watchyourlan_cpu_shares: 1024
watchyourlan_memory: "1G"
watchyourlan_memory_swap: -1

# app
watchyourlan_env_ifaces: "enp6s18" # required: 1 or more interface
watchyourlan_env_host: "0.0.0.0" # optional, default: 0.0.0.0
watchyourlan_env_timeout: "120" # optional, time in seconds, default: 120
watchyourlan_env_theme: "sand" # optional
watchyourlan_env_color: "dark" # optional
watchyourlan_env_shoutrrr_url: "" # optional, set url to notify

# autoheal
watchyourlan_autoheal_enabled: false

# dockflare
watchyourlan_dockflare_enabled: false
watchyourlan_dockflare_access_group: ""

# homepage
watchyourlan_homepage_group: "Apps"
watchyourlan_homepage_icon: "watchyourlan.png"
watchyourlan_homepage_showstats: false

# tinyauth
#watchyourlan_tinyauth_enabled: false

# watchtower
watchyourlan_watchtower_enabled: false