---
# ANE
ansible_nas_app_name: "Gameyfin"
gameyfin_enabled: false
gameyfin_available_externally: false
gameyfin_traefik_whitelist: "{{ lan }}"

# directories
gameyfin_data_directory: "{{ docker_home }}/gameyfin"
gameyfin_games_directory: "{{ games_root }}"

# docker
gameyfin_container_name: "gameyfin"
gameyfin_image_name: "ghcr.io/gameyfin/gameyfin"
gameyfin_image_tag: "latest"

# uid / gid
gameyfin_user_id: "0"
gameyfin_group_id: "0"

# network
gameyfin_port: "8081"
gameyfin_hostname: "gameyfin"

# specs
gameyfin_cpu_shares: "1024"
gameyfin_memory: 1g

# app
gameyfin_env_app_key: "gWrGswm6GWAl0lYhlLnhCPz/rFFkCoYelUIzJ2Ao9Tw=" # Generate a new APP_KEY using the command `openssl rand -base64 32` or similar.
gameyfin_env_app_url: "https://{{ gameyfin_hostname }}.{{ ansible_nas_domain }}"

# autoheal
gameyfin_autoheal: "false"

# dockflare
gameyfin_dockflare_tunnel: "false"
gameyfin_dockflare_access_group: ""

# homepage
gameyfin_homepage_group: "Apps"
gameyfin_homepage_icon: "sh-gameyfin.png"
gameyfin_homepage_href: "http://{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}:{{ gameyfin_port }}"
gameyfin_homepage_showstats: "false"

# repliqate
gameyfin_repliqate_enabled: "false"
gameyfin_repliqate_engine: "restic"
gameyfin_repliqate_schedule: "@daily 3am"
gameyfin_repliqate_backup_id: "gameyfin"
gameyfin_repliqate_retention: "30d"

# watchtower
gameyfin_watchtower_enable: "false"
