---
- name: Start {{ ansible_nas_app_name }}
  block:
    - name: Create {{ ansible_nas_app_name }} Directories
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
      with_items:
        - "{{ romm_data_directory }}/resources"
        - "{{ romm_db_data_directory }}"

    - name: Create {{ ansible_nas_app_name }} DB Container
      community.docker.docker_container:
        name: "{{ romm_db_container_name }}"
        image: "{{ romm_db_image_name }}:{{ romm_db_image_version }}"
        pull: true
        volumes:
          - "{{ romm_db_data_directory }}/db:/var/lib/mysql"
        env:
          MYSQL_ROOT_PASSWORD: "{{ romm_database_root_password }}"
          MYSQL_DATABASE: "romm"
          MYSQL_USER: "{{ romm_database_username }}"
          MYSQL_PASSWORD: "{{ romm_database_password }}"
        restart_policy: unless-stopped
        cpu_shares: "{{ romm_db_cpu_shares }}"
        memory: "{{ romm_db_memory }}"
        labels:
          autoheal: "{{ romm_db_autoheal }}"
          com.centurylinklabs.watchtower.monitor-only: "{{ romm_db_watchtower_monitor_only }}"

    - name: Create {{ ansible_nas_app_name }} Redis Container
      community.docker.docker_container:
        name: "{{ romm_redis_container_name }}"
        image: "{{ romm_redis_image_name }}:{{ romm_redis_image_version }}"
        pull: true
        restart_policy: unless-stopped
        memory: "{{ romm_redis_memory }}"
        labels:
          autoheal: "{{ romm_redis_autoheal }}"
          com.centurylinklabs.watchtower.monitor-only: "{{ romm_redis_watchtower_monitor_only }}"

    - name: Create {{ ansible_nas_app_name }} Container
      community.docker.docker_container:
        name: "{{ romm_container_name }}"
        image: "{{ romm_image_name }}:{{ romm_image_version }}"
        pull: true
        volumes:
          - "{{ romm_roms_directory }}:/romm/library/roms:rw"
          - "{{ romm_data_directory }}/resources:/romm/resources:rw"
        ports:
          - "{{ romm_port }}:8080"
        env:
          ROMM_DB_DRIVER: "mariadb"
          DB_HOST: "db"
          DB_PORT: "3306"
          DB_USER: "{{ romm_database_username }}"
          DB_PASSWD: "{{ romm_database_password }}"
          DB_NAME: "romm"
          ROMM_AUTH_ENABLED: "true"
          ROMM_AUTH_SECRET_KEY: "{{ romm_auth_secret_key }}"
          ENABLE_EXPERIMENTAL_REDIS: "true"
          REDIS_HOST: "redis"
          REDIS_PORT: "6379"
          IGDB_CLIENT_ID: "{{ romm_igdb_client_id }}"
          IGDB_CLIENT_SECRET: "{{ romm_igdb_client_secret }}"
          MOBYGAMES_API_KEY: "{{ romm_mobygames_client_id }}"
          STEAMGRIDDB_API_KEY: "{{ romm_steamgriddb_client_id }}"
          ROMM_AUTH_USERNAME: "{{ romm_auth_username }}"
          ROMM_AUTH_PASSWORD: "{{ romm_auth_password }}"
        restart_policy: unless-stopped
        cpu_shares: "{{ romm_cpu_shares }}"
        memory: "{{ romm_memory }}"
        links:
          - "{{ romm_db_container_name }}:db"
          - "{{ romm_redis_container_name }}:redis"
        labels:
          autoheal: "{{ romm_autoheal }}"
          com.centurylinklabs.watchtower.monitor-only: "{{ romm_watchtower_monitor_only }}"
          traefik.enable: "{{ romm_available_externally | string }}"
          traefik.http.routers.romm.rule: "Host(`{{ romm_hostname }}.{{ ansible_nas_domain }}`)"
          traefik.http.routers.romm.tls.certresolver: "letsencrypt"
          traefik.http.routers.romm.tls.domains[0].main: "{{ ansible_nas_domain }}"
          traefik.http.routers.romm.tls.domains[0].sans: "*.{{ ansible_nas_domain }}"
          traefik.http.services.romm.loadbalancer.server.port: "8080"
          homepage.group: Media
          homepage.name: Romm
          homepage.icon: romm
          homepage.href: http://{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}:{{ romm_port }}
          homepage.description: Game library manager
  when: romm_enabled is true

- name: Stop {{ ansible_nas_app_name }}
  block:
    - name: Stop {{ ansible_nas_app_name }} Container
      community.docker.docker_container:
        name: "{{ romm_container_name }}"
        state: absent

    - name: Stop {{ ansible_nas_app_name }} Redis Container
      community.docker.docker_container:
        name: "{{ romm_redis_container_name }}"
        state: absent

    - name: Stop {{ ansible_nas_app_name }} DB Container
      community.docker.docker_container:
        name: "{{ romm_db_container_name }}"
        state: absent
  when: romm_enabled is false

- name: Data Archive {{ ansible_nas_app_name }}
  block:
    - name: Check for {{ ansible_nas_app_name }} Data Directory
      stat:
        path: "{{ romm_data_directory }}"
      register: dir_stat

    - name: Archive {{ ansible_nas_app_name }} Data Directory
      ansible.builtin.archive:
        path: "{{ romm_data_directory }}"
        dest: "{{ docker_home }}/{{ ansible_nas_app_name | lower }}.zip"
        force_archive: true
        format: zip
        owner: ansible-nas
        group: ansible-nas
        mode: u=rw,g=rw
        remove: true
      when: dir_stat.stat.exists
  when: romm_enabled is false and archive_app_data_enabled is true
