---
ansible_nas_app_name: "CommaFeed"

commafeed_enabled: false
commafeed_available_externally: false
commafeed_traefik_whitelist: "{{ lan }}"

# directories
commafeed_data_directory: "{{ docker_home }}/commafeed"

# network
commafeed_port_http: "8082"
commafeed_hostname: "commafeed"

# docker
commafeed_container_name: "commafeed"
commafeed_image_name: "athou/commafeed"
commafeed_image_tag: "latest"
commafeed_cpu_shares: "1024"
commafeed_memory: 1g
commafeed_db_container_name: "commafeed-postgres"
commafeed_db_image_name: "postgres"
commafeed_db_image_tag: "latest"
commafeed_db_cpu_shares: "1024"
commafeed_db_memory: 1g

# autoheal
commafeed_autoheal: "false"
commafeed_db_autoheal: "false"

# dockflare
commafeed_dockflare_tunnel: "false"
commafeed_dockflare_access_group: ""

# homepage
commafeed_homepage_group: "Apps"
commafeed_homepage_icon: "commafeed.png"
commafeed_homepage_href: "http://{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}:{{ commafeed_port_http }}"
commafeed_homepage_showStats: "false"
commafeed_db_homepage_group: "DBs"
commafeed_db_homepage_icon: "postgres.png"
commafeed_db_homepage_href: "http://{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}:{{ commafeed_port_http }}"
commafeed_db_homepage_showStats: "false"

# watchtower
commafeed_watchtower_monitor_only: "true"
commafeed_db_watchtower_monitor_only: "true"