---
- name: Start {{ ansible_nas_app_name }}
  block:
    - name: Create {{ ansible_nas_app_name }} Directories
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
      with_items:
        - "{{ jackett_data_directory }}"

    - name: Create {{ ansible_nas_app_name }} Container
      community.docker.docker_container:
        container_default_behavior: "compatibility"
        name: "{{ jackett_container_name }}"
        hostname: "{{ jackett_container_name }}"
        image: "{{ jackett_image_name }}:{{ jackett_image_version }}"
        pull: true
        cpu_shares: "{{ jackett_cpu_shares }}"
        volumes:
          - "{{ jackett_data_directory }}:/config:rw"
          - "/etc/localtime:/etc/localtime:ro"
          - "{{ jackett_torrents_root }}:/downloads"
        ports:
          - "{{ jackett_port }}:9117"
        env:
          TZ: "{{ ansible_nas_timezone }}"
        restart_policy: unless-stopped
        memory: "{{ jackett_memory }}"
        labels:
          autoheal: "{{ jackett_autoheal }}"
          com.centurylinklabs.watchtower.monitor-only: "{{ jackett_watchtower_monitor_only }}"
          homepage.group: Download Tools
          homepage.name: Jackett
          homepage.icon: jackett
          homepage.href: http://{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}:{{ jackett_port }}
          homepage.description: "{{ 'API Support for your favorite torrent trackers' if homepage_show_description else omit }}"
          traefik.enable: "{{ jackett_available_externally | string }}"
          traefik.http.routers.jackett.rule: "Host(`{{ jackett_hostname }}.{{ ansible_nas_domain }}`)"
          traefik.http.routers.jackett.tls.certresolver: "letsencrypt"
          traefik.http.routers.jackett.tls.domains[0].main: "{{ ansible_nas_domain }}"
          traefik.http.routers.jackett.tls.domains[0].sans: "*.{{ ansible_nas_domain }}"
          traefik.http.routers.frontend.middlewares: "{{ jackett_hostname }}"
          traefik.http.routers.jackett.middlewares: "{{ jackett_hostname }}@docker"
          traefik.http.middlewares.jackett.IPAllowList.sourcerange: "{{ jackett_traefik_whitelist }}"
          traefik.http.services.jackett.loadbalancer.server.port: "9117"
  when: jackett_enabled is true

- name: Stop {{ ansible_nas_app_name }}
  block:
    - name: Stop {{ ansible_nas_app_name }} Container
      community.docker.docker_container:
        name: "{{ jackett_container_name }}"
        state: absent
  when: jackett_enabled is false

- name: Data Archive {{ ansible_nas_app_name }}
  block:
    - name: Check for {{ ansible_nas_app_name }} Data Directory
      stat:
        path: "{{ jackett_data_directory }}"
      register: dir_stat

    - name: Archive {{ ansible_nas_app_name }} Data Directory
      ansible.builtin.archive:
        path: "{{ jackett_data_directory }}"
        dest: "{{ docker_home }}/{{ ansible_nas_app_name | lower }}.zip"
        force_archive: true
        format: zip
        owner: ansible-nas
        group: ansible-nas
        mode: u=rw,g=rw
        remove: true
      when: dir_stat.stat.exists
  when: jackett_enabled is false and archive_app_data_enabled is true
