---
- name: Start {{ ansible_nas_app_name }}
  block:
    - name: Create {{ ansible_nas_app_name }} Directories
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
      with_items:
        - "{{ koillection_data_directory }}"
        - "{{ koillection_data_directory }}/db"
        - "{{ koillection_data_directory }}/uploads"

    - name: Set {{ ansible_nas_app_name }} FQDN var overrides
      ansible.builtin.set_fact:
        koillection_homepage_href: "https://{{ koillection_hostname }}.{{ ansible_nas_domain }}"
      when: koillection_traefik_enabled | bool or koillection_dockflare_enabled | bool

    - name: Create {{ ansible_nas_app_name }} DB Container
      community.docker.docker_container:
        container_default_behavior: "compatibility"
        name: "{{ koillection_db_container_name }}"
        hostname: "{{ koillection_db_container_name }}"
        image: "{{ koillection_db_image_name }}:{{ koillection_db_image_tag }}"
        pull: true
        volumes:
          - "{{ koillection_data_directory }}/db:/var/lib/postgresql/data"
        env:
          POSTGRES_DB: "koillection"
          POSTGRES_USER: "koillection"
          POSTGRES_PASSWORD: "koillection"
        healthcheck:
          test: ["CMD-SHELL", "pg_isready -U koillection"]
          interval: 10s
          timeout: 5s
          retries: 5
          start_period: 30s
        labels:
          autoheal: "{{ koillection_db_autoheal_enabled | ternary('true', 'false') }}"
          com.centurylinklabs.watchtower.enable: "{{ koillection_db_watchtower_enabled | ternary('true', 'false') }}"
          dockflare.enable: "false"
          homepage.name: "{{ ansible_nas_app_name }} PostgreSQL"
          homepage.group: "{{ koillection_db_homepage_group }}"
          homepage.icon: "{{ koillection_db_homepage_icon }}"
          homepage.href: "{{ koillection_db_homepage_href }}"
          homepage.description: "{{ 'PostgreSQL Database Management System' if homepage_show_description else omit }}"
          homepage.server: "my-docker"
          homepage.container: "{{ koillection_db_container_name }}"
          homepage.showStats: "{{ koillection_db_homepage_showstats | ternary('true', 'false') }}"
          repliqate.enabled: "{{ koillection_db_repliqate_enabled | ternary('true', 'false') }}"
          repliqate.engine: "{{ koillection_db_repliqate_engine }}"
          repliqate.schedule: "{{ koillection_db_repliqate_schedule }}"
          repliqate.backup_id: "{{ koillection_db_repliqate_backup_id }}"
          repliqate.retention: "{{ koillection_db_repliqate_retention }}"
          traefik.enable: "false"
          wud.tag.include: '^\d+\.\d+.*$'
          wud.tag.transform.type: "semver"
          wud.link.template: "https://hub.docker.com/_/postgres"
        cpu_shares: "{{ koillection_db_cpu_shares }}"
        memory: "{{ koillection_db_memory }}"
        memory_swap: "{{ koillection_db_memory_swap }}"
        restart_policy: unless-stopped
      register: koillection_db_status

    - name: Verify {{ ansible_nas_app_name }} DB is healthy
      community.docker.docker_container_info:
        name: "{{ koillection_db_container_name }}"
      register: db_info
      until: "db_info.container.State.Health.Status == 'healthy'"
      retries: 30
      delay: 5

    - name: Create {{ ansible_nas_app_name }} Container
      community.docker.docker_container:
        container_default_behavior: "compatibility"
        name: "{{ koillection_container_name }}"
        hostname: "{{ koillection_container_name }}"
        image: "{{ koillection_image_name }}:{{ koillection_image_tag }}"
        pull: true
        volumes:
          - "{{ koillection_data_directory }}/uploads:/uploads"
        ports:
          - "{{ koillection_port_http }}:80"
        env:
          APP_DEBUG: "0"
          APP_ENV: "prod"
          APP_SECRET: "{{ koillection_app_secret }}"
          HTTPS_ENABLED: "0"
          UPLOAD_MAX_FILESIZE: "20M"
          PHP_MEMORY_LIMIT: "512M"
          PHP_TZ: "{{ ansible_nas_timezone }}"
          DB_DRIVER: "pdo_pgsql"
          DB_NAME: "koillection"
          DB_HOST: "{{ koillection_db_container_name }}"
          DB_PORT: "5432"
          DB_USER: "koillection"
          DB_PASSWORD: "koillection"
          DB_VERSION: "16"
          TZ: "{{ ansible_nas_timezone }}"
        links:
          - "{{ koillection_db_container_name }}"
        labels:
          autoheal: "{{ koillection_autoheal_enabled | ternary('true', 'false') }}"
          com.centurylinklabs.watchtower.enable: "{{ koillection_watchtower_enabled | ternary('true', 'false') }}"
          dockflare.enable: "{{ koillection_dockflare_enabled | ternary('true', 'false') }}"
          dockflare.access.group: "{{ koillection_dockflare_access_group }}"
          dockflare.hostname: "{{ koillection_hostname }}.{{ ansible_nas_domain }}"
          dockflare.service: "http://{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}:{{ koillection_port_http }}"
          homepage.name: "koillection"
          homepage.group: "{{ koillection_homepage_group }}"
          homepage.icon: "{{ koillection_homepage_icon }}"
          homepage.href: "{{ koillection_homepage_href }}"
          homepage.description: "{{ 'a self-hosted service allowing users to manage any kind of collections.' if homepage_show_description else omit }}"
          homepage.siteMonitor: "http://{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}:{{ koillection_port_http }}"
          homepage.server: "my-docker"
          homepage.container: "{{ koillection_container_name }}"
          homepage.showStats: "{{ koillection_homepage_showstats | ternary('true', 'false') }}"
          repliqate.enabled: "{{ koillection_repliqate_enabled | ternary('true', 'false') }}"
          repliqate.engine: "{{ koillection_repliqate_engine }}"
          repliqate.schedule: "{{ koillection_repliqate_schedule }}"
          repliqate.backup_id: "{{ koillection_repliqate_backup_id }}"
          repliqate.retention: "{{ koillection_repliqate_retention }}"
          traefik.enable: "{{ koillection_traefik_enabled | ternary('true', 'false') }}"
          traefik.http.routers.koillection.rule: "Host(`{{ koillection_hostname }}.{{ ansible_nas_domain }}`)"
          traefik.http.routers.koillection.tls.certresolver: "letsencrypt"
          traefik.http.routers.koillection.tls.domains[0].main: "{{ ansible_nas_domain }}"
          traefik.http.routers.koillection.tls.domains[0].sans: "*.{{ ansible_nas_domain }}"
          traefik.http.routers.koillection.middlewares: "koillection@docker{{ ',tinyauth-auth@docker' if koillection_tinyauth_enabled | bool else '' }}"
          traefik.http.middlewares.koillection.IPAllowList.sourcerange: "{{ koillection_traefik_whitelist }}"
          traefik.http.services.koillection.loadbalancer.server.port: "80"
          wud.tag.include: '^\d+\.\d+\.\d+.*$'
          wud.tag.transform.type: "semver"
          wud.link.template: "https://hub.docker.com/r/koillection/koillection"
        cpu_shares: "{{ koillection_cpu_shares }}"
        memory: "{{ koillection_memory }}"
        memory_swap: "{{ koillection_memory_swap }}"
        restart_policy: unless-stopped

    - name: Access {{ ansible_nas_app_name }} at
      ansible.builtin.debug:
        msg: >-
              {{
                ['http://' + hostvars[inventory_hostname]['ansible_default_ipv4']['address'] + ':' + (koillection_port_http | string)] +
                (['https://' + koillection_hostname + '.' + ansible_nas_domain] if (koillection_traefik_enabled is true or koillection_dockflare_enabled is true) else [])
              }}
  when: koillection_enabled is true

- name: Stop {{ ansible_nas_app_name }}
  block:
    - name: Stop {{ ansible_nas_app_name }} Container
      community.docker.docker_container:
        name: "{{ koillection_container_name }}"
        state: absent

    - name: Stop {{ ansible_nas_app_name }} DB Container
      community.docker.docker_container:
        name: "{{ koillection_db_container_name }}"
        state: absent
  when: koillection_enabled is false

- name: Data Archive {{ ansible_nas_app_name }}
  include_role:
    name: ansible-nas-archive
  vars:
    target_data_dir: "{{ koillection_data_directory }}"
  when:
    - archive_app_data_enabled is true
    - koillection_enabled is false