---
- name: Start {{ ansible_nas_app_name }}
  block:
    - name: Create {{ ansible_nas_app_name }} Directories
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
      with_items:
        - "{{ kavita_data_directory }}"
        - "{{ kavita_data_directory }}/config"
        - "{{ kavita_books_directory }}"
        - "{{ kavita_comics_directory }}"

    - name: Create {{ ansible_nas_app_name }} Container
      community.docker.docker_container:
        container_default_behavior: "compatibility"
        name: "{{ kavita_container_name }}"
        hostname: "{{ kavita_container_name }}"
        image: "{{ kavita_image_name }}:{{ kavita_image_tag }}"
        pull: true
        volumes:
          - "{{ kavita_data_directory }}/config:/kavita/config"
          - "{{ kavita_books_directory }}:/books:ro"
          - "{{ kavita_comics_directory }}:/comics:ro"
        network_mode: bridge
        ports:
          - "{{ kavita_port_http }}:5000"
        env:
          TZ: "{{ ansible_nas_timezone }}"
        labels:
          autoheal: "{{ kavita_autoheal | string }}"
          com.centurylinklabs.watchtower.enable: "{{ kavita_watchtower_enabled| string }}"
          dockflare.enable: "{{ kavita_dockflare_enabled | string }}"
          dockflare.access.group: "{{ kavita_dockflare_access_group }}"
          dockflare.hostname: "{{ kavita_hostname }}.{{ ansible_nas_domain }}"
          dockflare.service: "http://{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}:{{ kavita_port_http }}"
          homepage.name: "{{ ansible_nas_app_name }}"
          homepage.group: "{{ kavita_homepage_group }}"
          homepage.icon: "{{ kavita_homepage_icon }}"
          homepage.href: "{{ kavita_homepage_href }}"
          homepage.siteMonitor: "http://{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}:{{ kavita_port_http }}"
          homepage.description: "{{ 'a fast, feature rich, cross platform reading server.' if homepage_show_description else omit }}"
          homepage.server: "my-docker"
          homepage.container: "{{ kavita_container_name }}"
          homepage.showStats: "{{ kavita_homepage_showstats | string }}"
          homepage.widget.type: "kavita"
          homepage.widget.url: "http://{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}:{{ kavita_port_http }}"
          homepage.widget.username: "{{ kavita_homepage_widget_username }}"
          homepage.widget.password: "{{ kavita_homepage_widget_password }}"
          homepage.widget.key: "{{ kavita_homepage_widget_key }}"
          repliqate.enabled: "{{ kavita_repliqate_enabled | string }}"
          repliqate.engine: "{{ kavita_repliqate_engine }}"
          repliqate.schedule: "{{ kavita_repliqate_schedule }}"
          repliqate.backup_id: "{{ kavita_repliqate_backup_id }}"
          repliqate.retention: "{{ kavita_repliqate_retention }}"
          traefik.enable: "{{ kavita_available_externally | string }}"
          traefik.http.routers.kavita.rule: "Host(`{{ kavita_hostname }}.{{ ansible_nas_domain }}`)"
          traefik.http.routers.kavita.tls.certresolver: "letsencrypt"
          traefik.http.routers.kavita.tls.domains[0].main: "{{ ansible_nas_domain }}"
          traefik.http.routers.kavita.tls.domains[0].sans: "*.{{ ansible_nas_domain }}"
          traefik.http.routers.kavita.middlewares: "kavita@docker{{ ',tinyauth-auth@docker' if kavita_tinyauth_enabled | bool else '' }}"
          traefik.http.middlewares.kavita.IPAllowList.sourcerange: "{{ kavita_traefik_whitelist }}"
          traefik.http.services.kavita.loadbalancer.server.port: "5000"
          wud.tag.include: '^\d+\.\d+\.\d+.*$'
          wud.tag.transform.type: "semver"
          wud.link.template: "https://hub.docker.com/r/jvmilazz0/kavita"
        cpu_shares: "{{ kavita_cpu_shares }}"
        memory: "{{ kavita_memory }}"
        memory_swap: "{{ kavita_memory_swap }}"
        restart_policy: unless-stopped

    - name: Access {{ ansible_nas_app_name }} at
      ansible.builtin.debug:
        msg: >-
              {{
                ['http://' + hostvars[inventory_hostname]['ansible_default_ipv4']['address'] + ':' + (kavita_port_http | string)] +
                (['https://' + kavita_hostname + '.' + ansible_nas_domain] if (kavita_available_externally is true or kavita_dockflare_enabled is true) else [])
              }}
  when: kavita_enabled is true

- name: Stop {{ ansible_nas_app_name }}
  block:
    - name: Stop {{ ansible_nas_app_name }} Container
      community.docker.docker_container:
        name: "{{ kavita_container_name }}"
        state: absent
  when: kavita_enabled is false

- name: Data Archive {{ ansible_nas_app_name }}
  include_role:
    name: ansible-nas-archive
  vars:
    target_data_dir: "{{ kavita_data_directory }}"
  when:
    - archive_app_data_enabled is true
    - kavita_enabled is false