---
# ANE
ansible_nas_app_name: "OpenEats"
openeats_enabled: false
openeats_available_externally: false
openeats_traefik_whitelist: "{{ lan }}"
openeats_data_directory: "{{ docker_home }}/openeats"

# network
openeats_hostname: "openeats"
openeats_port_http: "5807"
openeats_port_api: "3066"
openeats_port_db: "3306"

# docker
openeats_container_name: "openeats-web"
openeats_image_name: "openeats/openeats-web"
openeats_image_tag: "latest"
openeats_api_container_name: "openeats-api"
openeats_api_image_name: "openeats/openeats-api"
openeats_api_image_tag: "latest"
openeats_db_container_name: "openeats-db"
openeats_db_image_name: "mariadb"
openeats_db_image_tag: "10.3"

# specs
openeats_cpu_shares: 1024
openeats_memory: "1G"
openeats_api_cpu_shares: 1024
openeats_api_memory: "1G"
openeats_db_cpu_shares: 1024
openeats_db_memory: "1G"

# autoheal
openeats_autoheal: "false"
openeats_api_autoheal: "false"
openeats_db_autoheal: "false"

# dockflare
openeats_dockflare_tunnel: "false"
openeats_dockflare_access_group: ""

# homepage
openeats_homepage_group: "Apps"
openeats_homepage_icon: "openeats.png"
openeats_homepage_href: "http://{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}:{{ openeats_port_http }}"
openeats_homepage_showstats: "false"
openeats_api_homepage_group: "Misc"
openeats_api_homepage_icon: "openeats.png"
openeats_api_homepage_showstats: "false"
openeats_db_homepage_group: "DBs"
openeats_db_homepage_icon: "mariadb.png"
openeats_db_homepage_showstats: "false"

# repliqate
openeats_repliqate_enabled: "false"
openeats_repliqate_engine: "restic"
openeats_repliqate_schedule: "@daily 3am"
openeats_repliqate_backup_id: "{{ openeats_container_name }}"
openeats_repliqate_retention: "30d"
openeats_api_repliqate_enabled: "false"
openeats_api_repliqate_engine: "restic"
openeats_api_repliqate_schedule: "@daily 3am"
openeats_api_repliqate_backup_id: "{{ openeats_container_name }}"
openeats_api_repliqate_retention: "30d"
openeats_db_repliqate_enabled: "false"
openeats_db_repliqate_engine: "restic"
openeats_db_repliqate_schedule: "@daily 3am"
openeats_db_repliqate_backup_id: "{{ openeats_container_name }}"
openeats_db_repliqate_retention: "30d"

# watchtower
openeats_watchtower_enable: "false"
openeats_api_watchtower_enable: "false"
openeats_db_watchtower_enable: "false"