---
- name: Start {{ ansible_nas_app_name }}
  block:
    - name: Create {{ ansible_nas_app_name }} Directories
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
      with_items:
        - "{{ cup_data_directory }}"
        - "{{ cup_data_directory }}/config"

    - name: Create {{ ansible_nas_app_name }} Container
      community.docker.docker_container:
        container_default_behavior: "compatibility"
        name: "{{ cup_container_name }}"
        hostname: "{{ cup_container_name }}"
        image: "{{ cup_image_name }}:{{ cup_image_tag }}"
        pull: true
        tty: true
        command: "serve -p {{ cup_port_http }}"
        ports:
          - "{{ cup_port_http }}:{{ cup_port_http }}"
        volumes:
          - "{{ cup_data_directory }}/config:/config/cup.json"
          - "/var/run/docker.sock:/var/run/docker.sock"
        network_mode: bridge
        env:
          TZ: "{{ ansible_nas_timezone }}"
        labels:
          autoheal: "{{ cup_autoheal }}"
          com.centurylinklabs.watchtower.enable: "{{ cup_watchtower_enable }}"
          dockflare.enable: "{{ cup_dockflare_tunnel }}"
          dockflare.access.group: "{{ cup_dockflare_access_group }}"
          dockflare.hostname: "{{ cup_hostname }}.{{ ansible_nas_domain }}"
          dockflare.service: "http://{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}:{{ cup_port_http }}"
          homepage.name: "{{ ansible_nas_app_name }}"
          homepage.group: "{{ cup_homepage_group }}"
          homepage.icon: "{{ cup_homepage_icon }}"
          homepage.href: "{{ cup_homepage_href }}"
          homepage.siteMonitor: "http://{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}:{{ cup_port_http }}"
          homepage.description: "{{ 'Docker container updates made easy' if homepage_show_description else omit }}"
          homepage.server: "my-docker"
          homepage.container: "{{ cup_container_name }}"
          homepage.showStats: "{{ cup_homepage_showstats }}"
          homepage.widget.type: "customapi"
          homepage.widget.url: "{{ cup_homepage_widget_url }}"
          homepage.widget.mappings[0].label: "Monitoring"
          homepage.widget.mappings[0].field.metrics: "monitored_images"
          homepage.widget.mappings[0].format: "number"
          homepage.widget.mappings[1].label: "Up to date"
          homepage.widget.mappings[1].field.metrics: "up_to_date"
          homepage.widget.mappings[1].format: "number"
          homepage.widget.mappings[2].label: "Updates"
          homepage.widget.mappings[2].field.metrics: "update_available"
          homepage.widget.mappings[2].format: "number"
          repliqate.enabled: "{{ cup_repliqate_enabled }}"
          repliqate.engine: "{{ cup_repliqate_engine }}"
          repliqate.schedule: "{{ cup_repliqate_schedule }}"
          repliqate.backup_id: "{{ cup_repliqate_backup_id }}"
          repliqate.retention: "{{ cup_repliqate_retention }}"
          traefik.enable: "{{ cup_available_externally | string }}"
          traefik.http.routers.cup.rule: "Host(`{{ cup_hostname }}.{{ ansible_nas_domain }}`)"
          traefik.http.routers.cup.tls.certresolver: "letsencrypt"
          traefik.http.routers.cup.tls.domains[0].main: "{{ ansible_nas_domain }}"
          traefik.http.routers.cup.tls.domains[0].sans: "*.{{ ansible_nas_domain }}"
          traefik.http.routers.cup.middlewares: "cup@docker{{ ',tinyauth-auth@docker' if cup_tinyauth_enabled | bool else '' }}"
          traefik.http.middlewares.cup.IPAllowList.sourcerange: "{{ cup_traefik_whitelist }}"
          traefik.http.services.cup.loadbalancer.server.port: "{{ cup_port_http }}"
          wud.tag.include: '^\d+\.\d+\.\d+.*$'
          wud.tag.transform.type: "semver"
          wud.link.template: "https://github.com/sergi0g/CUP/releases"
        cpu_shares: "{{ cup_cpu_shares }}"
        memory: "{{ cup_memory }}"
        restart_policy: unless-stopped

    - name: Access {{ ansible_nas_app_name }} at
      ansible.builtin.debug:
        msg: >-
              {{
                ['http://' + hostvars[inventory_hostname]['ansible_default_ipv4']['address'] + ':' + (cup_port_http | string)] +
                (['https://' + cup_hostname + '.' + ansible_nas_domain] if (cup_available_externally is true or cup_dockflare_tunnel is true) else [])
              }}
  when: cup_enabled is true

- name: Stop {{ ansible_nas_app_name }}
  block:
    - name: Stop {{ ansible_nas_app_name }} Container
      community.docker.docker_container:
        name: "{{ cup_container_name }}"
        state: absent
  when: cup_enabled is false

- name: Data Archive {{ ansible_nas_app_name }}
  include_role:
    name: ansible-nas-archive
  vars:
    target_data_dir: "{{ cup_data_directory }}"
  when:
    - archive_app_data_enabled is true
    - cup_enabled is false