---
- name: Start {{ ansible_nas_app_name }}
  block:
    - name: Create {{ ansible_nas_app_name }} Directory
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
      with_items:
        - "{{ arcane_data_directory }}"

    - name: Set {{ ansible_nas_app_name }} FQDN var overrides
      ansible.builtin.set_fact:
        arcane_env_app_url: "https://{{ arcane_hostname }}.{{ ansible_nas_domain }}"
        arcane_homepage_href: "https://{{ arcane_hostname }}.{{ ansible_nas_domain }}"
      when: arcane_traefik_enabled | bool or arcane_dockflare_enabled | bool

    - name: Create {{ ansible_nas_app_name }} Container
      community.docker.docker_container:
        container_default_behavior: "compatibility"
        name: "{{ arcane_container_name }}"
        hostname: "{{ arcane_container_name }}"
        image: "{{ arcane_image_name }}:{{ arcane_image_tag }}"
        pull: true
        volumes:
          - "{{ arcane_data_directory }}:/app/data"
          - "{{ docker_compose_data_directory }}:/app/data/projects"
          - "/var/run/docker.sock:/var/run/docker.sock"
        ports:
          - "{{ arcane_port_http }}:{{ arcane_port_http }}"
        env:
          APP_URL: "{{ arcane_env_app_url }}"
          ENCRYPTION_KEY: "{{ arcane_env_encryption_key }}"
          JWT_SECRET: "{{ arcane_env_jwt_secret }}"
          PUID: "{{ arcane_puid }}"
          PGID: "{{ arcane_pgid }}"
          PORT: "{{ arcane_port_http | string }}"
#         PUBLIC_SESSION_SECRET: "{{ arcane_public_session_secret }}"
          TZ: "{{ ansible_nas_timezone }}"
        healthcheck:
          test: ['CMD-SHELL', 'curl -fsS http://localhost:3552/api/health >/dev/null || exit 1']
          interval: 10s
          timeout: 3s
          retries: 5
          start_period: 15s
        labels:
          autoheal: "{{ arcane_autoheal_enabled | ternary('true', 'false') }}"
          com.centurylinklabs.watchtower.enable: "{{ arcane_watchtower_enabled | ternary('true', 'false') }}"
          dockflare.enable: "{{ arcane_dockflare_enabled | ternary('true', 'false') }}"
          dockflare.access.group: "{{ arcane_dockflare_access_group }}"
          dockflare.hostname: "{{ arcane_hostname }}.{{ ansible_nas_domain }}"
          dockflare.service: "http://{{ hostvars[inventory_hostname]['ansible_facts']['default_ipv4']['address'] }}:{{ arcane_port_http }}"
          homepage.name: "{{ ansible_nas_app_name }}"
          homepage.group: "{{ arcane_homepage_group }}"
          homepage.icon: "{{ arcane_homepage_icon }}"
          homepage.href: "{{ arcane_homepage_href }}"
          homepage.description: "{{ 'Modern Docker Management, Designed for Everyone' if homepage_show_description else omit }}"
          homepage.siteMonitor: "http://{{ hostvars[inventory_hostname]['ansible_facts']['default_ipv4']['address'] }}:{{ arcane_port_http }}"
          homepage.server: "my-docker"
          homepage.container: "{{ arcane_container_name }}"
          homepage.showStats: "{{ arcane_homepage_showstats | ternary('true', 'false') }}"
          repliqate.enabled: "{{ arcane_repliqate_enabled | ternary('true', 'false') }}"
          repliqate.engine: "{{ arcane_repliqate_engine }}"
          repliqate.schedule: "{{ arcane_repliqate_schedule }}"
          repliqate.backup_id: "{{ arcane_repliqate_backup_id }}"
          repliqate.retention: "{{ arcane_repliqate_retention }}"
          traefik.enable: "{{ arcane_traefik_enabled | ternary('true', 'false') }}"
          traefik.http.routers.arcane.rule: "Host(`{{ arcane_hostname }}.{{ ansible_nas_domain }}`)"
          traefik.http.routers.arcane.tls.certresolver: "letsencrypt"
          traefik.http.routers.arcane.tls.domains[0].main: "{{ ansible_nas_domain }}"
          traefik.http.routers.arcane.tls.domains[0].sans: "*.{{ ansible_nas_domain }}"
          traefik.http.routers.arcane.middlewares: "arcane@docker{{ ',tinyauth-auth@docker' if arcane_tinyauth_enabled | bool else '' }}"
          traefik.http.middlewares.arcane.IPAllowList.sourcerange: "{{ arcane_traefik_whitelist }}"
          traefik.http.services.arcane.loadbalancer.server.port: "{{ arcane_port_http }}"
          wud.tag.include: '^v?\d+\.\d+\.\d+.*$'
          wud.tag.transform.type: "semver"
          wud.link.template: "https://github.com/OFKM/Arcane/releases"
        cpu_shares: "{{ arcane_cpu_shares }}"
        memory: "{{ arcane_memory }}"
        memory_swap: "{{ arcane_memory_swap }}"
        restart_policy: unless-stopped

    - name: Access {{ ansible_nas_app_name }} at
      ansible.builtin.debug:
        msg: >-
              {{
                ['http://' + hostvars[inventory_hostname]['ansible_facts']['default_ipv4']['address'] + ':' + (arcane_port_http | string)] +
                (['https://' + arcane_hostname + '.' + ansible_nas_domain] if (arcane_traefik_enabled is true or arcane_dockflare_enabled is true) else [])
              }}
  when: arcane_enabled is true

- name: Stop {{ ansible_nas_app_name }}
  block:
    - name: Stop {{ ansible_nas_app_name }} Container
      community.docker.docker_container:
        name: "{{ arcane_container_name }}"
        state: absent
  when: arcane_enabled is false

- name: Data Archive {{ ansible_nas_app_name }}
  include_role:
    name: ansible-nas-archive
  vars:
    target_data_dir: "{{ arcane_data_directory }}"
  when:
    - archive_app_data_enabled is true
    - arcane_enabled is false