---
- name: Start {{ ansible_nas_app_name }}
  block:
    - name: Create {{ ansible_nas_app_name }} Directories
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
      with_items:
        - "{{ mosquitto_data_directory }}/config"
        - "{{ mosquitto_data_directory }}/data"
        - "{{ mosquitto_data_directory }}/log"

    - name: Copy {{ ansible_nas_app_name }} Template mosquitto.conf
      ansible.builtin.copy:
        src: mosquitto.conf
        dest: "{{ mosquitto_data_directory }}/config/mosquitto.conf"
      register: mosquitto_conf

    - name: Create {{ ansible_nas_app_name }} Container
      community.docker.docker_container:
        container_default_behavior: "compatibility"
        name: "{{ mosquitto_container_name }}"
        hostname: "{{ mosquitto_container_name }}"
        image: "{{ mosquitto_image_name }}:{{ mosquitto_image_version }}"
        pull: true
        volumes:
          - "{{ mosquitto_data_directory }}/config/mosquitto.conf:/mosquitto/config/mosquitto.conf:rw"
          - "{{ mosquitto_data_directory }}/data:/mosquitto/data:rw"
          - "{{ mosquitto_data_directory }}/log:/mosquitto/log:rw"
        ports:
          - "{{ mosquitto_port_a }}:1883"
          - "{{ mosquitto_port_b }}:9001"
        restart_policy: unless-stopped
        labels:
          autoheal: "{{ mosquitto_autoheal | string }}"
          com.centurylinklabs.watchtower.enable: "{{ mosquitto_watchtower_enabled | string }}"
          dockflare.enable: "false"
          homepage.name: "{{ ansible_nas_app_name }}"
          homepage.group: "{{ mosquitto_homepage_group }}"
          homepage.icon: "{{ mosquitto_homepage_icon }}"
          homepage.description: "{{ 'An open source MQTT broker' if homepage_show_description else omit }}"
          homepage.server: "my-docker"
          homepage.container: "{{ mosquitto_container_name }}"
          homepage.showStats: "{{ mosquitto_homepage_showstats | string }}"
          repliqate.enabled: "{{ mosquitto_repliqate_enabled | string }}"
          repliqate.engine: "{{ mosquitto_repliqate_engine }}"
          repliqate.schedule: "{{ mosquitto_repliqate_schedule }}"
          repliqate.backup_id: "{{ mosquitto_repliqate_backup_id }}"
          repliqate.retention: "{{ mosquitto_repliqate_retention }}"
          traefik_enabled: "false"
          wud.tag.include: '^\d+\.\d+\.\d+.*$'
          wud.tag.transform.type: "semver"
          wud.link.template: "https://hub.docker.com/_/eclipse-mosquitto"
        cpu_shares: "{{ mosquitto_cpu_shares }}"
        memory: "{{ mosquitto_memory }}"
        memory_swap: "{{ mosquitto_memory_swap }}"
        restart: "{{ mosquitto_conf is changed }}"
  when: mosquitto_enabled is true

- name: Stop {{ ansible_nas_app_name }}
  block:
    - name: Stop {{ ansible_nas_app_name }} Container
      community.docker.docker_container:
        name: "{{ mosquitto_container_name }}"
        state: absent
  when: mosquitto_enabled is false

- name: Data Archive {{ ansible_nas_app_name }}
  include_role:
    name: ansible-nas-archive
  vars:
    target_data_dir: "{{ mosquitto_data_directory }}"
  when:
    - archive_app_data_enabled is true
    - mosquitto_enabled is false