---
- name: Start {{ ansible_nas_app_name }}
  block:
    - name: Create {{ ansible_nas_app_name }} Data Directory
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
      with_items:
        - "{{ sabnzbd_data_directory }}"

    - name: Create {{ ansible_nas_app_name }} Container
      community.docker.docker_container:
        name: "{{ sabnzbd_container_name }}"
        image: "{{ sabnzbd_image_name }}:{{ sabnzbd_image_version }}"
        pull: true
        volumes:
          - "{{ sabnzbd_data_directory }}:/config:rw"
          - "{{ sabnzbd_downloads_directory }}:/downloads"
          - "{{ sabnzbd_incomplete_directory }}:/incomplete-downloads"
        ports:
          - "{{ sabnzbd_port }}:8080"
        env:
          TZ: "{{ ansible_nas_timezone }}"
          PUID: "{{ sabnzbd_user_id }}"
          PGID: "{{ sabnzbd_group_id }}"
        restart_policy: unless-stopped
        cpu_shares: "{{ sabnzbd_cpu_shares }}"
        memory: "{{ sabnzbd_memory }}"
        labels:
          autoheal: "{{ sabnzbd_autoheal }}"
          com.centurylinklabs.watchtower.monitor-only: "{{ sabnzbd_watchtower_monitor_only }}"
          traefik.enable: "{{ sabnzbd_available_externally | string }}"
          traefik.http.routers.sabnzbd.rule: "Host(`{{ sabnzbd_hostname }}.{{ ansible_nas_domain }}`)"
          traefik.http.routers.sabnzbd.tls.certresolver: "letsencrypt"
          traefik.http.routers.sabnzbd.tls.domains[0].main: "{{ ansible_nas_domain }}"
          traefik.http.routers.sabnzbd.tls.domains[0].sans: "*.{{ ansible_nas_domain }}"
          traefik.http.services.sabnzbd.loadbalancer.server.port: "8080"
  when: sabnzbd_enabled is true

- name: Stop {{ ansible_nas_app_name }}
  block:
    - name: Stop {{ ansible_nas_app_name }} Container
      community.docker.docker_container:
        name: "{{ sabnzbd_container_name }}"
        state: absent
  when: sabnzbd_enabled is false

- name: Data Archive {{ ansible_nas_app_name }}
  block:
    - name: Check for {{ ansible_nas_app_name }} Data Directory
      stat:
        path: "{{ sabnzbd_data_directory }}"
      register: dir_stat

    - name: Archive {{ ansible_nas_app_name }} Data Directory
      ansible.builtin.archive:
        path: "{{ sabnzbd_data_directory }}"
        dest: "{{ docker_home }}/{{ ansible_nas_app_name | lower }}.zip"
        force_archive: true
        format: zip
        owner: ansible-nas
        group: ansible-nas
        mode: u=rw,g=rw
        remove: true
      when: dir_stat.stat.exists
  when: sabnzbd_enabled is false and archive_app_data_enabled is true
