---
- name: Verify
  hosts: all
  gather_facts: false
  tasks:
    - ansible.builtin.include_vars:
        file: ../../defaults/main.yml

    - name: Get {{ open_webui_proper_name }} container state
      community.docker.docker_container_info:
        name: "{{ open_webui_container_name }}"
      register: result_open_webui

    - name: Get {{ open_webui_proper_name }} OpenedAI container state
      community.docker.docker_container_info:
        name: "{{ open_webui_openedai_container_name }}"
      register: result_openedai

    - name: Check {{ open_webui_proper_name }} is running
      ansible.builtin.assert:
        that:
          - result_open_webui.container['State']['Status'] == "running"
          - result_open_webui.container['State']['Restarting'] == false
          - result_openedai.container['State']['Status'] == "running"
          - result_openedai.container['State']['Restarting'] == false
