---
- name: Verify
  hosts: all
  gather_facts: false
  tasks:
    - ansible.builtin.include_vars:
        file: ../../defaults/main.yml

    - name: Try and stop and remove {{ open_webui_proper_name }}
      community.docker.docker_container:
        name: "{{ open_webui_container_name }}"
        state: absent
      register: result_open_webui

    - name: Try and stop and remove {{ open_webui_proper_name }} OpenedAI
      community.docker.docker_container:
        name: "{{ open_webui_openedai_container_name }}"
        state: absent
      register: result_openedai

    - name: Check {{ open_webui_proper_name }} is stopped
      ansible.builtin.assert:
        that:
          - not result_open_webui.changed
          - not result_openedai.changed
