---
# ANE
wallabag_proper_name: "Wallabag"
wallabag_enabled: false
wallabag_traefik_enabled: false
wallabag_traefik_whitelist: "{{ lan }}"

# Directories
wallabag_data_directory: "{{ docker_home }}/wallabag"

# Networking
wallabag_port_http: "7780"
wallabag_hostname: "wallabag"

# Container
wallabag_container_name: "wallabag"
wallabag_image_name: "wallabag/wallabag"
wallabag_image_version: "latest"

# specs
wallabag_cpu_shares: 1024
wallabag_memory: "512M"
wallabag_memory_swap: -1

# app
wallabag_env_symfony_env_domain_name: "http://{{ hostvars[inventory_hostname]['ansible_facts']['default_ipv4']['address'] }}:{{ wallabag_port_http }}"

# autoheal
wallabag_autoheal_enabled: false

# dockflare
wallabag_dockflare_enabled: false
wallabag_dockflare_access_group: ""

# healthcheck
wallabag_healthcheck_test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://127.0.0.1:80/login || exit 1"]
wallabag_healthcheck_interval: 30s
wallabag_healthcheck_timeout: 10s
wallabag_healthcheck_retries: 3
wallabag_healthcheck_start_period: 60s

# homepage
wallabag_homepage_group: "Apps"
wallabag_homepage_icon: "wallabag.png"
wallabag_homepage_href: "http://{{ hostvars[inventory_hostname]['ansible_facts']['default_ipv4']['address'] }}:{{ wallabag_port_http }}"
wallabag_homepage_showstats: false

# repliqate
wallabag_repliqate_enabled: false
wallabag_repliqate_engine: "restic"
wallabag_repliqate_schedule: "@daily 3am"
wallabag_repliqate_backup_id: "{{ wallabag_container_name }}"
wallabag_repliqate_retention: "30d"

# tinyauth
wallabag_tinyauth_enabled: false

# watchtower
wallabag_watchtower_enabled: false