---
# ANE
ansible_nas_app_name: "Wallabag"
wallabag_enabled: false
wallabag_available_externally: false
wallabag_traefik_whitelist: "{{ lan }}"

# Directories
wallabag_data_directory: "{{ docker_home }}/wallabag"

# app
wallabag_env_symfony_env_domain_name: "https://{{ wallabag_hostname }}.{{ ansible_nas_domain }}"

# Networking
wallabag_port_http: "7780"
wallabag_hostname: "wallabag"

# Container
wallabag_memory: "512M"
wallabag_container_name: "wallabag"
wallabag_image_name: "wallabag/wallabag"

# specs
wallabag_image_version: "latest"
wallabag_cpu_shares: 1024

# autoheal
wallabag_autoheal: "false"

# dockflare
wallabag_dockflare_tunnel: "false"
wallabag_dockflare_access_group: ""

# homepage
wallabag_homepage_group: "Apps"
wallabag_homepage_icon: "wallabag.png"
wallabag_homepage_href: "http://{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}:{{ wallabag_port_http }}"
wallabag_homepage_showstats: "false"

# repliqate
wallabag_repliqate_enabled: "false"
wallabag_repliqate_engine: "restic"
wallabag_repliqate_schedule: "@daily 3am"
wallabag_repliqate_backup_id: "{{ wallabag_container_name }}"
wallabag_repliqate_retention: "30d"

# tinyauth
wallabag_tinyauth_enabled: false

# watchtower
wallabag_watchtower_enable: "false"