---
- name: Start {{ ansible_nas_app_name }}
  block:
    - name: Create {{ ansible_nas_app_name }} Directories
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
      with_items:
        - "{{ homarr_data_directory }}"
        - "{{ homarr_data_directory }}/appdata"

    - name: Create {{ ansible_nas_app_name }} Container
      community.docker.docker_container:
        container_default_behavior: "compatibility"
        name: "{{ homarr_container_name }}"
        hostname: "{{ homarr_container_name }}"
        image: "{{ homarr_image_name }}:{{ homarr_image_tag }}"
        pull: true
        volumes:
        - "{{ homarr_data_directory }}/appdata:/appdata"
        ports:
          - "{{ homarr_port_http }}:7575"
        env:
          SECRET_ENCRYPTION_KEY: "{{ homarr_env_secret_encryption_key }}"
          TZ: "{{ ansible_nas_timezone }}"
        labels:
          autoheal: "{{ homarr_autoheal }}"
          com.centurylinklabs.watchtower.enable: "{{ homarr_watchtower_enable }}"
          dockflare.enable: "{{ homarr_dockflare_tunnel }}"
          dockflare.access.group: "{{ homarr_dockflare_access_group }}"
          dockflare.hostname: "{{ homarr_hostname }}.{{ ansible_nas_domain }}"
          dockflare.service: "http://{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}:{{ homarr_port_http }}"
          homepage.name: "{{ ansible_nas_app_name }}"
          homepage.group: "{{ homarr_homepage_group }}"
          homepage.icon: "{{ homarr_homepage_icon }}"
          homepage.href: "{{ homarr_homepage_href }}"
          homepage.siteMonitor: "http://{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}:{{ homarr_port_http }}"
          homepage.description: "{{ 'A modern and easy to use dashboard.' if homepage_show_description else omit }}"
          homepage.server: "my-docker"
          homepage.container: "{{ homarr_container_name }}"
          homepage.showStats: "{{ homarr_homepage_showstats }}"
          repliqate.enabled: "{{ homarr_repliqate_enabled }}"
          repliqate.engine: "{{ homarr_repliqate_engine }}"
          repliqate.schedule: "{{ homarr_repliqate_schedule }}"
          repliqate.backup_id: "{{ homarr_repliqate_backup_id }}"
          repliqate.retention: "{{ homarr_repliqate_retention }}"
          traefik.enable: "{{ homarr_available_externally | string }}"
          traefik.http.routers.homarr.rule: "Host(`{{ homarr_hostname }}.{{ ansible_nas_domain }}`)"
          traefik.http.routers.homarr.tls.certresolver: "letsencrypt"
          traefik.http.routers.homarr.tls.domains[0].main: "{{ ansible_nas_domain }}"
          traefik.http.routers.homarr.tls.domains[0].sans: "*.{{ ansible_nas_domain }}"
          traefik.http.routers.homarr.middlewares: "homarr@docker{{ ',tinyauth-auth@docker' if homarr_tinyauth_enabled | bool else '' }}"
          traefik.http.middlewares.homarr.IPAllowList.sourcerange: "{{ homarr_traefik_whitelist }}"
          traefik.http.services.homarr.loadbalancer.server.port: "7575"
          wud.tag.include: '^\d+\.\d+\.\d+.*$'
          wud.tag.transform.type: "semver"
          wud.link.template: "https://github.com/Homarr/Homarr/releases"
        cpu_shares: "{{ homarr_cpu_shares }}"
        memory: "{{ homarr_memory }}"
        restart_policy: unless-stopped

    - name: Access {{ ansible_nas_app_name }} at
      ansible.builtin.debug:
        msg: >-
              {{
                ['http://' + hostvars[inventory_hostname]['ansible_default_ipv4']['address'] + ':' + (homarr_port_http | string)] +
                (['https://' + homarr_hostname + '.' + ansible_nas_domain] if (homarr_available_externally is true or homarr_dockflare_tunnel is true) else [])
              }}
  when: homarr_enabled is true

- name: Stop {{ ansible_nas_app_name }}
  block:
    - name: Stop {{ ansible_nas_app_name }} Container
      community.docker.docker_container:
        name: "{{ homarr_container_name }}"
        state: absent
  when: homarr_enabled is false

- name: Data Archive {{ ansible_nas_app_name }}
  include_role:
    name: ansible-nas-archive
  vars:
    target_data_dir: "{{ homarr_data_directory }}"
  when:
    - archive_app_data_enabled is true
    - homarr_enabled is false