---
- name: Start Dokemon
  block:
    - name: Create {{ ansible_nas_app_name }} Directories
      file:
        path: "{{ item }}"
        state: directory
      with_items:
        - "{{ dokemon_data_directory }}"

    - name: Create {{ ansible_nas_app_name }} Container
      community.docker.docker_container:
        container_default_behavior: "compatibility"
        name: "{{ dokemon_container_name }}"
        hostname: "{{ dokemon_container_name }}"
        image: "{{ dokemon_image_name }}:{{ dokemon_image_tag }}"
        pull: true
        ports:
          - "{{ dokemon_port_http }}:9090"
        volumes:
          - "{{ dokemon_data_directory }}:/data"
          - "/var/run/docker.sock:/var/run/docker.sock"
        network_mode: bridge
        env:
          TZ: "{{ ansible_nas_timezone }}"
        labels:
          autoheal: "{{ dokemon_autoheal }}"
          com.centurylinklabs.watchtower.enable: "{{ dokemon_watchtower_enable }}"
          dockflare.enable: "{{ dokemon_dockflare_tunnel }}"
          dockflare.access.group: "{{ dokemon_dockflare_access_group }}"
          dockflare.hostname: "{{ dokemon_hostname }}.{{ ansible_nas_domain }}"
          dockflare.service: "http://{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}:{{ dokemon_port }}"
          homepage.name: "{{ ansible_nas_app_name }}"
          homepage.group: "{{ dokemon_homepage_group }}"
          homepage.icon: "{{ dokemon_homepage_icon }}"
          homepage.href: "{{ dokemon_homepage_href }}"
          homepage.siteMonitor: "http://{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}:{{ dokemon_port_http }}"
          homepage.description: "{{ 'Docker Container Management GUI' if homepage_show_description else omit }}"
          homepage.server: "my-docker"
          homepage.container: "{{ dokemon_container_name }}"
          homepage.showStats: "{{ dokemon_homepage_showstats }}"
          repliqate.enabled: "{{ dokemon_repliqate_enabled }}"
          repliqate.engine: "{{ dokemon_repliqate_engine }}"
          repliqate.schedule: "{{ dokemon_repliqate_schedule }}"
          repliqate.backup_id: "{{ dokemon_repliqate_backup_id }}"
          repliqate.retention: "{{ dokemon_repliqate_retention }}"
          traefik.enable: "{{ dokemon_available_externally | string }}"
          traefik.http.routers.dokemon.rule: "Host(`{{ dokemon_hostname }}.{{ ansible_nas_domain }}`)"
          traefik.http.routers.dokemon.tls.certresolver: "letsencrypt"
          traefik.http.routers.dokemon.tls.domains[0].main: "{{ ansible_nas_domain }}"
          traefik.http.routers.dokemon.tls.domains[0].sans: "*.{{ ansible_nas_domain }}"
          traefik.http.routers.frontend.middlewares: "{{ dokemon_hostname }}"
          traefik.http.routers.dokemon.middlewares: "{{ dokemon_hostname }}@docker"
          traefik.http.middlewares.dokemon.IPAllowList.sourcerange: "{{ dokemon_traefik_whitelist }}"
          traefik.http.services.dokemon.loadbalancer.server.port: "9090"
          wud.tag.include: '^\d+\.\d+\.\d+.*$'
          wud.tag.transform.type: "semver"
          wud.link.template: "https://hub.docker.com/r/productiveops/dokemon"
        cpu_shares: "{{ dokemon_cpu_shares }}"
        memory: "{{ dokemon_memory }}"
        restart_policy: unless-stopped

    - name: Access {{ ansible_nas_app_name }} at
      ansible.builtin.debug:
        msg: >-
              {{
                ['http://' + hostvars[inventory_hostname]['ansible_default_ipv4']['address'] + ':' + (dokemon_port_http | string)] +
                (['https://' + dokemon_hostname + '.' + ansible_nas_domain] if (dokemon_available_externally is true or dokemon_dockflare_tunnel is true) else [])
              }}
  when: dokemon_enabled is true

- name: Stop {{ ansible_nas_app_name }}
  block:
    - name: Stop {{ ansible_nas_app_name }} Container
      community.docker.docker_container:
        name: "{{ dokemon_container_name }}"
        state: absent
  when: dokemon_enabled is false

- name: Data Archive {{ ansible_nas_app_name }}
  block:
    - name: Check for {{ ansible_nas_app_name }} Data Directory
      stat:
        path: "{{ dokemon_data_directory }}"
      register: dir_stat

    - name: Archive {{ ansible_nas_app_name }} Data Directory
      ansible.builtin.archive:
        path: "{{ dokemon_data_directory }}"
        dest: "{{ docker_home }}/{{ ansible_nas_app_name | lower }}.zip"
        force_archive: true
        format: zip
        owner: ansible-nas
        group: ansible-nas
        mode: u=rw,g=rw
        remove: true
      when: dir_stat.stat.exists
  when: dokemon_enabled is false and archive_app_data_enabled is true
