---
# ANE
ansible_nas_app_name: "Cloudflare DDNS"
cloudflare_ddns_enabled: false

# Data directory for config file
cloudflare_data_directory: "{{ docker_home }}/cloudflare-ddns"

# Your domain name
cloudflare_zone: "{{ ansible_nas_domain }}"

# The hostname you want the container to update. You shouldn't need to change this.
cloudflare_host: "*.{{ cloudflare_zone }}"

# Cloudflare scoped token (https://github.com/joshuaavalon/docker-cloudflare#api-token)
# Make sure token permissions include #DNS:Edit and #Zone:Read
cloudflare_token: "abcdabcdabcd123412341234"

# Set to true to make traffic go through the CloudFlare CDN.
# Note that if the cloudflare host is a wildcard (the default), this must be false, as cloudflare
# does not support http proxy of wildcard CNAMEs.
cloudflare_proxy: false

# Set to AAAA to use set IPv6 records instead of IPv4 records.
cloudflare_type: "A"

# specs
cloudflare_memory: 256MB

# docker
cloudflare_container_name: "cloudflare-ddns"
cloudflare_image_name: "joshava/cloudflare-ddns"
cloudflare_image_version: "latest"
cloudflare_cpu_shares: 1024

# autoheal
cloudflare_autoheal: "false"

# homepage
cloudflare_homepage_group: "Network"
cloudflare_homepage_icon: "cloudflare.png"
cloudflare_homepage_showstats: "false"

# repliqate
cloudflare_repliqate_enabled: "false"
cloudflare_repliqate_engine: "restic"
cloudflare_repliqate_schedule: "@daily 3am"
cloudflare_repliqate_backup_id: "{{ cloudflare_container_name }}"
cloudflare_repliqate_retention: "30d"

# watchtower
cloudflare_watchtower_enable: "false"