---
- name: Start {{ ansible_nas_app_name }}
  block:
    - name: Create {{ ansible_nas_app_name }} Directories
      file:
        path: "{{ item }}"
        state: directory
      with_items:
        - "{{ peppermint_data_directory }}"
        - "{{ peppermint_data_directory }}/db"

    - name: Create {{ ansible_nas_app_name }} DB Container
      community.docker.docker_container:
        container_default_behavior: "compatibility"
        name: "{{ peppermint_db_container_name }}"
        hostname: "{{ peppermint_db_container_name }}"
        image: "{{ peppermint_db_image_name }}:{{ peppermint_db_image_tag }}"
        pull: true
        volumes:
          - "{{ peppermint_data_directory }}/db:/var/lib/postgresql/data"
        env:
          POSTGRES_USER: "peppermint"
          POSTGRES_PASSWORD: "{{ peppermint_db_password }}"
          POSTGRES_DB: "peppermint"
        labels:
          autoheal: "{{ peppermint_db_autoheal }}"
          com.centurylinklabs.watchtower.enable: "{{ peppermint_db_watchtower_enable }}"
          dockflare.enable: "false"
          homepage.name: "{{ ansible_nas_app_name }} PostgreSQL"
          homepage.group: "{{ peppermint_db_homepage_group }}"
          homepage.icon: "{{ peppermint_db_homepage_icon }}"
          homepage.href: "{{ peppermint_db_homepage_href }}"
          homepage.description: "{{ 'MariaDB Server is a high performing open source relational database, forked from MySQL.' if homepage_show_description else omit }}"
          homepage.server: "my-docker"
          homepage.container: "{{ peppermint_db_container_name }}"
          homepage.showStats: "{{ peppermint_db_homepage_showstats }}"
          traefik.enable: "false"
          wud.tag.include: '^\d+\.\d+.*$'
          wud.tag.transform.type: "semver"
          wud.link.template: "https://hub.docker.com/_/postgres"
        cpu_shares: "{{ peppermint_db_cpu_shares }}"
        memory: "{{ peppermint_db_memory }}"
        restart_policy: unless-stopped

    - name: Create {{ ansible_nas_app_name }} Container
      community.docker.docker_container:
        container_default_behavior: "compatibility"
        name: "{{ peppermint_container_name }}"
        hostname: "{{ peppermint_container_name }}"
        image: "{{ peppermint_image_name }}:{{ peppermint_image_tag }}"
        pull: true
        ports:
          - "{{ peppermint_port_http }}:3000"
          - 5003:5003
        env:
          DB_USERNAME: "peppermint"
          DB_PASSWORD: "{{ peppermint_db_password }}"
          DB_HOST: "{{ peppermint_db_container_name }}"
          SECRET: 'peppermint4life'
          TZ: "{{ ansible_nas_timezone }}"
        links:
          - "{{ peppermint_db_container_name }}"
        labels:
          autoheal: "{{ peppermint_autoheal }}"
          com.centurylinklabs.watchtower.enable: "{{ peppermint_watchtower_enable }}"
          dockflare.enable: "{{ peppermint_dockflare_tunnel }}"
          dockflare.access.group: "{{ peppermint_dockflare_access_group }}"
          dockflare.hostname: "{{ peppermint_hostname }}.{{ ansible_nas_domain }}"
          dockflare.service: "http://{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}:{{ peppermint_port_http }}"
          homepage.name: "{{ ansible_nas_app_name }}"
          homepage.group: "{{ peppermint_homepage_group }}"
          homepage.icon: "{{ peppermint_homepage_icon }}"
          homepage.href: "{{ peppermint_homepage_href }}"
          homepage.description: "{{ 'An open source issue management & help desk solution. A zendesk & jira alternative' if homepage_show_description else omit }}"
          homepage.siteMonitor: "http://{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}:{{ peppermint_port_http }}"
          homepage.server: "my-docker"
          homepage.container: "{{ peppermint_container_name }}"
          homepage.showStats: "{{ peppermint_homepage_showstats }}"
          traefik.enable: "{{ peppermint_available_externally | string }}"
          traefik.http.routers.peppermint.rule: "Host(`peppermint.{{ ansible_nas_domain }}`)"
          traefik.http.routers.peppermint.tls.certresolver: "letsencrypt"
          traefik.http.routers.peppermint.tls.domains[0].main: "{{ ansible_nas_domain }}"
          traefik.http.routers.peppermint.tls.domains[0].sans: "*.{{ ansible_nas_domain }}"
          traefik.http.routers.frontend.middlewares: "{{ peppermint_hostname }}"
          traefik.http.routers.peppermint.middlewares: "{{ peppermint_hostname }}@docker"
          traefik.http.middlewares.peppermint.IPAllowList.sourcerange: "{{ peppermint_traefik_whitelist }}"
          traefik.http.services.peppermint.loadbalancer.server.port: "3000"
          wud.tag.include: '^\d+\.\d+\.\d+.*$'
          wud.tag.transform.type: "semver"
          wud.link.template: "https://hub.docker.com/r/pepperlabs/peppermint"
        cpu_shares: "{{ peppermint_cpu_shares }}"
        memory: "{{ peppermint_memory }}"
        restart_policy: unless-stopped
  when: peppermint_enabled is true

- name: Stop {{ ansible_nas_app_name }}
  block:
    - name: Stop {{ ansible_nas_app_name }} Container
      community.docker.docker_container:
        name: "{{ peppermint_container_name }}"
        state: absent

    - name: Stop {{ ansible_nas_app_name }} DB Container
      community.docker.docker_container:
        name: "{{ peppermint_db_container_name }}"
        state: absent
  when: peppermint_enabled is false

- name: Data Archive {{ ansible_nas_app_name }}
  block:
    - name: Check for {{ ansible_nas_app_name }} Data Directory
      stat:
        path: "{{ peppermint_data_directory }}"
      register: dir_stat

    - name: Archive {{ ansible_nas_app_name }} Data Directory
      ansible.builtin.archive:
        path: "{{ peppermint_data_directory }}"
        dest: "{{ docker_home }}/{{ ansible_nas_app_name | lower }}.zip"
        force_archive: true
        format: zip
        owner: ansible-nas
        group: ansible-nas
        mode: u=rw,g=rw
        remove: true
      when: dir_stat.stat.exists
  when: peppermint_enabled is false and archive_app_data_enabled is true

