---
##      _    _   _ _____
##     / \  | \ | | ____|
##    / _ \ |  \| |  _|
##   / ___ \| |\  | |___
##  /_/   \_\_| \_|_____|
##
##  Ansible-NAS-Enhanced - https://github.com/bcurran3/ansible-nas-enhanced

# Add your all.yml config overrides to this file.
# See group_vars/all.yml for all possible settings.

###
### Personal and computer specific defaults you want to customize:
###
ansible_nas_hostname: ANE # hostname to use for your ANE server
ansible_nas_timezone: Etc/UTC # timezone to use for your ANE server https://nodatime.org/TimeZones
ansible_nas_user: yourname # your login account for your ANE server
ansible_nas_email: yourname@myemail.com # your e-mail address
ansible_nas_domain: mydomain.com # your domain
ansible_nas_app_admin_password: "topsecret" # default admin password for ANE apps (where configurable)
samba_shares_root: /data/shares # The location where all shares will be created by default. Can be overridden on a per-share basis.
nfs_shares_root: /data/shares # The location for NFS shares

###
### Media Libraries / data directories you want to
### publish over Samba and NFS: (i.e. a proper NAS)
###
anime_share_enabled: false
audiobooks_share_enabled: false
backups_share_enabled: false
books_share_enabled: false
code_share_enabled: false
comics_share_enabled: false
courses_share_enabled: false
documents_share_enabled: false
downloads_share_enabled: false
dump_share_enabled: false
games_share_enabled: false
movies_share_enabled: false
music_share_enabled: false
photos_share_enabled: false
podcasts_share_enabled: false
porn_share_enabled: false
public_share_enabled: false
recordings_share_enabled: false
roms_share_enabled: false
torrents_share_enabled: false
tv_share_enabled: false
media_root_share_enabled: false # share everything from one place instead of individually

###
### List of APT packages you want installed:
###
ansible_nas_extra_packages:
  - ansible-lint
  - iputils-ping
  - nano
#  - cockpit
#  - dnsutils
#  - "linux-generic-hwe-{{ ansible_distribution_version }}"
#  - mc
#  - mdm
#  - net-tools
#  - nfs-common
#  - qemu-guest-agent
#  - samba

###
### Applications to enable:
###
homepage_enabled: true
portainer_enabled: true
