---
- name: Start {{ ansible_nas_app_name }}
  block:
    - name: Create {{ ansible_nas_app_name }} Directories
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
      with_items:
        - "{{ minio_data_directory }}/data"

    - name: Create {{ ansible_nas_app_name }} Container
      community.docker.docker_container:
        container_default_behavior: "compatibility"
        name: "{{ minio_container_name }}"
        hostname: "{{ minio_container_name }}"
        image: "{{ minio_image_name }}:{{ minio_image_version }}"
        pull: true
        ports:
          - "{{ minio_api_port }}:9000"
          - "{{ minio_console_port }}:{{ minio_console_port }}"
        command: 'server /data --console-address ":{{ minio_console_port }}"'
        volumes:
          - "{{ minio_data_directory }}/data:/data"
        env:
          MINIO_ROOT_USER: "{{ minio_admin_username }}"
          MINIO_ROOT_PASSWORD: "{{ minio_admin_password }}"
          MINIO_PROMETHEUS_AUTH_TYPE: public
        labels:
          autoheal: "{{ minio_autoheal }}"
          com.centurylinklabs.watchtower.enable: "{{ minio_watchtower_enable }}"
          dockflare.enable: "{{ minio_dockflare_tunnel }}"
          dockflare.access.group: "{{ minio_dockflare_access_group }}"
          dockflare.hostname: "{{ minio_hostname }}.{{ ansible_nas_domain }}"
          dockflare.service: "http://{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}:{{ minio_api_port }}"
          homepage.name: "{{ ansible_nas_app_name }}"
          homepage.group: "{{ minio_homepage_group }}"
          homepage.icon: "{{ minio_homepage_icon }}"
          homepage.href: "{{ minio_homepage_href }}"
          homepage.description: "{{ 'minio description' if homepage_show_description else omit }}"
          homepage.server: "my-docker"
          homepage.container: "{{ minio_container_name }}"
          homepage.showStats: "{{ minio_homepage_showstats }}"
          homepage.siteMonitor: "http://{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}:{{ minio_port }}"
          traefik.enable: "{{ minio_available_externally | string }}"
          traefik.http.routers.minio.rule: "Host(`{{ minio_hostname }}.{{ ansible_nas_domain }}`)"
          traefik.http.routers.minio.tls.certresolver: "letsencrypt"
          traefik.http.routers.minio.tls.domains[0].main: "{{ ansible_nas_domain }}"
          traefik.http.routers.minio.tls.domains[0].sans: "*.{{ ansible_nas_domain }}"
          traefik.http.routers.frontend.middlewares: "{{ minio_hostname }}"
          traefik.http.routers.minio.middlewares: "{{ minio_hostname }}@docker"
          traefik.http.middlewares.minio.IPAllowList.sourcerange: "{{ minio_traefik_whitelist }}"
          traefik.http.services.minio.loadbalancer.server.port: "9000"
          wud.watch.digest: "true"
          wud.link.template: "https://hub.docker.com/r/minio/minio"
        cpu_shares: "{{ minio_cpu_shares }}"
        memory: "{{ minio_memory }}"
        restart_policy: unless-stopped
  when: minio_enabled is true

- name: Stop {{ ansible_nas_app_name }}
  block:
    - name: Stop {{ ansible_nas_app_name }} Container
      community.docker.docker_container:
        name: "{{ minio_container_name }}"
        state: absent
  when: minio_enabled is false

- name: Data Archive {{ ansible_nas_app_name }}
  block:
    - name: Check for {{ ansible_nas_app_name }} Data Directory
      stat:
        path: "{{ minio_data_directory }}"
      register: dir_stat

    - name: Archive {{ ansible_nas_app_name }} Data Directory
      ansible.builtin.archive:
        path: "{{ minio_data_directory }}"
        dest: "{{ docker_home }}/{{ ansible_nas_app_name | lower }}.zip"
        force_archive: true
        format: zip
        owner: ansible-nas
        group: ansible-nas
        mode: u=rw,g=rw
        remove: true
      when: dir_stat.stat.exists
  when: minio_enabled is false and archive_app_data_enabled is true
