---
- name: Start {{ ansible_nas_app_name }}
  block:
    - name: Create {{ ansible_nas_app_name }} Directories
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
      with_items:
        - "{{ minio_data_directory }}/data"

    - name: Set {{ ansible_nas_app_name }} FQDN var overrides
      ansible.builtin.set_fact:
        minio_homepage_href: "https://{{ minio_hostname }}.{{ ansible_nas_domain }}"
      when: minio_traefik_enabled | bool or minio_dockflare_enabled | bool

    - name: Create {{ ansible_nas_app_name }} Container
      community.docker.docker_container:
        container_default_behavior: "compatibility"
        name: "{{ minio_container_name }}"
        hostname: "{{ minio_container_name }}"
        image: "{{ minio_image_name }}:{{ minio_image_version }}"
        pull: true
        ports:
          - "{{ minio_api_port }}:9000"
          - "{{ minio_console_port }}:{{ minio_console_port }}"
        command: 'server /data --console-address ":{{ minio_console_port }}"'
        volumes:
          - "{{ minio_data_directory }}/data:/data"
        env:
          MINIO_ROOT_USER: "{{ minio_admin_username }}"
          MINIO_ROOT_PASSWORD: "{{ minio_admin_password }}"
          MINIO_PROMETHEUS_AUTH_TYPE: "public"
        labels:
          autoheal: "{{ minio_autoheal_enabled | ternary('true', 'false') }}"
          com.centurylinklabs.watchtower.enable: "{{ minio_watchtower_enabled | ternary('true', 'false') }}"
          dockflare.enable: "{{ minio_dockflare_enabled | ternary('true', 'false') }}"
          dockflare.access.group: "{{ minio_dockflare_access_group }}"
          dockflare.hostname: "{{ minio_hostname }}.{{ ansible_nas_domain }}"
          dockflare.service: "http://{{ hostvars[inventory_hostname]['ansible_facts']['default_ipv4']['address'] }}:{{ minio_api_port }}"
          homepage.name: "{{ ansible_nas_app_name }}"
          homepage.group: "{{ minio_homepage_group }}"
          homepage.icon: "{{ minio_homepage_icon }}"
          homepage.href: "{{ minio_homepage_href }}"
          homepage.description: "{{ 'high-performance S3 compatible object store' if homepage_show_description else omit }}"
          homepage.server: "my-docker"
          homepage.container: "{{ minio_container_name }}"
          homepage.showStats: "{{ minio_homepage_showstats | ternary('true', 'false') }}"
          homepage.siteMonitor: "http://{{ hostvars[inventory_hostname]['ansible_facts']['default_ipv4']['address'] }}:{{ minio_api_port }}"
          repliqate.enabled: "{{ minio_repliqate_enabled | ternary('true', 'false') }}"
          repliqate.engine: "{{ minio_repliqate_engine }}"
          repliqate.schedule: "{{ minio_repliqate_schedule }}"
          repliqate.backup_id: "{{ minio_repliqate_backup_id }}"
          repliqate.retention: "{{ minio_repliqate_retention }}"
          traefik.enable: "{{ minio_traefik_enabled | ternary('true', 'false') }}"
          traefik.http.routers.minio.rule: "Host(`{{ minio_hostname }}.{{ ansible_nas_domain }}`)"
          traefik.http.routers.minio.tls.certresolver: "letsencrypt"
          traefik.http.routers.minio.tls.domains[0].main: "{{ ansible_nas_domain }}"
          traefik.http.routers.minio.tls.domains[0].sans: "*.{{ ansible_nas_domain }}"
          traefik.http.routers.minio.middlewares: "{{ minio_hostname }}@docker{{ ',tinyauth-auth@docker' if minio_tinyauth_enabled | bool else '' }}"
          traefik.http.middlewares.minio.IPAllowList.sourcerange: "{{ minio_traefik_whitelist }}"
          traefik.http.services.minio.loadbalancer.server.port: "9000"
          wud.watch.digest: "true"
          wud.link.template: "https://hub.docker.com/r/minio/minio"
        cpu_shares: "{{ minio_cpu_shares }}"
        memory: "{{ minio_memory }}"
        memory_swap: "{{ minio_memory_swap }}"
        restart_policy: unless-stopped

    - name: Access {{ ansible_nas_app_name }} at
      ansible.builtin.debug:
        msg: >-
              {{
                ['http://' + hostvars[inventory_hostname]['ansible_facts']['default_ipv4']['address'] + ':' + (minio_api_port | string)] +
                (['https://' + minio_hostname + '.' + ansible_nas_domain] if (minio_traefik_enabled is true or minio_dockflare_enabled is true) else [])
              }}
  when: minio_enabled is true

- name: Stop {{ ansible_nas_app_name }}
  block:
    - name: Stop {{ ansible_nas_app_name }} Container
      community.docker.docker_container:
        name: "{{ minio_container_name }}"
        state: absent
  when: minio_enabled is false

- name: Data Archive {{ ansible_nas_app_name }}
  include_role:
    name: ansible-nas-archive
  vars:
    target_data_dir: "{{ minio_data_directory }}"
  when:
    - archive_app_data_enabled is true
    - minio_enabled is false