---
- name: Start {{ ansible_nas_app_name }}
  block:
    - name: Create {{ ansible_nas_app_name }} Directories
      file:
        path: "{{ item }}"
        state: directory
      with_items:
        - "{{ searxng_data_directory }}"
        - "{{ searxng_data_directory }}/etc"

    - name: Create {{ ansible_nas_app_name }} Container
      community.docker.docker_container:
        container_default_behavior: "compatibility"
        name: "{{ searxng_container_name }}"
        hostname: "{{ searxng_container_name }}"
        image: "{{ searxng_image_name }}:{{ searxng_image_tag }}"
        pull: true
        cpu_shares: "{{ searxng_cpu_shares }}"
        ports:
          - "{{ searxng_port_http }}:8080"
        volumes:
          - "{{ searxng_data_directory }}/etc:/etc/searxng"
        network_mode: bridge
        env:
          BASE_URL: "http://localhost:8080"
          INSTANCE_NAME: "my-instance"
          URL: "searxng.{{ ansible_nas_domain }}"
          TZ: "{{ ansible_nas_timezone }}"
        labels:
          autoheal: "{{ searxng_autoheal }}"
          com.centurylinklabs.watchtower.monitor-only: "{{ searxng_watchtower_monitor_only }}"
          homepage.name: "{{ ansible_nas_app_name }}"
          homepage.group: "{{ searxng_homepage_group }}"
          homepage.icon: "{{ searxng_homepage_icon }}"
          homepage.href: "{{ searxng_homepage_href }}"
          homepage.siteMonitor: "http://{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}:{{ searxng_port_http }}"
          homepage.description: "{{ 'SearXNG is a free internet metasearch engine which aggregates results from various search services and databases.' if homepage_show_description else omit }}"
          homepage.server: "my-docker"
          homepage.container: "{{ searxng_container_name }}"
          homepage.showStats: "{{ searxng_homepage_showStats }}"
          traefik.enable: "{{ searxng_available_externally | string }}"
          traefik.http.routers.searxng.rule: "Host(`{{ searxng_hostname }}.{{ ansible_nas_domain }}`)"
          traefik.http.routers.searxng.tls.certresolver: "letsencrypt"
          traefik.http.routers.searxng.tls.domains[0].main: "{{ ansible_nas_domain }}"
          traefik.http.routers.searxng.tls.domains[0].sans: "*.{{ ansible_nas_domain }}"
          traefik.http.routers.frontend.middlewares: "{{ searxng_hostname }}"
          traefik.http.routers.searxng.middlewares: "{{ searxng_hostname }}@docker"
          traefik.http.middlewares.searxng.IPAllowList.sourcerange: "{{ searxng_traefik_whitelist }}"
          traefik.http.services.searxng.loadbalancer.server.port: "8080"
#         wud.tag.include: '^\d+\.\d+\.\d+$$'
#         wud.link.template: "https://github.com/fmartinou/whats-up-docker/releases/tag/$${major}.$${minor}.$${patch}"
        memory: "{{ searxng_memory_limit }}"
        restart_policy: unless-stopped
  when: searxng_enabled is true

- name: Stop {{ ansible_nas_app_name }}
  block:
    - name: Stop {{ ansible_nas_app_name }} Container
      community.docker.docker_container:
        name: "{{ searxng_container_name }}"
        state: absent
  when: searxng_enabled is false

- name: Data Archive {{ ansible_nas_app_name }}
  block:
    - name: Check for {{ ansible_nas_app_name }} Data Directory
      stat:
        path: "{{ searxng_data_directory }}"
      register: dir_stat

    - name: Archive {{ ansible_nas_app_name }} Data Directory
      ansible.builtin.archive:
        path: "{{ searxng_data_directory }}"
        dest: "{{ docker_home }}/{{ ansible_nas_app_name | lower }}.zip"
        force_archive: true
        format: zip
        owner: ansible-nas
        group: ansible-nas
        mode: u=rw,g=rw
        remove: true
      when: dir_stat.stat.exists
  when: searxng_enabled is false and archive_app_data_enabled is true
