---
- name: Start {{ ansible_nas_app_name }}
  block:
    - name: Create {{ ansible_nas_app_name }} Directories
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
      with_items:
        - "{{ searxng_data_directory }}"
        - "{{ searxng_data_directory }}/etc"

    - name: Create {{ ansible_nas_app_name }} Container
      community.docker.docker_container:
        container_default_behavior: "compatibility"
        name: "{{ searxng_container_name }}"
        hostname: "{{ searxng_container_name }}"
        image: "{{ searxng_image_name }}:{{ searxng_image_tag }}"
        pull: true
        ports:
          - "{{ searxng_port_http }}:8080"
        volumes:
          - "{{ searxng_data_directory }}/etc:/etc/searxng"
        network_mode: bridge
        env:
          BASE_URL: "http://localhost:8080"
          INSTANCE_NAME: "my-instance"
          URL: "searxng.{{ ansible_nas_domain }}"
          TZ: "{{ ansible_nas_timezone }}"
        labels:
          autoheal: "{{ searxng_autoheal | string }}"
          com.centurylinklabs.watchtower.enable: "{{ searxng_watchtower_enabled | string }}"
          dockflare.enable: "{{ searxng_dockflare_enabled | string }}"
          dockflare.access.group: "{{ searxng_dockflare_access_group }}"
          dockflare.hostname: "{{ searxng_hostname }}.{{ ansible_nas_domain }}"
          dockflare.service: "http://{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}:{{ searxng_port_http }}"
          homepage.name: "{{ ansible_nas_app_name }}"
          homepage.group: "{{ searxng_homepage_group }}"
          homepage.icon: "{{ searxng_homepage_icon }}"
          homepage.href: "{{ searxng_homepage_href }}"
          homepage.siteMonitor: "http://{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}:{{ searxng_port_http }}"
          homepage.description: "{{ 'SearXNG is a free internet metasearch engine which aggregates results from various search services and databases.' if homepage_show_description else omit }}"
          homepage.server: "my-docker"
          homepage.container: "{{ searxng_container_name }}"
          homepage.showStats: "{{ searxng_homepage_showstats | string }}"
          repliqate.enabled: "{{ searxng_repliqate_enabled | string }}"
          repliqate.engine: "{{ searxng_repliqate_engine }}"
          repliqate.schedule: "{{ searxng_repliqate_schedule }}"
          repliqate.backup_id: "{{ searxng_repliqate_backup_id }}"
          repliqate.retention: "{{ searxng_repliqate_retention }}"
          traefik.enable: "{{ searxng_available_externally | string }}"
          traefik.http.routers.searxng.rule: "Host(`{{ searxng_hostname }}.{{ ansible_nas_domain }}`)"
          traefik.http.routers.searxng.tls.certresolver: "letsencrypt"
          traefik.http.routers.searxng.tls.domains[0].main: "{{ ansible_nas_domain }}"
          traefik.http.routers.searxng.tls.domains[0].sans: "*.{{ ansible_nas_domain }}"
          traefik.http.routers.searxng.middlewares: "{{ searxng_hostname }}@docker{{ ',tinyauth-auth@docker' if searxng_tinyauth_enabled | bool else '' }}"
          traefik.http.middlewares.searxng.IPAllowList.sourcerange: "{{ searxng_traefik_whitelist }}"
          traefik.http.services.searxng.loadbalancer.server.port: "8080"
          wud.tag.include: '^\d{4}\.\d+\.\d+-.*$'
          wud.tag.transform.type: "semver"
          wud.link.template: "https://github.com/searxng/searxng-docker/pkgs/container/searxng"
        cpu_shares: "{{ searxng_cpu_shares }}"
        memory: "{{ searxng_memory }}"
        memory_swap: "{{ searxng_memory_swap }}"
        restart_policy: unless-stopped

    - name: Access {{ ansible_nas_app_name }} at
      ansible.builtin.debug:
        msg: >-
              {{
                ['http://' + hostvars[inventory_hostname]['ansible_default_ipv4']['address'] + ':' + (searxng_port_http | string)] +
                (['https://' + searxng_hostname + '.' + ansible_nas_domain] if (searxng_available_externally is true or searxng_dockflare_enabled is true) else [])
              }}
  when: searxng_enabled is true

- name: Stop {{ ansible_nas_app_name }}
  block:
    - name: Stop {{ ansible_nas_app_name }} Container
      community.docker.docker_container:
        name: "{{ searxng_container_name }}"
        state: absent
  when: searxng_enabled is false

- name: Data Archive {{ ansible_nas_app_name }}
  include_role:
    name: ansible-nas-archive
  vars:
    target_data_dir: "{{ searxng_data_directory }}"
  when:
    - archive_app_data_enabled is true
    - searxng_enabled is false