---
- name: Start Ombi
  block:
    - name: Create {{ ansible_nas_app_name }} Directories
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
      with_items:
        - "{{ ombi_data_directory }}"
        - "{{ ombi_data_directory }}/config"

    - name: Create {{ ansible_nas_app_name }} Container
      community.docker.docker_container:
        container_default_behavior: "compatibility"
        name: "{{ ombi_container_name }}"
        hostname: "{{ ombi_container_name }}"
        image: "{{ ombi_image_name }}:{{ ombi_image_version }}"
        pull: true
        volumes:
          - "{{ ombi_data_directory }}/config:/config:rw"
        ports:
          - "{{ ombi_port_http }}:3579"
        env:
          DOCKER_MODS: "{{ ombi_env_docker_mods }}"
          INSTALL_PACKAGES: "{{ ombi_env_docker_mods_install_packages }}"
          INSTALL_PIP_PACKAGES: "{{ ombi_env_docker_mods_install_pip_packages}}"
          TP_DOMAIN: "{{ ombi_env_docker_mods_tp_domain }}"
          TP_THEME: "{{ ombi_env_docker_mods_tp_theme }}"
          TP_COMMUNITY_THEME: "{{ ombi_env_docker_mods_tp_community_theme }}"
          TP_ADDON: "{{ ombi_env_docker_mods_tp_addon }}"
          PUID: "{{ ombi_user_id }}"
          PGID: "{{ ombi_group_id }}"
          TZ: "{{ ansible_nas_timezone }}"
        labels:
          autoheal: "{{ ombi_autoheal | string }}"
          com.centurylinklabs.watchtower.enable: "{{ ombi_watchtower_enabled | string }}"
          dockflare.enable: "{{ ombi_dockflare_enabled | string }}"
          dockflare.access.group: "{{ ombi_dockflare_access_group }}"
          dockflare.hostname: "{{ ombi_hostname }}.{{ ansible_nas_domain }}"
          dockflare.service: "http://{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}:{{ ombi_port_http }}"
          homepage.name: "{{ ansible_nas_app_name }}"
          homepage.group: "{{ ombi_homepage_group }}"
          homepage.icon: "{{ ombi_homepage_icon }}"
          homepage.href: "{{ ombi_homepage_href }}"
          homepage.description: "{{ 'ombi description' if homepage_show_description else omit }}"
          homepage.server: "my-docker"
          homepage.container: "{{ ombi_container_name }}"
          homepage.showStats: "{{ ombi_homepage_showstats | string }}"
          homepage.siteMonitor: "http://{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}:{{ ombi_port_http }}"
          homepage.widget.type: "ombi"
          homepage.widget.url: "http://{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}:{{ ombi_port_http }}"
          homepage.widget.key: "{{ ombi_homepage_widget_key }}"
          repliqate.enabled: "{{ ombi_repliqate_enabled | string }}"
          repliqate.engine: "{{ ombi_repliqate_engine }}"
          repliqate.schedule: "{{ ombi_repliqate_schedule }}"
          repliqate.backup_id: "{{ ombi_repliqate_backup_id }}"
          repliqate.retention: "{{ ombi_repliqate_retention }}"
          traefik.enable: "{{ ombi_available_externally | string }}"
          traefik.http.routers.ombi.rule: "Host(`{{ ombi_hostname }}.{{ ansible_nas_domain }}`)"
          traefik.http.routers.ombi.tls.certresolver: "letsencrypt"
          traefik.http.routers.ombi.tls.domains[0].main: "{{ ansible_nas_domain }}"
          traefik.http.routers.ombi.tls.domains[0].sans: "*.{{ ansible_nas_domain }}"
          traefik.http.routers.ombi.middlewares: "ombi@docker{{ ',tinyauth-auth@docker' if ombi_tinyauth_enabled | bool else '' }}"
          traefik.http.middlewares.ombi.IPAllowList.sourcerange: "{{ ombi_traefik_whitelist }}"
          traefik.http.services.ombi.loadbalancer.server.port: "3579"
          wud.tag.include: '^\d+\.\d+\.\d+.*$'
          wud.tag.transform.type: "semver"
          wud.link.template: "https://lscr.io/linuxserver/ombi"
        cpu_shares: "{{ ombi_cpu_shares }}"
        memory: "{{ ombi_memory }}"
        restart_policy: unless-stopped

    - name: Access {{ ansible_nas_app_name }} at
      ansible.builtin.debug:
        msg: >-
              {{
                ['http://' + hostvars[inventory_hostname]['ansible_default_ipv4']['address'] + ':' + (ombi_port_http | string)] +
                (['https://' + ombi_hostname + '.' + ansible_nas_domain] if (ombi_available_externally is true or ombi_dockflare_enabled is true) else [])
              }}
  when: ombi_enabled is true

- name: Stop {{ ansible_nas_app_name }}
  block:
    - name: Stop {{ ansible_nas_app_name }} Container
      community.docker.docker_container:
        name: "{{ ombi_container_name }}"
        state: absent
  when: ombi_enabled is false

- name: Data Archive {{ ansible_nas_app_name }}
  include_role:
    name: ansible-nas-archive
  vars:
    target_data_dir: "{{ ombi_data_directory }}"
  when:
    - archive_app_data_enabled is true
    - ombi_enabled is false