---
# ANE
ansible_nas_app_name: "OpenEMR"
openemr_enabled: false
openemr_available_externally: false
openemr_traefik_whitelist: "{{ lan }}"
openemr_data_directory: "{{ docker_home }}/openemr"

openemr_admin_password: "topsecret"

# network
openemr_hostname: "openemr"
openemr_port_http: "3016"
openemr_network_name: "openemr"

# docker
openemr_container_name: "openemr"
openemr_image_name: "openemr/openemr"
openemr_image_tag: "7.0.2"
openemr_cpu_shares: "1024"
openemr_memory: "1g"
openemr_db_container_name: "openemr_mariadb"
openemr_db_image_name: "lscr.io/linuxserver/mariadb"
openemr_db_image_tag: "latest"
opememr_db_cpu_shares: "1024"
openemr_db_memory: "1g"

# autoheal
openemr_autoheal: "false"
openemr_db_autoheal: "false"

# dockflare
openemr_dockflare_tunnel: "false"
openemr_dockflare_access_group: ""

# homepage
openemr_homepage_group: "Apps"
openemr_homepage_icon: "openemr.png"
openemr_homepage_href: "http://{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}:{{ openemr_port_http }}"
openemr_homepage_showStats: "false"
openemr_db_homepage_group: "DBs"
openemr_db_homepage_icon: "mariadb.png"
openemr_db_homepage_href: "http://{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}:{{ openemr_port_http }}"
openemr_db_homepage_showStats: "false"

# watchtower
openemer_watchtower_monitor_only: "true"
openemer_db_watchtower_monitor_only: "true"