---
- name: Start {{ ansible_nas_app_name }}
  block:
    - name: Create {{ ansible_nas_app_name }} Data Directory
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
      with_items:
        - "{{ gotify_data_directory }}"

    - name: Create {{ ansible_nas_app_name }} Container
      community.docker.docker_container:
        container_default_behavior: "compatibility"
        name: "{{ gotify_container_name }}"
        hostname: "{{ gotify_container_name }}"
        image: "{{ gotify_image_name }}:{{ gotify_image_version }}"
        pull: true
        ports:
          - "{{ gotify_port_http }}:{{ gotify_port_http }}"
        volumes:
          - "/var/run/docker.sock:/var/run/docker.sock"
          - "{{ gotify_data_directory }}:/app/data:rw"
        env:
          GOTIFY_SERVER_PORT: "{{ gotify_port_http }}"
          GOTIFY_SERVER_CORS_ALLOWORIGINS: "{{ gotify_env_gotify_server_cors_alloworigins }}"
          GOTIFY_SERVER_CORS_ALLOWMETHODS: "{{ gotify_env_gotify_server_cors_allowmethods }}"
          GOTIFY_SERVER_CORS_ALLOWHEADERS: "{{ gotify_env_gotify_server_cors_allowheaders }}"
          GOTIFY_SERVER_RESPONSEHEADERS: "{{ gotify_env_gotify_server_responseheaders }}"
          GOTIFY_SERVER_STREAM_ALLOWEDORIGINS: "{{ gotify_env_gotify_server_stream_alloworigins }}"
          GOTIFY_SERVER_TRUSTEDPROXIES: "{{ gotify_env_gotify_server_trustedproxies }}"
          PUID: "{{ gotify_user_id }}"
          PGID: "{{ gotify_group_id }}"
          TZ: "{{ ansible_nas_timezone }}"
        labels:
          autoheal: "{{ gotify_autoheal }}"
          com.centurylinklabs.watchtower.enable: "{{ gotify_watchtower_enable }}"
          dockflare.enable: "{{ gotify_dockflare_tunnel }}"
          dockflare.hostname: "{{ gotify_hostname }}.{{ ansible_nas_domain }}"
          dockflare.service: "http://{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}:{{ gotify_port_http }}"
          homepage.name: "{{ gotify_homepage_name }}"
          homepage.group: "{{ gotify_homepage_group }}"
          homepage.icon: "{{ gotify_homepage_icon }}"
          homepage.description: "{{ 'A simple server for sending and receiving messages in real-time per WebSocket.' if homepage_show_description else omit }}"
          homepage.href: "{{ gotify_homepage_href }}"
          homepage.siteMonitor: "http://{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}:{{ gotify_port_http }}"
          homepage.server: "my-docker"
          homepage.container: "{{ gotify_container_name }}"
          homepage.showStats: "{{ gotify_homepage_showstats }}"
          homepage.widget.type: "gotify"
          homepage.widget.url: "http://{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}:{{ gotify_port_http }}"
          homepage.widget.key: "{{ gotify_homepage_widget_key }}"
          repliqate.enabled: "{{ gotify_repliqate_enabled }}"
          repliqate.engine: "{{ gotify_repliqate_engine }}"
          repliqate.schedule: "{{ gotify_repliqate_schedule }}"
          repliqate.backup_id: "{{ gotify_repliqate_backup_id }}"
          repliqate.retention: "{{ gotify_repliqate_retention }}"
          traefik.enable: "{{ gotify_available_externally | string }}"
          traefik.http.routers.gotify.rule: "Host(`{{ gotify_hostname }}.{{ ansible_nas_domain }}`)"
          traefik.http.routers.gotify.tls.certresolver: "letsencrypt"
          traefik.http.routers.gotify.tls.domains[0].main: "{{ ansible_nas_domain }}"
          traefik.http.routers.gotify.tls.domains[0].sans: "*.{{ ansible_nas_domain }}"
          traefik.http.routers.gotify.middlewares: "gotify@docker{{ ',tinyauth-auth@docker' if gotify_tinyauth_enabled | bool else '' }}"
          traefik.http.middlewares.gotify.IPAllowList.sourcerange: "{{ gotify_traefik_whitelist }}"
          traefik.http.services.gotify.loadbalancer.server.port: "{{ gotify_port_http }}"
          wud.tag.include: '^v\d+\.\d+\.\d+$'
          wud.tag.transform.type: "semver"
          wud.link.template: "https://github.com/gotify/server/pkgs/container/server"
        cpu_shares: "{{ gotify_cpu_shares }}"
        memory: "{{ gotify_memory }}"
        memory_swap: "{{ gotify_memory_swap }}"
        restart_policy: unless-stopped

    - name: Access {{ ansible_nas_app_name }} at
      ansible.builtin.debug:
        msg: >-
              {{
                ['http://' + hostvars[inventory_hostname]['ansible_default_ipv4']['address'] + ':' + (gotify_port_http | string)] +
                (['https://' + gotify_hostname + '.' + ansible_nas_domain] if (gotify_available_externally is true or gotify_dockflare_tunnel is true) else [])
              }}
  when: gotify_enabled is true

- name: Stop {{ ansible_nas_app_name }}
  block:
    - name: Stop {{ ansible_nas_app_name }} Container
      community.docker.docker_container:
        name: "{{ gotify_container_name }}"
        state: absent
  when: gotify_enabled is false

- name: Data Archive {{ ansible_nas_app_name }}
  include_role:
    name: ansible-nas-archive
  vars:
    target_data_dir: "{{ gotify_data_directory }}"
  when:
    - archive_app_data_enabled is true
    - gotify_enabled is false