---
# ANE
ansible_nas_app_name: "Gokapi"
gokapi_enabled: false
gokapi_available_externally: false
gokapi_traefik_whitelist: "{{ lan }}"
gokapi_data_directory: "{{ docker_home }}/gokapi"

# network
gokapi_hostname: "gokapi"
gokapi_port_http: "53842"

# docker
gokapi_container_name: "gokapi"
gokapi_image_name: "f0rc3/gokapi"
gokapi_image_tag: "latest"
gokapi_cpu_shares: "1024"
gokapi_memory: "512m"

# autoheal
gokapi_autoheal: "false"

# dockflare
gokapi_dockflare_tunnel: "false"
gokapi_dockflare_access_group: ""

# homepage
gokapi_homepage_group: "Apps"
gokapi_homepage_icon: "gokapi.png"
gokapi_homepage_href: "http://{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}:{{ gokapi_port_http }}"
gokapi_homepage_showStats: "false"

# watchtower
gokapi_watchtower_monitor_only: "true"