---
# ANE
ansible_nas_app_name: "Silver Bullet"
silverbullet_enabled: false
silverbullet_available_externally: false
silverbullet_traefik_whitelist: "{{ lan }}"

# directories
silverbullet_data_directory: "{{ docker_home }}/silverbullet"

# network
silverbullet_port_http: 3007
silverbullet_hostname: silverbullet

# docker
silverbullet_container_name: "silverbullet"
silverbullet_image_name: "zefhemel/silverbullet"
silverbullet_image_version: "latest"

# specs
silverbullet_cpu_shares: 1024
silverbullet_memory: 1g

# config
silverbullet_username: admin
silverbullet_password: "{{ ansible_nas_app_admin_password }}"

# autoheal
silverbullet_autoheal: "false"

# dockflare
silverbullet_dockflare_tunnel: "false"
silverbullet_dockflare_access_group: ""

# homepage
silverbullet_homepage_group: "Apps"
silverbullet_homepage_icon: "silverbullet.png"
silverbullet_homepage_href: "http://{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}:{{ silverbullet_port_http }}"
silverbullet_homepage_showstats: "false"

# repliqate
silverbullet_repliqate_enabled: "false"
silverbullet_repliqate_engine: "restic"
silverbullet_repliqate_schedule: "@daily 3am"
silverbullet_repliqate_backup_id: "{{ silverbullet_container_name }}"
silverbullet_repliqate_retention: "30d"

# watchtower
silverbullet_watchtower_enable: "false"