---
ansible_nas_app_name: "Airsonic"

airsonic_enabled: false
airsonic_available_externally: false
airsonic_traefik_whitelist: "{{ lan }}"

# directories
airsonic_data_directory: "{{ docker_home }}/airsonic"
airsonic_music_directory: "{{ music_root }}"
airsonic_podcasts_directory: "{{ podcasts_root }}"

# network
airsonic_port: "4040"
airsonic_hostname: "airsonic"

# specs
airsonic_memory: 1g

# docker
airsonic_container_name: airsonic
airsonic_cpu_shares: 1024
airsonic_image_name: "airsonic/airsonic"
airsonic_image_tag: "latest"

# autoheal
airsonic_autoheal: "false"

# homepage
airsonic_homepage_group: "Apps"
airsonic_homepage_icon: "airsonic.png"
airsonic_homepage_href: "http://{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}:{{ airsonic_port }}"
airsonic_homepage_showStats: "false"

# watchtower
airsonic_watchtower_monitor_only: "true"
