---
- name: Start {{ ansible_nas_app_name }}
  block:
    - name: Create {{ ansible_nas_app_name }} Directories
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        # The mumble image gets uid/gid at build time, and uses 1000 for both, by default.
        # This ends up with permission denied on the data directory, unless we change ownership or fully open the permissions.
        owner: 1000
        group: 1000
      with_items:
        - "{{ mumble_data_directory }}"

    - name: Create {{ ansible_nas_app_name }} Container
      community.docker.docker_container:
        container_default_behavior: "compatibility"
        name: "{{ mumble_container_name }}"
        hostname: "{{ mumble_container_name }}"
        image: "{{ mumble_image_name }}:{{ mumble_image_tag }}"
        pull: true
        volumes:
          - "{{ mumble_data_directory }}:/data:rw"
        ports:
          - "{{ mumble_port_tcp }}:64738/tcp"
          - "{{ mumble_port_udp }}:64738/udp"
        env:
          MUMBLE_CONFIG_SERVER_PASSWORD: "{{ mumble_server_password }}"
        labels:
          autoheal: "{{ mumble_autoheal }}"
          com.centurylinklabs.watchtower.enable: "{{ mumble_watchtower_enable }}"
          dockflare.enable: "{{ mumble_dockflare_tunnel }}"
          dockflare.access.group: "{{ mumble_dockflare_access_group }}"
          dockflare.hostname: "{{ mumble_hostname }}.{{ ansible_nas_domain }}"
          dockflare.service: "http://{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}:{{ mumble_port_tcp }}"
          homepage.name: "{{ ansible_nas_app_name }}"
          homepage.group: "{{ mumble_homepage_group }}"
          homepage.icon: "{{ mumble_homepage_icon }}"
          homepage.href: "{{ mumble_homepage_href }}"
          homepage.description: "{{ 'mumble description' if homepage_show_description else omit }}"
          homepage.server: "my-docker"
          homepage.container: "{{ mumble_container_name }}"
          homepage.showStats: "{{ mumble_homepage_showstats }}"
          homepage.siteMonitor: "http://{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}:{{ mumble_port_tcp }}"
          traefik.enable: "{{ mumble_available_externally | string }}"
          traefik.http.routers.mumble.rule: "Host(`{{ mumble_hostname }}.{{ ansible_nas_domain }}`)"
          traefik.http.routers.mumble.tls.certresolver: "letsencrypt"
          traefik.http.routers.mumble.tls.domains[0].main: "{{ ansible_nas_domain }}"
          traefik.http.routers.mumble.tls.domains[0].sans: "*.{{ ansible_nas_domain }}"
          traefik.http.routers.frontend.middlewares: "{{ mumble_hostname }}"
          traefik.http.routers.mumble.middlewares: "{{ mumble_hostname }}@docker"
          traefik.http.middlewares.mumble.IPAllowList.sourcerange: "{{ mumble_traefik_whitelist }}"
          traefik.http.services.mumble.loadbalancer.server.port: "64738"
          wud.tag.include: '^\d+\.\d+\.\d+.*$'
          wud.tag.transform.type: "semver"
          wud.link.template: "https://hub.docker.com/r/mumblevoip/mumble-server"
        cpu_shares: "{{ mumble_cpu_shares }}"
        memory: "{{ mumble_memory }}"
        restart_policy: unless-stopped

    - name: Access {{ ansible_nas_app_name }} at
      ansible.builtin.debug:
        msg: >-
              {{
                ['http://' + hostvars[inventory_hostname]['ansible_default_ipv4']['address'] + ':' + (mumble_port_tcp | string)] +
                (['https://' + mumble_hostname + '.' + ansible_nas_domain] if (mumble_available_externally is true or mumble_dockflare_tunnel is true) else [])
              }}
  when: mumble_enabled is true

- name: Stop {{ ansible_nas_app_name }}
  block:
    - name: Stop {{ ansible_nas_app_name }} Container
      community.docker.docker_container:
        name: "{{ mumble_container_name }}"
        state: absent
  when: mumble_enabled is false

- name: Data Archive {{ ansible_nas_app_name }}
  block:
    - name: Check for {{ ansible_nas_app_name }} Data Directory
      stat:
        path: "{{ mumble_data_directory }}"
      register: dir_stat

    - name: Archive {{ ansible_nas_app_name }} Data Directory
      ansible.builtin.archive:
        path: "{{ mumble_data_directory }}"
        dest: "{{ docker_home }}/{{ ansible_nas_app_name | lower }}.zip"
        force_archive: true
        format: zip
        owner: ansible-nas
        group: ansible-nas
        mode: u=rw,g=rw
        remove: true
      when: dir_stat.stat.exists
  when: mumble_enabled is false and archive_app_data_enabled is true
