---
- name: Start {{ ansible_nas_app_name }}
  block:
    - name: Create {{ ansible_nas_app_name }} Directories
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        # The mumble image gets uid/gid at build time, and uses 1000 for both, by default.
        # This ends up with permission denied on the data directory, unless we change ownership or fully open the permissions.
        owner: 1000
        group: 1000
      with_items:
        - "{{ mumble_data_directory }}"

    - name: Create {{ ansible_nas_app_name }} Container
      community.docker.docker_container:
        container_default_behavior: "compatibility"
        name: "{{ mumble_container_name }}"
        hostname: "{{ mumble_container_name }}"
        image: "{{ mumble_image_name }}:{{ mumble_image_tag }}"
        pull: true
        volumes:
          - "{{ mumble_data_directory }}:/data:rw"
        ports:
          - "{{ mumble_port_tcp }}:64738/tcp"
          - "{{ mumble_port_udp }}:64738/udp"
        env:
          MUMBLE_CONFIG_SERVER_PASSWORD: "{{ mumble_env_mumble_config_server_password }}"
          MUMBLE_CONFIG_IMAGEMESSAGELENGTH: "{{ mumble_env_mumble_config_imagemessagelength }}"
          MUMBLE_CONFIG_REGISTERNAME: "{{ mumble_env_mumble_config_registername }}"
          MUMBLE_CONFIG_USERNAME: "{{ mumble_env_mumble_config_username }}"
          MUMBLE_CONFIG_CHANNELNAME: "{{ mumble_env_mumble_config_channelname }}"
          MUMBLE_CONFIG_WELCOMETEXT: "{{ mumble_env_mumble_config_welcometext }}"
          MUMBLE_SUPERUSER_PASSWORD: "{{ mumble_env_mumble_serveruser_password }}"
          MUMBLE_CONFIG_ICE: "{{ mumble_env_mumble_config_ice }}"
          MUMBLE_CONFIG_ICESECRETWRITE: "{{ mumble_env_mumble_config_icesecretwrite }}"
          MUMBLE_CONFIG_PORT: "{{ mumble_env_mumble_config_port }}"
          MUMBLE_CONFIG_TIMEOUT: "{{ mumble_env_mumble_config_timeout }}"
          MUMBLE_CONFIG_USERS: "{{ mumble_env_mumble_config_users }}"
          MUMBLE_CONFIG_REMEMBERCHANNEL: "{{ mumble_env_mumble_config_rememberchannel }}"
          MUMBLE_CONFIG_ALLOWHTML: "{{ mumble_env_mumble_config_allowhtml }}"
          MUMBLE_VERBOSE: "{{ mumble_env_mumble_verbose }}"
          PUID: "{{ mumble_puid }}"
          PGID: "{{ mumble_pgid }}"
        labels:
          autoheal: "{{ mumble_autoheal_enabled | ternary('true', 'false') }}"
          com.centurylinklabs.watchtower.enable: "{{ mumble_watchtower_enabled | ternary('true', 'false') }}"
          dockflare.enable: "false"
          homepage.name: "{{ ansible_nas_app_name }}"
          homepage.group: "{{ mumble_homepage_group }}"
          homepage.icon: "{{ mumble_homepage_icon }}"
          homepage.description: "{{ 'a free, open source, low latency, high quality voice chat application' if homepage_show_description else omit }}"
          homepage.server: "my-docker"
          homepage.container: "{{ mumble_container_name }}"
          homepage.showStats: "{{ mumble_homepage_showstats | ternary('true', 'false') }}"
          repliqate.enabled: "{{ mumble_repliqate_enabled | ternary('true', 'false') }}"
          repliqate.engine: "{{ mumble_repliqate_engine }}"
          repliqate.schedule: "{{ mumble_repliqate_schedule }}"
          repliqate.backup_id: "{{ mumble_repliqate_backup_id }}"
          repliqate.retention: "{{ mumble_repliqate_retention }}"
          traefik.enable: "false"
          wud.tag.include: '^\d+\.\d+\.\d+.*$'
          wud.tag.transform.type: "semver"
          wud.link.template: "https://hub.docker.com/r/mumblevoip/mumble-server"
        cpu_shares: "{{ mumble_cpu_shares }}"
        memory: "{{ mumble_memory }}"
        memory_swap: "{{ mumble_memory_swap }}"
        restart_policy: unless-stopped
  when: mumble_enabled is true

- name: Stop {{ ansible_nas_app_name }}
  block:
    - name: Stop {{ ansible_nas_app_name }} Container
      community.docker.docker_container:
        name: "{{ mumble_container_name }}"
        state: absent
  when: mumble_enabled is false

- name: Data Archive {{ ansible_nas_app_name }}
  include_role:
    name: ansible-nas-archive
  vars:
    target_data_dir: "{{ mumble_data_directory }}"
  when:
    - archive_app_data_enabled is true
    - mumble_enabled is false