---
# ANE
ansible_nas_app_name: "CrashPlan Pro"
crashplanpro_enabled: false
crashplanpro_available_externally: false
crashplanpro_traefik_whitelist: "{{ lan }}"
crashplanpro_data_directory: "{{ docker_home }}/crashplanpro"
crashplanpro_storage_directory: "/"

# network
crashplanpro_hostname: "crashplanpro"
crashplanpro_port_http: "5800"

# docker
crashplanpro_container_name: "crashplanpro"
crashplanpro_image_name: "ghcr.io/jlesage/crashplan-pro"
crashplanpro_image_tag: "latest"
crashplanpro_cpu_shares: "1024"
crashplanpro_memory: "8G"

# autoheal
crashplanpro_autoheal: "false"

# dockflare
crashplanpro_dockflare_tunnel: "false"
crashplanpro_dockflare_access_group: ""

# homepage
crashplanpro_homepage_group: "Apps"
crashplanpro_homepage_icon: "https://lh7-rt.googleusercontent.com/docsz/AD_4nXfsuRt75p1awOo4PEiVymI3TcFauFUk8syT3gqnrp0O1xedOTVRsZwXxOB6vTa4Z8gWRZXYuc1RWecqmhen1x9UnS11RK3axRLeS_kOUbVA583INyD4w00F_Ohn2GDJyWFXSDYckTM_Zep_NKY7mAwEeBE?key=8ldYwBcnQ67yTok6G7LSquuN"
crashplanpro_homepage_href: "http://{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}:{{ crashplanpro_port_http }}"
crashplanpro_homepage_showstats: "false"

# watchtower
crashplanpr_watchtower_enable: "false"