---
- name: Start {{ ansible_nas_app_name }}
  block:
    - name: Create {{ ansible_nas_app_name }} Directories
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
      with_items:
        - "{{ hammond_data_directory }}"
        - "{{ hammond_data_directory }}/assets"
        - "{{ hammond_data_directory }}/config"

    - name: Create {{ ansible_nas_app_name }} Container
      community.docker.docker_container:
        container_default_behavior: "compatibility"
        name: "{{ hammond_container_name }}"
        hostname: "{{ hammond_container_name }}"
        image: "{{ hammond_image_name }}:{{ hammond_image_tag }}"
        pull: true
        volumes:
          - "{{ hammond_data_directory }}/assets:/assets"
          - "{{ hammond_data_directory }}/config:/config"
        ports:
          - "{{ hammond_port_http }}:3000"
        env:
          JWT_SECRET: "{{ hammond_secret }}"
          TZ: "{{ ansible_nas_timezone }}"
        labels:
          autoheal: "{{ hammond_autoheal }}"
          com.centurylinklabs.watchtower.enable: "{{ hammond_watchtower_enable }}"
          dockflare.enable: "{{ hammond_dockflare_tunnel }}"
          dockflare.access.group: "{{ hammond_dockflare_access_group }}"
          dockflare.hostname: "{{ hammond_hostname }}.{{ ansible_nas_domain }}"
          dockflare.service: "http://{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}:{{ hammond_port_http }}"
          homepage.name: "{{ ansible_nas_app_name }}"
          homepage.group: "{{ hammond_homepage_group }}"
          homepage.icon: "{{ hammond_homepage_icon }}"
          homepage.href: "{{ hammond_homepage_href }}"
          homepage.description: "{{ 'Hammond is a self hosted vehicle management system to track fuel and other expenses related to all of your vehicles.' if homepage_show_description else omit }}"
          homepage.siteMonitor: "http://{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}:{{ hammond_port_http }}"
          homepage.server: "my-docker"
          homepage.container: "{{ hammond_container_name }}"
          homepage.showStats: "{{ hammond_homepage_showstats }}"
          repliqate.enabled: "{{ hammond_repliqate_enabled }}"
          repliqate.engine: "{{ hammond_repliqate_engine }}"
          repliqate.schedule: "{{ hammond_repliqate_schedule }}"
          repliqate.backup_id: "{{ hammond_repliqate_backup_id }}"
          repliqate.retention: "{{ hammond_repliqate_retention }}"
          traefik.enable: "{{ hammond_available_externally | string }}"
          traefik.http.routers.hammond.rule: "Host(`hammond.{{ ansible_nas_domain }}`)"
          traefik.http.routers.hammond.tls.certresolver: "letsencrypt"
          traefik.http.routers.hammond.tls.domains[0].main: "{{ ansible_nas_domain }}"
          traefik.http.routers.hammond.tls.domains[0].sans: "*.{{ ansible_nas_domain }}"
          traefik.http.routers.frontend.middlewares: "{{ hammond_hostname }}"
          traefik.http.routers.hammond.middlewares: "{{ hammond_hostname }}@docker"
          traefik.http.middlewares.hammond.IPAllowList.sourcerange: "{{ hammond_traefik_whitelist }}"
          traefik.http.services.hammond.loadbalancer.server.port: "3000"
          wud.tag.include: '^\d+\.\d+\.\d+$'
          wud.tag.transform.type: "semver"
          wud.link.template: "https://github.com/alfhou/hammond/pkgs/container/hammond"
        cpu_shares: "{{ hammond_cpu_shares }}"
        memory: "{{ hammond_memory }}"
        restart_policy: unless-stopped

    - name: Access {{ ansible_nas_app_name }} at
      ansible.builtin.debug:
        msg: >-
              {{
                ['http://' + hostvars[inventory_hostname]['ansible_default_ipv4']['address'] + ':' + (hammond_port_http | string)] +
                (['https://' + hammond_hostname + '.' + ansible_nas_domain] if (hammond_available_externally is true or hammond_dockflare_tunnel is true) else [])
              }}
  when: hammond_enabled is true

- name: Stop {{ ansible_nas_app_name }}
  block:
    - name: Stop {{ ansible_nas_app_name }} Contaner
      community.docker.docker_container:
        name: "{{ hammond_container_name }}"
        state: absent
  when: hammond_enabled is false

- name: Data Archive {{ ansible_nas_app_name }}
  block:
    - name: Check for {{ ansible_nas_app_name }} Data Directory
      stat:
        path: "{{ hammond_data_directory }}"
      register: dir_stat

    - name: Archive {{ ansible_nas_app_name }} Data Directory
      ansible.builtin.archive:
        path: "{{ hammond_data_directory }}"
        dest: "{{ docker_home }}/{{ ansible_nas_app_name | lower }}.zip"
        force_archive: true
        format: zip
        owner: ansible-nas
        group: ansible-nas
        mode: u=rw,g=rw
        remove: true
      when: dir_stat.stat.exists
  when: hammond_enabled is false and archive_app_data_enabled is true
