---
- name: Start {{ ansible_nas_app_name }}
  block:
    - name: Create {{ ansible_nas_app_name }} Directories
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
      with_items:
        - "{{ calibreweb_data_directory }}/config"
        - "{{ calibreweb_data_directory }}/data"

    - name: Create {{ ansible_nas_app_name }} Container
      community.docker.docker_container:
        container_default_behavior: "compatibility"
        name: "{{ calibreweb_container_name }}"
        hostname: "{{ calibreweb_container_name }}"
        image: "{{ calibreweb_image_name }}:{{ calibreweb_image_tag }}"
        pull: true
        volumes:
          - "{{ calibreweb_data_directory }}/config:/config"
          - "{{ calibreweb_books_root }}:/books"
          - "{{ calibreweb_data_directory }}/data:/data"
        env:
          DOCKER_MODS: "{{ calibreweb_env_docker_mods }}"
          PUID: "{{ calibreweb_user_id }}"
          PGID: "{{ calibreweb_group_id }}"
          TZ: "{{ ansible_nas_timezone }}"
        ports:
          - "{{ calibreweb_port }}:8083"
        labels:
          autoheal: "{{ calibreweb_autoheal }}"
          com.centurylinklabs.watchtower.enable: "{{ calibreweb_watchtower_enable }}"
          dockflare.enable: "{{ calibreweb_dockflare_tunnel }}"
          dockflare.access.group: "{{ calibreweb_dockflare_access_group }}"
          dockflare.hostname: "{{ calibreweb_hostname }}.{{ ansible_nas_domain }}"
          dockflare.service: "http://{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}:{{ calibreweb_port }}"
          homepage.name: "{{ ansible_nas_app_name }}"
          homepage.group: "{{ calibreweb_homepage_group }}"
          homepage.icon: "{{ calibreweb_homepage_icon }}"
          homepage.href: "{{ calibreweb_homepage_href }}"
          homepage.description: "{{ 'Web app for browsing, reading and downloading eBooks stored in a Calibre database' if homepage_show_description else omit }}"
          homepage.server: "my-docker"
          homepage.container: "{{ calibreweb_container_name }}"
          homepage.showStats: "{{ calibreweb_homepage_showstats }}"
          homepage.siteMonitor: "http://{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}:{{ calibreweb_port }}"
          traefik.enable: "{{ calibreweb_available_externally | string }}"
          traefik.http.routers.calibreweb.rule: "Host(`{{ calibreweb_hostname }}.{{ ansible_nas_domain }}`)"
          traefik.http.routers.calibreweb.tls.certresolver: "letsencrypt"
          traefik.http.routers.calibreweb.tls.domains[0].main: "{{ ansible_nas_domain }}"
          traefik.http.routers.calibreweb.tls.domains[0].sans: "*.{{ ansible_nas_domain }}"
          traefik.http.routers.frontend.middlewares: "{{ calibreweb_hostname }}"
          traefik.http.routers.calibreweb.middlewares: "{{ calibreweb_hostname }}@docker"
          traefik.http.middlewares.calibreweb.IPAllowList.sourcerange: "{{ calibreweb_traefik_whitelist }}"
          traefik.http.services.calibreweb.loadbalancer.server.port: "8083"
          wud.tag.include: '^\d+\.\d+\.\d+$'
          wud.tag.transform.type: "semver"
          wud.link.template: "lscr.io/linuxserver/calibre-web"
        cpu_shares: "{{ calibreweb_cpu_shares }}"
        memory: "{{ calibreweb_memory }}"
        restart_policy: unless-stopped
  when: calibreweb_enabled is true

- name: Stop {{ ansible_nas_app_name }}
  block:
    - name: Stop {{ ansible_nas_app_name }} Container
      community.docker.docker_container:
        name: "{{ calibreweb_container_name }}"
        state: absent
  when: calibreweb_enabled is false

- name: Data Archive {{ ansible_nas_app_name }}
  block:
    - name: Check for {{ ansible_nas_app_name }} Data Directory
      stat:
        path: "{{ calibreweb_data_directory }}"
      register: dir_stat

    - name: Archive {{ ansible_nas_app_name }} Data Directory
      ansible.builtin.archive:
        path: "{{ calibreweb_data_directory }}"
        dest: "{{ docker_home }}/{{ ansible_nas_app_name | lower }}.zip"
        force_archive: true
        format: zip
        owner: ansible-nas
        group: ansible-nas
        mode: u=rw,g=rw
        remove: true
      when: dir_stat.stat.exists
  when: calibreweb_enabled is false and archive_app_data_enabled is true
