---
# ANE
ansible_nas_app_name: "Time Machine"
timemachine_enabled: false

timemachine_log_level: error
timemachine_password: timemachine
timemachine_share_name: Data
timemachine_volume_size_limit: "0"

# Directories
timemachine_data_directory: "{{ docker_home }}/timemachine"

# Networking
timemachine_port: "10445"

# Container
timemachine_memory: "1G"
timemachine_container_name: "timemachine"
timemachine_image_name: "awlnx/samba-timemachine"
timemachine_image_version: "latest"

# autoheal
timemachine_cpu_shares: 1024
timemachine_autoheal: "false"

# homepage
timemachine_homepage_group: "Misc"
timemachine_homepage_icon: "https://static.wikia.nocookie.net/ipod/images/f/f1/Time_Machine.png"
timemachine_homepage_showstats: "false"

# repliqate
timemachine_repliqate_enabled: "false"
timemachine_repliqate_engine: "restic"
timemachine_repliqate_schedule: "@daily 3am"
timemachine_repliqate_backup_id: "{{ timemachine_container_name }}"
timemachine_repliqate_retention: "30d"

# watchtower
timemachine_watchtower_enable: "false"