---
ansible_nas_app_name: "Tianji"

# enable or disable the application
tianji_enabled: false
tianji_available_externally: false
tianji_traefik_whitelist: "{{ lan }}"

# directories
tianji_data_directory: "{{ docker_home }}/tianji"

# network
tianji_hostname: "tianji"
tianji_port_http: "3031"

# app
tianji_jwt_secret: "MstVibaSoeiN48cVmplj4efw2s2YfQ8xdl57RcDHSi8" # replace with your own
c: "false"
tianji_allow_openapi: "false"
tianji_openapi_key: "put openapi key here"

# docker
tianji_container_name: "tianji"
tianji_image_name: "moonrailgun/tianji"
tianji_image_tag: "latest"
tianji_cpu_shares: "1024"
tianji_memory: "1g"
tianji_db_container_name: "tianji-db"
tianji_db_image_name: "postgres"
tianji_db_image_tag: "postgres:16-alpine"
tianji_db_cpu_shares: "1024"
tianji_db_memory: "1g"

# autoheal
tianji_autoheal: "false"
tianji_db_autoheal: "false"

# homepage
tianji_homepage_group: "Apps"
tianji_homepage_icon: "tianji.png"
tianji_homepage_href: "http://{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}:{{ ghost_port_http }}"
tianji_homepage_showStats: "false"
tianji_db_homepage_group: "DBs"
tianji_db_homepage_icon: "postgres.png"

# watchtower
tianji_watchtower_monitor_only: "true"
tianji_db_watchtower_monitor_only: "true"
