---
# ANE
ansible_nas_app_name: "Sonos-Web"
sonos_web_enabled: false
sonos_web_traefik_enabled: false
sonos_web_traefik_whitelist: "{{ lan }}"

# network
sonos_web_hostname: "sonosweb"
sonos_web_port_http: "5050"

# docker
sonos_web_container_name: "sonos-web"
sonos_web_image_name: "sonosweb/sonos-web"
sonos_web_image_tag: "latest"

# specs
sonos_web_cpu_shares: 1024
sonos_web_memory: "256M"
sonos_web_memory_swap: -1

# autoheal
sonos_web_autoheal_enabled: false

# homepage
sonos_web_homepage_group: "Apps"
sonos_web_homepage_icon: "si-sonos"
sonos_web_homepage_href: "http://{{ hostvars[inventory_hostname]['ansible_facts']['default_ipv4']['address'] }}:{{ sonos_web_port_http }}"
sonos_web_homepage_showstats: false

# dockflare
sonos_web_dockflare_enabled: false
sonos_web_dockflare_access_group: ""

# tinyauth
sonos_web_tinyauth_enabled: false

# watchtower
sonos_web_watchtower_enabled: false
