---
- name: Start {{ ansible_nas_app_name }}
  block:
    - name: Create {{ ansible_nas_app_name }} Directories
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        # mode: 0755
      with_items:
        - "{{ rssbridge_data_directory }}/data"

    - name: Create {{ ansible_nas_app_name }} Container
      community.docker.docker_container:
        container_default_behavior: "compatibility"
        name: "{{ rssbridge_container_name }}"
        hostname: "{{ rssbridge_container_name }}"
        image: "{{ rssbridge_image_name }}:{{ rssbridge_image_version }}"
        pull: true
        volumes:
          - "{{ rssbridge_data_directory }}/data:/config:rw"
        ports:
          - "{{ rssbridge_port }}:80"
        env:
          TZ: "{{ ansible_nas_timezone }}"
        labels:
          autoheal: "{{ rssbridge_autoheal }}"
          com.centurylinklabs.watchtower.enable: "{{ rssbridge_watchtower_enable }}"
          dockflare.enable: "{{ rssbridge_dockflare_tunnel }}"
          dockflare.access.group: "{{ rssbridge_dockflare_access_group }}"
          dockflare.hostname: "{{ rssbridge_hostname }}.{{ ansible_nas_domain }}"
          dockflare.service: "http://{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}:{{ rssbridge_port }}"
          homepage.name: "{{ ansible_nas_app_name }}"
          homepage.group: "{{ rssbridge_homepage_group }}"
          homepage.icon: "{{ rssbridge_homepage_icon }}"
          homepage.href: "{{ rssbridge_homepage_href }}"
          homepage.description: "{{ 'rssbridge description' if homepage_show_description else omit }}"
          homepage.server: "my-docker"
          homepage.container: "{{ rssbridge_container_name }}"
          homepage.showStats: "{{ rssbridge_homepage_showstats }}"
          homepage.siteMonitor: "http://{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}:{{ rssbridge_port }}"
          traefik.enable: "{{ rssbridge_available_externally | string }}"
          traefik.http.routers.rssbridge.rule: "Host(`{{ rssbridge_hostname }}.{{ ansible_nas_domain }}`)"
          traefik.http.routers.rssbridge.tls.certresolver: "letsencrypt"
          traefik.http.routers.rssbridge.tls.domains[0].main: "{{ ansible_nas_domain }}"
          traefik.http.routers.rssbridge.tls.domains[0].sans: "*.{{ ansible_nas_domain }}"
          traefik.http.routers.frontend.middlewares: "{{ rssbridge_hostname }}"
          traefik.http.routers.rssbridge.middlewares: "{{ rssbridge_hostname }}@docker"
          traefik.http.middlewares.rssbridge.IPAllowList.sourcerange: "{{ rssbridge_traefik_whitelist }}"
          traefik.http.services.rssbridge.loadbalancer.server.port: "80"
          wud.tag.include: '^\d+\.\d+\.\d+.*$'
          wud.tag.transform.type: "semver"
          wud.link.template: "https://hub.docker.com/r/rssbridge/rss-bridge"
        cpu_shares: "{{ rssbridge_cpu_shares }}"
        memory: "{{ rssbridge_memory }}"
        restart_policy: unless-stopped

    - name: Access {{ ansible_nas_app_name }} at
      ansible.builtin.debug:
        msg: >-
              {{
                ['http://' + hostvars[inventory_hostname]['ansible_default_ipv4']['address'] + ':' + (rssbridge_port_http | string)] +
                (['https://' + rssbridge_hostname + '.' + ansible_nas_domain] if (rssbridge_available_externally is true or rssbridge_dockflare_tunnel is true) else [])
              }}
  when: rssbridge_enabled is true

- name: Stop {{ ansible_nas_app_name }}
  block:
    - name: Stop {{ ansible_nas_app_name }} Container
      community.docker.docker_container:
        name: "{{ rssbridge_container_name }}"
        state: absent
  when: rssbridge_enabled is false

- name: Data Archive {{ ansible_nas_app_name }}
  block:
    - name: Check for {{ ansible_nas_app_name }} Data Directory
      stat:
        path: "{{ rssbridge_data_directory }}"
      register: dir_stat

    - name: Archive {{ ansible_nas_app_name }} Data Directory
      ansible.builtin.archive:
        path: "{{ rssbridge_data_directory }}"
        dest: "{{ docker_home }}/{{ ansible_nas_app_name | lower }}.zip"
        force_archive: true
        format: zip
        owner: ansible-nas
        group: ansible-nas
        mode: u=rw,g=rw
        remove: true
      when: dir_stat.stat.exists
  when: rssbridge_enabled is false and archive_app_data_enabled is true
