---
- name: Start {{ ansible_nas_app_name }}
  block:
    - name: Create {{ ansible_nas_app_name }} Directories
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
      with_items:
        - "{{ get_iplayer_data_directory }}"
        - "{{ get_iplayer_download_directory }}"

    - name: Create {{ ansible_nas_app_name }} Container
      community.docker.docker_container:
        name: "{{ get_iplayer_container_name }}"
        hostname: "{{ get_iplayer_container_name }}"
        image: "{{ get_iplayer_image_name }}:{{ get_iplayer_image_version }}"
        pull: true
        cpu_shares: "{{ get_iplayer_cpu_shares }}"
        volumes:
          - "{{ get_iplayer_data_directory }}:/root/.get_iplayer:rw"
          - "{{ get_iplayer_download_directory }}:/root/output:rw"
        ports:
          - "{{ get_iplayer_port }}:8181"
        restart_policy: unless-stopped
        memory: "{{ get_iplayer_memory }}"
        labels:
          autoheal: "{{ get_iplayer_autoheal }}"
          com.centurylinklabs.watchtower.monitor-only: "{{ get_iplayer_watchtower_monitor_only }}"
  when: get_iplayer_enabled is true

- name: Stop {{ ansible_nas_app_name }}
  block:
    - name: Stop {{ ansible_nas_app_name }} Container
      community.docker.docker_container:
        name: "{{ get_iplayer_container_name }}"
        state: absent
  when: get_iplayer_enabled is false

- name: Data Archive {{ ansible_nas_app_name }}
  block:
    - name: Check for {{ ansible_nas_app_name }} Data Directory
      stat:
        path: "{{ get_iplayer_data_directory }}"
      register: dir_stat

    - name: Archive {{ ansible_nas_app_name }} Data Directory
      ansible.builtin.archive:
        path: "{{ get_iplayer_data_directory }}"
        dest: "{{ docker_home }}/{{ ansible_nas_app_name | lower }}.zip"
        force_archive: true
        format: zip
        owner: ansible-nas
        group: ansible-nas
        mode: u=rw,g=rw
        remove: true
      when: dir_stat.stat.exists
  when: get_iplayer_enabled is false and archive_app_data_enabled is true
