---
# ANE
ansible_nas_app_name: "Firefly III"
firefly_enabled: false
firefly_available_externally: false
firefly_traefik_whitelist: "{{ lan }}"

# directories
firefly_data_directory: "{{ docker_home }}/firefly"

# network
firefly_hostname: "firefly"
firefly_port_http: "8066"

# specs
firefly_cpu_shares: 1024
firefly_memory: "1G"
firefly_memory_swap: -1
firefly_db_cpu_shares: 1024
firefly_db_memory: "1G"
firefly_db_memory_swap: "{{ firefly_db_memory }}"

# docker
firefly_container_name: "firefly"
firefly_image_name: "fireflyiii/core"
firefly_image_tag: "latest"
firefly_db_container_name: "firefly-db"
firefly_db_image_name: "mariadb"
firefly_db_image_tag: "lts"

# app
firefly_env_app_env: "production"
firefly_env_app_key: "lm6sZhprxGgpc97sp09ph3ZElRUVGTT3"
firefly_env_app_url: "http://{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}:{{ firefly_port_http }}"
firefly_env_db_connection: "mysql"
firefly_env_db_database: "firefly_db"
firefly_env_db_username: "firefly"
firefly_env_db_password:  "topsecret"
firefly_env_db_port: "3306"
firefly_env_mail_mail: "log" # smtp, sendmail, mailgun, sparkpost, mailersend
firefly_env_mail_host: "" # smtp.mailtrap.io
firefly_env_mail_port: "" # 2525
firefly_env_mail_from: "" # changeme@example.com
firefly_env_mail_username: ""
firefly_env_mail_password: ""
firefly_env_mail_encryption: ""
firefly_env_site_owner: "" # you@example.com
firefly_db_env_mysql_root_password: "firefly"

# autoheal
firefly_autoheal: "false"
firefly_db_autoheal: "false"

# dockflare
firefly_dockflare_tunnel: "false"
firefly_dockflare_access_group: ""

# homepage
firefly_homepage_group: "Apps"
firefly_homepage_icon: "firefly.png"
firefly_homepage_href: "http://{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}:{{ firefly_port_http }}"
firefly_homepage_showstats: "false"
firefly_db_homepage_group: "DBs"
firefly_db_homepage_icon: "mariadb.png"
firefly_db_homepage_href: "http://{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}:{{ firefly_port_http }}"
firefly_db_homepage_showstats: "false"

# repliqate
firefly_repliqate_enabled: "false"
firefly_repliqate_engine: "restic"
firefly_repliqate_schedule: "@daily 3am"
firefly_repliqate_backup_id: "{{ firefly_container_name }}"
firefly_repliqate_retention: "30d"
firefly_db_repliqate_enabled: "false"
firefly_db_repliqate_engine: "restic"
firefly_db_repliqate_schedule: "@daily 3am"
firefly_db_repliqate_backup_id: "{{ firefly_db_container_name }}"
firefly_db_repliqate_retention: "30d"

# tinyauth
firefly_tinyauth_enabled: false

# watchtower
firefly_watchtower_enable: "false"
firefly_db_watchtower_enable: "false"