# /rules/transports.toml

# This defines a named transport called "insecureTransport"
[http.serversTransports.insecureTransport]
  insecureSkipVerify = true

# You can even define others here if needed, e.g., for mTLS
# [http.serversTransports.myOtherTransport]
#   ...