---
# ANE
ansible_nas_app_name: "Remotely"
remotely_enabled: false
remotely_traefik_enabled: false
remotely_traefik_whitelist: "{{ lan }}"
remotely_data_directory: "{{ docker_home }}/remotely"

# network
remotely_hostname: "remotely"
remotely_port_http: "3054"

# docker
remotely_container_name: "remotely"
remotely_image_name: "immybot/remotely"
remotely_image_tag: "latest"

# specs
remotely_cpu_shares: 1024
remotely_memory: "1G"
remotely_memory_swap: -1

# autoheal
remotely_autoheal_enabled: false

# dockflare
remotely_dockflare_enabled: false
remotely_dockflare_access_group: ""

# healthcheck
remotely_healthcheck_test: ["CMD-SHELL", "(echo > /dev/tcp/127.0.0.1/5000) >/dev/null 2>&1 || exit 1"]
remotely_healthcheck_interval: 1m
remotely_healthcheck_timeout: 10s
remotely_healthcheck_retries: 3
remotely_healthcheck_start_period: 45s

# homepage
remotely_homepage_group: "Apps"
remotely_homepage_icon: "remotely.png"
remotely_homepage_href: "http://{{ hostvars[inventory_hostname]['ansible_facts']['default_ipv4']['address'] }}:{{ remotely_port_http }}"
remotely_homepage_showstats: false

# repliqate
remotely_repliqate_enabled: false
remotely_repliqate_engine: "restic"
remotely_repliqate_schedule: "@daily 3am"
remotely_repliqate_backup_id: "{{ remotely_container_name }}"
remotely_repliqate_retention: "30d"

# tinyauth
remotely_tinyauth_enabled: false

# watchtower
remotely_watchtower_enabled: false