---
ansible_nas_app_name: "Hello World"

hello_world_enabled: false
hello_world_available_externally: false
hello_world_traefik_whitelist: "{{ lan }}"

# directories
hello_world_data_directory: "{{ docker_home }}/hello-world"

# network
hello_world_port: "9999"
hello_world_hostname: "helloworld"

# specs
hello_world_cpu_shares: 1024
hello_world_memory: 1g

# docker
hello_world_container_name: hello-world
hello_world_image_name: "crccheck/hello-world"
hello_world_image_tag: "latest"

# autoheal
hello_world_autoheal: "false"

# dockflare
hello_world_dockflare_tunnel: "false"
hello_world_dockflare_access_group: ""

# homepage
hello_world_homepage_group: "Apps"
hello_world_homepage_icon: "hello_world.png"
hello_world_homepage_href: "http://{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}:{{ hello_world_port }}"
hello_world_homepage_showStats: "false"

# watchtower
hello_world_watchtower_monitor_only: "true"