---
# ANE
ansible_nas_app_name: "GameVault"
gamevault_enabled: false
gamevault_available_externally: false
gamevault_traefik_whitelist: "{{ lan }}"

# directories
gamevault_data_directory: "{{ docker_home }}/gamevault"

# network
gamevault_hostname: "gamevault"
gamevault_port_http: 5082

# docker
gamevault_container_name: "gamevault"
gamevault_image_name: "ghcr.io/phalcode/gamevault-backend"
gamevault_image_tag: "latest"
gamevault_cpu_shares: 1024
gamevault_memory: "2g"
gamevault_db_container_name: "gamevault-db"
gamevault_db_image_name: "postgres"
gamevault_db_image_tag: "16-alpine"
gamevault_db_cpu_shares: "1024"
gamevault_db_memory: "1g"

# app
gamevault_puid: "0"
gamevault_pgid: "0"
gamevault_metadata_igdb_client_id: "generate_at_dev.twitch.tv"
gamevault_metadata_igdb_client_secret: "generate_at_dev.twitch.tv"
gamevault_server_admin_password: "{{ ansible_nas_app_admin_password }}"
gamevault_rawg_api_key: "https://gamevau.lt/docs/server-docs/indexing-and-metadata#rawg-api-key"

# autoheal
gamevault_autoheal: "false"
gamevault_db_autoheal: "false"

# dockflare
gamevault_dockflare_tunnel: "false"
gamevault_dockflare_access_group: ""

# homepage
gamevault_homepage_group: "Apps"
gamevault_homepage_icon: "gamevault.png"
gamevault_homepage_href: "http://{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}:{{ gamevault_port_http }}"
gamevault_homepage_showstats: "false"
gamevault_db_homepage_group: "DBs"
gamevault_db_homepage_icon: "postgres.png"
gamevault_db_homepage_showstats: "false"

# repliqate
gamevault_repliqate_enabled: "false"
gamevault_repliqate_engine: "restic"
gamevault_repliqate_schedule: "@daily 3am"
gamevault_repliqate_backup_id: "{{ gamevault_container_name }}"
gamevault_repliqate_retention: "30d"
gamevault_db_repliqate_enabled: "false"
gamevault_db_repliqate_engine: "restic"
gamevault_db_repliqate_schedule: "@daily 3am"
gamevault_db_repliqate_backup_id: "{{ gamevault_db_container_name }}"
gamevault_db_repliqate_retention: "30d"

# watchtower
gamevault_watchtower_enable: "false"
gamevault_db_watchtower_enable: "false"