---
- name: Start {{ ansible_nas_app_name }}
  block:
    - name: Create {{ ansible_nas_app_name }} Directories
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
      with_items:
        - "{{ traefik_data_directory }}"
        - "{{ traefik_data_directory }}/data"
        - "{{ traefik_data_directory }}/letsencrypt"
        - "{{ traefik_data_directory }}/rules"

    - name: Copy {{ ansible_nas_app_name }} Template config.toml
      ansible.builtin.template:
        src: traefik.toml
#       dest: "{{ traefik_data_directory }}/traefik.toml"
        dest: "{{ traefik_data_directory }}/data/traefik.toml"
      register: template_config

    - name: Copy {{ ansible_nas_app_name }} Template transports.toml
      ansible.builtin.template:
        src: transports.toml
        dest: "{{ traefik_data_directory }}/rules/transports.toml"
        mode: '0644'
      register: template_transports

    - name: Copy {{ ansible_nas_app_name }} Template external_hosts.yml
      ansible.builtin.template:
        src: external_hosts.yml
        dest: "{{ traefik_data_directory }}/rules/external_hosts.yml"
        mode: '0644'
      register: template_external_hosts

    - name: Create {{ ansible_nas_app_name }} Container
      community.docker.docker_container:
        container_default_behavior: "compatibility"
        name: "{{ traefik_container_name }}"
        hostname: "{{ traefik_container_name }}"
        image: "{{ traefik_image_name }}:{{ traefik_image_version }}"
        pull: true
        network_mode: host
        dns_servers: "{{ traefik_dns_servers }}"
        volumes:
#         - "{{ traefik_data_directory }}/traefik.toml:/etc/traefik/traefik.toml:ro"
          - "{{ traefik_data_directory }}/data:/etc/traefik"
          - "{{ traefik_data_directory }}/letsencrypt:/letsencrypt:rw"
          - "{{ traefik_data_directory }}/rules:/rules:ro"
          - "/var/run/docker.sock:/var/run/docker.sock:ro"
        env: "{{ traefik_environment_variables }}"
        labels:
          autoheal: "{{ traefik_autoheal | string }}"
          com.centurylinklabs.watchtower.enable: "{{ traefik_watchtower_enabled| string }}"
          dockflare.enable: "false"
          homepage.name: "{{ ansible_nas_app_name }}"
          homepage.group: "{{ traefik_homepage_group }}"
          homepage.icon: "{{ traefik_homepage_icon }}"
          homepage.href: "{{ traefik_homepage_href }}"
          homepage.siteMonitor: "http://{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}:8083"
          homepage.description: "{{ 'The Cloud Native Application Proxy' if homepage_show_description else omit }}"
          homepage.server: "my-docker"
          homepage.container: "{{ traefik_container_name }}"
          homepage.showStats: "{{ traefik_homepage_showstats | string }}"
          homepage.widget.type: "traefik"
          homepage.widget.url: "http://{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}:8083"
          repliqate.enabled: "{{ traefik_repliqate_enabled | string }}"
          repliqate.engine: "{{ traefik_repliqate_engine }}"
          repliqate.schedule: "{{ traefik_repliqate_schedule }}"
          repliqate.backup_id: "{{ traefik_repliqate_backup_id }}"
          repliqate.retention: "{{ traefik_repliqate_retention }}"
          traefik.enable: "true"
          traefik.http.routers.traefik-router.rule: "Host(`{{ traefik_hostname }}.{{ ansible_nas_domain }}`)"
          traefik.http.routers.traefik-router.entrypoints: "websecure"
          traefik.http.routers.traefik-router.tls.certresolver: "letsencrypt"
          traefik.http.routers.traefik-router.tls.domains[0].main: "{{ ansible_nas_domain }}"
          traefik.http.routers.traefik-router.tls.domains[0].sans: "*.{{ ansible_nas_domain }}"
          traefik.http.routers.traefik-router.service: "api@internal"
          traefik.http.services.traefik-router.loadbalancer.server.port: "8083"
          traefik.http.routers.traefik-router.middlewares: "traefik-dash-redirect,traefik-whitelist{{ ',tinyauth-auth@docker' if traefik_tinyauth_enabled | bool else '' }}"
          traefik.http.middlewares.traefik-dash-redirect.redirectregex.regex: "^https://{{ traefik_hostname | replace('.', '\\.') }}\\.{{ ansible_nas_domain | replace('.', '\\.') }}/?$"
          traefik.http.middlewares.traefik-dash-redirect.redirectregex.replacement: "https://{{ traefik_hostname }}.{{ ansible_nas_domain }}/dashboard/"
          traefik.http.middlewares.traefik-whitelist.ipallowlist.sourcerange: "{{ traefik_traefik_whitelist }}"
          wud.tag.include: "^v\\d+\\.\\d+$"
          wud.tag.transform.type: "semver"
          wud.link.template: "https://hub.docker.com/_/traefik"
        cpu_shares: "{{ traefik_cpu_shares }}"
        memory: "{{ traefik_memory }}"
        memory_swap: "{{ traefik_memory_swap }}"
        recreate: "{{ template_config is changed }}"
        restart_policy: unless-stopped

    - name: Access {{ ansible_nas_app_name }} at
      ansible.builtin.debug:
        msg: >-
              {{
                ['http://' + hostvars[inventory_hostname]['ansible_default_ipv4']['address'] + ':' + (traefik_port_ui | string) + '/dashboard'] +
                (['https://' + traefik_hostname + '.' + ansible_nas_domain])
              }}
  when: traefik_enabled is true

- name: Stop {{ ansible_nas_app_name }}
  block:
    - name: Stop {{ ansible_nas_app_name }} Container
      community.docker.docker_container:
        name: "{{ traefik_container_name }}"
        state: absent
  when: traefik_enabled is false

- name: Data Archive {{ ansible_nas_app_name }}
  include_role:
    name: ansible-nas-archive
  vars:
    target_data_dir: "{{ traefik_data_directory }}"
  when:
    - archive_app_data_enabled is true
    - traefik_enabled is false