---
- name: Start {{ ansible_nas_app_name }}
  block:
    - name: Create {{ ansible_nas_app_name }} Directories
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
      with_items:
        - "{{ traefik_data_directory }}"
        - "{{ traefik_data_directory }}/data"
        - "{{ traefik_data_directory }}/letsencrypt"

    - name: Copy {{ ansible_nas_app_name }} Template config.toml
      ansible.builtin.template:
        src: traefik.toml
#       dest: "{{ traefik_data_directory }}/traefik.toml"
        dest: "{{ traefik_data_directory }}/data/traefik.toml"
      register: template_config

    - name: Create {{ ansible_nas_app_name }} Container
      community.docker.docker_container:
        container_default_behavior: "compatibility"
        name: "{{ traefik_container_name }}"
        hostname: "{{ traefik_container_name }}"
        image: "{{ traefik_image_name }}:{{ traefik_image_version }}"
        pull: true
        network_mode: host
        dns_servers: "{{ traefik_dns_servers }}"
        volumes:
#         - "{{ traefik_data_directory }}/traefik.toml:/etc/traefik/traefik.toml:ro"
          - "{{ traefik_data_directory }}/data:/etc/traefik"
          - "{{ traefik_data_directory }}/letsencrypt:/letsencrypt:rw"
          - "/var/run/docker.sock:/var/run/docker.sock:ro" # ignores this and uses UTC
        env: "{{ traefik_environment_variables }}"
        labels:
          autoheal: "{{ traefik_autoheal }}"
          com.centurylinklabs.watchtower.enable: "{{ traefik_watchtower_enable }}"
          dockflare.enable: "false"
          homepage.name: "{{ ansible_nas_app_name }}"
          homepage.group: "{{ traefik_homepage_group }}"
          homepage.icon: "{{ traefik_homepage_icon }}"
          homepage.href: "{{ traefik_homepage_href }}"
          homepage.siteMonitor: "http://{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}:8083"
          homepage.description: "{{ 'The Cloud Native Application Proxy' if homepage_show_description else omit }}"
          homepage.server: "my-docker"
          homepage.container: "{{ traefik_container_name }}"
          homepage.showStats: "{{ traefik_homepage_showstats }}"
          homepage.widget.type: "traefik"
          homepage.widget.url: "http://{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}:8083"
          traefik.enable: "false"
#         ^^^ TDL would like to enable and add a re-write rule to go to the dashboard

          #traefik.enable: "true"
          # Define the router that will catch the request
          #traefik.http.routers.dashboard-redirect.rule: "Host(`{{ traefik_hostname }}`)"
          #traefik.http.routers.dashboard-redirect.entrypoints: "websecure"
          #traefik.http.routers.dashboard-redirect.tls.certresolver: "{{ traefik_cert_resolver }}"
          # Link the router to the redirect middleware
          #traefik.http.routers.dashboard-redirect.middlewares: "redirect-to-ip@docker"
          # Define the redirect middleware
          #traefik.http.middlewares.redirect-to-ip.redirectregex.regex: "^https?://(.*)"
          #traefik.http.middlewares.redirect-to-ip.redirectregex.replacement: "http://{{ dashboard_ip }}:8083"
          # Assign a dummy service (required by Traefik, but never used because of the redirect)
          #traefik.http.routers.dashboard-redirect.service: "noop@internal"

          wud.tag.include: "^v\\d+\\.\\d+$"
          wud.tag.transform.type: "semver"
          wud.link.template: "https://hub.docker.com/_/traefik"
        cpu_shares: "{{ traefik_cpu_shares }}"
        memory: "{{ traefik_memory }}"
        recreate: "{{ template_config is changed }}"
        restart_policy: unless-stopped

    - name: Access {{ ansible_nas_app_name }} at
      ansible.builtin.debug:
        msg: >-
              {{
                ['http://' + hostvars[inventory_hostname]['ansible_default_ipv4']['address'] + ':' + (traefik_port_ui | string) + '/dashboard']
              }}
  when: traefik_enabled is true

- name: Stop {{ ansible_nas_app_name }}
  block:
    - name: Stop {{ ansible_nas_app_name }} Container
      community.docker.docker_container:
        name: "{{ traefik_container_name }}"
        state: absent
  when: traefik_enabled is false

- name: Data Archive {{ ansible_nas_app_name }}
  block:
    - name: Check for {{ ansible_nas_app_name }} Data Directory
      stat:
        path: "{{ traefik_data_directory }}"
      register: dir_stat

    - name: Archive {{ ansible_nas_app_name }} Data Directory
      ansible.builtin.archive:
        path: "{{ traefik_data_directory }}"
        dest: "{{ docker_home }}/{{ ansible_nas_app_name | lower }}.zip"
        force_archive: true
        format: zip
        owner: ansible-nas
        group: ansible-nas
        mode: u=rw,g=rw
        remove: true
      when: dir_stat.stat.exists
  when: traefik_enabled is false and archive_app_data_enabled is true
