---
# ANE
romm_enabled: false
romm_available_externally: false
romm_traefik_whitelist: "{{ lan }}"
romm_data_directory: "{{ docker_home }}/romm"

# network
romm_hostname: "romm"
romm_network_name: "romm"
romm_port_http: "3033"

# docker
romm_container_name: "romm"
romm_db_container_name: "romm-mariadb"
romm_memory_limit: "1G"
romm_db_memory_limit: "1G"

romm_db_password: "topsecret"
romm_igdb_client_id: "_generated_ID_here_"
romm_igdb_client_secret: "enter secret here"
romm_mobygames_api_key: "enter api key"
romm_steamgriddb_api_key: "enter api key"
romm_auth_secret_key: "90466b7b3e6412b560a11d722f4dc009eb18d81a1e50df5497df629fe32996c6"
romm_auth_username: "admin"
romm_auth_password: "admin"

# homepage
romm_homepage_group: "Apps"
romm_homepage_icon: "romm.png"
romm_homepage_href: "http://{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}:{{ romm_port_http }}"
romm_homepage_showstats: "false"
romm_homepage_widget_username: "your username"
romm_homepage_widget_password: "your password"
#romm_homepage_widget_fields: ["platforms", "totalRoms", "saves", "states"] # optional - default fields shown
romm_db_homepage_group: "DBs"
romm_db_homepage_icon: "mariadb.png"
romm_db_homepage_href: "http://{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}:{{ romm_port_http }}"
romm_db_homepage_showstats: "false"

# watchtower
romm_watchtower_enable: "false"
romm_db_watchtower_enable: "false"
