---
# ANE
ansible_nas_app_name: "Recyclarr"
recyclarr_enabled: false
recyclarr_data_directory: "{{ docker_home }}/recyclarr"

# network
recyclarr_hostname: "recyclarr"

# docker
recyclarr_container_name: "recyclarr"
recyclarr_image_name: "ghcr.io/recyclarr/recyclarr"
recyclarr_image_tag: "latest"
recyclarr_cpu_shares: "1024"
recyclarr_memory: "512m"

# autoheal
recyclarr_autoheal: "false"

# homepage
recyclarr_homepage_group: "Apps"
recyclarr_homepage_icon: "recyclarr.png"
recyclarr_homepage_showstats: "false"

# repliqate
recyclarr_repliqate_enabled: "false"
recyclarr_repliqate_engine: "restic"
recyclarr_repliqate_schedule: "@daily 3am"
recyclarr_repliqate_backup_id: "{{ recyclarr_container_name }}"
recyclarr_repliqate_retention: "30d"

# watchtower
recyclarr_watchtower_enable: "false"
