---
sonarr_enabled: false
sonarr_available_externally: false
sonarr_traefik_whitelist: "{{ lan }}"

# directories
sonarr_data_directory: "{{ docker_home }}/sonarr/config"
sonarr_tv_directory: "{{ tv_root }}"
sonarr_anime_directory: "{{ anime_root }}"
sonarr_download_directory: "{{ downloads_root }}"

# uid / gid
sonarr_user_id: "0"
sonarr_group_id: "0"

# network
sonarr_port: "8989"
sonarr_hostname: "sonarr"

# docker
sonarr_container_name: "sonarr"
sonarr_image_name: "linuxserver/sonarr"
sonarr_image_version: "latest"

# specs
sonarr_cpu_shares: 1024
sonarr_memory: 1g

# autoheal
sonarr_autoheal: "false"

# homepage
sonarr_homepage_group: "Media Management"
sonarr_homepage_icon: "sonarr.png"
sonarr_homepage_href: "http://{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}:{{ sonarr_port }}"
sonarr_homepage_showStats: "false"
sonarr_homepage_widget_key: "your_api_key_here"

# watchtower
sonarr_watchtower_monitor_only: "true"