---
- name: Start {{ ansible_nas_app_name }}
  block:
    - name: Create {{ ansible_nas_app_name }} Directories
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
      with_items:
        - "{{ mymediaforalexa_media_directory }}"
        - "{{ mymediaforalexa_data_directory }}"

    - name: Create {{ ansible_nas_app_name }} Container
      community.docker.docker_container:
        container_default_behavior: "compatibility"
        name: "{{ mymediaforalexa_container_name }}"
        image: "{{ mymediaforalexa_image_name }}:{{ mymediaforalexa_image_version }}"
        pull: true
        cpu_shares: "{{ mymediaforalexa_cpu_shares }}"
        volumes:
          - "{{ mymediaforalexa_media_directory }}:/medialibrary:rw"
          - "{{ mymediaforalexa_data_directory }}:/datadir:rw"
        network_mode: host
        restart_policy: unless-stopped
        memory: "{{ mymediaforalexa_memory }}"
        labels:
          autoheal: "{{ mymediaforalexa_autoheal }}"
          com.centurylinklabs.watchtower.monitor-only: "{{ mymediaforalexa_watchtower_monitor_only }}"
  when: mymediaforalexa_enabled is true

- name: Stop {{ ansible_nas_app_name }}
  block:
    - name: Stop {{ ansible_nas_app_name }} Container
      community.docker.docker_container:
        name: "{{ mymediaforalexa_container_name }}"
        state: absent
  when: mymediaforalexa_enabled is false

- name: Data Archive {{ ansible_nas_app_name }}
  block:
    - name: Check for {{ ansible_nas_app_name }} Data Directory
      stat:
        path: "{{ mymediaforalexa_data_directory }}"
      register: dir_stat

    - name: Archive {{ ansible_nas_app_name }} Data Directory
      ansible.builtin.archive:
        path: "{{ mymediaforalexa_data_directory }}"
        dest: "{{ docker_home }}/{{ ansible_nas_app_name | lower }}.zip"
        force_archive: true
        format: zip
        owner: ansible-nas
        group: ansible-nas
        mode: u=rw,g=rw
        remove: true
      when: dir_stat.stat.exists
  when: mymediaforalexa_enabled is false and archive_app_data_enabled is true

