---
- name: Start {{ ansible_nas_app_name }}
  block:
    - name: Create {{ ansible_nas_app_name }} Directories
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
      with_items:
        - "{{ mymediaforalexa_data_directory }}"
        - "{{ mymediaforalexa_media_directory }}"

    - name: Create {{ ansible_nas_app_name }} Container
      community.docker.docker_container:
        container_default_behavior: "compatibility"
        name: "{{ mymediaforalexa_container_name }}"
        image: "{{ mymediaforalexa_image_name }}:{{ mymediaforalexa_image_version }}"
        pull: true
        volumes:
          - "{{ mymediaforalexa_media_directory }}:/medialibrary:rw"
          - "{{ mymediaforalexa_data_directory }}:/datadir:rw"
        network_mode: host
        labels:
          autoheal: "{{ mymediaforalexa_autoheal }}"
          com.centurylinklabs.watchtower.enable: "{{ mymediaforalexa_watchtower_enable }}"
          dockflare.enable: "false"
          homepage.name: "{{ ansible_nas_app_name }}"
          homepage.group: "{{ mymediaforalexa_homepage_group }}"
          homepage.icon: "{{ mymediaforalexa_homepage_icon }}"
          homepage.description: "{{ 'mymediaforalexa description' if homepage_show_description else omit }}"
          homepage.server: "my-docker"
          homepage.container: "{{ mymediaforalexa_container_name }}"
          homepage.showStats: "{{ mymediaforalexa_homepage_showstats }}"
          repliqate.enabled: "{{ mymediaforalexa_repliqate_enabled }}"
          repliqate.engine: "{{ mymediaforalexa_repliqate_engine }}"
          repliqate.schedule: "{{ mymediaforalexa_repliqate_schedule }}"
          repliqate.backup_id: "{{ mymediaforalexa_repliqate_backup_id }}"
          repliqate.retention: "{{ mymediaforalexa_repliqate_retention }}"
          traefik.enable: "false"
          wud.tag.include: '^\d+\.\d+\.\d+\.\d+.*$'
          wud.tag.transform.type: "semver"
          wud.link.template: "https://hub.docker.com/r/bizmodeller/mymediaforalexa"
        cpu_shares: "{{ mymediaforalexa_cpu_shares }}"
        memory: "{{ mymediaforalexa_memory }}"
        restart_policy: unless-stopped
  when: mymediaforalexa_enabled is true

- name: Stop {{ ansible_nas_app_name }}
  block:
    - name: Stop {{ ansible_nas_app_name }} Container
      community.docker.docker_container:
        name: "{{ mymediaforalexa_container_name }}"
        state: absent
  when: mymediaforalexa_enabled is false

- name: Data Archive {{ ansible_nas_app_name }}
  block:
    - name: Check for {{ ansible_nas_app_name }} Data Directory
      stat:
        path: "{{ mymediaforalexa_data_directory }}"
      register: dir_stat

    - name: Archive {{ ansible_nas_app_name }} Data Directory
      ansible.builtin.archive:
        path: "{{ mymediaforalexa_data_directory }}"
        dest: "{{ docker_home }}/{{ ansible_nas_app_name | lower }}.zip"
        force_archive: true
        format: zip
        owner: ansible-nas
        group: ansible-nas
        mode: u=rw,g=rw
        remove: true
      when: dir_stat.stat.exists
  when: mymediaforalexa_enabled is false and archive_app_data_enabled is true

