---
- name: Start {{ ansible_nas_app_name }}
  block:
    - name: Create {{ ansible_nas_app_name }} Directories
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
      with_items:
        - "{{ mymediaforalexa_data_directory }}"
        - "{{ mymediaforalexa_media_directory }}"

    - name: Create {{ ansible_nas_app_name }} Container
      community.docker.docker_container:
        container_default_behavior: "compatibility"
        name: "{{ mymediaforalexa_container_name }}"
        image: "{{ mymediaforalexa_image_name }}:{{ mymediaforalexa_image_version }}"
        pull: true
        ports:
          - 52050:52050
          - 52051:52051
        volumes:
          - "{{ mymediaforalexa_media_directory }}:/medialibrary:rw"
          - "{{ mymediaforalexa_data_directory }}:/datadir:rw"
        network_mode: bridge
        labels:
          autoheal: "{{ mymediaforalexa_autoheal_enabled | ternary('true', 'false') }}"
          com.centurylinklabs.watchtower.enable: "{{ mymediaforalexa_watchtower_enabled | ternary('true', 'false') }}"
          dockflare.enable: "false"
          homepage.name: "{{ ansible_nas_app_name }}"
          homepage.group: "{{ mymediaforalexa_homepage_group }}"
          homepage.icon: "{{ mymediaforalexa_homepage_icon }}"
          homepage.description: "{{ 'a tiny media server that integrates with Alexa for controlling your media collection' if homepage_show_description else omit }}"
          homepage.server: "my-docker"
          homepage.container: "{{ mymediaforalexa_container_name }}"
          homepage.showStats: "{{ mymediaforalexa_homepage_showstats | ternary('true', 'false') }}"
          repliqate.enabled: "{{ mymediaforalexa_repliqate_enabled | ternary('true', 'false') }}"
          repliqate.engine: "{{ mymediaforalexa_repliqate_engine }}"
          repliqate.schedule: "{{ mymediaforalexa_repliqate_schedule }}"
          repliqate.backup_id: "{{ mymediaforalexa_repliqate_backup_id }}"
          repliqate.retention: "{{ mymediaforalexa_repliqate_retention }}"
          traefik.enable: "false"
          wud.tag.include: '^\d+\.\d+\.\d+\.\d+.*$'
          wud.tag.transform.type: "semver"
          wud.link.template: "https://hub.docker.com/r/bizmodeller/mymediaforalexa"
        cpu_shares: "{{ mymediaforalexa_cpu_shares }}"
        memory: "{{ mymediaforalexa_memory }}"
        memory_swap: "{{ mymediaforalexa_memory_swap }}"
        restart_policy: unless-stopped
  when: mymediaforalexa_enabled is true

- name: Stop {{ ansible_nas_app_name }}
  block:
    - name: Stop {{ ansible_nas_app_name }} Container
      community.docker.docker_container:
        name: "{{ mymediaforalexa_container_name }}"
        state: absent
  when: mymediaforalexa_enabled is false

- name: Data Archive {{ ansible_nas_app_name }}
  include_role:
    name: ansible-nas-archive
  vars:
    target_data_dir: "{{ mymediaforalexa_data_directory }}"
  when:
    - archive_app_data_enabled is true
    - mymediaforalexa_enabled is false