---
# ANE
ansible_nas_app_name: "Miniflux"
miniflux_enabled: false
miniflux_traefik_enabled: false
miniflux_traefik_whitelist: "{{ lan }}"

# directories
miniflux_data_directory: "{{ docker_home }}/miniflux"

# env
miniflux_admin_username: admin
miniflux_admin_password: "{{ ansible_nas_app_admin_password }}"
miniflux_db_postgres_user: "miniflux"
miniflux_db_postgres_password: "supersecure"

# network
miniflux_hostname: "miniflux"
miniflux_network_name: "miniflux"
miniflux_port_http: "8070"

# docker
miniflux_container_name: "miniflux"
miniflux_image_name: "docker.io/miniflux/miniflux"
miniflux_image_version: "latest"
miniflux_db_container_name: "miniflux-db"
miniflux_db_image_name: "postgres"
miniflux_db_image_version: "11.1"

# specs
miniflux_cpu_shares: 1024
miniflux_memory: "1G"
miniflux_memory_swap: -1
miniflux_db_cpu_shares: 1024
miniflux_db_memory: "1G"
miniflux_db_memory_swap: "{{ miniflux_db_memory }}"

# autoheal
miniflux_autoheal_enabled: false
miniflux_db_autoheal_enabled: false

# dockflare
miniflux_dockflare_enabled: false
miniflux_dockflare_access_group: ""

# homepage
miniflux_homepage_group: "Apps"
miniflux_homepage_icon: "miniflux.png"
miniflux_homepage_href: "http://{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}:{{ miniflux_port_http }}"
miniflux_homepage_showstats: false
miniflux_homepage_widget_key: ""
miniflux_db_homepage_group: "DBs"
miniflux_db_homepage_icon: "postgres.png"
miniflux_db_homepage_href: "{{ miniflux_homepage_href }}"
miniflux_db_homepage_showstats: false

# repliqate
miniflux_db_repliqate_enabled: false
miniflux_db_repliqate_engine: "restic"
miniflux_db_repliqate_schedule: "@daily 3am"
miniflux_db_repliqate_backup_id: "{{ miniflux_db_container_name }}"
miniflux_db_repliqate_retention: "30d"

# tinyauth
miniflux_tinyauth_enabled: false

# watchtower
miniflux_watchtower_enabled: false
miniflux_db_watchtower_enabled: false