---
# ANE
ansible_nas_app_name: "Arcane"
arcane_enabled: false
arcane_traefik_enabled: false
arcane_traefik_whitelist: "{{ lan }}"
arcane_data_directory: "{{ docker_home }}/arcane"

arcane_puid: "1000"
arcane_pgid: "1000"

# network
arcane_port_http: "3552"
arcane_hostname: "arcane"

# docker
arcane_container_name: "arcane"
arcane_image_name: "ghcr.io/ofkm/arcane"
arcane_image_tag: "latest"
arcane_cpu_shares: 1024
arcane_memory: "1G"
arcane_memory_swap: -1

# app
arcane_env_app_url: "http://{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}:{{ arcane_port_http }}"
arcane_env_encryption_key: "utNR/dbhefsHao21s4OlY85jhPP1LIDIYJpy9ioYtLo=" # openssl rand -base64 32
arcane_env_jwt_secret: "BiDGz3DUEdMVuwhdgf0/QsNnuwGNgNyDbhffZIwuFrYOAiJ1OPerEjIGr9StvV7YBbk8UpGOLJb4J7TZdaRdcw==" # openssl rand -base64 64

# autoheal
arcane_autoheal_enabled: false

# dockflare
arcane_dockflare_enabled: false
arcane_dockflare_access_group: ""

# homepage
arcane_homepage_group: "Apps"
arcane_homepage_icon: "arcane.png"
arcane_homepage_href: "http://{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}:{{ arcane_port_http }}"
arcane_homepage_showstats: false

# repliqate
arcane_repliqate_enabled: false
arcane_repliqate_engine: "restic"
arcane_repliqate_schedule: "@daily 3am"
arcane_repliqate_backup_id: "{{ arcane_container_name }}"
arcane_repliqate_retention: "30d"

# tinyauth
arcane_tinyauth_enabled: false

# watchtower
arcane_watchtower_enabled: false
