---
# ANE
ansible_nas_app_name: "SeedSync"
seedsync_enabled: false
seedsync_traefik_enabled: false
seedsync_traefik_whitelist: "{{ lan }}"

seedsync_data_directory: "{{ docker_home }}/seedsync"
seedsync_ssh_directory: "/home/{{ ansible_nas_user }}/.ssh"
#seedsync_ssh_directory: "{{ seedsync_data_directory }}/ssh"

# network
seedsync_hostname: "seedsync"
seedsync_port_http: "8800"

# docker
seedsync_container_name: "seedsync"
seedsync_image_name: "ipsingh06/seedsync"
seedsync_image_tag: "latest"

# specs
seedsync_cpu_shares: 1024
seedsync_memory: "512MB"
seedsync_memory_swap: -1

# autoheal
seedsync_autoheal_enabled: false

# dockflare
seedsync_dockflare_enabled: false
seedsync_dockflare_access_group: ""

# healthcheck
seedsync_healthcheck_test: ["CMD-SHELL", "curl -f http://127.0.0.1:8800/ || exit 1"]
seedsync_healthcheck_interval: 30s
seedsync_healthcheck_timeout: 10s
seedsync_healthcheck_retries: 3
seedsync_healthcheck_start_period: 20s

# homepage
seedsync_homepage_group: "Apps"
seedsync_homepage_icon: "sh-seedsync.png"
seedsync_homepage_href: "http://{{ hostvars[inventory_hostname]['ansible_facts']['default_ipv4']['address'] }}:{{ seedsync_port_http }}"
seedsync_homepage_showstats: false

# repliqate
seedsync_repliqate_enabled: false
seedsync_repliqate_engine: "restic"
seedsync_repliqate_schedule: "@daily 3am"
seedsync_repliqate_backup_id: "{{ seedsync_container_name }}"
seedsync_repliqate_retention: "30d"

# tinyauth
seedsync_tinyauth_enabled: false

# watchtower
seedsync_watchtower_enabled: false