---
# ANE
ansible_nas_app_name: "Gotify"
gotify_enabled: false
gotify_traefik_enabled: false
gotify_traefik_whitelist: "{{ lan }}"

# data directory
gotify_data_directory: "{{ docker_home }}/gotify"

# network
gotify_port_http: "2346"
gotify_hostname: "gotify"

# docker
gotify_container_name: "gotify"
gotify_image_name: "ghcr.io/gotify/server"
gotify_image_version: "latest"

gotify_user_id: "0"
gotify_group_id: "0"

# specs
gotify_cpu_shares: 1024
gotify_memory: "256M"
gotify_memory_swap: -1

# app
# https://gotify.net/docs/config
gotify_env_gotify_server_cors_alloworigins: '["*"]' # "[.+.{{ ansible_nas_domain }},{{ hostvars[inventory_hostname]['ansible_facts']['default_ipv4']['address'] }}:{{ gotify_port_http }}]" # [.+.example\.com, otherdomain\.com]
gotify_env_gotify_server_cors_allowmethods: "[GET, POST, OPTIONS, DELETE, PUT]"
gotify_env_gotify_server_cors_allowheaders: "[X-Gotify-Key, Authorization, Content-Type]" # [X-Gotify-Key, Authorization]
gotify_env_gotify_server_responseheaders: "" # {X-Custom-Header: "custom value", x-other: value}
gotify_env_gotify_server_stream_alloworigins: '["*"]' # '["localhost", ".+\\.{{ ansible_nas_domain | replace(".", "\\.") }}"]' # [.+.example\.com, otherdomain\.com]
gotify_env_gotify_server_trustedproxies: "[127.0.0.1, 172.16.0.0/12, {{ (ansible_facts['default_ipv4']['network'] + '/' + ansible_facts['default_ipv4']['netmask']) | ansible.utils.ipaddr('net') }}]"

# autoheal
gotify_autoheal_enabled: false

# dockflare
gotify_dockflare_enabled: false
gotify_dockflare_access_group: ""

# homepage
gotify_homepage_group: "Apps"
gotify_homepage_name: "Gotify"
gotify_homepage_icon: "gotify.png"
gotify_homepage_href: "http://{{ hostvars[inventory_hostname]['ansible_facts']['default_ipv4']['address'] }}:{{ gotify_port_http }}"
gotify_homepage_showstats: false
gotify_homepage_widget_key: ""

# repliqate
gotify_repliqate_enabled: false
gotify_repliqate_engine: "restic"
gotify_repliqate_schedule: "@daily 3am"
gotify_repliqate_backup_id: "{{ gotify_container_name }}"
gotify_repliqate_retention: "30d"

# tinyauth
gotify_tinyauth_enabled: false

# watchtower
gotify_watchtower_enabled: false