---
# ANE
ansible_nas_app_name: "Pi-hole"
pihole_enabled: false
pihole_traefik_enabled: false
pihole_traefik_whitelist: "{{ lan }}"

# directories
pihole_data_directory: "{{ docker_home }}/pihole"

# docker
pihole_container_name: "pihole"
pihole_image_name: "pihole/pihole"
pihole_image_tag: "latest"

# uid / gid
pihole_user_id: "1000"
pihole_group_id: "1000"

# network
pihole_port_http: "8888"
pihole_hostname: "pihole"
pihole_dns: "{{ ansible_nas_dns }}"

# specs
pihole_cpu_shares: 1024
pihole_memory: "1G"

# app
pihole_env_additional_packages: "" # dig, ping, nslookup already in the image
pihole_env_ftlconf_webserver_api_password: "{{ ansible_nas_app_admin_password }}"

# autoheal
pihole_autoheal_enabled: false

# dockflare
pihole_dockflare_enabled: false
pihole_dockflare_access_group: ""

# homepage
pihole_homepage_group: "Network"
pihole_homepage_icon: "pi-hole.png"
pihole_homepage_href: "http://{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}:{{ pihole_port_http }}/admin"
pihole_homepage_showstats: false
pihole_homepage_widget_key: "{{ pihole_env_ftlconf_webserver_api_password }}"

# repliqate
pihole_repliqate_enabled: false
pihole_repliqate_engine: "restic"
pihole_repliqate_schedule: "@daily 3am"
pihole_repliqate_backup_id: "{{ pihole_container_name }}"
pihole_repliqate_retention: "30d"

# tinyauth
pihole_tinyauth_enabled: false

# watchtower
pihole_watchtower_enabled: false
