---
- name: Start {{ ansible_nas_app_name }}
  block:
    - name: Create {{ ansible_nas_app_name }} Directories
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
      with_items:
        - "{{ huntarr_data_directory }}"
        - "{{ huntarr_data_directory }}/config"

    - name: Create {{ ansible_nas_app_name }} Container
      community.docker.docker_container:
        container_default_behavior: "compatibility"
        name: "{{ huntarr_container_name }}"
        hostname: "{{ huntarr_container_name }}"
        image: "{{ huntarr_image_name }}:{{ huntarr_image_tag }}"
        pull: true
        ports:
          - "{{ huntarr_port_http }}:9705"
        volumes:
          - "{{ huntarr_data_directory }}/config:/config"
        network_mode: bridge
        env:
          TZ: "{{ ansible_nas_timezone }}"
        labels:
          autoheal: "{{ huntarr_autoheal_enabled | ternary('true', 'false') }}"
          com.centurylinklabs.watchtower.enable: "{{ huntarr_watchtower_enabled | ternary('true', 'false') }}"
          dockflare.enable: "{{ huntarr_dockflare_enabled | ternary('true', 'false') }}"
          dockflare.access.group: "{{ huntarr_dockflare_access_group }}"
          dockflare.hostname: "{{ huntarr_hostname }}.{{ ansible_nas_domain }}"
          dockflare.service: "http://{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}:{{ huntarr_port_http }}"
          homepage.name: "{{ ansible_nas_app_name }}"
          homepage.group: "{{ huntarr_homepage_group }}"
          homepage.icon: "{{ huntarr_homepage_icon }}"
          homepage.href: "{{ huntarr_homepage_href }}"
          homepage.siteMonitor: "http://{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}:{{ huntarr_port_http }}"
          homepage.description: "{{ 'A specialized utility that automates discovering missing and upgrading your media collection!' if homepage_show_description else omit }}"
          homepage.server: "my-docker"
          homepage.container: "{{ huntarr_container_name }}"
          homepage.showStats: "{{ huntarr_homepage_showstats | ternary('true', 'false') }}"
          repliqate.enabled: "{{ huntarr_repliqate_enabled | ternary('true', 'false') }}"
          repliqate.engine: "{{ huntarr_repliqate_engine }}"
          repliqate.schedule: "{{ huntarr_repliqate_schedule }}"
          repliqate.backup_id: "{{ huntarr_repliqate_backup_id }}"
          repliqate.retention: "{{ huntarr_repliqate_retention }}"
          traefik.enable: "{{ huntarr_traefik_enabled | ternary('true', 'false') }}"
          traefik.http.routers.huntarr.rule: "Host(`{{ huntarr_hostname }}.{{ ansible_nas_domain }}`)"
          traefik.http.routers.huntarr.tls.certresolver: "letsencrypt"
          traefik.http.routers.huntarr.tls.domains[0].main: "{{ ansible_nas_domain }}"
          traefik.http.routers.huntarr.tls.domains[0].sans: "*.{{ ansible_nas_domain }}"
          traefik.http.routers.huntarr.middlewares: "huntarr@docker{{ ',tinyauth-auth@docker' if huntarr_tinyauth_enabled | bool else '' }}"
          traefik.http.middlewares.huntarr.IPAllowList.sourcerange: "{{ huntarr_traefik_whitelist }}"
          traefik.http.services.huntarr.loadbalancer.server.port: "9705"
          wud.tag.include: '^\d+\.\d+\.\d+$'
          wud.tag.transform.type: "semver"
          wud.link.template: "https://github.com/plexguide/Huntarr.io/pkgs/container/huntarr"
        cpu_shares: "{{ huntarr_cpu_shares }}"
        memory: "{{ huntarr_memory }}"
        memory_swap: "{{ huntarr_memory_swap }}"
        restart_policy: unless-stopped

    - name: Access {{ ansible_nas_app_name }} at
      ansible.builtin.debug:
        msg: >-
              {{
                ['http://' + hostvars[inventory_hostname]['ansible_default_ipv4']['address'] + ':' + (huntarr_port_http | string)] +
                (['https://' + huntarr_hostname + '.' + ansible_nas_domain] if (huntarr_traefik_enabled is true or huntarr_dockflare_enabled is true) else [])
              }}
  when: huntarr_enabled is true

- name: Stop {{ ansible_nas_app_name }}
  block:
    - name: Stop {{ ansible_nas_app_name }} Container
      community.docker.docker_container:
        name: "{{ huntarr_container_name }}"
        state: absent
  when: huntarr_enabled is false

- name: Data Archive {{ ansible_nas_app_name }}
  include_role:
    name: ansible-nas-archive
  vars:
    target_data_dir: "{{ huntarr_data_directory }}"
  when:
    - archive_app_data_enabled is true
    - huntarr_enabled is false