---
# ANE
ansible_nas_app_name: "FileBrowser Quantum"
filebrowser_quantum_enabled: false
filebrowser_quantum_available_externally: false
filebrowser_quantum_traefik_whitelist: "{{ lan }}"

# directories
filebrowser_quantum_data_directory: "{{ docker_home }}/filebrowser-quantum"

# docker
filebrowser_quantum_container_name: "filebrowser-quantum"
filebrowser_quantum_image_name: "ghcr.io/gtsteffaniak/filebrowser"
filebrowser_quantum_image_tag: "latest"

# network
filebrowser_quantum_port_http: "9014"
filebrowser_quantum_hostname: "filebrowser"

# specs
filebrowser_quantum_cpu_shares: 1024
filebrowser_quantum_memory: "1G"
filebrowser_quantum_memory_swap: -1

# app
filebrowser_quantum_folder: "/"
filebrowser_quantum_env_filebrowser_admin_password: "{{ ansible_nas_app_admin_password }}"

# autoheal
filebrowser_quantum_autoheal: false

# dockflare
filebrowser_quantum_dockflare_enabled: false
filebrowser_quantum_dockflare_access_group: ""

# homepage
filebrowser_quantum_homepage_group: "Apps"
filebrowser_quantum_homepage_icon: "filebrowser-quantum.png"
filebrowser_quantum_homepage_href: "http://{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}:{{ filebrowser_quantum_port_http }}"
filebrowser_quantum_homepage_showstats: false

# repliqate
filebrowser_quantum_repliqate_enabled: false
filebrowser_quantum_repliqate_engine: "restic"
filebrowser_quantum_repliqate_schedule: "@daily 3am"
filebrowser_quantum_repliqate_backup_id: "{{ filebrowser_quantum_container_name }}"
filebrowser_quantum_repliqate_retention: "30d"

# tinyauth
filebrowser_quantum_tinyauth_enabled: false

# watchtower
filebrowser_quantum_watchtower_enabled: false
