---
# ANE
ansible_nas_app_name: "Fast Music Remover"
fast_music_remover_enabled: false
fast_music_remover_available_externally: false
fast_music_remover_traefik_whitelist: "{{ lan }}"

# network
fast_music_remover_hostname: "fastmusicremover"
fast_music_remover_port_http: "3045"

# docker
fast_music_remover_container_name: "fast-music-remover"
fast_music_remover_image_name: "ghcr.io/omeryusufyagci/fast-music-remover"
fast_music_remover_image_tag: "latest"

# specs
fast_music_remover_cpu_shares: 1024
fast_music_remover_memory: "4g"
fast_music_remover_memory_swap: -1

# autoheal
fast_music_remover_autoheal: false

# dockflare
fast_music_remover_dockflare_enabled: false
fast_music_remover_dockflare_access_group: ""

# homepage 
fast_music_remover_homepage_group: "Apps"
fast_music_remover_homepage_icon: "fastmusicremover.png"
fast_music_remover_homepage_href: "http://{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}:{{ fast_music_remover_port_http }}"
fast_music_remover_homepage_showstats: false

# tinyauth
fast_music_remover_tinyauth_enabled: false

# watchtower
fast_music_remover_watchtower_enabled: false