---
# https://webmin.com/download/
- name: Install {{ ansible_nas_app_name }}
  block:
    - name: Create directory for APT keyrings
      ansible.builtin.file:
        path: /usr/share/keyrings
        state: directory
        mode: '0755'

    - name: Download {{ ansible_nas_app_name }} GPG key to a dedicated keyring file
      ansible.builtin.get_url:
        url: https://download.webmin.com/jcameron-key.asc
        dest: /usr/share/keyrings/webmin-archive-keyring.asc
        mode: '0644'

    - name: Add {{ ansible_nas_app_name }} APT repository with signed-by option
      ansible.builtin.apt_repository:
        repo: "deb [signed-by=/usr/share/keyrings/webmin-archive-keyring.asc] https://download.webmin.com/download/repository sarge contrib"
        state: present
        filename: webmin

    - name: Install {{ ansible_nas_app_name }}
      ansible.builtin.apt:
        name: webmin
        state: present
        update_cache: yes
  when: webmin_enabled is true

- name: Remove {{ ansible_nas_app_name }}
  block:
        - name: Uninstall {{ ansible_nas_app_name }}
          ansible.builtin.apt:
            name: webmin
            state: absent
            autoremove: yes

        - name: Remove {{ ansible_nas_app_name }} APT repository
          ansible.builtin.apt_repository:
            repo: "deb [signed-by=/usr/share/keyrings/webmin-archive-keyring.asc] https://download.webmin.com/download/repository sarge contrib"
            state: absent
            filename: webmin

        - name: Remove {{ ansible_nas_app_name }} GPG key
          ansible.builtin.file:
            path: /usr/share/keyrings/webmin-archive-keyring.asc
            state: absent
  when: webmin_enabled is false
