---
# ANE
idrive_proper_name: "IDrive"
idrive_enabled: false
idrive_traefik_enabled: false
idrive_traefik_whitelist: "{{ lan }}"
idrive_data_directory: "{{ docker_home }}/idrive"

# app
idrive_backup_source: "/"

# docker
idrive_container_name: "idrive"
idrive_image_name: "ghcr.io/snorre-k/idrive-docker"
idrive_image_tag: "latest"

# specs
idrive_cpu_shares: 1024
idrive_memory: "1G"
idrive_memory_swap: -1

# autoheal
idrive_autoheal_enabled: false

# homepage
idrive_homepage_group: "Misc"
idrive_homepage_icon: "https://cdn-icons-png.flaticon.com/512/873/873125.png"
idrive_homepage_showstats: false
idrive_homepage_href: "https://www.idrive.com/"

# repliqate
idrive_repliqate_enabled: false
idrive_repliqate_engine: "restic"
idrive_repliqate_schedule: "@daily 3am"
idrive_repliqate_backup_id: "{{ idrive_container_name }}"
idrive_repliqate_retention: "30d"

# watchtower
idrive_watchtower_enabled: false