---
- name: Start {{ ansible_nas_app_name }}
  block:
    - name: Create {{ ansible_nas_app_name }} Directories
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
      with_items:
        - "{{ miniflux_data_directory }}/postgres"

    - name: Set {{ ansible_nas_app_name }} FQDN var overrides
      ansible.builtin.set_fact:
        miniflux_homepage_href: "https://{{ miniflux_hostname }}.{{ ansible_nas_domain }}"
      when: miniflux_traefik_enabled | bool or miniflux_dockflare_enabled | bool

    - name: Create {{ ansible_nas_app_name }} network
      community.docker.docker_network:
        name: "{{ miniflux_network_name }}"

    - name: Create {{ ansible_nas_app_name }} DB Container
      community.docker.docker_container:
        container_default_behavior: "compatibility"
        name: "{{ miniflux_db_container_name }}"
        hostname: "{{ miniflux_db_container_name }}"
        image: "{{ miniflux_db_image_name }}:{{ miniflux_db_image_version }}"
        pull: true
        networks:
          - name: "{{ miniflux_network_name }}"
        network_mode: "{{ miniflux_network_name }}"
        volumes:
          - "{{ miniflux_data_directory }}/postgres:/var/lib/postgresql/data:rw"
        env:
          POSTGRES_USER: "{{ miniflux_db_postgres_user }}"
          POSTGRES_PASSWORD: "{{ miniflux_db_postgres_password }}"
          TZ: "{{ ansible_nas_timezone }}"
        healthcheck:
          test: ["CMD-SHELL", "pg_isready -U {{ miniflux_db_postgres_user }}"]
          interval: 10s
          timeout: 5s
          retries: 5
          start_period: 30s
        labels:
          autoheal: "{{ miniflux_db_autoheal_enabled | ternary('true', 'false') }}"
          com.centurylinklabs.watchtower.enable: "{{ miniflux_db_watchtower_enabled | ternary('true', 'false') }}"
          dockflare.enable: "false"
          homepage.name: "{{ ansible_nas_app_name }} PostgreSQL"
          homepage.group: "{{ miniflux_db_homepage_group }}"
          homepage.icon: "{{ miniflux_db_homepage_icon }}"
          homepage.href: "{{ miniflux_homepage_href }}"
          homepage.description: "{{ 'PostgreSQL Database Management System' if homepage_show_description else omit }}"
          homepage.server: "my-docker"
          homepage.container: "{{ miniflux_db_container_name }}"
          homepage.showStats: "{{ miniflux_db_homepage_showstats | ternary('true', 'false') }}"
          repliqate.enabled: "{{ miniflux_db_repliqate_enabled | ternary('true', 'false') }}"
          repliqate.engine: "{{ miniflux_db_repliqate_engine }}"
          repliqate.schedule: "{{ miniflux_db_repliqate_schedule }}"
          repliqate.backup_id: "{{ miniflux_db_repliqate_backup_id }}"
          repliqate.retention: "{{ miniflux_db_repliqate_retention }}"
          traefik.enable: "false"
          wud.tag.include: '^\d+\.\d+.*$'
          wud.tag.transform.type: "semver"
          wud.link.template: "https://hub.docker.com/_/postgres"
        cpu_shares: "{{ miniflux_db_cpu_shares }}"
        memory: "{{ miniflux_db_memory }}"
        memory_swap: "{{ miniflux_db_memory_swap }}"
        restart_policy: unless-stopped
      register: miniflux_db_status

    - name: Verify {{ ansible_nas_app_name }} DB is healthy
      community.docker.docker_container_info:
        name: "{{ miniflux_db_container_name }}"
      register: db_info
      until: "db_info.container.State.Health.Status == 'healthy'"
      retries: 30
      delay: 5

    - name: Create {{ ansible_nas_app_name }} Container
      community.docker.docker_container:
        container_default_behavior: "compatibility"
        name: "{{ miniflux_container_name }}"
        hostname: "{{ miniflux_container_name }}"
        image: "{{ miniflux_image_name }}:{{ miniflux_image_version }}"
        pull: true
        networks:
          - name: "{{ miniflux_network_name }}"
        network_mode: "{{ miniflux_network_name }}"
        ports:
          - "{{ miniflux_port_http }}:8080"
        env:
          DATABASE_URL: "postgres://{{ miniflux_db_postgres_user }}:{{ miniflux_db_postgres_password }}@{{ miniflux_db_container_name }}/miniflux?sslmode=disable"
          RUN_MIGRATIONS: "1"
          CREATE_ADMIN: "1"
          ADMIN_USERNAME: "{{ miniflux_admin_username }}"
          ADMIN_PASSWORD: "{{ miniflux_admin_password }}"
          TZ: "{{ ansible_nas_timezone }}"
        labels:
          autoheal: "{{ miniflux_autoheal_enabled | ternary('true', 'false') }}"
          com.centurylinklabs.watchtower.enable: "{{ miniflux_watchtower_enabled | ternary('true', 'false') }}"
          dockflare.enable: "{{ miniflux_dockflare_enabled | ternary('true', 'false') }}"
          dockflare.access.group: "{{ miniflux_dockflare_access_group }}"
          dockflare.hostname: "{{ miniflux_hostname }}.{{ ansible_nas_domain }}"
          dockflare.service: "http://{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}:{{ miniflux_port_http }}"
          homepage.name: "{{ ansible_nas_app_name }}"
          homepage.group: "{{ miniflux_homepage_group }}"
          homepage.icon: "{{ miniflux_homepage_icon }}"
          homepage.href: "{{ miniflux_homepage_href }}"
          homepage.description: "{{ 'a minimalist and opinionated feed reader' if homepage_show_description else omit }}"
          homepage.server: "my-docker"
          homepage.container: "{{ miniflux_container_name }}"
          homepage.showStats: "{{ miniflux_homepage_showstats | ternary('true', 'false') }}"
          homepage.widget.type: "miniflux"
          homepage.widget.url: "http://{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}:{{ miniflux_port_http }}"
          homepage.widget.key: "{{ miniflux_homepage_widget_key }}"
          repliqate.enabled: "false"
          traefik.enable: "{{ miniflux_traefik_enabled | ternary('true', 'false') }}"
          traefik.http.routers.miniflux.rule: "Host(`{{ miniflux_hostname }}.{{ ansible_nas_domain }}`)"
          traefik.http.routers.miniflux.tls.certresolver: "letsencrypt"
          traefik.http.routers.miniflux.tls.domains[0].main: "{{ ansible_nas_domain }}"
          traefik.http.routers.miniflux.tls.domains[0].sans: "*.{{ ansible_nas_domain }}"
          traefik.http.routers.miniflux.middlewares: "miniflux@docker{{ ',tinyauth-auth@docker' if miniflux_tinyauth_enabled | bool else '' }}"
          traefik.http.middlewares.miniflux.IPAllowList.sourcerange: "{{ miniflux_traefik_whitelist }}"
          traefik.http.services.miniflux.loadbalancer.server.port: "8080"
          wud.tag.include: '^\d+\.\d+\.\d+.*$'
          wud.tag.transform.type: "semver"
          wud.link.template: "https://hub.docker.com/r/miniflux/miniflux"
        cpu_shares: "{{ miniflux_cpu_shares }}"
        memory: "{{ miniflux_memory }}"
        memory_swap: "{{ miniflux_memory_swap }}"
        restart_policy: unless-stopped

    - name: Access {{ ansible_nas_app_name }} at
      ansible.builtin.debug:
        msg: >-
              {{
                ['http://' + hostvars[inventory_hostname]['ansible_default_ipv4']['address'] + ':' + (miniflux_port_http | string)] +
                (['https://' + miniflux_hostname + '.' + ansible_nas_domain] if (miniflux_traefik_enabled is true or miniflux_dockflare_enabled is true) else [])
              }}
  when: miniflux_enabled is true

- name: Stop {{ ansible_nas_app_name }}
  block:
    - name: Stop {{ ansible_nas_app_name }} Container
      community.docker.docker_container:
        name: "{{ miniflux_container_name }}"
        state: absent

    - name: Stop {{ ansible_nas_app_name }} DB Container
      community.docker.docker_container:
        name: "{{ miniflux_db_container_name }}"
        state: absent

    - name: Delete {{ ansible_nas_app_name }} Network
      community.docker.docker_network:
        name: "{{ miniflux_network_name }}"
        state: absent
  when: miniflux_enabled is false

- name: Data Archive {{ ansible_nas_app_name }}
  include_role:
    name: ansible-nas-archive
  vars:
    target_data_dir: "{{ miniflux_data_directory }}"
  when:
    - archive_app_data_enabled is true
    - miniflux_enabled is false