---
- name: Start {{ ansible_nas_app_name }}
  block:
    - name: Create {{ ansible_nas_app_name }} Directories
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
      with_items:
        - "{{ miniflux_data_directory }}/postgres"

    - name: Create {{ ansible_nas_app_name }} network
      community.docker.docker_network:
        name: "{{ miniflux_network_name }}"

    - name: Create {{ ansible_nas_app_name }} DB Container
      community.docker.docker_container:
        container_default_behavior: "compatibility"
        name: "{{ miniflux_db_container_name }}"
        hostname: "{{ miniflux_db_container_name }}"
        image: "{{ miniflux_db_image_name }}:{{ miniflux_db_image_version }}"
        pull: true
        cpu_shares: "{{ miniflux_db_cpu_shares }}"
        networks:
          - name: "{{ miniflux_network_name }}"
        network_mode: "{{ miniflux_network_name }}"
        volumes:
          - "{{ miniflux_data_directory }}/postgres:/var/lib/postgresql/data:rw"
        env:
          POSTGRES_USER: "miniflux"
          POSTGRES_PASSWORD: "supersecure"
        restart_policy: unless-stopped
        memory: "{{ miniflux_postgres_memory }}"
        labels:
          autoheal: "{{ miniflux_db_autoheal }}"
          com.centurylinklabs.watchtower.monitor-only: "{{ miniflux_db_watchtower_monitor_only }}"

    - name: Create {{ ansible_nas_app_name }} Container
      community.docker.docker_container:
        container_default_behavior: "compatibility"
        name: "{{ miniflux_container_name }}"
        hostname: "{{ miniflux_container_name }}"
        image: "{{ miniflux_image_name }}:{{ miniflux_image_version }}"
        pull: true
        cpu_shares: "{{ miniflux_cpu_shares }}"
        networks:
          - name: "{{ miniflux_network_name }}"
        network_mode: "{{ miniflux_network_name }}"
        ports:
          - "{{ miniflux_port }}:8080"
        env:
          DATABASE_URL: "postgres://miniflux:supersecure@{{ miniflux_db_container_name }}/miniflux?sslmode=disable"
          RUN_MIGRATIONS: "1"
          CREATE_ADMIN: "1"
          ADMIN_USERNAME: "{{ miniflux_admin_username }}"
          ADMIN_PASSWORD: "{{ miniflux_admin_password }}"
        restart_policy: unless-stopped
        memory: "{{ miniflux_memory }}"
        labels:
          autoheal: "{{ miniflux_autoheal }}"
          com.centurylinklabs.watchtower.monitor-only: "{{ miniflux_watchtower_monitor_only }}"
          traefik.enable: "{{ miniflux_available_externally | string }}"
          traefik.http.routers.miniflux.rule: "Host(`{{ miniflux_hostname }}.{{ ansible_nas_domain }}`)"
          traefik.http.routers.miniflux.tls.certresolver: "letsencrypt"
          traefik.http.routers.miniflux.tls.domains[0].main: "{{ ansible_nas_domain }}"
          traefik.http.routers.miniflux.tls.domains[0].sans: "*.{{ ansible_nas_domain }}"
          traefik.http.services.miniflux.loadbalancer.server.port: "8080"
  when: miniflux_enabled is true

- name: Stop {{ ansible_nas_app_name }}
  block:
    - name: Stop {{ ansible_nas_app_name }} Container
      community.docker.docker_container:
        name: "{{ miniflux_container_name }}"
        state: absent

    - name: Stop {{ ansible_nas_app_name }} DB Container
      community.docker.docker_container:
        name: "{{ miniflux_db_container_name }}"
        state: absent
  when: miniflux_enabled is false

- name: Data Archive {{ ansible_nas_app_name }}
  block:
    - name: Check for {{ ansible_nas_app_name }} Data Directory
      stat:
        path: "{{ miniflux_data_directory }}"
      register: dir_stat

    - name: Archive {{ ansible_nas_app_name }} Data Directory
      ansible.builtin.archive:
        path: "{{ miniflux_data_directory }}"
        dest: "{{ docker_home }}/{{ ansible_nas_app_name | lower }}.zip"
        force_archive: true
        format: zip
        owner: ansible-nas
        group: ansible-nas
        mode: u=rw,g=rw
        remove: true
      when: dir_stat.stat.exists
  when: miniflux_enabled is false and archive_app_data_enabled is true
