---
- name: Start {{ ansible_nas_app_name }}
  block:
    - name: Create {{ ansible_nas_app_name }} Directories
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
      with_items:
        - "{{ beszel_data_directory }}"
        - "{{ beszel_data_directory }}/data"

    - name: Set {{ ansible_nas_app_name }} FQDN var overrides
      ansible.builtin.set_fact:
        beszel_homepage_href: "https://{{ beszel_hostname }}.{{ ansible_nas_domain }}"
      when: beszel_traefik_enabled | bool or beszel_dockflare_enabled | bool

    - name: Create {{ ansible_nas_app_name }} Container
      community.docker.docker_container:
        container_default_behavior: "compatibility"
        name: "{{ beszel_container_name }}"
        hostname: "{{ beszel_container_name }}"
        image: "{{ beszel_image_name }}:{{ beszel_image_tag }}"
        pull: true
        ports:
          - "{{ beszel_port_http }}:8090"
        volumes:
          - "{{ beszel_data_directory }}/data:/beszel_data"
        network_mode: bridge
        env:
          TZ: "{{ ansible_nas_timezone }}"
        labels:
          autoheal: "{{ beszel_autoheal_enabled | ternary('true', 'false') }}"
          com.centurylinklabs.watchtower.enable: "{{ beszel_watchtower_enabled | ternary('true', 'false') }}"
          dockflare.enable: "{{ beszel_dockflare_enabled | ternary('true', 'false') }}"
          dockflare.access.group: "{{ beszel_dockflare_access_group }}"
          dockflare.hostname: "{{ beszel_hostname }}.{{ ansible_nas_domain }}"
          dockflare.service: "http://{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}:{{ beszel_port_http }}"
          homepage.name: "{{ ansible_nas_app_name }}"
          homepage.group: "{{ beszel_homepage_group }}"
          homepage.icon: "{{ beszel_homepage_icon }}"
          homepage.href: "{{ beszel_homepage_href }}"
          homepage.siteMonitor: "http://{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}:{{ beszel_port_http }}"
          homepage.description: "{{ 'Lightweight server monitoring hub with historical data, docker stats, and alerts.' if homepage_show_description else omit }}"
          homepage.server: "my-docker"
          homepage.container: "{{ beszel_container_name }}"
          homepage.showStats: "{{ beszel_homepage_showstats | ternary('true', 'false') }}"
          homepage.widget.type: "beszel"
          homepage.widget.url: "http://{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}:{{ beszel_port_http }}"
          homepage.widget.username: "{{ beszel_homepage_widget_username }}"
          homepage.widget.password: "{{ beszel_homepage_widget_password }}"
          homepage.widget.systemId: "{{ beszel_homepage_widget_systemid }}"
          homepage.widget.version: "{{ beszel_homepage_widget_version }}"
          repliqate.enabled: "{{ beszel_repliqate_enabled | ternary('true', 'false') }}"
          repliqate.engine: "{{ beszel_repliqate_engine }}"
          repliqate.schedule: "{{ beszel_repliqate_schedule }}"
          repliqate.backup_id: "{{ beszel_repliqate_backup_id }}"
          repliqate.retention: "{{ beszel_repliqate_retention }}"
          traefik.enable: "{{ beszel_traefik_enabled | ternary('true', 'false') }}"
          traefik.http.routers.beszel.rule: "Host(`{{ beszel_hostname }}.{{ ansible_nas_domain }}`)"
          traefik.http.routers.beszel.tls.certresolver: "letsencrypt"
          traefik.http.routers.beszel.tls.domains[0].main: "{{ ansible_nas_domain }}"
          traefik.http.routers.beszel.tls.domains[0].sans: "*.{{ ansible_nas_domain }}"
          traefik.http.routers.beszel.middlewares: "beszel@docker{{ ',tinyauth-auth@docker' if beszel_tinyauth_enabled | bool else '' }}"
          traefik.http.middlewares.beszel.IPAllowList.sourcerange: "{{ beszel_traefik_whitelist }}"
          traefik.http.services.beszel.loadbalancer.server.port: "8090"
          wud.tag.include: '^\d+\.\d+\.\d+.*$'
          wud.tag.transform.type: "semver"
          wud.link.template: "https://hub.docker.com/r/henrygd/beszel"
        cpu_shares: "{{ beszel_cpu_shares }}"
        memory: "{{ beszel_memory }}"
        memory_swap: "{{ beszel_memory_swap }}"
        restart_policy: unless-stopped

    - name: Access {{ ansible_nas_app_name }} at
      ansible.builtin.debug:
        msg: >-
              {{
                ['http://' + hostvars[inventory_hostname]['ansible_default_ipv4']['address'] + ':' + (beszel_port_http | string)] +
                (['https://' + beszel_hostname + '.' + ansible_nas_domain] if (beszel_traefik_enabled is true or beszel_dockflare_enabled is true) else [])
              }}
  when: beszel_enabled is true

- name: Stop {{ ansible_nas_app_name }}
  block:
    - name: Stop {{ ansible_nas_app_name }} Container
      community.docker.docker_container:
        name: "{{ beszel_container_name }}"
        state: absent
  when: beszel_enabled is false

- name: Data Archive {{ ansible_nas_app_name }}
  include_role:
    name: ansible-nas-archive
  vars:
    target_data_dir: "{{ beszel_data_directory }}"
  when:
    - archive_app_data_enabled is true
    - beszel_enabled is false
