---
# ANE
ansible_nas_app_name: "portracker"
portracker_enabled: false
portracker_available_externally: false
portracker_traefik_whitelist: "{{ lan }}"

# directories
portracker_data_directory: "{{ docker_home }}/portracker"

# docker
portracker_container_name: "portracker"
portracker_image_name: "mostafawahied/portracker"
portracker_image_tag: "latest"

# network
portracker_port_http: "4999"
portracker_hostname: "portracker"

# specs
portracker_cpu_shares: 1024
portracker_memory: "1G"

# autoheal
portracker_autoheal: false

# dockflare
portracker_dockflare_enabled: false
portracker_dockflare_access_group: ""

# homepage
portracker_homepage_group: "Apps"
portracker_homepage_icon: "sh-portracker.png"
portracker_homepage_href: "http://{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}:{{ portracker_port_http }}"
portracker_homepage_showstats: false

# repliqate
portracker_repliqate_enabled: false
portracker_repliqate_engine: "restic"
portracker_repliqate_schedule: "@daily 3am"
portracker_repliqate_backup_id: "{{ portracker_container_name }}"
portracker_repliqate_retention: "30d"

# tinyauth
portracker_tinyauth_enabled: false

# watchtower
portracker_watchtower_enabled: false
