---
- name: Start {{ ansible_nas_app_name }}
  block:
    - name: Create {{ ansible_nas_app_name }} Container
      community.docker.docker_container:
        container_default_behavior: "compatibility"
        name: "{{ chatpadai_container_name }}"
        hostname: "{{ chatpadai_container_name }}"
        image: "{{ chatpadai_image_name }}:{{ chatpadai_image_tag }}"
        pull: true
        network_mode: "bridge"
        env:
          TZ: "{{ ansible_nas_timezone }}"
        ports:
          - "{{ chatpadai_port_http }}: 80"
        labels:
          autoheal: "{{ chatpadai_autoheal }}"
          com.centurylinklabs.watchtower.enable: "{{ chatpadai_watchtower_enable }}"
          dockflare.enable: "{{ chatpadai_dockflare_tunnel }}"
          dockflare.access.group: "{{ chatpadai_dockflare_access_group }}"
          dockflare.hostname: "{{ chatpadai_hostname }}.{{ ansible_nas_domain }}"
          dockflare.service: "http://{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}:{{ chatpadai_port_http }}"
          homepage.name: "{{ ansible_nas_app_name }}"
          homepage.group: "{{ chatpadai_homepage_group }}"
          homepage.icon: "{{ chatpadai_homepage_icon }}"
          homepage.href: "{{ chatpadai_homepage_href }}"
          homepage.siteMonitor: "http://{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}:{{ chatpadai_port_http }}"
          homepage.description: "{{ 'Not just another ChatGPT user-interface!' if homepage_show_description else omit }}"
          homepage.server: "my-docker"
          homepage.container: "{{ chatpadai_container_name }}"
          homepage.showStats: "{{ chatpadai_homepage_showstats }}"
          traefik.enable: "{{ chatpadai_available_externally | string }}"
          traefik.http.routers.chatpad.rule: "Host(`{{ chatpadai_hostname }}.{{ ansible_nas_domain }}`)"
          traefik.http.routers.chatpad.tls.certresolver: "letsencrypt"
          traefik.http.routers.chatpad.tls.domains[0].main: "{{ ansible_nas_domain }}"
          traefik.http.routers.chatpad.tls.domains[0].sans: "*.{{ ansible_nas_domain }}"
          traefik.http.routers.frontend.middlewares: "{{ chatpadai_hostname }}"
          traefik.http.routers.chatpad.middlewares: "{{ chatpadai_hostname }}@docker"
          traefik.http.middlewares.chatpad.IPAllowList.sourcerange: "{{ chatpadai_traefik_whitelist }}"
          traefik.http.services.chatpad.loadbalancer.server.port: "80"
          wud.watch.digest: "true"
          wud.link.template: "https://github.com/deiucanta/chatpad"
        cpu_shares: "{{ chatpadai_cpu_shares }}"
        memory: "{{ chatpadai_memory }}"
        restart_policy: unless-stopped

    - name: Access {{ ansible_nas_app_name }} at
      ansible.builtin.debug:
        msg: >-
              {{
                ['http://' + hostvars[inventory_hostname]['ansible_default_ipv4']['address'] + ':' + (chatpadai_port_http | string)] +
                (['https://' + chatpadai_hostname + '.' + ansible_nas_domain] if (chatpadai_available_externally is true or chatpadai_dockflare_tunnel is true) else [])
              }}
  when: chatpadai_enabled is true

- name: Stop {{ ansible_nas_app_name }}
  block:
    - name: Stop {{ ansible_nas_app_name }} Container
      community.docker.docker_container:
        name: "{{ chatpadai_container_name }}"
        state: absent
  when: chatpadai_enabled is false
