---
- name: Start {{ ansible_nas_app_name }}
  block:
    - name: Create {{ ansible_nas_app_name }} Directories
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
      with_items:
        - "{{ tinyauth_data_directory }}"
        - "{{ tinyauth_data_directory }}/data"

    - name: Create {{ ansible_nas_app_name }} Container
      community.docker.docker_container:
        container_default_behavior: "compatibility"
        name: "{{ tinyauth_container_name }}"
        hostname: "{{ tinyauth_container_name }}"
        image: "{{ tinyauth_image_name }}:{{ tinyauth_image_tag }}"
        pull: true
        ports:
          - "{{ tinyauth_port_http }}:{{ tinyauth_port_http }}"
        env:
          APP_URL: "https://{{ tinyauth_hostname }}.{{ ansible_nas_domain }}"
          PORT: "{{ tinyauth_port_http }}"
          SECRET: "{{ tinyauth_env_secret }}"
          USERS: "{{ tinyauth_env_users }}"
          TZ: "{{ ansible_nas_timezone }}"
        volumes:
          - "{{ tinyauth_data_directory }}/data:/data"
          - "/var/run/docker.sock:/var/run/docker.sock"
        labels:
          autoheal: "{{ tinyauth_autoheal_enabled | ternary('true', 'false') }}"
          com.centurylinklabs.watchtower.enable: "{{ tinyauth_watchtower_enabled | ternary('true', 'false') }}"
          dockflare.enable: "{{ tinyauth_dockflare_enabled | ternary('true', 'false') }}"
          dockflare.access.group: "{{ tinyauth_dockflare_access_group }}"
          dockflare.hostname: "{{ tinyauth_hostname }}.{{ ansible_nas_domain }}"
          dockflare.service: "http://{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}:{{ tinyauth_port_http }}"
          homepage.name: "{{ ansible_nas_app_name }}"
          homepage.group: "{{ tinyauth_homepage_group }}"
          homepage.icon: "{{ tinyauth_homepage_icon }}"
          homepage.href: "{{ tinyauth_homepage_href }}"
          homepage.description: "{{ 'The simplest way to protect your apps with a login screen.' if homepage_show_description else omit }}"
          homepage.server: "my-docker"
          homepage.container: "{{ tinyauth_container_name }}"
          homepage.showStats: "{{ tinyauth_homepage_showstats | ternary('true', 'false') }}"
          homepage.siteMonitor: "http://{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}:{{ tinyauth_port_http }}"
          traefik.enable: "true"
          traefik.http.routers.tinyauth.rule: "Host(`{{ tinyauth_hostname }}.{{ ansible_nas_domain }}`)"
          traefik.http.routers.tinyauth.tls.certresolver: "letsencrypt"
          traefik.http.middlewares.tinyauth-auth.forwardauth.address: "http://127.0.0.1:{{ tinyauth_port_http }}/api/auth/traefik"
          traefik.http.middlewares.tinyauth-auth.forwardauth.trustForwardHeader: "true"
          traefik.http.middlewares.tinyauth-auth.forwardauth.authResponseHeaders: "X-Forwarded-User"
          traefik.http.services.tinyauth.loadbalancer.server.port: "{{ tinyauth_port_http }}"
          wud.tag.include: '^v\d+\.\d+\.\d+$'
          wud.tag.transform.type: "semver"
          wud.link.template: "https://github.com/steveiliop/tinyauth/pkgs/container/tinyauth"
        cpu_shares: "{{ tinyauth_cpu_shares }}"
        memory: "{{ tinyauth_memory }}"
        memory_swap: "{{ tinyauth_memory_swap }}"
        restart_policy: unless-stopped

    - name: Access {{ ansible_nas_app_name }} at
      ansible.builtin.debug:
        msg: >-
              {{
                ['http://' + hostvars[inventory_hostname]['ansible_default_ipv4']['address'] + ':' + (tinyauth_port_http | string)] +
                (['https://' + tinyauth_hostname + '.' + ansible_nas_domain] if (tinyauth_traefik_enabled is true or tinyauth_dockflare_enabled is true) else [])
              }}
  when: tinyauth_enabled is true

- name: Stop {{ ansible_nas_app_name }}
  block:
    - name: Stop {{ ansible_nas_app_name }} Container
      community.docker.docker_container:
        name: "{{ tinyauth_container_name }}"
        state: absent
  when: tinyauth_enabled is false
