---
# ANE
ansible_nas_app_name: "Minecraft Server"
minecraft_server_enabled: false
minecraft_server_data_directory: "{{ docker_home }}/minecraft-server"

# network
minecraft_server_port: "25565"

# docker
minecraft_server_container_name: "minecraft-server"
minecraft_server_image_name: "itzg/minecraft-server"
minecraft_server_image_version: "latest"
minecraft_server_cpu_shares: 1024
minecraft_server_memory: 1024MB

# autoheal
minecraft_server_autoheal: "false"

# homepage
minecraft_server_homepage_group: "Misc"
minecraft_server_homepage_icon: "minecraft.png"
minecraft_server_homepage_showStats: "false"

# watchtower
minecraft_server_watchtower_monitor_only: "true"