---
# ANE
ansible_nas_app_name: "Minecraft Server"
minecraft_server_enabled: false
minecraft_server_data_directory: "{{ docker_home }}/minecraft-server"

# network
minecraft_server_port: "25565"

# docker
minecraft_server_container_name: "minecraft-server"
minecraft_server_image_name: "ghcr.io/itzg/minecraft-server"
minecraft_server_image_version: "latest"

# specs
minecraft_server_cpu_shares: 1024
minecraft_server_memory: 1024MB
minecraft_server_memory_swap: -1

# autoheal
minecraft_server_autoheal: false

# homepage
minecraft_server_homepage_group: "Misc"
minecraft_server_homepage_icon: "minecraft.png"
minecraft_server_homepage_showstats: false

# repliqate
minecraft_server_repliqate_enabled: false
minecraft_server_repliqate_engine: "restic"
minecraft_server_repliqate_schedule: "@daily 3am"
minecraft_server_repliqate_backup_id: "{{ minecraft_server_container_name }}"
minecraft_server_repliqate_retention: "30d"

# watchtower
minecraft_server_watchtower_enabled: false