---
# ANE
ansible_nas_app_name: "IT-Tools"
ittools_enabled: false
ittools_available_externally: false
ittools_traefik_whitelist: "{{ lan }}"

# docker
ittools_container_name: "it-tools"
ittools_image_name: "corentinth/it-tools"
ittools_image_tag: "latest"

# network
ittools_port_http: "8991"
ittools_hostname: "ittools"

# specs
ittools_cpu_shares: 1024
ittools_memory: "1G"

# autoheal
ittools_autoheal: "false"

# dockflare
ittools_dockflare_tunnel: "false"
ittools_dockflare_access_group: ""

# homepage
ittools_homepage_group: "Apps"
ittools_homepage_icon: "it-tools.png"
ittools_homepage_href: "http://{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}:{{ ittools_port }}"
ittools_homepage_showstats: "false"

# tinyauth
ittools_tinyauth_enabled: false

# watchtower
ittools_watchtower_enable: "false"
