---
- name: Start {{ ansible_nas_app_name }}
  block:
    - name: Create {{ ansible_nas_app_name }} Directories
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        mode: 0777
      with_items:
        - "{{ pytivo_data_directory }}"
        - "{{ pytivo_data_directory }}/config"

    - name: Create {{ ansible_nas_app_name }} Container
      community.docker.docker_container:
        container_default_behavior: "compatibility"
        name: "{{ pytivo_container_name }}"
        hostname: "{{ pytivo_container_name }}"
        image: "{{ pytivo_image_name }}:{{ pytivo_image_version }}"
        pull: true
        volumes:
          - "/etc/localtime:/etc/localtime:ro"
          - "{{ pytivo_data_directory }}/config:/config:rw"
          - "{{ pytivo_movies_directory }}:/movies:ro"
          - "{{ pytivo_tv_directory }}:/tv:ro"
          - "{{ pytivo_photos_directory }}:/photos:ro"
          - "{{ pytivo_music_directory }}:/music:ro"
          - "{{ pytivo_podcasts_directory }}:/podcasts:ro"
        ports:
          - "9032:9032"
          - "2190:2190/udp"
        env:
          TZ: "{{ ansible_nas_timezone }}"
          PUID: "{{ pytivo_user_id }}"
          PGID: "{{ pytivo_group_id }}"
        labels:
          autoheal: "{{ pytivo_autoheal }}"
          com.centurylinklabs.watchtower.enable: "{{ pytivo_watchtower_enable }}"
          dockflare.enable: "{{ pytivo_dockflare_tunnel }}"
          dockflare.access.group: "{{ pytivo_dockflare_access_group }}"
          dockflare.hostname: "{{ pytivo_hostname }}.{{ ansible_nas_domain }}"
          dockflare.service: "http://{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}:9032"
          homepage.name: "{{ ansible_nas_app_name }}"
          homepage.group: "{{ pytivo_homepage_group }}"
          homepage.icon: "{{ pytivo_homepage_icon }}"
          homepage.href: "{{ pytivo_homepage_href }}"
          homepage.description: "{{ 'pytivo description' if homepage_show_description else omit }}"
          homepage.server: "my-docker"
          homepage.container: "{{ pytivo_container_name }}"
          homepage.showStats: "{{ pytivo_homepage_showstats }}"
          homepage.siteMonitor: "http://{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}:{{ pytivo_port }}"
          traefik.enable: "{{ pytivo_available_externally | string }}"
          traefik.http.routers.pytivo.rule: "Host(`{{ pytivo_hostname }}.{{ ansible_nas_domain }}`)"
          traefik.http.routers.pytivo.tls.certresolver: "letsencrypt"
          traefik.http.routers.pytivo.tls.domains[0].main: "{{ ansible_nas_domain }}"
          traefik.http.routers.pytivo.tls.domains[0].sans: "*.{{ ansible_nas_domain }}"
          traefik.http.routers.frontend.middlewares: "{{ pytivo_hostname }}"
          traefik.http.routers.pytivo.middlewares: "{{ pytivo_hostname }}@docker"
          traefik.http.middlewares.pytivo.IPAllowList.sourcerange: "{{ pytivo_traefik_whitelist }}"
          traefik.http.services.pytivo.loadbalancer.server.port: "9032"
          wud.watch.digest: "true"
          wud.link.template: "https://hub.docker.com/r/pinion/docker-pytivo"
        cpu_shares: "{{ pytivo_cpu_shares }}"
        memory: "{{ pytivo_memory }}"
        restart_policy: unless-stopped
  when: pytivo_enabled is true

- name: Stop {{ ansible_nas_app_name }}
  block:
    - name: Stop {{ ansible_nas_app_name }} Container
      community.docker.docker_container:
        name: "{{ pytivo_container_name }}"
        state: absent
  when: pytivo_enabled is false

- name: Data Archive {{ ansible_nas_app_name }}
  block:
    - name: Check for {{ ansible_nas_app_name }} Data Directory
      stat:
        path: "{{ pytivo_data_directory }}"
      register: dir_stat

    - name: Archive {{ ansible_nas_app_name }} Data Directory
      ansible.builtin.archive:
        path: "{{ pytivo_data_directory }}"
        dest: "{{ docker_home }}/{{ ansible_nas_app_name | lower }}.zip"
        force_archive: true
        format: zip
        owner: ansible-nas
        group: ansible-nas
        mode: u=rw,g=rw
        remove: true
      when: dir_stat.stat.exists
  when: pytivo_enabled is false and archive_app_data_enabled is true
