---
- name: Start {{ ansible_nas_app_name }}
  block:
    - name: Create {{ ansible_nas_app_name }} Directories
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
      with_items:
        - "{{ music_assistant_data_directory }}"
        - "{{ music_assistant_data_directory }}/data"

    - name: Create {{ ansible_nas_app_name }} Container
      community.docker.docker_container:
        container_default_behavior: "compatibility"
        name: "{{ music_assistant_container_name }}"
        hostname: "{{ music_assistant_container_name }}"
        image: "{{ music_assistant_image_name }}:{{ music_assistant_image_tag }}"
        pull: true
        privileged: true
        network_mode: host
        volumes:
          - "{{ music_assistant_data_directory }}/data:/data"
          - "{{ music_root }}:/media:ro"
#        ports:
#          - 8095:8095
        env:
          TZ: "{{ ansible_nas_timezone }}"
        labels:
          autoheal: "{{ music_assistant_autoheal }}"
          com.centurylinklabs.watchtower.enable: "{{ music_assistant_watchtower_enable }}"
          dockflare.enable: "false"
          homepage.name: "{{ ansible_nas_app_name }}"
          homepage.group: "{{ music_assistant_homepage_group }}"
          homepage.icon: "{{ music_assistant_homepage_icon }}"
          homepage.href: "{{ music_assistant_homepage_href }}"
          homepage.description: "{{ 'a free, opensource Media library manager that connects to your streaming services and a wide range of connected speakers' if homepage_show_description else omit }}"
          homepage.server: "my-docker"
          homepage.container: "{{ music_assistant_container_name }}"
          homepage.showStats: "{{ music_assistant_homepage_showstats }}"
          homepage.siteMonitor: "http://{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}:{{ music_assistant_port_http }}"
          repliqate.enabled: "{{ music_assistant_repliqate_enabled }}"
          repliqate.engine: "{{ music_assistant_repliqate_engine }}"
          repliqate.schedule: "{{ music_assistant_repliqate_schedule }}"
          repliqate.backup_id: "{{ music_assistant_repliqate_backup_id }}"
          repliqate.retention: "{{ music_assistant_repliqate_retention }}"
          traefik.enable: "false"
          wud.tag.include: '^\d+\.\d+\.\d+$'
          wud.tag.transform.type: "semver"
          wud.link.template: "https://github.com/music-assistant/server/pkgs/container/server"
        cpu_shares: "{{ music_assistant_cpu_shares }}"
        memory: "{{ music_assistant_memory }}"
        restart_policy: unless-stopped
  when: music_assistant_enabled is true

- name: Stop {{ ansible_nas_app_name }}
  block:
    - name: Stop {{ ansible_nas_app_name }} Container
      community.docker.docker_container:
        name: "{{ music_assistant_container_name }}"
        state: absent
  when: music_assistant_enabled is false

- name: Data Archive {{ ansible_nas_app_name }}
  block:
    - name: Check for {{ ansible_nas_app_name }} Data Directory
      stat:
        path: "{{ music_assistant_data_directory }}"
      register: dir_stat

    - name: Archive {{ ansible_nas_app_name }} Data Directory
      ansible.builtin.archive:
        path: "{{ music_assistant_data_directory }}"
        dest: "{{ docker_home }}/{{ ansible_nas_app_name | lower }}.zip"
        force_archive: true
        format: zip
        owner: ansible-nas
        group: ansible-nas
        mode: u=rw,g=rw
        remove: true
      when: dir_stat.stat.exists
  when: music_assistant_enabled is false and archive_app_data_enabled is true
