---
- name: Start {{ ansible_nas_app_name }}
  block:
    - name: Create {{ ansible_nas_app_name }} Directories
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
      with_items:
        - "{{ music_assistant_data_directory }}"
        - "{{ music_assistant_data_directory }}/data"
        - "{{ music_assistant_music_directory }}"

    - name: Set {{ ansible_nas_app_name }} FQDN var overrides
      ansible.builtin.set_fact:
        music_assistant_homepage_href: "https://{{ music_assistant_hostname }}.{{ ansible_nas_domain }}"
      when: music_assistant_traefik_enabled | bool or music_assistant_dockflare_enabled | bool

    - name: Create {{ ansible_nas_app_name }} Container
      community.docker.docker_container:
        container_default_behavior: "compatibility"
        name: "{{ music_assistant_container_name }}"
        hostname: "{{ music_assistant_container_name }}"
        image: "{{ music_assistant_image_name }}:{{ music_assistant_image_tag }}"
        pull: true
        privileged: true
        network_mode: host
        capabilities:
          - SYS_ADMIN        # to mount SMB shares in container
          - DAC_READ_SEARCH  # to mount SMB shares in container
        security_opts: ["apparmor=unconfined"]
        volumes:
          - "{{ music_assistant_data_directory }}/data:/data"
          - "{{ music_assistant_audiobooks_directory }}:/media/audiobooks:ro"
          - "{{ music_assistant_music_directory }}:/media/music:ro"
          - "{{ music_assistant_podcasts_directory }}:/media/podcasts:ro"
#        ports:
#          - 8095:8095  # web interface
#          - 8097:8097  # stream to players
        env:
          LOG_LEVEL: "info"
          TZ: "{{ ansible_nas_timezone }}"
        labels:
          autoheal: "{{ music_assistant_autoheal_enabled | ternary('true', 'false') }}"
          com.centurylinklabs.watchtower.enable: "{{ music_assistant_watchtower_enabled | ternary('true', 'false') }}"
          dockflare.enable: "false"
          homepage.name: "{{ ansible_nas_app_name }}"
          homepage.group: "{{ music_assistant_homepage_group }}"
          homepage.icon: "{{ music_assistant_homepage_icon }}"
          homepage.href: "{{ music_assistant_homepage_href }}"
          homepage.description: "{{ 'a free, opensource Media library manager that connects to your streaming services and a wide range of connected speakers' if homepage_show_description else omit }}"
          homepage.server: "my-docker"
          homepage.container: "{{ music_assistant_container_name }}"
          homepage.showStats: "{{ music_assistant_homepage_showstats | ternary('true', 'false') }}"
          homepage.siteMonitor: "http://{{ hostvars[inventory_hostname]['ansible_facts']['default_ipv4']['address'] }}:{{ music_assistant_port_http }}"
          repliqate.enabled: "{{ music_assistant_repliqate_enabled | ternary('true', 'false') }}"
          repliqate.engine: "{{ music_assistant_repliqate_engine }}"
          repliqate.schedule: "{{ music_assistant_repliqate_schedule }}"
          repliqate.backup_id: "{{ music_assistant_repliqate_backup_id }}"
          repliqate.retention: "{{ music_assistant_repliqate_retention }}"
          traefik.enable: "{{ music_assistant_traefik_enabled | ternary('true', 'false') }}"
          traefik.http.routers.music-assistant.rule: "Host(`{{ music_assistant_hostname }}.{{ ansible_nas_domain }}`)"
          traefik.http.routers.music-assistant.entrypoints: "websecure"
          traefik.http.routers.music-assistant.tls.certresolver: "letsencrypt"
          traefik.http.routers.music-assistant.tls.domains[0].main: "{{ ansible_nas_domain }}"
          traefik.http.routers.music-assistant.tls.domains[0].sans: "*.{{ ansible_nas_domain }}"
          traefik.http.routers.music-assistant.middlewares: "music-assistant-whitelist{{ ',tinyauth-auth@docker' if music_assistant_tinyauth_enabled | bool else '' }}"
          traefik.http.middlewares.music-assistant-whitelist.ipallowlist.sourcerange: "{{ music_assistant_traefik_whitelist }}"
          traefik.http.services.music-assistant-svc.loadbalancer.server.url: "http://{{ hostvars[inventory_hostname]['ansible_facts']['default_ipv4']['address'] }}:{{ music_assistant_port_http }}"
          wud.tag.include: '^\d+\.\d+\.\d+$'
          wud.tag.transform.type: "semver"
          wud.link.template: "https://github.com/music-assistant/server/pkgs/container/server"
        cpu_shares: "{{ music_assistant_cpu_shares }}"
        memory: "{{ music_assistant_memory }}"
        memory_swap: "{{ music_assistant_memory_swap }}"
        restart_policy: unless-stopped

    - name: Access {{ ansible_nas_app_name }} at
      ansible.builtin.debug:
        msg: >-
              {{
                ['http://' + hostvars[inventory_hostname]['ansible_facts']['default_ipv4']['address'] + ':' + (music_assistant_port_http | string)] +
                (['https://' + music_assistant_hostname + '.' + ansible_nas_domain] if (music_assistant_traefik_enabled is true or music_assistant_dockflare_enabled is true) else [])
              }}
  when: music_assistant_enabled is true

- name: Stop {{ ansible_nas_app_name }}
  block:
    - name: Stop {{ ansible_nas_app_name }} Container
      community.docker.docker_container:
        name: "{{ music_assistant_container_name }}"
        state: absent
  when: music_assistant_enabled is false

- name: Data Archive {{ ansible_nas_app_name }}
  include_role:
    name: ansible-nas-archive
  vars:
    target_data_dir: "{{ music_assistant_data_directory }}"
  when:
    - archive_app_data_enabled is true
    - music_assistant_enabled is false