---
- name: Start {{ ansible_nas_app_name }}
  block:
    - name: Create {{ ansible_nas_app_name }} Directories
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
      with_items:
        - "{{ komga_data_directory }}"
        - "{{ komga_data_directory }}/config"
        - "{{ komga_books_directory }}"
        - "{{ komga_comics_directory }}"

    - name: Create {{ ansible_nas_app_name }} Container
      community.docker.docker_container:
        container_default_behavior: "compatibility"
        name: "{{ komga_container_name }}"
        hostname: "{{ komga_container_name }}"
        image: "{{ komga_image_name }}:{{ komga_image_version }}"
        pull: true
        volumes:
          - "{{ komga_comics_directory }}:/comics:ro"
          - "{{ komga_books_directory }}:/books:ro"
          - "{{ komga_data_directory }}:/data:rw"
          - "{{ komga_data_directory }}/config:/config:rw"
        network_mode: bridge
        ports:
          - "{{ komga_port_http }}:{{ komga_port_http }}"
        env:
          PUID: "{{ komga_user_id }}"
          PGID: "{{ komga_group_id }}"
          JAVA_TOOL_OPTIONS: "-Xmx4g"
          journal-mode: "wal"
          SERVER_PORT: "{{ komga_port_http }}"
          TZ: "{{ ansible_nas_timezone }}"
        labels:
          autoheal: "{{ komga_autoheal | string }}"
          com.centurylinklabs.watchtower.enable: "{{ komga_watchtower_enabled| string }}"
          dockflare.enable: "{{ komga_dockflare_enabled | string }}"
          dockflare.access.group: "{{ komga_dockflare_access_group }}"
          dockflare.hostname: "{{ komga_hostname }}.{{ ansible_nas_domain }}"
          dockflare.service: "http://{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}:{{ komga_port_http }}"
          homepage.group: "{{ komga_homepage_group }}"
          homepage.name: "{{ ansible_nas_app_name }}"
          homepage.icon: "{{ komga_homepage_icon }}"
          homepage.href: "{{ komga_homepage_href }}"
          homepage.siteMonitor: "http://{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}:{{ komga_port_http }}"
          homepage.description: "{{ 'Media server for comics/mangas/BDs/magazines/eBooks with API, OPDS, Kobo Sync and KOReader Sync support' if homepage_show_description else omit }}"
          homepage.server: "my-docker"
          homepage.container: "{{ komga_container_name }}"
          homepage.showStats: "{{ komga_homepage_showstats | string }}"
          homepage.widget.type: "komga"
          homepage.widget.url: "http://{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}:{{ komga_port_http }}"
          homepage.widget.username: "{{ komga_homepage_widget_username }}"
          homepage.widget.password: "{{ komga_homepage_widget_password }}"
          homepage.widget.key: "{{ komga_homepage_widget_key }}"
          repliqate.enabled: "{{ komga_repliqate_enabled | string }}"
          repliqate.engine: "{{ komga_repliqate_engine }}"
          repliqate.schedule: "{{ komga_repliqate_schedule }}"
          repliqate.backup_id: "{{ komga_repliqate_backup_id }}"
          repliqate.retention: "{{ komga_repliqate_retention }}"
          traefik.enable: "{{ komga_available_externally | string }}"
          traefik.http.routers.komga.rule: "Host(`{{ komga_hostname }}.{{ ansible_nas_domain }}`)"
          traefik.http.routers.komga.tls.certresolver: "letsencrypt"
          traefik.http.routers.komga.tls.domains[0].main: "{{ ansible_nas_domain }}"
          traefik.http.routers.komga.tls.domains[0].sans: "*.{{ ansible_nas_domain }}"
          traefik.http.routers.komga.middlewares: "komga@docker{{ ',tinyauth-auth@docker' if komga_tinyauth_enabled | bool else '' }}"
          traefik.http.middlewares.komga.IPAllowList.sourcerange: "{{ komga_traefik_whitelist }}"
          traefik.http.services.komga.loadbalancer.server.port: "{{ komga_port_http }}"
          wud.tag.include: '^v\\d+\\.\\d+\\.\\d+.*$'
          wud.tag.transform.type: "semver"
          wud.link.template: "https://github.com/gotson/komga/pkgs/container/komga"
        cpu_shares: "{{ komga_cpu_shares }}"
        memory: "{{ komga_memory }}"
        memory_swap: "{{ komga_memory_swap }}"
        restart_policy: unless-stopped

    - name: Access {{ ansible_nas_app_name }} at
      ansible.builtin.debug:
        msg: >-
              {{
                ['http://' + hostvars[inventory_hostname]['ansible_default_ipv4']['address'] + ':' + (komga_port_http | string)] +
                (['https://' + komga_hostname + '.' + ansible_nas_domain] if (komga_available_externally is true or komga_dockflare_enabled is true) else [])
              }}
  when: komga_enabled is true

- name: Stop {{ ansible_nas_app_name }}
  block:
    - name: Stop {{ ansible_nas_app_name }} Container
      community.docker.docker_container:
        name: "{{ komga_container_name }}"
        state: absent
  when: komga_enabled is false

- name: Data Archive {{ ansible_nas_app_name }}
  include_role:
    name: ansible-nas-archive
  vars:
    target_data_dir: "{{ komga_data_directory }}"
  when:
    - archive_app_data_enabled is true
    - komga_enabled is false