---
- name: Start {{ ansible_nas_app_name }}
  block:
    - name: Create {{ ansible_nas_app_name }} Directories
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
      with_items:
        - "{{ trilium_data_directory }}"
        - "{{ trilium_data_directory }}/data"

    - name: Create {{ ansible_nas_app_name }} Container
      community.docker.docker_container:
        container_default_behavior: "compatibility"
        name: "{{ trilium_container_name }}"
        hostname: "{{ trilium_container_name }}"
        image: "{{ trilium_image_name }}:{{ trilium_image_tag }}"
        pull: true
        volumes:
          - "{{ trilium_data_directory }}/data:/home/node/trilium-data"
          - /etc/timezone:/etc/timezone:ro
          - /etc/localtime:/etc/localtime:ro
        ports:
          - "{{ trilium_port_http }}:8080"
        env:
          USER_UID: "{{ trilium_env_user_uid }}"
          USER_GID: "{{ trilium_env_user_gid }}"
          TRILIUM_DATA_DIR: "/home/node/trilium-data"
          TZ: "{{ ansible_nas_timezone }}"
        labels:
          autoheal: "{{ trilium_autoheal | string }}"
          com.centurylinklabs.watchtower.enable: "{{ trilium_watchtower_enabled | string }}"
          dockflare.enable: "{{ trilium_dockflare_enabled | string }}"
          dockflare.access.group: "{{ trilium_dockflare_access_group }}"
          dockflare.hostname: "{{ trilium_hostname }}.{{ ansible_nas_domain }}"
          dockflare.service: "http://{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}:{{ trilium_port_http }}"
          homepage.name: "{{ ansible_nas_app_name }}"
          homepage.group: "{{ trilium_homepage_group }}"
          homepage.icon: "{{ trilium_homepage_icon }}"
          homepage.href: "{{ trilium_homepage_href }}"
          homepage.description: "{{ 'Build your personal knowledge base' if homepage_show_description else omit }}"
          homepage.server: "my-docker"
          homepage.container: "{{ trilium_container_name }}"
          homepage.showStats: "{{ trilium_homepage_showstats | string }}"
          homepage.siteMonitor: "http://{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}:{{ trilium_port_http }}"
          homepage.widget.type: "trilium"
          homepage.widget.url: "http://{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}:{{ trilium_port_http }}"
          homepage.widget.key: "{{ trilium_homepage_widget_key }}"
          repliqate.enabled: "{{ trilium_repliqate_enabled | string }}"
          repliqate.engine: "{{ trilium_repliqate_engine }}"
          repliqate.schedule: "{{ trilium_repliqate_schedule }}"
          repliqate.backup_id: "{{ trilium_repliqate_backup_id }}"
          repliqate.retention: "{{ trilium_repliqate_retention }}"
          traefik.enable: "{{ trilium_available_externally | string }}"
          traefik.http.routers.trilium.rule: "Host(`{{ trilium_hostname }}.{{ ansible_nas_domain }}`)"
          traefik.http.routers.trilium.tls.certresolver: "letsencrypt"
          traefik.http.routers.trilium.tls.domains[0].main: "{{ ansible_nas_domain }}"
          traefik.http.routers.trilium.tls.domains[0].sans: "*.{{ ansible_nas_domain }}"
          traefik.http.routers.trilium.middlewares: "trilium@docker{{ ',tinyauth-auth@docker' if trilium_tinyauth_enabled | bool else '' }}"
          traefik.http.middlewares.trilium.IPAllowList.sourcerange: "{{ trilium_traefik_whitelist }}"
          traefik.http.services.trilium.loadbalancer.server.port: "8080"
          wud.tag.include: '^v\d+\.\d+\.\d+$'
          wud.tag.transform.type: "semver"
          wud.link.template: "https://github.com/TriliumNext/Trilium/pkgs/container/trilium"
        cpu_shares: "{{ trilium_cpu_shares }}"
        memory: "{{ trilium_memory }}"
        restart_policy: unless-stopped

    - name: Access {{ ansible_nas_app_name }} at
      ansible.builtin.debug:
        msg: >-
              {{
                ['http://' + hostvars[inventory_hostname]['ansible_default_ipv4']['address'] + ':' + (trilium_port_http | string)] +
                (['https://' + trilium_hostname + '.' + ansible_nas_domain] if (trilium_available_externally is true or trilium_dockflare_enabled is true) else [])
              }}
  when: trilium_enabled is true

- name: Stop {{ ansible_nas_app_name }}
  block:
    - name: Stop {{ ansible_nas_app_name }} Container
      community.docker.docker_container:
        name: "{{ trilium_container_name }}"
        state: absent
  when: trilium_enabled is false

- name: Data Archive {{ ansible_nas_app_name }}
  include_role:
    name: ansible-nas-archive
  vars:
    target_data_dir: "{{ trilium_data_directory }}"
  when:
    - archive_app_data_enabled is true
    - trilium_enabled is false