---
# ANE
ansible_nas_app_name: "SearXNG"
searxng_enabled: false
searxng_available_externally: false
searxng_traefik_whitelist: "{{ lan }}"
searxng_data_directory: "{{ docker_home }}/searxng"

# network
searxng_hostname: "searxng"
searxng_port_http: "3008"

# docker
searxng_container_name: "searxng"
searxng_image_name: "searxng/searxng"
searxng_image_tag: "latest"
searxng_cpu_shares: "1024"
searxng_memory_limit: "1G"

# autoheal
searxng_autoheal: "false"

# dockflare
searxng_dockflare_tunnel: "false"
searxng_dockflare_access_group: ""

# homepage
searxng_homepage_group: "Apps"
searxng_homepage_icon: "searxng.png"
searxng_homepage_href: "http://{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}:{{ searxng_port_http }}"
searxng_homepage_showStats: "false"

# watchtower
searxng_watchtower_monitor_only: "true"