---
# ANE
ansible_nas_app_name: "Homebridge"
homebridge_enabled: false
homebridge_available_externally: false
homebridge_traefik_whitelist: "{{ lan }}"

# directories
homebridge_data_directory: "{{ docker_home }}/homebridge"

# uid / gid
homebridge_user_id: "0"
homebridge_group_id: "0"

# network
homebridge_hostname: "homebridge"
homebridge_port: "8087"

# docker
homebridge_container_name: "homebridge"
homebridge_image_name: "oznu/homebridge"
homebridge_image_version: "latest"
homebridge_cpu_shares: 1024

# specs
homebridge_memory: "1g"

# autoheal
homebridge_autoheal: "false"

# dockflare
homebridge_dockflare_tunnel: "false"
homebridge_dockflare_access_group: ""

# homepage
homebridge_homepage_group: "Apps"
homebridge_homepage_icon: "homebridge.png"
homebridge_homepage_href: "http://{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}:{{ homebridge_port }}"
homebridge_homepage_showStats: "false"

# watchtower
homebridge_watchtower_monitor_only: "true"