---
- name: Start {{ ansible_nas_app_name }}
  block:
    - name: Create {{ ansible_nas_app_name }} Directories
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        owner: 1000
        group: ansible-nas
      with_items:
        - "{{ code_server_data_directory }}"
        - "{{ code_server_data_directory }}/project"
        - "{{ code_server_data_directory }}/.config"
        - "{{ code_server_data_directory }}/.config/code-server"
        - "{{ code_server_data_directory }}/.local"
        - "{{ code_server_data_directory }}/.local/share"
        - "{{ code_server_data_directory }}/.local/share/code-server"
        - "{{ code_server_data_directory }}/.local/share/code-server/extensions"

    - name: Set {{ ansible_nas_app_name }} FQDN var overrides
      ansible.builtin.set_fact:
        code_server_homepage_href: "https://{{ code_server_hostname }}.{{ ansible_nas_domain }}"
      when: code_server_traefik_enabled | bool or code_server_dockflare_enabled | bool

    - name: Create {{ ansible_nas_app_name }} Container
      community.docker.docker_container:
        container_default_behavior: "compatibility"
        name: "{{ code_server_container_name }}"
        hostname: "{{ code_server_container_name }}"
        image: "{{ code_server_image_name }}:{{ code_server_image_tag }}"
        pull: true
        ports:
          - "{{ code_server_port_http }}:8080"
        volumes:
#         - "{{ code_server_data_directory }}/project:/home/coder/project"
          - "{{ code_server_data_directory }}/.config:/home/coder/.config"
          - "{{ code_server_data_directory }}/.local:/home/coder/.local"
          - "/home/{{ ansible_nas_user }}:/home/coder/{{ ansible_nas_user }}" # added
          - "{{ docker_home }}:/home/coder/dockerdata" # added
          - "/etc/timezone:/etc/timezone:ro"
        network_mode: bridge
        env:
          DOCKER_USER: "{{ ansible_nas_user }}"
          PASSWORD: "{{ code_server_password }}"
          TZ: "{{ ansible_nas_timezone }}"
        labels:
          autoheal: "{{ code_server_autoheal_enabled | ternary('true', 'false') }}"
          com.centurylinklabs.watchtower.enable: "{{ code_server_watchtower_enabled | ternary('true', 'false') }}"
          dockflare.enable: "{{ code_server_dockflare_enabled | ternary('true', 'false') }}"
          dockflare.access.group: "{{ code_server_dockflare_access_group }}"
          dockflare.hostname: "{{ code_server_hostname }}.{{ ansible_nas_domain }}"
          dockflare.service: "http://{{ hostvars[inventory_hostname]['ansible_facts']['default_ipv4']['address'] }}:{{ code_server_port_http }}"
          homepage.group: "{{ code_server_homepage_group }}"
          homepage.name: "{{ ansible_nas_app_name }}"
          homepage.icon: "{{ code_server_homepgae_icon }}"
          homepage.href: "{{ code_server_homepage_href }}"
          homepage.siteMonitor: "http://{{ hostvars[inventory_hostname]['ansible_facts']['default_ipv4']['address'] }}:{{ code_server_port_http }}"
          homepage.description: "{{ 'VS Code in the browser' if homepage_show_description else omit }}"
          homepage.server: "my-docker"
          homepage.container: "code-server"
          homepage.showStats: "{{ code_server_homepage_showstats | ternary('true', 'false') }}"
          repliqate.enabled: "{{ code_server_repliqate_enabled | ternary('true', 'false') }}"
          repliqate.engine: "{{ code_server_repliqate_engine }}"
          repliqate.schedule: "{{ code_server_repliqate_schedule }}"
          repliqate.backup_id: "{{ code_server_repliqate_backup_id }}"
          repliqate.retention: "{{ code_server_repliqate_retention }}"
          traefik.enable: "{{ code_server_traefik_enabled | ternary('true', 'false') }}"
          traefik.http.routers.codeserver.rule: "Host(`{{ code_server_hostname }}.{{ ansible_nas_domain }}`)"
          traefik.http.routers.codeserver.tls.certresolver: "letsencrypt"
          traefik.http.routers.codeserver.tls.domains[0].main: "{{ ansible_nas_domain }}"
          traefik.http.routers.codeserver.tls.domains[0].sans: "*.{{ ansible_nas_domain }}"
          traefik.http.routers.codeserver.middlewares: "codeserver@docker{{ ',tinyauth-auth@docker' if code_server_tinyauth_enabled | bool else '' }}"
          traefik.http.middlewares.codeserver.IPAllowList.sourcerange: "{{ code_server_traefik_whitelist }}"
          traefik.http.services.codeserver.loadbalancer.server.port: "8080"
          wud.tag.include: '^\d+\.\d+\.\d+.*$'
          wud.tag.transform.type: "semver"
          wud.link.template: "https://hub.docker.com/r/codercom/code-server"
        cpu_shares: "{{ code_server_cpu_shares }}"
        memory: "{{ code_server_memory }}"
        memory_swap: "{{ code_server_memory_swap }}"
        restart_policy: unless-stopped

    - name: Access {{ ansible_nas_app_name }} at
      ansible.builtin.debug:
        msg: >-
              {{
                ['http://' + hostvars[inventory_hostname]['ansible_facts']['default_ipv4']['address'] + ':' + (code_server_port_http | string)] +
                (['https://' + code_server_hostname + '.' + ansible_nas_domain] if (code_server_traefik_enabled is true or code_server_dockflare_enabled is true) else [])
              }}
  when: code_server_enabled is true

- name: Stop {{ ansible_nas_app_name }}
  block:
    - name: Stop {{ ansible_nas_app_name }} Container
      community.docker.docker_container:
        name: "{{ code_server_container_name }}"
        state: absent
  when: code_server_enabled is false

- name: Data Archive {{ ansible_nas_app_name }}
  include_role:
    name: ansible-nas-archive
  vars:
    target_data_dir: "{{ code_server_data_directory }}"
  when:
    - archive_app_data_enabled is true
    - code_server_enabled is false