---
# ANE
opencloud_proper_name: "OpenCloud"
opencloud_enabled: false
opencloud_traefik_enabled: false
opencloud_traefik_whitelist: "{{ lan }}"

# directories
opencloud_data_directory: "{{ docker_home }}/opencloud"

# docker
opencloud_container_name: "opencloud"
opencloud_image_name: "opencloudeu/opencloud-rolling"
opencloud_image_tag: "latest"

# network
opencloud_port_http: "9201"
opencloud_hostname: "opencloud"
# TDL: add?
# https://github.com/opencloud-eu/opencloud-compose
# Metrics endpoints for OpenCloud proxy service (port 9205)
# Metrics endpoints for collaboration service (port 9304)

# specs
opencloud_cpu_shares: 1024
opencloud_memory: "1G"
opencloud_memory_swap: -1

# app
# https://github.com/opencloud-eu/opencloud-compose/blob/main/.env.example
opencloud_env_idm_admin_password: "{{ ansible_nas_app_admin_password }}" # NOTE: This variable needs to be set before the first start of OpenCloud. Changes to this variable after the first start will be IGNORED.
opencloud_env_oc_url: "https://{{ opencloud_hostname }}.{{ ansible_nas_domain }}"
opencloud_env_smtp_host: ""
opencloud_env_smtp_port: ""
opencloud_env_smtp_sender: ""
opencloud_env_smtp_username: ""
opencloud_env_smtp_password: ""
opencloud_env_smtp_insecure: ""
opencloud_env_smtp_authentication: ""
opencloud_env_smtp_encryption: ""

# autoheal
opencloud_autoheal_enabled: false

# dockflare
opencloud_dockflare_enabled: false
opencloud_dockflare_access_group: ""

# homepage
opencloud_homepage_group: "Apps"
opencloud_homepage_icon: "sh-opencloud.png"
opencloud_homepage_href: "https://{{ opencloud_hostname }}.{{ ansible_nas_domain }}"
opencloud_homepage_showstats: false

# repliqate
opencloud_repliqate_enabled: false
opencloud_repliqate_engine: "restic"
opencloud_repliqate_schedule: "@daily 3am"
opencloud_repliqate_backup_id: "{{ opencloud_container_name }}"
opencloud_repliqate_retention: "30d"

# tinyauth
opencloud_tinyauth_enabled: false

# watchtower
opencloud_watchtower_enabled: false
