# https://hub.docker.com/r/linuxserver/htpcmanager/
---
- name: Start {{ ansible_nas_app_name }}
  block:
    - name: Create {{ ansible_nas_app_name }} Directories
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
      with_items:
        - "{{ htpcmanager_data_directory }}"
        - "{{ htpcmanager_data_directory }}/config"

    - name: Create {{ ansible_nas_app_name }} Container
      community.docker.docker_container:
        container_default_behavior: "compatibility"
        name: "{{ htpcmanager_container_name }}"
        hostname: "{{ htpcmanager_container_name }}"
        image: "{{ htpcmanager_image_name }}:{{ htpcmanager_image_tag }}"
        pull: true
        network_mode: bridge
        ports:
          - "{{ htpcmanager_port_http }}:8085"
        volumes:
          - "{{ htpcmanager_data_directory }}/config:/config"
        env:
          DOCKER_MODS: "{{ htpcmanager_env_docker_mods }}"
          INSTALL_PACKAGES: "{{ htpcmanager_env_docker_mods_install_packages }}"
          INSTALL_PIP_PACKAGES: "{{ htpcmanager_env_docker_mods_install_pip_packages}}"
          PUID: "{{ htpcmanager_puid }}"
          PGID: "{{ htpcmanager_pgid }}"
          TZ: "{{ ansible_nas_timezone }}"
        labels:
          autoheal: "{{ htpcmanager_autoheal }}"
          com.centurylinklabs.watchtower.enable: "{{ htpcmanager_watchtower_enable }}"
          dockflare.enable: "{{ htpcmanager_dockflare_tunnel }}"
          dockflare.access.group: "{{ htpcmanager_dockflare_access_group }}"
          dockflare.hostname: "{{ htpcmanager_hostname }}.{{ ansible_nas_domain }}"
          dockflare.service: "http://{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}:{{ htpcmanager_port_http }}"
          homepage.group: "{{ htpcmanager_homepage_group }}"
          homepage.name: "{{ ansible_nas_app_name }}"
          homepage.href: "{{ htpcmanager_homepage_href }}"
          homepage.icon: "{{ htpcmanager_homepage_icon }}"
          homepage.description: "{{ 'A fully responsive interface to manage all your favorite software on your HTPC.' if homepage_show_description else omit }}"
          homepage.server: "my-docker"
          homepage.container: "{{ htpcmanager_container_name }}"
          homepage.showStats: "{{ htpcmanager_homepage_showstats }}"
          homepage.siteMonitor: "http://{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}:{{ htpcmanager_port_http }}"
          repliqate.enabled: "{{ htpcmanager_repliqate_enabled }}"
          repliqate.engine: "{{ htpcmanager_repliqate_engine }}"
          repliqate.schedule: "{{ htpcmanager_repliqate_schedule }}"
          repliqate.backup_id: "{{ htpcmanager_repliqate_backup_id }}"
          repliqate.retention: "{{ htpcmanager_repliqate_retention }}"
          traefik.enable: "{{ htpcmanager_available_externally | string }}"
          traefik.http.routers.htpcmanager.rule: "Host(`{{ htpcmanager_hostname }}.{{ ansible_nas_domain }}`)"
          traefik.http.routers.htpcmanager.tls.certresolver: "letsencrypt"
          traefik.http.routers.htpcmanager.tls.domains[0].main: "{{ ansible_nas_domain }}"
          traefik.http.routers.htpcmanager.tls.domains[0].sans: "*.{{ ansible_nas_domain }}"
          traefik.http.routers.htpcmanager.middlewares: "htpcmanager@docker{{ ',tinyauth-auth@docker' if htpcmanager_tinyauth_enabled | bool else '' }}"
          traefik.http.middlewares.htpcmanager.IPAllowList.sourcerange: "{{ htpcmanager_traefik_whitelist }}"
          traefik.http.services.htpcmanager.loadbalancer.server.port: "8085"
          wud.watch.digest: "true"
          wud.link.template: "https://lscr.io/linuxserver/htpcmanager"
        cpu_shares: "{{ htpcmanager_cpu_shares }}"
        memory: "{{ htpcmanager_memory }}"
        memory_swap: "{{ htpcmanager_memory_swap }}"
        restart_policy: unless-stopped

    - name: Access {{ ansible_nas_app_name }} at
      ansible.builtin.debug:
        msg: >-
              {{
                ['http://' + hostvars[inventory_hostname]['ansible_default_ipv4']['address'] + ':' + (htpcmanager_port_http | string)] +
                (['https://' + htpcmanager_hostname + '.' + ansible_nas_domain] if (htpcmanager_available_externally is true or htpcmanager_dockflare_tunnel is true) else [])
              }}
  when: htpcmanager_enabled is true

- name: Stop {{ ansible_nas_app_name }}
  block:
    - name: Stop {{ ansible_nas_app_name }} Container
      community.docker.docker_container:
        name: "{{ htpcmanager_container_name }}"
        state: absent
  when: htpcmanager_enabled is false

- name: Data Archive {{ ansible_nas_app_name }}
  include_role:
    name: ansible-nas-archive
  vars:
    target_data_dir: "{{ htpcmanager_data_directory }}"
  when:
    - archive_app_data_enabled is true
    - htpcmanager_enabled is false