---
ansible_nas_app_name: "Tdarr Server"

#
tdarr_enabled: false
tdarr_available_externally: false
tdarr_traefik_whitelist: "{{ lan }}"

# directories
tdarr_data_directory: "{{ docker_home }}/tdarr"
tdarr_cache_directory: "{{ samba_shares_root }}/dump/tdarr_temp"
tdarr_media_directory: "{{ samba_shares_root }}"

# uid / gid
tdarr_user_id: "0"
tdarr_group_id: "0"

# network
tdarr_hostname: "tdarr"
tdarr_port_http: "8265"
tdarr_port_server: "8266"

# docker
tdarr_container_name: "tdarr"
tdarr_image_name: "ghcr.io/haveagitgat/tdarr"
tdarr_image_tag: "latest"
tdarr_cpu_shares: "1024"
tdarr_memory: "4g"

# autoheal
tdarr_autoheal: "false"

# homepage
tdarr_homepage_group: "Apps"
tdarr_homepage_icon: "tdarr.png"
tdarr_homepage_href: "http://{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}:{{ tdarr_port_http }}"
tdarr_homepage_showStats: "false"
tdarr_homepage_key: "insert Tdarr API key here"

# watchtower
tdarr_watchtower_monitor_only: "true"