---
- name: Start {{ ansible_nas_app_name }}
  block:
    - name: Create {{ ansible_nas_app_name }} Directories
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        owner: 65534
        group: 65534
      with_items:
        - "{{ wallabag_data_directory }}/data"
        - "{{ wallabag_data_directory }}/data/db"
        - "{{ wallabag_data_directory }}/images"

    - name: Create {{ ansible_nas_app_name }} Container
      community.docker.docker_container:
        container_default_behavior: "compatibility"
        name: "{{ wallabag_container_name }}"
        hostname: "{{ wallabag_container_name }}"
        image: "{{ wallabag_image_name }}:{{ wallabag_image_version }}"
        pull: true
        volumes:
          - "{{ wallabag_data_directory }}/data:/var/www/wallabag/data:rw"
          - "{{ wallabag_data_directory }}/images:/var/www/wallabag/web/assets/images:rw"
        ports:
          - "{{ wallabag_port_http }}:80"
        env:
          SYMFONY__ENV__DOMAIN_NAME: "{{ wallabag_env_symfony_env_domain_name }}"
          TZ: "{{ ansible_nas_timezone }}"
        labels:
          autoheal: "{{ wallabag_autoheal }}"
          com.centurylinklabs.watchtower.enable: "{{ wallabag_watchtower_enable }}"
          dockflare.enable: "{{ wallabag_dockflare_tunnel }}"
          dockflare.access.group: "{{ wallabag_dockflare_access_group }}"
          dockflare.hostname: "{{ wallabag_hostname }}.{{ ansible_nas_domain }}"
          dockflare.service: "http://{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}:{{ wallabag_port_http }}"
          homepage.name: "{{ ansible_nas_app_name }}"
          homepage.group: "{{ wallabag_homepage_group }}"
          homepage.icon: "{{ wallabag_homepage_icon }}"
          homepage.href: "{{ wallabag_homepage_href }}"
          homepage.siteMonitor: "http://{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}:{{ wallabag_port_http }}"
          homepage.description: "{{ 'wallabag is a self hostable application for saving web pages: Save and classify articles. Read them later. Freely.' if homepage_show_description else omit }}"
          homepage.server: "my-docker"
          homepage.container: "{{ wallabag_container_name }}"
          homepage.showStats: "{{ wallabag_homepage_showstats }}"
          repliqate.enabled: "{{ wallabag_repliqate_enabled }}"
          repliqate.engine: "{{ wallabag_repliqate_engine }}"
          repliqate.schedule: "{{ wallabag_repliqate_schedule }}"
          repliqate.backup_id: "{{ wallabag_repliqate_backup_id }}"
          repliqate.retention: "{{ wallabag_repliqate_retention }}"
          traefik.enable: "{{ wallabag_available_externally | string }}"
          traefik.http.routers.wallabag.rule: "Host(`{{ wallabag_hostname }}.{{ ansible_nas_domain }}`)"
          traefik.http.routers.wallabag.tls.certresolver: "letsencrypt"
          traefik.http.routers.wallabag.tls.domains[0].main: "{{ ansible_nas_domain }}"
          traefik.http.routers.wallabag.tls.domains[0].sans: "*.{{ ansible_nas_domain }}"
          traefik.http.routers.wallabag.middlewares: "wallabag@docker{{ ',tinyauth-auth@docker' if wallabag_tinyauth_enabled | bool else '' }}"
          traefik.http.middlewares.wallabag.IPAllowList.sourcerange: "{{ wallabag_traefik_whitelist }}"
          traefik.http.services.wallabag.loadbalancer.server.port: "80"
          wud.tag.include: '^\d+\.\d+\.\d+$'
          wud.tag.transform.type: "semver"
          wud.link.template: "https://hub.docker.com/r/wallabag/wallabag"
        cpu_shares: "{{ wallabag_cpu_shares }}"
        memory: "{{ wallabag_memory }}"
        restart_policy: unless-stopped

    - name: Access {{ ansible_nas_app_name }} at
      ansible.builtin.debug:
        msg: >-
              {{
                ['http://' + hostvars[inventory_hostname]['ansible_default_ipv4']['address'] + ':' + (wallabag_port_http | string)] +
                (['https://' + wallabag_hostname + '.' + ansible_nas_domain] if (wallabag_available_externally is true or wallabag_dockflare_tunnel is true) else [])
              }}
  when: wallabag_enabled is true

- name: Stop {{ ansible_nas_app_name }}
  block:
    - name: Stop {{ ansible_nas_app_name }} Container
      community.docker.docker_container:
        name: "{{ wallabag_container_name }}"
        state: absent
  when: wallabag_enabled is false

- name: Data Archive {{ ansible_nas_app_name }}
  include_role:
    name: ansible-nas-archive
  vars:
    target_data_dir: "{{ wallabag_data_directory }}"
  when:
    - archive_app_data_enabled is true
    - wallabag_enabled is false