---
- name: Start {{ ansible_nas_app_name }}
  block:
    - name: Create {{ ansible_nas_app_name }} Directories
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        owner: 65534
        group: 65534
      with_items:
        - "{{ wallabag_data_directory }}/data"
        - "{{ wallabag_data_directory }}/data/db"
        - "{{ wallabag_data_directory }}/images"

    - name: Create {{ ansible_nas_app_name }} Container
      community.docker.docker_container:
        name: "{{ wallabag_container_name }}"
        hostname: "{{ wallabag_container_name }}"
        image: "{{ wallabag_image_name }}:{{ wallabag_image_version }}"
        pull: true
        volumes:
          - "{{ wallabag_data_directory }}/data:/var/www/wallabag/data:rw"
          - "{{ wallabag_data_directory }}/images:/var/www/wallabag/web/assets/images:rw"
        ports:
          - "{{ wallabag_port }}:80"
        env:
          SYMFONY__ENV__DOMAIN_NAME: "https://{{ wallabag_hostname }}.{{ ansible_nas_domain }}"
          TZ: "{{ ansible_nas_timezone }}"
        restart_policy: unless-stopped
        cpu_shares: "{{ wallabag_cpu_shares }}"
        memory: "{{ wallabag_memory }}"
        labels:
          autoheal: "{{ wallabag_autoheal }}"
          com.centurylinklabs.watchtower.monitor-only: "{{ wallabag_watchtower_monitor_only }}"
          homepage.name: "wallabag"
          homepage.group: "{{ wallabag_homepage_group }}"
          homepage.icon: "{{ wallabag_homepage_icon }}"
          homepage.href: "{{ wallabag_homepage_href }}"
          homepage.siteMonitor: "http://{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}:{{ wallabag_port }}"
#         homepage.description: "wallabag is a self hostable application for saving web pages: Save and classify articles. Read them later. Freely."
          homepage.server: "my-docker"
          homepage.container: "{{ wallabag_container_name }}"
          homepage.showStats: "{{ wallabag_homepage_showStats }}"
          traefik.enable: "{{ wallabag_available_externally | string }}"
          traefik.http.routers.wallabag.rule: "Host(`wallabag.{{ ansible_nas_domain }}`)"
          traefik.http.routers.wallabag.tls.certresolver: "letsencrypt"
          traefik.http.routers.wallabag.tls.domains[0].main: "{{ ansible_nas_domain }}"
          traefik.http.routers.wallabag.tls.domains[0].sans: "*.{{ ansible_nas_domain }}"
          traefik.http.routers.frontend.middlewares: "{{ wallabag_hostname }}"
          traefik.http.routers.wallabag.middlewares: "{{ wallabag_hostname }}@docker"
          traefik.http.middlewares.wallabag.IPAllowList.sourcerange: "{{ wallabag_traefik_whitelist }}"
          traefik.http.services.wallabag.loadbalancer.server.port: "80"
          wud.tag.include: '^\d+\.\d+\.\d+$$'
          wud.link.template: "https://github.com/wallabag/wallabag/releases/tag/$${major}.$${minor}.$${patch}"
  when: wallabag_enabled is true

- name: Stop {{ ansible_nas_app_name }}
  block:
    - name: Stop {{ ansible_nas_app_name }} Container
      community.docker.docker_container:
        name: "{{ wallabag_container_name }}"
        state: absent
  when: wallabag_enabled is false
