---
# ANE
ansible_nas_app_name: "Pi.Alert"
pialert_enabled: false
pialert_available_externally: false
pialert_traefik_whitelist: "{{ lan }}"
pialert_data_directory: "{{ docker_home }}/pialert"

# network
pialert_hostname: "pialert"
pialert_port_http: "20211"

# docker
pialert_container_name: "pialert"
pialert_image_name: "jokobsk/pi.alert"
pialert_image_tag: "latest"
pialert_cpu_shares: "1024"
pialert_memory: "1g"

# autoheal
pialert_autoheal: "false"

# dockflare
pialert_dockflare_tunnel: "false"
pialert_dockflare_access_group: ""

# homepage
pialert_homepage_group: "Apps"
pialert_homepage_icon: "pialert.png"
pialert_homepage_href: "http://{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}:{{ pialert_port_http }}"
pialert_homepage_showstats: "false"

# watchtower
pialert_watchtower_enable: "false"