---
- name: Start {{ ansible_nas_app_name }}
  block:
    - name: Create {{ ansible_nas_app_name }} Directories
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
#        owner: "{{ youtubedlmaterial_uid }}"
#        group: "{{ youtubedlmaterial_gid }}"
        # mode: 0755
      with_items:
        - "{{ youtubedlmaterial_data_directory }}/appdata"
        - "{{ youtubedlmaterial_data_directory }}/db"
        - "{{ youtubedlmaterial_dl_audio_directory }}"
        - "{{ youtubedlmaterial_dl_video_directory }}"
        - "{{ youtubedlmaterial_dl_subscriptions_directory }}"
        - "{{ youtubedlmaterial_dl_channels_directory }}"
        - "{{ youtubedlmaterial_dl_users_directory }}"

    - name: Create {{ ansible_nas_app_name }} DB Container
      community.docker.docker_container:
        container_default_behavior: "compatibility"
        name: "{{ youtubedlmaterial_db_container_name }}"
        hostname: "{{ youtubedlmaterial_db_container_name }}"
        image: "{{ youtubedlmaterial_db_image_name }}:{{ youtubedlmaterial_db_image_version }}"
        pull: true
        volumes:
          - "{{ youtubedlmaterial_data_directory }}/db:/data/db"
        network_mode: bridge
        env:
          TZ: "{{ ansible_nas_timezone }}"
        restart_policy: unless-stopped
        cpu_shares: "{{ youtubedlmaterial_db_cpu_shares }}"
        memory: "{{ youtubedlmaterial_db_memory_limit }}"
        labels:
          autoheal: "{{ youtubedlmaterial_db_autoheal }}"
          com.centurylinklabs.watchtower.monitor-only: "{{ youtubedlmaterial_db_watchtower_monitor_only }}"
          homepage.name: "YoutubeDL-Material MongoDB"
          homepage.group: "{{ youtubedlmaterial_db_homepage_group }}"
          homepage.icon: "{{ youtubedlmaterial_db_homepage_icon }}"
          homepage.href: "{{ youtubedlmaterial_homepage_href }}"
#         homepage.description: "The MongoDB Database"
          homepage.server: "my-docker"
          homepage.container: "{{ youtubedlmaterial_db_container_name }}"
          homepage.showStats: "{{ youtubedlmaterial_db_homepage_showStats }}"
          traefik.enable: "false"
          wud.tag.include: '^\d+\.\d+\.\d+$$'
          wud.link.template: "https://github.com/mongodb/mongo/tags/tags/$${major}.$${minor}.$${patch}"

    - name: Create {{ ansible_nas_app_name }} Container
      community.docker.docker_container:
        name: "{{ youtubedlmaterial_container_name }}"
        hostname: "{{ youtubedlmaterial_container_name }}"
        image: "{{ youtubedlmaterial_image_name }}:{{ youtubedlmaterial_image_version }}"
        pull: true
        volumes:
          - "{{ youtubedlmaterial_data_directory }}/appdata:/app/appdata:rw"
          - "{{ youtubedlmaterial_dl_audio_directory }}:/app/audio:rw"
          - "{{ youtubedlmaterial_dl_video_directory }}:/app/video:rw"
          - "{{ youtubedlmaterial_dl_subscriptions_directory }}:/app/subscriptions:rw"
          - "{{ youtubedlmaterial_dl_channels_directory }}:/app/subscriptions/channels:rw"
          - "{{ youtubedlmaterial_dl_users_directory }}:/app/users:rw"
############ special for me
#          - "{{ podcasts_root }}:/app/users/admin/subscriptions/channels:rw"
############ special for me
        network_mode: "bridge"
        ports:
          - "{{ youtubedlmaterial_port_http }}:17442"
        env:
          USER: "root"
          ALLOW_CONFIG_MUTATIONS: "true"
          ytdl_mongodb_connection_string: "mongodb://{{ youtubedlmaterial_db_container_name }}:27017"
          ytdl_use_local_db: "false"
          write_ytdl_config: "true"
#         UID: "{{ youtubedlmaterial_uid }}"
#         GID: "{{ youtubedlmaterial_gid }}"
          TZ: "{{ ansible_nas_timezone }}"
        restart_policy: unless-stopped
        cpu_shares: "{{ youtubedlmaterial_cpu_shares }}"
        memory: "{{ youtubedlmaterial_memory }}"
        links:
          - "{{ youtubedlmaterial_db_container_name }}"
        labels:
          autoheal: "{{ youtubedlmaterial_autoheal }}"
          com.centurylinklabs.watchtower.monitor-only: "{{ youtubedlmaterial_watchtower_monitor_only }}"
          homepage.name: "YoutubeDL-Material"
          homepage.group: "{{ youtubedlmaterial_homepage_group }}"
          homepage.icon: "{{ youtubedlmaterial_homepage_icon }}"
          homepage.href: "{{ youtubedlmaterial_homepage_href }}"
#         homepage.description: "Self-hosted YouTube downloader built on Material Design"
          homepage.siteMonitor: "http://{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}:{{ wud_port_http }}"
          homepage.server: "my-docker"
          homepage.container: "{{ youtubedlmaterial_container_name }}"
          homepage.showStats: "{{ youtubedlmaterial_homepage_showStats }}"
          traefik.enable: "{{ youtubedlmaterial_available_externally | string }}"
          traefik.http.routers.youtubedlmaterial.rule: "Host(`{{ youtubedlmaterial_hostname }}.{{ ansible_nas_domain }}`)"
          traefik.http.routers.youtubedlmaterial.tls.certresolver: "letsencrypt"
          traefik.http.routers.youtubedlmaterial.tls.domains[0].main: "{{ ansible_nas_domain }}"
          traefik.http.routers.youtubedlmaterial.tls.domains[0].sans: "*.{{ ansible_nas_domain }}"
          traefik.http.services.youtubedlmaterial.loadbalancer.server.port: "17442"
          traefik.http.routers.frontend.middlewares: "{{ youtubedlmaterial_hostname }}"
          traefik.http.routers.youtubedlmaterial.middlewares: "{{ youtubedlmaterial_hostname }}@docker"
          traefik.http.middlewares.youtubedlmaterial.IPAllowList.sourcerange: "{{ youtubedlmaterial_traefik_whitelist }}"
          wud.tag.include: '^\d+\.\d+\.\d+$$'
          wud.link.template: "https://github.com/Tzahi12345/YoutubeDL-Material/releases/tags/$${major}.$${minor}.$${patch}"
  when: youtubedlmaterial_enabled is true

- name: Stop {{ ansible_nas_app_name }}
  block:
    - name: Stop {{ ansible_nas_app_name }} Container
      community.docker.docker_container:
        name: "{{ youtubedlmaterial_container_name }}"
        state: absent

    - name: Stop {{ ansible_nas_app_name }} DB Container
      community.docker.docker_container:
        name: "{{ youtubedlmaterial_db_container_name }}"
        state: absent
  when: youtubedlmaterial_enabled is false

- name: Data Archive {{ ansible_nas_app_name }}
  block:
    - name: Check for {{ ansible_nas_app_name }} Data Directory
      stat:
        path: "{{ youtubedlmaterial_data_directory }}"
      register: dir_stat

    - name: Archive {{ ansible_nas_app_name }} Data Directory
      ansible.builtin.archive:
        path: "{{ youtubedlmaterial_data_directory }}"
        dest: "{{ docker_home }}/{{ ansible_nas_app_name | lower }}.zip"
        force_archive: true
        format: zip
        owner: ansible-nas
        group: ansible-nas
        mode: u=rw,g=rw
        remove: true
      when: dir_stat.stat.exists
  when: youtubedlmaterial_enabled is false and archive_app_data_enabled is true
