---
- name: Start {{ ansible_nas_app_name }}
  block:
    - name: Create {{ ansible_nas_app_name }} Directories
      file:
        path: "{{ item }}"
        state: directory
      with_items:
        - "{{ dockge_data_directory }}"
        - "{{ dockge_data_directory }}/data"

    - name: Create {{ ansible_nas_app_name }} Container
      community.docker.docker_container:
        container_default_behavior: "compatibility"
        name: "{{ dockge_container_name }}"
        hostname: "{{ dockge_container_name }}"
        image: "{{ dockge_image_name }}:{{ dockge_image_tag }}"
        pull: true
        volumes:
          - "{{ dockge_data_directory }}/data:/app/data"
          - "{{ docker_compose_data_directory }}:/opt/stacks"
          - "/var/run/docker.sock:/var/run/docker.sock"
        # If you want to use private registries, you need to share the auth file with Dockge:
        # - /root/.docker/:/root/.docker
        ports:
          - "{{ dockge_port }}:5001"
        env:
          DOCKGE_STACKS_DIR: "/opt/stacks"
          TZ: "{{ ansible_nas_timezone }}"
        labels:
          autoheal: "{{ dockge_autoheal }}"
          com.centurylinklabs.watchtower.enable: "{{ dockge_watchtower_enable }}"
          dockflare.enable: "{{ dockge_dockflare_tunnel }}"
          dockflare.access.group: "{{ dockge_dockflare_access_group }}"
          dockflare.hostname: "{{ dockge_hostname }}.{{ ansible_nas_domain }}"
          dockflare.service: "http://{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}:{{ dockge_port }}"
          homepage.name: "{{ ansible_nas_app_name }}"
          homepage.group: "{{ dockge_homepage_group }}"
          homepage.icon: "{{ dockge_homepage_icon }}"
          homepage.href: "{{ dockge_homepage_href }}"
          homepage.description: "{{ 'A fancy, easy-to-use and reactive self-hosted docker compose.yaml stack-oriented manager' if homepage_show_description else omit }}"
          homepage.server: "my-docker"
          homepage.container: "{{ dockge_container_name }}"
          homepage.showStats: "{{ dockge_homepage_showstats }}"
          homepage.siteMonitor: "http://{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}:{{ dockge_port }}"
          repliqate.enabled: "{{ dockge_repliqate_enabled }}"
          repliqate.engine: "{{ dockge_repliqate_engine }}"
          repliqate.schedule: "{{ dockge_repliqate_schedule }}"
          repliqate.backup_id: "{{ dockge_repliqate_backup_id }}"
          repliqate.retention: "{{ dockge_repliqate_retention }}"
          traefik.enable: "{{ dockge_available_externally | string }}"
          traefik.http.routers.dockge.rule: "Host(`{{ dockge_hostname }}.{{ ansible_nas_domain }}`)"
          traefik.http.routers.dockge.tls.certresolver: "letsencrypt"
          traefik.http.routers.dockge.tls.domains[0].main: "{{ ansible_nas_domain }}"
          traefik.http.routers.dockge.tls.domains[0].sans: "*.{{ ansible_nas_domain }}"
          traefik.http.routers.frontend.middlewares: "{{ dockge_hostname }}"
          traefik.http.routers.dockge.middlewares: "{{ dockge_hostname }}@docker"
          traefik.http.middlewares.dockge.IPAllowList.sourcerange: "{{ dockge_traefik_whitelist }}"
          traefik.http.services.dockge.loadbalancer.server.port: "5001"
          wud.tag.include: '^\d+\.\d+\.\d+.*$'
          wud.tag.transform.type: "semver"
          wud.link.template: "https://hub.docker.com/r/louislam/dockge"
        cpu_shares: "{{ dockge_cpu_shares }}"
        memory: "{{ dockge_memory }}"
        restart_policy: unless-stopped

    - name: Access {{ ansible_nas_app_name }} at
      ansible.builtin.debug:
        msg: >-
              {{
                ['http://' + hostvars[inventory_hostname]['ansible_default_ipv4']['address'] + ':' + (dockge_port | string)] +
                (['https://' + dockge_hostname + '.' + ansible_nas_domain] if (dockge_available_externally is true or dockge_dockflare_tunnel is true) else [])
              }}
  when: dockge_enabled is true

- name: Stop {{ ansible_nas_app_name }}
  block:
    - name: Stop {{ ansible_nas_app_name }} Container
      community.docker.docker_container:
        name: "{{ dockge_container_name }}"
        state: absent
  when: dockge_enabled is false

- name: Data Archive {{ ansible_nas_app_name }}
  block:
    - name: Check for {{ ansible_nas_app_name }} Data Directory
      stat:
        path: "{{ dockge_data_directory }}"
      register: dir_stat

    - name: Archive {{ ansible_nas_app_name }} Data Directory
      ansible.builtin.archive:
        path: "{{ dockge_data_directory }}"
        dest: "{{ docker_home }}/{{ ansible_nas_app_name | lower }}.zip"
        force_archive: true
        format: zip
        owner: ansible-nas
        group: ansible-nas
        mode: u=rw,g=rw
        remove: true
      when: dir_stat.stat.exists
  when: dockge_enabled is false and archive_app_data_enabled is true
