---
- name: Start {{ ansible_nas_app_name }}
  block:
    - name: Create {{ ansible_nas_app_name }} Directories
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        owner: 1000
        group: 1000
      with_items:
        - "{{ node_red_data_directory }}"

    - name: Create {{ ansible_nas_app_name }} Container
      community.docker.docker_container:
        container_default_behavior: "compatibility"
        name: "{{ node_red_container_name }}"
        hostname: "{{ node_red_container_name }}"
        image: "{{ node_red_image_name }}:{{ node_red_image_tag }}"
        pull: true
        volumes:
          - "{{ node_red_data_directory }}:/data"
        ports:
          - "{{ node_red_port_http }}:1880"
        env:
          TZ: "{{ ansible_nas_timezone }}"
        labels:
          autoheal: "{{ node_red_autoheal }}"
          com.centurylinklabs.watchtower.enable: "{{ node_red_watchtower_enable }}"
          dockflare.enable: "{{ node_red_dockflare_tunnel }}"
          dockflare.access.group: "{{ node_red_dockflare_access_group }}"
          dockflare.hostname: "{{ node_red_hostname }}.{{ ansible_nas_domain }}"
          dockflare.service: "http://{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}:{{ node_red_port_http }}"
          homepage.name: "{{ ansible_nas_app_name }}"
          homepage.group: "{{ node_red_homepage_group }}"
          homepage.icon: "{{ node_red_homepage_icon }}"
          homepage.href: "{{ node_red_homepage_href }}"
          homepage.description: "{{ 'Low-code programming for event-driven applications' if homepage_show_description else omit }}"
          homepage.server: "my-docker"
          homepage.container: "{{ node_red_container_name }}"
          homepage.showStats: "{{ node_red_homepage_showstats }}"
          homepage.siteMonitor: "http://{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}:{{ node_red_port_http }}"
          repliqate.enabled: "{{ node_red_repliqate_enabled }}"
          repliqate.engine: "{{ node_red_repliqate_engine }}"
          repliqate.schedule: "{{ node_red_repliqate_schedule }}"
          repliqate.backup_id: "{{ node_red_repliqate_backup_id }}"
          repliqate.retention: "{{ node_red_repliqate_retention }}"
          traefik.enable: "{{ node_red_available_externally | string }}"
          traefik.http.routers.nodered.rule: "Host(`{{ node_red_hostname }}.{{ ansible_nas_domain }}`)"
          traefik.http.routers.nodered.tls.certresolver: "letsencrypt"
          traefik.http.routers.nodered.tls.domains[0].main: "{{ ansible_nas_domain }}"
          traefik.http.routers.nodered.tls.domains[0].sans: "*.{{ ansible_nas_domain }}"
          traefik.http.routers.nodered.middlewares: "nodered@docker{{ ',tinyauth-auth@docker' if node_red_tinyauth_enabled | bool else '' }}"
          traefik.http.middlewares.nodered.IPAllowList.sourcerange: "{{ node_red_traefik_whitelist }}"
          traefik.http.services.nodered.loadbalancer.server.port: "1880"
          wud.tag.include: '^\d+\.\d+\.\d+$'
          wud.tag.transform.type: "semver"
          wud.link.template: "https://github.com/node-red/node-red/pkgs/container/node-red"
        cpu_shares: "{{ node_red_cpu_shares }}"
        memory: "{{ node_red_memory }}"
        restart_policy: unless-stopped

    - name: Access {{ ansible_nas_app_name }} at
      ansible.builtin.debug:
        msg: >-
              {{
                ['http://' + hostvars[inventory_hostname]['ansible_default_ipv4']['address'] + ':' + (node_red_port_http | string)] +
                (['https://' + node_red_hostname + '.' + ansible_nas_domain] if (node_red_available_externally is true or node_red_dockflare_tunnel is true) else [])
              }}
  when: node_red_enabled is true

- name: Stop {{ ansible_nas_app_name }}
  block:
    - name: Stop {{ ansible_nas_app_name }} Container
      community.docker.docker_container:
        name: "{{ node_red_container_name }}"
        state: absent
  when: node_red_enabled is false

- name: Data Archive {{ ansible_nas_app_name }}
  include_role:
    name: ansible-nas-archive
  vars:
    target_data_dir: "{{ node_red_data_directory }}"
  when:
    - archive_app_data_enabled is true
    - node_red_enabled is false