---
# ANE
ansible_nas_app_name: "TiddlyWiki"
tiddlywiki_enabled: false
tiddlywiki_traefik_enabled: false
tiddlywiki_traefik_whitelist: "{{ lan }}"

# Data directory for config file
tiddlywiki_data_directory: "{{ docker_home }}/tiddlywiki"

# Basic auth
# tiddlywiki_username:
# tiddlywiki_password:

# Node low memory
# tiddlywiki_node_memory:

# Server debugging
# tiddlywiki_debug_level: none # full

# Networking
tiddlywiki_port_http: "8092"
tiddlywiki_hostname: "tiddlywiki"

# Container
tiddlywiki_container_name: "tiddlywiki"
tiddlywiki_image_name: "wmudge/tiddlywiki"
tiddlywiki_image_version: "latest"

# specs
tiddlywiki_cpu_shares: 1024
tiddlywiki_memory: "512M"

# autoheal
tiddlywiki_autoheal_enabled: false

# dockflare
tiddlywiki_dockflare_enabled: false
tiddlywiki_dockflare_access_group: ""

# homepage
tiddlywiki_homepage_group: "Apps"
tiddlywiki_homepage_icon: "tiddlywiki.png"
tiddlywiki_homepage_href: "http://{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}:{{ tiddlywiki_port_http }}"
tiddlywiki_homepage_showstats: false

# repliqate
tiddlywiki_repliqate_enabled: false
tiddlywiki_repliqate_engine: "restic"
tiddlywiki_repliqate_schedule: "@daily 3am"
tiddlywiki_repliqate_backup_id: "{{ tiddlywiki_container_name }}"
tiddlywiki_repliqate_retention: "30d"

# tinyauth
tiddlywiki_tinyauth_enabled: false

# watchtower
tiddlywiki_watchtower_enabled: false