---
# ANE
ansible_nas_app_name: "Immich"
immich_enabled: false
immich_available_externally: false
immich_traefik_whitelist: "{{ lan }}"

# directories
immich_data_directory: "{{ docker_home }}/immich"
immich_upload_directory: "{{ photos_root }}/immich"

# network
immich_port_http: "2283"
immich_hostname: "immich"
immich_network_name: "immich"

# app
immich_user_id: "1000"
immich_group_id: "1000"

# docker
immich_server_container_name: "immich-server"
immich_server_image: "ghcr.io/immich-app/immich-server"
immich_server_tag: "release"
immich_db_container_name: "immich-db"
immich_db_image: "ghcr.io/immich-app/postgres"
immich_db_tag: "14-vectorchord0.3.0-pgvectors0.2.0"
# For hardware acceleration, add one of -[armnn, cuda, openvino] to the image tag.
# Example tag: ${IMMICH_VERSION:-release}-cuda
immich_ml_container_name: "immich-machine-learning"
immich_ml_image: "ghcr.io/immich-app/immich-machine-learning"
immich_ml_tag: "release"
immich_redis_container_name: "immich-redis"
immich_redis_image: "redis"
immich_redis_tag: "6.2-alpine"

# specs
immich_server_cpu_shares: 1024
immich_server_memory: "1G"
immich_db_cpu_shares: 1024
immich_db_memory: "2G"
immich_ml_cpu_shares: 1024
immich_ml_memory: "1G"
immich_redis_cpu_shares: 1024
immich_redis_memory: "1G"

# database
immich_db_password: "postgres" # $(pwgen -s 40 1)
immich_db_username: "postgres"
immich_db_name: "immich_db"
immich_db_port: 5432
immich_db_storage_type: "SSD" # or "HDD"

# immich
immich_jwt_secret: "verylongandsecrettext"
immich_enable_mapbox: "false"
immich_mapbox_key: ""
immich_public_login_page_message: "Welcome to Immich!"
immich_ignore_mount_check_errors: "false"

# autoheal
immich_autoheal: "false"
immich_db_autoheal: "false"
immich_ml_autoheal: "false"
immich_redis_autoheal: "false"

# dockflare
immich_dockflare_tunnel: "false"
immich_dockflare_access_group: ""

# homepage
immich_homepage_group: "Apps"
immich_homepage_icon: "immich.png"
immich_homepage_href: "http://{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}:{{ immich_port_http }}"
immich_homepage_showstats: "false"
immich_homepage_widget_key: "your_admin_api_key"
immich_db_homepage_group: "DBs"
immich_db_homepage_icon: "postgres.png"
immich_db_homepage_showstats: "false"
immich_ml_homepage_group: "Misc"
immich_ml_homepage_icon: "immich.png"
immich_ml_homepage_showstats: "false"
immich_redis_homepage_group: "DBs"
immich_redis_homepage_icon: "redis.png"
immich_redis_homepage_showstats: "false"

# repliqate
immich_server_repliqate_enabled: "false"
immich_server_repliqate_engine: "restic"
immich_server_repliqate_schedule: "@daily 3am"
immich_server_repliqate_backup_id: "{{ immich_server_container_name }}"
immich_server_repliqate_retention: "30d"
immich_db_repliqate_enabled: "false"
immich_db_repliqate_engine: "restic"
immich_db_repliqate_schedule: "@daily 3am"
immich_db_repliqate_backup_id: "{{ immich_db_container_name }}"
immich_db_repliqate_retention: "30d"
immich_ml_repliqate_enabled: "false"
immich_ml_repliqate_engine: "restic"
immich_ml_repliqate_schedule: "@daily 3am"
immich_ml_repliqate_backup_id: "{{ immich_ml_container_name }}"
immich_ml_repliqate_retention: "30d"

# tinyauth
immich_tinyauth_enabled: false

# watchtower
immich_watchtower_enable: "false"