---
- name: Start {{ ansible_nas_app_name }}
  block:
    - name: Create {{ ansible_nas_app_name }} Directory
      file:
        path: "{{ item }}"
        state: directory
      with_items:
        - "{{ flood_data_directory }}/config"

    - name: Create {{ ansible_nas_app_name }} Container
      community.docker.docker_container:
        container_default_behavior: "compatibility"
        name: "{{ flood_container_name }}"
        hostname: "{{ flood_container_name }}"
        image: "{{ flood_image_name }}:{{ flood_image_tag }}"
        pull: true
        volumes:
          - "{{ flood_data_directory }}/date:/date:rw"
        ports:
          - "{{ flood_port_http }}:3000"
        env:
          TZ: "{{ ansible_nas_timezone }}"
        labels:
          autoheal: "{{ flood_autoheal }}"
          com.centurylinklabs.watchtower.enable: "{{ flood_watchtower_enable }}"
          dockflare.enable: "{{ flood_dockflare_tunnel }}"
          dockflare.access.group: "{{ flood_dockflare_access_group }}"
          dockflare.hostname: "{{ flood_hostname }}.{{ ansible_nas_domain }}"
          dockflare.service: "http://{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}:{{ flood_port_http }}"
          homepage.name: "{{ ansible_nas_app_name }}"
          homepage.group: "{{ flood_homepage_group }}"
          homepage.icon: "{{ flood_homepage_icon }}"
          homepage.href: "{{ flood_homepage_href }}"
          homepage.siteMonitor: "http://{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}:{{ flood_port_http }}"
          homepage.description: "{{ 'A modern web UI for various torrent clients with a Node.js backend and React frontend.' if homepage_show_description else omit }}"
          homepage.server: "my-docker"
          homepage.container: "{{ flood_container_name }}"
          homepage.showStats: "{{ flood_homepage_showstats }}"
          homepage.widget.type: "flood"
          homepage.widget.url: "http://{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}:{{ flood_port_http }}"
          homepage.widget.username: "{{ flood_homepage_widget_username }}"
          homepage.widget.password: "{{ flood_homepage_widget_password }}"
          traefik.enable: "{{ flood_available_externally | string }}"
          traefik.http.routers.flood.rule: "Host(`flood.{{ ansible_nas_domain }}`)"
          traefik.http.routers.flood.tls.certresolver: "letsencrypt"
          traefik.http.routers.flood.tls.domains[0].main: "{{ ansible_nas_domain }}"
          traefik.http.routers.flood.tls.domains[0].sans: "*.{{ ansible_nas_domain }}"
          traefik.http.routers.frontend.middlewares: "{{ flood_hostname }}"
          traefik.http.routers.flood.middlewares: "{{ flood_hostname }}@docker"
          traefik.http.middlewares.flood.IPAllowList.sourcerange: "{{ flood_traefik_whitelist }}"
          traefik.http.services.flood.loadbalancer.server.port: "3000"
          wud.tag.include: '^\d+\.\d+\.\d+.*$'
          wud.tag.transform.type: "semver"
          wud.link.template: "https://hub.docker.com/r/jesec/flood"
        cpu_shares: "{{ flood_cpu_shares }}"
        memory: "{{ flood_memory }}"
        restart_policy: unless-stopped

    - name: Access {{ ansible_nas_app_name }} at
      ansible.builtin.debug:
        msg: >-
              {{
                ['http://' + hostvars[inventory_hostname]['ansible_default_ipv4']['address'] + ':' + (flood_port_http | string)] +
                (['https://' + flood_hostname + '.' + ansible_nas_domain] if (flood_available_externally is true or flood_dockflare_tunnel is true) else [])
              }}
  when: flood_enabled is true

- name: Stop {{ ansible_nas_app_name }}
  block:
    - name: Stop {{ ansible_nas_app_name }} Container
      community.docker.docker_container:
        name: "{{ flood_container_name }}"
        state: absent
  when: flood_enabled is false

- name: Data Archive {{ ansible_nas_app_name }}
  block:
    - name: Check for {{ ansible_nas_app_name }} Data Directory
      stat:
        path: "{{ flood_data_directory }}"
      register: dir_stat

    - name: Archive {{ ansible_nas_app_name }} Data Directory
      ansible.builtin.archive:
        path: "{{ flood_data_directory }}"
        dest: "{{ docker_home }}/{{ ansible_nas_app_name | lower }}.zip"
        force_archive: true
        format: zip
        owner: ansible-nas
        group: ansible-nas
        mode: u=rw,g=rw
        remove: true
      when: dir_stat.stat.exists
  when: flood_enabled is false and archive_app_data_enabled is true
