---
- name: Start {{ ansible_nas_app_name }}
  block:
    - name: Create {{ ansible_nas_app_name }} Directories
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
      with_items:
        - "{{ pihole_data_directory }}"
        - "{{ pihole_data_directory }}/etc-pihole"
        - "{{ pihole_data_directory }}/etc-dnsmasq.d"

    - name: Set {{ ansible_nas_app_name }} FQDN var overrides
      ansible.builtin.set_fact:
        pihole_homepage_href: "https://{{ pihole_hostname }}.{{ ansible_nas_domain }}/admin"
      when: pihole_traefik_enabled | bool or pihole_dockflare_enabled | bool

    - name: Disable systemd-resolved StubListener
      ansible.builtin.lineinfile:
        path: /etc/systemd/resolved.conf
        regexp: '^#?DNSStubListener='
        line: 'DNSStubListener=no'
        state: present
      register: resolved_conf_update

    - name: Update resolv.conf symlink
      ansible.builtin.file:
        src: /run/systemd/resolve/resolv.conf
        dest: /etc/resolv.conf
        state: link
        force: true

    - name: Restart systemd-resolved
      ansible.builtin.systemd_service:
        name: systemd-resolved
        state: restarted
      when: resolved_conf_update.changed

    - name: Create {{ ansible_nas_app_name }} Container
      community.docker.docker_container:
        container_default_behavior: "compatibility"
        name: "{{ pihole_container_name }}"
        hostname: "{{ pihole_container_name }}"
        image: "{{ pihole_image_name }}:{{ pihole_image_tag }}"
        pull: true
        dns_servers: "{{ pihole_dns }}"
        ports:
          - "{{ pihole_port_http }}:80"
          - "53:53/udp"
          - "53:53/tcp"
          - "67:67/udp"
          - "123:123/udp"
        volumes:
          - "{{ pihole_data_directory }}/etc-dnsmasq.d:/etc/dnsmasq.d"
          - "{{ pihole_data_directory }}/etc-pihole:/etc/pihole"
        env:
          ADDITIONAL_PACKAGES: "{{ pihole_env_additional_packages }}"
          FTLCONF_dns_listeningMode: 'all'
          FTLCONF_webserver_api_password: "{{ pihole_env_ftlconf_webserver_api_password }}"
          PIHOLE_UID: "{{ pihole_user_id }}"
          PIHOLE_GID: "{{ pihole_group_id }}"
          TZ: "{{ ansible_nas_timezone }}"
        capabilities:
          - NET_ADMIN
          - SYS_TIME
          - SYS_NICE
        labels:
          autoheal: "{{ pihole_autoheal_enabled | ternary('true', 'false') }}"
          com.centurylinklabs.watchtower.enable: "{{ pihole_watchtower_enabled | ternary('true', 'false') }}"
          dockflare.enable: "{{ pihole_dockflare_enabled | ternary('true', 'false') }}"
          dockflare.access.group: "{{ pihole_dockflare_access_group }}"
          dockflare.hostname: "{{ pihole_hostname }}.{{ ansible_nas_domain }}"
          dockflare.service: "http://{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}:{{ pihole_port_http }}"
          homepage.name: "{{ ansible_nas_app_name }}"
          homepage.group: "{{ pihole_homepage_group }}"
          homepage.icon: "{{ pihole_homepage_icon }}"
          homepage.href: "{{ pihole_homepage_href }}"
          homepage.description: "{{ 'Network-wide Ad Blocking' if homepage_show_description else omit }}"
          homepage.server: "my-docker"
          homepage.container: "{{ pihole_container_name }}"
          homepage.showStats: "{{ pihole_homepage_showstats | ternary('true', 'false') }}"
          homepage.siteMonitor: "http://{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}:{{ pihole_port_http }}"
          homepage.widget.type: "pihole"
          homepage.widget.url: "http://{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}:{{ pihole_port_http }}"
          homepage.widget.version: "6"
          homepage.widget.key: "{{ pihole_homepage_widget_key }}"
          repliqate.enabled: "{{ pihole_repliqate_enabled | ternary('true', 'false') }}"
          repliqate.engine: "{{ pihole_repliqate_engine }}"
          repliqate.schedule: "{{ pihole_repliqate_schedule }}"
          repliqate.backup_id: "{{ pihole_repliqate_backup_id }}"
          repliqate.retention: "{{ pihole_repliqate_retention }}"
          traefik.enable: "{{ pihole_traefik_enabled | ternary('true', 'false') }}"
          traefik.http.routers.pihole.rule: "Host(`{{ pihole_hostname }}.{{ ansible_nas_domain }}`)"
          traefik.http.routers.pihole.tls.certresolver: "letsencrypt"
          traefik.http.routers.pihole.tls.domains[0].main: "{{ ansible_nas_domain }}"
          traefik.http.routers.pihole.tls.domains[0].sans: "*.{{ ansible_nas_domain }}"
          traefik.http.routers.pihole.middlewares: "pihole@docker{{ ',tinyauth-auth@docker' if pihole_tinyauth_enabled | bool else '' }}"
          traefik.http.middlewares.pihole.IPAllowList.sourcerange: "{{ pihole_traefik_whitelist }}"
          traefik.http.services.pihole.loadbalancer.server.port: "80"
          wud.tag.include: '^\d+\.\d+\.\d+.*$'
          wud.tag.transform.type: "semver"
          wud.link.template: "https://hub.docker.com/r/pihole/pihole"
        cpu_shares: "{{ pihole_cpu_shares }}"
        memory: "{{ pihole_memory }}"
        restart_policy: unless-stopped

    - name: Access {{ ansible_nas_app_name }} at
      ansible.builtin.debug:
        msg: >-
              {{
                ['http://' + hostvars[inventory_hostname]['ansible_default_ipv4']['address'] + ':' + (pihole_port_http | string) + '/admin'] +
                (['https://' + pihole_hostname + '.' + ansible_nas_domain + '/admin'] if (pihole_traefik_enabled is true or pihole_dockflare_enabled is true) else [])
              }}
  when: pihole_enabled is true

- name: Stop {{ ansible_nas_app_name }}
  block:
    - name: Stop {{ ansible_nas_app_name }} Container
      community.docker.docker_container:
        name: "{{ pihole_container_name }}"
        state: absent

    - name: Re-enable systemd-resolved StubListener
      ansible.builtin.lineinfile:
        path: /etc/systemd/resolved.conf
        regexp: '^#?DNSStubListener='
        line: 'DNSStubListener=yes'
        state: present
      register: resolved_conf_revert

    - name: Restore default resolv.conf symlink
      ansible.builtin.file:
        src: /run/systemd/resolve/stub-resolv.conf
        dest: /etc/resolv.conf
        state: link
        force: true

    - name: Restart systemd-resolved
      ansible.builtin.systemd_service:
        name: systemd-resolved
        state: restarted
      when: resolved_conf_revert.changed
  when: pihole_enabled is false

- name: Data Archive {{ ansible_nas_app_name }}
  include_role:
    name: ansible-nas-archive
  vars:
    target_data_dir: "{{ pihole_data_directory }}"
  when:
    - archive_app_data_enabled is true
    - pihole_enabled is false