---
- name: Start {{ ansible_nas_app_name }}
  block:
    - name: Create {{ ansible_nas_app_name }} Directories
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
      with_items:
        - "{{ tianji_data_directory }}"
        - "{{ tianji_data_directory }}/db"

    - name: Set {{ ansible_nas_app_name }} FQDN var overrides
      ansible.builtin.set_fact:
        tianji_homepage_href: "https://{{ tianji_hostname }}.{{ ansible_nas_domain }}"
      when: tianji_traefik_enabled | bool or tianji_dockflare_enabled | bool

    - name: Create {{ ansible_nas_app_name }} DB Container
      community.docker.docker_container:
        container_default_behavior: "compatibility"
        name: "{{ tianji_db_container_name }}"
        hostname: "{{ tianji_db_container_name }}"
        image: "{{ tianji_db_image_name }}:{{ tianji_db_image_tag }}"
        pull: true
        volumes:
          - "{{ tianji_data_directory }}/db:/var/lib/postgresql/data"
        env:
          POSTGRES_USER: "tianji"
          POSTGRES_PASSWORD: "tianji"
          POSTGRES_DB: "tianji"
          TZ: "{{ ansible_nas_timezone }}"
        healthcheck:
          test: ["CMD-SHELL", "pg_isready -U tianji -d tianji"]
          interval: "5s"
          timeout: "5s"
          retries: "5"
        labels:
          autoheal: "{{ tianji_db_autoheal_enabled | ternary('true', 'false') }}"
          com.centurylinklabs.watchtower.enable: "{{ tianji_db_watchtower_enabled | ternary('true', 'false') }}"
          dockflare.enable: "false"
          homepage.name: "{{ ansible_nas_app_name }} PostgreSQL"
          homepage.group: "{{ tianji_db_homepage_group }}"
          homepage.icon: "{{ tianji_db_homepage_icon }}"
          homepage.href: "{{ tianji_homepage_href }}"
          homepage.description: "{{ 'PostgreSQL Database Management System' if homepage_show_description else omit }}"
          homepage.server: "my-docker"
          homepage.container: "{{ tianji_db_container_name }}"
          homepage.showStats: "{{ tianji_homepage_showstats | ternary('true', 'false') }}"
          repliqate.enabled: "{{ tianji_db_repliqate_enabled | ternary('true', 'false') }}"
          repliqate.engine: "{{ tianji_db_repliqate_engine }}"
          repliqate.schedule: "{{ tianji_db_repliqate_schedule }}"
          repliqate.backup_id: "{{ tianji_db_repliqate_backup_id }}"
          repliqate.retention: "{{ tianji_db_repliqate_retention }}"
          traefik.enable: "false"
          wud.tag.include: '^16\.\d+(\.\d+)?-alpine.*$'
          wud.tag.transform.type: "semver"
          wud.link.template: "https://hub.docker.com/_/postgres"
        cpu_shares: "{{ tianji_db_cpu_shares }}"
        memory: "{{ tianji_db_memory }}"
        memory_swap: "{{ tianji_db_memory_swap }}"
        restart_policy: unless-stopped

    - name: Wait for {{ ansible_nas_app_name }} DB to become healthy
      community.docker.docker_container_info:
        name: "{{ tianji_db_container_name }}"
      register: db_info
      until: "db_info.container.State.Health.Status == 'healthy'"
      retries: 30
      delay: 5

    - name: Create {{ ansible_nas_app_name }} Container
      community.docker.docker_container:
        container_default_behavior: "compatibility"
        name: "{{ tianji_container_name }}"
        hostname: "{{ tianji_container_name }}"
        image: "{{ tianji_image_name }}:{{ tianji_image_tag }}"
        pull: true
        ports:
          - "{{ tianji_port_http }}:12345"
        env:
          DATABASE_URL: "postgresql://tianji:tianji@{{ tianji_db_container_name }}:5432/tianji"
          JWT_SECRET: "{{ tianji_env_jwt_secret }}"
          ALLOW_REGISTER: "{{ tianji_env_allow_register }}"
          ALLOW_OPENAPI: "{{ tianji_env_allow_openapi }}"
          OPENAI_API_KEY: "{{ tianji_env_openapi_key }}"
          PUBLIC_URL: "{{ tianji_env_public_url }}"
          TZ: "{{ ansible_nas_timezone }}"
        links:
          - "{{ tianji_db_container_name }}"
        labels:
          autoheal: "{{ tianji_autoheal_enabled | ternary('true', 'false') }}"
          com.centurylinklabs.watchtower.enable: "{{ tianji_watchtower_enabled | ternary('true', 'false') }}"
          dockflare.enable: "{{ tianji_dockflare_enabled | ternary('true', 'false') }}"
          dockflare.access.group: "{{ tianji_dockflare_access_group }}"
          dockflare.hostname: "{{ tianji_hostname }}.{{ ansible_nas_domain }}"
          dockflare.service: "http://{{ hostvars[inventory_hostname]['ansible_facts']['default_ipv4']['address'] }}:{{ tianji_port_http }}"
          homepage.name: "{{ ansible_nas_app_name }}"
          homepage.group: "{{ tianji_homepage_group }}"
          homepage.icon: "{{ tianji_homepage_icon }}"
          homepage.href: "{{ tianji_homepage_href }}"
          homepage.siteMonitor: "http://{{ hostvars[inventory_hostname]['ansible_facts']['default_ipv4']['address'] }}:{{ tianji_port_http }}"
          homepage.description: "{{ 'Tianji: Insight into everything, Website Analytics + Uptime Monitor + Server Status. not only another GA alternatives' if homepage_show_description else omit }}"
          homepage.server: "my-docker"
          homepage.container: "{{ tianji_container_name }}"
          homepage.showStats: "{{ tianji_homepage_showstats | ternary('true', 'false') }}"
          repliqate.enabled: "{{ tianji_repliqate_enabled | ternary('true', 'false') }}"
          repliqate.engine: "{{ tianji_repliqate_engine }}"
          repliqate.schedule: "{{ tianji_repliqate_schedule }}"
          repliqate.backup_id: "{{ tianji_repliqate_backup_id }}"
          repliqate.retention: "{{ tianji_repliqate_retention }}"
          traefik.enable: "{{ tianji_traefik_enabled | ternary('true', 'false') }}"
          traefik.http.routers.tianji.rule: "Host(`{{ tianji_hostname }}.{{ ansible_nas_domain }}`)"
          traefik.http.routers.tianji.tls.certresolver: "letsencrypt"
          traefik.http.routers.tianji.tls.domains[0].main: "{{ ansible_nas_domain }}"
          traefik.http.routers.tianji.tls.domains[0].sans: "*.{{ ansible_nas_domain }}"
          traefik.http.routers.tianji.middlewares: "tianji@docker{{ ',tinyauth-auth@docker' if tianji_tinyauth_enabled | bool else '' }}"
          traefik.http.middlewares.tianji.IPAllowList.sourcerange: "{{ tianji_traefik_whitelist }}"
          traefik.http.services.tianji.loadbalancer.server.port: "12345"
          wud.tag.include: '^v\d+\.\d+\.\d+$'
          wud.tag.transform.type: "semver"
          wud.link.template: "https://github.com/msgbyte/tianji/pkgs/container/tianji"
        cpu_shares: "{{ tianji_cpu_shares }}"
        memory: "{{ tianji_memory }}"
        memory_swap: "{{ tianji_memory_swap }}"
        restart_policy: unless-stopped

    - name: Access {{ ansible_nas_app_name }} at
      ansible.builtin.debug:
        msg: >-
              {{
                ['http://' + hostvars[inventory_hostname]['ansible_facts']['default_ipv4']['address'] + ':' + (tianji_port_http | string)] +
                (['https://' + tianji_hostname + '.' + ansible_nas_domain] if (tianji_traefik_enabled is true or tianji_dockflare_enabled is true) else [])
              }}
  when: tianji_enabled is true

- name: Stop {{ ansible_nas_app_name }}
  block:
    - name: Stop {{ ansible_nas_app_name }} Container
      community.docker.docker_container:
        name: "{{ tianji_container_name }}"
        state: absent

    - name: Stop {{ ansible_nas_app_name }} DB Container
      community.docker.docker_container:
        name: "{{ tianji_db_container_name }}"
        state: absent
  when: tianji_enabled is false

- name: Data Archive {{ ansible_nas_app_name }}
  include_role:
    name: ansible-nas-archive
  vars:
    target_data_dir: "{{ tianji_data_directory }}"
  when:
    - archive_app_data_enabled is true
    - tianji_enabled is false