---
- name: Start {{ ansible_nas_app_name }}
  block:
    - name: Create {{ ansible_nas_app_name }} Container
      community.docker.docker_container:
        container_default_behavior: "compatibility"
        name: "{{ cloudflared_container_name }}"
        hostname: "{{ cloudflared_container_name }}"
        image: "{{ cloudflared_image_name }}:{{ cloudflared_image_tag }}"
        pull: true
        network_mode: "bridge"
        cpu_shares: "{{ cloudflared_cpu_shares }}"
        command: "tunnel --no-autoupdate run --token {{ cloudflared_token }}"
        env:
          TZ: "{{ ansible_nas_timezone }}"
        labels:
          autoheal: "{{ cloudflared_autoheal }}"
          com.centurylinklabs.watchtower.monitor-only: "{{ cloudflared_watchtower_monitor_only }}"
          homepage.group: "{{ cloudflared_homepage_group }}"
          homepage.name: "{{ ansible_nas_app_name }}"
          homepage.icon: "{{ cloudflared_homepage_icon }}"
          homepage.href: "https://dash.cloudflare.com/login"
          homepage.description: "{{ 'Client for Cloudflare Tunnel, a daemon that exposes private services through the Cloudflare edge.' if homepage_show_description else omit }}"
          homepage.server: "my-docker"
          homepage.container: "{{ cloudflared_container_name }}"
          homepage.showStats: "{{ cloudflared_homepage_showStats }}"
          homepage.widget.type: "cloudflared"
          homepage.widget.accountid: "{{ cloudflared_homepage_widget_accountid }}"
          homepage.widget.tunnelid: "{{ cloudflared_homepage_widget_tunnelid }}"
          homepage.widget.key: "{{ cloudflared_homepage_widget_key }}"
          traefik.enable: "false"
          wud.tag.include: '^\d+\.\d+\.\d+$$'
          wud.link.template: "https://github.com/cloudflare/cloudflared/releases/tag/$${major}.$${minor}.$${patch}"
        memory: "{{ cloudflared_memory }}"
        restart_policy: unless-stopped
  when: cloudflared_enabled is true

- name: Stop {{ ansible_nas_app_name }}
  block:
    - name: Stop {{ ansible_nas_app_name }} Container
      community.docker.docker_container:
        name: "{{ cloudflared_container_name }}"
        state: absent
  when: cloudflared_enabled is false
